# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(purchaseAmount = 100) == 0
    assert candidate(purchaseAmount = 85) == 10
    assert candidate(purchaseAmount = 15) == 80
    assert candidate(purchaseAmount = 10) == 90
    assert candidate(purchaseAmount = 45) == 50
    assert candidate(purchaseAmount = 51) == 50
    assert candidate(purchaseAmount = 34) == 70
    assert candidate(purchaseAmount = 0) == 100
    assert candidate(purchaseAmount = 60) == 40
    assert candidate(purchaseAmount = 25) == 70
    assert candidate(purchaseAmount = 9) == 90
    assert candidate(purchaseAmount = 75) == 20
    assert candidate(purchaseAmount = 50) == 50
    assert candidate(purchaseAmount = 55) == 40
    assert candidate(purchaseAmount = 99) == 0
    assert candidate(purchaseAmount = 31) == 70
    assert candidate(purchaseAmount = 27) == 70
    assert candidate(purchaseAmount = 22) == 80
    assert candidate(purchaseAmount = 35) == 60
    assert candidate(purchaseAmount = 1) == 100
    assert candidate(purchaseAmount = 7) == 90
    assert candidate(purchaseAmount = 49) == 50
    assert candidate(purchaseAmount = 28) == 70
    assert candidate(purchaseAmount = 11) == 90
    assert candidate(purchaseAmount = 26) == 70
    assert candidate(purchaseAmount = 65) == 30
    assert candidate(purchaseAmount = 90) == 10
    assert candidate(purchaseAmount = 69) == 30
    assert candidate(purchaseAmount = 84) == 20
    assert candidate(purchaseAmount = 91) == 10
    assert candidate(purchaseAmount = 29) == 70
    assert candidate(purchaseAmount = 67) == 30
    assert candidate(purchaseAmount = 23) == 80
    assert candidate(purchaseAmount = 59) == 40
    assert candidate(purchaseAmount = 63) == 40
    assert candidate(purchaseAmount = 4) == 100
    assert candidate(purchaseAmount = 38) == 60
    assert candidate(purchaseAmount = 6) == 90
    assert candidate(purchaseAmount = 5) == 90
    assert candidate(purchaseAmount = 79) == 20
    assert candidate(purchaseAmount = 74) == 30
    assert candidate(purchaseAmount = 47) == 50
    assert candidate(purchaseAmount = 77) == 20
    assert candidate(purchaseAmount = 39) == 60
    assert candidate(purchaseAmount = 2) == 100
    assert candidate(purchaseAmount = 8) == 90
    assert candidate(purchaseAmount = 95) == 0
    assert candidate(purchaseAmount = 14) == 90
    assert candidate(purchaseAmount = 94) == 10
    assert candidate(purchaseAmount = 30) == 70
    assert candidate(purchaseAmount = 89) == 10
    assert candidate(purchaseAmount = 3) == 100
    assert candidate(purchaseAmount = 19) == 80
    assert candidate(purchaseAmount = 82) == 20
