# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abcd",goal = "dcba") == False
    assert candidate(s = "xyy",goal = "xyx") == False
    assert candidate(s = "abac",goal = "abad") == False
    assert candidate(s = "aa",goal = "aa") == True
    assert candidate(s = "abcde",goal = "edcba") == False
    assert candidate(s = "aaaa",goal = "aaaa") == True
    assert candidate(s = "abab",goal = "abab") == True
    assert candidate(s = "ab",goal = "ab") == False
    assert candidate(s = "xyz",goal = "zyx") == True
    assert candidate(s = "aabbcc",goal = "ccbbaa") == False
    assert candidate(s = "abcd",goal = "cbad") == True
    assert candidate(s = "abcd",goal = "abdc") == True
    assert candidate(s = "xy",goal = "yx") == True
    assert candidate(s = "aabbcc",goal = "aabbcc") == True
    assert candidate(s = "abcde",goal = "abced") == True
    assert candidate(s = "ab",goal = "bba") == False
    assert candidate(s = "abcd",goal = "abcd") == False
    assert candidate(s = "abab",goal = "baba") == False
    assert candidate(s = "xx",goal = "xx") == True
    assert candidate(s = "aba",goal = "aba") == True
    assert candidate(s = "abcde",goal = "abcde") == False
    assert candidate(s = "abc",goal = "acb") == True
    assert candidate(s = "ab",goal = "ba") == True
    assert candidate(s = "abcdefghij",goal = "bacdefghij") == True
    assert candidate(s = "abcdefghi",goal = "abcdefghj") == False
    assert candidate(s = "xyzabc",goal = "zyxabc") == True
    assert candidate(s = "aabbccddeeff",goal = "aabbccdeeff") == False
    assert candidate(s = "abcabcabcabc",goal = "abcabcabcaba") == False
    assert candidate(s = "abacabad",goal = "abacabad") == True
    assert candidate(s = "aabbccdd",goal = "aabbcccc") == False
    assert candidate(s = "xyzz",goal = "zzyx") == False
    assert candidate(s = "aabb",goal = "bbaa") == False
    assert candidate(s = "xyzz",goal = "zzxy") == False
    assert candidate(s = "xyzzxyzz",goal = "zzxyzzxy") == False
    assert candidate(s = "abacab",goal = "babaab") == False
    assert candidate(s = "abcdefgh",goal = "efabcdgh") == False
    assert candidate(s = "abcdabcdabcd",goal = "abcdabcdabcd") == True
    assert candidate(s = "abcabcabc",goal = "abcabcabc") == True
    assert candidate(s = "abcaa",goal = "acbaa") == True
    assert candidate(s = "abcabcabc",goal = "abcabcbac") == True
    assert candidate(s = "aabbcc",goal = "abcabc") == False
    assert candidate(s = "aaaaaaa",goal = "aaaaaaa") == True
    assert candidate(s = "mississippi",goal = "ssimmisippi") == False
    assert candidate(s = "abcdefgh",goal = "abcdefgh") == False
    assert candidate(s = "aabbc",goal = "aabcb") == True
    assert candidate(s = "abcdefghi",goal = "abcdefghij") == False
    assert candidate(s = "aabbcc",goal = "aaccbb") == False
    assert candidate(s = "abracadabra",goal = "abracadabra") == True
    assert candidate(s = "aabbaa",goal = "aabbba") == False
    assert candidate(s = "aabbccddeeff",goal = "bbaaddeeccff") == False
    assert candidate(s = "abcdefghij",goal = "abcdefghij") == False
    assert candidate(s = "xyzz",goal = "zzxz") == False
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",goal = "abcdefghijklmnopqrstuvwxzy") == True
    assert candidate(s = "abacabad",goal = "abacabda") == True
    assert candidate(s = "mississippi",goal = "misssipii") == False
    assert candidate(s = "xyzz",goal = "yxzz") == True
    assert candidate(s = "aabbccddeeff",goal = "bbaaddeeffcc") == False
    assert candidate(s = "abcdef",goal = "fedcba") == False
    assert candidate(s = "xyzz",goal = "zyzz") == False
    assert candidate(s = "abcab",goal = "abcab") == True
    assert candidate(s = "mississippi",goal = "mpississii") == False
    assert candidate(s = "aabbccdd",goal = "aabbccdd") == True
    assert candidate(s = "abcabcabc",goal = "cbaabcabc") == True
    assert candidate(s = "abcdabcd",goal = "abcdabcd") == True
    assert candidate(s = "abac",goal = "acba") == False
    assert candidate(s = "aabbccddeeff",goal = "ffeeddccbbaa") == False
    assert candidate(s = "aabb",goal = "abab") == True
    assert candidate(s = "aabbccddeeffgg",goal = "aabbcdddeeffgg") == False
    assert candidate(s = "xyzxyz",goal = "zyxzyx") == False
    assert candidate(s = "xyzxyzxyz",goal = "zyxzyxzyx") == False
    assert candidate(s = "a",goal = "a") == False
    assert candidate(s = "abcdef",goal = "abdefc") == False
    assert candidate(s = "abccba",goal = "bacbca") == False
    assert candidate(s = "abcabcabc",goal = "bacbacbac") == False
    assert candidate(s = "xyzz",goal = "zyzx") == True
    assert candidate(s = "abcdefg",goal = "gfedcba") == False
    assert candidate(s = "abac",goal = "abca") == True
    assert candidate(s = "aabbccddeeff",goal = "aabbccddffee") == False
    assert candidate(s = "abcdexyz",goal = "abcdefyz") == False
    assert candidate(s = "abacaxbada",goal = "abacaxbada") == True
    assert candidate(s = "aabcc",goal = "acaab") == False
    assert candidate(s = "aabbccddeeffgg",goal = "aabbccddeeffgg") == True
    assert candidate(s = "xyzz",goal = "zyxz") == True
    assert candidate(s = "abcdeabcde",goal = "abcdeabcde") == True
    assert candidate(s = "abcdefgh",goal = "efghabcd") == False
    assert candidate(s = "xyzz",goal = "xyzz") == True
    assert candidate(s = "abcabcabc",goal = "bcaabcabc") == False
    assert candidate(s = "xyxyxyxyxy",goal = "yxyxyxyxyx") == False
    assert candidate(s = "abcdefghij",goal = "abcdefghik") == False
    assert candidate(s = "abababab",goal = "babababa") == False
    assert candidate(s = "abcdef",goal = "fabcde") == False
    assert candidate(s = "ababab",goal = "bababa") == False
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",goal = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == True
    assert candidate(s = "aaaabbbbcccc",goal = "ccccaaaabbbb") == False
    assert candidate(s = "aab",goal = "aba") == True
    assert candidate(s = "aabbc",goal = "aacbb") == True
    assert candidate(s = "xyzz",goal = "zzzx") == False
    assert candidate(s = "zzzzzzzz",goal = "zzzzzzzz") == True
    assert candidate(s = "abcdefghij",goal = "abcdefghji") == True
    assert candidate(s = "abcdeabcde",goal = "abcdebacde") == True
    assert candidate(s = "abcdefg",goal = "abcdefg") == False
    assert candidate(s = "abacabadabacaba",goal = "abacabadabacabb") == False
    assert candidate(s = "mississippi",goal = "mississippi") == True
    assert candidate(s = "abcdxy",goal = "abcdyx") == True
    assert candidate(s = "abcdexyz",goal = "xyzabcdexyz") == False
    assert candidate(s = "xyzz",goal = "zyyz") == False
    assert candidate(s = "abcabcabc",goal = "cbacbacba") == False
    assert candidate(s = "aabbccddeeff",goal = "aabbccddfeef") == True
    assert candidate(s = "aabbccddeeff",goal = "aabbccdeeef") == False
    assert candidate(s = "abacabadabacaba",goal = "babacabadabacab") == False
    assert candidate(s = "aabbccddeeff",goal = "aabbccddeeff") == True
    assert candidate(s = "aabbccddeeff",goal = "aabbccddeffg") == False
    assert candidate(s = "aabbb",goal = "bbaaa") == False
    assert candidate(s = "mississippi",goal = "mississipp") == False
    assert candidate(s = "abacabadabacaba",goal = "abacabadabacaba") == True
    assert candidate(s = "abcabcabcabc",goal = "abcabcabcabc") == True
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",goal = "zzxxwwvvuuttsrqponmlkjihgfedcbaabbccddeeffgg") == False
    assert candidate(s = "abcdabcd",goal = "dcbaabcd") == False
    assert candidate(s = "aabbccdd",goal = "bbaaddcc") == False
    assert candidate(s = "abcdefgh",goal = "hgfedcba") == False
    assert candidate(s = "abacaba",goal = "abacaba") == True
    assert candidate(s = "abcxy",goal = "abcyx") == True
    assert candidate(s = "abcdefgh",goal = "abcdefhg") == True
    assert candidate(s = "abacabad",goal = "abacabdc") == False
    assert candidate(s = "aaaaaa",goal = "aaaaaa") == True
    assert candidate(s = "abcdefghij",goal = "aibcdefghj") == False
