# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abc",t = "abc",k = 0) == True
    assert candidate(s = "aaa",t = "zzz",k = 702) == True
    assert candidate(s = "abc",t = "bcd",k = 10) == False
    assert candidate(s = "abc",t = "xyz",k = 702) == True
    assert candidate(s = "abcd",t = "pqrs",k = 100) == True
    assert candidate(s = "zzz",t = "aaa",k = 78) == True
    assert candidate(s = "abcd",t = "pqrs",k = 78) == False
    assert candidate(s = "aaa",t = "abc",k = 3) == True
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "bcdefghijklmnopqrstuvwxyza",k = 25) == False
    assert candidate(s = "zzz",t = "aaa",k = 25) == False
    assert candidate(s = "aab",t = "bbb",k = 27) == True
    assert candidate(s = "a",t = "z",k = 25) == True
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "abcdefghijklmnopqrstuvwxyz",k = 0) == True
    assert candidate(s = "input",t = "ouput",k = 9) == True
    assert candidate(s = "repeatedchars",t = "sfpqeueftdsft",k = 150) == True
    assert candidate(s = "zzzzz",t = "aaaaa",k = 122) == True
    assert candidate(s = "aaaaaaaaaa",t = "zzzzzzzzzz",k = 260) == True
    assert candidate(s = "abcde",t = "edcba",k = 155) == True
    assert candidate(s = "wraparound",t = "xqcsbpsboe",k = 150) == True
    assert candidate(s = "abcdef",t = "fedcba",k = 50) == True
    assert candidate(s = "z",t = "a",k = 1) == True
    assert candidate(s = "xylophone",t = "xylophone",k = 1) == True
    assert candidate(s = "testcase",t = "testcase",k = 0) == True
    assert candidate(s = "pqrs",t = "abcd",k = 76) == False
    assert candidate(s = "xyz",t = "abc",k = 25) == False
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "zyxwvutsrqponmlkjihgfedcba",k = 104) == True
    assert candidate(s = "longstringexample",t = "mpjutjvqygfqfcqpf",k = 300) == True
    assert candidate(s = "xyzzxyzz",t = "abcdabcd",k = 156) == True
    assert candidate(s = "zzz",t = "abc",k = 78) == True
    assert candidate(s = "hello",t = "tqxxa",k = 100) == False
    assert candidate(s = "abcabcabc",t = "defdefdef",k = 24) == False
    assert candidate(s = "aaaaabbbbb",t = "bbbbbccccc",k = 250) == True
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",t = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",k = 900) == True
    assert candidate(s = "hello",t = "worry",k = 100) == True
    assert candidate(s = "python",t = "pythom",k = 100) == True
    assert candidate(s = "aquickbrownfoxjumpsoverthelazydog",t = "zptjhoqznbmmktgdobnkszemgsvx",k = 1000) == False
    assert candidate(s = "abcd",t = "dcba",k = 10) == False
    assert candidate(s = "mississippi",t = "ssissippi",k = 100) == False
    assert candidate(s = "hello",t = "khoor",k = 15) == False
    assert candidate(s = "almostthere",t = "bnmpsuusfsf",k = 99) == False
    assert candidate(s = "abcdefghij",t = "jihgfedcba",k = 260) == True
    assert candidate(s = "shifting",t = "zmtxlqjq",k = 300) == True
    assert candidate(s = "abcde",t = "edcba",k = 156) == True
    assert candidate(s = "abc",t = "bcd",k = 2) == False
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "bcccdddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzza",k = 1000) == False
    assert candidate(s = "conversion",t = "cvqfvkzqpo",k = 100) == True
    assert candidate(s = "xyz",t = "abc",k = 24) == False
    assert candidate(s = "abcxyz",t = "bcdyza",k = 27) == False
    assert candidate(s = "zzzzzzzzzz",t = "aaaaaaaaaa",k = 259) == True
    assert candidate(s = "hello",t = "uifsf",k = 100) == True
    assert candidate(s = "abc",t = "xyz",k = 100) == True
    assert candidate(s = "thisisatest",t = "ujkjkfbtftu",k = 150) == True
    assert candidate(s = "aaaaaaa",t = "zzzzzzz",k = 702) == True
    assert candidate(s = "abcd",t = "abcd",k = 0) == True
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "zzzzzzzzzzzzzzzzzzzzzzzzzz",k = 1000) == True
    assert candidate(s = "abcdabcdabcd",t = "efghefghijkl",k = 100) == False
    assert candidate(s = "aaaabbbb",t = "bbbbcccc",k = 26) == False
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcd",t = "bcdebcdebcdebcdebcdebcdebcdebcdebcdebcde",k = 100) == False
    assert candidate(s = "aaaaaaaaaaa",t = "bbbbbbbbbbb",k = 1000) == True
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "abcdefghijklmnopqrstuvwxyz",k = 1) == True
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz",t = "aaaaaaaaaaaaaaaaaaaa",k = 260) == False
    assert candidate(s = "ab",t = "yz",k = 51) == True
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "zabcdefghijklmnopqrstuvwxy",k = 51) == False
    assert candidate(s = "abcdabcdabcd",t = "efefefefefef",k = 80) == False
    assert candidate(s = "hello",t = "world",k = 20) == False
    assert candidate(s = "aabbaabb",t = "bbccbbcc",k = 25) == False
    assert candidate(s = "aaaabbbb",t = "bbbbcccc",k = 100) == False
    assert candidate(s = "aaaa",t = "bbbb",k = 26) == False
    assert candidate(s = "abcabcabcabcabcabc",t = "defdefdefdefdefdef",k = 260) == False
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "bcdefghijklmnopqrstuvwxyza",k = 200) == False
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "bcdefghijklmnopqrstuvwxyza",k = 26) == False
    assert candidate(s = "azazaz",t = "bbbbbb",k = 78) == True
    assert candidate(s = "aabbcc",t = "bbccdd",k = 29) == False
    assert candidate(s = "abcdabcd",t = "bcdebcde",k = 10) == False
    assert candidate(s = "hello",t = "world",k = 51) == True
    assert candidate(s = "zzzz",t = "aaaa",k = 104) == True
    assert candidate(s = "aaaaaaaaaa",t = "bbbbbbbbbb",k = 100) == False
    assert candidate(s = "hello",t = "ifmmp",k = 5) == False
    assert candidate(s = "abcd",t = "dcba",k = 104) == True
    assert candidate(s = "abcd",t = "dcba",k = 100) == True
    assert candidate(s = "abacabadabacaba",t = "bcbbcadbbcbcbbc",k = 200) == True
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "zzzzzzzzzzzzzzzzzzzzzzzzzz",k = 675) == True
    assert candidate(s = "aaaaaaaaaaaa",t = "bbbbbbbbbbbb",k = 12) == False
    assert candidate(s = "python",t = "python",k = 0) == True
    assert candidate(s = "abcabcabc",t = "defdefdef",k = 26) == False
    assert candidate(s = "hello",t = "world",k = 52) == True
    assert candidate(s = "abcdef",t = "ghijkl",k = 18) == False
    assert candidate(s = "xyz",t = "abc",k = 77) == True
    assert candidate(s = "abcdefghij",t = "jihgfedcba",k = 100) == True
    assert candidate(s = "same",t = "same",k = 10) == True
    assert candidate(s = "programming",t = "qpsxstjnnqj",k = 200) == True
    assert candidate(s = "programming",t = "programming",k = 1000) == True
    assert candidate(s = "conversion",t = "wxvqivlxnt",k = 500) == True
    assert candidate(s = "thisisatest",t = "ytnsytyfyty",k = 150) == True
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzz",t = "aaaaaaaaaaaaaaaaaaaaaaaaaaaa",k = 1325) == True
    assert candidate(s = "aaa",t = "zzz",k = 701) == True
    assert candidate(s = "a",t = "a",k = 0) == True
    assert candidate(s = "aaa",t = "zzz",k = 78) == True
    assert candidate(s = "conversion",t = "hxqzsrqvok",k = 200) == True
    assert candidate(s = "aaa",t = "abc",k = 2) == True
    assert candidate(s = "abcdefgh",t = "hgfedcba",k = 50) == True
    assert candidate(s = "abcabcabc",t = "defdefdef",k = 78) == False
    assert candidate(s = "mississippi",t = "vvvttttpppp",k = 260) == True
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "bcdefghijklmnopqrstuvwxyza",k = 260) == False
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "zabcdefghijklmnopqrstuvwxy",k = 100) == False
    assert candidate(s = "racecar",t = "racecar",k = 100) == True
    assert candidate(s = "aabbcc",t = "bbccdd",k = 30) == False
    assert candidate(s = "aabbaabb",t = "bbccbbcc",k = 26) == False
    assert candidate(s = "aaaa",t = "zzzz",k = 103) == True
    assert candidate(s = "python",t = "qzuipo",k = 65) == False
    assert candidate(s = "zzzzz",t = "aaaab",k = 130) == True
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc",t = "bcdbcdbcdbcdbcdbcdbcdbcdbcdbcdbcdcb",k = 260) == False
    assert candidate(s = "mississippi",t = "aaaaaaaaaaa",k = 130) == True
    assert candidate(s = "yzyzyzyzyz",t = "acacacacac",k = 520) == True
    assert candidate(s = "hello",t = "world",k = 50) == True
    assert candidate(s = "quickbrownfox",t = "rvjdlqpsqfy",k = 200) == False
    assert candidate(s = "leetcode",t = "leetcode",k = 0) == True
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "bbaacceeggiikkmmppttuuwwyyzzeeddfgghhjjoonnuuxx",k = 1000) == False
    assert candidate(s = "longstringwithmultiplecharacters",t = "nqprxuixwqywwpdqfhhcifqtf",k = 500) == False
