# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(maxChoosableInteger = 15,desiredTotal = 50) == True
    assert candidate(maxChoosableInteger = 10,desiredTotal = 0) == True
    assert candidate(maxChoosableInteger = 10,desiredTotal = 15) == True
    assert candidate(maxChoosableInteger = 8,desiredTotal = 25) == False
    assert candidate(maxChoosableInteger = 10,desiredTotal = 40) == False
    assert candidate(maxChoosableInteger = 10,desiredTotal = 25) == True
    assert candidate(maxChoosableInteger = 20,desiredTotal = 21) == False
    assert candidate(maxChoosableInteger = 5,desiredTotal = 50) == False
    assert candidate(maxChoosableInteger = 10,desiredTotal = 100) == False
    assert candidate(maxChoosableInteger = 20,desiredTotal = 28) == True
    assert candidate(maxChoosableInteger = 15,desiredTotal = 100) == True
    assert candidate(maxChoosableInteger = 12,desiredTotal = 30) == False
    assert candidate(maxChoosableInteger = 7,desiredTotal = 15) == False
    assert candidate(maxChoosableInteger = 6,desiredTotal = 16) == True
    assert candidate(maxChoosableInteger = 10,desiredTotal = 1) == True
    assert candidate(maxChoosableInteger = 3,desiredTotal = 8) == False
    assert candidate(maxChoosableInteger = 20,desiredTotal = 300) == False
    assert candidate(maxChoosableInteger = 10,desiredTotal = 11) == False
    assert candidate(maxChoosableInteger = 16,desiredTotal = 80) == True
    assert candidate(maxChoosableInteger = 18,desiredTotal = 150) == False
    assert candidate(maxChoosableInteger = 15,desiredTotal = 70) == False
    assert candidate(maxChoosableInteger = 8,desiredTotal = 30) == True
    assert candidate(maxChoosableInteger = 20,desiredTotal = 199) == False
    assert candidate(maxChoosableInteger = 9,desiredTotal = 36) == True
    assert candidate(maxChoosableInteger = 16,desiredTotal = 85) == False
    assert candidate(maxChoosableInteger = 20,desiredTotal = 200) == False
    assert candidate(maxChoosableInteger = 18,desiredTotal = 120) == False
    assert candidate(maxChoosableInteger = 11,desiredTotal = 33) == True
    assert candidate(maxChoosableInteger = 13,desiredTotal = 45) == True
    assert candidate(maxChoosableInteger = 10,desiredTotal = 99) == False
    assert candidate(maxChoosableInteger = 16,desiredTotal = 90) == False
    assert candidate(maxChoosableInteger = 14,desiredTotal = 49) == True
    assert candidate(maxChoosableInteger = 13,desiredTotal = 30) == True
    assert candidate(maxChoosableInteger = 20,desiredTotal = 180) == False
    assert candidate(maxChoosableInteger = 14,desiredTotal = 60) == False
    assert candidate(maxChoosableInteger = 13,desiredTotal = 80) == True
    assert candidate(maxChoosableInteger = 14,desiredTotal = 80) == True
    assert candidate(maxChoosableInteger = 16,desiredTotal = 60) == True
    assert candidate(maxChoosableInteger = 12,desiredTotal = 80) == False
    assert candidate(maxChoosableInteger = 10,desiredTotal = 55) == False
    assert candidate(maxChoosableInteger = 19,desiredTotal = 135) == True
    assert candidate(maxChoosableInteger = 14,desiredTotal = 99) == False
    assert candidate(maxChoosableInteger = 19,desiredTotal = 110) == True
    assert candidate(maxChoosableInteger = 12,desiredTotal = 75) == False
    assert candidate(maxChoosableInteger = 5,desiredTotal = 15) == True
    assert candidate(maxChoosableInteger = 14,desiredTotal = 95) == False
    assert candidate(maxChoosableInteger = 7,desiredTotal = 28) == True
    assert candidate(maxChoosableInteger = 14,desiredTotal = 50) == True
    assert candidate(maxChoosableInteger = 20,desiredTotal = 250) == False
    assert candidate(maxChoosableInteger = 17,desiredTotal = 140) == True
    assert candidate(maxChoosableInteger = 19,desiredTotal = 180) == True
    assert candidate(maxChoosableInteger = 16,desiredTotal = 110) == False
    assert candidate(maxChoosableInteger = 13,desiredTotal = 60) == True
    assert candidate(maxChoosableInteger = 9,desiredTotal = 45) == True
    assert candidate(maxChoosableInteger = 12,desiredTotal = 35) == True
    assert candidate(maxChoosableInteger = 17,desiredTotal = 85) == True
    assert candidate(maxChoosableInteger = 20,desiredTotal = 150) == False
    assert candidate(maxChoosableInteger = 15,desiredTotal = 80) == True
    assert candidate(maxChoosableInteger = 8,desiredTotal = 28) == True
    assert candidate(maxChoosableInteger = 7,desiredTotal = 25) == True
    assert candidate(maxChoosableInteger = 18,desiredTotal = 130) == True
    assert candidate(maxChoosableInteger = 11,desiredTotal = 55) == True
    assert candidate(maxChoosableInteger = 17,desiredTotal = 90) == True
    assert candidate(maxChoosableInteger = 17,desiredTotal = 100) == True
    assert candidate(maxChoosableInteger = 16,desiredTotal = 120) == True
    assert candidate(maxChoosableInteger = 20,desiredTotal = 130) == False
    assert candidate(maxChoosableInteger = 19,desiredTotal = 120) == True
    assert candidate(maxChoosableInteger = 16,desiredTotal = 130) == False
    assert candidate(maxChoosableInteger = 7,desiredTotal = 20) == True
    assert candidate(maxChoosableInteger = 18,desiredTotal = 180) == False
    assert candidate(maxChoosableInteger = 18,desiredTotal = 100) == True
    assert candidate(maxChoosableInteger = 12,desiredTotal = 60) == False
    assert candidate(maxChoosableInteger = 15,desiredTotal = 120) == True
    assert candidate(maxChoosableInteger = 14,desiredTotal = 70) == True
    assert candidate(maxChoosableInteger = 10,desiredTotal = 50) == False
