# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(title = "ai and ml") == "ai And ml"
    assert candidate(title = "First leTTeR of EACH Word") == "First Letter of Each Word"
    assert candidate(title = "tHis iS a tEsT") == "This is a Test"
    assert candidate(title = "a b c") == "a b c"
    assert candidate(title = "HELLO WORLD") == "Hello World"
    assert candidate(title = "a b c d e f g") == "a b c d e f g"
    assert candidate(title = "sMaLl wOrDs") == "Small Words"
    assert candidate(title = "mY nAmE is Qwen") == "my Name is Qwen"
    assert candidate(title = "abc") == "Abc"
    assert candidate(title = "mY sOLution IS Awesome") == "my Solution is Awesome"
    assert candidate(title = "ab") == "ab"
    assert candidate(title = "Python Programming") == "Python Programming"
    assert candidate(title = "this is a test") == "This is a Test"
    assert candidate(title = "i lOve leetcode") == "i Love Leetcode"
    assert candidate(title = "mY NaMe Is Qwen") == "my Name is Qwen"
    assert candidate(title = "capiTalIze tHe titLe") == "Capitalize The Title"
    assert candidate(title = "Alibaba Cloud") == "Alibaba Cloud"
    assert candidate(title = "machine learning") == "Machine Learning"
    assert candidate(title = "tHis is a TeSt") == "This is a Test"
    assert candidate(title = "a") == "a"
    assert candidate(title = "hello world") == "Hello World"
    assert candidate(title = "tHis is A tEsT cASE") == "This is a Test Case"
    assert candidate(title = "data science") == "Data Science"
    assert candidate(title = "data science and machine learning") == "Data Science And Machine Learning"
    assert candidate(title = "the quick") == "The Quick"
    assert candidate(title = "tiny a big BIGGEST") == "Tiny a Big Biggest"
    assert candidate(title = "advanced DATABASE MANAGEMENT SYSTEM") == "Advanced Database Management System"
    assert candidate(title = "FLASK and DJANGO web FRAMEWORKS") == "Flask And Django Web Frameworks"
    assert candidate(title = "sINGLEcHaRaCters AND twOCHaRaCters") == "Singlecharacters And Twocharacters"
    assert candidate(title = "PYTHON pROGRAMMING") == "Python Programming"
    assert candidate(title = "pyThOn cOdInG chAlLenge") == "Python Coding Challenge"
    assert candidate(title = "data sCience and MaChine LeArning") == "Data Science And Machine Learning"
    assert candidate(title = "PYTHON programming LANGUAGE") == "Python Programming Language"
    assert candidate(title = "DESIGN PATTERNS in software ENGINEERING") == "Design Patterns in Software Engineering"
    assert candidate(title = "lowercase with small words like a and the") == "Lowercase With Small Words Like a And The"
    assert candidate(title = "wHy cApItAlIzE sOmE wOrDs") == "Why Capitalize Some Words"
    assert candidate(title = "data sCience and MaChInE lEaRnInG") == "Data Science And Machine Learning"
    assert candidate(title = "WEB DEVELOPMENT essentials") == "Web Development Essentials"
    assert candidate(title = "an") == "an"
    assert candidate(title = "Data Science and Machine Learning") == "Data Science And Machine Learning"
    assert candidate(title = "INformation TECHNOLOGY") == "Information Technology"
    assert candidate(title = "cryptography and SECURITY") == "Cryptography And Security"
    assert candidate(title = "UPPER lower CASE") == "Upper Lower Case"
    assert candidate(title = "SOFTWARE ENGINEERING principles") == "Software Engineering Principles"
    assert candidate(title = "LONGEST wORD") == "Longest Word"
    assert candidate(title = "pYtHoN pRoGrAmMiNg") == "Python Programming"
    assert candidate(title = "multiple     spaces   here") == "Multiple Spaces Here"
    assert candidate(title = "sInGlE") == "Single"
    assert candidate(title = "openai gpt four") == "Openai Gpt Four"
    assert candidate(title = "user INTERFACE and user EXPERIENCE") == "User Interface And User Experience"
    assert candidate(title = "VIRTUALIZATION technology") == "Virtualization Technology"
    assert candidate(title = "in the land OF wonder AND magic") == "in The Land of Wonder And Magic"
    assert candidate(title = "CoMpLeX wOrDs LiKe SuPeRcAlIfR aNd qUiXoTtIc") == "Complex Words Like Supercalifr And Quixottic"
    assert candidate(title = "tHis is A tEsT String") == "This is a Test String"
    assert candidate(title = "INTERNET of THINGS iot") == "Internet of Things Iot"
    assert candidate(title = "tHiS is a sHoRt TeSt") == "This is a Short Test"
    assert candidate(title = "python programming LANGUAGE") == "Python Programming Language"
    assert candidate(title = "a quick brown fox jumps over the lazy dog") == "a Quick Brown Fox Jumps Over The Lazy Dog"
    assert candidate(title = "UPPERCASE lowercase MIXEDcase") == "Uppercase Lowercase Mixedcase"
    assert candidate(title = "a SHORT story IN a SMALL town") == "a Short Story in a Small Town"
    assert candidate(title = "single") == "Single"
    assert candidate(title = "data STRUCTURE and ALGORITHMS") == "Data Structure And Algorithms"
    assert candidate(title = "this is a test STRING with MIXED CASE") == "This is a Test String With Mixed Case"
    assert candidate(title = "to be or not to be") == "to be or Not to be"
    assert candidate(title = "wordlengthsofthreetwoone") == "Wordlengthsofthreetwoone"
    assert candidate(title = "wiTh lOnG wOrDs liKe suPercalifragilisticexpialidocious") == "With Long Words Like Supercalifragilisticexpialidocious"
    assert candidate(title = "this is a longer sentence with more words to test the function") == "This is a Longer Sentence With More Words to Test The Function"
    assert candidate(title = "very Very LONG title with MANY Words indeed") == "Very Very Long Title With Many Words Indeed"
    assert candidate(title = "Algorithms and DATA structures") == "Algorithms And Data Structures"
    assert candidate(title = "tEsTiNg WoRdS wItH vArIoUs lEnGtHs") == "Testing Words With Various Lengths"
    assert candidate(title = "a quick brown fox") == "a Quick Brown Fox"
    assert candidate(title = "tExT pRoCeSsInG") == "Text Processing"
    assert candidate(title = "the quick BROWN fox JUMPS OVER the LAZY DOG") == "The Quick Brown Fox Jumps Over The Lazy Dog"
    assert candidate(title = "algorithms and data structures") == "Algorithms And Data Structures"
    assert candidate(title = "a short AND a LONG word") == "a Short And a Long Word"
    assert candidate(title = "AlGoRiThM aNd dAtA sTrUcTuRe") == "Algorithm And Data Structure"
    assert candidate(title = "data sCIENCE and maCHine LEARNING") == "Data Science And Machine Learning"
    assert candidate(title = "cOnsIdEr tHiS eXaMpLe") == "Consider This Example"
    assert candidate(title = "cloud COMPUTING") == "Cloud Computing"
    assert candidate(title = "fLASK aNd dJANGO") == "Flask And Django"
    assert candidate(title = "To be OR not TO be") == "to be or Not to be"
    assert candidate(title = "multiple words of varying length and CASE") == "Multiple Words of Varying Length And Case"
    assert candidate(title = "network SECURITY") == "Network Security"
    assert candidate(title = "programming IN python") == "Programming in Python"
    assert candidate(title = "the QUICK brown FOX jumps OVER the LAZY dog") == "The Quick Brown Fox Jumps Over The Lazy Dog"
    assert candidate(title = "MiXcAsE wOrDlEnGtH") == "Mixcase Wordlength"
    assert candidate(title = "in") == "in"
    assert candidate(title = "wiTh grEat pOwEr cOmEs gReAt rEsPoNsIbIlItY") == "With Great Power Comes Great Responsibility"
    assert candidate(title = "algorithms AND dataSTRUCTURES") == "Algorithms And Datastructures"
    assert candidate(title = "wiTh gReAt pOWeR cOmEs gReAt rEsPoNsIbIlItY") == "With Great Power Comes Great Responsibility"
    assert candidate(title = "A B c D E F G") == "a b c d e f g"
    assert candidate(title = "AI and MACHINE LEARNING") == "ai And Machine Learning"
    assert candidate(title = "big DATA ANALYSIS") == "Big Data Analysis"
    assert candidate(title = "mUlTiPlE sMaLl wOrDs") == "Multiple Small Words"
    assert candidate(title = "LEETcode IS coOL") == "Leetcode is Cool"
    assert candidate(title = "two Words") == "Two Words"
    assert candidate(title = "introduction to ARTIFICIAL INTELLIGENCE") == "Introduction to Artificial Intelligence"
    assert candidate(title = "sOlVe tHe rObOt wOrLd cHAlLeNgEs") == "Solve The Robot World Challenges"
    assert candidate(title = "mIxEd cAsE iNpUt") == "Mixed Case Input"
    assert candidate(title = "EACH WORD IN THE TITLE") == "Each Word in The Title"
    assert candidate(title = "programming in PYTHON") == "Programming in Python"
    assert candidate(title = "one two three four five six seven eight nine ten") == "One Two Three Four Five Six Seven Eight Nine Ten"
    assert candidate(title = "very very LONG words in THIS sentence") == "Very Very Long Words in This Sentence"
    assert candidate(title = "leet code CHALLENGE") == "Leet Code Challenge"
    assert candidate(title = "the") == "The"
    assert candidate(title = "double two") == "Double Two"
    assert candidate(title = "a B c D E F G") == "a b c d e f g"
    assert candidate(title = "a b c d e f g h i j k l m n o p q r s t u v w x y z") == "a b c d e f g h i j k l m n o p q r s t u v w x y z"
    assert candidate(title = "in The HoLlyWoOd") == "in The Hollywood"
    assert candidate(title = "tHis is a tEsT string") == "This is a Test String"
    assert candidate(title = "MiXeD CaSe wOrDs") == "Mixed Case Words"
    assert candidate(title = "multiple small words in here") == "Multiple Small Words in Here"
    assert candidate(title = "in the HEART of the CITY") == "in The Heart of The City"
    assert candidate(title = "randomly CaPiTaLiZed WoRds") == "Randomly Capitalized Words"
    assert candidate(title = "To BE OR NOT to BE") == "to be or Not to be"
    assert candidate(title = "MiNiMaL MaXiMaL") == "Minimal Maximal"
    assert candidate(title = "HELLO wORLD") == "Hello World"
    assert candidate(title = "THE quick BROWN fox JUMPS OVER the LAZY dog") == "The Quick Brown Fox Jumps Over The Lazy Dog"
    assert candidate(title = "data SCIENCE and MACHINE LEARNING") == "Data Science And Machine Learning"
    assert candidate(title = "pYthon programming lanGuage") == "Python Programming Language"
    assert candidate(title = "OpenAI GPT-4") == "Openai Gpt-4"
    assert candidate(title = "triple three words") == "Triple Three Words"
    assert candidate(title = "eNcYcLopEdIa oF pHySiCs aNd mAtHeMaTiCs") == "Encyclopedia of Physics And Mathematics"
    assert candidate(title = "a a a a a a a") == "a a a a a a a"
    assert candidate(title = "openAI GPT AND machineLEARNING") == "Openai Gpt And Machinelearning"
    assert candidate(title = "PYTHON programming") == "Python Programming"
    assert candidate(title = "sOFTWARE dEVELOPMENT") == "Software Development"
    assert candidate(title = "tHiS iS a TeSt CaSe") == "This is a Test Case"
    assert candidate(title = "wEb dEveLopMeNt fOr bEgInNeRs") == "Web Development For Beginners"
    assert candidate(title = "one") == "One"
    assert candidate(title = "Data STRUCTURES and ALGORITHMs") == "Data Structures And Algorithms"
    assert candidate(title = "aBcDeFgHiJ kLmNoPqRsT") == "Abcdefghij Klmnopqrst"
    assert candidate(title = "Python Programming Language") == "Python Programming Language"
    assert candidate(title = "blockCHAIN technology") == "Blockchain Technology"
    assert candidate(title = "Python Programming Is Fun") == "Python Programming is Fun"
    assert candidate(title = "LoNg WoRdS aNd sHoRt wOrDs") == "Long Words And Short Words"
    assert candidate(title = "tHe qUiCk bRoWn fOx") == "The Quick Brown Fox"
