# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(a = "abc",b = "bcd") == 2
    assert candidate(a = "aba",b = "caa") == 2
    assert candidate(a = "xyzz",b = "zzzz") == 2
    assert candidate(a = "abcd",b = "dcba") == 4
    assert candidate(a = "aaaabbbb",b = "ccccdddd") == 0
    assert candidate(a = "xyz",b = "abc") == 0
    assert candidate(a = "abc",b = "def") == 0
    assert candidate(a = "abcdefghijklmnopqrstuvwxyz",b = "abcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(a = "zzz",b = "aaa") == 0
    assert candidate(a = "abc",b = "abc") == 3
    assert candidate(a = "a",b = "z") == 0
    assert candidate(a = "aaa",b = "zzz") == 0
    assert candidate(a = "abacabadabacaba",b = "zzzyzxzyzxzyzxz") == 0
    assert candidate(a = "aabbcc",b = "bbccdd") == 4
    assert candidate(a = "xyz",b = "xyz") == 3
    assert candidate(a = "abcdefghijklmnopqrstuvwxyz",b = "zyxwvutsrqponmlkjihgfedcba") == 26
    assert candidate(a = "xyz",b = "zyx") == 3
    assert candidate(a = "aaa",b = "bbb") == 0
    assert candidate(a = "dabadd",b = "cda") == 3
    assert candidate(a = "a",b = "b") == 0
    assert candidate(a = "aaaa",b = "bbbb") == 0
    assert candidate(a = "aaaaabbbbbccccc",b = "cccccbbaaaa") == 11
    assert candidate(a = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",b = "aaaaa") == 0
    assert candidate(a = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",b = "zyxwvutsrqponmlkjihgfedcba") == 27
    assert candidate(a = "qwert",b = "asdfg") == 2
    assert candidate(a = "ababababababababababababababab",b = "bababababababababababababababa") == 30
    assert candidate(a = "algorithm",b = "datastructure") == 7
    assert candidate(a = "abcabcabcabcabcabcabcabcabcabc",b = "zzzzyyyxxxwwwwvvvvuuuuttttssssrrrrqqqqppppooooonnnnmmmmmlllllkkkkkjjjjjiiiii") == 0
    assert candidate(a = "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq",b = "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq") == 0
    assert candidate(a = "abcdabcdabcdabcdabcd",b = "dcbaabcdabcdabcdabcd") == 20
    assert candidate(a = "bcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcb",b = "abadabadabadabadabadabadabadabadabadabadabadabadabadabadabadabadabadabadabadab") == 39
    assert candidate(a = "aaabbbcccddd",b = "eefffgggg") == 0
    assert candidate(a = "aaaaaaaaaabbbbbbbbbbbccccccccc",b = "zzzzzzzzzzzyyyyyyyyyyxxxxxxxxxx") == 0
    assert candidate(a = "abababababababababab",b = "babababababababababa") == 20
    assert candidate(a = "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",b = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 25
    assert candidate(a = "aabbaabbaabbaabbaabbaabbaabbaabbaabbaabb",b = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(a = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",b = "zyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcba") == 52
    assert candidate(a = "mnopmnopmnopmnopmnop",b = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz") == 0
    assert candidate(a = "abacabadabacabadabacaba",b = "zyxzyxzyxzyxzyxzyxzyxzyx") == 0
    assert candidate(a = "aaaaa",b = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(a = "aaaaaabbbbccccdddd",b = "eeeeefffffggggghhhhh") == 0
    assert candidate(a = "abcdefg",b = "hijklmnopqrstuvwxyz") == 0
    assert candidate(a = "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",b = "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq") == 0
    assert candidate(a = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",b = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 2
    assert candidate(a = "mississippi",b = "bababababa") == 0
    assert candidate(a = "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq",b = "pppppppppppppppppppppppppppppppppppppppppp") == 0
    assert candidate(a = "mnop",b = "qrst") == 0
    assert candidate(a = "qazwsxedcrfvtgbyhnujmikolp",b = "ploikmjhunbygvtfredcxswqaz") == 26
    assert candidate(a = "hello",b = "world") == 3
    assert candidate(a = "mno",b = "jkl") == 0
    assert candidate(a = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",b = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(a = "hellohellohello",b = "worldworldworld") == 9
    assert candidate(a = "mmmmmmmmmmmmmmmmmmmmmm",b = "nnnnnnnnnnnnnnnnnnnnnn") == 0
    assert candidate(a = "aabaaaacaba",b = "bcdef") == 2
    assert candidate(a = "zzzzzzzzzz",b = "aaaaaaaaaa") == 0
    assert candidate(a = "aaaaaaaaaaaaaabbbbbbbbbbbbbbcccccccccccccccccdddddddddddddddd",b = "eeeeeeeeeeeeeeeeffffffffgggggggggggggggggghhhhhhhhhhhhhhhhhiiiiiiiiiiiiiiiiii") == 0
    assert candidate(a = "qwertqwertqwert",b = "mnbvmnbvmnbv") == 6
    assert candidate(a = "aaaabbbbccccddddeeeeffffgggghhhhiiii",b = "jkkkllllmmmmnnnnooooppppqqqqrrrrssssttttuuuuvvvvwwwwxxxxyyyyzzzz") == 0
    assert candidate(a = "qwertyuiop",b = "poiuytrewq") == 10
    assert candidate(a = "mno",b = "mnpq") == 2
    assert candidate(a = "llllllllllllllllllllllllllllllllllllllll",b = "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk") == 0
    assert candidate(a = "programming",b = "contest") == 4
    assert candidate(a = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",b = "zzxxwwvvutssrrqqppoonnmmllkkjjiihhggffeeddccbbaa") == 48
    assert candidate(a = "xyzzzzzxyzzzzz",b = "zzzzzxyzzzzzxy") == 8
    assert candidate(a = "zzzzz",b = "aaaaa") == 0
    assert candidate(a = "zzzzzzzzzzzzzz",b = "aaaaaaaaaaaaaa") == 0
    assert candidate(a = "ababababababababababababababababab",b = "bababababababababababababababababa") == 34
    assert candidate(a = "ppppqqqqqqrrrrrrsssssss",b = "tttttuuuuuuuuvvvvvvvvvvvvv") == 0
    assert candidate(a = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",b = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 0
    assert candidate(a = "qwerttyuiiopasdfghjklzzxcvbnm",b = "mnbvcxzlkjhgfdsapoiuytrewq") == 26
    assert candidate(a = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",b = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 2
    assert candidate(a = "python",b = "java") == 2
    assert candidate(a = "pqrstuv",b = "mnopq") == 2
    assert candidate(a = "abcdefghijklmnopqrstuvwxyz",b = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(a = "acabcbacbacbacbaca",b = "bdadbdadbdadbdad") == 8
    assert candidate(a = "abcdefghijklmnopqrstu",b = "vwxyzvwxyzvwxyzvwxyz") == 0
    assert candidate(a = "abcdefghijklmnop",b = "zyxwvutsrqponmlkjihgfedcba") == 16
    assert candidate(a = "abcdefghijklmnopqrstuvwxyz",b = "abcdefghijklmnopqrstuvwxy") == 25
    assert candidate(a = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc",b = "defdefdefdefdefdefdefdefdefdefdefdefdefdefdefdefdefdef") == 0
    assert candidate(a = "abcabcabcabcabcabcabcabcabcabc",b = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyz") == 0
    assert candidate(a = "aabbaacc",b = "zzzzyyxx") == 0
    assert candidate(a = "aaaabbbbcccc",b = "ccccbbbbaaaa") == 12
    assert candidate(a = "abcdefg",b = "zzzzzzz") == 0
    assert candidate(a = "abcdefghijklmnopqrstuvwxy",b = "zyxwvutsrqponmlkjihgfedcba") == 25
    assert candidate(a = "acacacacacacacacacacacacacacaca",b = "bcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbc") == 15
    assert candidate(a = "mnop",b = "qrstuvwxyza") == 1
    assert candidate(a = "abcdabcdabcd",b = "xyzxyzxyzxyz") == 0
    assert candidate(a = "abacabadabacaba",b = "zyxzyxzyxzyxzyxzyx") == 0
    assert candidate(a = "same",b = "same") == 4
    assert candidate(a = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",b = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 0
    assert candidate(a = "mnopqrstu",b = "vwxyzijkl") == 4
    assert candidate(a = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",b = "abcdefghijklmnopqrstuvwxyz") == 1
    assert candidate(a = "mnopqrstuvwxy",b = "abcdefghijklmnopqrstuvwxyz") == 14
    assert candidate(a = "abcdabcabc",b = "zyxzxyzxyz") == 0
    assert candidate(a = "abacabadabacabad",b = "zyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyx") == 0
    assert candidate(a = "abcabcabcabcabcabcabcabcabcabc",b = "abcabcabcabcabcabcabcabcabcabc") == 30
    assert candidate(a = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",b = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(a = "abcdefghijklm",b = "nopqrstuvwxyz") == 0
    assert candidate(a = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",b = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 0
    assert candidate(a = "mnopqrstuvwxyzmnopqrstu",b = "abcdefghijklmnopqrstuabcdefghijklmnopqrstu") == 18
    assert candidate(a = "aaabbbcccdddeeefffggghhhhiiiiijjjjjjkkkkkkkllllllllmmmmmmmmmmm",b = "mnopqrstuvwxyzmnopqrstuvwxyzmnopqrstuvwxyzmnopqrstuvwxyz") == 4
    assert candidate(a = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",b = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 0
    assert candidate(a = "aaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccdddddddddddddddddddddd",b = "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee") == 0
    assert candidate(a = "xyxzyzxzyzxzyzxzyz",b = "zyxzyzxzyzxzyzxzyx") == 18
    assert candidate(a = "abcdefghijklmnop",b = "qrstuvwxyz") == 0
    assert candidate(a = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",b = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(a = "xyzz",b = "abcd") == 0
    assert candidate(a = "racecar",b = "madam") == 5
    assert candidate(a = "abcdefghijklmnopqrstu",b = "vwxyzabcdefghijklmnopqrstu") == 21
    assert candidate(a = "qwe",b = "qwer") == 3
    assert candidate(a = "pppppppppppppppppppppppppppppppppppppppppp",b = "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq") == 0
    assert candidate(a = "mnbvcxzlkjhgfdsapoiuytrewq",b = "qwertyuiopasdfghjklzxcvbnm") == 26
    assert candidate(a = "abcdabcdabcd",b = "dcbaabcdabcd") == 12
    assert candidate(a = "aaaaabbbbb",b = "bbbbbccccc") == 5
    assert candidate(a = "aaabbbcccdddeeefffggghhhiii",b = "kkklllmmmnnnooopppqqqrrrssstttuuuvvv") == 0
    assert candidate(a = "aaaaaaaaaaaaaaaaaaaaaaa",b = "bbbbbbbbbbbbbbbbbbbbbbbbb") == 0
    assert candidate(a = "abacabadabacabadabacabad",b = "zzzzyyyyxxxxyyyyzzzz") == 0
    assert candidate(a = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",b = "zzyyxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeeeddccbbbaa") == 52
    assert candidate(a = "abacabadabacaba",b = "zzzyyyxxxwwwwvvvvuuuuuuttttttsssssrrrrrqqqqqqpppppoonnnnmmmllllkkkkjjjjiiiihhhhhgggggffffffeeeeeeeedddddccccbbbaaaa") == 10
    assert candidate(a = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",b = "zzzyyxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccbbaa") == 52
    assert candidate(a = "mnopqrstuvwxyz",b = "abcdefghijklm") == 1
    assert candidate(a = "one",b = "two") == 1
    assert candidate(a = "qwertyuiopasdfghjklzxcvbnm",b = "qwertyuiopasdfghjklzxcvbnm") == 26
    assert candidate(a = "mississippi",b = "delaware") == 3
    assert candidate(a = "abcdefghijklmnopqrstuvwxyz",b = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 1
    assert candidate(a = "abc",b = "xyz") == 0
    assert candidate(a = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",b = "abcdefghijklmnopqrstuvwxyz") == 27
    assert candidate(a = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc",b = "mnopmnopmnopmnopmnopmnopmnopmnopmnopmnopmnopmnopmnop") == 0
