# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s1 = "abcd",s2 = "cdab") == True
    assert candidate(s1 = "acbd",s2 = "bdac") == True
    assert candidate(s1 = "abab",s2 = "abcd") == False
    assert candidate(s1 = "abdc",s2 = "cdab") == False
    assert candidate(s1 = "abcd",s2 = "dacb") == False
    assert candidate(s1 = "abab",s2 = "baba") == False
    assert candidate(s1 = "abcd",s2 = "abcd") == True
    assert candidate(s1 = "aabb",s2 = "bbaa") == True
    assert candidate(s1 = "abcd",s2 = "dcba") == False
    assert candidate(s1 = "zzzz",s2 = "zzzz") == True
    assert candidate(s1 = "zabc",s2 = "cbaz") == False
    assert candidate(s1 = "efef",s2 = "fefo") == False
    assert candidate(s1 = "abcd",s2 = "dcab") == False
    assert candidate(s1 = "abcd",s2 = "dbca") == False
    assert candidate(s1 = "qrst",s2 = "tqsr") == False
    assert candidate(s1 = "mnop",s2 = "ponq") == False
    assert candidate(s1 = "ijkl",s2 = "lkji") == False
    assert candidate(s1 = "abcd",s2 = "cabd") == False
    assert candidate(s1 = "wxxy",s2 = "yxwx") == False
    assert candidate(s1 = "abcd",s2 = "abdc") == False
    assert candidate(s1 = "qrst",s2 = "tsqr") == False
    assert candidate(s1 = "abba",s2 = "baab") == True
    assert candidate(s1 = "abcd",s2 = "cadb") == False
    assert candidate(s1 = "abcd",s2 = "cdac") == False
    assert candidate(s1 = "wxyz",s2 = "yxwz") == True
    assert candidate(s1 = "abac",s2 = "cabd") == False
    assert candidate(s1 = "mnop",s2 = "npom") == False
    assert candidate(s1 = "ijkl",s2 = "lkij") == False
    assert candidate(s1 = "efgh",s2 = "fegh") == False
    assert candidate(s1 = "pqrs",s2 = "rqps") == True
    assert candidate(s1 = "uvwx",s2 = "xwvu") == False
    assert candidate(s1 = "wxyz",s2 = "xywz") == False
    assert candidate(s1 = "xyxy",s2 = "yxyx") == False
    assert candidate(s1 = "efgh",s2 = "hgfq") == False
    assert candidate(s1 = "abcd",s2 = "dbac") == False
    assert candidate(s1 = "aabb",s2 = "abab") == False
    assert candidate(s1 = "mnop",s2 = "ponm") == False
    assert candidate(s1 = "abcd",s2 = "bdca") == False
    assert candidate(s1 = "qrst",s2 = "tsrf") == False
    assert candidate(s1 = "qrst",s2 = "tsrq") == False
    assert candidate(s1 = "abcd",s2 = "badc") == False
    assert candidate(s1 = "qrst",s2 = "tqrs") == False
    assert candidate(s1 = "abcd",s2 = "adcb") == True
    assert candidate(s1 = "mnop",s2 = "pmno") == False
    assert candidate(s1 = "abba",s2 = "baba") == False
    assert candidate(s1 = "abcd",s2 = "bacd") == False
    assert candidate(s1 = "abca",s2 = "acba") == False
    assert candidate(s1 = "abcd",s2 = "bdac") == False
    assert candidate(s1 = "mnop",s2 = "onmp") == True
    assert candidate(s1 = "lwxy",s2 = "xylw") == True
    assert candidate(s1 = "zzza",s2 = "zzaa") == False
    assert candidate(s1 = "abcd",s2 = "acdb") == False
    assert candidate(s1 = "zzzz",s2 = "zzaz") == False
    assert candidate(s1 = "aabb",s2 = "abba") == True
    assert candidate(s1 = "abcd",s2 = "acbd") == False
    assert candidate(s1 = "wxyz",s2 = "xyzw") == False
    assert candidate(s1 = "xxyz",s2 = "zyxz") == False
    assert candidate(s1 = "abcd",s2 = "dabc") == False
    assert candidate(s1 = "pqrs",s2 = "rspq") == True
    assert candidate(s1 = "zyxw",s2 = "xwyz") == False
    assert candidate(s1 = "abcd",s2 = "abca") == False
    assert candidate(s1 = "abca",s2 = "cabd") == False
    assert candidate(s1 = "mnop",s2 = "nopm") == False
