# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(n = 933) == False
    assert candidate(n = 147) == False
    assert candidate(n = 576) == False
    assert candidate(n = 789) == False
    assert candidate(n = 579) == False
    assert candidate(n = 273) == True
    assert candidate(n = 327) == True
    assert candidate(n = 192) == True
    assert candidate(n = 369) == False
    assert candidate(n = 258) == False
    assert candidate(n = 932) == False
    assert candidate(n = 100) == False
    assert candidate(n = 819) == False
    assert candidate(n = 735) == False
    assert candidate(n = 342) == False
    assert candidate(n = 269) == False
    assert candidate(n = 135) == False
    assert candidate(n = 729) == False
    assert candidate(n = 639) == False
    assert candidate(n = 657) == False
    assert candidate(n = 846) == False
    assert candidate(n = 964) == False
    assert candidate(n = 402) == False
    assert candidate(n = 123) == False
    assert candidate(n = 396) == False
    assert candidate(n = 300) == False
    assert candidate(n = 854) == False
    assert candidate(n = 852) == False
    assert candidate(n = 439) == False
    assert candidate(n = 673) == False
    assert candidate(n = 384) == False
    assert candidate(n = 621) == False
    assert candidate(n = 270) == False
    assert candidate(n = 471) == False
    assert candidate(n = 741) == False
    assert candidate(n = 594) == False
    assert candidate(n = 783) == False
    assert candidate(n = 186) == False
    assert candidate(n = 654) == False
    assert candidate(n = 873) == False
    assert candidate(n = 297) == False
    assert candidate(n = 927) == False
    assert candidate(n = 725) == False
    assert candidate(n = 999) == False
    assert candidate(n = 294) == False
    assert candidate(n = 519) == False
    assert candidate(n = 518) == False
    assert candidate(n = 140) == False
    assert candidate(n = 513) == False
    assert candidate(n = 504) == False
    assert candidate(n = 693) == False
    assert candidate(n = 843) == False
    assert candidate(n = 918) == False
    assert candidate(n = 534) == False
    assert candidate(n = 624) == False
    assert candidate(n = 183) == False
    assert candidate(n = 753) == False
    assert candidate(n = 486) == False
    assert candidate(n = 243) == False
    assert candidate(n = 924) == False
