# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s1 = "aabbcc",s2 = "bbaacc") == True
    assert candidate(s1 = "abcdabcd",s2 = "dcbadcba") == False
    assert candidate(s1 = "abcdba",s2 = "cabdab") == True
    assert candidate(s1 = "a",s2 = "a") == True
    assert candidate(s1 = "hello",s2 = "olelh") == False
    assert candidate(s1 = "aabbcc",s2 = "acbbca") == True
    assert candidate(s1 = "abcd",s2 = "cdab") == True
    assert candidate(s1 = "abcdef",s2 = "fedcba") == False
    assert candidate(s1 = "xyz",s2 = "zyx") == True
    assert candidate(s1 = "ab",s2 = "ba") == False
    assert candidate(s1 = "abe",s2 = "bea") == False
    assert candidate(s1 = "abcd",s2 = "dcba") == False
    assert candidate(s1 = "aabbccddeeff",s2 = "ffeeddccbbaa") == True
    assert candidate(s1 = "mississippi",s2 = "ssimmppiiss") == False
    assert candidate(s1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",s2 = "zzzyyxwwvvuuttrrssqqppoonnmmllkkjjiihhggffeeeeddccbbaa") == False
    assert candidate(s1 = "palindrome",s2 = "paldinrome") == False
    assert candidate(s1 = "abcdefghijklmnopqrstuvwxyz",s2 = "zyxwvutsrqponmlkjihgfedcba") == False
    assert candidate(s1 = "racecar",s2 = "acecarr") == False
    assert candidate(s1 = "aaabbbccc",s2 = "bbbaaacc") == False
    assert candidate(s1 = "oddindexedswap",s2 = "doidndexswpoa") == False
    assert candidate(s1 = "abcdefghijabcdefghijabcdefghij",s2 = "abcdefghijabcdefghijabcdefghjk") == False
    assert candidate(s1 = "level",s2 = "level") == True
    assert candidate(s1 = "deified",s2 = "deified") == True
    assert candidate(s1 = "evenlydistributedstring",s2 = "elvnyeedisutrdstrign") == False
    assert candidate(s1 = "aabbcc",s2 = "ccbbaa") == True
    assert candidate(s1 = "pqrstuv",s2 = "upqrsvt") == False
    assert candidate(s1 = "rotor",s2 = "rotar") == False
    assert candidate(s1 = "abcdefg",s2 = "gfedcba") == True
    assert candidate(s1 = "racecar",s2 = "carrace") == False
    assert candidate(s1 = "abababab",s2 = "babababa") == False
    assert candidate(s1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",s2 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == True
    assert candidate(s1 = "zxcvbnm",s2 = "mnbvcxz") == True
    assert candidate(s1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",s2 = "zzyyxwwvvuuttssrrqppoonnllkkjjiihhggeeffdccbbbaa") == False
    assert candidate(s1 = "abcdefgh",s2 = "gfehdcba") == False
    assert candidate(s1 = "abcdefghijabcdefghijabcdefghij",s2 = "bacdfegihjbacdfegihjbacdfegihj") == False
    assert candidate(s1 = "aaaabbbbccccddddeeeeffffgggghhhh",s2 = "hhhhggggffffeeeeddddbbbbccccaaaa") == True
    assert candidate(s1 = "hellohello",s2 = "ehlolhloel") == False
    assert candidate(s1 = "abacabadabacaba",s2 = "abaabacabadabaaba") == False
    assert candidate(s1 = "abcdabcdabcdabcd",s2 = "bacdbacdbacdbacd") == False
    assert candidate(s1 = "banana",s2 = "ananab") == False
    assert candidate(s1 = "abcabcabcabcabcabcabcabcabcabc",s2 = "bababababababababababababababababa") == False
    assert candidate(s1 = "zzzzzzzzzz",s2 = "zzzzzzzzzz") == True
    assert candidate(s1 = "abacabadabacabad",s2 = "babaacabadabacab") == False
    assert candidate(s1 = "abcdabcdabcdabcd",s2 = "ddddccccbbbbaaaa") == False
    assert candidate(s1 = "aabbccddeeff",s2 = "abbaccddffee") == True
    assert candidate(s1 = "xyzxyzxyzxyz",s2 = "zyxzyxzyxzyx") == True
    assert candidate(s1 = "abcdefghijklmnopqrstuvwxyzz",s2 = "zzabcdefghijklmnopqrstuvwxy") == True
    assert candidate(s1 = "thisisaverylongstring",s2 = "tihisrasevylnsgtrnogi") == False
    assert candidate(s1 = "mississippi",s2 = "ppissimissi") == True
    assert candidate(s1 = "aaaaaabbbbbb",s2 = "bbbbbaaaaaa") == False
    assert candidate(s1 = "abacabadabacaba",s2 = "aabacabadabacab") == False
    assert candidate(s1 = "abcdefghijkmnopqrstuvwxyz",s2 = "bacdfeghijkmnopqrstvwxyz") == False
    assert candidate(s1 = "abacabadabacabad",s2 = "babaacabdacaba") == False
    assert candidate(s1 = "abcdef",s2 = "fdecba") == False
    assert candidate(s1 = "abcdefghijk",s2 = "jihgfedcbaa") == False
    assert candidate(s1 = "mississippi",s2 = "imississipp") == False
    assert candidate(s1 = "qwertqwert",s2 = "wqerqewtqw") == False
    assert candidate(s1 = "mississippi",s2 = "ssissimippi") == True
    assert candidate(s1 = "almostsame",s2 = "lmostsae") == False
    assert candidate(s1 = "abcdefgabcdefg",s2 = "gfedcbagfedcba") == True
    assert candidate(s1 = "abcdefghijklmnopqrstuvwx",s2 = "bacdfeghijklmnopqrstuvxw") == False
    assert candidate(s1 = "abcdefghijkll",s2 = "llijkgfhecdba") == False
    assert candidate(s1 = "abcabcabc",s2 = "bcabcbaca") == False
    assert candidate(s1 = "zaybzcyd",s2 = "dzbyazcy") == False
    assert candidate(s1 = "abcdefghef",s2 = "gdefhabcef") == False
    assert candidate(s1 = "aabbcc",s2 = "bbccaa") == True
    assert candidate(s1 = "abcabcabc",s2 = "cbacbacba") == True
    assert candidate(s1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",s2 = "bbbbccccddddeeeeffffgggghhhhiiijjjkkkllmmnnooppqqrrssttuuvvwwxxyyzz") == False
    assert candidate(s1 = "abcdefghijklmnop",s2 = "ponmlkjihgfedcba") == False
    assert candidate(s1 = "programming",s2 = "pgmrnomggin") == False
    assert candidate(s1 = "repaper",s2 = "repaper") == True
    assert candidate(s1 = "abcdefgihjklmnopqrstuvwxyz",s2 = "bacdfegihjklmnopqrstuvwxzy") == False
    assert candidate(s1 = "abcdeffedcba",s2 = "fedcbaffedcba") == False
    assert candidate(s1 = "abcdefghijklmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba",s2 = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == False
    assert candidate(s1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",s2 = "zzyyxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeeeddccbbbaa") == False
    assert candidate(s1 = "sameorder",s2 = "sameorder") == True
    assert candidate(s1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",s2 = "bbaaccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == True
    assert candidate(s1 = "abcdabcd",s2 = "dcbaabcd") == False
    assert candidate(s1 = "abcdefghij",s2 = "jihgfedcba") == False
    assert candidate(s1 = "pqrstuvw",s2 = "wvutsrqp") == False
    assert candidate(s1 = "zyxwvutsrqponmlkjihgfedcba",s2 = "yxwvuztsrqponmlkjihgfedcba") == False
    assert candidate(s1 = "abcdefghij",s2 = "aecgbdfhij") == False
    assert candidate(s1 = "acdbegfh",s2 = "bfegacdh") == False
    assert candidate(s1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",s2 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == False
    assert candidate(s1 = "abadecafagbahbbhacdg",s2 = "bdacegafabchbahbadcg") == False
    assert candidate(s1 = "abcdefghij",s2 = "abcdefghij") == True
    assert candidate(s1 = "aabbaabb",s2 = "bbaabbaa") == True
    assert candidate(s1 = "xyzzyxzyxzyx",s2 = "zyxzyxzyxzyx") == True
    assert candidate(s1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",s2 = "zzzzyyyxxxwwvvuuttssrrqqppoonnllkkjjiihhggeeffddeebbcaaa") == False
    assert candidate(s1 = "abcabcabcabc",s2 = "cbacbacbacba") == True
    assert candidate(s1 = "racecar",s2 = "racecar") == True
    assert candidate(s1 = "abacabadabacabad",s2 = "badcbadcbadcba") == False
    assert candidate(s1 = "abacabadabacaba",s2 = "abacabaabacabada") == False
    assert candidate(s1 = "aabbccddeeff",s2 = "fbeeccddbaaa") == False
    assert candidate(s1 = "noon",s2 = "noon") == True
    assert candidate(s1 = "aaabbbcccddd",s2 = "dddcccbbbaaa") == False
    assert candidate(s1 = "zxyxzyzyx",s2 = "yxzyxzyxq") == False
    assert candidate(s1 = "mississippi",s2 = "ppimississi") == False
    assert candidate(s1 = "abcdefghij",s2 = "gbihfedcja") == False
    assert candidate(s1 = "aabbccddeeffgghhiijj",s2 = "jjiihhggffeeeddccbaa") == False
    assert candidate(s1 = "zzzzzzzzzzzzzzzzzzzzzzzzzz",s2 = "zzzzzzzzzzzzzzzzzzzzzzzzzz") == True
    assert candidate(s1 = "aabbaabbaabb",s2 = "bbaabbaabbba") == False
    assert candidate(s1 = "abcdefg",s2 = "afedcba") == False
    assert candidate(s1 = "abacabad",s2 = "dcadcbab") == False
    assert candidate(s1 = "aabbccdd",s2 = "ddccbbaa") == True
    assert candidate(s1 = "ababababababababababababab",s2 = "bababababababababababababa") == False
    assert candidate(s1 = "noonnoon",s2 = "nnoonnou") == False
    assert candidate(s1 = "ababab",s2 = "bababa") == False
    assert candidate(s1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",s2 = "abbaccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == True
    assert candidate(s1 = "abcdefgihjklmnopqrstuvwxyz",s2 = "zyxwvutsrqponmlkjihgfedcba") == False
    assert candidate(s1 = "abcdefghij",s2 = "jeihgfedcb") == False
    assert candidate(s1 = "abcdefghijk",s2 = "jihgfedcbak") == False
    assert candidate(s1 = "qwertypoiuytrewq",s2 = "qwertyuiytrewpoi") == False
    assert candidate(s1 = "rotor",s2 = "rotor") == True
    assert candidate(s1 = "pneumonoultramicroscopicsilicovolcanoconiosis",s2 = "pneumonoultramicroscopicsilicovolcanoconiosis") == True
    assert candidate(s1 = "noonoon",s2 = "nooouon") == False
    assert candidate(s1 = "detartrated",s2 = "detartrated") == True
    assert candidate(s1 = "abcdabcdabcd",s2 = "dcbaabcdabcd") == False
    assert candidate(s1 = "aabbaabbaabbaabb",s2 = "bbaabbaabbaabbaa") == True
    assert candidate(s1 = "mnopqrstuvwxyzabcdefghijkl",s2 = "onmpqrstuvwxyzabcdefghijkl") == True
    assert candidate(s1 = "abcdabcd",s2 = "cdabcdab") == True
    assert candidate(s1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",s2 = "zzyyxxwwvvuuttrrqqppoonnllkkjjiihhggeeffddeeaabbcc") == False
    assert candidate(s1 = "xyxzyzyx",s2 = "yxzyxzyz") == False
    assert candidate(s1 = "pqrstuvwx",s2 = "vutsrqpwx") == True
    assert candidate(s1 = "abacabadabacabaa",s2 = "abaabacabadabaab") == False
    assert candidate(s1 = "abcdefghijklmnopqrstuvwxyz",s2 = "zabcdefghijklmnopqrstuvwxy") == False
    assert candidate(s1 = "aabbccddeeff",s2 = "bbccddeeffaa") == True
