# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(sentence = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == True
    assert candidate(sentence = "quickbrownfoxjumpsoverthelazydog") == True
    assert candidate(sentence = "aaaaabbbbbccccc") == False
    assert candidate(sentence = "a") == False
    assert candidate(sentence = "thequickbrownfoxjumpsoverthelazydogandmorelettersjusttoextendthelengthofthesentenceevenmorejustformeasurements") == True
    assert candidate(sentence = "hellothere") == False
    assert candidate(sentence = "hello") == False
    assert candidate(sentence = "thequickbrownfoxjumpsoverthelazy") == False
    assert candidate(sentence = "abcdefghijjklmnopqrstuvwxyz") == True
    assert candidate(sentence = "hello world") == False
    assert candidate(sentence = "abcdefghijklmnopqrstuvwxyzzzzz") == True
    assert candidate(sentence = "leetcode") == False
    assert candidate(sentence = "thisisaverylongsentencebutnotapangram") == False
    assert candidate(sentence = "abcdefghijklmnopqrstuvwxyz") == True
    assert candidate(sentence = "thequickbrownfoxjumpsoverthelazydog") == True
    assert candidate(sentence = "abcdefghijklmnopqrstuvwxyzabc") == True
    assert candidate(sentence = "mississippi") == False
    assert candidate(sentence = "thequickbrownfoxjumpsoverthelaz") == False
    assert candidate(sentence = "zyxwvutsrqponmlkjihgfedcba") == True
    assert candidate(sentence = "abcdefghijlkmnopqrstuvwxyz") == True
    assert candidate(sentence = "thequickbrownfoxjumpsoverthelazydogandthenomeofthezebra") == True
    assert candidate(sentence = "aquickmovementsoftheenemywilljeopardizethesecurityofthefort") == False
    assert candidate(sentence = "neverjumpoveraslydogquicklyasmyfastcat") == False
    assert candidate(sentence = "jumpedoverthelazybrownfoxquickly") == False
    assert candidate(sentence = "thisisaverylongsentencethatwantsyoumakesurethatispangram") == False
    assert candidate(sentence = "everygoodboydoesfine") == False
    assert candidate(sentence = "thequickbrownfoxjumpsoverthefly") == False
    assert candidate(sentence = "thefoxjumpedoveralazydogandquicklymunchedberries") == False
    assert candidate(sentence = "aquickmovofjumpsbxngthevlackdwarf") == False
    assert candidate(sentence = "abcdefghijklnopqrstuvwxyz") == False
    assert candidate(sentence = "sphinxofblackquartzjudgemyvowels") == True
    assert candidate(sentence = "thequickbrownfoxjumpsoverthelazydozzzzzzzzzz") == False
    assert candidate(sentence = "aabbbcccdddeeefffggghhhhiiiijjjjkkkkllllmmmmnnnnooooppppqqqqrrrrssttttuuuuvvvvwwwwxxxxyyyyzzzz") == True
    assert candidate(sentence = "thisisaverylongsentencethatshouldcontainalllettersquickly") == False
    assert candidate(sentence = "thebrownfoxjumpsovertheleazydog") == False
    assert candidate(sentence = "phinxofquizzingjudgesbringsmywonder") == False
    assert candidate(sentence = "packmyboxwithfivedozenliquorjugsquicklyandjudgeeachvowel") == True
    assert candidate(sentence = "vowelsaeiouyzqjfdxhcntrbplsmkgw") == True
    assert candidate(sentence = "jumpsquickonthisbrownfox") == False
    assert candidate(sentence = "fivexwiseguysjumpquicklyonthiszanyboat") == False
    assert candidate(sentence = "aquickmovewiththiszestyjuicebringsvexflation") == False
    assert candidate(sentence = "quickbrownfoxjumpsoverthelazydogquickbrownfoxjumpsoverthelazydog") == True
    assert candidate(sentence = "pythonprogramminglanguage") == False
    assert candidate(sentence = "xylophonesarefunbutquickbrownfoxjumpsoverthelazydog") == True
    assert candidate(sentence = "thequickbrownfoxjumpsoverthelazydogy") == True
    assert candidate(sentence = "qwertypoiuytrewqasdfghjklzxcvbnmasdfghjklzxcvbnmqwertyuiopcvbnm") == True
    assert candidate(sentence = "zyxwvutsrqponmlkjihgfedcbaabcdefghijklmnopqrstuvwxyz") == True
    assert candidate(sentence = "thesixfatfingersjumpquicklyonthisverylazydog") == False
    assert candidate(sentence = "jumpsfoxoverthelazydogquickb") == False
    assert candidate(sentence = "sixjovialfellowshavequicklyzippedanddrunkmanybeers") == False
    assert candidate(sentence = "abacaxypromiseyouanelephantwhoxylophones") == False
    assert candidate(sentence = "jumpedoverthelazydogthequickbrownfox") == False
    assert candidate(sentence = "sphinxofblackquartzjudgemyvexzwift") == True
    assert candidate(sentence = "thequickbrownfoxjumpedoverthelazydogquickly") == False
    assert candidate(sentence = "abcdefghijklmnopqrstuvwxy") == False
    assert candidate(sentence = "abcdefghijklmnopqrstuvwxyzzzzzzzzzz") == True
    assert candidate(sentence = "foxjumpsoverthelazydogquickbrown") == True
    assert candidate(sentence = "thisquestionaboutpangramsissomewhatredundant") == False
    assert candidate(sentence = "aquickbrownfoxjumpsoverthelazydog") == True
    assert candidate(sentence = "jumpedoverthelazydogquickbrownfox") == False
    assert candidate(sentence = "aquickmovingtonafleetofsixgreyhounds") == False
    assert candidate(sentence = "thequickbrownfoxjumpsoverthelazydogg") == True
    assert candidate(sentence = "howvexinglyquickdaftzebrasjump") == True
    assert candidate(sentence = "quickbrownfoxjumpsoverthelazydogzzzzzzzzzz") == True
    assert candidate(sentence = "aquickmovementsofthejaguarzephyr") == False
    assert candidate(sentence = "quicklyjudginghowvexingzebraflowscanbeverytricky") == False
    assert candidate(sentence = "aquickbrownfoxjumpsoverthelazydogandbackagain") == True
    assert candidate(sentence = "abcdefghijklnopqrstuvwxyzabcdefghijklnopqrstuvwxyz") == False
    assert candidate(sentence = "jellyoftheplumlovesmeandthemonkeyrinsesupwithgrapejuicequickly") == False
    assert candidate(sentence = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == True
    assert candidate(sentence = "thebrownfoxjumpedoveralazylazydog") == False
    assert candidate(sentence = "packmyboxwithfivedozenliquorjugs") == True
    assert candidate(sentence = "foxjumpsoverthelazydogquickbrownzzzzzzzzzz") == True
    assert candidate(sentence = "althoughsomehumansareabsolutelyastonishing") == False
    assert candidate(sentence = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == True
    assert candidate(sentence = "jovialwaltzsexemplifiesquickbymyflyfriend") == False
    assert candidate(sentence = "aquickbrownfoxjumpsoverthelazydogs") == True
    assert candidate(sentence = "thequickbrownfoxjumpsoverthelazydo") == False
    assert candidate(sentence = "abcdefghjklmnopqrstuvwxyz") == False
    assert candidate(sentence = "veryfewlazydogslikejumpingoverthebigbrownfox") == False
    assert candidate(sentence = "therearemanysmallpacksofdifferentbooksinthelibrary") == False
    assert candidate(sentence = "zyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcba") == True
    assert candidate(sentence = "jimquicklyzippedvexedfowlsbymyplushog") == False
    assert candidate(sentence = "quickbrownfoxjumpsoverthelazydogs") == True
    assert candidate(sentence = "abcdefghijkllllmnopqrstuvwxyz") == True
    assert candidate(sentence = "thequickbrownfoxjumpsoverthelazydogandmore") == True
    assert candidate(sentence = "everygoodboydoesfinejustkickslovingmonkeysnearpianoquicksly") == False
    assert candidate(sentence = "pqrsghijklmnabcdefwxyzotuvcd") == True
    assert candidate(sentence = "pangramsarefunnywordsusedinyogamatclasses") == False
    assert candidate(sentence = "thequickbrownfoxjumpedoverthelazydogandthenranoff") == False
    assert candidate(sentence = "fourxsixtwoseveneleveneightfivenineninetwozero") == False
    assert candidate(sentence = "abracadabracabracadabra") == False
    assert candidate(sentence = "mjklqrswxzytfpuhncideaoxbgvlozmt") == True
    assert candidate(sentence = "thequickbrownfoxjumpsoverthelazydogandcat") == True
    assert candidate(sentence = "thisisaverylongstringsentencethatwillnotbepangram") == False
    assert candidate(sentence = "quovadis") == False
    assert candidate(sentence = "thisisaverylongsentencethatjustmightcontainallthelettersofthealphabet") == False
    assert candidate(sentence = "everygoodboydoesfineandzestfullyjumpoverlazysnails") == False
