# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "aabbccc") == False
    assert candidate(s = "abacbc") == True
    assert candidate(s = "abcabcabc") == True
    assert candidate(s = "qqqq") == True
    assert candidate(s = "aabbcc") == True
    assert candidate(s = "zzzzzzzzzz") == True
    assert candidate(s = "aabbc") == False
    assert candidate(s = "a") == True
    assert candidate(s = "abc") == True
    assert candidate(s = "") == False
    assert candidate(s = "aabb") == True
    assert candidate(s = "aabbccddeeff") == True
    assert candidate(s = "abcdabcd") == True
    assert candidate(s = "zzz") == True
    assert candidate(s = "xyz") == True
    assert candidate(s = "aaabb") == False
    assert candidate(s = "hello") == False
    assert candidate(s = "thisisnotagoodstring") == False
    assert candidate(s = "aaaabbbbccccdddd") == True
    assert candidate(s = "almostgoodbutoneextrab") == False
    assert candidate(s = "mnopqrstuvwxyzz") == False
    assert candidate(s = "uniquecharactersabcdefghijklmnopqrstuvwxyz") == False
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == True
    assert candidate(s = "qwertyuioplkjhgfdsazxcvbnm") == True
    assert candidate(s = "kjhgfdsazxcvbnmlpoiuytrewq") == True
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == True
    assert candidate(s = "llllkkkkjjjjiiiihhhhggggffffeeeeeeee") == False
    assert candidate(s = "repeatedcharsrepeatedcharsrepeatedchars") == False
    assert candidate(s = "aaabbbcccdddeeefffggghhhiiiijjjkkklllmmmnnnooopppqqqrrrssstttuuuvvvwwwxxxyyyzzz") == False
    assert candidate(s = "samefrequencyforallcharacters") == False
    assert candidate(s = "lmnolmnolmnolmnolmnolmnolmnolmnolmnolmnolmnolmnolmnolmnolmnolmnolmnolmnolmnolmnolmnolmnolmnolmnolmnolmnolmno") == True
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == False
    assert candidate(s = "mnopqrsmnopqrsmnopqrsmnopqrsmnopqrs") == True
    assert candidate(s = "abcdefabcdefabcdef") == True
    assert candidate(s = "abacadaeafagahaibiciidieifigihiiijijikikililimimioinioipoipiqiririsititiuiujujukukululumiumiujujukvkvkwlwlxmxmylynzozp") == False
    assert candidate(s = "mnopqrstuvwxyzabcdefghijklmnopqrstuvwxyza") == False
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzqqqq") == False
    assert candidate(s = "abracadabra") == False
    assert candidate(s = "mnopqrstuvwxymnopqrstuvwxymnopqrstuvwxymnopqrstuvwxyn") == False
    assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij") == True
    assert candidate(s = "qwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiop") == True
    assert candidate(s = "abcdefabcdef") == True
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz") == True
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd") == True
    assert candidate(s = "almostgoodbutoneextraa") == False
    assert candidate(s = "abcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnop") == True
    assert candidate(s = "jjjjkkkkllllmmmmnnnnooooppppqqqqrrrrssssttttuuuuvvvvwwwwxxxxyyyyzzzzaaaaaa") == False
    assert candidate(s = "zzzzzyyyyxxxwwvvuuttssrrqqlloommnnppekkaaiioouuyy") == False
    assert candidate(s = "racecar") == False
    assert candidate(s = "almostgoodbutoneextrac") == False
    assert candidate(s = "xyzxyzxyz") == True
    assert candidate(s = "qwerqwerqwer") == True
    assert candidate(s = "abababababababab") == True
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == True
    assert candidate(s = "abcdefghijabcdefghijabcdefghij") == True
    assert candidate(s = "ppppppqqqqqrrrrrssssstttttuuuuuvvvvvwwwwwooooo") == False
    assert candidate(s = "ababababc") == False
    assert candidate(s = "mmnnnmmmnnnmmmnnnmmmnnnmmmnnnmmmnnnmmmnnnmm") == False
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzz") == False
    assert candidate(s = "pqrspqrspqrspqrspqrspqrspqrspqrspqrspqrspqrspqrspqrspqrspqrspqrspqrspqrspqrspqrspqrspqrspqrspqrspqrspqrspqrspqrs") == True
    assert candidate(s = "mmnnooppqqrrssttuuvvwwxxyyzzqqwweerrttyyuuiihhggffeeddccba") == False
    assert candidate(s = "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy") == True
    assert candidate(s = "ppppqqqqrrrrssssttttuuuuvvvvwwwwxxxxyyyyzzzz") == True
    assert candidate(s = "mnopmnopmnopmnopmnopmnopmnopmnop") == True
    assert candidate(s = "xyzzzzzyzx") == False
    assert candidate(s = "abacabadabacabad") == False
    assert candidate(s = "abcdefghijklmnopqrstuvwxzyabcdefghijklmnopqrstuvwxzy") == True
    assert candidate(s = "abcdefghijklmnop") == True
    assert candidate(s = "xyzzxyzzxyzzxyzzxyzzxyzz") == False
    assert candidate(s = "zzzyyyxxxwwwwvvvvuuuuuuuuutttttttsssssssrrrrrrqqqqpppooooonnnnmmmmllllkkkkjjjjiiiihhhhhgggggfffffeeeeeeeee") == False
    assert candidate(s = "mnopqrmpqrno") == True
    assert candidate(s = "qqwweerrttyyuuuiooppppllkkiijjhgffeeddccba") == False
    assert candidate(s = "qrstuvwxyzabcdefghijklmnopqrstuvwxyz") == False
    assert candidate(s = "mississippi") == False
    assert candidate(s = "xyzzxyzzxyzzxyzz") == False
    assert candidate(s = "oneonetwoonetwothree") == False
    assert candidate(s = "zxcvbnmzxcvbnmzxcvbnmzxcvbnmzxcvbnmzxcvbnmzxcvbnmzxcvbnmzxcvbnmzxcvbnmzxcvbnmzxcvbnmzxcvbnmzxcvbnmzxcvbnm") == True
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == True
    assert candidate(s = "xyzxyzxyzxyz") == True
    assert candidate(s = "zzzzyyyyxxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccbbaa") == False
    assert candidate(s = "qqqqwweerrrrtttyyyy") == False
    assert candidate(s = "abcdabcdabcdabcd") == True
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba") == False
    assert candidate(s = "almostgoodbutoneextrad") == False
    assert candidate(s = "almostgoodbutoneextrae") == False
    assert candidate(s = "programming") == False
    assert candidate(s = "equalfrequenciesequalfrequencies") == False
    assert candidate(s = "xyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == False
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzabc") == False
    assert candidate(s = "almostgoodbutoneextraf") == False
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzabcdefghij") == False
