# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "b") == True
    assert candidate(s = "aaaaabbbbb") == True
    assert candidate(s = "bbb") == True
    assert candidate(s = "ab") == True
    assert candidate(s = "aabbaa") == False
    assert candidate(s = "ba") == False
    assert candidate(s = "bba") == False
    assert candidate(s = "aaa") == True
    assert candidate(s = "aabbaabb") == False
    assert candidate(s = "aaabbb") == True
    assert candidate(s = "a") == True
    assert candidate(s = "aabbabbb") == False
    assert candidate(s = "abab") == False
    assert candidate(s = "abbb") == True
    assert candidate(s = "aaaaaaaaaabbbbbbbbbb") == True
    assert candidate(s = "abababbabababbab") == False
    assert candidate(s = "baaa") == False
    assert candidate(s = "bbbbbbbbbb") == True
    assert candidate(s = "aabababababbb") == False
    assert candidate(s = "bbbbbaaaaaaaaa") == False
    assert candidate(s = "ababbab") == False
    assert candidate(s = "aaaabbbbbaaabb") == False
    assert candidate(s = "baaabbb") == False
    assert candidate(s = "bbaaabbb") == False
    assert candidate(s = "abbbab") == False
    assert candidate(s = "aabbbbbba") == False
    assert candidate(s = "aabbbbbaaab") == False
    assert candidate(s = "aabaa") == False
    assert candidate(s = "aabaaabba") == False
    assert candidate(s = "aabbbbabbab") == False
    assert candidate(s = "aaaaaaaaaa") == True
    assert candidate(s = "babbaabbaabbaabb") == False
    assert candidate(s = "baaabaaa") == False
    assert candidate(s = "bbbbbbbaaaaaa") == False
    assert candidate(s = "aaaababbbb") == False
    assert candidate(s = "aabbbbaaa") == False
    assert candidate(s = "aaaa") == True
    assert candidate(s = "bbbbbbbbbaaaaaaaaa") == False
    assert candidate(s = "bbbbbaaaa") == False
    assert candidate(s = "aabbaabbabba") == False
    assert candidate(s = "aaaaaaaaa") == True
    assert candidate(s = "aaabbaabbb") == False
    assert candidate(s = "bbbbbaaaaa") == False
    assert candidate(s = "aaabba") == False
    assert candidate(s = "bbbbaaab") == False
    assert candidate(s = "aabbabb") == False
    assert candidate(s = "bbab") == False
    assert candidate(s = "baaaab") == False
    assert candidate(s = "bbbbabaa") == False
    assert candidate(s = "aabbbbba") == False
    assert candidate(s = "baaabbbb") == False
    assert candidate(s = "bbbaaa") == False
    assert candidate(s = "abbbbaaaaa") == False
    assert candidate(s = "aaaaaabbbbbb") == True
    assert candidate(s = "aaabbbaa") == False
    assert candidate(s = "bbbbba") == False
    assert candidate(s = "aaaabbbbaaaa") == False
    assert candidate(s = "bab") == False
    assert candidate(s = "bbaabbba") == False
    assert candidate(s = "aaaaabbbbbaaa") == False
    assert candidate(s = "baaaabbb") == False
    assert candidate(s = "aabbaabbb") == False
    assert candidate(s = "aaaabbbbba") == False
    assert candidate(s = "bababababa") == False
    assert candidate(s = "abbbbaaa") == False
    assert candidate(s = "bbaaaabbb") == False
    assert candidate(s = "aabbbbbbaaaa") == False
    assert candidate(s = "aaabb") == True
    assert candidate(s = "aabaaaabbb") == False
    assert candidate(s = "aaaaaaaaaabbbbbbbb") == True
    assert candidate(s = "aaabbbaaab") == False
    assert candidate(s = "ababababababab") == False
    assert candidate(s = "aabbabaa") == False
    assert candidate(s = "bbbbaa") == False
    assert candidate(s = "aaaaaaaaaaabbbbbbbbbbb") == True
    assert candidate(s = "bbbbbaab") == False
    assert candidate(s = "bbbbbaaabbaabbaabb") == False
    assert candidate(s = "abbbbbba") == False
    assert candidate(s = "aaaaaaaaabbbbbbbb") == True
    assert candidate(s = "bbbaaaaa") == False
    assert candidate(s = "abbbba") == False
    assert candidate(s = "aaaabbbbbbba") == False
    assert candidate(s = "aaaaaab") == True
    assert candidate(s = "babababaab") == False
    assert candidate(s = "abababab") == False
    assert candidate(s = "aaaaa") == True
    assert candidate(s = "bbaaaa") == False
    assert candidate(s = "aabbbbaa") == False
    assert candidate(s = "aababbaa") == False
    assert candidate(s = "aabbbbbaa") == False
    assert candidate(s = "abbbbbbaaaaa") == False
    assert candidate(s = "aaabbbbbba") == False
    assert candidate(s = "bbbbbbbbaaaa") == False
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbb") == True
    assert candidate(s = "bbbbbaaaaabbb") == False
    assert candidate(s = "bbaabbabaa") == False
    assert candidate(s = "aabb") == True
    assert candidate(s = "ababbabababbab") == False
    assert candidate(s = "bbbbbbbbbaaaaa") == False
    assert candidate(s = "aaaabbbaaabb") == False
    assert candidate(s = "bababaaaabbbb") == False
    assert candidate(s = "bbaaa") == False
    assert candidate(s = "aabbaaabaaaabbbb") == False
    assert candidate(s = "aabababb") == False
    assert candidate(s = "bbbb") == True
    assert candidate(s = "aabbaabbbb") == False
    assert candidate(s = "baaaaa") == False
    assert candidate(s = "bbbbbaaaaabbbb") == False
    assert candidate(s = "aabbaaa") == False
    assert candidate(s = "ababab") == False
    assert candidate(s = "babbba") == False
    assert candidate(s = "bbbbbbbb") == True
    assert candidate(s = "aaabbbab") == False
    assert candidate(s = "bbaaaaaaab") == False
    assert candidate(s = "aaaaabbbbbbbba") == False
    assert candidate(s = "bbbbaaaaaa") == False
    assert candidate(s = "aabbabbbaabbb") == False
    assert candidate(s = "bababababab") == False
    assert candidate(s = "bbbaa") == False
    assert candidate(s = "bbbbbbbbb") == True
    assert candidate(s = "baaaabbbb") == False
    assert candidate(s = "aaaaabbbbbbbbb") == True
    assert candidate(s = "aabbba") == False
    assert candidate(s = "bababbababababab") == False
    assert candidate(s = "bbbbbbbbbaaab") == False
    assert candidate(s = "baab") == False
    assert candidate(s = "baaabb") == False
    assert candidate(s = "ababababbabababb") == False
    assert candidate(s = "bababbab") == False
    assert candidate(s = "ababababab") == False
    assert candidate(s = "bbbaaaaabbbbbbbbaaaa") == False
    assert candidate(s = "aabbbbbaaaa") == False
    assert candidate(s = "aabbbbb") == True
    assert candidate(s = "bbaa") == False
    assert candidate(s = "bbbaababbb") == False
    assert candidate(s = "bbbbaaaa") == False
    assert candidate(s = "baaab") == False
    assert candidate(s = "aaaaaabbbbba") == False
    assert candidate(s = "abaaa") == False
    assert candidate(s = "bbbaaabbb") == False
    assert candidate(s = "babababa") == False
    assert candidate(s = "aab") == True
    assert candidate(s = "bbbbbbbaaaaaaaaa") == False
    assert candidate(s = "abbbabab") == False
    assert candidate(s = "bbbbaabbaabb") == False
    assert candidate(s = "aabbbba") == False
    assert candidate(s = "aaaaaaaa") == True
    assert candidate(s = "aababbababaa") == False
    assert candidate(s = "aabbababab") == False
    assert candidate(s = "abbbbaaaab") == False
    assert candidate(s = "bbaaabbaaab") == False
    assert candidate(s = "aabbaab") == False
