# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "aaabbbccc") == False
    assert candidate(s = "aababcbccabc") == False
    assert candidate(s = "cababc") == False
    assert candidate(s = "abcabcabc") == True
    assert candidate(s = "aababcbabc") == False
    assert candidate(s = "abcabcabcabc") == True
    assert candidate(s = "aabcbc") == True
    assert candidate(s = "") == True
    assert candidate(s = "abcabc") == True
    assert candidate(s = "abcabcababcc") == True
    assert candidate(s = "bcaabc") == False
    assert candidate(s = "aabcabcabc") == False
    assert candidate(s = "bca") == False
    assert candidate(s = "abc") == True
    assert candidate(s = "aabababc") == False
    assert candidate(s = "abcabcabcabcabcabc") == True
    assert candidate(s = "abcabcabacbc") == False
    assert candidate(s = "ababcabcababcc") == False
    assert candidate(s = "abccba") == False
    assert candidate(s = "cab") == False
    assert candidate(s = "aabbcc") == False
    assert candidate(s = "aabcbcababc") == False
    assert candidate(s = "aabcbabcbabc") == False
    assert candidate(s = "aabcbabcbabccba") == False
    assert candidate(s = "aababababababcabcabcabcabcabc") == False
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == True
    assert candidate(s = "aababababababcabcababc") == False
    assert candidate(s = "aabcbcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == True
    assert candidate(s = "ababcabcabcababcabcababcabc") == False
    assert candidate(s = "abcabcabababcabc") == False
    assert candidate(s = "ababcabcabcabcababc") == False
    assert candidate(s = "ababcababcababcababcababcc") == False
    assert candidate(s = "abcabababcababcabc") == False
    assert candidate(s = "aababababcbcbcbc") == False
    assert candidate(s = "aabbbccabcabcabcabcabcabcab") == False
    assert candidate(s = "aabbabccbababc") == False
    assert candidate(s = "aaaabbbbcccc") == False
    assert candidate(s = "abcabababababababc") == False
    assert candidate(s = "aababcabcbaabc") == False
    assert candidate(s = "aabcbabcbabcbabcbabcbabc") == False
    assert candidate(s = "abcabababababababcababababababc") == False
    assert candidate(s = "abcabccbaabc") == False
    assert candidate(s = "abcabcababababcabc") == False
    assert candidate(s = "aabcbcaabcab") == False
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabc") == True
    assert candidate(s = "aabcbabcababcabcba") == False
    assert candidate(s = "aabcbcababcbcababc") == False
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabc") == True
    assert candidate(s = "aabcbabcabcbabcabcbabcabcbabcabcbabcabc") == False
    assert candidate(s = "abccabccabccabccabccabccabccabccabcc") == False
    assert candidate(s = "aababcababcabcabcabcabcababcc") == False
    assert candidate(s = "aabcbcaabcbcaabcbcaabcbcaabc") == False
    assert candidate(s = "abcabcabcabcabcabcabc") == True
    assert candidate(s = "abcabcabcabcabcabcab") == False
    assert candidate(s = "abababcabcabcabc") == False
    assert candidate(s = "abababcabcabcabcabc") == False
    assert candidate(s = "abccababccababcc") == False
    assert candidate(s = "ababcabcababcabcabcabcabc") == False
    assert candidate(s = "abccbaabccbaabccba") == False
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc") == True
    assert candidate(s = "aabcbcabcabcabcabcbcaabbcc") == False
    assert candidate(s = "aabababababababcabcabc") == False
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == True
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == True
    assert candidate(s = "aabcbcababcbcababccba") == False
    assert candidate(s = "ababababcabcabc") == False
    assert candidate(s = "ababababababcabcabcababc") == False
    assert candidate(s = "abccabccabccabccabccabcc") == False
    assert candidate(s = "aabcbabcbababc") == False
    assert candidate(s = "abcabcababccabcabcab") == False
    assert candidate(s = "aabcbcabcabababcabcabcabababcabcab") == False
    assert candidate(s = "aabcbcaabcbcaabcbcaabc") == False
    assert candidate(s = "aabcbabcabcbabcabcbabcabc") == False
    assert candidate(s = "abcabababcabababc") == False
    assert candidate(s = "ababababababcabcabcabcabcabc") == False
    assert candidate(s = "aaabbbcccaabbbcccaabbbcccabcabcabc") == False
    assert candidate(s = "abcababccbaabc") == False
    assert candidate(s = "abcabcabcabcabcabcabccbaabccba") == False
    assert candidate(s = "aabcbabababcabcabc") == False
    assert candidate(s = "aabcbcababccbaabcbcbcabcababcababcbc") == False
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabccba") == False
    assert candidate(s = "abcababababcabab") == False
    assert candidate(s = "abcababcababcababc") == False
    assert candidate(s = "aabcbcababccbaabccba") == False
    assert candidate(s = "abababababcabababcabc") == False
    assert candidate(s = "aabcbcababcbcababcbcabababcabcabccba") == False
    assert candidate(s = "aabcbabcbabcbabcbabcbabcbabcbabc") == False
    assert candidate(s = "aababababababababcabcababcababcc") == False
    assert candidate(s = "aabbccabcabcabcabcabcabcabc") == False
    assert candidate(s = "abababababababababababcabcabcabcabcabcabc") == False
    assert candidate(s = "aabcbcabcabcabcabcabccbaabc") == False
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbcccccccccc") == False
    assert candidate(s = "abababababababababababc") == False
    assert candidate(s = "abababababababababababcabcabc") == False
    assert candidate(s = "aabcaabbccabcabcabc") == False
    assert candidate(s = "ababcababcababcababcababcababcababcabcabcc") == False
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabc") == True
    assert candidate(s = "abcabababababababababababababcabcabcababcabc") == False
    assert candidate(s = "abcabcabcabcabccba") == False
    assert candidate(s = "aabcbcababccbaabcbcbcabcababcababcbcababccba") == False
    assert candidate(s = "abcabcababcabcabcabababc") == False
    assert candidate(s = "aaabbbbcccc") == False
    assert candidate(s = "abcabababcababababc") == False
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == True
    assert candidate(s = "ababababcabcabcababc") == False
    assert candidate(s = "abccabccabccabccabccabccabccabccabccabccabcc") == False
    assert candidate(s = "ababcababcababcababcababcababcababcababc") == False
    assert candidate(s = "abcababababababababababababcabcabcab") == False
    assert candidate(s = "abababababababababababababcabcabcabcabcabcabcabc") == False
    assert candidate(s = "abccabccabccabcabcabc") == False
    assert candidate(s = "aababcababcababcababcab") == False
    assert candidate(s = "abcabcabcabccbaabc") == False
    assert candidate(s = "aababcabcabcababcc") == False
    assert candidate(s = "aabcbcaabcbcaabc") == False
    assert candidate(s = "abcabcabcabababcababc") == False
    assert candidate(s = "abcababcababcababcababcab") == False
    assert candidate(s = "abcabcabcabcababcabc") == False
    assert candidate(s = "abacbabcbacbabcbabc") == False
    assert candidate(s = "aabccbaabcabcabc") == False
    assert candidate(s = "abccbaabcabcabcabcabc") == False
    assert candidate(s = "abababababcabcabcabc") == False
    assert candidate(s = "aabbabccbababcabcabc") == False
    assert candidate(s = "abcabcabcabcabcabcabcabcabc") == True
    assert candidate(s = "abcabcabcabcabcabccba") == False
    assert candidate(s = "abcabcabcabcabcabcabcabc") == True
    assert candidate(s = "abcabcababcababc") == False
    assert candidate(s = "aabcbcababcbcababcbcababcabc") == False
    assert candidate(s = "ababababababababc") == False
    assert candidate(s = "aabcbabcbabcbabc") == False
    assert candidate(s = "ababcababcababcababcababcababcabcabc") == False
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabc") == True
    assert candidate(s = "aabcbcabcabcabcabcabcabcabcabcabcabcabc") == True
    assert candidate(s = "abcabcabcababccbaabc") == False
    assert candidate(s = "abcababababcabcabcab") == False
    assert candidate(s = "aabcbcabcabcabcabcabcabcabcbc") == False
    assert candidate(s = "aabababababababababababababababcabcabc") == False
    assert candidate(s = "aabcbcbcbcabcabcabc") == False
    assert candidate(s = "abccabcabcabcabcab") == False
    assert candidate(s = "abababababababababababababababababababcabcabc") == False
    assert candidate(s = "aabcbcababccbaabcbcbc") == False
