# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 1
    assert candidate(s = "tourist") == 1
    assert candidate(s = "a") == 1
    assert candidate(s = "aabbbbccc") == 4
    assert candidate(s = "cccccaaaa") == 5
    assert candidate(s = "bbaaaaacccddddeeeefffggghhhiiijjjkkkllmmnnnooopppqqrrssttuuvvwwwxxxyyyzzz") == 5
    assert candidate(s = "leetcode") == 2
    assert candidate(s = "zzzzzzzzzz") == 10
    assert candidate(s = "hooray") == 2
    assert candidate(s = "ccbccbbbaaaa") == 4
    assert candidate(s = "triplepilloooooo") == 6
    assert candidate(s = "aabbbcccccdd") == 5
    assert candidate(s = "abcd") == 1
    assert candidate(s = "ccbccbb") == 2
    assert candidate(s = "aabbcc") == 2
    assert candidate(s = "cc") == 2
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 2
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba") == 1
    assert candidate(s = "abbcccddddeeeeedcba") == 5
    assert candidate(s = "abcdeffffffffghijklmnopqrstuvwxyz") == 8
    assert candidate(s = "aaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaab") == 4
    assert candidate(s = "pppppqqqqqrrrrrsssss") == 5
    assert candidate(s = "aaabbaaabbbaaaabbaaabbaaabbaaabbaaabbaaabbaaabbaaabbaaabbaaabbaaabbaaabbaaabbaaabbaaabbaaabbaa") == 4
    assert candidate(s = "ababababababababababab") == 1
    assert candidate(s = "aaaaaaaaaaa") == 11
    assert candidate(s = "mmmmmmnnnnnnooooooppppppqqqqqqrrrrrrssssssttttttuuuuuuvvvvvvwwwwwwxxxxxxxxxyyyyyyzzzzzz") == 9
    assert candidate(s = "aaaabbbbccccddddeeeeffffgggghhhiiijjjkkklllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 28
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 96
    assert candidate(s = "aaaaaaabbbbbbcccccc") == 7
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 1
    assert candidate(s = "abcdefffffffffghijklmnopqrstuvwxyz") == 9
    assert candidate(s = "aaabbbcccdddeeefffggghhhiiiijjjkkklllmmmnnnooopppqqqrrrssstttuuuvvvwwwxxxyyyzzz") == 4
    assert candidate(s = "abacabadabacaba") == 1
    assert candidate(s = "aabbbccccdddddeeeeeeeeefffffffffggggggggggg") == 11
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 188
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc") == 1
    assert candidate(s = "abcdddddddddddabcdddddddddddabcddddddddddd") == 11
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbcccccccccc") == 10
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 88
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 1
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 202
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb") == 180
    assert candidate(s = "aabaaaaccaaaaabbb") == 5
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd") == 10
    assert candidate(s = "mnopqrstuvwxyzaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbccccccccccccccccccdddddddddddddddddddd") == 26
    assert candidate(s = "aabcccccaaaaddddddeeeeffffggggghhhhiiiiijjjjjkkkkklllllmmmmmnnnnnooooo") == 6
    assert candidate(s = "zzzzzyyyyyzzzzzzzzz") == 9
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 1
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 1
    assert candidate(s = "aabbaabbccbbccddeeffggffhhiiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 3
    assert candidate(s = "aabbccddeeeefffbbbccc") == 4
    assert candidate(s = "aabbaaabbbaaaabbbaaabbaaaabbbaaaabbbaaabbaaaabbbaaaabbbaaabbaaaabbbaaaabbbaaabbaaaabbbaaaabbbaaabbaaaabbbaaaabbbaaabbaaaabbbaaaabbbaaabbaaaabbbaaaabbbaaabbaaaabbbaaaa") == 4
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 152
    assert candidate(s = "aaaaabbbbbccccccdddddeeeeeeffffffgggggghhhhhiiiiiijjjjjkkkkklllllmmmmmnnnnnooooo") == 6
    assert candidate(s = "abcabcabcabcabcabc") == 1
    assert candidate(s = "abccbaabccbaabccbaabccbaabccbaabccbaabccbaabccba") == 2
    assert candidate(s = "aabbbcccdddeeefffggghhh") == 3
    assert candidate(s = "zzzzzyyyyxxwwwwvvvuuutttsssrqqpponnmmllkkjjiihhggffeeddccbbaa") == 5
    assert candidate(s = "aaabbbcccddddeeeeffffggggg") == 5
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 51
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 34
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzz") == 6
    assert candidate(s = "pppppaaaabbbbccccdddddeeeeeeeeeffffffggggggggggghhhhhhhhhiiiiiiiijjjjjjjkkkkkkllllllmmmmmmnnnnnoooooopppppqqqqrrrrsssttttuuuuuuuuuuuuvvvvvvvvvvvvvvvwwwwwwwwwwwxxxxxyyyyyyyyyyyyyzzzzzzzzzzzzzzzzz") == 17
    assert candidate(s = "aabbbccccdddddeeeee") == 5
    assert candidate(s = "abcabcabcabcabc") == 1
    assert candidate(s = "sssssssqqqqqqqqqqppppppooooonnnnnnmmmmmmm") == 10
    assert candidate(s = "abababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababab") == 1
    assert candidate(s = "mnonononoqpqrstuvwxyzzzzzzzz") == 8
    assert candidate(s = "aabbccddeeffaabbccddeeff") == 2
    assert candidate(s = "aabbbcccddddeeeeeffffffggggg") == 6
