# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(pattern = "DDD") == "4321"
    assert candidate(pattern = "IIIDIDDD") == "123549876"
    assert candidate(pattern = "ID") == "132"
    assert candidate(pattern = "IIDDD") == "126543"
    assert candidate(pattern = "DDIII") == "321456"
    assert candidate(pattern = "IDID") == "13254"
    assert candidate(pattern = "IIII") == "12345"
    assert candidate(pattern = "DI") == "213"
    assert candidate(pattern = "IID") == "1243"
    assert candidate(pattern = "DDIDDIID") == "321654798"
    assert candidate(pattern = "IDIDIDID") == "132547698"
    assert candidate(pattern = "I") == "12"
    assert candidate(pattern = "DID") == "2143"
    assert candidate(pattern = "IIIII") == "123456"
    assert candidate(pattern = "DDDDD") == "654321"
    assert candidate(pattern = "D") == "21"
    assert candidate(pattern = "DDDD") == "54321"
    assert candidate(pattern = "DDIIDDIID") == None
    assert candidate(pattern = "IDIDIDIDID") == None
    assert candidate(pattern = "DDDIDIII") == "432165789"
    assert candidate(pattern = "DDDDDDIIIIIIII") == None
    assert candidate(pattern = "DDDIIIII") == "432156789"
    assert candidate(pattern = "IIIIIIIII") == None
    assert candidate(pattern = "IDDDDDID") == "176543298"
    assert candidate(pattern = "IDDDDDIDI") == None
    assert candidate(pattern = "DDIDIDIDIDIDID") == None
    assert candidate(pattern = "IIDID") == "124365"
    assert candidate(pattern = "DIIIDDDI") == "213487659"
    assert candidate(pattern = "DDDDDDDDDD") == None
    assert candidate(pattern = "IIIIIIIIII") == None
    assert candidate(pattern = "IIDDDDDDII") == None
    assert candidate(pattern = "DDIIDIDID") == None
    assert candidate(pattern = "IIIIIIDDD") == None
    assert candidate(pattern = "DDDDDDD") == "87654321"
    assert candidate(pattern = "DIDIDIDI") == "214365879"
    assert candidate(pattern = "IIDDDDDDD") == None
    assert candidate(pattern = "DDDDDDDD") == "987654321"
    assert candidate(pattern = "IIDDIIDDI") == None
    assert candidate(pattern = "IIDDDIIID") == None
    assert candidate(pattern = "DDDDIIII") == "543216789"
    assert candidate(pattern = "DDIIDDDDD") == None
    assert candidate(pattern = "IIDIDIDDD") == None
    assert candidate(pattern = "IIIIIDDDDDD") == None
    assert candidate(pattern = "IDIDIDDDDD") == None
    assert candidate(pattern = "IIIDIDID") == "123547698"
    assert candidate(pattern = "IDDDIIDI") == "154326879"
    assert candidate(pattern = "IIDIDDDI") == "124387659"
    assert candidate(pattern = "IIDDIDDIID") == None
    assert candidate(pattern = "DDDDDDDDDDDD") == None
    assert candidate(pattern = "DIDIDID") == "21436587"
    assert candidate(pattern = "IIIDDDIID") == None
    assert candidate(pattern = "DDIIIDDDIDI") == None
    assert candidate(pattern = "IIDDIIIIID") == None
    assert candidate(pattern = "DDDDIII") == "54321678"
    assert candidate(pattern = "IDIDID") == "1325476"
    assert candidate(pattern = "IIDIDIDI") == "124365879"
    assert candidate(pattern = "DDDDDDDDD") == None
    assert candidate(pattern = "DDDDDDI") == "76543218"
    assert candidate(pattern = "DDIDDDID") == "321765498"
    assert candidate(pattern = "DDIIIIIII") == None
    assert candidate(pattern = "DIIIIIII") == "213456789"
    assert candidate(pattern = "IIIDDDDDDID") == None
    assert candidate(pattern = "IDDDIDII") == "154327689"
    assert candidate(pattern = "DDIIDIDDDI") == None
    assert candidate(pattern = "DDDDIIIID") == None
    assert candidate(pattern = "DDIDIDID") == "321547698"
    assert candidate(pattern = "IIIDDDDD") == "123987654"
    assert candidate(pattern = "DDDDDIIIIII") == None
    assert candidate(pattern = "IIIDDDDIII") == None
    assert candidate(pattern = "IIIIIIIDDDDDD") == None
    assert candidate(pattern = "IIIIIID") == "12345687"
    assert candidate(pattern = "IIIIIIIIIII") == None
    assert candidate(pattern = "IDIDDDID") == "132765498"
    assert candidate(pattern = "IDIDIDIDIDIDID") == None
    assert candidate(pattern = "IDIDIIDID") == None
    assert candidate(pattern = "IIIIIII") == "12345678"
    assert candidate(pattern = "DDIIDDDD") == "321498765"
    assert candidate(pattern = "IIIIIIID") == "123456798"
    assert candidate(pattern = "IDIDIDIDIDID") == None
    assert candidate(pattern = "DIIDIDID") == "213547698"
    assert candidate(pattern = "DDIIDIDI") == "321465879"
    assert candidate(pattern = "DDDIIIDID") == None
    assert candidate(pattern = "IIDDDIIII") == None
    assert candidate(pattern = "IIDDDIID") == "126543798"
    assert candidate(pattern = "IIDDDIII") == "126543789"
    assert candidate(pattern = "IDIDIDIDIDIDIDID") == None
    assert candidate(pattern = "DIDID") == "214365"
    assert candidate(pattern = "DDDDDIII") == "654321789"
    assert candidate(pattern = "DDII") == "32145"
    assert candidate(pattern = "DDDIDDDD") == "432198765"
    assert candidate(pattern = "IIIDDDIDDD") == None
    assert candidate(pattern = "DDIDDDDDDID") == None
    assert candidate(pattern = "IDDDDDD") == "18765432"
    assert candidate(pattern = "IDII") == "13245"
    assert candidate(pattern = "DDDDDDII") == "765432189"
    assert candidate(pattern = "IIIDDDDI") == "123876549"
    assert candidate(pattern = "IDDDIDID") == "154327698"
    assert candidate(pattern = "IIIIIDDI") == "123458769"
    assert candidate(pattern = "DDDDDD") == "7654321"
    assert candidate(pattern = "IIDDDIDDDDD") == None
    assert candidate(pattern = "IIIIIDDD") == "123459876"
    assert candidate(pattern = "IDIDDDIDID") == None
    assert candidate(pattern = "IIIIIIIID") == None
    assert candidate(pattern = "DDDDDDDDDDDID") == None
    assert candidate(pattern = "IIIIIDDDD") == None
    assert candidate(pattern = "DDDDIID") == "54321687"
    assert candidate(pattern = "IDDDIIDDD") == None
    assert candidate(pattern = "IIIDDDDDDDDDD") == None
    assert candidate(pattern = "DDIIDDID") == "321476598"
    assert candidate(pattern = "IIDDDDDD") == "129876543"
    assert candidate(pattern = "IIDDDII") == "12654378"
    assert candidate(pattern = "DDIIDIDD") == "321465987"
    assert candidate(pattern = "IIDDIIDD") == "125436987"
    assert candidate(pattern = "IIIIIIII") == "123456789"
    assert candidate(pattern = "IIIDDDD") == "12387654"
    assert candidate(pattern = "DDIID") == "321465"
