# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "aabbcc") == 9
    assert candidate(s = "bbccdd") == 9
    assert candidate(s = "zzzzz") == 15
    assert candidate(s = "aaaba") == 8
    assert candidate(s = "abcdabcdabcd") == 12
    assert candidate(s = "ababab") == 6
    assert candidate(s = "zzz") == 6
    assert candidate(s = "ababababab") == 10
    assert candidate(s = "abc") == 3
    assert candidate(s = "aaaaabbbb") == 25
    assert candidate(s = "aa") == 3
    assert candidate(s = "zzzzy") == 11
    assert candidate(s = "abcdabcd") == 8
    assert candidate(s = "aaaaaaaaaa") == 55
    assert candidate(s = "zzzzzxyzzy") == 21
    assert candidate(s = "bbaaaabbb") == 19
    assert candidate(s = "a") == 1
    assert candidate(s = "abcdefghijjihgfedcba") == 21
    assert candidate(s = "aaabbbccc") == 18
    assert candidate(s = "aaaabbbbccccddddeeeeffffgggghhhhiiii") == 90
    assert candidate(s = "aabbccddeeefffggghhhhiiiijjjjkkkkllllmmmmnnnnoooo") == 110
    assert candidate(s = "qqqqqqqqqqppppppppooonnnnmmmmlllkkkjjjiii") == 141
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "xyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 5673
    assert candidate(s = "aaabaaaabaaaabaaaab") == 40
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 990
    assert candidate(s = "abacabadabacaba") == 15
    assert candidate(s = "abcabcabc") == 9
    assert candidate(s = "aabbccddeeefffggg") == 30
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzz") == 141
    assert candidate(s = "abbbbbccccddddeeeeefffffgggggg") == 87
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd") == 220
    assert candidate(s = "abcde") == 5
    assert candidate(s = "aabbccddeeefffggghhhiii") == 42
    assert candidate(s = "mnoooppnnooo") == 20
    assert candidate(s = "abccccccba") == 25
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 5778
    assert candidate(s = "mnopqrssrqpomnopqrssrqpomn") == 28
    assert candidate(s = "aabbbbcccccccdddddddddeeeeeeeeeeffffffffffggggggggggg") == 262
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 53
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbccccccccccccc") == 613
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbb") == 1959
    assert candidate(s = "ababababababababababababababababababababababababababababab") == 58
    assert candidate(s = "aabccddeeeaaa") == 22
    assert candidate(s = "aaaaaabbbbbcccccccc") == 72
    assert candidate(s = "aabbbccddddeeefff") == 34
    assert candidate(s = "aabbaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 84
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 8853
    assert candidate(s = "aabbaaabbbaaaabbbbbaaaa") == 53
    assert candidate(s = "aabbccccdddddddeeeeeeeeefffffffffgggggggggggggggg") == 270
    assert candidate(s = "lllllllllllllll") == 120
    assert candidate(s = "xyxyxyxyxyxyxyxyxyxyxy") == 22
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 78
    assert candidate(s = "ppppqqqqrrrsssss") == 41
    assert candidate(s = "aabbcccddd") == 18
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1275
    assert candidate(s = "xyzzzyyxxy") == 15
