# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "zzz",c = "z") == 6
    assert candidate(s = "abcabcabc",c = "b") == 6
    assert candidate(s = "abcdefg",c = "f") == 1
    assert candidate(s = "",c = "a") == 0
    assert candidate(s = "abcabcabc",c = "a") == 6
    assert candidate(s = "hello",c = "l") == 3
    assert candidate(s = "xyz",c = "a") == 0
    assert candidate(s = "aaaaa",c = "a") == 15
    assert candidate(s = "abc",c = "a") == 1
    assert candidate(s = "abcabcabc",c = "c") == 6
    assert candidate(s = "aaa",c = "a") == 6
    assert candidate(s = "abada",c = "a") == 6
    assert candidate(s = "mississippi",c = "i") == 10
    assert candidate(s = "lalalalalalalala",c = "l") == 36
    assert candidate(s = "aabaaacaaadaaae",c = "e") == 1
    assert candidate(s = "bcbcbcbcb",c = "b") == 15
    assert candidate(s = "aabbccddeeff",c = "f") == 3
    assert candidate(s = "lkjkljkljkljklj",c = "k") == 15
    assert candidate(s = "repeatedcharactersrepeatedcharacters",c = "r") == 21
    assert candidate(s = "abcbcbcbc",c = "b") == 10
    assert candidate(s = "acbacbacbacbacbac",c = "a") == 21
    assert candidate(s = "racecar",c = "r") == 3
    assert candidate(s = "abababababa",c = "b") == 15
    assert candidate(s = "xyzzyxzyzxzyz",c = "z") == 21
    assert candidate(s = "pppppppppppp",c = "p") == 78
    assert candidate(s = "abcdefghijk",c = "j") == 1
    assert candidate(s = "pqrsrqpqrsrqpqrs",c = "r") == 15
    assert candidate(s = "bookkeeper",c = "e") == 6
    assert candidate(s = "aaaabbbcccddd",c = "b") == 6
    assert candidate(s = "noonnoonnoon",c = "n") == 21
    assert candidate(s = "xyxzyxzyxzyxzyx",c = "y") == 15
    assert candidate(s = "aaaaabaaaa",c = "a") == 45
    assert candidate(s = "aabbccddeeffgg",c = "g") == 3
    assert candidate(s = "banana",c = "a") == 6
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",c = "z") == 990
    assert candidate(s = "bbaabbaabbaa",c = "b") == 21
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm",c = "m") == 3
    assert candidate(s = "bananabananabanana",c = "a") == 45
    assert candidate(s = "aabbccddeeffgg",c = "b") == 3
    assert candidate(s = "abacabadabacaba",c = "a") == 36
    assert candidate(s = "aaaaabaaa",c = "a") == 36
    assert candidate(s = "qwertyuiop",c = "q") == 1
    assert candidate(s = "ababababab",c = "b") == 15
    assert candidate(s = "xyxzyxzyx",c = "x") == 10
    assert candidate(s = "abcdefghij",c = "a") == 1
    assert candidate(s = "zzzzzzzzzzzzzzzzz",c = "z") == 153
    assert candidate(s = "hellohellohello",c = "o") == 6
    assert candidate(s = "hello",c = "o") == 1
    assert candidate(s = "abcdefgabcdefgabcdefg",c = "d") == 6
    assert candidate(s = "qqwweerrttyyuuiioopp",c = "q") == 3
    assert candidate(s = "aabacabaa",c = "a") == 21
    assert candidate(s = "lkjlkjlkjlkj",c = "l") == 10
    assert candidate(s = "aaabaaaabaaaa",c = "a") == 66
    assert candidate(s = "aabbccddeeff",c = "d") == 3
    assert candidate(s = "aabbccddeeff",c = "c") == 3
    assert candidate(s = "abcdabcde",c = "d") == 3
    assert candidate(s = "aaaaabbbbbb",c = "b") == 21
    assert candidate(s = "ananananananananana",c = "n") == 45
    assert candidate(s = "abcababcabcab",c = "b") == 15
    assert candidate(s = "abacaba",c = "a") == 10
    assert candidate(s = "xyxzxyxzyzx",c = "x") == 15
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaa",c = "a") == 351
    assert candidate(s = "hellohellobyehello",c = "o") == 6
    assert candidate(s = "zzzzzzzzzzzzz",c = "z") == 91
    assert candidate(s = "aninterestingproblem",c = "n") == 6
    assert candidate(s = "abcdefghijabcdefghijabcdefghij",c = "i") == 6
    assert candidate(s = "llllllllllllllllllllllllll",c = "l") == 351
    assert candidate(s = "bcbcbcbcbcb",c = "b") == 21
    assert candidate(s = "bababababababa",c = "b") == 28
    assert candidate(s = "abcdefghefghijklmnopqrstuvwxyz",c = "a") == 1
    assert candidate(s = "abcdefghi",c = "a") == 1
    assert candidate(s = "aaaaabaaaaa",c = "a") == 55
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnmqwertyuiop",c = "q") == 3
    assert candidate(s = "abcdefghij",c = "j") == 1
    assert candidate(s = "thisisaverylongstringwithseveralcharacters",c = "t") == 10
    assert candidate(s = "abcdefghigklmnopqrstuvwxyz",c = "a") == 1
    assert candidate(s = "xyzzzyzxzyzxzyz",c = "z") == 36
    assert candidate(s = "zzzzzzzzzz",c = "z") == 55
    assert candidate(s = "xyzyxzyzxzyzx",c = "x") == 10
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",c = "z") == 3
    assert candidate(s = "xyzxyzxyzxyz",c = "x") == 10
    assert candidate(s = "abacabadaba",c = "a") == 21
    assert candidate(s = "programming",c = "m") == 3
    assert candidate(s = "aaabaaa",c = "a") == 21
    assert candidate(s = "anananananan",c = "a") == 21
    assert candidate(s = "cccccccccc",c = "c") == 55
    assert candidate(s = "cccccccccccccccccc",c = "c") == 171
    assert candidate(s = "xyzxyzxyz",c = "z") == 6
    assert candidate(s = "zazazazazaz",c = "z") == 21
    assert candidate(s = "abcdefghigklmnopqrstuvwxyz",c = "z") == 1
    assert candidate(s = "aabaaacaaadaaae",c = "a") == 66
    assert candidate(s = "bcbcbcbc",c = "b") == 10
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",c = "a") == 0
    assert candidate(s = "aabbccddeeffaabbccddeeff",c = "d") == 10
    assert candidate(s = "abcdefabcdefabcdef",c = "f") == 6
    assert candidate(s = "abracadabra",c = "a") == 15
    assert candidate(s = "aaaaaaaaaaaaaa",c = "a") == 105
    assert candidate(s = "popcornpopcorn",c = "p") == 10
    assert candidate(s = "xyxxyxyxy",c = "x") == 15
    assert candidate(s = "bbbbbbbbbb",c = "b") == 55
    assert candidate(s = "abcdefg",c = "g") == 1
    assert candidate(s = "hellohellohellohello",c = "l") == 36
    assert candidate(s = "abcdeabcdeabcde",c = "a") == 6
    assert candidate(s = "abcdefhijklmnopqrstuvwxyz",c = "z") == 1
    assert candidate(s = "aabbccddeeff",c = "b") == 3
