# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(word = "xyzyxzyzxzyz",k = 2) == 2
    assert candidate(word = "mississippi",k = 1) == 11
    assert candidate(word = "zzzzzzzzz",k = 9) == 1
    assert candidate(word = "abcdefghijklmnopqrstuvwxyz",k = 1) == 351
    assert candidate(word = "ababababab",k = 1) == 19
    assert candidate(word = "ababab",k = 2) == 3
    assert candidate(word = "ababababab",k = 2) == 7
    assert candidate(word = "abcdabcdabcd",k = 4) == 0
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 1) == 77
    assert candidate(word = "qrstuvqrstuvqrstuv",k = 3) == 0
    assert candidate(word = "mnopqrspqr",k = 2) == 0
    assert candidate(word = "zzzzzzzzz",k = 3) == 7
    assert candidate(word = "zyxwvutsrqponmlkjihgfedcba",k = 1) == 351
    assert candidate(word = "aabbccddeeffgghhii",k = 2) == 45
    assert candidate(word = "abacabadabacaba",k = 1) == 31
    assert candidate(word = "zzzzzzzzz",k = 2) == 8
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 5) == 46
    assert candidate(word = "mnopqrsmnopqrsmnopqrsmnopqrsmnopqrsmnopqrs",k = 4) == 0
    assert candidate(word = "abcdefg",k = 1) == 28
    assert candidate(word = "abcd",k = 1) == 10
    assert candidate(word = "abcabcabcabcabc",k = 3) == 7
    assert candidate(word = "aaabbbccc",k = 3) == 6
    assert candidate(word = "abcde",k = 1) == 15
    assert candidate(word = "abababababababababababababababababababababababababababababababababa",k = 2) == 64
    assert candidate(word = "xyzxyzxyz",k = 3) == 1
    assert candidate(word = "abcabcabcabcabcabcabcabcabcabcabcabcabc",k = 1) == 114
    assert candidate(word = "zzzzzzyyyxx",k = 2) == 10
    assert candidate(word = "xyzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 1) == 31
    assert candidate(word = "abcabcabcabc",k = 4) == 1
    assert candidate(word = "a",k = 1) == 1
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 26) == 25
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 5) == 40
    assert candidate(word = "abcabcabcabc",k = 3) == 4
    assert candidate(word = "igigee",k = 2) == 3
    assert candidate(word = "aaaaaa",k = 6) == 1
    assert candidate(word = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc",k = 3) == 58
    assert candidate(word = "abcabcabc",k = 3) == 1
    assert candidate(word = "xxxxxxyyyyyzzzzz",k = 5) == 7
    assert candidate(word = "abcabcabcabcabcabcabc",k = 3) == 13
    assert candidate(word = "aabbaa",k = 2) == 6
    assert candidate(word = "qqqqqqqqqqqqqqqqqqqq",k = 5) == 16
    assert candidate(word = "aaaabbbbcccc",k = 4) == 6
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 1) == 50
    assert candidate(word = "acacacacacacacacacacacacacacacacacacacacacacacacacacacacacacacacaca",k = 2) == 64
    assert candidate(word = "ababababababababababababab",k = 2) == 23
    assert candidate(word = "zzzzzz",k = 2) == 5
    assert candidate(word = "zzzzzzzzzz",k = 5) == 6
    assert candidate(word = "zzzyyyxxxwwvvuuttrrqqqppponnmmllkkjjiihhggffeeddccbbbaaa",k = 3) == 12
    assert candidate(word = "aaaabbbbccccddddeeeeffff",k = 4) == 21
    assert candidate(word = "aaaabbbbccccdddd",k = 4) == 10
    assert candidate(word = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc",k = 3) == 55
    assert candidate(word = "abacabadabacaba",k = 3) == 0
    assert candidate(word = "mississippi",k = 2) == 3
    assert candidate(word = "aaa",k = 1) == 3
    assert candidate(word = "aabbbcccaabb",k = 2) == 12
    assert candidate(word = "abcdefghi",k = 1) == 45
    assert candidate(word = "ababababababababababababababababababababab",k = 2) == 39
    assert candidate(word = "zzzyyyxxxwwwwvvvuuutttsssrrrqqqpppoonnmmmlllkkkjjjiii",k = 3) == 61
    assert candidate(word = "aabbcc",k = 2) == 6
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzzzz",k = 1) == 354
    assert candidate(word = "xyzyxzyzxzyx",k = 2) == 3
    assert candidate(word = "zzzzz",k = 5) == 1
    assert candidate(word = "abacaba",k = 1) == 15
    assert candidate(word = "aabbaabbaabbaabb",k = 2) == 21
    assert candidate(word = "abacabadabacaba",k = 2) == 0
    assert candidate(word = "abcdabcdeabcdabcde",k = 2) == 0
    assert candidate(word = "abcabcabc",k = 1) == 24
    assert candidate(word = "zzzzz",k = 1) == 5
    assert candidate(word = "mnopqr",k = 1) == 21
    assert candidate(word = "xyxxyxyxyx",k = 2) == 6
    assert candidate(word = "mnopqrsmnopqrsmnopqrsmnopqrs",k = 5) == 0
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 5) == 47
    assert candidate(word = "qwertyuiopasdfghjklzxcvbnm",k = 1) == 51
    assert candidate(word = "abcdefghij",k = 1) == 55
    assert candidate(word = "zzzaaa",k = 3) == 2
    assert candidate(word = "qqwweerrtt",k = 2) == 6
    assert candidate(word = "abcdefghijk",k = 1) == 66
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 2) == 351
    assert candidate(word = "abcdabcdabcd",k = 2) == 0
    assert candidate(word = "abcabcabcabcabcabcabcabcabcabc",k = 3) == 22
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzaaa",k = 1) == 354
    assert candidate(word = "aaaabbbbccccaaaabbbbcccc",k = 4) == 24
    assert candidate(word = "zzzzzz",k = 1) == 6
    assert candidate(word = "abcabcabcabcabcabc",k = 3) == 10
    assert candidate(word = "abababababababababab",k = 2) == 17
    assert candidate(word = "abcdef",k = 1) == 21
    assert candidate(word = "aabbccddeeaabbccddeeaabbccddeeddeeaabbcc",k = 2) == 57
    assert candidate(word = "abcdabc",k = 2) == 0
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 10) == 43
    assert candidate(word = "zzzyyyxxx",k = 3) == 6
    assert candidate(word = "xyzzzzzyxxyzzzzzyx",k = 3) == 6
