# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abba") == 6
    assert candidate(s = "abccba") == 14
    assert candidate(s = "abcba") == 10
    assert candidate(s = "abac") == 5
    assert candidate(s = "a") == 1
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcddcbadcbadcbadcbadcbadcbadcbadcba") == 104860361
    assert candidate(s = "aabbaa") == 10
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcd") == 29348
    assert candidate(s = "abcddcba") == 30
    assert candidate(s = "bccb") == 6
    assert candidate(s = "aaa") == 3
    assert candidate(s = "abcd") == 4
    assert candidate(s = "aabb") == 4
    assert candidate(s = "aaaa") == 4
    assert candidate(s = "abab") == 6
    assert candidate(s = "abacabadabacabadabacaba") == 2571
    assert candidate(s = "ababbabaabbababbab") == 212
    assert candidate(s = "aabbaabbaabb") == 44
    assert candidate(s = "aaaabbbbccccaaaabbbbccccaaaabbbbcccc") == 996
    assert candidate(s = "ddccbbbaaacccbdd") == 94
    assert candidate(s = "abcabcabcabc") == 84
    assert candidate(s = "aaaaabbbbbccccddddaaaaabbbbbccccddddaaaaabbbbbccccddddaaaaabbbbbccccddddaaaaabbbbbccccddddaaaaabbbbbccccddddaaaaabbbbbccccdddd") == 127372410
    assert candidate(s = "abcddcbaabcddcba") == 340
    assert candidate(s = "abcdabcdabcd") == 72
    assert candidate(s = "abababababababababababababababab") == 8358
    assert candidate(s = "aaaabbbbccccddddaaaabbbbccccdddd") == 224
    assert candidate(s = "abacaba") == 19
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 450061485
    assert candidate(s = "aaaabbbaaaaabbbbaaaaabbbbaaaaabbbbaaaaabbbbaaaaabbbbaaaa") == 61293
    assert candidate(s = "abcdcba") == 22
    assert candidate(s = "acbdca") == 14
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 320164
    assert candidate(s = "ababababababababababababababababababababababababababababababababababababababababababab") == 672623781
    assert candidate(s = "abcdbca") == 20
    assert candidate(s = "abccbaabccbaabccba") == 446
    assert candidate(s = "abcdabcdaabbccbddc") == 184
    assert candidate(s = "ababababababab") == 106
    assert candidate(s = "abababababab") == 64
    assert candidate(s = "abcababcababcababcababcababcababcababcab") == 237716
    assert candidate(s = "abcdabcdaabbccbddcddcbaabccbddcddcba") == 17166
    assert candidate(s = "abcabcabcabcabcabc") == 504
    assert candidate(s = "aababaababaababaababaababaababaababaababaababaababa") == 442187
    assert candidate(s = "abbbccaddccbbbaabbbccaddccbbba") == 4260
    assert candidate(s = "abcdabcdabcdabcd") == 244
    assert candidate(s = "abcdabcdabcdabcdabcd") == 812
    assert candidate(s = "ddccbbbaaacccbbbaaacccbdd") == 607
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 38097140
    assert candidate(s = "dddddddddddddddddddddddd") == 24
    assert candidate(s = "abababababababababab") == 462
    assert candidate(s = "aaaaa") == 5
    assert candidate(s = "abacabadabacaba") == 232
    assert candidate(s = "dcbadcbadcbadcbadcbadcb") == 2219
    assert candidate(s = "aabababababababa") == 161
    assert candidate(s = "abcdabcd") == 20
    assert candidate(s = "aaaaabbbbbcccc") == 14
    assert candidate(s = "abccccddddddbbbaaaadddbbbbccccaaaabbbccbbccbbccbbccbbccbbccbbbbaaaaddbbbbccccaaaaadddbbbbccccaaaabbbccbbccbbccbbccbbccbbccbbbbaaaadd") == 584072730
    assert candidate(s = "dcbaabcd") == 30
    assert candidate(s = "abcabcdabcabcdabcabcdabcabcdabcabcdabcabcdabcabcdabcabcdabcabcdabcabcdabcabcd") == 852725823
    assert candidate(s = "abcdabcdbabcdbabcdb") == 607
    assert candidate(s = "aaaabbbbccccdddd") == 16
    assert candidate(s = "abacabadabacabadabacabad") == 2784
    assert candidate(s = "abbaabbaabba") == 54
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcd") == 96936
    assert candidate(s = "aabbccddccbbaa") == 106
    assert candidate(s = "abccbaabcba") == 56
    assert candidate(s = "abababababababababababab") == 1216
    assert candidate(s = "ababababab") == 38
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcda") == 198263755
    assert candidate(s = "abcabc") == 12
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 125826312
    assert candidate(s = "abcdcbadcbadcbabcd") == 432
    assert candidate(s = "abcabcabcabcabcabcabcabc") == 2952
    assert candidate(s = "dcbbabdccacbaaadbcbbabcbbb") == 934
    assert candidate(s = "ababa") == 9
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 320443980
    assert candidate(s = "ddddcbbaabcdccbdddbddbcccbdbabdbbaccabdbdddcbbaabaddabbdcbbaabcddbacccbadcbbaabcdccbdddbddbcccbdbabdbbaccabdbddd") == 923039370
    assert candidate(s = "abcadcbadcbadcb") == 210
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcddcbadcbadcbadcbadcbadcbadcbadcbaabcd") == 649659461
    assert candidate(s = "abcdcbaabcdcbaabcdcba") == 1694
