# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(word = "aAbBcCdDeEfFgG") == 7
    assert candidate(word = "AaBbCc") == 0
    assert candidate(word = "aabbCC") == 0
    assert candidate(word = "Aabbcc") == 0
    assert candidate(word = "abABcdCD") == 4
    assert candidate(word = "zZaA") == 2
    assert candidate(word = "aAbBcC") == 3
    assert candidate(word = "aAb") == 1
    assert candidate(word = "abcABC") == 3
    assert candidate(word = "ZzYyXxWwVvUuTtSsRrQqPpOoNnMmLlKkJjIiHhGgFfEeDdCcBbAa") == 0
    assert candidate(word = "AbBCab") == 0
    assert candidate(word = "ZzYyXx") == 0
    assert candidate(word = "ZzYyXxWwVvUuTtSsRrQqPpOoNnMmLlKkJjiIhHgGfFeEdDcCbBaA") == 9
    assert candidate(word = "aA") == 1
    assert candidate(word = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz") == 0
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 0
    assert candidate(word = "abcdefgHIJKLmnopqrstuvwxyz") == 0
    assert candidate(word = "aaAbcBC") == 3
    assert candidate(word = "aabB") == 1
    assert candidate(word = "abc") == 0
    assert candidate(word = "Aa") == 0
    assert candidate(word = "aabbccAABBCC") == 3
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ") == 26
    assert candidate(word = "AaBbCcDdEeFf") == 0
    assert candidate(word = "aBcDeFgHiJkLmNoPqRsTuVwXyZ") == 0
    assert candidate(word = "AaBbCcDd") == 0
    assert candidate(word = "zZyYxXwWvVuUtTsSrRqQpPoOnNmMlLkKjJiIhHgGfFeEdDcCbBaA") == 26
    assert candidate(word = "aabbccAAABBBCCC") == 3
    assert candidate(word = "zZyYxXwWvVuUtTsSrRpPqQoOnNmMlLkKjJiIhHgGfFeEdDcCbBaA") == 26
    assert candidate(word = "aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaA") == 0
    assert candidate(word = "aaaaaAAAAAaaaaaAAAAA") == 0
    assert candidate(word = "abcXYZabcXYZ") == 0
    assert candidate(word = "zzzzZ") == 1
    assert candidate(word = "abcdEFGhijklmNOPqrSTuvWXYZ") == 0
    assert candidate(word = "aAaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz") == 0
    assert candidate(word = "aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaA") == 0
    assert candidate(word = "aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ") == 0
    assert candidate(word = "AbCdEfGhIjKlMnOpQrStUvWxYz") == 0
    assert candidate(word = "aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaA") == 0
    assert candidate(word = "aAaAaAaAaAaAaAaAaAaA") == 0
    assert candidate(word = "aAbBcCddeEfffGggHhhIiiJjjKkkLllMmmNnnOooPppQqqRrrSssTttUuuVvvWwwXxxYyyZzz") == 4
    assert candidate(word = "Zabcdefghijklmnopqrstuvwxyz") == 0
    assert candidate(word = "zZyYxXwWvVuUtTsSrRpPoOnNmMlLkKjJiIhHgGfFeEdDcCbBaA") == 25
    assert candidate(word = "aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaA") == 0
    assert candidate(word = "aBcD") == 0
    assert candidate(word = "aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbB") == 24
    assert candidate(word = "AbCdeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZ") == 2
    assert candidate(word = "xyzXYZabcABC") == 6
    assert candidate(word = "zzzzZzzzZzzzzzzz") == 0
    assert candidate(word = "AbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYz") == 0
    assert candidate(word = "AbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ") == 25
    assert candidate(word = "abcABCabcABCabcABC") == 0
    assert candidate(word = "abABcdCDefEfghGhijIJklKLmMnopNOPqrstQRstUVuvwVwxWXyzYZ") == 20
    assert candidate(word = "AABBCCDDEEFFGGHHIIJJKKLLMMNNOOPPQQRRSSTTUUVVWWXXYZZZ") == 0
    assert candidate(word = "aAAAbBBBcCCCCdDDDD") == 4
    assert candidate(word = "AbcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ") == 25
    assert candidate(word = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZzAaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz") == 0
    assert candidate(word = "abCDcdEFefGHghIJijKLklMNmnOPopQRqrSTstUVuvWXwxYZyz") == 0
    assert candidate(word = "abcdefABCDEFghijklGHJKLmnopQRStuTUvwVWXyYZ") == 16
    assert candidate(word = "AABBCCDDEEFFGGHHIIJJKKLLMMNNOOPPQQRRSSTTUUVVWWXXYYZZ") == 0
    assert candidate(word = "aAAaBBBbcccC") == 1
    assert candidate(word = "aBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz") == 0
    assert candidate(word = "aaaBBBcccDDD") == 0
    assert candidate(word = "abABcdE") == 2
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz") == 0
    assert candidate(word = "aBcDDefFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ") == 21
    assert candidate(word = "aAbBcCdefGhIjKlMnopQrstUvwXyz") == 3
    assert candidate(word = "aaaBBBcccDDDeeeFFFgggHHHiiiJJJkkkLLLmmmNNNoooPPPqqqRRRsssTTTuuuVVVwwwXXXyyyZZZ") == 0
    assert candidate(word = "aBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZzabcdefghijklmnopqrstuvwxyz") == 0
    assert candidate(word = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZzAaBbCc") == 0
    assert candidate(word = "ZZZZzzzzYYYYyyyyXXXXXXXXxxWWWWwwwwVVVVvvvvUUUUuuuuTTTTttttSSSSssssRRRRrrrrQQQQqqqqPPPPppppOOOOooooNNNNnnnnMMMMmmmmLLLLllllKKKKkkkkJJJJjjjjIIIIiiiiHHHHhhhhGGGGggggFFFFFFffffEEEEeeeeDDDDddddCCCCccccBBBBbbbbAAAAAAAAaaaa") == 0
    assert candidate(word = "aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZ") == 0
    assert candidate(word = "abcdefgHIJKLMNopqrstuvwxyz") == 0
    assert candidate(word = "AbCdEfGhIjKlMnOpQrStUvWxYzABCD") == 2
    assert candidate(word = "zZyYxXwWvVuUtTrRsSqQpPnNmMlLkKiIhHgGfFeEdDcCbBaA") == 24
    assert candidate(word = "aAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 0
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzAA") == 1
    assert candidate(word = "aB") == 0
    assert candidate(word = "aBcDeFgHiJkLmNoPqRsTuVwXyZaA") == 1
    assert candidate(word = "aBcDEfGHiJKlMNopQRsTuVwXyZ") == 0
    assert candidate(word = "aaaAAAaaaAAAaaaAAA") == 0
    assert candidate(word = "aBbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb") == 0
    assert candidate(word = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZzBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz") == 0
    assert candidate(word = "zzzZZZyyyYYYxxxXXXwwwWWWvvvVVVuuuUUUtttTTTsssSSSrrrRRRqqqQQQpppPPPoooOOOnnnNNNmmmMMMlllLLLkkkKKKjjjJJJiiiIIIhhhHHHgggGGGfffFFFeeeEEEdddDDDcccCCCbbbBBBaaaAAA") == 26
    assert candidate(word = "aBcDefGhiJklMnoPqrStuVwxYz") == 0
    assert candidate(word = "abcdefghijklmnopqrstuvwxyz") == 0
    assert candidate(word = "ABCDEFGHIJKLMNOPQRSTUVWXYZ") == 0
    assert candidate(word = "aaBBccDDeeFFggHHiiJJkkLLmmNNooPPqqRRssTTuuVVwwXXyyZZ") == 0
    assert candidate(word = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ") == 0
    assert candidate(word = "aaBBccDDeeFFggHHiiJjkkLLmmNNooPPqqRRssTTuuVVwwXXyyZZ") == 0
    assert candidate(word = "aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZ") == 0
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzZ") == 1
    assert candidate(word = "aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZ") == 0
    assert candidate(word = "mnopqrstuNOPQRS") == 6
    assert candidate(word = "aAbC") == 1
    assert candidate(word = "aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaA") == 0
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzZ") == 1
    assert candidate(word = "aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ") == 26
    assert candidate(word = "aAbCdeFghIjKlmNoPqRsTuVwXyZ") == 1
    assert candidate(word = "aaAaabBBccCCCd") == 2
