# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "aeiaaioaaaaeiiiiouuuooououuoiiiuuuuaeiou",k = 10) == 0
    assert candidate(s = "aabbcc",k = 4) == 1
    assert candidate(s = "zzzzz",k = 1) == 0
    assert candidate(s = "",k = 1) == 0
    assert candidate(s = "baeyh",k = 2) == 2
    assert candidate(s = "bbaeaeaaeiou",k = 3) == 0
    assert candidate(s = "bcdf",k = 1) == 0
    assert candidate(s = "aeiou",k = 25) == 0
    assert candidate(s = "vowelsandconsonants",k = 10) == 0
    assert candidate(s = "",k = 3) == 0
    assert candidate(s = "abba",k = 1) == 3
    assert candidate(s = "abcdefghij",k = 2) == 0
    assert candidate(s = "aebcde",k = 3) == 1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",k = 7) == 0
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",k = 2) == 0
    assert candidate(s = "a",k = 1) == 0
    assert candidate(s = "aeiou",k = 5) == 0
    assert candidate(s = "beautifulstring",k = 7) == 0
    assert candidate(s = "aabbccddeeff",k = 4) == 4
    assert candidate(s = "aaabbbcccddd",k = 6) == 0
    assert candidate(s = "consonantsandvowels",k = 20) == 0
    assert candidate(s = "bbaaccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 12) == 0
    assert candidate(s = "vowelsvowelsvowelsvowels",k = 4) == 8
    assert candidate(s = "thisisaverylongstringwithabunchoflettersandvariousvowelsandconsonants",k = 10) == 0
    assert candidate(s = "bcbcbcbcbcbcbcbcbcbcbcbcbc",k = 11) == 0
    assert candidate(s = "aebcdefghijklmnopqrstuvwxyz",k = 5) == 0
    assert candidate(s = "abacabadabacaba",k = 10) == 0
    assert candidate(s = "vowelsandconsonants",k = 6) == 0
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 100) == 0
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",k = 13) == 0
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",k = 20) == 0
    assert candidate(s = "aeiouaeiouaeiou",k = 25) == 0
    assert candidate(s = "vwxyzvwxyzvwxyzvwxyz",k = 20) == 0
    assert candidate(s = "abcdabcdabcdabcdabcdabcd",k = 9) == 0
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 10) == 0
    assert candidate(s = "aaaabbbbccccddddeeeeffff",k = 16) == 6
    assert candidate(s = "abcdefghijabcdefghijabcdefghij",k = 3) == 0
    assert candidate(s = "bcdfghjklmnpqrstvwxyzbcd",k = 15) == 0
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnm",k = 11) == 0
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzz",k = 20) == 0
    assert candidate(s = "abcdeffedcba",k = 4) == 1
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 2) == 0
    assert candidate(s = "repeatedcharactersaaaaaaaabbbbbbbbcccccccc",k = 16) == 13
    assert candidate(s = "aaeeiioouu",k = 10) == 0
    assert candidate(s = "thisisalongstringwithvariousvowelsandconsonants",k = 36) == 6
    assert candidate(s = "beautifulstring",k = 3) == 2
    assert candidate(s = "abcdefghefghijklmnopqrstuvwxyz",k = 8) == 0
    assert candidate(s = "aeioubcdfghjklmnpqrstvwxyz",k = 25) == 1
    assert candidate(s = "zzzzzaaaaabbbbbbccccccdddddd",k = 12) == 0
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 1) == 0
    assert candidate(s = "aeiouaeiou",k = 5) == 0
    assert candidate(s = "aeioubcdfg",k = 5) == 1
    assert candidate(s = "bcaedfghioklmnpqrstuvwxyz",k = 7) == 0
    assert candidate(s = "bcdfghjklmnpqrstvwxyzzzzzzzz",k = 11) == 0
    assert candidate(s = "beautifulstring",k = 2) == 5
    assert candidate(s = "abababababababababab",k = 6) == 9
    assert candidate(s = "aaeeiioouubbccddeeffgghhjjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 10) == 1
    assert candidate(s = "aeeeeiiioouu",k = 10) == 0
    assert candidate(s = "aeiouaeiouaeiou",k = 3) == 0
    assert candidate(s = "vowelvowelvowelvowelvowel",k = 10) == 0
    assert candidate(s = "aaaaaaaaaaabbbbbbbbbb",k = 1) == 10
    assert candidate(s = "abacabadabacaba",k = 2) == 24
    assert candidate(s = "aaaabbbbcccc",k = 10) == 0
    assert candidate(s = "eiouaeiouaeiouaeiou",k = 5) == 0
    assert candidate(s = "aeioubcdfghjklmnpqrstvwxyz",k = 5) == 1
    assert candidate(s = "thisisaverylongstringwithvariouscharacters",k = 11) == 0
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba",k = 3) == 0
    assert candidate(s = "bcdfghjklmnpqrstvwxyzbcdfghjklmnpqrstvwxyz",k = 30) == 0
    assert candidate(s = "aeiaeiouaeiaeiouaeiaeiou",k = 18) == 0
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzabcdefghijklmnopqrstuvwxyz",k = 50) == 0
    assert candidate(s = "consonantconsonantconsonant",k = 15) == 0
    assert candidate(s = "bcbcbcbcbcbcbc",k = 3) == 0
    assert candidate(s = "vowelsconsonants",k = 4) == 5
    assert candidate(s = "aebcdeioufhgjk",k = 12) == 1
    assert candidate(s = "xylophone",k = 2) == 2
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 25) == 0
    assert candidate(s = "xyzabcxyzabc",k = 9) == 0
    assert candidate(s = "thisisateststring",k = 7) == 0
    assert candidate(s = "aaaaaaaaaabbbbbbbbbb",k = 100) == 1
    assert candidate(s = "vowelsandconsonants",k = 18) == 0
    assert candidate(s = "bcdfghjklmnpqrstvwxyz",k = 26) == 0
    assert candidate(s = "aabbbbcccc",k = 4) == 1
    assert candidate(s = "beautifulsubstring",k = 5) == 2
    assert candidate(s = "xyzxyzxyzxyz",k = 9) == 0
    assert candidate(s = "abecidofug",k = 8) == 3
    assert candidate(s = "xyzxyzxyzxyz",k = 3) == 0
    assert candidate(s = "aaaabbbbccccdddd",k = 8) == 1
    assert candidate(s = "mnbvcxzlkjhgfdsapoiuytrewwq",k = 11) == 0
    assert candidate(s = "aeiouaeiouaeiouaeiou",k = 25) == 0
    assert candidate(s = "aaaaaaaaaeeeeeeiiioooouuuu",k = 10) == 0
    assert candidate(s = "consonantsconsonantsconsonants",k = 9) == 3
