# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "zzzzzzzzz") == 9
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 351
    assert candidate(s = "abacbacbacbacbacbacbacbacbacbacbacbacbacbacbacbacbacbacbacbacbacbacb") == 200
    assert candidate(s = "pp") == 2
    assert candidate(s = "pqpqs") == 10
    assert candidate(s = "a") == 1
    assert candidate(s = "abab") == 7
    assert candidate(s = "abcabcabc") == 24
    assert candidate(s = "p") == 1
    assert candidate(s = "pqpqrp") == 13
    assert candidate(s = "xyzxyzxyz") == 24
    assert candidate(s = "zzzzzzzzzz") == 10
    assert candidate(s = "ooo") == 3
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 53
    assert candidate(s = "abcd") == 10
    assert candidate(s = "hello") == 9
    assert candidate(s = "aabbcc") == 8
    assert candidate(s = "unique") == 19
    assert candidate(s = "pppppp") == 6
    assert candidate(s = "abacaba") == 15
    assert candidate(s = "abcdefg") == 28
    assert candidate(s = "abcdabcdeabcdabcdeabcdabcde") == 113
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 150
    assert candidate(s = "abcdefghijkabcdefghijkabcdefghijkabcdefghijk") == 429
    assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghij") == 355
    assert candidate(s = "aabbccddeeffaabbccddeeffaabbccddeeff") == 53
    assert candidate(s = "aabbaaabbbaaaabbbaabbbaaaabaaabaaaabbaaababbaaabaaabababaa") == 84
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcbaabcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 1053
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad") == 258
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacaba") == 135
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcbazyxwvutabcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcbazyxwvutabcdefghijklmnopqrstuvwxyzzyxwvut") == 2413
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 618
    assert candidate(s = "abbaabbaabbaabbaabbaabba") == 36
    assert candidate(s = "abcababcababcababcababcababcababcababcababcababcababcababc") == 149
    assert candidate(s = "abcdeffedcbaabcdeffedcbaabcdeffedcbaabcdeffedcbaabcdeffedcba") == 210
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 195
    assert candidate(s = "abcdefghijkabcdeghijklmnopqrstuvwxyzabcdeghijklmnopqrstuvwxyz") == 1066
    assert candidate(s = "abababababababababababababababababababababababababababababababab") == 127
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcbaabcdefghijklmnopqrstuvwxyzzyxwvut") == 730
    assert candidate(s = "abababababababababababababababab") == 63
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcbazyxwvutabcdefghijklmnopqrstuvwxyzzyxwvut") == 1396
    assert candidate(s = "aabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabb") == 95
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 177
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 159
    assert candidate(s = "aabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaab") == 112
    assert candidate(s = "mnopqrstuvwxyzabcdefghijkl") == 351
    assert candidate(s = "abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde") == 215
    assert candidate(s = "aaaaabbbbbcccccdddddeeeee") == 29
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc") == 87
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 141
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 420
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd") == 43
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 702
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzz") == 79
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 330
    assert candidate(s = "abcdabcdeabcdabcdeabcde") == 97
    assert candidate(s = "abababababababababababababababababababababab") == 87
    assert candidate(s = "abcdefggfedcba") == 56
    assert candidate(s = "abcdefedcbafedcba") == 77
    assert candidate(s = "abababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababab") == 319
    assert candidate(s = "abcdeffedcba") == 42
    assert candidate(s = "thisproblemisreallyhardbutinteresting") == 215
    assert candidate(s = "uniquecharactersetuniquecharactersetuniquecharacterset") == 275
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzyyxxwwvvuuttssrrqqppllmnkkjjiihhggeeddbbccaa") == 150
    assert candidate(s = "aabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabb") == 71
    assert candidate(s = "anagramsofanagramsofanagramsofanagramsofanagramsof") == 217
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcbaabcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 1404
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzabcdefghij") == 142
    assert candidate(s = "xyzzzzxyzzzzxyzzzz") == 31
    assert candidate(s = "abababababababababababababababababababababababababababababa") == 117
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 168
    assert candidate(s = "aabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabb") == 227
    assert candidate(s = "ababababababababababababababababababababab") == 83
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad") == 218
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 56
    assert candidate(s = "abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde") == 240
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcbaedcbazyxwvutsrqponmlkjihgfedcba") == 842
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 1703
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzabcdefghijklmnopqrstuvwxyz") == 453
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 70
    assert candidate(s = "aabacbadbacbacbacbacbacbacbacbacbacbacbacbacbacbacbacbacbacbacbac") == 191
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabad") == 98
    assert candidate(s = "aaaaabbbbbccccdddddeeeeefffff") == 34
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzuniquecharacterset") == 162
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 54
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 123
    assert candidate(s = "banana") == 12
    assert candidate(s = "aabbccddeeffaabbccddeeffaabbccddeeffaabbccddeeffaabbccddeeff") == 89
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzqqwweerrttyyuuiiooppaassddffgg") == 122
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbccccccccccaaaaaaaaaabbbbbbbbbbcccccccccc") == 65
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzz") == 89
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 186
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabad") == 138
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad") == 158
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 77
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcbazyxwvut") == 884
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 250
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabad") == 118
    assert candidate(s = "mnopqrspqronmlkjihgfedcbazyxwvuttsrqponmlkjihgfedcba") == 591
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba") == 351
    assert candidate(s = "thequickbrownfoxjumpsoverthelazydog") == 271
    assert candidate(s = "abacabadabacabadabacabad") == 58
    assert candidate(s = "ababababababababababababababababababababababababababababababababababababababab") == 155
    assert candidate(s = "aaaabbbbccccaaaabbbbccccaaaabbbbccccaaaabbbbccccaaaabbbbcccc") == 74
    assert candidate(s = "aaaaaabbbaaaaabbbbccccccaaaaaabbbaaaaabbbbcccccc") == 57
    assert candidate(s = "abcdefghijkllkjihgfedcba") == 156
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbccccccccccaaaaaaaaaabbbbbbbbbbccccccccccaaaaaaaaaabbbbbbbbbbcccccccccc") == 98
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzabcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 804
    assert candidate(s = "longestsubstringwithoutrepeatingcharacters") == 215
    assert candidate(s = "aabbaabbccddeeffaabbccddeeff") == 41
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzmnopqrstuvwxyz") == 195
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm") == 1027
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 53
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzz") == 86
    assert candidate(s = "racecar") == 19
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 234
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcbaedcbazyxwvutsrqponmlkjihgfedcbaabcdefghijklmnopqrstuvwxyzzyxwvut") == 1221
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnmnbvcxzlkjhgfdsapoiuytrewq") == 701
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 1027
    assert candidate(s = "abcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefg") == 371
    assert candidate(s = "pneumonoultramicroscopicsilicovolcanoconiosis") == 194
    assert candidate(s = "abcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdef") == 381
    assert candidate(s = "abcdeabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 227
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 429
    assert candidate(s = "abacabaabacabaabacabaabacabaabacabaabacabaabacabaabacabaabacabaabacabaabacabaabacaba") == 180
    assert candidate(s = "aabbaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 83
    assert candidate(s = "mississippi") == 20
    assert candidate(s = "hellohellohellohello") == 51
    assert candidate(s = "abcdefagfedcba") == 66
    assert candidate(s = "ababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababab") == 339
    assert candidate(s = "abcdcbaabcdcbaabcdcba") == 57
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 50
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcbazyxwvutabc") == 911
