# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "aaabbbccc") == 18
    assert candidate(s = "aabbccddeeefffggghhhiiii") == 46
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "xy") == 2
    assert candidate(s = "aabbaa") == 9
    assert candidate(s = "aaaaa") == 15
    assert candidate(s = "pppppppppp") == 55
    assert candidate(s = "abcdeffffff") == 26
    assert candidate(s = "a") == 1
    assert candidate(s = "qqqqqwwweeeerrrrtttttyyyyyuuuuuiooooo") == 102
    assert candidate(s = "abcabcabc") == 9
    assert candidate(s = "ababababab") == 10
    assert candidate(s = "abcde") == 5
    assert candidate(s = "ababababa") == 9
    assert candidate(s = "zzzzyyyyxxxwwwwvvvvuuuuttttsrrrqqqppoonnmlkjihgfedcba") == 101
    assert candidate(s = "ccccccccc") == 45
    assert candidate(s = "abbcccaa") == 13
    assert candidate(s = "abcd") == 4
    assert candidate(s = "zzzzz") == 15
    assert candidate(s = "ababab") == 6
    assert candidate(s = "aaaaaabb") == 24
    assert candidate(s = "aabbccddeeeeffff") == 32
    assert candidate(s = "abcabcabcabcabcabcabc") == 21
    assert candidate(s = "aabbbccccdddd") == 29
    assert candidate(s = "mmmmmlllllkkkkkkjjjjjjjjiiiiiiiiiiiihhhhhhhhhhhh") == 243
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1326
    assert candidate(s = "aaabaaaabaaaaabaaaaaaabaaaaaaaabaaaaaaaaabaaaaaaaaaabaaaaaaaaaa") == 257
    assert candidate(s = "aaaaaaaaaabbbbbbbbccccccccddddddddeeeeeeeee") == 208
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 903
    assert candidate(s = "aabbcccddddeeeee") == 37
    assert candidate(s = "pppppqqqqqqrrrrrrsssssstttttuuuuuuvvvvvvvvvwwwwwwwww") == 204
    assert candidate(s = "aabbbcccc") == 19
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 676
    assert candidate(s = "aaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaa") == 252
    assert candidate(s = "mmmmmmmmmmmmmmmnnnnnnnnnnnnnnnoooooooooooopppppppppppp") == 396
    assert candidate(s = "aabbccddeeefffggg") == 30
    assert candidate(s = "abcabcabcabc") == 12
    assert candidate(s = "aaabbaaaabbaaa") == 28
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbcccccccccc") == 165
    assert candidate(s = "aabbccddeeefffggghhhh") == 40
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 277140
    assert candidate(s = "zzzzyyyyzzzz") == 30
    assert candidate(s = "aaaaabbbbccccc") == 40
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 29403
    assert candidate(s = "xyzxyzxyzxyzxyzxyzxyzxyz") == 24
    assert candidate(s = "aabbccddeeeeffffggggghhhhiiiii") == 72
    assert candidate(s = "pppppppppppppppppppppppppppppppppp") == 595
    assert candidate(s = "ababababababababababababababab") == 30
    assert candidate(s = "aaaaabbbbccccdddddeeeee") == 65
    assert candidate(s = "aabbccddeeefffggghhhhiiiiijjjjjkkkkklllllmmmmmnnnnnooooo") == 145
    assert candidate(s = "pppppppppppppppppppppppppppppppppppppppppppqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq") == 1892
    assert candidate(s = "ppppppppppppppppppppppp") == 276
    assert candidate(s = "xyzzyzxzyzxyz") == 14
    assert candidate(s = "ababababababab") == 14
    assert candidate(s = "aabbccddeeeefffghhhiiiijjjjkkkkllllmmmmmnnnnnooooo") == 120
    assert candidate(s = "abcdefghijklmnopqrstuvwxyza") == 27
    assert candidate(s = "aabbccddeeefffggghhhiiiijjjjkkkkllllmmmmmnnnnnooooooo") == 134
    assert candidate(s = "aaaaaaaaabbbbbbbbbbcccccccccc") == 155
    assert candidate(s = "zzzzzyyyxxxwwwwvvvvuuuuu") == 62
    assert candidate(s = "aabbccddeeeeffffggggghhhiiijjjkkklllmmnnooopppqqqrrsssttuuuvvvwwwwwxxxxxyyyyyzzzz") == 180
    assert candidate(s = "abcdefffffffffffffffffffffffffghijklmnopqrstuvwxyz") == 350
    assert candidate(s = "abcdabcdbcdabcd") == 15
    assert candidate(s = "aabbbbccccc") == 28
    assert candidate(s = "aaaaaaaaaaaabbaaaaaaa") == 109
    assert candidate(s = "aabbbccccc") == 24
    assert candidate(s = "xyxyxyxyxyxyxyx") == 15
    assert candidate(s = "aabbaaabbbaaa") == 24
    assert candidate(s = "aabbaaabbcccddeee") == 30
    assert candidate(s = "aabbccddeeffgg") == 21
    assert candidate(s = "aaaaabbbbbbbbbbcccccccccc") == 125
    assert candidate(s = "pppppppppppppppppppppppppppppppppppppppp") == 820
    assert candidate(s = "aabbaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 84
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad") == 160
    assert candidate(s = "qwerqwerqwerqwerqwerqwerqwer") == 28
    assert candidate(s = "aaabbaaa") == 15
    assert candidate(s = "aaabbaaabbaaa") == 24
    assert candidate(s = "abcabcabcabcabc") == 15
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 21736
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1275
    assert candidate(s = "abcdefg") == 7
