# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "iamprogrammer") == 0
    assert candidate(s = "|*|*|*|*|") == 2
    assert candidate(s = "||||||||||") == 0
    assert candidate(s = "yo|uar|e**|b|e***au|tifu|l") == 5
    assert candidate(s = "l|*e*et|c**o|*de|") == 2
    assert candidate(s = "abc|def|ghi|jkl|") == 0
    assert candidate(s = "a*b*c*d*e*f*g*h*i*j*k*l|m*n*o*p*q*r*s*t*u*v*w*x*y*z|") == 11
    assert candidate(s = "*|*|*|*|*|*|") == 3
    assert candidate(s = "no|asterisks|here|") == 0
    assert candidate(s = "*|*|*|*|*|*|*|*|*|*|") == 5
    assert candidate(s = "|*a|b*|*c|d*|e*f*g*h*i*j*k*l*m*n*o*p*q*r*s*t*u*v*w*x*y*z*|") == 2
    assert candidate(s = "|*a*|b*|*c*|d*|*e*|f*|*g*|h*|*i*|j*|*k*|l*|*m*|n*|*o*|p*|*q*|r*|*s*|t*|*u*|v*|*w*|x*|*y*|z*|") == 13
    assert candidate(s = "*a|*b|*c|*d|*e|*f|*g|*h|*i|*j|*k|*l|*m|*n|*o|*p|*q|*r|*s|*t|*u|*v|*w|*x|*y|*z|") == 13
    assert candidate(s = "*a*|b*c|d*e*f|g*h*i*j*k|l*m*n*o*p*q*r*s*t*u*v*w*x*y*z*|*") == 19
    assert candidate(s = "this|is|a|test|string|with|multiple|pipes|and|asterisks|*|*|*|*|*|*|*|*|*|*|*|") == 6
    assert candidate(s = "|*a|b*c|d*e*f|g*h*i*j*k|l*m*n*o*p*q*r*s*t*u*v*w*x*y*z*|*a*|b|*c*|d*|*e*|f*|*g*|*h*|*i*|*j*|*k*|*l*|*m*|*n*|*o*|*p*|*q*|*r*|*s*|*t*|*u*|*v*|*w*|*x*|*y*|*z*|") == 31
    assert candidate(s = "multiple|pairs|of|bars|and*no*asterisks*between|them|") == 3
    assert candidate(s = "*a*|b*c|d*e*f|g*h*i*j|") == 4
    assert candidate(s = "abc*def|ghi*jkl|*mnop|qrstu|vwxyz*") == 3
    assert candidate(s = "|*a*|b|c*|d*e*|f*g*h|*i*j*k*|l*m*n*o*|") == 6
    assert candidate(s = "this|is|a|test|string|with|multiple|pipes|and|asterisks|*|*|*|") == 2
    assert candidate(s = "a*b*c*d*e*f*g*h*i*j*k*l*m*n*o*p*q*r*s*t*u*v*w*x*y*z*|*a*b*c*d*e*f*g*h*i*j*k*l*m*n*o*p*q*r*s*t*u*v*w*x*y*z|") == 26
    assert candidate(s = "|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||") == 0
    assert candidate(s = "|*a*b*c*d*e*f*g*h*i*j*k*l*m*n*o*p*q*r*s*t*u*v*w*x*y*z*|") == 0
    assert candidate(s = "interleaved*characters|with|pipes*and*asterisks|and|more|pipes*and*asterisks*at|the*end*of*the|string*") == 6
    assert candidate(s = "|*||||*||||*||||*||||*|") == 0
    assert candidate(s = "|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|") == 0
    assert candidate(s = "|*a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z*|") == 1
    assert candidate(s = "*a*b*c*d*e*f*g*h*i*j*k*l*m*n*o*p*q*r*s*t*u*v*w*x*y*z*|") == 27
    assert candidate(s = "nested||pipes|should|not|affect|the|count|of|*|in|between|pipes|") == 0
    assert candidate(s = "*a|*b|*c|*d|*e|*f|*g|*h|*i|*j|*k|*l|*m|*n|*o|*p|*q|*r|*s|*t|*u|*v|*w|*x|*y|*z*|") == 13
    assert candidate(s = "*a*|*b*|*c*|*d*|*e*|*f*|*g*|*h*|*i*|*j*|*k*|*l*|*m*|*n*|*o*|*p*|*q*|*r*|*s*|*t*|*u*|*v*|*w*|*x*|*y*|*z*|") == 26
    assert candidate(s = "long|*sequence*|of|*characters*|to|test|the|*algorithm*|efficiency|") == 0
    assert candidate(s = "*a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z*|*") == 2
    assert candidate(s = "|*a*|b*|c*|d*|e*|f*|g*|h*|i*|j*|k*|l*|m*|n*|o*|p*|q*|r*|s*|t*|u*|v*|w*|x*|y*|z*|") == 13
    assert candidate(s = "a*|b*|c*|d*|e*|f*|g*|h*|i*|j*|k*|l*|m*|n*|o*|p*|q*|r*|s*|t*|u*|v*|w*|x*|y*|z*|") == 13
    assert candidate(s = "nested|*pipes*|and|*asterisks*|inside|*and*|outside|*pipes*|") == 0
    assert candidate(s = "|a*b*c|d*e*f*g|h*i*j*k*l*m*n|o*p*q*r*s*t*u|v*w*x*y*z|") == 9
    assert candidate(s = "multiple*asterisks*here|and*here*too|and*here|") == 3
    assert candidate(s = "this|is*a*test|to*see*if*the*function*works*correctly*with*many*bars|and*asterisks*in*various*places*|") == 9
    assert candidate(s = "*|*a*b*c*|d*e*f*g*|h*i*j*k*l*m*n*|o*p*q*r*s*t*u*|v*w*x*y*z*|") == 12
    assert candidate(s = "1234567890|*1*2*3*4*5*6*7*8*9*0|abcdefg|hijklmn|opqrstuv|wxyz|") == 0
    assert candidate(s = "*at|the|start*|and|at|the|end*|pipes|should|not|affect|the|count*|") == 4
    assert candidate(s = "|a*b*c*d*e*f*g*h*i*j*k*l*m*n*o*p*q*r*s*t*u*v*w*x*y*z*|") == 0
    assert candidate(s = "|pipes|without|*asterisks*|in|between|pipes|should|return|zero|") == 0
    assert candidate(s = "*only*|*pipes*|*and*|*asterisks*|*in*|*the*|*string*|") == 8
    assert candidate(s = "no*bars*in*string") == 3
    assert candidate(s = "no|pipes|here|just|plain|text|and|some|asterisks*at*the*end") == 3
    assert candidate(s = "|a*b*c*d*e*f*g*h*i*j*k*l*m*n*o*p*q*r*s*t*u*v*w|x*y*z*|a*b*c*d*e*f*g*h*i*j*k*l*m*n*o*p*q*r*s*t*u*v*w|x*y*z*|") == 6
    assert candidate(s = "nested*bars*are|not|possible|but|this|is*a*test*case*with*many*bars|and*some*stars*in*the*end*|") == 8
    assert candidate(s = "*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|") == 20
    assert candidate(s = "*at*the*start*and*no*pipes*in*the*middle*or*end") == 11
    assert candidate(s = "|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|") == 19
    assert candidate(s = "noasterisks|here|but|many|pipes|to|confuse|you|") == 0
    assert candidate(s = "*a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z*") == 1
    assert candidate(s = "|a*b*c*d*e*f*g*h*i*j*k*l*m*n*o*p*q*r*s*t*u*v*w*x*y*z|*") == 1
    assert candidate(s = "*|a*|b*|c*|d*|e*|f*|g*|h*|i*|j*|k*|l*|m*|n*|o*|p*|q*|r*|s*|t*|u*|v*|w*|x*|y*|z*|") == 14
    assert candidate(s = "hello*world|this|is*a*test|string|with*many*asterisks|") == 5
    assert candidate(s = "*|a|*b|*c|*d|*e|*f|*g|*h|*i|*j|*k|*l|*m|*n|*o|*p|*q|*r|*s|*t|*u|*v|*w|*x|*y|*z|*|") == 14
    assert candidate(s = "*a|b*c|d*e*f|g|h*i*j|k*l*m|n*o*p*q*r*s*t*u*v*w*x*y*z|") == 17
    assert candidate(s = "*a|b|*c|d|*e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z*|") == 3
    assert candidate(s = "*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|") == 18
    assert candidate(s = "||||||||**||||||||") == 2
    assert candidate(s = "*single*|*pair*|of|*pipes*|with|*multiple*|asterisks*|inside*|") == 3
    assert candidate(s = "no|pipes|here|just|asterisks|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|") == 11
    assert candidate(s = "a*|b*c|d*e*f|g*h|i*j*k|l*m*n|") == 5
    assert candidate(s = "*a*|b*c|d*e*f|g*h*i*j*k|l*m*n*o*p*q*r*s*t*u*v*w*x*y*z|") == 18
    assert candidate(s = "mixed|*case*|UPPER|*lower*|numbers|*1234567890*|special|*!@#$%^&*()_+*|") == 0
    assert candidate(s = "*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|") == 8
    assert candidate(s = "a*b*c*d*e*f*g*h*i*j*k*l*m*n*o*p*q*r*s*t*u*v*w*x*y*z") == 25
    assert candidate(s = "this|is*a*test|with*many*asterisks|and*no*exclusions*at*the*end*") == 2
    assert candidate(s = "multiple||pipes||in||a||row||with||asterisks*in||between") == 1
    assert candidate(s = "a|*b*|*c*|*d*|*e*|*f*|*g*|*h*|*i*|*j*|*k*|*l*|*m*|*n*|*o*|*p*|*q*|*r*|*s*|*t*|*u*|*v*|*w*|*x*|*y*|*z*|") == 24
    assert candidate(s = "*a|*b*c|*d*e*f|*g*h*i|*j*k*l|m*n*o|*p*q*r|*s*t*u|*v*w*x|*y*z*|") == 13
    assert candidate(s = "*a|b|*c|d|e|*f|g|h|*i|j|k|l|m|*n|o|p|q|r|*s|t|u|v|w|x|*y|z*|") == 5
    assert candidate(s = "*a*|b*c|d*e*f|g*h*i*j*k|l*m*n*o*p*q*r*s*t*u*v*w*x*y*z|*") == 18
    assert candidate(s = "hello|world|*python*|programming|*|code*|") == 3
    assert candidate(s = "hello|world*is*great|but*this*is*not|") == 3
    assert candidate(s = "*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|") == 20
    assert candidate(s = "*|**|***|****|*****|******|*******|********|*********|**********|") == 25
    assert candidate(s = "no|*pipes|or|*asterisks*|here|") == 0
    assert candidate(s = "a*b*c*d*e*f*g*h*i*j*k*l*m*n*o*p*q*r*s*t*u*v*w*x*y*z|*a*b*c*d*e*f*g*h*i*j*k*l*m*n*o*p*q*r*s*t*u*v*w*x*y*z|") == 25
    assert candidate(s = "|a|*b|*c|*d|*e|*f|*g|*h|*i|*j|*k|*l|*m|*n|*o|*p|*q|*r|*s|*t|*u|*v|*w|*x|*y|*z|") == 13
    assert candidate(s = "*middle*|pipes|*middle*|pipes|*middle*|pipes|*middle*|pipes|*middle*|pipes|") == 10
    assert candidate(s = "*a|b*c|d*e*f|g*h*i*j*k|l*m*n*o*p*q*r*s*t*u*v*w*x*y*z*|") == 18
    assert candidate(s = "*a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z*|") == 1
    assert candidate(s = "*|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|*") == 1
    assert candidate(s = "nested|pipes|are|not|possible||but|this|is|how|it|could|look|if|they|were|*|*|*|*|*|*|") == 3
    assert candidate(s = "*a|b|*c|d|*e|f|*g|h|*i|j|*k|l|*m|n|*o|p|*q|r|*s|t|*u|*v|*w|*x|*y|*z*|") == 13
    assert candidate(s = "*|*a*|*b*|*c*|*d*|*e*|*f*|*g*|*h*|*i*|*j*|*k*|*l*|*m*|*n*|*o*|*p*|*q*|*r*|*s*|*t*|*u*|*v*|*w*|*x*|*y*|*z*|*|") == 27
    assert candidate(s = "a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|a*b*c*d*e*f*g*h*i*j*k*l*m*n*o*p*q*r*s*t*u*v*w*x*y*z") == 25
    assert candidate(s = "|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|") == 21
    assert candidate(s = "longer|string|with|many|characters|and|some|pipes|and|asterisks*in*various*places|and*more|pipes|and|asterisks*at*the*end*") == 1
    assert candidate(s = "complex|test*case*with*mixed*characters*and*bars*and*asterisks|throughout*the*string|") == 2
    assert candidate(s = "single*asterisk*outside*pipes|double**asterisks*inside*pipes|triple***asterisks*outside*pipes") == 8
    assert candidate(s = "|a*b*c|d*e*f|g*h*i|j*k*l|m*n*o|p*q*r|s*t*u|v*w*x|y*z|") == 8
    assert candidate(s = "multiple|*pipes*|in|*one*|segment|*of*|the|*string*|should|be|handled|correctly|") == 0
    assert candidate(s = "|a|*b*|c|d|e|*f*|g|h|i|j|k|l|m|*n*|o|p|q|r|s|t|u|v|w|x|y|z|") == 6
    assert candidate(s = "|a*b*c*d*e*f*g*h*i*j*k*l*m*n*o*p*q*r*s*t*u*v*w*x*y*z||") == 0
    assert candidate(s = "|a*|b*|c*|d*|e*|f*|g*|h*|i*|j*|k*|l*|m*|n*|o*|p*|q*|r*|s*|t*|u*|v*|w*|x*|y*|z|") == 12
    assert candidate(s = "a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|*|*|*|*|") == 2
    assert candidate(s = "|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|") == 16
    assert candidate(s = "|a*b*c*d*e*f*g*h*i*j*k*l*m*n*o*p*q*r*s*t*u*v*w*x*y*z|") == 0
    assert candidate(s = "|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|") == 20
    assert candidate(s = "||||||||||||||||||||||||||||||||||||||||||||||||||||") == 0
    assert candidate(s = "nested|*p*|ai|*n*|e*d|*|t*e*s*t|case|") == 4
