# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(word = "aeiou") == 1
    assert candidate(word = "aeiofvuaeiou") == 3
    assert candidate(word = "uoiea") == 1
    assert candidate(word = "aeiouxaeeiaouoieua") == 28
    assert candidate(word = "aeiaaioaaaaeiiiiouuuooaauuaeiu") == 175
    assert candidate(word = "aeiaaioaaaaeiiiiouuuoo") == 55
    assert candidate(word = "aeiouaeiouaeiou") == 66
    assert candidate(word = "unicornarihan") == 0
    assert candidate(word = "aaaaaeeeeeeiiiiioooooouuuuu") == 25
    assert candidate(word = "aeiouu") == 2
    assert candidate(word = "a") == 0
    assert candidate(word = "abcdefghijklmnopqrstuvwxyz") == 0
    assert candidate(word = "vowelsaeiou") == 1
    assert candidate(word = "cuaieuouac") == 7
    assert candidate(word = "aeiooauuieoiau") == 41
    assert candidate(word = "bcdfeioau") == 1
    assert candidate(word = "zzzzzaeiouzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(word = "aeiouaeiouxyzaeiouaeiouxyzaeiou") == 43
    assert candidate(word = "aeiouaeiouaeiouaeiouaeiouaeiouaeiou") == 496
    assert candidate(word = "aeiouxyzaeiouaeiou") == 22
    assert candidate(word = "aeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiou") == 1326
    assert candidate(word = "aeiouxyzaeiou") == 2
    assert candidate(word = "xyzaeiouaeiouxyzaeiouaeiouxyzaeiouaeiouxyz") == 63
    assert candidate(word = "aeiouuuueeiooiaaaeeoioioiaaaeeuuuiooiiuaeiouaeiouaeiouaeiouaeiou") == 1565
    assert candidate(word = "aeiouaeiouaeiouaeiouaeiou") == 231
    assert candidate(word = "aeiouaeiouxyzaeiouaeiouxyzaeiouaeiou") == 63
    assert candidate(word = "uoieaueoiaueoiaueoiaueoi") == 208
    assert candidate(word = "aeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiou") == 666
    assert candidate(word = "aeioubcdfghjklmnpqrstvwxyzaeiou") == 2
    assert candidate(word = "aeiouaeiouxyzaeiouaeiouxyzaeiouaeiouxyz") == 63
    assert candidate(word = "aeioubaeioucaeioudeaeioufaeioubaeioucaeioudeaeioufaeioubaeioucaeioudeaeiouf") == 15
    assert candidate(word = "bcdaeioufghijklmnopqrstuvwxyz") == 1
    assert candidate(word = "aeiouwxyzaeiouwxyzaeiouwxyzaeiouwxyz") == 4
    assert candidate(word = "xayaioeoiuaueoieoiauiouio") == 139
    assert candidate(word = "aeioubaeiouaeioubaeiouxyzaeiouaeiouaeioubaeiou") == 90
    assert candidate(word = "aeioubaeioucaeiou") == 3
    assert candidate(word = "bcaeiouaeiouaieouacb") == 77
    assert candidate(word = "aeiouaeiouxyzaeiouaeiouxyz") == 42
    assert candidate(word = "aieouaeiouaieouaeiouaieouaeiouaieou") == 490
    assert candidate(word = "aeiouuueeiooiaaaeeoioioiaaaeeuuuiooiiu") == 348
    assert candidate(word = "aeioubaeiouaeioucaeiou") == 23
    assert candidate(word = "aeiouaeiouaeiouaeiouaeiouzzzzzzzzz") == 231
    assert candidate(word = "aeiouxyzaeiouxyzaeiouxyzaeiouxyzaeiouxyzaeiouxyzaeiouxyzaeiouxyz") == 8
    assert candidate(word = "aeiouxyzzyxwvutsrqponmlkjihgfedcbaeiouaeiou") == 22
    assert candidate(word = "aeiouxyaeiouaeiou") == 22
    assert candidate(word = "aeeeeiiiioouuuaeiouaaaeioueee") == 247
    assert candidate(word = "aeiouxyzaeiouxyzaeiouxyzaeiouxyzaeiouxyz") == 5
    assert candidate(word = "aeioucaeioubaeiouaeiou") == 23
    assert candidate(word = "aeiouxyzaeiouxyzaeiouxyzaeiouxyzaeiou") == 5
    assert candidate(word = "xyzaeiouaeiouxyzaeiouaeiouxyz") == 42
    assert candidate(word = "mnopqrstuvwxyaeiouaeiouxyzaeiouxyzzyxwvutsrqponmlkjihgfedcbaeiou") == 23
    assert candidate(word = "bcaeiouc") == 1
    assert candidate(word = "aeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiou") == 4656
    assert candidate(word = "aeioueoiuaeiouaeioua") == 125
    assert candidate(word = "aabbccddeeeffgghhiijjkkllmmnnooouuupppqqrrsstttuuuvvvwwxxyyzz") == 0
    assert candidate(word = "aeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiou") == 1081
    assert candidate(word = "aeiouaeiouxyzaeiouaeiouxyzaeiouaeiouxyzaeiouaeiouxyzaeiouaeiouxyz") == 105
    assert candidate(word = "aeiouaeiouxxxaeiouaeiou") == 42
    assert candidate(word = "aebcioudfeiauoceioua") == 2
    assert candidate(word = "aouieaeioueaouieaeiou") == 139
    assert candidate(word = "aeiouaeiouabcdeiouaeiouabcdeiouaeiou") == 64
    assert candidate(word = "zzzzzvvvvvaeeeiioouuuaeiou") == 44
    assert candidate(word = "uoieaueoiaueoiaueoiaueoiaeiou") == 317
    assert candidate(word = "bcdfeaioueaiouaeioueaioueaiou") == 229
    assert candidate(word = "aeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiou") == 1596
    assert candidate(word = "ueaiaoueoiuaeiouaeiouaeiou") == 245
    assert candidate(word = "aeiaeiouoieiouaeiou") == 93
    assert candidate(word = "aeioubaeioucaeioudaeioufaeioubaeioucaeioudaeioufaeioubaeioucaeioudaeioufxyzaeioubaeioucaeioudaeioufaeioubaeioucaeioudaeiouf") == 20
    assert candidate(word = "uoieaueoiaueoiaueoiaueoiaeiouaeiouaeiouaeiouaeiou") == 1027
    assert candidate(word = "aeiooouiaeiouaeiou") == 92
    assert candidate(word = "aeioubaeiouaeioubaeiouxyzaeiouaeiouaeioubaeiouxyzaeiouaeioubaeiou") == 112
    assert candidate(word = "aabbccddeeffggahhiiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 0
    assert candidate(word = "xyzaeiouaeiouxyz") == 21
    assert candidate(word = "aeioueoiuaeiouaeioueoiuaeiouaeioueoiu") == 529
    assert candidate(word = "zzzzzaeiouzzzzzzzzzz") == 1
    assert candidate(word = "zbcdefghijklmnopqrstuvwxyaeiou") == 1
    assert candidate(word = "bcdfgohueaioeuncdfeoiu") == 5
    assert candidate(word = "aeioubaeioucaeioudaeioubaeioucaeioudaeioubaeioucaeiou") == 9
    assert candidate(word = "xaaaeeeiiiiooooouuuuuaaaeiiiou") == 131
    assert candidate(word = "eiaouoieaueioaeioaeiaoueioea") == 253
    assert candidate(word = "aeiouaeiouaeiouxyzaeiouaeiouaeiouxyzaeiouaeiou") == 153
    assert candidate(word = "aeiouxyzaeiouxyzaeiouxyz") == 3
    assert candidate(word = "mnopqrstuvwxyaeiouaeiouxyz") == 21
    assert candidate(word = "aeiouaeiouxyzaeiouaeiouxyzaeiouaeiouxyzaeiouaeiouxyz") == 84
    assert candidate(word = "xyzaeiouaeiouaeiouaeiouaeiouaeiouxyz") == 351
    assert candidate(word = "baeiouaeiouaeiouaeiouaeiou") == 231
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 0
    assert candidate(word = "aeioubaeioucaeioudeaeiouf") == 5
    assert candidate(word = "oiueaeiouaeiouaeiouaeiouaeiouaeiou") == 461
    assert candidate(word = "aeioubaeiouaeiouaeiouaeiou") == 137
    assert candidate(word = "zzzzzaeiouzzzzz") == 1
    assert candidate(word = "baeioucaeiouaeioucb") == 22
    assert candidate(word = "eiouaeioua") == 21
    assert candidate(word = "aeioubaeiouaeioubaeiou") == 23
    assert candidate(word = "xyzabcdeioufghijklmnopqrstuvwaeiou") == 1
    assert candidate(word = "aeiouaeeeeeiioouuuuuaeiou") == 146
    assert candidate(word = "abcdeioua") == 1
    assert candidate(word = "aeioubaeioucaeioudeaeioufaeioubaeioucaeioudeaeiouf") == 10
    assert candidate(word = "aeioueaioueaioueaioueaioueaiou") == 350
    assert candidate(word = "aeioubaeiouaeioubaeiouaeiou") == 43
    assert candidate(word = "aeiouaeiouaebcdeaeiouaeiou") == 63
    assert candidate(word = "aeiouaeiouaeiouaeiouaeiouaeiou") == 351
    assert candidate(word = "aeiouaeiouaeiouaeiou") == 136
    assert candidate(word = "xyzaeiouaeiouxyzaeiouaeiouxyzaeiouaeiouxyzaeiouaeiou") == 84
    assert candidate(word = "aeiouzyxwvutsrqponmlkjihgfedcbaeiou") == 2
    assert candidate(word = "aeiouzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(word = "aeiouxyzzyxwvutsrqponmlkjihgfedcbaeiouaeiouaeiouxyzaeiouxyzzyxwvutsrqponmlkjihgfedcbaeiou") == 69
    assert candidate(word = "eiouaeiouaeiouaeiouaeiouaeiou") == 325
    assert candidate(word = "aeiouaeiouxyzaeiouaeiouxyzaeiouaeiouxyzaeiouaeiouxyzaeiouaeiouxyzaeiouaeiouxyzaeiouaeiouxyz") == 147
    assert candidate(word = "xzaeiouaeiouaeiouaeiouaeioux") == 231
