# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(word = "abc") == 0
    assert candidate(word = "xyzXYZ") == 3
    assert candidate(word = "aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ") == 26
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ") == 26
    assert candidate(word = "aabbcc") == 0
    assert candidate(word = "AABBCC") == 0
    assert candidate(word = "cCcCc") == 1
    assert candidate(word = "AaBbCc") == 3
    assert candidate(word = "abBCab") == 1
    assert candidate(word = "AbCdEfGhIjKlMnOpQrStUvWxYz") == 0
    assert candidate(word = "XyZxYz") == 3
    assert candidate(word = "a") == 0
    assert candidate(word = "A") == 0
    assert candidate(word = "aaAbcBC") == 3
    assert candidate(word = "bBbB") == 1
    assert candidate(word = "aA") == 1
    assert candidate(word = "") == 0
    assert candidate(word = "MixedCASEwithSPECIALSspecial") == 7
    assert candidate(word = "nestedLoopNESTED") == 5
    assert candidate(word = "kKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkK") == 1
    assert candidate(word = "LongStringWithNoSpecials") == 3
    assert candidate(word = "vVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvV") == 1
    assert candidate(word = "abcdefABCDEF") == 6
    assert candidate(word = "SpecialLettersTest") == 3
    assert candidate(word = "MixedCASEwithSpecials") == 4
    assert candidate(word = "UniqueSpecialsABCDabcd") == 6
    assert candidate(word = "aaaaBBBBccccDDDDeeeeFFFFggggHHHHiiiiJJJjkkkkLLLLmmmmNNNNooooPPPqqqqRRRRssssTTTTuuuuVVVVwwwwXXXXyyyyZZZZ") == 1
    assert candidate(word = "eEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEe") == 1
    assert candidate(word = "aAbBcC") == 3
    assert candidate(word = "aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaA") == 1
    assert candidate(word = "abcABC") == 3
    assert candidate(word = "abcdefGHIJKLmnopQRstUVWxyz") == 0
    assert candidate(word = "Python3.8") == 0
    assert candidate(word = "aAbBC") == 2
    assert candidate(word = "worldWORLD") == 5
    assert candidate(word = "xylophoneXYZ") == 2
    assert candidate(word = "aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ") == 26
    assert candidate(word = "qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM") == 26
    assert candidate(word = "nestedCASECASEnested") == 2
    assert candidate(word = "aAaAaAaAaAaAaAaAaAaA") == 1
    assert candidate(word = "SpecialsAllOverAaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz") == 26
    assert candidate(word = "AbCdefGhIjkLmnopQrstUVwXyZ") == 0
    assert candidate(word = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(word = "aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaA") == 1
    assert candidate(word = "UPPERlower") == 2
    assert candidate(word = "zZyYxXwWvVuUtTsSrRpPoOnNmMlLkKjJiIhHgGfFeEdDcCbBaA") == 25
    assert candidate(word = "NoSpecial") == 0
    assert candidate(word = "SpecialCharacters123") == 2
    assert candidate(word = "OneSpecialA") == 1
    assert candidate(word = "SingleSpeciala") == 0
    assert candidate(word = "AbcDeEfGhIjKlMnOpQrStUvWxYz") == 1
    assert candidate(word = "helloHELLO") == 4
    assert candidate(word = "HelloWorld") == 0
    assert candidate(word = "MultipleUUppercases") == 1
    assert candidate(word = "wWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwW") == 1
    assert candidate(word = "yYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyY") == 1
    assert candidate(word = "AbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYz") == 0
    assert candidate(word = "TrailingSpecialsAaBbCc") == 4
    assert candidate(word = "abcABCabcABCabcABC") == 3
    assert candidate(word = "JustOneSpecialCharacterb") == 2
    assert candidate(word = "iIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiI") == 1
    assert candidate(word = "noSpecial") == 0
    assert candidate(word = "NoSpecialCharacters") == 2
    assert candidate(word = "SpecialCharacters") == 2
    assert candidate(word = "lowerCASEuppercase") == 4
    assert candidate(word = "UniqueUniqueUniqueUnique") == 1
    assert candidate(word = "CASEsensitive") == 2
    assert candidate(word = "OneSpecialAa") == 1
    assert candidate(word = "SingleSpecialA") == 1
    assert candidate(word = "jJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJ") == 1
    assert candidate(word = "bBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbB") == 1
    assert candidate(word = "aabbCCddeeffGGhhiiJJkkllMMnnooppQQrrssttuuVVwwxxyyzz") == 0
    assert candidate(word = "MultipleMultipleMultiple") == 0
    assert candidate(word = "ComplexMixAaBbCc123!@#AaBbCc") == 4
    assert candidate(word = "TestCase") == 1
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzAaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz") == 26
    assert candidate(word = "mMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmM") == 1
    assert candidate(word = "NestedSpecialsAaBBbbCCcc") == 4
    assert candidate(word = "fFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFf") == 1
    assert candidate(word = "lLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlL") == 1
    assert candidate(word = "tTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtT") == 1
    assert candidate(word = "abcdEFGHijKLMnopQRSTuvWXyz") == 0
    assert candidate(word = "JustOneAa") == 1
    assert candidate(word = "nNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnN") == 1
    assert candidate(word = "StartingWithSpecialsAaBbCc") == 4
    assert candidate(word = "uniqueUnique") == 1
    assert candidate(word = "gGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgG") == 1
    assert candidate(word = "xXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX") == 1
    assert candidate(word = "AaAaAaAaAaBbBbBbBbCcCcCcCcDdDdDdDdEeEeEeEeFfFfFfFfGgGgGgGgHhHhHhHhIiIiIiIiJjJjJjJjKkKkKkKkLlLlLlLlMmMmMmMmNnNnNnNnOoOoOoOoPpPpPpPpQqQqQqQqRrRrRrRrSsSsSsSsTtTtTtTtUuUuUuUuVvVvVvVvWwWwWwWwXxXxXxXxYyYyYyYyZzZzZzZz") == 26
    assert candidate(word = "specialCharSPECIAL") == 7
    assert candidate(word = "hHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhH") == 1
    assert candidate(word = "AlphabetSoup") == 1
    assert candidate(word = "AaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAa") == 1
    assert candidate(word = "RepeatRepeatREPEAT") == 4
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ") == 1
    assert candidate(word = "pPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpP") == 1
    assert candidate(word = "aA1Bb2Cc3Dd4Ee5Ff6Gg7Hh8Ii9Jj0") == 10
    assert candidate(word = "specialCharacters") == 1
    assert candidate(word = "sSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsS") == 1
    assert candidate(word = "aAaAaA") == 1
    assert candidate(word = "JustOneZz") == 1
    assert candidate(word = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZzAaBbCc") == 26
    assert candidate(word = "Zebra") == 0
    assert candidate(word = "EndingWithSpecialsAaBbCc") == 5
    assert candidate(word = "aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZ") == 0
    assert candidate(word = "bbbbbbbbBBBBBBB") == 1
    assert candidate(word = "RePeAtInGChaRaCtErS") == 3
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzABCD") == 4
    assert candidate(word = "AaBbCc1234567890!@#$%^&*()") == 3
    assert candidate(word = "repeatedCHARactersCHARacters") == 3
    assert candidate(word = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZzabcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(word = "UniqueCASE") == 2
    assert candidate(word = "doubleDOUBLEtrouble") == 6
    assert candidate(word = "PythonIsAwesome") == 0
    assert candidate(word = "MixedCASE123") == 1
    assert candidate(word = "QwErTyUiOpAsDfGhJkLzXcVbNm") == 0
    assert candidate(word = "rRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrR") == 1
    assert candidate(word = "abCDefGHijKLmnopQRstUVwxYZ") == 0
    assert candidate(word = "abcABCdefDEFghiGHI") == 9
    assert candidate(word = "pythonPYTHON") == 6
    assert candidate(word = "OverlapOverlap") == 0
    assert candidate(word = "aBcDeFgHiJkLmNoPqRsTuVwXyZ") == 0
    assert candidate(word = "CASEcase") == 4
    assert candidate(word = "testCaseTestCase") == 1
    assert candidate(word = "specialCHARSareHERE") == 5
    assert candidate(word = "SingleSpecialAa") == 1
    assert candidate(word = "qQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQ") == 1
    assert candidate(word = "aaBBccDDeeFFggHHiiJJkkLLmmNNooPPqqRRssTTuuVVwwXXyyZZ") == 0
    assert candidate(word = "dDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd") == 1
    assert candidate(word = "SsEeCcIiAaLlTtCcHaArAcCtTeErsRsS") == 8
    assert candidate(word = "JustOneSpecialCharacterB") == 2
    assert candidate(word = "bBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbB") == 1
    assert candidate(word = "aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAa") == 1
    assert candidate(word = "NoRepeatsJustSpecialsAaBbCc") == 4
    assert candidate(word = "MiXeDcAsEwItHiSmOvEs") == 4
    assert candidate(word = "HelloWORLD") == 2
    assert candidate(word = "SpecialCharactersTEST") == 4
    assert candidate(word = "ZzYyXxWwVvUuTtSsRrQqPpOoNnMmLlKkJjIiHhGgFfEeDdCcBbAa") == 26
    assert candidate(word = "oOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoO") == 1
    assert candidate(word = "SpecialCHARacters") == 4
    assert candidate(word = "zZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZ") == 1
    assert candidate(word = "MultiplELowercases") == 2
    assert candidate(word = "AabbCCddeEFFgghhIIjjKKllMMnnooppQQrrSsttUuvvWwXxyyZz") == 7
    assert candidate(word = "MiXeDcAsE123") == 1
    assert candidate(word = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz") == 26
    assert candidate(word = "OverlapAaBbCcAaBbCc") == 3
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 0
    assert candidate(word = "uniqueUnIQUE") == 4
    assert candidate(word = "helloWorldHELLO") == 4
    assert candidate(word = "specialSPECIAL") == 7
    assert candidate(word = "PythonProgramming") == 0
    assert candidate(word = "cCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCc") == 1
    assert candidate(word = "uUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuU") == 1
    assert candidate(word = "SpecialAndNormalChars123!@#") == 4
    assert candidate(word = "Mississippi") == 0
    assert candidate(word = "MixedCASEWithSOMEspecial") == 4
    assert candidate(word = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz1234567890") == 26
    assert candidate(word = "NoSpecialHere") == 0
    assert candidate(word = "aaaaaaaaaAAAAAA") == 1
