# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "zzzzzzzzz") == "zz"
    assert candidate(s = "aaabbbccc") == "aabbcc"
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == "abcdefghijklmnopqrstuvwxyz"
    assert candidate(s = "aabbaa") == "aabbaa"
    assert candidate(s = "leeetcode") == "leetcode"
    assert candidate(s = "aaaaa") == "aa"
    assert candidate(s = "ccccccaaa") == "ccaa"
    assert candidate(s = "aabbccddd") == "aabbccdd"
    assert candidate(s = "cccaaa") == "ccaa"
    assert candidate(s = "aaa") == "aa"
    assert candidate(s = "aababab") == "aababab"
    assert candidate(s = "aaaabbbcccaa") == "aabbccaa"
    assert candidate(s = "aaaabbbbcccc") == "aabbcc"
    assert candidate(s = "zzzzzzzzzz") == "zz"
    assert candidate(s = "ababababc") == "ababababc"
    assert candidate(s = "abacadaeafag") == "abacadaeafag"
    assert candidate(s = "abc") == "abc"
    assert candidate(s = "aabbaaabbbaaa") == "aabbaabbaa"
    assert candidate(s = "aab") == "aab"
    assert candidate(s = "aabbcc") == "aabbcc"
    assert candidate(s = "mississippi") == "mississippi"
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz"
    assert candidate(s = "xyzzzxxzzzz") == "xyzzxxzz"
    assert candidate(s = "aaabaaaa") == "aabaa"
    assert candidate(s = "abcdefg") == "abcdefg"
    assert candidate(s = "aabbccddeeefffggghhhiiiijjjkkklllmmmnnnooopppqqqrrrssstttuuuvvvwwwwwxxxxyyyzzz") == "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz"
    assert candidate(s = "abcabcabcabc") == "abcabcabcabc"
    assert candidate(s = "pppaaabbbcccddddeeeffffggghhhhiiiijjjjjkkkkklllllmmmmmnnnnnooooooopppppqqqqqrrrrrssssstttttuuuuuuvvvvvvvvvvwwwwwwxxxxxyyyyzzzzz") == "ppaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz"
    assert candidate(s = "xyzzzzzzzzzyx") == "xyzzyx"
    assert candidate(s = "mnonononojmnonononojmnonononoj") == "mnonononojmnonononojmnonononoj"
    assert candidate(s = "pppqqqrssstttuuuvvvwwwxxyyyzzz") == "ppqqrssttuuvvwwxxyyzz"
    assert candidate(s = "aabbccddeeefff") == "aabbccddeeff"
    assert candidate(s = "abcdefghijjjjjklmnopqrstuvwxyz") == "abcdefghijjklmnopqrstuvwxyz"
    assert candidate(s = "nnneennneennneennn") == "nneenneenneenn"
