# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(word = "AB") == True
    assert candidate(word = "Python") == True
    assert candidate(word = "python") == True
    assert candidate(word = "USA") == True
    assert candidate(word = "ab") == True
    assert candidate(word = "hello") == True
    assert candidate(word = "gOOgle") == False
    assert candidate(word = "Leetcode") == True
    assert candidate(word = "ABcD") == False
    assert candidate(word = "Google") == True
    assert candidate(word = "AbcD") == False
    assert candidate(word = "a") == True
    assert candidate(word = "A") == True
    assert candidate(word = "leetcode") == True
    assert candidate(word = "HELLO") == True
    assert candidate(word = "HelloWorld") == False
    assert candidate(word = "FlaG") == False
    assert candidate(word = "HELloworld") == False
    assert candidate(word = "INSTAGRAMSERVICES") == True
    assert candidate(word = "mNoPqR") == False
    assert candidate(word = "FACEBOOK") == True
    assert candidate(word = "cYbErSeCUrIty") == False
    assert candidate(word = "RoaDmAP") == False
    assert candidate(word = "AmaZoN") == False
    assert candidate(word = "Aaaaaaaaa") == True
    assert candidate(word = "QwErTyUiOp") == False
    assert candidate(word = "abcdefghij") == True
    assert candidate(word = "INTERNET") == True
    assert candidate(word = "M") == True
    assert candidate(word = "pRoGrAmMiNg") == False
    assert candidate(word = "rANDOMIZE") == False
    assert candidate(word = "aMAzOaN") == False
    assert candidate(word = "aNIMaTiOn") == False
    assert candidate(word = "dEveLopMeNt") == False
    assert candidate(word = "SNAPCHATWEB") == True
    assert candidate(word = "SiMpLe") == False
    assert candidate(word = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz") == False
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ") == False
    assert candidate(word = "aBCdEfGhI") == False
    assert candidate(word = "AbCdEfGh") == False
    assert candidate(word = "wEb") == False
    assert candidate(word = "sWift") == False
    assert candidate(word = "TeChNiCaL") == False
    assert candidate(word = "bUG") == False
    assert candidate(word = "sUpErCaLiFrAgIlIsTiCcExPiAlIdOiCiOuS") == False
    assert candidate(word = "GoogleIsAmazing") == False
    assert candidate(word = "AlibabaCloud") == False
    assert candidate(word = "AbCdEfGhIj") == False
    assert candidate(word = "flag") == True
    assert candidate(word = "SNAPCHAT") == True
    assert candidate(word = "alibaba") == True
    assert candidate(word = "lower") == True
    assert candidate(word = "internationalization") == True
    assert candidate(word = "ABCDEFGHijklmnopqrstuvwxyz") == False
    assert candidate(word = "cLoudCOmPUTInG") == False
    assert candidate(word = "world") == True
    assert candidate(word = "AbcDefGhIjKlMnopQrstUvWxyZ") == False
    assert candidate(word = "TitleCase") == False
    assert candidate(word = "FLICKRWEB") == True
    assert candidate(word = "HaRdWaRE") == False
    assert candidate(word = "fAceBoOk") == False
    assert candidate(word = "JupyTeR") == False
    assert candidate(word = "PYTHON") == True
    assert candidate(word = "CdEf") == False
    assert candidate(word = "SuperCalifragilisticexpialidocious") == False
    assert candidate(word = "MachiNeLEARNING") == False
    assert candidate(word = "Internationalization") == True
    assert candidate(word = "APPLECOMPUTER") == True
    assert candidate(word = "eNd") == False
    assert candidate(word = "machinelearning") == True
    assert candidate(word = "AuDiO") == False
    assert candidate(word = "aAaAaA") == False
    assert candidate(word = "AbCdEfGhIjKlMnOpQrStUvWxYzA") == False
    assert candidate(word = "iNTERNATIONALIZATION") == False
    assert candidate(word = "pRoJeCt") == False
    assert candidate(word = "FLICKR") == True
    assert candidate(word = "qwen") == True
    assert candidate(word = "lAnGuAgE") == False
    assert candidate(word = "physICs") == False
    assert candidate(word = "cSHaRp") == False
    assert candidate(word = "EDiToR") == False
    assert candidate(word = "FaCeBoOk") == False
    assert candidate(word = "aB") == False
    assert candidate(word = "oNE") == False
    assert candidate(word = "aNATOMy") == False
    assert candidate(word = "QwErTyUiOpAsDfGhJkLzXcVbNm") == False
    assert candidate(word = "FACEBOOKINSTAGRAM") == True
    assert candidate(word = "aBcDeFgHiJkLmNoPqRsTuVwXyZ") == False
    assert candidate(word = "MaChInE") == False
    assert candidate(word = "ABc") == False
    assert candidate(word = "java") == True
    assert candidate(word = "CoMpLiCATED") == False
    assert candidate(word = "gOOGLE") == False
    assert candidate(word = "AMAZONWEB") == True
    assert candidate(word = "Alibaba") == True
    assert candidate(word = "pROGRaMMiNG") == False
    assert candidate(word = "xMl") == False
    assert candidate(word = "RaDIo") == False
    assert candidate(word = "INternationalization") == False
    assert candidate(word = "iNtErNaTioNaL") == False
    assert candidate(word = "uSeR") == False
    assert candidate(word = "INSTAGRAM") == True
    assert candidate(word = "AbCdEfGhIjKlMnOpQrSt") == False
    assert candidate(word = "ABCDEFGHIjklmnopqr") == False
    assert candidate(word = "Zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == True
    assert candidate(word = "lowercase") == True
    assert candidate(word = "MuSiC") == False
    assert candidate(word = "fAcEboOk") == False
    assert candidate(word = "YOUTUBESERVICES") == True
    assert candidate(word = "aPpLiCaTiOn") == False
    assert candidate(word = "Ba") == True
    assert candidate(word = "s") == True
    assert candidate(word = "AbCdEfGhIjKlMnOp") == False
    assert candidate(word = "yOuTuBe") == False
    assert candidate(word = "fRoM") == False
    assert candidate(word = "gRaphIcS") == False
    assert candidate(word = "cGraPhIcs") == False
    assert candidate(word = "eCONoMiCS") == False
    assert candidate(word = "SiNgEr") == False
    assert candidate(word = "abcdefgh") == True
    assert candidate(word = "PRoDUCeR") == False
    assert candidate(word = "vIdEoGaMe") == False
    assert candidate(word = "GOOGLESERVICES") == True
    assert candidate(word = "Z") == True
    assert candidate(word = "z") == True
    assert candidate(word = "BuSINESSiNTelligence") == False
    assert candidate(word = "EBAY") == True
    assert candidate(word = "rEddIt") == False
    assert candidate(word = "CAPITALIZATION") == True
    assert candidate(word = "wOrLd") == False
    assert candidate(word = "abcdefghijKlmnopqrSTUVWXyz") == False
    assert candidate(word = "InValid") == False
    assert candidate(word = "data") == True
    assert candidate(word = "TWo") == False
    assert candidate(word = "wEbDeVeLopMeNt") == False
    assert candidate(word = "cDEF") == False
    assert candidate(word = "RUsT") == False
    assert candidate(word = "MICROSOFTAZURE") == True
    assert candidate(word = "MiCROsOfT") == False
    assert candidate(word = "UPPERlower") == False
    assert candidate(word = "MICROSOFTCLOUD") == True
    assert candidate(word = "openAI") == False
    assert candidate(word = "ViDIoGraPhEr") == False
    assert candidate(word = "YouTube") == False
    assert candidate(word = "hACK") == False
    assert candidate(word = "Ab") == True
    assert candidate(word = "jSoN") == False
    assert candidate(word = "DiReCtOr") == False
    assert candidate(word = "aPPlE") == False
    assert candidate(word = "ZyxWvuTsRqPoNmLkJiHgFeDcBa") == False
    assert candidate(word = "FACEBOOKWEB") == True
    assert candidate(word = "AbcDefGhIjKlMnopQrstUvWxyz") == False
    assert candidate(word = "WRiTeR") == False
    assert candidate(word = "tELEviSiOn") == False
    assert candidate(word = "FLICKRSERVICES") == True
    assert candidate(word = "YOUTUBE") == True
    assert candidate(word = "ai") == True
    assert candidate(word = "TUMBLRSERVICES") == True
    assert candidate(word = "artificialintelligence") == True
    assert candidate(word = "bUiLd") == False
    assert candidate(word = "gAmEs") == False
    assert candidate(word = "GOOGLEWEB") == True
    assert candidate(word = "PHp") == False
    assert candidate(word = "applecomputer") == True
    assert candidate(word = "openai") == True
    assert candidate(word = "LoWeRuPPeR") == False
    assert candidate(word = "ArtificialIntelligence") == False
    assert candidate(word = "qwenai") == True
    assert candidate(word = "TyPeScRiPT") == False
    assert candidate(word = "wEbSiTe") == False
    assert candidate(word = "pRoGrAmMaR") == False
    assert candidate(word = "AMericA") == False
    assert candidate(word = "AbCdEfGhIjKl") == False
    assert candidate(word = "cOdInG") == False
    assert candidate(word = "SPSS") == True
    assert candidate(word = "JAVA") == True
    assert candidate(word = "hELLO") == False
    assert candidate(word = "PsYCHOLOgY") == False
    assert candidate(word = "aBcDeFgHiJ") == False
    assert candidate(word = "allUPPER") == False
    assert candidate(word = "Defg") == True
    assert candidate(word = "tHISISATEST") == False
    assert candidate(word = "TUMBLR") == True
    assert candidate(word = "OpenAI") == False
    assert candidate(word = "wHiTtEr") == False
    assert candidate(word = "PyThOnPrOgRaM") == False
    assert candidate(word = "LeArNiNg") == False
    assert candidate(word = "AMAZONWEBSERVICES") == True
    assert candidate(word = "iOS") == False
    assert candidate(word = "FLaG") == False
    assert candidate(word = "QWENAI") == True
    assert candidate(word = "bAcK") == False
    assert candidate(word = "ALLUPPERCASE") == True
    assert candidate(word = "SAP") == True
    assert candidate(word = "UPPERCASE") == True
    assert candidate(word = "STATA") == True
    assert candidate(word = "FlAG") == False
    assert candidate(word = "SlAcK") == False
    assert candidate(word = "NeWs") == False
    assert candidate(word = "vIsUAlsTuDiOs") == False
    assert candidate(word = "tWItTeR") == False
    assert candidate(word = "LINKEDINSERVICES") == True
    assert candidate(word = "RuBuY") == False
    assert candidate(word = "THISISATEST") == True
    assert candidate(word = "ThIsIsAtEsT") == False
    assert candidate(word = "AAAAAAAAA") == True
    assert candidate(word = "AlLcaPslOcK") == False
    assert candidate(word = "gOOgLE") == False
    assert candidate(word = "PyThOn") == False
    assert candidate(word = "HELLOworld") == False
    assert candidate(word = "MaThS") == False
    assert candidate(word = "AbCdEfGhIjKlMnOpQrStUvWx") == False
    assert candidate(word = "tHIsSHOULDBEFalse") == False
    assert candidate(word = "Qwen") == True
    assert candidate(word = "INTERNationalIZATION") == False
    assert candidate(word = "PhYSIOlOGy") == False
    assert candidate(word = "dEfInE") == False
    assert candidate(word = "MiXeD123") == False
    assert candidate(word = "SNAPCHATSERVICES") == True
    assert candidate(word = "AbCDeFgHiJkLmNoPqRsTuVwXyZ") == False
    assert candidate(word = "GOOGLE") == True
    assert candidate(word = "WRiTEr") == False
    assert candidate(word = "AcTReSS") == False
    assert candidate(word = "gOOD") == False
    assert candidate(word = "AbCdEfGhIjKlMnOpQrStUvWxYz") == False
    assert candidate(word = "ArTIFICiALiNTelligence") == False
    assert candidate(word = "AbCd") == False
    assert candidate(word = "ValidCapital") == False
    assert candidate(word = "microsoft") == True
    assert candidate(word = "LINKEDIN") == True
    assert candidate(word = "EBAYSERVICES") == True
    assert candidate(word = "AMAZON") == True
    assert candidate(word = "AbCdEf") == False
    assert candidate(word = "ORAcLe") == False
    assert candidate(word = "AMaZiNg") == False
    assert candidate(word = "NeURALnETWORKS") == False
    assert candidate(word = "mNopQr") == False
    assert candidate(word = "ALIBABA") == True
    assert candidate(word = "america") == True
    assert candidate(word = "cOdE") == False
    assert candidate(word = "HTmL") == False
    assert candidate(word = "GoogleSearch") == False
    assert candidate(word = "ThisIsATest") == False
    assert candidate(word = "DROPBOXWEB") == True
    assert candidate(word = "MACHINELEARNING") == True
    assert candidate(word = "Go") == True
    assert candidate(word = "tEsT") == False
    assert candidate(word = "gRaPhiCs") == False
    assert candidate(word = "OPENAI") == True
    assert candidate(word = "DataSCIENCE") == False
    assert candidate(word = "hISToRY") == False
    assert candidate(word = "oneTWOthreeFOUR") == False
    assert candidate(word = "TUMBLRWEB") == True
    assert candidate(word = "MaNaGeR") == False
    assert candidate(word = "mAkE") == False
    assert candidate(word = "mEsSeNger") == False
    assert candidate(word = "RoBOtIcs") == False
    assert candidate(word = "sUPERCALIFRAGILISTICEXPIALIDOCIOUS") == False
    assert candidate(word = "AbCdEfGhIjKlMnOpQr") == False
    assert candidate(word = "m") == True
    assert candidate(word = "sOFTwaRE") == False
    assert candidate(word = "AbCdEfGhIjKlMn") == False
    assert candidate(word = "AI") == True
    assert candidate(word = "RaCT") == False
    assert candidate(word = "BingSearchEngine") == False
    assert candidate(word = "ARTIFICIALINTELLIGENCE") == True
    assert candidate(word = "oPeN") == False
    assert candidate(word = "mOVie") == False
    assert candidate(word = "AA") == True
    assert candidate(word = "mnopqr") == True
    assert candidate(word = "Aa") == True
    assert candidate(word = "abc") == True
    assert candidate(word = "TWITTER") == True
    assert candidate(word = "aLGoRiTHMs") == False
    assert candidate(word = "tO") == False
    assert candidate(word = "ZzZ") == False
    assert candidate(word = "ABCDEFGHIJKLMNOPQRSTUVWXYZ") == True
    assert candidate(word = "MACHINE") == True
    assert candidate(word = "GoOgLe") == False
    assert candidate(word = "INFORMATIONtechnology") == False
    assert candidate(word = "JSAvAsCrIpT") == False
    assert candidate(word = "kOTlIN") == False
    assert candidate(word = "MuSiCiAn") == False
    assert candidate(word = "machine") == True
    assert candidate(word = "tIKtOk") == False
    assert candidate(word = "mnopQR") == False
    assert candidate(word = "yAmL") == False
    assert candidate(word = "abCdEfGhIjKlMnOpQrStUvWxYz") == False
    assert candidate(word = "singleLETTER") == False
    assert candidate(word = "youtube") == True
    assert candidate(word = "sNAPcHaT") == False
    assert candidate(word = "apple") == True
    assert candidate(word = "AbCdEfGhIjKlMnOpQrStUv") == False
    assert candidate(word = "cODe") == False
    assert candidate(word = "cINeMa") == False
    assert candidate(word = "MICROSOFTWEB") == True
    assert candidate(word = "alllower") == True
    assert candidate(word = "THISisAteSt") == False
    assert candidate(word = "FLAG") == True
    assert candidate(word = "Data") == True
    assert candidate(word = "OnEtwOthReEfOuR") == False
    assert candidate(word = "pRoGrEsS") == False
    assert candidate(word = "ABCDEFGH") == True
    assert candidate(word = "TWITTERWEB") == True
    assert candidate(word = "leetCODe") == False
    assert candidate(word = "fLAG") == False
    assert candidate(word = "bA") == False
    assert candidate(word = "abcdefghijKLMNOPQR") == False
    assert candidate(word = "DISCoRd") == False
    assert candidate(word = "MakE") == False
    assert candidate(word = "bing") == True
    assert candidate(word = "gOOGLe") == False
    assert candidate(word = "vErSiOn") == False
    assert candidate(word = "eXpEriEnCe") == False
    assert candidate(word = "ThrEE") == False
    assert candidate(word = "wItH") == False
    assert candidate(word = "mICROSOFT") == False
    assert candidate(word = "MaCHiNeViSiOn") == False
    assert candidate(word = "qUaNtuMCoMpUtInG") == False
    assert candidate(word = "APPLEpie") == False
    assert candidate(word = "AaAaAa") == False
    assert candidate(word = "SAS") == True
    assert candidate(word = "MicroSoft") == False
    assert candidate(word = "DaTaANaLYsIS") == False
    assert candidate(word = "EBAYWEB") == True
    assert candidate(word = "MiXeDLoWeRuPpEr") == False
    assert candidate(word = "MATLAB") == True
    assert candidate(word = "CamelCase") == False
    assert candidate(word = "micro") == True
    assert candidate(word = "onELETTER") == False
    assert candidate(word = "MiCroSoFt") == False
    assert candidate(word = "fACeBoOk") == False
    assert candidate(word = "DATA") == True
    assert candidate(word = "TWITTERSERVICES") == True
    assert candidate(word = "sOuRcE") == False
    assert candidate(word = "DEFG") == True
    assert candidate(word = "CAPITAL") == True
    assert candidate(word = "JAVa") == False
    assert candidate(word = "dEsIgN") == False
    assert candidate(word = "FLAGship") == False
    assert candidate(word = "BING") == True
    assert candidate(word = "QwertyUiopAsDfGhJkLzXcVbNm") == False
    assert candidate(word = "GOOGLECLOUD") == True
    assert candidate(word = "alibabacloud") == True
    assert candidate(word = "DeBuGgInG") == False
    assert candidate(word = "MIXEDcase") == False
    assert candidate(word = "ApPlE") == False
    assert candidate(word = "TwItTeR") == False
    assert candidate(word = "ONE") == True
    assert candidate(word = "cOMPUTERsCIENCE") == False
    assert candidate(word = "PythonProgram") == False
    assert candidate(word = "zXcVbNmKlJ") == False
    assert candidate(word = "QwenAI") == False
    assert candidate(word = "NeTwORkS") == False
    assert candidate(word = "ZePpElIn") == False
    assert candidate(word = "AcTOr") == False
    assert candidate(word = "zYxWVuTsRqPoNmLkJiHgFeDcBa") == False
    assert candidate(word = "vIsIoN") == False
    assert candidate(word = "Three") == True
    assert candidate(word = "INSTaGram") == False
    assert candidate(word = "two") == True
    assert candidate(word = "AMERICA") == True
    assert candidate(word = "MixedCASE") == False
    assert candidate(word = "jOuRnaLiSm") == False
    assert candidate(word = "lInKeDin") == False
    assert candidate(word = "AlGoRiThMs") == False
    assert candidate(word = "JaVaScRiPt") == False
    assert candidate(word = "INSTAGRAMFACEBOOK") == True
    assert candidate(word = "DeEPLEaRNING") == False
    assert candidate(word = "APPLE") == True
    assert candidate(word = "aNdRoId") == False
    assert candidate(word = "LeetCode") == False
    assert candidate(word = "DROPBOX") == True
    assert candidate(word = "Valid") == True
    assert candidate(word = "LINKEDINWEB") == True
    assert candidate(word = "INSTAGRAMWEB") == True
    assert candidate(word = "abcdefghijklmnopqrstuvwxyz") == True
    assert candidate(word = "MachineLearning") == False
    assert candidate(word = "ALIBABACLOUD") == True
    assert candidate(word = "DataScience") == False
    assert candidate(word = "CAPITALS") == True
    assert candidate(word = "oneTWOthree") == False
    assert candidate(word = "YOUTUBEWEB") == True
    assert candidate(word = "LEETCODE") == True
    assert candidate(word = "tWiTtEr") == False
    assert candidate(word = "thisisatest") == True
    assert candidate(word = "sCALA") == False
    assert candidate(word = "bLoGgInG") == False
    assert candidate(word = "alllowercase") == True
    assert candidate(word = "TeStCaSe") == False
    assert candidate(word = "QWEN") == True
    assert candidate(word = "cSs") == False
    assert candidate(word = "aAaAaAaAaA") == False
    assert candidate(word = "Supercalifragilisticexpialidocious") == True
    assert candidate(word = "ABCDEFGHIJ") == True
    assert candidate(word = "INfOrMaTiOnSYsTEMS") == False
    assert candidate(word = "pInTeReSt") == False
    assert candidate(word = "DROPBOXSERVICES") == True
    assert candidate(word = "nOcaPslOcK") == False
    assert candidate(word = "PERL") == True
    assert candidate(word = "CoMpUtEr") == False
