# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(text = "ababab") == 2
    assert candidate(text = "") == 0
    assert candidate(text = "abcabcabc") == 3
    assert candidate(text = "aaaa") == 2
    assert candidate(text = "ab") == 0
    assert candidate(text = "abbbabbb") == 2
    assert candidate(text = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 51
    assert candidate(text = "abcd") == 0
    assert candidate(text = "abacaba") == 0
    assert candidate(text = "abc") == 0
    assert candidate(text = "leetcodeleetcode") == 2
    assert candidate(text = "banana") == 2
    assert candidate(text = "xyzxyzxyzxyz") == 4
    assert candidate(text = "abcdefg") == 0
    assert candidate(text = "racecar racecar") == 0
    assert candidate(text = "a") == 0
    assert candidate(text = "abababab") == 3
    assert candidate(text = "aabbccddeeff") == 6
    assert candidate(text = "mississippi") == 4
    assert candidate(text = "ababababab") == 4
    assert candidate(text = "xyxyxyxyxyxyxyxyxyxyxyxy") == 11
    assert candidate(text = "abacaxiabacaxiabacaxi") == 7
    assert candidate(text = "abcabcabcabcabcabcabc") == 9
    assert candidate(text = "abcdeabcdeabcdeabcde") == 6
    assert candidate(text = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 33
    assert candidate(text = "repeatedrepeatedrepeatedrepeated") == 9
    assert candidate(text = "tattattattattattat") == 8
    assert candidate(text = "aaaaabaaaabaaaa") == 7
    assert candidate(text = "racecaracecaracecar") == 6
    assert candidate(text = "abcababcababcab") == 6
    assert candidate(text = "aabbccddeeffaabbccddeeff") == 7
    assert candidate(text = "xyxyxyxyxyxyxyxyxyxyxy") == 10
    assert candidate(text = "abacabaabacaba") == 3
    assert candidate(text = "leetcodeleetcodeleetcodeleetcode") == 10
    assert candidate(text = "thisisaverylongstringthatrepeatstitselfthisisaverylongstringthatrepeatstitself") == 2
    assert candidate(text = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 26
    assert candidate(text = "aaaabaaaab") == 3
    assert candidate(text = "abcabcabcabcabcabc") == 7
    assert candidate(text = "aaaaaaa") == 3
    assert candidate(text = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij") == 20
    assert candidate(text = "abababababab") == 5
    assert candidate(text = "aaaaabcabcabcabcabc") == 8
    assert candidate(text = "qwertyqwertyqwerty") == 6
    assert candidate(text = "aabbccddeeffaabbccddeeffaabbccddeeff") == 18
    assert candidate(text = "xyzxyzxyzxyzxyzxyz") == 7
    assert candidate(text = "aabbaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 27
    assert candidate(text = "abababababababababababababababababababababababababababababababababab") == 33
    assert candidate(text = "leetcodeisgoodandleetcodeisgood") == 2
    assert candidate(text = "supercalifragilisticexpialidocioussupercalifragilisticexpialidocious") == 2
    assert candidate(text = "abacabacabacabac") == 5
    assert candidate(text = "patternpatternpatternpattern") == 9
    assert candidate(text = "mississippimississippi") == 5
    assert candidate(text = "abcdabcdabcdabcd") == 5
    assert candidate(text = "zxcvbnmlkjhgfdsazxcvbnmlkjhgfdsa") == 1
    assert candidate(text = "abcdefgabcdefgabcdefg") == 7
    assert candidate(text = "abracadabraabracadabra") == 3
    assert candidate(text = "hellohellohellohellohello") == 11
    assert candidate(text = "zzzzzzzzzzzzzzzzzzzz") == 10
    assert candidate(text = "zzzzzzzzzzzzzzzz") == 8
    assert candidate(text = "abababa") == 2
    assert candidate(text = "ababababababab") == 6
    assert candidate(text = "aaaaaaaaaa") == 5
    assert candidate(text = "abcdabcdeabcd") == 1
    assert candidate(text = "racecar") == 0
    assert candidate(text = "abcdefghabcdefgh") == 1
    assert candidate(text = "xyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxy") == 32
    assert candidate(text = "xyzxyzxyzxyzxyzxyzxyzxyz") == 10
    assert candidate(text = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 30
    assert candidate(text = "abcabcabcabc") == 4
    assert candidate(text = "abcdefghijabcdefghijabcdefghij") == 10
    assert candidate(text = "pneumonoultramicroscopicsilicovolcanoconiosis") == 0
    assert candidate(text = "aaaaa") == 2
    assert candidate(text = "abracadabrabracadabra") == 4
    assert candidate(text = "aaaaaa") == 3
    assert candidate(text = "abacabadabacabadabacaba") == 8
    assert candidate(text = "aaaaabbbbbaaaaabbbbb") == 5
    assert candidate(text = "noonnoonnoonnoon") == 7
    assert candidate(text = "abacabadabacaba") == 0
    assert candidate(text = "xyxyxyxyxyxyxyxy") == 7
    assert candidate(text = "abracadabraabracadabraabracadabraabracadabraabracadabraabracadabra") == 25
    assert candidate(text = "abcabcabcabcabc") == 6
    assert candidate(text = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 43
    assert candidate(text = "abababababababab") == 7
    assert candidate(text = "aaaaaaaaaabaaaaaaaaaa") == 5
    assert candidate(text = "aaaabbbbcccc") == 6
    assert candidate(text = "noonnoonnoonnoonnoon") == 10
    assert candidate(text = "abcxyzabcxyzabcxyz") == 6
    assert candidate(text = "abcabca") == 2
    assert candidate(text = "aaaabbbbccccddddeeeeffffgggghhhhiiiijjjjkkkkllllmmmmnnnnooooppppqqqqrrrrssssttttuuuuvvvvwwwwxxxxyyyyzzzz") == 52
    assert candidate(text = "uniqueuniqueuniqueunique") == 7
    assert candidate(text = "racecaracecar") == 2
    assert candidate(text = "abcdefabcdefabcdef") == 6
    assert candidate(text = "bananabananaananabanana") == 7
    assert candidate(text = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 32
    assert candidate(text = "bananaabanana") == 3
    assert candidate(text = "aaaabbbbccccddddeeeeffff") == 12
    assert candidate(text = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 27
    assert candidate(text = "hellohellohellohellohellohellohellohellohellohello") == 22
