# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abcdefghij",k = 3,fill = "x") == ['abc', 'def', 'ghi', 'jxx']
    assert candidate(s = "abcdefg",k = 2,fill = "z") == ['ab', 'cd', 'ef', 'gz']
    assert candidate(s = "abcdefghi",k = 3,fill = "x") == ['abc', 'def', 'ghi']
    assert candidate(s = "a",k = 1,fill = "y") == ['a']
    assert candidate(s = "python",k = 6,fill = "q") == ['python']
    assert candidate(s = "hello world",k = 4,fill = "_") == ['hell', 'o wo', 'rld_']
    assert candidate(s = "programming",k = 1,fill = "a") == ['p', 'r', 'o', 'g', 'r', 'a', 'm', 'm', 'i', 'n', 'g']
    assert candidate(s = "hello world",k = 2,fill = "_") == ['he', 'll', 'o ', 'wo', 'rl', 'd_']
    assert candidate(s = "",k = 3,fill = "b") == []
    assert candidate(s = "hello",k = 2,fill = "q") == ['he', 'll', 'oq']
    assert candidate(s = "abc",k = 5,fill = "z") == ['abczz']
    assert candidate(s = "a",k = 5,fill = "y") == ['ayyyy']
    assert candidate(s = "boundarycase",k = 8,fill = "b") == ['boundary', 'casebbbb']
    assert candidate(s = "thisisaverylongstring",k = 5,fill = "p") == ['thisi', 'saver', 'ylong', 'strin', 'gpppp']
    assert candidate(s = "abcdexyz",k = 2,fill = "g") == ['ab', 'cd', 'ex', 'yz']
    assert candidate(s = "repeatedcharacters",k = 7,fill = "e") == ['repeate', 'dcharac', 'terseee']
    assert candidate(s = "interview",k = 2,fill = "z") == ['in', 'te', 'rv', 'ie', 'wz']
    assert candidate(s = "abcdefg",k = 7,fill = "z") == ['abcdefg']
    assert candidate(s = "abcdefghijk",k = 5,fill = "m") == ['abcde', 'fghij', 'kmmmm']
    assert candidate(s = "abcdef",k = 8,fill = "n") == ['abcdefnn']
    assert candidate(s = "programming",k = 3,fill = "a") == ['pro', 'gra', 'mmi', 'nga']
    assert candidate(s = "complexstringwithfill",k = 9,fill = "r") == ['complexst', 'ringwithf', 'illrrrrrr']
    assert candidate(s = "abcd",k = 5,fill = "t") == ['abcdt']
    assert candidate(s = "almostfill",k = 9,fill = "l") == ['almostfil', 'lllllllll']
    assert candidate(s = "partitioning",k = 3,fill = "z") == ['par', 'tit', 'ion', 'ing']
    assert candidate(s = "abcdefgxyz",k = 1,fill = "m") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'x', 'y', 'z']
    assert candidate(s = "abcdefg",k = 1,fill = "d") == ['a', 'b', 'c', 'd', 'e', 'f', 'g']
    assert candidate(s = "hello",k = 4,fill = "o") == ['hell', 'oooo']
    assert candidate(s = "abcdefghijabcdefghij",k = 11,fill = "c") == ['abcdefghija', 'bcdefghijcc']
    assert candidate(s = "repeatthispattern",k = 8,fill = "m") == ['repeatth', 'ispatter', 'nmmmmmmm']
    assert candidate(s = "ab",k = 2,fill = "l") == ['ab']
    assert candidate(s = "example",k = 2,fill = "z") == ['ex', 'am', 'pl', 'ez']
    assert candidate(s = "fill",k = 1,fill = "f") == ['f', 'i', 'l', 'l']
    assert candidate(s = "thisisaverylongstringthatneedstobedivided",k = 5,fill = "a") == ['thisi', 'saver', 'ylong', 'strin', 'gthat', 'needs', 'tobed', 'ivide', 'daaaa']
    assert candidate(s = "abcdefghijk",k = 1,fill = "m") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k']
    assert candidate(s = "short",k = 5,fill = "q") == ['short']
    assert candidate(s = "thisisaverylongstring",k = 5,fill = "m") == ['thisi', 'saver', 'ylong', 'strin', 'gmmmm']
    assert candidate(s = "abcdefghij",k = 2,fill = "w") == ['ab', 'cd', 'ef', 'gh', 'ij']
    assert candidate(s = "hello",k = 4,fill = "p") == ['hell', 'oppp']
    assert candidate(s = "almostfullgroup",k = 10,fill = "a") == ['almostfull', 'groupaaaaa']
    assert candidate(s = "qwen",k = 2,fill = "q") == ['qw', 'en']
    assert candidate(s = "hello",k = 1,fill = "b") == ['h', 'e', 'l', 'l', 'o']
    assert candidate(s = "abcd",k = 2,fill = "p") == ['ab', 'cd']
    assert candidate(s = "partitioning",k = 5,fill = "p") == ['parti', 'tioni', 'ngppp']
    assert candidate(s = "thisisanexample",k = 3,fill = "y") == ['thi', 'sis', 'ane', 'xam', 'ple']
    assert candidate(s = "abcdefg",k = 10,fill = "q") == ['abcdefgqqq']
    assert candidate(s = "samecharacter",k = 2,fill = "s") == ['sa', 'me', 'ch', 'ar', 'ac', 'te', 'rs']
    assert candidate(s = "fillingwithx",k = 7,fill = "x") == ['filling', 'withxxx']
    assert candidate(s = "longerstring",k = 6,fill = "p") == ['longer', 'string']
    assert candidate(s = "algorithm",k = 4,fill = "m") == ['algo', 'rith', 'mmmm']
    assert candidate(s = "xylophone",k = 6,fill = "o") == ['xyloph', 'oneooo']
    assert candidate(s = "thisisaverylongstringthatneedstobedivided",k = 5,fill = "x") == ['thisi', 'saver', 'ylong', 'strin', 'gthat', 'needs', 'tobed', 'ivide', 'dxxxx']
    assert candidate(s = "abcdeabcdeabcdea",k = 4,fill = "w") == ['abcd', 'eabc', 'deab', 'cdea']
    assert candidate(s = "xyz",k = 1,fill = "v") == ['x', 'y', 'z']
    assert candidate(s = "evenlydivisible",k = 2,fill = "q") == ['ev', 'en', 'ly', 'di', 'vi', 'si', 'bl', 'eq']
    assert candidate(s = "programming",k = 3,fill = "w") == ['pro', 'gra', 'mmi', 'ngw']
    assert candidate(s = "boundarycase",k = 9,fill = "b") == ['boundaryc', 'asebbbbbb']
    assert candidate(s = "onemoretestcase",k = 6,fill = "t") == ['onemor', 'etestc', 'asettt']
    assert candidate(s = "abcdefg",k = 3,fill = "v") == ['abc', 'def', 'gvv']
    assert candidate(s = "equalgroups",k = 5,fill = "w") == ['equal', 'group', 'swwww']
    assert candidate(s = "equalgroups",k = 3,fill = "c") == ['equ', 'alg', 'rou', 'psc']
    assert candidate(s = "quickbrownfox",k = 3,fill = "y") == ['qui', 'ckb', 'row', 'nfo', 'xyy']
    assert candidate(s = "abcdef",k = 7,fill = "n") == ['abcdefn']
    assert candidate(s = "abcdefghij",k = 4,fill = "x") == ['abcd', 'efgh', 'ijxx']
    assert candidate(s = "abcdef",k = 7,fill = "z") == ['abcdefz']
    assert candidate(s = "zebra",k = 1,fill = "x") == ['z', 'e', 'b', 'r', 'a']
    assert candidate(s = "this is a test",k = 5,fill = "_") == ['this ', 'is a ', 'test_']
    assert candidate(s = "abcdef",k = 2,fill = "o") == ['ab', 'cd', 'ef']
    assert candidate(s = "thisisalongstring",k = 4,fill = "x") == ['this', 'isal', 'ongs', 'trin', 'gxxx']
    assert candidate(s = "partitioning",k = 7,fill = "f") == ['partiti', 'oningff']
    assert candidate(s = "example",k = 10,fill = "z") == ['examplezzz']
    assert candidate(s = "abcdefghij",k = 4,fill = "e") == ['abcd', 'efgh', 'ijee']
    assert candidate(s = "programmingisfun",k = 5,fill = "a") == ['progr', 'ammin', 'gisfu', 'naaaa']
    assert candidate(s = "thisisaverylongstringthatwillneedfilling",k = 7,fill = "a") == ['thisisa', 'verylon', 'gstring', 'thatwil', 'lneedfi', 'llingaa']
    assert candidate(s = "onetwothreefourfive",k = 6,fill = "j") == ['onetwo', 'threef', 'ourfiv', 'ejjjjj']
    assert candidate(s = "world",k = 10,fill = "c") == ['worldccccc']
    assert candidate(s = "xyz",k = 10,fill = "a") == ['xyzaaaaaaa']
    assert candidate(s = "hello world",k = 4,fill = "x") == ['hell', 'o wo', 'rldx']
    assert candidate(s = "abcdefgxyz",k = 4,fill = "a") == ['abcd', 'efgx', 'yzaa']
    assert candidate(s = "abcdefghijk",k = 4,fill = "x") == ['abcd', 'efgh', 'ijkx']
    assert candidate(s = "partition",k = 1,fill = "m") == ['p', 'a', 'r', 't', 'i', 't', 'i', 'o', 'n']
    assert candidate(s = "algorithms",k = 7,fill = "b") == ['algorit', 'hmsbbbb']
    assert candidate(s = "repeatedcharacterstest",k = 7,fill = "z") == ['repeate', 'dcharac', 'terstes', 'tzzzzzz']
    assert candidate(s = "almostfull",k = 4,fill = "i") == ['almo', 'stfu', 'llii']
    assert candidate(s = "filler",k = 11,fill = "l") == ['fillerlllll']
    assert candidate(s = "",k = 3,fill = "n") == []
    assert candidate(s = "abcdefghijk",k = 3,fill = "n") == ['abc', 'def', 'ghi', 'jkn']
    assert candidate(s = "elephants",k = 3,fill = "p") == ['ele', 'pha', 'nts']
    assert candidate(s = "short",k = 10,fill = "p") == ['shortppppp']
    assert candidate(s = "abcd",k = 6,fill = "w") == ['abcdww']
    assert candidate(s = "abcdef",k = 2,fill = "x") == ['ab', 'cd', 'ef']
    assert candidate(s = "quickbrownfox",k = 4,fill = "x") == ['quic', 'kbro', 'wnfo', 'xxxx']
    assert candidate(s = "qwert",k = 10,fill = "n") == ['qwertnnnnn']
    assert candidate(s = "machinelearning",k = 8,fill = "d") == ['machinel', 'earningd']
    assert candidate(s = "abcdef",k = 1,fill = "z") == ['a', 'b', 'c', 'd', 'e', 'f']
    assert candidate(s = "short",k = 10,fill = "b") == ['shortbbbbb']
    assert candidate(s = "programming",k = 7,fill = "a") == ['program', 'mingaaa']
    assert candidate(s = "datastructure",k = 5,fill = "a") == ['datas', 'truct', 'ureaa']
    assert candidate(s = "helloWorld",k = 3,fill = "x") == ['hel', 'loW', 'orl', 'dxx']
    assert candidate(s = "abcdefghijkmnopqrstuvwxyz",k = 5,fill = "x") == ['abcde', 'fghij', 'kmnop', 'qrstu', 'vwxyz']
    assert candidate(s = "abcdefghijk",k = 3,fill = "p") == ['abc', 'def', 'ghi', 'jkp']
    assert candidate(s = "divisiblebyk",k = 2,fill = "h") == ['di', 'vi', 'si', 'bl', 'eb', 'yk']
    assert candidate(s = "qwenassistant",k = 7,fill = "a") == ['qwenass', 'istanta']
    assert candidate(s = "cloudcomputing",k = 6,fill = "c") == ['cloudc', 'omputi', 'ngcccc']
    assert candidate(s = "longerstringexample",k = 6,fill = "n") == ['longer', 'string', 'exampl', 'ennnnn']
    assert candidate(s = "abcdefghijklnm",k = 4,fill = "r") == ['abcd', 'efgh', 'ijkl', 'nmrr']
    assert candidate(s = "algorithm",k = 5,fill = "b") == ['algor', 'ithmb']
    assert candidate(s = "quickbrownfox",k = 3,fill = "m") == ['qui', 'ckb', 'row', 'nfo', 'xmm']
    assert candidate(s = "abcd",k = 4,fill = "x") == ['abcd']
    assert candidate(s = "almostfull",k = 8,fill = "o") == ['almostfu', 'lloooooo']
