# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(n = 8) == True
    assert candidate(n = 3) == False
    assert candidate(n = 4) == True
    assert candidate(n = 9) == False
    assert candidate(n = 6) == True
    assert candidate(n = 2) == True
    assert candidate(n = 1000) == True
    assert candidate(n = 7) == False
    assert candidate(n = 10) == True
    assert candidate(n = 5) == False
    assert candidate(n = 625) == False
    assert candidate(n = 576) == True
    assert candidate(n = 729) == False
    assert candidate(n = 49) == False
    assert candidate(n = 50) == True
    assert candidate(n = 300) == True
    assert candidate(n = 99) == False
    assert candidate(n = 64) == True
    assert candidate(n = 17) == False
    assert candidate(n = 649) == False
    assert candidate(n = 23) == False
    assert candidate(n = 343) == False
    assert candidate(n = 640) == True
    assert candidate(n = 819) == False
    assert candidate(n = 128) == True
    assert candidate(n = 1024) == True
    assert candidate(n = 299) == False
    assert candidate(n = 777) == False
    assert candidate(n = 701) == False
    assert candidate(n = 999) == False
    assert candidate(n = 129) == False
    assert candidate(n = 18) == True
    assert candidate(n = 32) == True
    assert candidate(n = 256) == True
    assert candidate(n = 997) == False
    assert candidate(n = 768) == True
    assert candidate(n = 127) == False
    assert candidate(n = 81) == False
    assert candidate(n = 150) == True
    assert candidate(n = 503) == False
    assert candidate(n = 24) == True
    assert candidate(n = 15) == False
    assert candidate(n = 400) == True
    assert candidate(n = 512) == True
    assert candidate(n = 31) == False
    assert candidate(n = 377) == False
    assert candidate(n = 499) == False
    assert candidate(n = 1) == False
    assert candidate(n = 500) == True
    assert candidate(n = 420) == True
    assert candidate(n = 13) == False
