# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(columnTitle = "MAD") == 8818
    assert candidate(columnTitle = "AAA") == 703
    assert candidate(columnTitle = "ZY") == 701
    assert candidate(columnTitle = "AC") == 29
    assert candidate(columnTitle = "Z") == 26
    assert candidate(columnTitle = "ZYZ") == 18252
    assert candidate(columnTitle = "FXSHRXW") == 2147483647
    assert candidate(columnTitle = "ZAB") == 17604
    assert candidate(columnTitle = "BZ") == 78
    assert candidate(columnTitle = "M") == 13
    assert candidate(columnTitle = "ABC") == 731
    assert candidate(columnTitle = "ZZZ") == 18278
    assert candidate(columnTitle = "AB") == 28
    assert candidate(columnTitle = "A") == 1
    assert candidate(columnTitle = "XYZ") == 16900
    assert candidate(columnTitle = "ZYZY") == 474577
    assert candidate(columnTitle = "AAN") == 716
    assert candidate(columnTitle = "ACB") == 756
    assert candidate(columnTitle = "AAI") == 711
    assert candidate(columnTitle = "AAD") == 706
    assert candidate(columnTitle = "FXSHRXV") == 2147483646
    assert candidate(columnTitle = "ASDFGH") == 20638470
    assert candidate(columnTitle = "SS") == 513
    assert candidate(columnTitle = "GH") == 190
    assert candidate(columnTitle = "AAR") == 720
    assert candidate(columnTitle = "ALIBABA") == 455640953
    assert candidate(columnTitle = "PQ") == 433
    assert candidate(columnTitle = "AAE") == 707
    assert candidate(columnTitle = "UU") == 567
    assert candidate(columnTitle = "LO") == 327
    assert candidate(columnTitle = "RT") == 488
    assert candidate(columnTitle = "QWJH") == 314608
    assert candidate(columnTitle = "EEEEE") == 2376275
    assert candidate(columnTitle = "AAB") == 704
    assert candidate(columnTitle = "WORLD") == 10786572
    assert candidate(columnTitle = "IK") == 245
    assert candidate(columnTitle = "COLUMN") == 42724228
    assert candidate(columnTitle = "AZZ") == 1378
    assert candidate(columnTitle = "II") == 243
    assert candidate(columnTitle = "BAA") == 1379
    assert candidate(columnTitle = "AAM") == 715
    assert candidate(columnTitle = "DDDDD") == 1901020
    assert candidate(columnTitle = "TUVW") == 366311
    assert candidate(columnTitle = "ABB") == 730
    assert candidate(columnTitle = "BB") == 54
    assert candidate(columnTitle = "MZZ") == 9490
    assert candidate(columnTitle = "AZY") == 1377
    assert candidate(columnTitle = "VV") == 594
    assert candidate(columnTitle = "TRE") == 13993
    assert candidate(columnTitle = "AAQ") == 719
    assert candidate(columnTitle = "MN") == 352
    assert candidate(columnTitle = "TY") == 545
    assert candidate(columnTitle = "HJKL") == 147666
    assert candidate(columnTitle = "ADZ") == 806
    assert candidate(columnTitle = "AAAA") == 18279
    assert candidate(columnTitle = "CB") == 80
    assert candidate(columnTitle = "LL") == 324
    assert candidate(columnTitle = "NO") == 379
    assert candidate(columnTitle = "ABCDEFG") == 334123303
    assert candidate(columnTitle = "BCD") == 1434
    assert candidate(columnTitle = "STUVWX") == 235270254
    assert candidate(columnTitle = "PO") == 431
    assert candidate(columnTitle = "CVBNM") == 1759329
    assert candidate(columnTitle = "ALGORITHM") == 307557815253
    assert candidate(columnTitle = "QWERTY") == 212594433
    assert candidate(columnTitle = "ZXCVBN") == 319950866
    assert candidate(columnTitle = "QRSTU") == 8098345
    assert candidate(columnTitle = "ALPHABET") == 11932576390
    assert candidate(columnTitle = "UVWX") == 384590
    assert candidate(columnTitle = "DF") == 110
    assert candidate(columnTitle = "WW") == 621
    assert candidate(columnTitle = "CC") == 81
    assert candidate(columnTitle = "AAO") == 717
    assert candidate(columnTitle = "GG") == 189
    assert candidate(columnTitle = "QWEN") == 314484
    assert candidate(columnTitle = "SD") == 498
    assert candidate(columnTitle = "QWJRTYUP") == 143773244150
    assert candidate(columnTitle = "WZYZ") == 422500
    assert candidate(columnTitle = "MNBVCXZ") == 4183547654
    assert candidate(columnTitle = "FXSH") == 122182
    assert candidate(columnTitle = "PQRST") == 7623090
    assert candidate(columnTitle = "AAU") == 723
    assert candidate(columnTitle = "UI") == 555
    assert candidate(columnTitle = "NUMBER") == 176165748
    assert candidate(columnTitle = "MM") == 351
    assert candidate(columnTitle = "BAC") == 1381
    assert candidate(columnTitle = "FF") == 162
    assert candidate(columnTitle = "WX") == 622
    assert candidate(columnTitle = "FXSHRXU") == 2147483645
    assert candidate(columnTitle = "YUIOP") == 11799986
    assert candidate(columnTitle = "MATH") == 229692
    assert candidate(columnTitle = "MIX") == 9046
    assert candidate(columnTitle = "LM") == 325
    assert candidate(columnTitle = "XY") == 649
    assert candidate(columnTitle = "BBZ") == 1430
    assert candidate(columnTitle = "AAF") == 708
    assert candidate(columnTitle = "IO") == 249
    assert candidate(columnTitle = "TU") == 541
    assert candidate(columnTitle = "AEZ") == 832
    assert candidate(columnTitle = "ER") == 148
    assert candidate(columnTitle = "ZZ") == 702
    assert candidate(columnTitle = "OL") == 402
    assert candidate(columnTitle = "AAV") == 724
    assert candidate(columnTitle = "AFZ") == 858
    assert candidate(columnTitle = "AAT") == 722
    assert candidate(columnTitle = "FGHTY") == 2870841
    assert candidate(columnTitle = "QQ") == 459
    assert candidate(columnTitle = "MID") == 9026
    assert candidate(columnTitle = "DEF") == 2840
    assert candidate(columnTitle = "ST") == 514
    assert candidate(columnTitle = "ZXCVBNM") == 8318722529
    assert candidate(columnTitle = "ACZ") == 780
    assert candidate(columnTitle = "ABZ") == 754
    assert candidate(columnTitle = "RS") == 487
    assert candidate(columnTitle = "QQQQQ") == 8079335
    assert candidate(columnTitle = "AS") == 45
    assert candidate(columnTitle = "LETTERS") == 3775891099
    assert candidate(columnTitle = "XYZZY") == 11425101
    assert candidate(columnTitle = "CODING") == 42575527
    assert candidate(columnTitle = "AXX") == 1324
    assert candidate(columnTitle = "FG") == 163
    assert candidate(columnTitle = "AAH") == 710
    assert candidate(columnTitle = "QW") == 465
    assert candidate(columnTitle = "XYZZ") == 439426
    assert candidate(columnTitle = "MIXED") == 6115230
    assert candidate(columnTitle = "AGZ") == 884
    assert candidate(columnTitle = "AAL") == 714
    assert candidate(columnTitle = "UY") == 571
    assert candidate(columnTitle = "TR") == 538
    assert candidate(columnTitle = "UV") == 568
    assert candidate(columnTitle = "AXY") == 1325
    assert candidate(columnTitle = "UPPERCASE") == 4518887657679
    assert candidate(columnTitle = "AAK") == 713
    assert candidate(columnTitle = "VBN") == 14938
    assert candidate(columnTitle = "ZZZZ") == 475254
    assert candidate(columnTitle = "HJ") == 218
    assert candidate(columnTitle = "PROGRAMMING") == 2359598803856431
    assert candidate(columnTitle = "ZYXWVUT") == 8340231686
    assert candidate(columnTitle = "CAT") == 2074
    assert candidate(columnTitle = "BNM") == 1729
    assert candidate(columnTitle = "ZZZZZ") == 12356630
    assert candidate(columnTitle = "XYZXYZ") == 297051300
    assert candidate(columnTitle = "STUVWXYZ") == 159042692380
    assert candidate(columnTitle = "SHEET") == 8826682
    assert candidate(columnTitle = "OP") == 406
    assert candidate(columnTitle = "BBA") == 1405
    assert candidate(columnTitle = "NN") == 378
    assert candidate(columnTitle = "EE") == 135
    assert candidate(columnTitle = "ZZZZZZ") == 321272406
    assert candidate(columnTitle = "MNO") == 9167
    assert candidate(columnTitle = "QR") == 460
    assert candidate(columnTitle = "AAJ") == 712
    assert candidate(columnTitle = "AAX") == 726
    assert candidate(columnTitle = "QQQQ") == 310743
    assert candidate(columnTitle = "HH") == 216
    assert candidate(columnTitle = "AZX") == 1376
    assert candidate(columnTitle = "AAZ") == 728
    assert candidate(columnTitle = "AAG") == 709
    assert candidate(columnTitle = "TITLE") == 9311541
    assert candidate(columnTitle = "BN") == 66
    assert candidate(columnTitle = "TT") == 540
    assert candidate(columnTitle = "LEETCODE") == 97994910369
    assert candidate(columnTitle = "ABCD") == 19010
    assert candidate(columnTitle = "ASDFGHJKL") == 362741755778
    assert candidate(columnTitle = "AXZ") == 1326
    assert candidate(columnTitle = "PYTHON") == 201883748
    assert candidate(columnTitle = "AAS") == 721
    assert candidate(columnTitle = "AAC") == 705
    assert candidate(columnTitle = "AA") == 27
    assert candidate(columnTitle = "OO") == 405
    assert candidate(columnTitle = "EXCEL") == 2708874
    assert candidate(columnTitle = "HELLO") == 3752127
    assert candidate(columnTitle = "GHJKL") == 3346498
    assert candidate(columnTitle = "AXB") == 1302
    assert candidate(columnTitle = "YY") == 675
    assert candidate(columnTitle = "TUVWX") == 9524110
    assert candidate(columnTitle = "DD") == 108
    assert candidate(columnTitle = "XX") == 648
    assert candidate(columnTitle = "JK") == 271
    assert candidate(columnTitle = "KL") == 298
    assert candidate(columnTitle = "RR") == 486
    assert candidate(columnTitle = "CA") == 79
    assert candidate(columnTitle = "JKLMNOPQR") == 2180488677476
    assert candidate(columnTitle = "SPREADSHEET") == 2772846287758970
    assert candidate(columnTitle = "JJ") == 270
    assert candidate(columnTitle = "DA") == 105
    assert candidate(columnTitle = "PP") == 432
    assert candidate(columnTitle = "CVB") == 2602
    assert candidate(columnTitle = "OPQR") == 274916
    assert candidate(columnTitle = "CODE") == 62977
    assert candidate(columnTitle = "AAP") == 718
    assert candidate(columnTitle = "TREND") == 9459636
    assert candidate(columnTitle = "ABCDEFGHIJKLMNOPQRSTUVWXYZ") == 256094574536617744129141650397448476
    assert candidate(columnTitle = "BEE") == 1487
    assert candidate(columnTitle = "VW") == 595
    assert candidate(columnTitle = "LMNO") == 220079
    assert candidate(columnTitle = "AAW") == 725
    assert candidate(columnTitle = "ZZZZZZZ") == 8353082582
    assert candidate(columnTitle = "ABCDEF") == 12850896
    assert candidate(columnTitle = "YZ") == 676
    assert candidate(columnTitle = "KK") == 297
