# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(columnNumber = 1) == "A"
    assert candidate(columnNumber = 28) == "AB"
    assert candidate(columnNumber = 1045) == "ANE"
    assert candidate(columnNumber = 2147483647) == "FXSHRXW"
    assert candidate(columnNumber = 456976) == "YYYZ"
    assert candidate(columnNumber = 52) == "AZ"
    assert candidate(columnNumber = 701) == "ZY"
    assert candidate(columnNumber = 1048576) == "BGQCV"
    assert candidate(columnNumber = 26) == "Z"
    assert candidate(columnNumber = 134217728) == "KGRJXH"
    assert candidate(columnNumber = 702) == "ZZ"
    assert candidate(columnNumber = 1047) == "ANG"
    assert candidate(columnNumber = 1046527) == "BGNCA"
    assert candidate(columnNumber = 351) == "MM"
    assert candidate(columnNumber = 27) == "AA"
    assert candidate(columnNumber = 4194304) == "IDPOJ"
    assert candidate(columnNumber = 466527) == "ZNCI"
    assert candidate(columnNumber = 1048575) == "BGQCU"
    assert candidate(columnNumber = 703) == "AAA"
    assert candidate(columnNumber = 1234567) == "BRFGI"
    assert candidate(columnNumber = 2702) == "CYX"
    assert candidate(columnNumber = 16384) == "XFD"
    assert candidate(columnNumber = 1000) == "ALL"
    assert candidate(columnNumber = 1379) == "BAA"
    assert candidate(columnNumber = 123456) == "FZPH"
    assert candidate(columnNumber = 4095) == "FAM"
    assert candidate(columnNumber = 676) == "YZ"
    assert candidate(columnNumber = 10000000) == "UVXWJ"
    assert candidate(columnNumber = 14776336) == "AFHRLP"
    assert candidate(columnNumber = 1378) == "AZZ"
    assert candidate(columnNumber = 140625) == "GYZQ"
    assert candidate(columnNumber = 728) == "AAZ"
    assert candidate(columnNumber = 2704) == "CYZ"
    assert candidate(columnNumber = 18278) == "ZZZ"
    assert candidate(columnNumber = 234567890) == "SSGWWX"
    assert candidate(columnNumber = 255) == "IU"
    assert candidate(columnNumber = 99999999) == "HJUNYU"
    assert candidate(columnNumber = 11829215) == "YVZUU"
