# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(words = ['a', 'ab', 'abc']) == "abc"
    assert candidate(words = ['abcde', 'bcdef', 'cdefg']) == "abcdefg"
    assert candidate(words = ['a', 'b', 'c']) == "abc"
    assert candidate(words = ['shortest', 'superstring', 'string', 'abc']) == "superstringshortestabc"
    assert candidate(words = ['abc', 'bcd', 'xyz', 'zyx']) == "zyxyzabcd"
    assert candidate(words = ['aaa', 'bbb', 'ccc']) == "aaabbbccc"
    assert candidate(words = ['abcd', 'cde', 'efg', 'ghij']) == "abcdefghij"
    assert candidate(words = ['catg', 'ctaagt', 'gcta', 'ttca', 'atgcatc']) == "gctaagttcatgcatc"
    assert candidate(words = ['apple', 'plea', 'peach']) == "appleapeach"
    assert candidate(words = ['unique', 'ness', 'super', 'set']) == "nessuperuniqueset"
    assert candidate(words = ['abcd', 'cdab', 'bcda', 'dabc']) == "bcdabcd"
    assert candidate(words = ['ab', 'bc', 'cd']) == "abcd"
    assert candidate(words = ['hello', 'world', 'abc']) == "helloworldabc"
    assert candidate(words = ['alex', 'loves', 'leetcode']) == "alexlovesleetcode"
    assert candidate(words = ['abc', 'bcd', 'cde', 'def', 'efg']) == "abcdefg"
    assert candidate(words = ['short', 'longer', 'longest']) == "shortlongerlongest"
    assert candidate(words = ['one', 'two', 'three', 'four']) == "twonethreefour"
    assert candidate(words = ['abc', 'bca', 'cab']) == "bcabc"
    assert candidate(words = ['hello', 'world', 'word', 'dlrow', 'row']) == "wordlroworldhello"
    assert candidate(words = ['abcd', 'cdef', 'efab', 'fabc']) == "cdefabcd"
    assert candidate(words = ['abc', 'bcd', 'cde', 'def', 'efg', 'fgh', 'ghi', 'hij', 'ijk', 'jkl', 'klm', 'lmn', 'mno', 'nop']) == "abcdefghijklmnop"
    assert candidate(words = ['abcd', 'cdabcd', 'bcdaabcd', 'dabcabcd', 'abcdabcd', 'bcabcd', 'cdababcd', 'dababcd', 'abcabcd', 'bcdabc', 'cdabc', 'dabc']) == "cdababcdabcabcdaabcdabcd"
    assert candidate(words = ['aaaa', 'bbba', 'abbb', 'baaa']) == "abbbaaaa"
    assert candidate(words = ['abcde', 'bcdef', 'cdefg', 'defgh', 'efghi']) == "abcdefghi"
    assert candidate(words = ['abcdef', 'bcdefg', 'cdefgh', 'defghi', 'efghij', 'fghijk', 'ghijkl', 'hijklm', 'ijklmn']) == "abcdefghijklmn"
    assert candidate(words = ['abcd', 'cdab', 'bcda', 'dabc', 'abdc', 'dcba', 'cadb', 'bdac']) == "bdacadbdabcdabdcba"
    assert candidate(words = ['abcdefghij', 'bcdefghijk', 'cdefghijkl', 'defghijklm', 'efghijklmn', 'fghijklmno', 'ghijklmnop', 'hijklmnopq', 'ijklmnopqr', 'jklmnopqrs', 'klmnopqrst', 'lmnopqrstu']) == "abcdefghijklmnopqrstu"
    assert candidate(words = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten']) == "sevenineightensixfivefourthreetwone"
    assert candidate(words = ['aabb', 'bbcc', 'ccdd', 'ddee', 'eeff', 'ffgg', 'ggaa', 'aacc', 'ccbb', 'ddeeff', 'ffggaa', 'aabbcc']) == "aaccddeeffggaabbccbb"
    assert candidate(words = ['abcd', 'cdab', 'bcda', 'dabc', 'abcd', 'cdab', 'bcda', 'dabc', 'abcd', 'cdab']) == "bcdabcd"
    assert candidate(words = ['abcd', 'cdab', 'bcda', 'dabc', 'abcdabc', 'bcdbcd']) == "abcdabcdbcdab"
    assert candidate(words = ['unique', 'words', 'here', 'are', 'some', 'more', 'complex', 'test', 'cases']) == "casesomeareherewordsuniquemorecomplextest"
    assert candidate(words = ['abcde', 'bcdef', 'cdefg', 'defgh', 'efghi', 'fghij', 'ghijk', 'hijkl', 'ijklm']) == "abcdefghijklm"
    assert candidate(words = ['ab', 'bc', 'ca', 'ac', 'ba']) == "bacabc"
    assert candidate(words = ['xyz', 'yzabc', 'abcde', 'cdefg', 'efghi', 'fghij', 'ghijk', 'hijkl', 'ijklm', 'jklmn', 'klmno', 'lmnop']) == "xyzabcdefghijklmnop"
    assert candidate(words = ['abcd', 'bcde', 'cdef', 'defg', 'efgh', 'fghi', 'ghij', 'hijk', 'ijkl', 'jklm', 'klmn', 'lmno']) == "abcdefghijklmno"
    assert candidate(words = ['overlap', 'lapover', 'lover', 'verlap', 'overla', 'verlapo', 'verlapov', 'overlapov', 'verlapove', 'lapoverla']) == "loverlapoverlapo"
    assert candidate(words = ['prefix', 'fixpre', 'refixp', 'fixpref', 'refixpr', 'fixprefi', 'refixpre', 'fixprefix', 'refixpref', 'fixprefix']) == "fixprefixpref"
    assert candidate(words = ['algorithm', 'rhythm', 'myth', 'throttle', 'thorn', 'horn']) == "thornrhythmythrottlealgorithm"
    assert candidate(words = ['aabbccdd', 'bbccddaa', 'ccddaabb', 'ddaaaabb', 'aaaabbbb', 'bbbbaaaa']) == "ddaaaabbbbaaaabbccddaabb"
    assert candidate(words = ['prefix', 'refix', 'fix', 'ix', 'x', 'suffix', 'uffix', 'ffix', 'fixy', 'xylophone', 'phone', 'honeymoon']) == "suffixylophoneymoonprefix"
    assert candidate(words = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve']) == "twelvelevenineightensevensixfivefourthreetwone"
    assert candidate(words = ['pqr', 'qrs', 'rst', 'stu', 'tuv', 'uvw', 'vwx', 'wxy', 'xyz']) == "pqrstuvwxyz"
    assert candidate(words = ['aaaa', 'aabb', 'abbb', 'bbaa', 'baab', 'baba', 'abba', 'abaa', 'baba', 'abab', 'baba', 'abab']) == "ababaabbaaaabbb"
    assert candidate(words = ['xyz', 'yzw', 'wxy', 'uvw', 'vwxy', 'wxyz', 'xyzu']) == "xyzuvwxyzw"
    assert candidate(words = ['overlap', 'laplong', 'longer', 'ergonomic', 'nomics', 'micronix', 'nixos', 'xenon', 'nonya', 'yonder', 'nder', 'derivation']) == "yonderivationxenonyamicronixosoverlaplongergonomics"
    assert candidate(words = ['abcd', 'cdab', 'bcda', 'dabc', 'abcd', 'cdab', 'bcda', 'dabc', 'abcd', 'cdab', 'bcda', 'dabc']) == "bcdabcd"
    assert candidate(words = ['abcdef', 'defghi', 'ghijkl', 'jklmno', 'mnopqr', 'nopqrs']) == "abcdefghijklmnopqrs"
    assert candidate(words = ['hello', 'world', 'foobar', 'barfoo', 'foobaz', 'bazfoo', 'bazbar', 'bazoof', 'foobazoo', 'oofbazfo']) == "bazbarfoobazoofbazfoobarworldhello"
    assert candidate(words = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve']) == "twelvelevenineightensevensixfivefourthreetwone"
    assert candidate(words = ['xyz', 'yzab', 'zabc', 'abcd', 'bcde', 'cdef', 'defg', 'efgh', 'fghi', 'ghij']) == "xyzabcdefghij"
    assert candidate(words = ['abcd', 'bcd', 'cde', 'def', 'efg', 'fgh', 'ghi', 'hij', 'ijk', 'jkl', 'klm', 'lmn']) == "abcdefghijklmn"
    assert candidate(words = ['abc', 'bca', 'cab', 'acb', 'bac', 'cba', 'ab', 'bc', 'ca', 'ba', 'ac', 'cb']) == "cbacbcabc"
    assert candidate(words = ['aabbcc', 'bbccdd', 'ccddee', 'ddeeff', 'eefggh', 'fgghii']) == "eefgghiiaabbccddeeff"
    assert candidate(words = ['abcde', 'bcdef', 'cdefg', 'defgh', 'efghi', 'fghij', 'ghijk', 'hijkl', 'ijklm', 'jklmn', 'klmno', 'lmnop']) == "abcdefghijklmnop"
    assert candidate(words = ['prefix', 'refixa', 'fixato', 'fixatra', 'ixatrace', 'xatracer', 'atracerp', 'tracerpx', 'racerpxy', 'acerpxyz', 'cerpxyzl', 'erpxyzlh', 'rpxyzlhe', 'pxyzlhet', 'xyzlhetr']) == "fixatracerpxyzlhetrprefixato"
    assert candidate(words = ['ab', 'bc', 'cd', 'da']) == "bcdab"
    assert candidate(words = ['overlap', 'lapping', 'ping', 'pingpong', 'ong', 'overlaplap', 'laplaplap', 'pingping']) == "overlaplaplappingpingpong"
    assert candidate(words = ['aabbcc', 'bbccdd', 'ccddeeff', 'ddeeffgg', 'eeffgghh']) == "aabbccddeeffgghh"
    assert candidate(words = ['abcd', 'bcde', 'cdef', 'defg', 'efgh', 'fghi', 'ghij', 'hijk', 'ijkl', 'jklm', 'klmn', 'lmno']) == "abcdefghijklmno"
    assert candidate(words = ['xyz', 'yzx', 'zxy', 'xyx', 'yxy', 'xyy', 'yxx', 'yzy', 'zyz', 'zyx', 'xzy', 'yxz']) == "yxzyzyxxyxyzxyy"
    assert candidate(words = ['one', 'two', 'three', 'four', 'five', 'six']) == "twonethreefourfivesix"
    assert candidate(words = ['abcdef', 'defabc', 'bcdefa', 'cdefab', 'defabc', 'efabcd', 'fabcde']) == "bcdefabcdef"
    assert candidate(words = ['aabbcc', 'bccdda', 'cdddee', 'ddeeff', 'effggg', 'ffgggh', 'ggghhh', 'hhhiii', 'iiiijj', 'jjjkkl', 'kkllmm', 'llmmnn']) == "cdddeeffggghhhiiiijjjkkllmmnnaabbccdda"
    assert candidate(words = ['abcde', 'bcdef', 'cdefg', 'defgh', 'efghi', 'fghij', 'ghijk', 'hijkl', 'ijklm', 'jklmn', 'klmno', 'lmnop']) == "abcdefghijklmnop"
    assert candidate(words = ['longest', 'string', 'that', 'contains', 'overlapping', 'parts']) == "longestringthatcontainsoverlappingparts"
    assert candidate(words = ['abcdef', 'defghi', 'ghijkl', 'ijklmn', 'mnopqr']) == "abcdefghijklmnopqr"
    assert candidate(words = ['abcdef', 'defghi', 'ghijkl', 'ijklmn', 'mnopqr']) == "abcdefghijklmnopqr"
    assert candidate(words = ['abcdefgh', 'efghijkl', 'ghijklmn', 'ijklmnop', 'jklmnopq', 'klmnopqr', 'mnopqrst', 'nopqrstu', 'opqrstuv', 'pqrstuvw', 'qrstuvwx', 'rstuvxyz']) == "abcdefghijklmnopqrstuvwxrstuvxyz"
    assert candidate(words = ['abcd', 'bcde', 'cdef', 'defg', 'efgh', 'fghi', 'ghij', 'hijk']) == "abcdefghijk"
    assert candidate(words = ['aabbcc', 'bbccdd', 'ccddeeff', 'ddeeffgg', 'effgghh', 'ffgghhiijj', 'gghhiijjkk', 'hhiijjkkll', 'iijjkkllmm', 'jjkkllmmnn', 'kkllmmnnoo', 'llmmnnoopp']) == "aabbccddeeffgghhiijjkkllmmnnoopp"
    assert candidate(words = ['overlap', 'lapping', 'ping', 'pingpong', 'ong']) == "overlappingpong"
    assert candidate(words = ['pqr', 'qrp', 'rqp', 'prq', 'rpq', 'pqq', 'qqp']) == "pqrpqqprqp"
    assert candidate(words = ['abcxyz', 'xyzuvw', 'uvwdef', 'defghj', 'ghjklm', 'klmnop', 'mnopqr']) == "abcxyzuvwdefghjklmnopqr"
    assert candidate(words = ['overlap', 'laptime', 'timefly', 'flyby', 'bymy', 'myself']) == "overlaptimeflybymyself"
    assert candidate(words = ['rotation', 'otationr', 'tationro', 'ationrot', 'tionrota', 'ionrotat', 'onrotate', 'nrotate', 'rotate']) == "rotationrotate"
    assert candidate(words = ['aaa', 'aab', 'aba', 'abb', 'baa', 'bab', 'bba', 'bbb', 'aabbaa', 'bbbaab']) == "bbababbbaabbaaa"
    assert candidate(words = ['abcdef', 'defabc', 'bcdefa', 'cdefab']) == "abcdefabc"
    assert candidate(words = ['abcd', 'bcde', 'cdef', 'defg']) == "abcdefg"
    assert candidate(words = ['aaaa', 'bbbb', 'cccc', 'dddd', 'eeee', 'ffff', 'gggg', 'hhhh', 'iiii', 'jjjj', 'kkkk', 'llll']) == "aaaabbbbccccddddeeeeffffgggghhhhiiiijjjjkkkkllll"
    assert candidate(words = ['qwerty', 'wertyu', 'ertyui', 'rtyuiop', 'tyuiopq', 'yuiopqr']) == "qwertyuiopqr"
    assert candidate(words = ['abcdefg', 'bcdefgh', 'cdefghi', 'defghij', 'efghijk', 'fghijkl', 'ghijklm', 'hijklmn', 'ijklmno', 'jklmnop', 'klmnopq', 'lmnopqr', 'mnopqrs', 'nopqrst']) == "abcdefghijklmnopqrst"
    assert candidate(words = ['unique', 'strings', 'for', 'this', 'problem', 'are', 'here', 'and', 'there', 'everywhere']) == "thereverywhereareproblemforthistringsuniqueand"
    assert candidate(words = ['abcdef', 'cdefgh', 'efghij', 'ghijkl']) == "abcdefghijkl"
    assert candidate(words = ['aabb', 'bbaa', 'abab', 'baba', 'abba', 'baab']) == "bababbaabb"
    assert candidate(words = ['apple', 'pleas', 'please', 'ease', 'asean', 'anean', 'nean', 'east']) == "appleaseaneaneast"
    assert candidate(words = ['pqr', 'qrs', 'rst', 'stu', 'tuv', 'uvw', 'vwx', 'wxy', 'xyz', 'yza', 'zab']) == "pqrstuvwxyzab"
    assert candidate(words = ['ab', 'ba', 'ac', 'ca', 'ad', 'da', 'ae', 'ea', 'af', 'fa', 'ag', 'ga', 'ah', 'ha', 'ai', 'ia']) == "baiahagafaeadacab"
    assert candidate(words = ['abcxyz', 'xyzuvw', 'uvwdef', 'defghi', 'ghijkl', 'jklmno', 'mnopqr', 'nopqrs', 'pqrsuv', 'qrstuv', 'vwxyza']) == "qrstuvwxyzabcxyzuvwdefghijklmnopqrsuv"
    assert candidate(words = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l']) == "abcdefghijkl"
    assert candidate(words = ['aaaa', 'bbb', 'cccc', 'dddd', 'eeee', 'ffff', 'gggg', 'hhhh', 'iiii', 'jjjj', 'kkkk', 'llll']) == "aaaabbbccccddddeeeeffffgggghhhhiiiijjjjkkkkllll"
    assert candidate(words = ['abcdef', 'defghi', 'ghijkl', 'jklmno', 'mnopqr', 'nopqrs', 'pqrsuv', 'qrstuv']) == "abcdefghijklmnopqrsuvqrstuv"
    assert candidate(words = ['abcd', 'cdab', 'bcda', 'dabc', 'abcd', 'cdab', 'bcda', 'dabc']) == "bcdabcd"
    assert candidate(words = ['abcdef', 'bcdegh', 'cdefij', 'defgkl', 'efghmn', 'fghnop', 'ghnopq', 'hnoqrs', 'noqrst', 'qrstuv', 'rstuvw', 'stuvwx']) == "bcdeghnoqrstuvwxfghnopqefghmndefgklabcdefij"
    assert candidate(words = ['ab', 'bc', 'cd', 'de', 'ef', 'fa']) == "bcdefab"
    assert candidate(words = ['abcdefgh', 'ghijklmn', 'mnopqrst', 'rstuvwxy', 'xyzabcde']) == "ghijklmnopqrstuvwxyzabcdefgh"
