# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "bcbcbc") == 6
    assert candidate(s = "cbacdcdcdbacdbad") == 14
    assert candidate(s = "aeiouaeiouaeiouaeiou") == 20
    assert candidate(s = "aaaaaeeeeeiioooouuuu") == 14
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 5
    assert candidate(s = "uuuuuuuuuuuuuuuuuuuuuuuuuuu") == 26
    assert candidate(s = "aaeeiioouu") == 10
    assert candidate(s = "aeiou") == 0
    assert candidate(s = "aaaaa") == 4
    assert candidate(s = "a") == 0
    assert candidate(s = "leetcodeisgreat") == 5
    assert candidate(s = "abacabadabacaba") == 15
    assert candidate(s = "aeiaaioaaaaeiiiiouuuooaaaaea") == 18
    assert candidate(s = "") == 0
    assert candidate(s = "aeeeeeiiiiioooouuuu") == 12
    assert candidate(s = "xyz") == 3
    assert candidate(s = "abcdefghiijkeilmnopqrstuvwxyzaeiou") == 12
    assert candidate(s = "aabbeeaabbeeaabb") == 16
    assert candidate(s = "eiouaeiouaeiou") == 10
    assert candidate(s = "eleetminicoworoep") == 13
    assert candidate(s = "bbaeixaaaaooxu") == 8
    assert candidate(s = "aioieu") == 0
    assert candidate(s = "bcdfghjklmnpqrstvwxyz") == 21
    assert candidate(s = "aeiaaioaaaaeiiiiiioooeeeauuaeuia") == 28
    assert candidate(s = "aabbccddeeff") == 12
    assert candidate(s = "leetcodeleetcode") == 16
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 52
    assert candidate(s = "zxcvbnmlkjhgfdsapoiuytrewq") == 15
    assert candidate(s = "aaaaaaaa") == 8
    assert candidate(s = "aeiouaeiouaeiouaeiouaeiouxyzuvwaeiouaeiouaeiou") == 45
    assert candidate(s = "eeioouuuaeeioouuua") == 18
    assert candidate(s = "aeiouaeiouaeiou") == 10
    assert candidate(s = "abacaxebecixodeoxou") == 9
    assert candidate(s = "thisisaverylongstringwithvariousvowels") == 13
    assert candidate(s = "eiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiou") == 40
    assert candidate(s = "uoieaouioeaoieauoi") == 12
    assert candidate(s = "mamad") == 5
    assert candidate(s = "leetcodeleetcodeleetcode") == 21
    assert candidate(s = "bbaaccddeeffgg") == 14
    assert candidate(s = "eiouaeiouaieouaeiouaeiouaeiou") == 20
    assert candidate(s = "xyzuvwaeiouaeiouxyzuvwaeiouaeiouxyzuvwaeiouaeiou") == 47
    assert candidate(s = "abcdeabcdeabcde") == 13
    assert candidate(s = "aeiouaeiouaeiouaeiouaeiouaeiouabcdeffedcbaaeiouaeiou") == 52
    assert candidate(s = "xyzabcdeiouaeiouabcdeiouaeiouxyz") == 32
    assert candidate(s = "bbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 50
    assert candidate(s = "bcbcbcbaeibcbcbcbaeibcbcbc") == 26
    assert candidate(s = "aeeeeiiiooouuuuuuuuu") == 10
    assert candidate(s = "bcbcbcabcabcabcabcabcabc") == 24
    assert candidate(s = "abacaxebecixodeoxouabacaxebecixodeoxou") == 38
    assert candidate(s = "zzzaeizzzaeiouzzzaeiouzzz") == 19
    assert candidate(s = "aeiouabcdefghijklmnopqrstuvwxyzaeiou") == 31
    assert candidate(s = "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu") == 52
    assert candidate(s = "uvceeaieeaaceeaiaa") == 17
    assert candidate(s = "aebecixodeoxouaebecixodeoxou") == 28
    assert candidate(s = "vvvvvvvvvvvvvvvvvv") == 18
    assert candidate(s = "aebecidofugoeiaoeiu") == 4
    assert candidate(s = "aeiouaeiouabcdeffedcbaaeiouaeiou") == 32
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzaeiouaeiouaeiou") == 41
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 52
    assert candidate(s = "leetcodeisgreataeiou") == 17
    assert candidate(s = "aeiouaeiouaeiouxyzuvw") == 17
    assert candidate(s = "abcdeffedcbabcdeffedcbabcdeffedcbabcdeffedcb") == 44
    assert candidate(s = "xyzuvwaeiouxyzuvwaeiou") == 22
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnmaeiouaeiou") == 31
    assert candidate(s = "vwxyz") == 5
    assert candidate(s = "aabbccddeeffgg") == 14
    assert candidate(s = "eleetminicoworoepzzzzzzzzzz") == 13
    assert candidate(s = "abecidofug") == 1
    assert candidate(s = "eiouaieouaieoua") == 10
    assert candidate(s = "aeiaoeiuioeiuaeiaoeiuioeiuaeiaoeiuioeiaoeiu") == 26
    assert candidate(s = "aeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiou") == 50
    assert candidate(s = "eiouaeiouaeiouaeiouaeiouaeiou") == 20
    assert candidate(s = "eleetminicoworoepaeiou") == 13
    assert candidate(s = "eeioouuuaeeioouuuaeeioouuuaeeioouuua") == 36
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 50
    assert candidate(s = "aabbccddeeffaabbccddeeff") == 24
    assert candidate(s = "leetcodeisgreatleetcodeisgreatleetcodeisgreat") == 35
