# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(haystack = "ababcabcabababd",needle = "ababd") == 10
    assert candidate(haystack = "abcde",needle = "f") == -1
    assert candidate(haystack = "mississippi",needle = "issi") == 1
    assert candidate(haystack = "sadbutsad",needle = "sad") == 0
    assert candidate(haystack = "abababa",needle = "aba") == 0
    assert candidate(haystack = "abcdefgh",needle = "efg") == 4
    assert candidate(haystack = "abc",needle = "c") == 2
    assert candidate(haystack = "aaaaa",needle = "bba") == -1
    assert candidate(haystack = "mississippi",needle = "issip") == 4
    assert candidate(haystack = "abc",needle = "d") == -1
    assert candidate(haystack = "a",needle = "a") == 0
    assert candidate(haystack = "hello",needle = "ll") == 2
    assert candidate(haystack = "leetcode",needle = "leeto") == -1
    assert candidate(haystack = "ababababab",needle = "aba") == 0
    assert candidate(haystack = "randomrandomrandom",needle = "random") == 0
    assert candidate(haystack = "abcdefgabcdefgabcdefg",needle = "efg") == 4
    assert candidate(haystack = "abcdefg",needle = "") == 0
    assert candidate(haystack = "a quick brown fox jumps over the lazy dog",needle = "quack") == -1
    assert candidate(haystack = "abracadabra",needle = "cad") == 4
    assert candidate(haystack = "aaaaaaabc",needle = "aaaaaab") == 1
    assert candidate(haystack = "level",needle = "eve") == 1
    assert candidate(haystack = "aaaaaa",needle = "aaa") == 0
    assert candidate(haystack = "abababab",needle = "aba") == 0
    assert candidate(haystack = "abcde",needle = "") == 0
    assert candidate(haystack = "xylophone",needle = "phone") == 4
    assert candidate(haystack = "abcdeabcdeabcde",needle = "deabc") == 3
    assert candidate(haystack = "quickbrownfox",needle = "quick") == 0
    assert candidate(haystack = "repeatedstringrepeatedstring",needle = "string") == 8
    assert candidate(haystack = "abcde",needle = "abcde") == 0
    assert candidate(haystack = "noinneedlehere",needle = "needle") == 4
    assert candidate(haystack = "banana",needle = "ana") == 1
    assert candidate(haystack = "abcdefghijklmnopqrstuvwxyz",needle = "mnop") == 12
    assert candidate(haystack = "abcabcabcabcabcabc",needle = "abcabc") == 0
    assert candidate(haystack = "boundarycase",needle = "boundarycase") == 0
    assert candidate(haystack = "abcabcabcabc",needle = "bcabc") == 1
    assert candidate(haystack = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",needle = "mnopqrstuv") == -1
    assert candidate(haystack = "sequence",needle = "qu") == 2
    assert candidate(haystack = "bananananana",needle = "nan") == 2
    assert candidate(haystack = "aaaaaaaaaaaaaaaaaa",needle = "aaaaaaaaaa") == 0
    assert candidate(haystack = "abcdefghij",needle = "jihgfedcba") == -1
    assert candidate(haystack = "abcdefghij",needle = "abcdefghij") == 0
    assert candidate(haystack = "thisisaverylongstringwithsomecharacters",needle = "characters") == 29
    assert candidate(haystack = "thisisaverylongstringwithsomerepeatingpatterns",needle = "patterns") == 38
    assert candidate(haystack = "thesamethesame",needle = "thesame") == 0
    assert candidate(haystack = "noon",needle = "noon") == 0
    assert candidate(haystack = "hellohellohellohellohello",needle = "hellohello") == 0
    assert candidate(haystack = "nnnnnnnnnn",needle = "nnnn") == 0
    assert candidate(haystack = "12345678901234567890",needle = "56789012") == 4
    assert candidate(haystack = "12345678901234567890",needle = "56789") == 4
    assert candidate(haystack = "abcabcabcabcabc",needle = "cab") == 2
    assert candidate(haystack = "thisisaverylonghaystack",needle = "averylong") == 6
    assert candidate(haystack = "hellohellohello",needle = "hellohello") == 0
    assert candidate(haystack = "singleletter",needle = "a") == -1
    assert candidate(haystack = "oneonetwoonethreeonethreeone",needle = "three") == 12
    assert candidate(haystack = "abcabcabcabcabcabc",needle = "cab") == 2
    assert candidate(haystack = "pythonprogrammingpython",needle = "thonpro") == 2
    assert candidate(haystack = "repeatedcharactersequenceeeeeeeeeeeeeee",needle = "eeeeeeee") == 24
    assert candidate(haystack = "abcdabcyabcdabc",needle = "abcdabc") == 0
    assert candidate(haystack = "mississippi",needle = "issipp") == 4
    assert candidate(haystack = "aaaaabaaaabaaaaabaaaabaaaaabaaaabaaaaabaaaab",needle = "baaab") == -1
    assert candidate(haystack = "aaaaaa",needle = "aaaaaaa") == -1
    assert candidate(haystack = "abcdefghijklmnopqrstuvwxyz",needle = "xyz") == 23
    assert candidate(haystack = "overlaplaplaplaplap",needle = "lap") == 4
    assert candidate(haystack = "aaaaabaaaaaa",needle = "aaaaab") == 0
    assert candidate(haystack = "helloworldhelloworld",needle = "worldhello") == 5
    assert candidate(haystack = "abracadabra",needle = "abra") == 0
    assert candidate(haystack = "abababababababababab",needle = "ababab") == 0
    assert candidate(haystack = "aabbccddeeffgghhiijjkk",needle = "eeffgg") == 8
    assert candidate(haystack = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",needle = "mnop") == -1
    assert candidate(haystack = "mississippiissippi",needle = "issip") == 4
    assert candidate(haystack = "aquickbrownfoxjumpsoverthelazydog",needle = "dog") == 30
    assert candidate(haystack = "abababababababab",needle = "ababab") == 0
    assert candidate(haystack = "almostsameprefixalmost",needle = "almost") == 0
    assert candidate(haystack = "qwertyuiopasdfghjklzxcvbnm",needle = "qwertyuiop") == 0
    assert candidate(haystack = "ananananananan",needle = "anana") == 0
    assert candidate(haystack = "averylongstringwithrepeatedcharactersaaaaaaaaa",needle = "aaaaaaaa") == 37
    assert candidate(haystack = "",needle = "") == 0
    assert candidate(haystack = "findinganoccurrenceinanarray",needle = "anoccurrence") == 7
    assert candidate(haystack = "repeatedrepeatedrepeated",needle = "repeated") == 0
    assert candidate(haystack = "pythonprogramming",needle = "programming") == 6
    assert candidate(haystack = "palindrome",needle = "alin") == 1
    assert candidate(haystack = "singleletter",needle = "s") == 0
    assert candidate(haystack = "aaaaaabaaaaaab",needle = "aaaaaab") == 0
    assert candidate(haystack = "thisisaverylongstringthatwilltestouralgorithm",needle = "longstring") == 11
    assert candidate(haystack = "this is a simple test",needle = "simple") == 10
    assert candidate(haystack = "aaaaabaaaabaaaaabaaaab",needle = "aaaab") == 1
    assert candidate(haystack = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",needle = "zzzzzzzzzz") == 0
    assert candidate(haystack = "repeatedrepeatedrepeated",needle = "repeatedre") == 0
    assert candidate(haystack = "thelastwordisneedle",needle = "needle") == 13
    assert candidate(haystack = "hellohellohello",needle = "lohe") == 3
    assert candidate(haystack = "abababababab",needle = "ababab") == 0
    assert candidate(haystack = "abababababab",needle = "bababa") == 1
    assert candidate(haystack = "thisisaverylongstringforatest",needle = "avery") == 6
    assert candidate(haystack = "overlappingoverlap",needle = "lapping") == 4
    assert candidate(haystack = "findthehiddenpattern",needle = "hidden") == 7
    assert candidate(haystack = "ababababab",needle = "abab") == 0
    assert candidate(haystack = "asubstringrightattheend",needle = "end") == 20
    assert candidate(haystack = "longstringthatcontainsavarietyofcharacters",needle = "characters") == 32
    assert candidate(haystack = "bananaanabanana",needle = "anaban") == 6
    assert candidate(haystack = "racecar",needle = "race") == 0
    assert candidate(haystack = "longstringwithnokeyword",needle = "keyword") == 16
    assert candidate(haystack = "abcdefghij",needle = "gh") == 6
    assert candidate(haystack = "mississippi",needle = "pi") == 9
    assert candidate(haystack = "verylonghaystackwithrepeatingcharactersaaaaaaaaaaa",needle = "aaaaa") == 39
    assert candidate(haystack = "",needle = "a") == -1
    assert candidate(haystack = "a",needle = "") == 0
    assert candidate(haystack = "09876543210987654321",needle = "654321") == 4
    assert candidate(haystack = "hellohellohello",needle = "hello") == 0
    assert candidate(haystack = "aaaaaaaaaaa",needle = "aaaaaa") == 0
    assert candidate(haystack = "thisisaverylongstringthatcontainsmultiplesubstrings",needle = "substring") == 41
    assert candidate(haystack = "uniquecharacters",needle = "characters") == 6
    assert candidate(haystack = "aaaaaaab",needle = "aaaab") == 3
    assert candidate(haystack = "almosttherealmost",needle = "almostthere") == 0
    assert candidate(haystack = "aaaaaaaaaab",needle = "aaaaaab") == 4
    assert candidate(haystack = "aaaaabaaaaabaaaaab",needle = "aaaaab") == 0
    assert candidate(haystack = "a quick brown fox jumps over the lazy dog",needle = "quick") == 2
    assert candidate(haystack = "thisisaverylongstringwithrepeatedpatterns",needle = "repeated") == 25
    assert candidate(haystack = "thisisaverylonghaystackthatcontainsavariablesubstring",needle = "substring") == 44
    assert candidate(haystack = "xxyyzzxxyyzzxxyyzz",needle = "xxyyzz") == 0
    assert candidate(haystack = "aaaaa",needle = "aa") == 0
    assert candidate(haystack = "ababababababababa",needle = "abab") == 0
    assert candidate(haystack = "a quick brown fox jumps over the lazy dog",needle = "lazy") == 33
    assert candidate(haystack = "needleinthestack",needle = "needle") == 0
    assert candidate(haystack = "aaaaaaaaaaaaaaaaaaaa",needle = "aaaaaaaaa") == 0
    assert candidate(haystack = "aaaaaaab",needle = "aaaaaab") == 1
    assert candidate(haystack = "aaaa",needle = "aaaaa") == -1
    assert candidate(haystack = "substring",needle = "string") == 3
    assert candidate(haystack = "xyzxyzxyzxyz",needle = "zyx") == -1
    assert candidate(haystack = "abababababababababab",needle = "abab") == 0
    assert candidate(haystack = "oneonetwoonetwothree",needle = "twone") == -1
    assert candidate(haystack = "bananananana",needle = "anan") == 1
    assert candidate(haystack = "xyxxyxyxyxyxyxyx",needle = "xyxyx") == 3
    assert candidate(haystack = "aaaaabaaaa",needle = "aaab") == 2
    assert candidate(haystack = "abcdefghij",needle = "efgh") == 4
    assert candidate(haystack = "overlaplaplaplap",needle = "laplap") == 4
    assert candidate(haystack = "thisisaverylongstringforsearching",needle = "searching") == 24
    assert candidate(haystack = "bananabananabanana",needle = "nan") == 2
    assert candidate(haystack = "longhaystackwithaveryspecificsubstring",needle = "averyspecific") == 16
    assert candidate(haystack = "aaaaaaa",needle = "aaaaaa") == 0
    assert candidate(haystack = "abcdefabcdefabcdefabcdef",needle = "cdef") == 2
    assert candidate(haystack = "aaaaabaaaaabaaaaabaaaaab",needle = "aaaab") == 1
    assert candidate(haystack = "hellohellohello",needle = "lohel") == 3
    assert candidate(haystack = "abcdabcdabcd",needle = "cdab") == 2
    assert candidate(haystack = "banana",needle = "na") == 2
