# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abcdeabcde") == -1
    assert candidate(s = "abba") == 2
    assert candidate(s = "zzzzzz") == -1
    assert candidate(s = "aabbcc") == 4
    assert candidate(s = "abacabadabacaba") == 1
    assert candidate(s = "abcabcabcabc") == -1
    assert candidate(s = "xyzzyx") == 4
    assert candidate(s = "abacd") == 4
    assert candidate(s = "abcdef") == 5
    assert candidate(s = "aabbccddeeff") == 10
    assert candidate(s = "abcdeabc") == 2
    assert candidate(s = "xyzabc") == 5
    assert candidate(s = "aaaa") == -1
    assert candidate(s = "abab") == -1
    assert candidate(s = "abcabcabcabcabcabcabc") == -1
    assert candidate(s = "aaabbbccc") == 6
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == -1
    assert candidate(s = "abacabadabacabadabacabad") == -1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 25
    assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghij") == -1
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == -1
    assert candidate(s = "mnopqrsmnopqrsmnopqrsmnopqrsmnopqrsmnopqrs") == -1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 60
    assert candidate(s = "abcdefgihgfedcba") == 14
    assert candidate(s = "abcdabcde") == 8
    assert candidate(s = "mnopmnopmnop") == -1
    assert candidate(s = "aabbaaabbbaaabbbaaa") == -1
    assert candidate(s = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz") == -1
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc") == -1
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbbbbccccccccdddddd") == 31
    assert candidate(s = "abcdeffedcbaa") == 10
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzxyz") == 53
    assert candidate(s = "zzzzzzzzzzzzzzz") == -1
    assert candidate(s = "abcdabcdeabcdabcdeabcd") == -1
    assert candidate(s = "abcdefabcdefabcdefabcdefabcdef") == -1
    assert candidate(s = "mnopqrsmnopqrsmnopqrs") == -1
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz") == -1
    assert candidate(s = "abcdefgabcdefgabcdefgabcdefgabcdefgabcdefg") == -1
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcd") == -1
    assert candidate(s = "abcdefgabcdefgabcdefg") == -1
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd") == 30
    assert candidate(s = "mnopqrstmnopqrstmnopqrstmnopqrstmnopqrstmnopqrst") == -1
    assert candidate(s = "abcdefgihgfedcbamnopqrsmnopqrsmnopqrs") == 21
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzab") == 48
    assert candidate(s = "abcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefg") == -1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyz") == 50
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzabcdefghijklmnopqrstuvwxyz") == -1
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabad") == -1
    assert candidate(s = "abcabcabcabcabcabcabcabcabc") == -1
    assert candidate(s = "ababababababababababababababab") == -1
    assert candidate(s = "abcdefgabcdefgabcdefgabcdefgabcdefg") == -1
    assert candidate(s = "abcdefghijabcdefghij") == -1
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == -1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 50
    assert candidate(s = "abcdefabcdefabcdefabcdef") == -1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == -1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzz") == 52
    assert candidate(s = "abcdabcdabcd") == -1
    assert candidate(s = "abababababababababababababababababababababababababababababababab") == -1
    assert candidate(s = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyz") == -1
    assert candidate(s = "abcabcabcabcabcabcabcabc") == -1
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabc") == -1
    assert candidate(s = "abababababab") == -1
    assert candidate(s = "zyxwzyxwzyxwzyxwzyxwzyxwzyxwzyxwzyxwzyxw") == -1
    assert candidate(s = "abcdefgabcdefg") == -1
    assert candidate(s = "abcdefghijkabcdefghijk") == -1
    assert candidate(s = "abababababababababababababababab") == -1
    assert candidate(s = "abacabadabac") == 1
    assert candidate(s = "aabbccddeeffgghhii") == 16
    assert candidate(s = "mnopqrstuvwxyz") == 13
    assert candidate(s = "aabbaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 54
    assert candidate(s = "abcdefgabcdefgabcdefgabcdefgh") == 28
    assert candidate(s = "abcdeffedcba") == 10
    assert candidate(s = "abcdabcdeabcdeabcde") == -1
    assert candidate(s = "aaabbbcccdddcccbbaaa") == 14
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzxy") == 51
    assert candidate(s = "qwertyqwertyqwertyqwerty") == -1
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcba") == -1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy") == -1
    assert candidate(s = "abcdeabcdeabcdeabcdeabcdeabcde") == -1
    assert candidate(s = "xyzxyzxyzxyz") == -1
    assert candidate(s = "xyzabcxyzabcxyzabcxyzabc") == -1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 50
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcba") == -1
    assert candidate(s = "mnopqrstmnopqrstmnopqrstmnopqrst") == -1
    assert candidate(s = "abcabcabcabcfdefgdefgdefg") == 13
    assert candidate(s = "aabbaabbaabbaabb") == -1
