# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(n = 8) == 6
    assert candidate(n = 3) == -1
    assert candidate(n = 4) == -1
    assert candidate(n = 1) == 1
    assert candidate(n = 1000) == -1
    assert candidate(n = 10) == -1
    assert candidate(n = 625) == -1
    assert candidate(n = 576) == -1
    assert candidate(n = 729) == -1
    assert candidate(n = 144) == -1
    assert candidate(n = 49) == 35
    assert candidate(n = 12) == -1
    assert candidate(n = 900) == -1
    assert candidate(n = 324) == -1
    assert candidate(n = 100) == -1
    assert candidate(n = 50) == -1
    assert candidate(n = 5) == -1
    assert candidate(n = 841) == -1
    assert candidate(n = 289) == -1
    assert candidate(n = 550) == -1
    assert candidate(n = 99) == -1
    assert candidate(n = 64) == -1
    assert candidate(n = 17) == -1
    assert candidate(n = 484) == -1
    assert candidate(n = 2) == -1
    assert candidate(n = 225) == -1
    assert candidate(n = 784) == -1
    assert candidate(n = 250) == -1
    assert candidate(n = 999) == -1
    assert candidate(n = 35) == -1
    assert candidate(n = 169) == -1
    assert candidate(n = 75) == -1
    assert candidate(n = 256) == -1
    assert candidate(n = 36) == -1
    assert candidate(n = 529) == -1
    assert candidate(n = 20) == -1
    assert candidate(n = 676) == -1
    assert candidate(n = 81) == -1
    assert candidate(n = 48) == -1
    assert candidate(n = 325) == -1
    assert candidate(n = 15) == -1
    assert candidate(n = 441) == -1
    assert candidate(n = 961) == -1
    assert candidate(n = 400) == -1
    assert candidate(n = 196) == -1
    assert candidate(n = 9) == -1
    assert candidate(n = 121) == -1
    assert candidate(n = 361) == -1
    assert candidate(n = 700) == -1
    assert candidate(n = 500) == -1
    assert candidate(n = 7) == -1
    assert candidate(n = 25) == -1
