# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "aabbbccccddeeeeeffffffgggggghhhhhhiiiiiiiijjjjjjjjjkkkkkkkkkkklllllllllllllmmmmmmmmmmmmmmmnnnnnnnnnnnnnnnnooooooooollllllllllllllllmmmmmmmmmmmmmmmmmnnnnnnnnnnnnnnnnnp") == 165
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 0
    assert candidate(s = "abcdef") == 0
    assert candidate(s = "aabbccddee") == -1
    assert candidate(s = "a") == 0
    assert candidate(s = "abacabadabacaba") == 7
    assert candidate(s = "abcdabcde") == 8
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == -1
    assert candidate(s = "swiss") == 1
    assert candidate(s = "abacabadabc") == 7
    assert candidate(s = "") == -1
    assert candidate(s = "repetition") == 0
    assert candidate(s = "zzz") == -1
    assert candidate(s = "aabbccddeeffg") == 12
    assert candidate(s = "leetcode") == 0
    assert candidate(s = "aabb") == -1
    assert candidate(s = "loveleetcode") == 2
    assert candidate(s = "abcdabcdf") == 8
    assert candidate(s = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyz") == -1
    assert candidate(s = "development") == 0
    assert candidate(s = "aabbcceeff") == -1
    assert candidate(s = "zzyyxxwwvvuuttrrqqppoonnmmllkkjjiihhggffeeddccbbaa") == -1
    assert candidate(s = "algorithm") == 0
    assert candidate(s = "unique") == 1
    assert candidate(s = "z") == 0
    assert candidate(s = "abbacd") == 4
    assert candidate(s = "aabbcceeffgghhiijjklmnopqrstuvwxyz") == 18
    assert candidate(s = "character") == 1
    assert candidate(s = "bba") == 2
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba") == 0
    assert candidate(s = "abcdefg") == 0
    assert candidate(s = "thisisjustafancysentence") == 1
    assert candidate(s = "almostunique") == 0
    assert candidate(s = "repetitionsofletters") == 2
    assert candidate(s = "abacabadabacabadabacabad") == -1
    assert candidate(s = "xyzzyzxyz") == -1
    assert candidate(s = "almosteverycharacterisunique") == 1
    assert candidate(s = "uniquecharactersarecool") == 1
    assert candidate(s = "abcdedcba") == 4
    assert candidate(s = "verylongstringwithmanyanonymouscharacterssssssssssssssssssssssss") == 0
    assert candidate(s = "uniqueidentifier") == 3
    assert candidate(s = "abracadabra") == 4
    assert candidate(s = "allcharactersrepeatmorethanonce") == 12
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad") == -1
    assert candidate(s = "xylophone") == 0
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == -1
    assert candidate(s = "unrepeatedcharacterstring") == 0
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzyxwvutsrqponmlkjihgfedcba") == -1
    assert candidate(s = "bbaaccddeeffgghhiijjkkllmmnnoopqrrssttuuvvwwxxyyzz") == 30
    assert candidate(s = "zzzzzyyyyxxxxwwvvvttrrssqqppoonnmmlkkjjiihhggffeedcba") == 34
    assert candidate(s = "thisisaverylongstringwithnomanynonrepeatingcharacters") == 7
    assert candidate(s = "xyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(s = "firstuniquicharacter") == 0
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyz") == 50
    assert candidate(s = "nocharactersrepeat") == 0
    assert candidate(s = "wovwovwov") == -1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == -1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == -1
    assert candidate(s = "abcdefghijabcdefghijabcdefghij") == -1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzz") == -1
    assert candidate(s = "aabbaaccddeeffaabbccddeeffaabbccddeeff") == -1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwooxxyyzz") == -1
    assert candidate(s = "banana") == 0
    assert candidate(s = "thisisaverylongstringwithseveralcharacters") == 10
    assert candidate(s = "aaaaabbbbbcccccdddddeeeeefffffggggghhhhiiiiijjjjkkkkklllllmmmmmnnnnnooooo") == -1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwxyzz") == 44
    assert candidate(s = "s") == 0
    assert candidate(s = "swissknife") == 1
    assert candidate(s = "abacaxabacayabacaza") == 5
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwxyz") == 44
    assert candidate(s = "thisproblemhasaveryunusalcharacterdistribution") == 4
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzz") == -1
    assert candidate(s = "aabbcdeef") == 4
    assert candidate(s = "aabbcdeeffgg") == 4
    assert candidate(s = "abcdefghijhgfedcba") == 8
    assert candidate(s = "single") == 0
    assert candidate(s = "uniquecharacter") == 1
    assert candidate(s = "mississippi") == 0
    assert candidate(s = "hashmapimplementation") == 2
    assert candidate(s = "abcdabcdbacd") == -1
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcbaabcdefghijklmnopqrstuvwxyz") == -1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == -1
    assert candidate(s = "supercalifragilisticexpialidocious") == 9
    assert candidate(s = "firstnonrepeatingcharacter") == 0
    assert candidate(s = "zzzzyyyyyxxxxxwwwwvvvvuuuuttttssssrrrrqqqqpppooooonnnnmmmmllllkkkkjjjjiiiihhhhggggffffeeeeddddccccbbbbaaaa") == -1
    assert candidate(s = "onlyonecharacterrepeats") == 2
    assert candidate(s = "ababababababababababababababababababab") == -1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwooxxyyzzzz") == -1
    assert candidate(s = "thequickbrownfoxjumpsoverthelazydog") == 3
    assert candidate(s = "bbaaccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzza") == -1
    assert candidate(s = "almostuniquecharacter") == 1
