# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(ring = "caotmcaataijjxi",key = "oatjiioijjjxxxcx") == 42
    assert candidate(ring = "godding",key = "gd") == 4
    assert candidate(ring = "pqwcx",key = "cpqwx") == 13
    assert candidate(ring = "edcba",key = "abc") == 6
    assert candidate(ring = "ababcabc",key = "abc") == 6
    assert candidate(ring = "iotfo",key = "fio") == 8
    assert candidate(ring = "abcdefghijklmnopqrstuvwxyz",key = "zyxwvutsrqponmlkjihgfedcba") == 52
    assert candidate(ring = "iaadddfef",key = "dd") == 5
    assert candidate(ring = "abcdefghijklmnopqrstuvwxyz",key = "cba") == 7
    assert candidate(ring = "abcdefg",key = "fa") == 6
    assert candidate(ring = "iaejfhfihjdghfihdddddddhddcfjghjgddf",key = "did") == 9
    assert candidate(ring = "xyxzyzyxy",key = "xzyxz") == 12
    assert candidate(ring = "godding",key = "godding") == 13
    assert candidate(ring = "caotmcaataijjxi",key = "oatjiioijia") == 35
    assert candidate(ring = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",key = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 66
    assert candidate(ring = "lkjhgfedcbazyxwvutsrqponml",key = "abcdefghijklmnopqrstuvwxyz") == inf
    assert candidate(ring = "mississippi",key = "ppiiisssmm") == 18
    assert candidate(ring = "uniquecharacters",key = "unique") == 11
    assert candidate(ring = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",key = "zyxwvutsrqponmlkjihgfedcba") == 77
    assert candidate(ring = "mississippi",key = "missis") == 10
    assert candidate(ring = "noonnoonnoonnoonnoonnoon",key = "noonnoon") == 12
    assert candidate(ring = "abacabadabacabadabacabadabacabad",key = "badabadabacaba") == 28
    assert candidate(ring = "thistimeitsshouldbeaveryunusualring",key = "unusualring") == 30
    assert candidate(ring = "thisisaverylongringwithmanysamecharacters",key = "thisisaverylongring") == 37
    assert candidate(ring = "encyclopedia",key = "pediaencyclopedia") == 38
    assert candidate(ring = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabc",key = "ac") == 3
    assert candidate(ring = "rotor",key = "rotorrotor") == 18
    assert candidate(ring = "abcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefg",key = "gfedcba") == 14
    assert candidate(ring = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",key = "zzzaa") == 7
    assert candidate(ring = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",key = "zyxwvutsrqponmlkjihgfedcba") == 52
    assert candidate(ring = "abababababababababab",key = "bababa") == 12
    assert candidate(ring = "abacabadabacaba",key = "abcabcabc") == 20
    assert candidate(ring = "rhythms",key = "rhythmrhythmsrhythmrhythms") == 53
    assert candidate(ring = "abcdefghijklmnopqrstuvwxyzaabcdefghijklmnopqrstuvwxyza",key = "abcdefghijklmnopqrstuvwxyz") == 51
    assert candidate(ring = "floccinaucinihilipilification",key = "floccinaucinihilipilification") == 57
    assert candidate(ring = "abcdefghijabcdefghijabcdefghij",key = "jjiihhggffeeddccba") == 28
    assert candidate(ring = "bcaacbcaacbcaac",key = "abcabc") == 15
    assert candidate(ring = "qwertyuiopasdfghjklzxcvbnm",key = "lkjhgfdsa") == 25
    assert candidate(ring = "abcabcabcabcabcabcabcabc",key = "abcabcabc") == 17
    assert candidate(ring = "ringwithrepeatedcharactersrrrr",key = "ringwithrepeatedcharacters") == 51
    assert candidate(ring = "repetition",key = "rep") == 5
    assert candidate(ring = "abcdefgabcdefgabcdefgabcdefgabcdefg",key = "abcdefgabcdefgabcdefgabcdefg") == 55
    assert candidate(ring = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",key = "zzzyyxxwvuttsrqponmlkjihgfedcba") == 82
    assert candidate(ring = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",key = "zzyyxxwvuttsrqponmlkjihgfedcba") == 81
    assert candidate(ring = "abracadabra",key = "abcabcabc") == 25
    assert candidate(ring = "qwertyuiopasdfghjklzxcvbnmqwertyuiop",key = "programming") == 87
    assert candidate(ring = "thisisaverylongstringthatweneedtocheckanditsrepeatedthisisaverylongstringthatweneedtocheck",key = "check") == 12
    assert candidate(ring = "thisisaverylongstringthatweneedtocheck",key = "string") == 26
    assert candidate(ring = "rhythm",key = "myrhth") == 16
    assert candidate(ring = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",key = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 52
    assert candidate(ring = "pqrsyzxcvbnmlkjhgfedwatpoiuy",key = "python") == 42
    assert candidate(ring = "mnbvcxzlkjhgfdsapoiuytrewq",key = "qwertyuiop") == 20
    assert candidate(ring = "mississippi",key = "mississippimississippi") == 41
    assert candidate(ring = "qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm",key = "mnbvcxzlkjhgfdsapoiuytrewq") == 52
    assert candidate(ring = "abcdefgabcdefgabcdefgabcdefg",key = "aceg") == 10
    assert candidate(ring = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",key = "zzz") == 3
    assert candidate(ring = "repeatedrepeatedrepeated",key = "repeat") == 11
    assert candidate(ring = "aaabbbcccdddeeefffggghhhiii",key = "abcdefghi") == 33
    assert candidate(ring = "aaaaabbbbbcccccdddddeeeeefffffggggghhhhhiiiii",key = "abcdefghi") == 49
    assert candidate(ring = "rotorrotorrotor",key = "rotor") == 9
    assert candidate(ring = "qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm",key = "qzam") == 31
    assert candidate(ring = "abcdefghijklmnopqrstuvwxyz",key = "abcdefghijklmnopqrstuvwxyz") == 51
    assert candidate(ring = "aaabbbbccccddddeeeeffffgggg",key = "abcdefg") == 30
    assert candidate(ring = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",key = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 60
    assert candidate(ring = "abcdefabcdefabcdefabcdefabcdefabcdefabcdef",key = "abcdefabcdefabcdefabcdefabcdefabcdefabcdef") == 83
    assert candidate(ring = "abacabadabacabadabacabad",key = "abad") == 7
    assert candidate(ring = "lmnopqrstuvwxyzabcdefghijkl",key = "key") == 17
    assert candidate(ring = "xylophone",key = "oxylphoen") == 24
    assert candidate(ring = "aaaaabbbbcccccdddddeeeeeffffffggggghhhhhhiiiiijjjjjjkkkkkkllllllmmmmmmnnnnnnooooooppppppqqqqqqrrrrrrssssssttttttuuuuuuvvvvvvwwwwwwwxxxxxxxxxyyyyyyyzzzzzzz",key = "zyxwvutsrqponmlkjihgfedcba") == 176
    assert candidate(ring = "mississippi",key = "issi") == 7
