# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(sentence = "Convert this sentence") == "onvertCmaa histmaaa entencesmaaaa"
    assert candidate(sentence = "In the end") == "Inmaa hetmaaa endmaaaa"
    assert candidate(sentence = "a e i o u") == "amaa emaaa imaaaa omaaaaa umaaaaaa"
    assert candidate(sentence = "Hello world") == "elloHmaa orldwmaaa"
    assert candidate(sentence = "Python is great") == "ythonPmaa ismaaa reatgmaaaa"
    assert candidate(sentence = "This is a test") == "hisTmaa ismaaa amaaaa esttmaaaaa"
    assert candidate(sentence = "Hello World") == "elloHmaa orldWmaaa"
    assert candidate(sentence = "Goat Latin Example") == "oatGmaa atinLmaaa Examplemaaaa"
    assert candidate(sentence = "Convert this sentence to Goat Latin") == "onvertCmaa histmaaa entencesmaaaa otmaaaaa oatGmaaaaaa atinLmaaaaaaa"
    assert candidate(sentence = "The quick brown fox jumped over the lazy dog") == "heTmaa uickqmaaa rownbmaaaa oxfmaaaaa umpedjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa"
    assert candidate(sentence = "Programming is fun") == "rogrammingPmaa ismaaa unfmaaaa"
    assert candidate(sentence = "Every vowel example") == "Everymaa owelvmaaa examplemaaaa"
    assert candidate(sentence = "hello world") == "ellohmaa orldwmaaa"
    assert candidate(sentence = "Goat Latin is easy") == "oatGmaa atinLmaaa ismaaaa easymaaaaa"
    assert candidate(sentence = "Keep practicing") == "eepKmaa racticingpmaaa"
    assert candidate(sentence = "Conversion to Goat Latin") == "onversionCmaa otmaaa oatGmaaaa atinLmaaaaa"
    assert candidate(sentence = "I speak Goat Latin") == "Imaa peaksmaaa oatGmaaaa atinLmaaaaa"
    assert candidate(sentence = "Every word matters") == "Everymaa ordwmaaa attersmmaaaa"
    assert candidate(sentence = "ChatGPT is an AI language model") == "hatGPTCmaa ismaaa anmaaaa AImaaaaa anguagelmaaaaaa odelmmaaaaaaa"
    assert candidate(sentence = "A big brown dog jumps over a lazy fox") == "Amaa igbmaaa rownbmaaaa ogdmaaaaa umpsjmaaaaaa overmaaaaaaa amaaaaaaaa azylmaaaaaaaaa oxfmaaaaaaaaaa"
    assert candidate(sentence = "Quick brown fox jumps over the lazy dog") == "uickQmaa rownbmaaa oxfmaaaa umpsjmaaaaa overmaaaaaa hetmaaaaaaa azylmaaaaaaaa ogdmaaaaaaaaa"
    assert candidate(sentence = "Frogs jump joyfully in the rain") == "rogsFmaa umpjmaaa oyfullyjmaaaa inmaaaaa hetmaaaaaa ainrmaaaaaaa"
    assert candidate(sentence = "Conversion to Goat Latin should handle complex sentences properly") == "onversionCmaa otmaaa oatGmaaaa atinLmaaaaa houldsmaaaaaa andlehmaaaaaaa omplexcmaaaaaaaa entencessmaaaaaaaaa roperlypmaaaaaaaaaa"
    assert candidate(sentence = "The quick brown fox jumps over the lazy dog and runs") == "heTmaa uickqmaaa rownbmaaaa oxfmaaaaa umpsjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa andmaaaaaaaaaaa unsrmaaaaaaaaaaaa"
    assert candidate(sentence = "User experience design and usability") == "Usermaa experiencemaaa esigndmaaaa andmaaaaa usabilitymaaaaaa"
    assert candidate(sentence = "This is an interesting problem to solve") == "hisTmaa ismaaa anmaaaa interestingmaaaaa roblempmaaaaaa otmaaaaaaa olvesmaaaaaaaa"
    assert candidate(sentence = "A quick brown fox jumps over the lazy dog") == "Amaa uickqmaaa rownbmaaaa oxfmaaaaa umpsjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa"
    assert candidate(sentence = "This is a simple test case for Goat Latin") == "hisTmaa ismaaa amaaaa implesmaaaaa esttmaaaaaa asecmaaaaaaa orfmaaaaaaaa oatGmaaaaaaaaa atinLmaaaaaaaaaa"
    assert candidate(sentence = "Another Example to demonstrate the Conversion") == "Anothermaa Examplemaaa otmaaaa emonstratedmaaaaa hetmaaaaaa onversionCmaaaaaaa"
    assert candidate(sentence = "Let us create more examples for testing") == "etLmaa usmaaa reatecmaaaa oremmaaaaa examplesmaaaaaa orfmaaaaaaa estingtmaaaaaaaa"
    assert candidate(sentence = "a e i o u A E I O U") == "amaa emaaa imaaaa omaaaaa umaaaaaa Amaaaaaaa Emaaaaaaaa Imaaaaaaaaa Omaaaaaaaaaa Umaaaaaaaaaaa"
    assert candidate(sentence = "Lorem ipsum dolor sit amet consectetur adipiscing elit") == "oremLmaa ipsummaaa olordmaaaa itsmaaaaa ametmaaaaaa onsecteturcmaaaaaaa adipiscingmaaaaaaaa elitmaaaaaaaaa"
    assert candidate(sentence = "Every vowel and consonant has its own rule") == "Everymaa owelvmaaa andmaaaa onsonantcmaaaaa ashmaaaaaa itsmaaaaaaa ownmaaaaaaaa ulermaaaaaaaaa"
    assert candidate(sentence = "The quick brown fox jumps over the lazy dog and plays") == "heTmaa uickqmaaa rownbmaaaa oxfmaaaaa umpsjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa andmaaaaaaaaaaa layspmaaaaaaaaaaaa"
    assert candidate(sentence = "Sphinx of black quartz judge my vow") == "phinxSmaa ofmaaa lackbmaaaa uartzqmaaaaa udgejmaaaaaa ymmaaaaaaa owvmaaaaaaaa"
    assert candidate(sentence = "Artificial intelligence is transforming the world") == "Artificialmaa intelligencemaaa ismaaaa ransformingtmaaaaa hetmaaaaaa orldwmaaaaaaa"
    assert candidate(sentence = "Gnomes gather golden grains gracefully gathering groups") == "nomesGmaa athergmaaa oldengmaaaa rainsgmaaaaa racefullygmaaaaaa atheringgmaaaaaaa roupsgmaaaaaaaa"
    assert candidate(sentence = "Natural language processing is revolutionizing technology") == "aturalNmaa anguagelmaaa rocessingpmaaaa ismaaaaa evolutionizingrmaaaaaa echnologytmaaaaaaa"
    assert candidate(sentence = "Python programming is fun") == "ythonPmaa rogrammingpmaaa ismaaaa unfmaaaaa"
    assert candidate(sentence = "The weather today is absolutely perfect") == "heTmaa eatherwmaaa odaytmaaaa ismaaaaa absolutelymaaaaaa erfectpmaaaaaaa"
    assert candidate(sentence = "Let us see how this conversion works") == "etLmaa usmaaa eesmaaaa owhmaaaaa histmaaaaaa onversioncmaaaaaaa orkswmaaaaaaaa"
    assert candidate(sentence = "Internet of Things and smart devices") == "Internetmaa ofmaaa hingsTmaaaa andmaaaaa martsmaaaaaa evicesdmaaaaaaa"
    assert candidate(sentence = "OpenAI develops advanced AI systems") == "OpenAImaa evelopsdmaaa advancedmaaaa AImaaaaa ystemssmaaaaaa"
    assert candidate(sentence = "Edge cases exercise existing expertise effectively") == "Edgemaa asescmaaa exercisemaaaa existingmaaaaa expertisemaaaaaa effectivelymaaaaaaa"
    assert candidate(sentence = "Zoologists zealously zoom into zoological zoological zones") == "oologistsZmaa ealouslyzmaaa oomzmaaaa intomaaaaa oologicalzmaaaaaa oologicalzmaaaaaaa oneszmaaaaaaaa"
    assert candidate(sentence = "Beautiful scenery and wonderful views") == "eautifulBmaa cenerysmaaa andmaaaa onderfulwmaaaaa iewsvmaaaaaa"
    assert candidate(sentence = "Mixed CASE Words Should Still Work") == "ixedMmaa ASECmaaa ordsWmaaaa houldSmaaaaa tillSmaaaaaa orkWmaaaaaaa"
    assert candidate(sentence = "Every vowel and consonant has a unique rule") == "Everymaa owelvmaaa andmaaaa onsonantcmaaaaa ashmaaaaaa amaaaaaaa uniquemaaaaaaaa ulermaaaaaaaaa"
    assert candidate(sentence = "Artificial intelligence will change our lives") == "Artificialmaa intelligencemaaa illwmaaaa hangecmaaaaa ourmaaaaaa iveslmaaaaaaa"
    assert candidate(sentence = "Testing edge cases like empty spaces in between words") == "estingTmaa edgemaaa asescmaaaa ikelmaaaaa emptymaaaaaa pacessmaaaaaaa inmaaaaaaaa etweenbmaaaaaaaaa ordswmaaaaaaaaaa"
    assert candidate(sentence = "Programming in Python is fun and challenging") == "rogrammingPmaa inmaaa ythonPmaaaa ismaaaaa unfmaaaaaa andmaaaaaaa hallengingcmaaaaaaaa"
    assert candidate(sentence = "This is a longer sentence that includes several words to ensure the solution works correctly") == "hisTmaa ismaaa amaaaa ongerlmaaaaa entencesmaaaaaa hattmaaaaaaa includesmaaaaaaaa everalsmaaaaaaaaa ordswmaaaaaaaaaa otmaaaaaaaaaaa ensuremaaaaaaaaaaaa hetmaaaaaaaaaaaaa olutionsmaaaaaaaaaaaaaa orkswmaaaaaaaaaaaaaaa orrectlycmaaaaaaaaaaaaaaaa"
    assert candidate(sentence = "This is a simple test") == "hisTmaa ismaaa amaaaa implesmaaaaa esttmaaaaaa"
    assert candidate(sentence = "Conversion to Goat Latin can be tricky") == "onversionCmaa otmaaa oatGmaaaa atinLmaaaaa ancmaaaaaa ebmaaaaaaa rickytmaaaaaaaa"
    assert candidate(sentence = "Complex sentences with various words") == "omplexCmaa entencessmaaa ithwmaaaa ariousvmaaaaa ordswmaaaaaa"
    assert candidate(sentence = "Understanding algorithms and data structures") == "Understandingmaa algorithmsmaaa andmaaaa atadmaaaaa tructuressmaaaaaa"
    assert candidate(sentence = "Goat Latin is a fun and creative language") == "oatGmaa atinLmaaa ismaaaa amaaaaa unfmaaaaaa andmaaaaaaa reativecmaaaaaaaa anguagelmaaaaaaaaa"
    assert candidate(sentence = "Consonants should move their first letter to the end") == "onsonantsCmaa houldsmaaa ovemmaaaa heirtmaaaaa irstfmaaaaaa etterlmaaaaaaa otmaaaaaaaa hetmaaaaaaaaa endmaaaaaaaaaa"
    assert candidate(sentence = "Fascinating flora frequently feed furry friends") == "ascinatingFmaa lorafmaaa requentlyfmaaaa eedfmaaaaa urryfmaaaaaa riendsfmaaaaaaa"
    assert candidate(sentence = "Keep pushing your limits and you will achieve great things") == "eepKmaa ushingpmaaa ourymaaaa imitslmaaaaa andmaaaaaa ouymaaaaaaa illwmaaaaaaaa achievemaaaaaaaaa reatgmaaaaaaaaaa hingstmaaaaaaaaaaa"
    assert candidate(sentence = "Software engineering principles") == "oftwareSmaa engineeringmaaa rinciplespmaaaa"
    assert candidate(sentence = "Every vowel must be handled") == "Everymaa owelvmaaa ustmmaaaa ebmaaaaa andledhmaaaaaa"
    assert candidate(sentence = "Testing multiple words with varied starting letters") == "estingTmaa ultiplemmaaa ordswmaaaa ithwmaaaaa ariedvmaaaaaa tartingsmaaaaaaa etterslmaaaaaaaa"
    assert candidate(sentence = "Beautiful butterflies brightly bask in blazing sunshine") == "eautifulBmaa utterfliesbmaaa rightlybmaaaa askbmaaaaa inmaaaaaa lazingbmaaaaaaa unshinesmaaaaaaaa"
    assert candidate(sentence = "The quick brown fox jumps over the lazy dog on a sunny day") == "heTmaa uickqmaaa rownbmaaaa oxfmaaaaa umpsjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa onmaaaaaaaaaaa amaaaaaaaaaaaa unnysmaaaaaaaaaaaaa aydmaaaaaaaaaaaaaa"
    assert candidate(sentence = "Machine learning is transforming the world") == "achineMmaa earninglmaaa ismaaaa ransformingtmaaaaa hetmaaaaaa orldwmaaaaaaa"
    assert candidate(sentence = "b c d f g h j k l m n p q r s t v w x y z B C D F G H J K L M N P Q R S T V W X Y Z") == "bmaa cmaaa dmaaaa fmaaaaa gmaaaaaa hmaaaaaaa jmaaaaaaaa kmaaaaaaaaa lmaaaaaaaaaa mmaaaaaaaaaaa nmaaaaaaaaaaaa pmaaaaaaaaaaaaa qmaaaaaaaaaaaaaa rmaaaaaaaaaaaaaaa smaaaaaaaaaaaaaaaa tmaaaaaaaaaaaaaaaaa vmaaaaaaaaaaaaaaaaaa wmaaaaaaaaaaaaaaaaaaa xmaaaaaaaaaaaaaaaaaaaa ymaaaaaaaaaaaaaaaaaaaaa zmaaaaaaaaaaaaaaaaaaaaaa Bmaaaaaaaaaaaaaaaaaaaaaaa Cmaaaaaaaaaaaaaaaaaaaaaaaa Dmaaaaaaaaaaaaaaaaaaaaaaaaa Fmaaaaaaaaaaaaaaaaaaaaaaaaaa Gmaaaaaaaaaaaaaaaaaaaaaaaaaaa Hmaaaaaaaaaaaaaaaaaaaaaaaaaaaa Jmaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Kmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Lmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Mmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Nmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Pmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Qmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Rmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Smaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Tmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Vmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Wmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Xmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Ymaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Zmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    assert candidate(sentence = "Bright vixens jump over the lazy dog") == "rightBmaa ixensvmaaa umpjmaaaa overmaaaaa hetmaaaaaa azylmaaaaaaa ogdmaaaaaaaa"
    assert candidate(sentence = "Hello world this is a test sentence") == "elloHmaa orldwmaaa histmaaaa ismaaaaa amaaaaaa esttmaaaaaaa entencesmaaaaaaaa"
    assert candidate(sentence = "Natural language processing and chatbots") == "aturalNmaa anguagelmaaa rocessingpmaaaa andmaaaaa hatbotscmaaaaaa"
    assert candidate(sentence = "Lazy dogs jump over sleeping cats") == "azyLmaa ogsdmaaa umpjmaaaa overmaaaaa leepingsmaaaaaa atscmaaaaaaa"
    assert candidate(sentence = "Computer vision and image processing") == "omputerCmaa isionvmaaa andmaaaa imagemaaaaa rocessingpmaaaaaa"
    assert candidate(sentence = "Every vowel should remain unchanged ma") == "Everymaa owelvmaaa houldsmaaaa emainrmaaaaa unchangedmaaaaaa ammaaaaaaa"
    assert candidate(sentence = "The five boxing wizards jump quickly") == "heTmaa ivefmaaa oxingbmaaaa izardswmaaaaa umpjmaaaaaa uicklyqmaaaaaaa"
    assert candidate(sentence = "Blockchain technology and cryptography") == "lockchainBmaa echnologytmaaa andmaaaa ryptographycmaaaaa"
    assert candidate(sentence = "Debugging code can be challenging") == "ebuggingDmaa odecmaaa ancmaaaa ebmaaaaa hallengingcmaaaaaa"
    assert candidate(sentence = "Python Programming Language is Fun") == "ythonPmaa rogrammingPmaaa anguageLmaaaa ismaaaaa unFmaaaaaa"
    assert candidate(sentence = "Algorithm design and analysis") == "Algorithmmaa esigndmaaa andmaaaa analysismaaaaa"
    assert candidate(sentence = "Alphabet University of Economics and Business Administration") == "Alphabetmaa Universitymaaa ofmaaaa Economicsmaaaaa andmaaaaaa usinessBmaaaaaaa Administrationmaaaaaaaa"
    assert candidate(sentence = "Continuous integration and deployment") == "ontinuousCmaa integrationmaaa andmaaaa eploymentdmaaaaa"
    assert candidate(sentence = "Beautiful scenery in nature") == "eautifulBmaa cenerysmaaa inmaaaa aturenmaaaaa"
    assert candidate(sentence = "Machine learning models are fascinating") == "achineMmaa earninglmaaa odelsmmaaaa aremaaaaa ascinatingfmaaaaaa"
    assert candidate(sentence = "Jackdaws love my big sphinx of quartz") == "ackdawsJmaa ovelmaaa ymmaaaa igbmaaaaa phinxsmaaaaaa ofmaaaaaaa uartzqmaaaaaaaa"
    assert candidate(sentence = "The brown fox jumps over a lazy dog") == "heTmaa rownbmaaa oxfmaaaa umpsjmaaaaa overmaaaaaa amaaaaaaa azylmaaaaaaaa ogdmaaaaaaaaa"
    assert candidate(sentence = "Python programming promotes productivity and problem solving") == "ythonPmaa rogrammingpmaaa romotespmaaaa roductivitypmaaaaa andmaaaaaa roblempmaaaaaaa olvingsmaaaaaaaa"
    assert candidate(sentence = "High performance computing and big data") == "ighHmaa erformancepmaaa omputingcmaaaa andmaaaaa igbmaaaaaa atadmaaaaaaa"
    assert candidate(sentence = "The quick brown fox jumps over the lazy dog quickly") == "heTmaa uickqmaaa rownbmaaaa oxfmaaaaa umpsjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa uicklyqmaaaaaaaaaaa"
    assert candidate(sentence = "The quick brown fox jumps over the lazy dog") == "heTmaa uickqmaaa rownbmaaaa oxfmaaaaa umpsjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa"
    assert candidate(sentence = "Data analysis and machine learning") == "ataDmaa analysismaaa andmaaaa achinemmaaaaa earninglmaaaaaa"
    assert candidate(sentence = "ComplexSentencesWithNoSpaces") == "omplexSentencesWithNoSpacesCmaa"
    assert candidate(sentence = "Understanding complex algorithms unravelles endless possibilities") == "Understandingmaa omplexcmaaa algorithmsmaaaa unravellesmaaaaa endlessmaaaaaa ossibilitiespmaaaaaaa"
    assert candidate(sentence = "Watch Jeopardy on NBC") == "atchWmaa eopardyJmaaa onmaaaa BCNmaaaaa"
    assert candidate(sentence = "Artificial neural networks and deep learning") == "Artificialmaa euralnmaaa etworksnmaaaa andmaaaaa eepdmaaaaaa earninglmaaaaaaa"
    assert candidate(sentence = "Data structures and algorithms") == "ataDmaa tructuressmaaa andmaaaa algorithmsmaaaaa"
    assert candidate(sentence = "Algorithms are crucial for computer science") == "Algorithmsmaa aremaaa rucialcmaaaa orfmaaaaa omputercmaaaaaa ciencesmaaaaaaa"
    assert candidate(sentence = "Consonants should also be tested") == "onsonantsCmaa houldsmaaa alsomaaaa ebmaaaaa estedtmaaaaaa"
    assert candidate(sentence = "She sells sea shells by the sea shore") == "heSmaa ellssmaaa easmaaaa hellssmaaaaa ybmaaaaaa hetmaaaaaaa easmaaaaaaaa horesmaaaaaaaaa"
    assert candidate(sentence = "abcdefghijklmnopqrstuvwxyz") == "abcdefghijklmnopqrstuvwxyzmaa"
    assert candidate(sentence = "A big black bear sat on a big black rug") == "Amaa igbmaaa lackbmaaaa earbmaaaaa atsmaaaaaa onmaaaaaaa amaaaaaaaa igbmaaaaaaaaa lackbmaaaaaaaaaa ugrmaaaaaaaaaaa"
    assert candidate(sentence = "Multiple words starting with a consonant") == "ultipleMmaa ordswmaaa tartingsmaaaa ithwmaaaaa amaaaaaa onsonantcmaaaaaaa"
    assert candidate(sentence = "How vexingly quick daft zebras jump") == "owHmaa exinglyvmaaa uickqmaaaa aftdmaaaaa ebraszmaaaaaa umpjmaaaaaaa"
    assert candidate(sentence = "SingleWord") == "ingleWordSmaa"
    assert candidate(sentence = "An example of a more complex sentence conversion") == "Anmaa examplemaaa ofmaaaa amaaaaa oremmaaaaaa omplexcmaaaaaaa entencesmaaaaaaaa onversioncmaaaaaaaaa"
    assert candidate(sentence = "Transformations are always fascinating") == "ransformationsTmaa aremaaa alwaysmaaaa ascinatingfmaaaaa"
    assert candidate(sentence = "Single") == "ingleSmaa"
    assert candidate(sentence = "bc df gh jk lm np qr st vx zy") == "cbmaa fdmaaa hgmaaaa kjmaaaaa mlmaaaaaa pnmaaaaaaa rqmaaaaaaaa tsmaaaaaaaaa xvmaaaaaaaaaa yzmaaaaaaaaaaa"
    assert candidate(sentence = "Algorithms and data structures") == "Algorithmsmaa andmaaa atadmaaaa tructuressmaaaaa"
    assert candidate(sentence = "Sometimes it rains cats and dogs") == "ometimesSmaa itmaaa ainsrmaaaa atscmaaaaa andmaaaaaa ogsdmaaaaaaa"
    assert candidate(sentence = "Understanding the rules of Goat Latin") == "Understandingmaa hetmaaa ulesrmaaaa ofmaaaaa oatGmaaaaaa atinLmaaaaaaa"
    assert candidate(sentence = "This is an elaborate test case with multiple words") == "hisTmaa ismaaa anmaaaa elaboratemaaaaa esttmaaaaaa asecmaaaaaaa ithwmaaaaaaaa ultiplemmaaaaaaaaa ordswmaaaaaaaaaa"
    assert candidate(sentence = "The early morning dew dries") == "heTmaa earlymaaa orningmmaaaa ewdmaaaaa riesdmaaaaaa"
    assert candidate(sentence = "Short long longer longest longestest") == "hortSmaa onglmaaa ongerlmaaaa ongestlmaaaaa ongestestlmaaaaaa"
    assert candidate(sentence = "Quantum computing and future technologies") == "uantumQmaa omputingcmaaa andmaaaa uturefmaaaaa echnologiestmaaaaaa"
    assert candidate(sentence = "The five boxing wizards jump quickly on this extraordinary bicycle") == "heTmaa ivefmaaa oxingbmaaaa izardswmaaaaa umpjmaaaaaa uicklyqmaaaaaaa onmaaaaaaaa histmaaaaaaaaa extraordinarymaaaaaaaaaa icyclebmaaaaaaaaaaa"
    assert candidate(sentence = "Python programming is fun and educational") == "ythonPmaa rogrammingpmaaa ismaaaa unfmaaaaa andmaaaaaa educationalmaaaaaaa"
    assert candidate(sentence = "Multiple words starting with a vowel") == "ultipleMmaa ordswmaaa tartingsmaaaa ithwmaaaaa amaaaaaa owelvmaaaaaaa"
    assert candidate(sentence = "Fuzzy wuzzy was a bear") == "uzzyFmaa uzzywmaaa aswmaaaa amaaaaa earbmaaaaaa"
    assert candidate(sentence = "Cloud computing and artificial intelligence") == "loudCmaa omputingcmaaa andmaaaa artificialmaaaaa intelligencemaaaaaa"
    assert candidate(sentence = "AEIOU aeiou UUIIOOAAEE") == "AEIOUmaa aeioumaaa UUIIOOAAEEmaaaa"
    assert candidate(sentence = "Multiple words with different starting letters") == "ultipleMmaa ordswmaaa ithwmaaaa ifferentdmaaaaa tartingsmaaaaaa etterslmaaaaaaa"
    assert candidate(sentence = "The quick brown fox jumps over the lazy dog several times") == "heTmaa uickqmaaa rownbmaaaa oxfmaaaaa umpsjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa everalsmaaaaaaaaaaa imestmaaaaaaaaaaaa"
    assert candidate(sentence = "Xylophones yield xylophonic xenon xylophonically") == "ylophonesXmaa ieldymaaa ylophonicxmaaaa enonxmaaaaa ylophonicallyxmaaaaaa"
    assert candidate(sentence = "Open source software development") == "Openmaa ourcesmaaa oftwaresmaaaa evelopmentdmaaaaa"
    assert candidate(sentence = "A rapid brown fox jumps over the lazy dog") == "Amaa apidrmaaa rownbmaaaa oxfmaaaaa umpsjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa"
    assert candidate(sentence = "Quickly zigzagging through the dense forest") == "uicklyQmaa igzaggingzmaaa hroughtmaaaa hetmaaaaa ensedmaaaaaa orestfmaaaaaaa"
    assert candidate(sentence = "Programming in Python is fun") == "rogrammingPmaa inmaaa ythonPmaaaa ismaaaaa unfmaaaaaa"
    assert candidate(sentence = "An elephant and an antelope") == "Anmaa elephantmaaa andmaaaa anmaaaaa antelopemaaaaaa"
    assert candidate(sentence = "This is an exceptionally long sentence to test the robustness of the solution") == "hisTmaa ismaaa anmaaaa exceptionallymaaaaa onglmaaaaaa entencesmaaaaaaa otmaaaaaaaa esttmaaaaaaaaa hetmaaaaaaaaaa obustnessrmaaaaaaaaaaa ofmaaaaaaaaaaaa hetmaaaaaaaaaaaaa olutionsmaaaaaaaaaaaaaa"
    assert candidate(sentence = "An exquisite oriental fan") == "Anmaa exquisitemaaa orientalmaaaa anfmaaaaa"
    assert candidate(sentence = "ABCDEFGHIJKLMNOPQRSTUVWXYZ") == "ABCDEFGHIJKLMNOPQRSTUVWXYZmaa"
    assert candidate(sentence = "Virtual reality and augmented reality") == "irtualVmaa ealityrmaaa andmaaaa augmentedmaaaaa ealityrmaaaaaa"
    assert candidate(sentence = "Every vowel should be handled properly") == "Everymaa owelvmaaa houldsmaaaa ebmaaaaa andledhmaaaaaa roperlypmaaaaaaa"
    assert candidate(sentence = "A quick movement of the enemy will jeopardize five gunboats") == "Amaa uickqmaaa ovementmmaaaa ofmaaaaa hetmaaaaaa enemymaaaaaaa illwmaaaaaaaa eopardizejmaaaaaaaaa ivefmaaaaaaaaaa unboatsgmaaaaaaaaaaa"
    assert candidate(sentence = "Beautiful butterflies brightly bask in blazing sun") == "eautifulBmaa utterfliesbmaaa rightlybmaaaa askbmaaaaa inmaaaaaa lazingbmaaaaaaa unsmaaaaaaaa"
    assert candidate(sentence = "This is a test of the Goat Latin conversion tool") == "hisTmaa ismaaa amaaaa esttmaaaaa ofmaaaaaa hetmaaaaaaa oatGmaaaaaaaa atinLmaaaaaaaaa onversioncmaaaaaaaaaa ooltmaaaaaaaaaaa"
