# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(num = 9) == "Nine"
    assert candidate(num = 10) == "Ten"
    assert candidate(num = 100000000) == "One Hundred Million"
    assert candidate(num = 1234567) == "One Million Two Hundred Thirty Four Thousand Five Hundred Sixty Seven"
    assert candidate(num = 999) == "Nine Hundred Ninety Nine"
    assert candidate(num = 10000000) == "Ten Million"
    assert candidate(num = 29) == "Twenty Nine"
    assert candidate(num = 31) == "Thirty One"
    assert candidate(num = 30) == "Thirty"
    assert candidate(num = 1000000000) == "One Billion"
    assert candidate(num = 110) == "One Hundred Ten"
    assert candidate(num = 5) == "Five"
    assert candidate(num = 11) == "Eleven"
    assert candidate(num = 1000) == "One Thousand"
    assert candidate(num = 123) == "One Hundred Twenty Three"
    assert candidate(num = 12345) == "Twelve Thousand Three Hundred Forty Five"
    assert candidate(num = 1001) == "One Thousand One"
    assert candidate(num = 21) == "Twenty One"
    assert candidate(num = 0) == "Zero"
    assert candidate(num = 39) == "Thirty Nine"
    assert candidate(num = 100) == "One Hundred"
    assert candidate(num = 111) == "One Hundred Eleven"
    assert candidate(num = 2147483647) == "Two Billion One Hundred Forty Seven Million Four Hundred Eighty Three Thousand Six Hundred Forty Seven"
    assert candidate(num = 100000) == "One Hundred Thousand"
    assert candidate(num = 999999999) == "Nine Hundred Ninety Nine Million Nine Hundred Ninety Nine Thousand Nine Hundred Ninety Nine"
    assert candidate(num = 1000000) == "One Million"
    assert candidate(num = 999999) == "Nine Hundred Ninety Nine Thousand Nine Hundred Ninety Nine"
    assert candidate(num = 19) == "Nineteen"
    assert candidate(num = 10000) == "Ten Thousand"
    assert candidate(num = 101) == "One Hundred One"
    assert candidate(num = 500000050) == "Five Hundred Million Fifty"
    assert candidate(num = 111111111) == "One Hundred Eleven Million One Hundred Eleven Thousand One Hundred Eleven"
    assert candidate(num = 555555555) == "Five Hundred Fifty Five Million Five Hundred Fifty Five Thousand Five Hundred Fifty Five"
    assert candidate(num = 1111111111) == "One Billion One Hundred Eleven Million One Hundred Eleven Thousand One Hundred Eleven"
    assert candidate(num = 10000000000) == "Ten Billion"
    assert candidate(num = 890123456) == "Eight Hundred Ninety Million One Hundred Twenty Three Thousand Four Hundred Fifty Six"
    assert candidate(num = 508) == "Five Hundred Eight"
    assert candidate(num = 999999999999) == "Nine Hundred Ninety Nine Billion Nine Hundred Ninety Nine Million Nine Hundred Ninety Nine Thousand Nine Hundred Ninety Nine"
    assert candidate(num = 1010101010) == "One Billion Ten Million One Hundred One Thousand Ten"
    assert candidate(num = 50000050) == "Fifty Million Fifty"
    assert candidate(num = 99) == "Ninety Nine"
    assert candidate(num = 1000010001) == "One Billion Ten Thousand One"
    assert candidate(num = 807000000) == "Eight Hundred Seven Million"
    assert candidate(num = 900000009) == "Nine Hundred Million Nine"
    assert candidate(num = 123456789) == "One Hundred Twenty Three Million Four Hundred Fifty Six Thousand Seven Hundred Eighty Nine"
    assert candidate(num = 11000011) == "Eleven Million Eleven"
    assert candidate(num = 900000090) == "Nine Hundred Million Ninety"
    assert candidate(num = 1010001000) == "One Billion Ten Million One Thousand"
    assert candidate(num = 1000000001) == "One Billion One"
    assert candidate(num = 1001001001) == "One Billion One Million One Thousand One"
    assert candidate(num = 999000999) == "Nine Hundred Ninety Nine Million Nine Hundred Ninety Nine"
    assert candidate(num = 1234567890) == "One Billion Two Hundred Thirty Four Million Five Hundred Sixty Seven Thousand Eight Hundred Ninety"
    assert candidate(num = 2000000000) == "Two Billion"
    assert candidate(num = 9876) == "Nine Thousand Eight Hundred Seventy Six"
    assert candidate(num = 1000010) == "One Million Ten"
    assert candidate(num = 1000000000001) == "Ten Hundred Billion One"
    assert candidate(num = 987654321) == "Nine Hundred Eighty Seven Million Six Hundred Fifty Four Thousand Three Hundred Twenty One"
    assert candidate(num = 990000000) == "Nine Hundred Ninety Million"
    assert candidate(num = 123000456) == "One Hundred Twenty Three Million Four Hundred Fifty Six"
    assert candidate(num = 203040506) == "Two Hundred Three Million Forty Thousand Five Hundred Six"
    assert candidate(num = 101010101) == "One Hundred One Million Ten Thousand One Hundred One"
    assert candidate(num = 500000500) == "Five Hundred Million Five Hundred"
    assert candidate(num = 2100000100) == "Two Billion One Hundred Million One Hundred"
    assert candidate(num = 450000000) == "Four Hundred Fifty Million"
    assert candidate(num = 4321098765) == "Four Billion Three Hundred Twenty One Million Ninety Eight Thousand Seven Hundred Sixty Five"
    assert candidate(num = 123000000) == "One Hundred Twenty Three Million"
    assert candidate(num = 4321) == "Four Thousand Three Hundred Twenty One"
    assert candidate(num = 900009000) == "Nine Hundred Million Nine Thousand"
    assert candidate(num = 1100000000) == "One Billion One Hundred Million"
    assert candidate(num = 123400000) == "One Hundred Twenty Three Million Four Hundred Thousand"
    assert candidate(num = 1000001) == "One Million One"
    assert candidate(num = 9999) == "Nine Thousand Nine Hundred Ninety Nine"
    assert candidate(num = 900900000) == "Nine Hundred Million Nine Hundred Thousand"
    assert candidate(num = 60012003) == "Sixty Million Twelve Thousand Three"
