# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abc",t = "abdc") == True
    assert candidate(s = "ab",t = ('baab',)) == False
    assert candidate(s = "xyz",t = "abcdefghijklmnopqrstuvwxyz") == True
    assert candidate(s = "aec",t = "abcde") == False
    assert candidate(s = "",t = "ahbgdc") == True
    assert candidate(s = "",t = "") == True
    assert candidate(s = "zyx",t = "abcdefghijklmnopqrstuvwxyz") == False
    assert candidate(s = "abcd",t = "abcde") == True
    assert candidate(s = "abc",t = "abcbc") == True
    assert candidate(s = "bb",t = "aabbb") == True
    assert candidate(s = "aaaaaa",t = "bbaaaa") == False
    assert candidate(s = "abc",t = "bahbgdca") == True
    assert candidate(s = "ab",t = "baab") == True
    assert candidate(s = "bd",t = "abcde") == True
    assert candidate(s = "bd",t = "abcd") == True
    assert candidate(s = "axc",t = "ahbgdc") == False
    assert candidate(s = "a",t = "ahbgdc") == True
    assert candidate(s = "a",t = "a") == True
    assert candidate(s = "abc",t = "ahbgdc") == True
    assert candidate(s = "acb",t = "ahbgdc") == False
    assert candidate(s = "bcd",t = "ahbgdc") == False
    assert candidate(s = "abc",t = "") == False
    assert candidate(s = "ahbgdc",t = "ahbgdc") == True
    assert candidate(s = "abcd",t = "abbbcd") == True
    assert candidate(s = "b",t = "abcde") == True
    assert candidate(s = "abc",t = "abc") == True
    assert candidate(s = "abc",t = "abcde") == True
    assert candidate(s = "test",t = "ttttteeeesstttt") == True
    assert candidate(s = "challenge",t = "chllenge") == False
    assert candidate(s = "leetcode",t = "lleettccooddee") == True
    assert candidate(s = "consecutive",t = "consecutivve") == True
    assert candidate(s = "example",t = "exxample") == True
    assert candidate(s = "interview",t = "intrvw") == False
    assert candidate(s = "substring",t = "subtrring") == False
    assert candidate(s = "hello",t = "ohellomyworld") == True
    assert candidate(s = "characters",t = "characttrrs") == False
    assert candidate(s = "python",t = "pyyyynntthhoonn") == True
    assert candidate(s = "challenge",t = "cchhaalllleennnggggeee") == True
    assert candidate(s = "algorithm",t = "aggglllllllllooooooorrrrrriiiiiiiiiimmmmmm") == False
    assert candidate(s = "a",t = "") == False
    assert candidate(s = "complexity",t = "ccllllcooooooommmppppppllllleeeeeexxxxxxyyyyyyytttttttt") == False
    assert candidate(s = "",t = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == True
    assert candidate(s = "word",t = "wwwooorrrrdddd") == True
    assert candidate(s = "algorithm",t = "algotihm") == False
    assert candidate(s = "repeated",t = "reppeted") == False
    assert candidate(s = "dynamic",t = "dyyyyynnaaaaaammmmcccciiiiiiiiinnnnnnnnggggggg") == False
    assert candidate(s = "abcd",t = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == True
    assert candidate(s = "abcdabcd",t = "abxycdxeyzabcd") == True
    assert candidate(s = "complex",t = "complxc") == False
    assert candidate(s = "interview",t = "iiiiinnnnnttttttterrrrrrrrreevvvvvvvvvw") == False
    assert candidate(s = "mississippi",t = "mmissiissippiissippississippi") == True
    assert candidate(s = "substrings",t = "sssssuuuuubbstrrrrrriiiiinnnggggggsss") == True
    assert candidate(s = "substring",t = "ssssuusssubbssssttrrrriiiinnngggggg") == True
    assert candidate(s = "sequence",t = "seqqqqquuuuueeeennnnccceeeeee") == True
    assert candidate(s = "programming",t = "ppppprrogggggggrrrrrroooooogggggggaaaaammmmiiiiinnnnnggggggg") == True
    assert candidate(s = "repeated",t = "reeeepppeeeaaaatteeedd") == True
    assert candidate(s = "abcabcabc",t = "aabbccabcabcabc") == True
    assert candidate(s = "z",t = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == True
    assert candidate(s = "consecutive",t = "ccoonnnsseecccccoooooonnnsssccceeeeeevvvvvvvveeeennnnnnncccccccceeeeeee") == False
    assert candidate(s = "",t = "a") == True
    assert candidate(s = "hello",t = "hhelllllooooworld") == True
    assert candidate(s = "example",t = "eeeexxaample") == True
    assert candidate(s = "subsequence",t = "ssubsuuubbbbsssseeeeeqqqqqqqqqqccceeeennnnneeeeee") == False
    assert candidate(s = "characters",t = "ccccchhhhaaaaaarrrrrrrtttteeeeeeccchhhhaaaaaarrrrrrrtttteeeeee") == False
    assert candidate(s = "abcdef",t = "fedcbazyxwvutsrqponmlkjihgfedcba") == False
    assert candidate(s = "subsequence",t = "substringsequence") == True
    assert candidate(s = "abcdefg",t = "axbxcxdxexfxgx") == True
    assert candidate(s = "abcdefg",t = "azbycxdwevfug") == True
    assert candidate(s = "sequence",t = "sqeuences") == False
