# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "hello",t = "world") == False
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "zyxwvutsrqponmlkjihgfedcba") == True
    assert candidate(s = "paper",t = "title") == True
    assert candidate(s = "#a@C",t = "%b$D") == True
    assert candidate(s = "1234567890",t = "0987654321") == True
    assert candidate(s = "aaaa",t = "bbbb") == True
    assert candidate(s = "123",t = "456") == True
    assert candidate(s = "13",t = "42") == True
    assert candidate(s = "egg",t = "add") == True
    assert candidate(s = "test",t = "tets") == False
    assert candidate(s = "foo",t = "bar") == False
    assert candidate(s = "badc",t = "baba") == False
    assert candidate(s = "abba",t = "abba") == True
    assert candidate(s = "a",t = "a") == True
    assert candidate(s = "abcd",t = "dcba") == True
    assert candidate(s = "ab",t = "aa") == False
    assert candidate(s = "abcdefghijabcdefghij",t = "zyxwvutsrqzyxwvutsrq") == True
    assert candidate(s = "testcase",t = "tattldce") == False
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzz") == False
    assert candidate(s = "thisisatest",t = "qdpdqpdafqd") == False
    assert candidate(s = "123456",t = "654321") == True
    assert candidate(s = "hello world",t = "uifsf ftuqi") == False
    assert candidate(s = "aba",t = "cdc") == True
    assert candidate(s = "xyzzzzzzzzzyxzzzzzzzxy",t = "yxqqqqqqqqqyxqqqqqqqyx") == False
    assert candidate(s = "aabbccddeeff",t = "zzyyxxwwvvuuzz") == True
    assert candidate(s = "aabb",t = "cccc") == False
    assert candidate(s = "abracadabra",t = "xyxzyzyxzyx") == False
    assert candidate(s = "aaaaa",t = "bbbbb") == True
    assert candidate(s = "abcdeabcde",t = "fghijfghij") == True
    assert candidate(s = "abcdefg",t = "gfedcba") == True
    assert candidate(s = "a",t = "z") == True
    assert candidate(s = "abacaba",t = "xyzxzyx") == False
    assert candidate(s = "abccbaabc",t = "xyzyxzyxzyx") == False
    assert candidate(s = "abcdabcdabcd",t = "wxyzwxyzwxyz") == True
    assert candidate(s = "mississippi",t = "bbccddeffgg") == False
    assert candidate(s = "aabbccddeeff",t = "zzzzyyxxwwvvuuzz") == False
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzyyxxwwvvuuttrrssqqppoonnmmllkkjjiihhggeeffddeebbaa") == False
    assert candidate(s = "abcde",t = "edcba") == True
    assert candidate(s = "ababab",t = "xyzxyz") == False
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",t = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == False
    assert candidate(s = "ababababab",t = "cdcdcdcdcd") == True
    assert candidate(s = "randomstring",t = "stringrandom") == False
    assert candidate(s = "mississippi",t = "hhlllppppss") == False
    assert candidate(s = "aabbccddeeffgg",t = "zzxxccvvnngghh") == True
    assert candidate(s = "repeatedcharacters",t = "substitutedletters") == False
    assert candidate(s = "aabbcc",t = "ddeeff") == True
    assert candidate(s = "abcdefghijkabcdefghijkabcdefghijkabcdefghijk",t = "abcdefghijkabcdefghijkabcdefghijkabcdefghijk") == True
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "bcdefghijklmnopqrstuvwxyza") == True
    assert candidate(s = "longlongstringwithvariouscharacters",t = "shortshort") == False
    assert candidate(s = "sos",t = "non") == True
    assert candidate(s = "rat",t = "car") == True
    assert candidate(s = "elephant",t = "mouse") == False
    assert candidate(s = "abc",t = "zyx") == True
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzxxwwvvuuttssrrqqppoonnmmllkkjjiihhggeeffddccbbaa") == True
    assert candidate(s = "isomorphic",t = "esomoprphc") == False
    assert candidate(s = "aaabbbccc",t = "xxxyyyzzz") == True
    assert candidate(s = "abcdefghij",t = "jihgfedcba") == True
    assert candidate(s = "aaaaaa",t = "bbbbbb") == True
    assert candidate(s = "mississippi",t = "bbcccb") == False
    assert candidate(s = "xyxxyxyxyx",t = "xyxyyxyxyx") == False
    assert candidate(s = "aaaabbbbccccdddd",t = "ddddccccbbbbaaaa") == True
    assert candidate(s = "sameexample",t = "gnatgnatgnat") == False
    assert candidate(s = "twosky",t = "threesky") == False
    assert candidate(s = "abcabcabc",t = "xyzxyzxyz") == True
    assert candidate(s = "hellohello",t = "worldworld") == False
    assert candidate(s = "12345",t = "54321") == True
    assert candidate(s = "aabbccddeeffgghhii",t = "zzxxyywwvvuuttrrqqpp") == True
    assert candidate(s = "123123123",t = "abcabcabc") == True
    assert candidate(s = "racecar",t = "level") == False
    assert candidate(s = "racecar",t = "madam") == False
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzyyxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccbbaa") == True
    assert candidate(s = "abacabadabacaba",t = "xyxyxyxyxyxyxyxy") == False
    assert candidate(s = "abcdeffedcba",t = "gfedcbaabcdefg") == False
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzyyxxwwvvuuttrrssqqppoonnmmllkkjjiihhggeeffdccbbbaa") == False
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzzzyyyxxwwvvuuttrrsqqppoonnmmllkkjjiihhggffeeddccbbaa") == False
    assert candidate(s = "1234567890",t = "!@#$%^&*()") == True
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzxxwvuttssrrqqponmlkjihgfedcbbaa") == False
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzyyxxwwvvuuttrrssqqppoonnmmllkkjjiihhhgggffeeeeddccbbbaa") == False
    assert candidate(s = "xyzzxyzz",t = "abccabcc") == True
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "abcdefghijklmnopqrstuvwxyz") == True
    assert candidate(s = "thisisatest",t = "abccbaabcab") == False
    assert candidate(s = "abcdabcdabcdabcd",t = "dcbaabcdabcdabcd") == False
    assert candidate(s = "anagram",t = "nagaram") == False
    assert candidate(s = "aaaaabbbbbccccc",t = "bbbbbcccccaaaaa") == True
    assert candidate(s = "abcdabcd",t = "wxyzwxyz") == True
    assert candidate(s = "twowords",t = "twooorld") == False
    assert candidate(s = "abbabbbbabaabababbaaabbbabbbaaa",t = "xyzxxzzxzyzyzyzyzyzyzyzyzyzyzyzyzyz") == False
    assert candidate(s = "aaabbbcccdddeeefffggghhhh",t = "mmmnnnoooqqrssstttuuuvvvvv") == False
    assert candidate(s = "mississippi",t = "bbjjjjbbbrrr") == False
    assert candidate(s = "abab",t = "baba") == True
    assert candidate(s = "thisisatest",t = "thisisatest") == True
    assert candidate(s = "unique",t = "unique") == True
    assert candidate(s = "abcabcabcabc",t = "defgdefgdefgdefg") == False
    assert candidate(s = "isomorphic",t = "homomorphi") == False
    assert candidate(s = "aaaaabbbbbaaaa",t = "cccceeeedddd") == False
    assert candidate(s = "xxxxx",t = "yyyyy") == True
    assert candidate(s = "abcabcabcabc",t = "xyzxyzxyzxyz") == True
    assert candidate(s = "abcabcabc",t = "xyzxyzyxzy") == False
    assert candidate(s = "isomorphic",t = "homomorphic") == False
    assert candidate(s = "sabcsabc",t = "tabctabc") == True
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnm",t = "mlkjihgfdsapoiuytrewqzxcvbnm") == False
    assert candidate(s = "thisisatest",t = "thatistest") == False
    assert candidate(s = "!@#$%^&*()",t = "()&*^%$#@!") == True
    assert candidate(s = "racecar",t = "kayyak") == False
    assert candidate(s = "!@#$%^&*()",t = ")(*&^%$#@!") == True
    assert candidate(s = "sphinxofblackquartzjumps",t = "zpmxkbvhnckgyusldqpj") == False
    assert candidate(s = "1122334455",t = "1122334455") == True
    assert candidate(s = "ab",t = "zy") == True
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccbbaa") == True
    assert candidate(s = "aaaaaa",t = "zzzzzz") == True
    assert candidate(s = "noon",t = "moon") == False
    assert candidate(s = "aaaaabbbbccccddddd",t = "bbbbbccccdddddfffff") == False
    assert candidate(s = "special$chars!@#",t = "normal%^&*()") == False
    assert candidate(s = "abcabcabcabc",t = "defdefdefdef") == True
    assert candidate(s = "mississippi",t = "bbnnnnoooppp") == False
    assert candidate(s = "teest",t = "beest") == False
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",t = "zyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcba") == True
    assert candidate(s = "!@#$%^",t = "^%$#@!") == True
    assert candidate(s = "unique",t = "mapped") == False
    assert candidate(s = "mississippi",t = "eeffgghhiiii") == False
    assert candidate(s = "xyxxyxyxyx",t = "zvzvzvzvzv") == False
    assert candidate(s = "abacabadabacaba",t = "xyxzyxzyzxzyxzy") == False
    assert candidate(s = "aabbccddeeffgghhiijj",t = "zzxxccvvnnooppmmqqllkk") == True
    assert candidate(s = "abababab",t = "cdcdcdcd") == True
    assert candidate(s = "xyxzyzyx",t = "qpqpqpqp") == False
    assert candidate(s = "abcdefghijabcdefghij",t = "klmnopqrstklmnopqrst") == True
    assert candidate(s = "aabbccddeeff",t = "zzxxyywwvvuutt") == True
    assert candidate(s = "elephant",t = "zuluqaak") == False
    assert candidate(s = "mississippi",t = "lllssssiiip") == False
    assert candidate(s = "thisproblemisfun",t = "thatquestionistame") == False
    assert candidate(s = "abcdefghij",t = "abcdefghij") == True
