# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "aabbaa") == 4
    assert candidate(s = "xyzx") == 2
    assert candidate(s = "a") == -1
    assert candidate(s = "aa") == 0
    assert candidate(s = "abcda") == 3
    assert candidate(s = "abcabc") == 2
    assert candidate(s = "abcdabcd") == 3
    assert candidate(s = "xyz") == -1
    assert candidate(s = "abcabcbb") == 5
    assert candidate(s = "leetcode") == 5
    assert candidate(s = "mnopqrstuvmnop") == 9
    assert candidate(s = "zzzzzzzzzz") == 8
    assert candidate(s = "zabz") == 2
    assert candidate(s = "cbzxy") == -1
    assert candidate(s = "abcdeabcde") == 4
    assert candidate(s = "aabbcc") == 0
    assert candidate(s = "zabacdz") == 5
    assert candidate(s = "mnopqrlomn") == 7
    assert candidate(s = "abacaba") == 5
    assert candidate(s = "abca") == 2
    assert candidate(s = "abcdefg") == -1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzyyxxwwvvuuttssrrqqppoonnmmllkkjjiihggffeeddccbbaa") == 102
    assert candidate(s = "aaaabbbbccccdddd") == 2
    assert candidate(s = "abcabcabcabcabcabcabc") == 17
    assert candidate(s = "ababcabcab") == 7
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzxywvutsrqponmlkjihgfedcba") == 50
    assert candidate(s = "abcdexyzabcdexyzabcdexyz") == 15
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzza") == 51
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzz") == 8
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 49
    assert candidate(s = "deified") == 5
    assert candidate(s = "pqrstuvwxyzabcdefghijklmno") == -1
    assert candidate(s = "abcdefgahijklmnopqrstuvwxyz") == 6
    assert candidate(s = "rotorrotorrotor") == 13
    assert candidate(s = "aaaaaaaaaabbbbbbbbbccccccccddddddddeeeeeeeeeffffffffggggggggghhhhhhhhiiiiiiiiiijjjjjjjjjjjjjjjjjkkkkkkkkkkkllllllllllllllllllmmmmmmmmmmmmmmmmmmmnnnnnnnnnnnnnnnnnnnooooooooooooooooppppppppppppppppppppqqqqqqqqqqqqqqqqqqqqrrrrrrrrrrrrrrrrrrrrsssssssssssssssssssssttttttttttttttttttttuuuuuuuuuuuuuuuuuuuuvvvvvvvvvvvvvvvvvvvvwwwwwwwwwwwwwwwwwwwwxxxyyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzzzzzz") == 19
    assert candidate(s = "aaaaabbbbbcccccdddddeeeee") == 3
    assert candidate(s = "kayak") == 3
    assert candidate(s = "abacabadabacaba") == 13
    assert candidate(s = "aabbccddeeaabbccddeeffgghheeffgghhii") == 18
    assert candidate(s = "abracadabra") == 9
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 54
    assert candidate(s = "abcabcabcabc") == 8
    assert candidate(s = "abcdaebcdfeghifijkiljklmnopqrstuvswxyzxyzz") == 4
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 51
    assert candidate(s = "xyzyxzyzyxzyzyxzyzyx") == 18
    assert candidate(s = "ab") == -1
    assert candidate(s = "xyzwvutsrqponmlkjihgfedcbaabcdefghijklmnopqrstuvwxyz") == 48
    assert candidate(s = "aabcdefghijklmnopqrstuvwxyzabcde") == 26
    assert candidate(s = "xyzzxyzzxyzzxyzzxyzz") == 16
    assert candidate(s = "abcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcb") == 113
    assert candidate(s = "acbabcbabcbabcbabcbabcbabcbabcbabcbabcbabcbabcbabcbabcbabcbabcbabcbabcbabcbabcbabcbabcbabcbabcbabcbabcbabcbabcba") == 110
    assert candidate(s = "rotor") == 3
    assert candidate(s = "racecar") == 5
    assert candidate(s = "aaabbbaaaabbbaaaabbbaaaabbbaaaabbbaaaabbbaaaabbbaaaabbbaaaabbbaaaabbbaaaabbbaaaabbbaaaabbbaaaabbbaaaabbbaaa") == 105
    assert candidate(s = "abcdefghijabcdefghij") == 9
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 50
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 25
    assert candidate(s = "abcdefghijabcdefghijabcdefghij") == 19
    assert candidate(s = "noon") == 2
    assert candidate(s = "aaabaaaacaaaaadaaaaaeaaaaa") == 24
    assert candidate(s = "abcdefgabcdefg") == 6
    assert candidate(s = "pneumonoultramicroscopicsilicovolcanoconiosis") == 37
    assert candidate(s = "lkjlkjlkjlkjlkjlkj") == 14
    assert candidate(s = "abcdeafghijaklmnopqrastuvwxyz") == 19
    assert candidate(s = "aabbaaabbbaaa") == 11
    assert candidate(s = "abcdaebcdfeghifijkiljklmnopqrstuvswxyzxyzzzyxwvutsrqponmlkjilfedcbazyxwvutsrqponmlkjihgfedcba") == 91
    assert candidate(s = "abcdefghijjihegfedcba") == 19
    assert candidate(s = "abacaxab") == 5
    assert candidate(s = "mississippi") == 8
    assert candidate(s = "xyzzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxz") == 124
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 0
    assert candidate(s = "level") == 3
    assert candidate(s = "abcdefghijzyxwvutsrqponmlkjihgfedcba") == 34
    assert candidate(s = "abcdefgxyzgfedcba") == 15
