# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "zzzzzzzzz") == 1
    assert candidate(s = "abxyz") == 3
    assert candidate(s = "qrstuvwpqrstu") == 7
    assert candidate(s = "mnopqrstuvwxyzz") == 14
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "mnopqrstuvwxyza") == 14
    assert candidate(s = "abababab") == 2
    assert candidate(s = "qrstuvwxyza") == 10
    assert candidate(s = "bcdfghij") == 5
    assert candidate(s = "a") == 1
    assert candidate(s = "abcdabcde") == 5
    assert candidate(s = "pqrstuvwxyzabc") == 11
    assert candidate(s = "ababababab") == 2
    assert candidate(s = "mnopqr") == 6
    assert candidate(s = "abcde") == 5
    assert candidate(s = "xyz") == 3
    assert candidate(s = "mnopqrstu") == 9
    assert candidate(s = "qrstuvwpqr") == 7
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba") == 1
    assert candidate(s = "abccba") == 3
    assert candidate(s = "acdfg") == 2
    assert candidate(s = "defghijklmno") == 12
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 2
    assert candidate(s = "zab") == 2
    assert candidate(s = "abxyzab") == 3
    assert candidate(s = "bcdfghjkl") == 3
    assert candidate(s = "abacaba") == 2
    assert candidate(s = "xyzabc") == 3
    assert candidate(s = "abcabcvwxyz") == 5
    assert candidate(s = "abcdefgxyzabcdefghijlmnopqrstuvwxyz") == 15
    assert candidate(s = "abcdefghijlmnopqrstuvwxyzmnopqrstuvwxy") == 15
    assert candidate(s = "mnopqrstuabcdefghijklmnopqrstuvwxyzaabcdeefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "defghijklmnopqrstuvwxyz") == 23
    assert candidate(s = "mnopqrstuvmnopqrstu") == 10
    assert candidate(s = "mnopqrstuuvwxyzaaaa") == 9
    assert candidate(s = "abcabcdabcdeabcdeabcd") == 5
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzab") == 26
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzz") == 26
    assert candidate(s = "pqrsabcdewxyz") == 5
    assert candidate(s = "xyzabcd") == 4
    assert candidate(s = "aaaabbbbcccc") == 2
    assert candidate(s = "zzzzzzzzzz") == 1
    assert candidate(s = "abxyzabxyz") == 3
    assert candidate(s = "abdefgxyz") == 4
    assert candidate(s = "defghijklmnopqrstuvw") == 20
    assert candidate(s = "mnopqrstuvxyzab") == 10
    assert candidate(s = "pqrstuvwxyzaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 11
    assert candidate(s = "mnopqrstuabcde") == 9
    assert candidate(s = "abcxyzab") == 3
    assert candidate(s = "abcdefgxyzabcde") == 7
    assert candidate(s = "abcabcabcabcabcabcabc") == 3
    assert candidate(s = "pqrstuvwxyza") == 11
    assert candidate(s = "mnopqrstuvwxyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 14
    assert candidate(s = "mnopqrstuvwxyzmnopqrstuvwxyzmnopqrstuvwxyzmnopqrstuvwxyzmnopqrstuvwxyz") == 14
    assert candidate(s = "lmnopqrstuvwxyzabc") == 15
    assert candidate(s = "mnopqrstuvwxyzabcdefghijkl") == 14
    assert candidate(s = "qrsabcdabcdxyz") == 4
    assert candidate(s = "defghijklmnopqrstuvwxyza") == 23
    assert candidate(s = "mnopqrstuvwxyzmnopqrstuvwxyza") == 14
    assert candidate(s = "abcdeabfghicdef") == 5
    assert candidate(s = "xyzabxyzuvwxyza") == 6
    assert candidate(s = "abxyzabcxyz") == 3
    assert candidate(s = "qrstuvwxyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 10
    assert candidate(s = "abcdefabcdeabcde") == 6
    assert candidate(s = "pqrsabcd") == 4
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 26
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzmnopqrstuvwxyz") == 26
    assert candidate(s = "abcdefghijklmnopqrstuvwxyza") == 26
    assert candidate(s = "klmnopqrstuvxyz") == 12
    assert candidate(s = "abababababab") == 2
    assert candidate(s = "mnopqrstuabcdefghijklmnopqrstuvwxyzaabcde") == 26
    assert candidate(s = "mnopqrstuvwxyzabcde") == 14
    assert candidate(s = "xyzabcde") == 5
    assert candidate(s = "mnopqrstuzyxwvutsrqponmlkjihgfedcba") == 9
    assert candidate(s = "qrsabcdabcdabcd") == 4
    assert candidate(s = "mnopqrstuvwxyzabcdefghijklmno") == 15
    assert candidate(s = "abcdeabcdabcdabcdabcde") == 5
    assert candidate(s = "mnopqrstuabcdefghijklmnopqrstuvwxyza") == 26
    assert candidate(s = "aaaaa") == 1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "zabcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "xyzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxz") == 3
    assert candidate(s = "mnopqrstuuvwxyza") == 9
    assert candidate(s = "abcdefgabcdefgabcdefgabcdefg") == 7
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "qrstuvwxyzabcdefghijklmnop") == 16
    assert candidate(s = "abcdxyzuvwxyza") == 6
    assert candidate(s = "mnopqrstuvwxyzmnopqrstu") == 14
    assert candidate(s = "xyzzyxwvutsrqponmlkjihgfedcba") == 3
    assert candidate(s = "zabcdefghijklmnopqrstuvwxy") == 25
    assert candidate(s = "zabcvwxyz") == 5
    assert candidate(s = "abxyzabcd") == 4
    assert candidate(s = "mnopqrlmnopqr") == 7
    assert candidate(s = "aabcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "abxyzabc") == 3
    assert candidate(s = "qrstuvwpqrstuzyxwvutsrqponmlkjihgfedcba") == 7
    assert candidate(s = "zabcdefghijklmnopqrstuvwxyza") == 26
    assert candidate(s = "xyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 3
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzaabbcc") == 2
    assert candidate(s = "abcdefghijlmnopqrstuvwxyz") == 15
    assert candidate(s = "abcddefghijklmnopqrstuvwxyz") == 23
    assert candidate(s = "abcdeabcdeabcde") == 5
    assert candidate(s = "qrstuvwxyz") == 10
    assert candidate(s = "abcdefghijkabcde") == 11
    assert candidate(s = "abcdefgabcdefgabcdefg") == 7
    assert candidate(s = "abcdefg hijklmnop qrstuvwx yz") == 9
    assert candidate(s = "abcdefghijlkjihgfedcba") == 10
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcbaedcba") == 1
    assert candidate(s = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz") == 3
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzaabcdefghijklmnopqrstuvwxyza") == 26
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "xyzzyxwvutsrqpomnlkjihgfedcba") == 3
    assert candidate(s = "pqrstuvwxyzabcde") == 11
    assert candidate(s = "lmnopqrsabcd") == 8
