# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(tiles = "AAAAAAA") == 7
    assert candidate(tiles = "QQQ") == 3
    assert candidate(tiles = "ABCDEFG") == 13699
    assert candidate(tiles = "ABC") == 15
    assert candidate(tiles = "AAB") == 8
    assert candidate(tiles = "AABBCC") == 270
    assert candidate(tiles = "XYZ") == 15
    assert candidate(tiles = "AAABBC") == 188
    assert candidate(tiles = "AB") == 4
    assert candidate(tiles = "AAAAAA") == 6
    assert candidate(tiles = "ABCD") == 64
    assert candidate(tiles = "V") == 1
    assert candidate(tiles = "ABBB") == 13
    assert candidate(tiles = "AAA") == 3
    assert candidate(tiles = "AABC") == 34
    assert candidate(tiles = "HHHHHHHH") == 8
    assert candidate(tiles = "UVWXYZ") == 1956
    assert candidate(tiles = "ABCDABCD") == 7364
    assert candidate(tiles = "ZZZZZZZ") == 7
    assert candidate(tiles = "JKJKJKJKJK") == 922
    assert candidate(tiles = "ZWZWZWZW") == 250
    assert candidate(tiles = "AAAABBBB") == 250
    assert candidate(tiles = "AAABBBCCC") == 5247
    assert candidate(tiles = "AABBCCDDEEFF") == 21295782
    assert candidate(tiles = "AAABBBCCCDDD") == 1107696
    assert candidate(tiles = "XYZXYZ") == 270
    assert candidate(tiles = "ABCDEFGH") == 109600
    assert candidate(tiles = "ABACADAE") == 5188
    assert candidate(tiles = "AABBCD") == 522
    assert candidate(tiles = "HELLO") == 170
    assert candidate(tiles = "AAAAAAAA") == 8
    assert candidate(tiles = "ABCDEABCDE") == 326010
    assert candidate(tiles = "QQQQRRRSSSTTTT") == 12743958
    assert candidate(tiles = "AABCCDDEE") == 65201
    assert candidate(tiles = "PPPPQQRR") == 1350
    assert candidate(tiles = "AAAAABBCCC") == 8293
    assert candidate(tiles = "ABCDABC") == 1840
    assert candidate(tiles = "MISSISSIPPI") == 107898
    assert candidate(tiles = "AABBCCD") == 1840
    assert candidate(tiles = "ABCDEFF") == 7012
    assert candidate(tiles = "REPEAT") == 1010
    assert candidate(tiles = "WWWWW") == 5
    assert candidate(tiles = "ZZZZAAAA") == 250
    assert candidate(tiles = "AABBBCC") == 649
    assert candidate(tiles = "QQQQQQQ") == 7
    assert candidate(tiles = "AABBCCDD") == 7364
    assert candidate(tiles = "AAABBCCCC") == 4024
    assert candidate(tiles = "ABCDEFGHII") == 4986850
    assert candidate(tiles = "ABCXYZ") == 1956
    assert candidate(tiles = "AAAAABBBCCC") == 29887
    assert candidate(tiles = "PYTHON") == 1956
    assert candidate(tiles = "AABCCD") == 522
    assert candidate(tiles = "ABABABABAB") == 922
    assert candidate(tiles = "AABBCCDDEE") == 326010
    assert candidate(tiles = "AAAABBBCCCDDD") == 3627112
    assert candidate(tiles = "AABBCCDE") == 14458
    assert candidate(tiles = "ABCDEF") == 1956
    assert candidate(tiles = "XYZABC") == 1956
    assert candidate(tiles = "SEQUENCES") == 87185
    assert candidate(tiles = "ABCDE") == 325
    assert candidate(tiles = "AABCDD") == 522
    assert candidate(tiles = "ABCABCABC") == 5247
    assert candidate(tiles = "AAAAABBBB") == 460
    assert candidate(tiles = "ABCDEFGABC") == 1274854
    assert candidate(tiles = "QWRTYUIOP") == 986409
    assert candidate(tiles = "AAAAABBBBBCCCCC") == 2435199
    assert candidate(tiles = "UNIQUE") == 1010
    assert candidate(tiles = "TILES") == 325
    assert candidate(tiles = "ABACADAEA") == 9833
    assert candidate(tiles = "MNOPQRST") == 109600
    assert candidate(tiles = "AAAABBBCCC") == 13298
    assert candidate(tiles = "FFFFFFFFF") == 9
    assert candidate(tiles = "ABCDEFGHI") == 986409
    assert candidate(tiles = "AAAAAABBBB") == 790
