# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(picture = [['W', 'W', 'B'], ['W', 'B', 'W'], ['B', 'W', 'W']]) == 3
    assert candidate(picture = [['B', 'B', 'B'], ['B', 'B', 'W'], ['B', 'B', 'B']]) == 0
    assert candidate(picture = [['W']]) == 0
    assert candidate(picture = [['W', 'W', 'W'], ['W', 'W', 'W'], ['W', 'W', 'W']]) == 0
    assert candidate(picture = [['B', 'W', 'W'], ['W', 'W', 'W'], ['W', 'W', 'B']]) == 2
    assert candidate(picture = [['B', 'W', 'W', 'B'], ['W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W'], ['B', 'W', 'W', 'B']]) == 0
    assert candidate(picture = [['B', 'W', 'W'], ['W', 'B', 'W'], ['W', 'W', 'B']]) == 3
    assert candidate(picture = [['B', 'W', 'B'], ['W', 'B', 'W'], ['B', 'W', 'B']]) == 1
    assert candidate(picture = [['B']]) == 1
    assert candidate(picture = [['B', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W'], ['W', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'B']]) == 2
    assert candidate(picture = [['B', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'B', 'W'], ['W', 'W', 'B', 'W', 'W', 'W'], ['W', 'W', 'W', 'B', 'W', 'W'], ['W', 'B', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'B']]) == 6
    assert candidate(picture = [['W', 'B', 'W', 'W'], ['W', 'W', 'B', 'W'], ['B', 'W', 'W', 'W'], ['W', 'W', 'W', 'B']]) == 4
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W']]) == 0
    assert candidate(picture = [['B', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W'], ['B', 'W', 'B', 'W', 'B'], ['W', 'W', 'W', 'W', 'W'], ['B', 'W', 'W', 'W', 'B']]) == 0
    assert candidate(picture = [['W', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W'], ['B', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'B', 'W']]) == 3
    assert candidate(picture = [['W', 'W', 'W'], ['W', 'B', 'W'], ['W', 'W', 'W'], ['B', 'W', 'B'], ['W', 'W', 'W']]) == 1
    assert candidate(picture = [['W', 'B', 'W', 'W', 'W', 'B', 'W'], ['B', 'W', 'B', 'W', 'B', 'W', 'B'], ['W', 'B', 'W', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W', 'B', 'W'], ['B', 'W', 'B', 'W', 'B', 'W', 'B'], ['W', 'B', 'W', 'W', 'W', 'B', 'W']]) == 0
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W'], ['W', 'W', 'W', 'B', 'W'], ['W', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'B']]) == 4
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'B', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W']]) == 2
    assert candidate(picture = [['W', 'W', 'B', 'W', 'W'], ['B', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W'], ['B', 'W', 'W', 'W', 'B']]) == 1
    assert candidate(picture = [['B', 'W', 'W', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['B', 'W', 'W', 'W', 'W', 'W', 'B']]) == 0
    assert candidate(picture = [['W', 'W', 'B', 'W', 'W'], ['W', 'B', 'W', 'W', 'B'], ['B', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'B', 'W'], ['W', 'B', 'W', 'W', 'W']]) == 3
    assert candidate(picture = [['B', 'W', 'W', 'W', 'B'], ['W', 'B', 'W', 'B', 'W'], ['W', 'W', 'B', 'W', 'W'], ['B', 'W', 'W', 'B', 'W'], ['B', 'W', 'W', 'W', 'B']]) == 1
    assert candidate(picture = [['B', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'B', 'W', 'W', 'W'], ['W', 'W', 'B', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W', 'B', 'W']]) == 7
    assert candidate(picture = [['B', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'B', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'B', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W']]) == 4
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'B', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'B', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'B', 'W']]) == 0
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'B', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'B']]) == 4
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'B', 'W'], ['W', 'W', 'B', 'W', 'W'], ['W', 'B', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W']]) == 1
    assert candidate(picture = [['W', 'W', 'B', 'W', 'W'], ['W', 'B', 'W', 'B', 'W'], ['B', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W'], ['W', 'W', 'B', 'W', 'W']]) == 0
    assert candidate(picture = [['B', 'B', 'W', 'W', 'W'], ['W', 'W', 'W', 'B', 'B'], ['W', 'B', 'B', 'W', 'W'], ['B', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'B']]) == 0
    assert candidate(picture = [['B', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W'], ['B', 'W', 'W', 'W', 'B']]) == 0
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'B', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'B']]) == 3
    assert candidate(picture = [['B', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W'], ['B', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W']]) == 0
    assert candidate(picture = [['B', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'B']]) == 2
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W'], ['W', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'B'], ['B', 'W', 'W', 'W', 'W']]) == 5
    assert candidate(picture = [['W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W'], ['W', 'W', 'W', 'B']]) == 2
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W']]) == 0
    assert candidate(picture = [['W', 'B', 'W', 'W', 'W'], ['B', 'W', 'B', 'W', 'B'], ['W', 'B', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'B', 'W']]) == 0
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W']]) == 0
    assert candidate(picture = [['B', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W'], ['B', 'W', 'B', 'W', 'W']]) == 0
    assert candidate(picture = [['W', 'W', 'B', 'W'], ['B', 'W', 'W', 'B'], ['W', 'W', 'B', 'W'], ['B', 'W', 'W', 'B']]) == 0
    assert candidate(picture = [['B', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'B']]) == 2
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W', 'W'], ['B', 'W', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'B', 'W']]) == 0
    assert candidate(picture = [['W', 'W', 'B', 'W'], ['B', 'W', 'W', 'W'], ['W', 'W', 'W', 'B'], ['W', 'B', 'W', 'W']]) == 4
    assert candidate(picture = [['B', 'W', 'B', 'W', 'B'], ['W', 'W', 'W', 'W', 'W'], ['B', 'W', 'B', 'W', 'B'], ['W', 'W', 'W', 'W', 'W'], ['B', 'W', 'B', 'W', 'B']]) == 0
    assert candidate(picture = [['B', 'W', 'W', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'B', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['B', 'W', 'W', 'W', 'W', 'W', 'B']]) == 0
    assert candidate(picture = [['W', 'B', 'W', 'W', 'W'], ['B', 'W', 'B', 'W', 'B'], ['W', 'B', 'W', 'B', 'W'], ['B', 'W', 'B', 'W', 'B'], ['W', 'B', 'W', 'W', 'W']]) == 0
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W', 'W']]) == 0
    assert candidate(picture = [['B', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'B', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'B', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W']]) == 4
    assert candidate(picture = [['B', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'B', 'W', 'W', 'W'], ['W', 'W', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W', 'W']]) == 5
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'B', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'B']]) == 3
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'B', 'W', 'B', 'W'], ['W', 'B', 'W', 'W', 'W', 'B', 'W'], ['W', 'B', 'W', 'W', 'W', 'B', 'W'], ['W', 'B', 'W', 'W', 'W', 'B', 'W'], ['W', 'B', 'W', 'B', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W']]) == 0
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'B', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W']]) == 1
    assert candidate(picture = [['W', 'B', 'W', 'W', 'W'], ['B', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'B', 'W'], ['W', 'B', 'W', 'W', 'W']]) == 1
    assert candidate(picture = [['B', 'W', 'W', 'W'], ['W', 'B', 'W', 'W'], ['W', 'W', 'B', 'W'], ['W', 'W', 'W', 'B']]) == 4
    assert candidate(picture = [['W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W'], ['W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W']]) == 2
    assert candidate(picture = [['W', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'W'], ['B', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W'], ['W', 'W', 'B', 'W', 'W']]) == 0
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'B', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W']]) == 1
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W']]) == 0
    assert candidate(picture = [['B', 'B', 'B', 'W', 'W'], ['B', 'W', 'B', 'W', 'W'], ['B', 'B', 'B', 'W', 'W'], ['W', 'W', 'W', 'B', 'B'], ['W', 'W', 'W', 'B', 'B']]) == 0
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W'], ['W', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W']]) == 1
    assert candidate(picture = [['B', 'W', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'B', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'B'], ['B', 'W', 'W', 'W', 'W', 'B']]) == 1
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'B', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W']]) == 1
    assert candidate(picture = [['W', 'W', 'W'], ['B', 'B', 'B'], ['W', 'W', 'W'], ['B', 'B', 'B'], ['W', 'W', 'W']]) == 0
    assert candidate(picture = [['W', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'W'], ['B', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W'], ['W', 'W', 'B', 'W', 'W']]) == 0
    assert candidate(picture = [['B', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'B', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'B'], ['W', 'B', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'B']]) == 5
    assert candidate(picture = [['W', 'W', 'B', 'W', 'W'], ['W', 'B', 'W', 'B', 'W'], ['B', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W'], ['W', 'W', 'B', 'W', 'W']]) == 0
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W', 'W']]) == 0
    assert candidate(picture = [['W', 'W', 'B', 'W', 'W'], ['W', 'B', 'W', 'B', 'W'], ['B', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'B', 'W'], ['W', 'W', 'B', 'W', 'W']]) == 1
    assert candidate(picture = [['B', 'W', 'W', 'W', 'W'], ['W', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'B'], ['W', 'B', 'W', 'W', 'W']]) == 5
    assert candidate(picture = [['W', 'B', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'B', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'B', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'B', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'B']]) == 7
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'B', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'B', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W', 'W', 'B']]) == 6
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W']]) == 0
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W', 'W']]) == 3
    assert candidate(picture = [['B', 'W', 'W', 'W'], ['W', 'W', 'W', 'W'], ['W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W'], ['B', 'W', 'W', 'W']]) == 1
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'W', 'B', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'W', 'W']]) == 5
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'B', 'W'], ['W', 'W', 'W', 'W', 'W']]) == 0
    assert candidate(picture = [['W', 'W', 'W', 'W', 'W'], ['W', 'B', 'W', 'W', 'W'], ['W', 'W', 'B', 'W', 'W'], ['W', 'W', 'W', 'W', 'B'], ['W', 'W', 'W', 'W', 'W']]) == 3
