# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz",k = 25) == 20
    assert candidate(s = "a",k = 0) == 1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",k = 0) == 1
    assert candidate(s = "abcd",k = 3) == 4
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba",k = 1) == 26
    assert candidate(s = "a",k = 5) == 1
    assert candidate(s = "abacabadabacaba",k = 1) == 12
    assert candidate(s = "pqrspqrstuv",k = 2) == 10
    assert candidate(s = "abcabcabcabc",k = 2) == 12
    assert candidate(s = "abcdefghijklmnopqrstuvwxyza",k = 25) == 27
    assert candidate(s = "acfgbd",k = 2) == 4
    assert candidate(s = "aaaabbbbcccc",k = 25) == 12
    assert candidate(s = "zzzzzzzzz",k = 25) == 9
    assert candidate(s = "leetcode",k = 2) == 5
    assert candidate(s = "abcabcabc",k = 2) == 9
    assert candidate(s = "zyzyzyzyzyzyzyzyzyzy",k = 1) == 20
    assert candidate(s = "triplebyte",k = 2) == 3
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba",k = 1) == 52
    assert candidate(s = "aabbaabbaabbaabbaabbaabbaabbaabb",k = 1) == 32
    assert candidate(s = "aaaabbbbccccddddeeeeffffgggg",k = 2) == 28
    assert candidate(s = "aabcdefghijklmnopqrstuvwxyz",k = 24) == 27
    assert candidate(s = "abcdefghijabcdefghijabcdefghij",k = 2) == 16
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",k = 1) == 26
    assert candidate(s = "abacabadabacaba",k = 0) == 8
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 0) == 50
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",k = 25) == 26
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba",k = 5) == 26
    assert candidate(s = "aaaabbbbccccddddeeeeffffgggghhhh",k = 3) == 32
    assert candidate(s = "aabcdefghijklmnopqrstuvwxyz",k = 1) == 27
    assert candidate(s = "abababababababababababababababab",k = 0) == 16
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcd",k = 3) == 32
    assert candidate(s = "ababababababababababababababababab",k = 0) == 17
    assert candidate(s = "abcdxyzabcdxyzabcdxyz",k = 4) == 12
    assert candidate(s = "z",k = 25) == 1
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba",k = 0) == 1
    assert candidate(s = "mississippiissipi",k = 4) == 9
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 0) == 60
    assert candidate(s = "thisisaverylongstringthatneedstobechecked",k = 3) == 17
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba",k = 25) == 51
    assert candidate(s = "zzzzyyyyxxxwwvvuttsrrqqppoonnmmllkkjjiihhggffeeddccbbbaaa",k = 3) == 57
    assert candidate(s = "qpwoeirutyalskdjfhgzmxncbv",k = 4) == 11
    assert candidate(s = "aaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaab",k = 0) == 40
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcd",k = 3) == 28
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",k = 2) == 29
    assert candidate(s = "zzzyyyxxxwwwwvvvuuutttsssrrrqqqpPPPoonnmmlkkjjiihhhgggfffeeeddccbbbaaa",k = 3) == 67
    assert candidate(s = "abcdabcdabcdabcdabcdabcd",k = 3) == 24
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm",k = 5) == 21
    assert candidate(s = "abacabacabacaba",k = 1) == 12
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",k = 25) == 52
    assert candidate(s = "zzzyyyxxxwwwwvvvuutttsssrqqppoonnmlkkjjiihhggffeeddccbbaaa",k = 2) == 58
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 1) == 52
    assert candidate(s = "zabcdefghijklmnopqrstuvwxyz",k = 24) == 26
    assert candidate(s = "bdfhjlnprtvxz",k = 2) == 13
    assert candidate(s = "mnopqrsmnopqrsmnopqrsmnopqrs",k = 2) == 16
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",k = 0) == 120
    assert candidate(s = "qwertypoiuytrewqazxcvbnmnbvcxz",k = 5) == 15
    assert candidate(s = "abcdefghijabcdefghijabcdefghij",k = 5) == 22
    assert candidate(s = "qpqprqqpqrqpqrqpqrqpq",k = 1) == 20
    assert candidate(s = "abcdxyzabcdxyzabcdxyz",k = 3) == 12
    assert candidate(s = "mnopqrstuvwxyzabcdefghijkl",k = 10) == 14
    assert candidate(s = "mmppqqrrssttuuvvwwxxyyzz",k = 1) == 22
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz",k = 0) == 20
    assert candidate(s = "abababababababababababababababab",k = 1) == 32
    assert candidate(s = "abcdefgabcdefgabcdefg",k = 5) == 19
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",k = 24) == 26
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 0) == 2
    assert candidate(s = "abacabadabacabadabacabad",k = 1) == 18
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba",k = 2) == 26
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",k = 3) == 30
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcbaabcdefghijklmnopqrstuvwxyz",k = 12) == 52
    assert candidate(s = "aeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",k = 0) == 63
    assert candidate(s = "qpwoeirutyalskdjfhgxcvbnm",k = 5) == 11
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd",k = 2) == 97
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",k = 10) == 37
    assert candidate(s = "abcdefghijkalmnopqrstuvwxyz",k = 2) == 26
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 25) == 84
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 2) == 52
    assert candidate(s = "abababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababab",k = 1) == 128
    assert candidate(s = "abcdabcdabcdabcd",k = 3) == 16
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnmqwertyuiop",k = 5) == 17
    assert candidate(s = "a",k = 25) == 1
    assert candidate(s = "aquickbrownfoxjumpsoverthelazydog",k = 5) == 14
    assert candidate(s = "mjmnjmmnjmnmjmmnj",k = 0) == 8
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba",k = 24) == 26
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 24) == 52
