# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 2
    assert candidate(s = "ababccababcc") == 4
    assert candidate(s = "aabacbebebe") == 6
    assert candidate(s = "a") == 1
    assert candidate(s = "abcabcabc") == 2
    assert candidate(s = "abcabcabcabc") == 2
    assert candidate(s = "ababababab") == 10
    assert candidate(s = "abaccc") == 4
    assert candidate(s = "aa") == 2
    assert candidate(s = "") == 0
    assert candidate(s = "abcabc") == 2
    assert candidate(s = "xyzabcxyzabc") == 2
    assert candidate(s = "xyzxyzxyz") == 2
    assert candidate(s = "abacab") == 3
    assert candidate(s = "ccaabbb") == 5
    assert candidate(s = "aabbaaabbbaaa") == 13
    assert candidate(s = "zzzzzzzzzzzzz") == 13
    assert candidate(s = "abcd") == 2
    assert candidate(s = "aabbccddeeff") == 4
    assert candidate(s = "aab") == 3
    assert candidate(s = "aabbcc") == 4
    assert candidate(s = "mmazzzzzzz") == 8
    assert candidate(s = "aabbbbcccc") == 8
    assert candidate(s = "eceba") == 3
    assert candidate(s = "abacaba") == 3
    assert candidate(s = "abacabac") == 3
    assert candidate(s = "aaaaaaa") == 7
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba") == 2
    assert candidate(s = "abcdefg") == 2
    assert candidate(s = "aaaaaaaaaabbbbbbbbbcccccccccccccccccccccc") == 31
    assert candidate(s = "aabbaabbaabbaabbaabbaabb") == 24
    assert candidate(s = "ababababababababababababababababababababababababab") == 50
    assert candidate(s = "abacababaacbbccba") == 6
    assert candidate(s = "abababababababababababababababababababababababababab") == 52
    assert candidate(s = "ababababababababababab") == 22
    assert candidate(s = "aabbccaaaabbbbcccc") == 8
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 2
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 42
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 54
    assert candidate(s = "aabbbcccccbbbbaaaaccccbbaaa") == 12
    assert candidate(s = "aaaabbbbccccddddeeeeffffgggg") == 8
    assert candidate(s = "abcdabcdeabcdefg") == 2
    assert candidate(s = "abacabadabacaba") == 3
    assert candidate(s = "aabbbbbbaaaaabbbaaabbbaabbbaaa") == 30
    assert candidate(s = "abracadabra") == 3
    assert candidate(s = "xyxyxyxyxyxyxyxyxyxyxyxyxy") == 26
    assert candidate(s = "aabccccaaaabbbbccccaaaabbbbcccc") == 8
    assert candidate(s = "aaabbbaaabbbaaabbbaaa") == 21
    assert candidate(s = "aabababababcabcabc") == 11
    assert candidate(s = "aaabaaaabbbbaaabbb") == 18
    assert candidate(s = "abracadabraabracadabraabracadabraabracadabraabracadabra") == 3
    assert candidate(s = "aaaaaaaabbbbbbbbaaaaabbbbbbbbcccccccccccaaaabbbbcccc") == 29
    assert candidate(s = "ababbabcbababc") == 7
    assert candidate(s = "abccbaabccbaabccbaabccbaabccbaabccba") == 4
    assert candidate(s = "aabbccddeeefffggghhh") == 6
    assert candidate(s = "aabbccccddeee") == 6
    assert candidate(s = "abcabcabcabcabcabcabcabc") == 2
    assert candidate(s = "aabbaaabbbaaaabbbaaabbbaabbbaaaabbbaaabbbaabbbaaaaabbbaaaaabbbaaaa") == 66
    assert candidate(s = "aaaaaabbbbbcccccc") == 11
    assert candidate(s = "abababababab") == 12
    assert candidate(s = "aabcccccaaa") == 8
    assert candidate(s = "abcdeabcdeabcdeabcde") == 2
    assert candidate(s = "ababababababababababababab") == 26
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 52
    assert candidate(s = "mnopqrstuvwxyzmnopqrstuvwxyzmnopqrstuvwxyzmnopqrstuvwxyz") == 2
    assert candidate(s = "abcdefggfedcba") == 4
    assert candidate(s = "abcdefabcdeff") == 3
    assert candidate(s = "abcdabcdabcdabcdabcdabcd") == 2
    assert candidate(s = "zzzzzzyyyyyy") == 12
    assert candidate(s = "aaaaabbbbccccdddd") == 9
    assert candidate(s = "abababababababababababababababababab") == 36
    assert candidate(s = "aabbaabbbccccddeeeeffff") == 9
    assert candidate(s = "mississippi") == 7
    assert candidate(s = "aabccbbbaaaacccbbb") == 7
    assert candidate(s = "abcabcabcabcabc") == 2
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 4
    assert candidate(s = "zxyzzxyzzxyzzxyzz") == 3
    assert candidate(s = "zzzzzzzzzzzzzzzzzz") == 18
    assert candidate(s = "aabbaaccddccbaaabb") == 6
    assert candidate(s = "aabbaabbaabbaabb") == 16
