# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(words = ['z', 'ze', 'zee', 'zeek', 'zeeky', 'zeekys']) == "zeekys"
    assert candidate(words = ['b', 'br', 'bri', 'brio', 'brion', 'brione']) == "brione"
    assert candidate(words = ['zz', 'zzy', 'zzys', 'zzyst']) == ""
    assert candidate(words = ['m', 'mo', 'moc', 'moch', 'mocha', 'mochaa', 'mochaaa', 'mochaaaa', 'mochaaaaa']) == "mochaaaaa"
    assert candidate(words = ['p', 'pu', 'pur', 'pure', 'purel', 'purely']) == "purely"
    assert candidate(words = ['g', 'go', 'gog', 'gogi', 'gogin', 'gogins']) == "gogins"
    assert candidate(words = ['t', 'ta', 'tan', 'tang', 'tangi', 'tangib', 'tangibu', 'tangibl', 'tangible']) == "tangible"
    assert candidate(words = ['b', 'br', 'bre', 'brea', 'break', 'breaks']) == "breaks"
    assert candidate(words = ['zebra', 'zeb', 'zebraf', 'zebrafi', 'zebrafir', 'zebrafire']) == ""
    assert candidate(words = ['w', 'wa', 'wan', 'wana', 'wanat', 'wanath', 'wanathf', 'wanathfu', 'wanathful']) == "wanathful"
    assert candidate(words = ['z', 'zz', 'zzz', 'zzzz', 'zzzzz']) == "zzzzz"
    assert candidate(words = ['w', 'wo', 'wor', 'worl', 'world']) == "world"
    assert candidate(words = ['m', 'mo', 'moc', 'mocq', 'mocqd', 'mocqde', 'mocqdeo']) == "mocqdeo"
    assert candidate(words = ['apple', 'app', 'ap', 'a', 'apples']) == "app"
    assert candidate(words = ['a', 'b', 'c', 'd', 'e', 'f']) == "a"
    assert candidate(words = ['car', 'cars', 'carpet', 'cat']) == ""
    assert candidate(words = ['a', 'aa', 'aaa', 'aaaa', 'aaaaa']) == "aaaaa"
    assert candidate(words = ['abc', 'bc', 'ab', 'qwe']) == ""
    assert candidate(words = ['do', 'dog', 'doge', 'doges', 'dogesh', 'dogeshi']) == ""
    assert candidate(words = ['b', 'be', 'bel', 'bell', 'bella']) == "bella"
    assert candidate(words = ['l', 'la', 'laz', 'lazi', 'lazie', 'lazier', 'laziest']) == "lazier"
    assert candidate(words = ['cat', 'bat', 'rat', 'car', 'card', 'cards']) == ""
    assert candidate(words = ['cat', 'cats', 'catsd', 'catsde']) == ""
    assert candidate(words = ['s', 'sn', 'sna', 'snap', 'snapp', 'snappy']) == "snappy"
    assert candidate(words = ['cat', 'cats', 'catsdogcats', 'dog', 'dogcatsdog', 'hippopotamuses', 'rat', 'ratcatdogcat']) == ""
    assert candidate(words = ['car', 'cars', 'carsa', 'carsac']) == ""
    assert candidate(words = ['do', 'dot', 'dots', 'dotz', 'dotzo']) == ""
    assert candidate(words = ['leet', 'leetc', 'leetcod', 'leetcode']) == ""
    assert candidate(words = ['p', 'pp', 'ppp', 'pppp', 'ppppp']) == "ppppp"
    assert candidate(words = ['car', 'cars', 'carx', 'carxx', 'cat', 'cats', 'catt']) == ""
    assert candidate(words = ['car', 'cat', 'cater', 'cart', 'ca']) == ""
    assert candidate(words = ['banana', 'ban', 'ba', 'b']) == "ban"
    assert candidate(words = ['k', 'ki', 'kir', 'kira', 'kiran']) == "kiran"
    assert candidate(words = ['a', 'banana', 'app', 'appl', 'ap', 'apply', 'apple']) == "apple"
    assert candidate(words = ['z', 'zo', 'zoo', 'zoos', 'zooso', 'zoosoo', 'zoosooo']) == "zoosooo"
    assert candidate(words = ['z', 'zo', 'zon', 'zone', 'zoned', 'zonedu', 'zoneduc', 'zoneducu', 'zoneducat', 'zoneducati', 'zoneducatio', 'zoneducation']) == "zoneducu"
    assert candidate(words = ['aa', 'a', 'aaa', 'aab', 'aac', 'ba', 'b', 'bba', 'bbb', 'bbc', 'caa', 'ca', 'cca', 'ccc', 'cccc']) == "aaa"
    assert candidate(words = ['cat', 'cater', 'category', 'catalog', 'catalogs', 'catalogue', 'catalogued', 'catalogues']) == ""
    assert candidate(words = ['sun', 's', 'su', 'moon', 'mo', 'moo', 'moonb', 'moonba', 'moonbas', 'moonbase', 'moonbaseb', 'moonbasebo', 'moonbasebon', 'moonbasebonu', 'moonbasebonux', 'moonbasebonuxa', 'moonbasebonuxal', 'moonbasebonuxale', 'moonbasebonuxalex', 'moonbasebonuxalexu']) == "sun"
    assert candidate(words = ['j', 'jo', 'jog', 'jogg', 'joggi', 'joggig', 'joggign', 'joggigng', 'joggigngu', 'joggigngun', 'joggignguns']) == "joggignguns"
    assert candidate(words = ['a', 'ab', 'abc', 'abcd', 'abcde', 'abcdef', 'abcdefg', 'abcdefgh', 'abcdefghi', 'abcdefghij', 'abcdefghijk', 'abcdefghijkl', 'abcdefghijklm', 'abcdefghijklmn', 'abcdefghijklmno', 'abcdefghijklmnop', 'abcdefghijklmnopq', 'abcdefghijklmnopqr', 'abcdefghijklmnopqrs', 'abcdefghijklmnopqrst', 'abcdefghijklmnopqrstu', 'abcdefghijklmnopqrstuv', 'abcdefghijklmnopqrstuvw', 'abcdefghijklmnopqrstuvwx', 'abcdefghijklmnopqrstuvwxy', 'abcdefghijklmnopqrstuvwxyz']) == "abcdefghijklmnopqrstuvwxyz"
    assert candidate(words = ['xy', 'xyz', 'xyza', 'xyzab', 'xyzabc', 'xyzabcd', 'xyzabcde', 'xyzabcdef', 'xyzabcdefg', 'xyzabcdefgh', 'xyzabcdefghi', 'xyzabcdefghij', 'xyzabcdefghijk', 'xyzabcdefghijkl', 'xyzabcdefghijklm', 'xyzabcdefghijklmn', 'xyzabcdefghijklmno', 'xyzabcdefghijklmnop', 'xyzabcdefghijklmnopq', 'xyzabcdefghijklmnopqr', 'xyzabcdefghijklmnopqrs', 'xyzabcdefghijklmnopqrst', 'xyzabcdefghijklmnopqrstu', 'xyzabcdefghijklmnopqrstuv', 'xyzabcdefghijklmnopqrstuvw', 'xyzabcdefghijklmnopqrstuvwx', 'xyzabcdefghijklmnopqrstuvwxy', 'xyzabcdefghijklmnopqrstuvwxyz']) == ""
    assert candidate(words = ['z', 'za', 'zap', 'zapz', 'zapzo', 'zapzom', 'zapzomp', 'zapzompe', 'zapzompel', 'zapzompels', 'zapzompelsz', 'zapzompelsza', 'zapzompelszap', 'zapzompelszapz', 'zapzompelszapzo', 'zapzompelszapzom', 'zapzompelszapzomp', 'zapzompelszapzompe', 'zapzompelszapzompel', 'zapzompelszapzompels']) == "zapzompelszapzompels"
    assert candidate(words = ['m', 'ma', 'mak', 'maki', 'makis', 'makisu', 'makisug', 'makisugi', 'makisugis', 'makisugisu', 'makisugisub']) == "makisugisub"
    assert candidate(words = ['t', 'te', 'tes', 'test', 'testi', 'testin', 'testing', 'testingg', 'testinggg', 'testingggg', 'testinggggg', 'testingggggr', 'testingggggrr', 'testingggggrrt', 'testingggggrrte', 'testingggggrrtng', 'testingggggrrtnga', 'testingggggrrtngab', 'testingggggrrtngabc', 'testingggggrrtngabcd']) == "testingggggrrte"
    assert candidate(words = ['abcd', 'abc', 'ab', 'a', 'bcde', 'bcd', 'cd', 'c', 'efgh', 'efg', 'ef', 'e', 'fgh', 'fg', 'fh', 'f', 'gh', 'g', 'h']) == "abcd"
    assert candidate(words = ['a', 'ab', 'abc', 'abcd', 'abcde', 'abcdef', 'abcdefg', 'abcdefgh', 'abcdefghi', 'abcdefghij', 'abcdefghijk', 'abcdefghijkl', 'abcdefghijklm', 'abcdefghijklmn', 'abcdefghijklmnop']) == "abcdefghijklmn"
    assert candidate(words = ['tree', 'trees', 'treestand', 'treestands', 'treestandings', 'treestanded', 'treestanding']) == ""
    assert candidate(words = ['ant', 'ants', 'antacid', 'antacids', 'antacidic', 'antacidness', 'antacidity']) == ""
    assert candidate(words = ['abcd', 'abc', 'ab', 'a', 'abcde', 'abcdef', 'abcdefg', 'abcdefgh', 'abcdefghi', 'abcdefghij']) == "abcdefghij"
    assert candidate(words = ['f', 'fa', 'fan', 'fant', 'fanta', 'fantas', 'fantasi', 'fantasia', 'fantasiax', 'fantasiaxe', 'fantasiaxen', 'fantasiaxend', 'fantasiaxendr', 'fantasiaxendri', 'fantasiaxendrin', 'fantasiaxendrina', 'fantasiaxendrinat', 'fantasiaxendrinata', 'fantasiaxendrinatav']) == "fantasiaxendrinatav"
    assert candidate(words = ['cat', 'cats', 'catsd', 'catsdo', 'catsdom', 'catsdomi', 'catsdomin', 'catsdomina', 'catsdominat', 'catsdominato', 'catsdominatoi', 'catsdominatore']) == ""
    assert candidate(words = ['c', 'co', 'cod', 'code', 'codin', 'coding', 'codings', 'codingsh', 'codingshe', 'codingshel', 'codingshell', 'codingshellp', 'codingshellpr', 'codingshellpro', 'codingshellprog', 'codingshellprogr', 'codingshellprogra', 'codingshellprogram']) == "code"
    assert candidate(words = ['elephant', 'elepha', 'eleph', 'elep', 'ele', 'el', 'e', 'elephanti', 'elephantin', 'elephanting', 'elephantings', 'elephantingsk', 'elephantingski', 'elephantingskip', 'elephantingskipp', 'elephantingskippu', 'elephantingskippus', 'elephantingskippusk', 'elephantingskippuske', 'elephantingskippuskel', 'elephantingskippuskell']) == "elepha"
    assert candidate(words = ['dog', 'dogs', 'dogss', 'dogsss', 'dogssss', 'dogsssss', 'dogssssss', 'dogsssssss', 'dogssssssss', 'dogsssssssss', 'dogssssssssss', 'dogsssssssssss', 'dogssssssssssss', 'dogsssssssssssss', 'dogssssssssssssss', 'dogsssssssssssssss', 'dogssssssssssssssss']) == ""
    assert candidate(words = ['p', 'pi', 'pip', 'pipe', 'piper', 'pipers', 'pipersp', 'piperspi', 'piperspip', 'piperspipe', 'piperspiper', 'piperspipers', 'piperspipersp', 'piperspiperspi', 'piperspiperspip', 'piperspiperspipe', 'piperspiperspiper']) == "piperspiperspiper"
    assert candidate(words = ['g', 'go', 'goo', 'good', 'goode', 'gooden', 'goodenc', 'goodence', 'goodences', 'goodencese', 'goodenceses', 'goodencesest', 'goodencesests', 'goodencesestsa', 'goodencesestsan', 'goodencesestsanl', 'goodencesestsanld', 'goodencesestsanlds', 'goodencesestsanldso', 'goodencesestsanldsom', 'goodencesestsanldsome', 'goodencesestsanldsomee']) == "goodencesestsanldsomee"
    assert candidate(words = ['p', 'pr', 'pro', 'prob', 'probl', 'proble', 'problej', 'problem', 'problemj', 'problemjo', 'problemjos', 'problemjosk', 'problemjoske', 'problemjoskel', 'problemjoskell', 'problemjoskello', 'problemjoskellov']) == "problemjoskellov"
    assert candidate(words = ['m', 'mo', 'mon', 'mond', 'monde', 'mondy', 'monday']) == "monde"
    assert candidate(words = ['g', 'go', 'goo', 'good', 'gooda', 'goodas', 'goodass', 'goodasses']) == "goodass"
    assert candidate(words = ['f', 'fa', 'fan', 'fanc', 'fancy', 'fancye', 'fancyer', 'fanciest', 'fanciests', 'fanciestsh', 'fanciestsha', 'fanciestshap', 'fanciestshape', 'fanciestshaped']) == "fancyer"
    assert candidate(words = ['xyz', 'xy', 'x', 'abcd', 'abc', 'ab', 'a', 'uvw', 'uv', 'u', 'abcdx', 'abcdxy']) == "abcdxy"
    assert candidate(words = ['zebra', 'ze', 'z', 'elephant', 'ele', 'elep', 'eleph', 'elepha', 'elephan', 'elephantt', 'elephantte', 'elephantter', 'elephantters', 'elephantterst', 'elephanttest']) == "ze"
    assert candidate(words = ['z', 'zi', 'zim', 'zimb', 'zimba', 'zimbab', 'zimbaba', 'zimbabw', 'zimbabwe']) == "zimbabwe"
    assert candidate(words = ['a', 'b', 'ab', 'abc', 'abcd', 'abcde', 'abcdef', 'abcdefg', 'abcdefgh']) == "abcdefgh"
    assert candidate(words = ['apple', 'apples', 'appl', 'appli', 'applin', 'applins', 'applinsi', 'applinsin', 'applinsins']) == ""
    assert candidate(words = ['fish', 'fishes', 'fishbowl', 'fishbowls', 'fishbowlful', 'fishbowlsful', 'fishbowlsfully']) == ""
    assert candidate(words = ['dog', 'dogs', 'dogwood', 'dogwoods', 'dogwooded', 'dogwooding', 'dogwoodlands', 'dogwoodedness']) == ""
    assert candidate(words = ['o', 'ow', 'owl', 'owls', 'owlsa', 'owlsap', 'owlsapo', 'owlsapos', 'owlsaposi', 'owlsaposin', 'owlsaposint', 'owlsaposinte', 'owlsaposinter', 'owlsaposintera', 'owlsaposinteran', 'owlsaposinteranc', 'owlsaposinterance']) == "owlsaposinterance"
    assert candidate(words = ['c', 'ca', 'cat', 'catt', 'catch', 'catchi', 'catchin', 'catching', 'catchings', 'catchinga', 'catchingal', 'catchingall']) == "catt"
    assert candidate(words = ['y', 'yi', 'yin', 'yiny', 'yinyu', 'yinyur', 'yinyurg', 'yinyurge', 'yinyurges', 'yinyurgese', 'yinyurgesev', 'yinyurgeseve', 'yinyurgeseven', 'yinyurgesevenv', 'yinyurgesevenve', 'yinyurgesevenver', 'yinyurgesevenvers', 'yinyurgesevenversi', 'yinyurgesevenversio', 'yinyurgesevenversioo', 'yinyurgesevenversioon']) == "yinyurgesevenversioon"
    assert candidate(words = ['w', 'wi', 'win', 'wind', 'windy', 'windye', 'windyed', 'windyest']) == "windyed"
    assert candidate(words = ['penguin', 'pengui', 'pengu', 'peng', 'pen', 'pe', 'p', 'penguinl', 'penguinli', 'penguinlin', 'penguinling', 'penguinlingo', 'penguinlingon', 'penguinlingons', 'penguinlingonso', 'penguinlingonsom', 'penguinlingsome', 'penguinlingsomeo', 'penguinlingsomeon', 'penguinlingsomeone']) == "penguinlingonsom"
    assert candidate(words = ['x', 'xu', 'xur', 'xurn', 'xurna', 'xurnam', 'xurname', 'xurnames']) == "xurnames"
    assert candidate(words = ['x', 'xy', 'xyz', 'xyza', 'xyzab', 'xyzabc', 'xyzabcd', 'xyzabcde', 'xyzabcdef', 'xyzabcdefg']) == "xyzabcdefg"
    assert candidate(words = ['p', 'pi', 'pin', 'pine', 'pinea', 'pineap', 'pineapp', 'pineappl', 'pineapple']) == "pineapple"
    assert candidate(words = ['z', 'zo', 'zoo', 'zoog', 'zoogl', 'zoogly', 'zooglyz', 'zooglyze', 'zooglyzer', 'zooglyzers', 'zooglyzersa', 'zooglyzersam', 'zooglyzersami', 'zooglyzersamie', 'zooglyzersamiel', 'zooglyzersamielo', 'zooglyzersamielow', 'zooglyzersamielowt', 'zooglyzersamielowth', 'zooglyzersamielowthi', 'zooglyzersamielowthil', 'zooglyzersamielowthill', 'zooglyzersamielowthilly', 'zooglyzersamielowthillye', 'zooglyzersamielowthillyen', 'zooglyzersamielowthillyenz']) == "zooglyzersamielowthillyenz"
    assert candidate(words = ['x', 'xy', 'xyz', 'xyza', 'xyzab', 'xyzabc', 'xyzabcd', 'xyzabce', 'xyzabcef', 'xyzabcdef', 'xyzabcdefg']) == "xyzabcef"
    assert candidate(words = ['p', 'pi', 'pip', 'pipe', 'piper', 'pipers', 'piperso', 'pipersom', 'pipersome', 'pipersomeo', 'pipersomeon', 'pipersomeone']) == "pipersomeone"
    assert candidate(words = ['panda', 'pan', 'panther', 'panthe', 'panthen', 'pantheon', 'pand', 'pande', 'pander', 'pandeo', 'pando', 'pandor', 'pandora']) == ""
    assert candidate(words = ['apple', 'appl', 'app', 'ap', 'a', 'banana', 'banan', 'bananas', 'bananash', 'bananasha', 'bananashan', 'bananashand', 'bananashandg', 'bananashandgo', 'bananashandgon', 'bananashandgona']) == "apple"
    assert candidate(words = ['zebra', 'zeb', 'ze', 'z', 'zebras', 'zebrass', 'zebrasst', 'zebrassta', 'zebrasstak', 'zebrasstake', 'zebrasstaken', 'zebrasstakeno', 'zebrasstakenon', 'zebrasstakenone']) == "zeb"
    assert candidate(words = ['cat', 'cats', 'catsd', 'catsdo', 'catsdog', 'catsdogw', 'catsdogwa', 'catsdogwal', 'catsdogwalk']) == ""
    assert candidate(words = ['a', 'b', 'c', 'ab', 'bc', 'abc', 'abcd', 'abcde', 'abcdef', 'abcdefg', 'abcdefgh', 'abcdefghi', 'abcdefghij', 'abcdefghijk', 'abcdefghijkl', 'abcdefghijklm', 'abcdefghijklmn']) == "abcdefghijklmn"
    assert candidate(words = ['qwerty', 'q', 'qw', 'qwe', 'qwer', 'qwert', 'qwertz', 'qwertzx', 'qwertzxy', 'qwertzxya', 'qwertzxyab', 'qwertzxyabc']) == "qwertzxyabc"
    assert candidate(words = ['q', 'qu', 'qui', 'quic', 'quick', 'quicke', 'quickly', 'quicklye', 'quicklyev', 'quicklyeve', 'quicklyever', 'quicklyevert', 'quicklyeverth', 'quicklyeverthi', 'quicklyeverthin', 'quicklyeverthing']) == "quicke"
    assert candidate(words = ['dog', 'doge', 'doges', 'dogesh', 'dogeshi', 'dogeshin', 'dogeshing', 'dogeshingz', 'dogeshingze', 'dogeshingzel', 'dogeshingzela', 'dogeshingzelab', 'dogeshingzelabc', 'dogeshingzelabcd']) == ""
    assert candidate(words = ['t', 'te', 'tec', 'tech', 'techc', 'techch', 'techchi', 'techchis', 'techchise', 'techchisel']) == "techchisel"
    assert candidate(words = ['m', 'ma', 'man', 'many', 'manyp', 'manype', 'manypea', 'manypeas', 'manypeaso', 'manypeason', 'manypeasone']) == "manypeasone"
    assert candidate(words = ['c', 'ca', 'cat', 'catt', 'catty', 'cattycorner', 'cattycornered', 'cattycorneredly']) == "catty"
    assert candidate(words = ['a', 'ab', 'abc', 'abcd', 'abcde', 'abcdef', 'abcdefg', 'abcdefgh', 'abcdefghi', 'abcdefghij']) == "abcdefghij"
    assert candidate(words = ['a', 'abc', 'abcd', 'abcde', 'abcdef', 'abcdefg', 'abcdefgh', 'abcdefghi', 'abcdefghij', 'abcdefghijk']) == "a"
    assert candidate(words = ['fly', 'flies', 'flycatcher', 'flycatchers', 'flycatchering', 'flycatchered', 'flycatcherings']) == ""
    assert candidate(words = ['abcdxyz', 'abcdxy', 'abcdx', 'abcd', 'abc', 'ab', 'a', 'bcdxyz', 'bcdxy', 'bcdx', 'bcd', 'bc', 'b', 'cdxyz', 'cdxy', 'cdx', 'cd', 'c', 'dxyz', 'dxy', 'dx', 'd', 'xyz', 'xy', 'x', 'yz', 'y', 'z']) == "abcdxyz"
    assert candidate(words = ['hello', 'hell', 'hel', 'he', 'h', 'hellod', 'hellodo', 'hellodog', 'hellodogg', 'hellodoggo', 'hellodoggos', 'hellodoggosi', 'hellodoggosin', 'hellodoggosine']) == "hellodoggosine"
    assert candidate(words = ['zebra', 'zebras', 'zebrass', 'zebrasss', 'zebrassss', 'zebrasssss', 'zebrassssss', 'zebrasssssss', 'zebrassssssss', 'zebrasssssssss', 'zebrassssssssss']) == ""
    assert candidate(words = ['m', 'mo', 'mon', 'mont', 'monta', 'montan', 'montana', 'montanan', 'montanans', 'montanas', 'montanasm', 'montanasmu', 'montanasmun', 'montanasmunt', 'montanasmunta', 'montanasmuntan', 'montanasmuntana', 'montanasmuntanan', 'montanasmuntanans', 'montanasmuntanas']) == "montanasmuntanans"
    assert candidate(words = ['x', 'y', 'xy', 'xyz', 'xzz', 'xz', 'yxy', 'yzy', 'yy', 'yx', 'yz', 'yzz', 'yyy', 'zzz', 'zz', 'zx', 'zy']) == "xyz"
    assert candidate(words = ['x', 'xy', 'xyz', 'xyza', 'xyzab', 'xyzabc', 'xyzabcd', 'xyzabcde', 'xyzabcdef', 'xyzabcdefg', 'xyzabcdefgh', 'xyzabcdefghi', 'xyzabcdefghij', 'xyzabcdefghijk', 'xyzabcdefghijkl', 'xyzabcdefghijklm', 'xyzabcdefghijklmn', 'xyzabcdefghijklmno', 'xyzabcdefghijklmnop', 'xyzabcdefghijklmnopq']) == "xyzabcdefghijklmnopq"
    assert candidate(words = ['elephant', 'elephants', 'elephantiasis', 'elephantiasises', 'elephantiasissed', 'elephantiasissing']) == ""
    assert candidate(words = ['j', 'jo', 'joh', 'john', 'johnn', 'johnny', 'johnnyo', 'johnnyon', 'johnnyons']) == "johnnyons"
    assert candidate(words = ['qwerty', 'qwert', 'qwertyu', 'qwer', 'qwertyui', 'qwertu', 'qwertyuiop', 'qwertyuiopa', 'qwertyuiopab', 'qwertyuiopabc', 'qwertyuiopabcd', 'qwertyuiopabcde', 'qwertyuiopabcdef', 'qwertyuiopabcdefg', 'qwertyuiopabcdefgh', 'qwertyuiopabcdefghi', 'qwertyuiopabcdefghij', 'qwertyuiopabcdefghijk', 'qwertyuiopabcdefghijkl', 'qwertyuiopabcdefghijklm']) == ""
    assert candidate(words = ['m', 'ma', 'maa', 'maaa', 'maaaa', 'maaaaa', 'maaaaaa', 'maaaaaaa', 'maaaaaaaa', 'maaaaaaaaa', 'maaaaaaaaaa', 'maaaaaaaaaaa', 'maaaaaaaaaaaa', 'maaaaaaaaaaaaa', 'maaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa']) == "maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    assert candidate(words = ['t', 'ta', 'tan', 'tang', 'tangi', 'tangib', 'tangibl', 'tangible']) == "tangible"
    assert candidate(words = ['cat', 'bat', 'rat', 'car', 'bar', 'batman', 'batarang']) == ""
    assert candidate(words = ['m', 'ma', 'mak', 'make', 'maker', 'makers', 'makersp', 'makerspa', 'makerspac', 'makerspace', 'makerspacex', 'makerspacexi', 'makerspacexin', 'makerspacexing']) == "makerspacexing"
    assert candidate(words = ['abcd', 'abcde', 'ab', 'a', 'abcdef', 'abcdefg', 'abcdefgh', 'abcdefghi', 'abcdefghij', 'abcdefghijk', 'abcdefghijkl', 'abcdefghijklm', 'abcdefghijklmn', 'abcdefghijklmno']) == "ab"
    assert candidate(words = ['xyz', 'xy', 'x', 'xyza', 'xyzab', 'xyzabc', 'xyzabcd', 'xyzabcde', 'xyzabcdef', 'xyzabcdefg']) == "xyzabcdefg"
    assert candidate(words = ['zebra', 'z', 'ze', 'zee', 'zebraa', 'zebraab', 'zebraabc', 'zebraabcd', 'zebraabcde', 'zebraabcdef']) == "zee"
    assert candidate(words = ['p', 'pa', 'par', 'para', 'paral', 'parale', 'paralel', 'paralell', 'parallel', 'paralleli', 'parallelis', 'parallelism', 'parallelis', 'parallelis', 'parallelism', 'parallelis', 'parallelism', 'parallelism']) == "paralell"
    assert candidate(words = ['hello', 'hell', 'hel', 'he', 'h', 'hero', 'her', 'here', 'herein', 'hereinafter']) == "hello"
    assert candidate(words = ['a', 'aa', 'aaa', 'aaaa', 'aaaaa', 'aab', 'aabba', 'aabbaa', 'aabbaab']) == "aaaaa"
    assert candidate(words = ['zebra', 'zebras', 'zebrafish', 'zebrafinch', 'zebrafinches', 'zebrafinched', 'zebrafinching']) == ""
    assert candidate(words = ['rat', 'rats', 'ratable', 'ratably', 'ratableness', 'ratability', 'ratabilities']) == ""
    assert candidate(words = ['q', 'qu', 'qui', 'quic', 'quick', 'quicks', 'quickse', 'quicksee', 'quickseed', 'quickseeds']) == "quickseeds"
