# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(words = ['dog', 'cat', 'bird', 'fish'],groups = [0, 1, 1, 0]) == ['dog', 'cat', 'fish']
    assert candidate(words = ['x', 'y', 'z'],groups = [0, 1, 0]) == ['x', 'y', 'z']
    assert candidate(words = ['a', 'b', 'c', 'd'],groups = [1, 0, 1, 1]) == ['a', 'b', 'c']
    assert candidate(words = ['e', 'a', 'b'],groups = [0, 0, 1]) == ['e', 'b']
    assert candidate(words = ['one', 'two', 'three'],groups = [1, 1, 0]) == ['one', 'three']
    assert candidate(words = ['apple', 'banana', 'cherry'],groups = [1, 1, 0]) == ['apple', 'cherry']
    assert candidate(words = ['one', 'two', 'three', 'four', 'five'],groups = [1, 0, 1, 0, 1]) == ['one', 'two', 'three', 'four', 'five']
    assert candidate(words = ['cat', 'dog', 'fish', 'bird'],groups = [1, 1, 0, 0]) == ['cat', 'fish']
    assert candidate(words = ['hello', 'world', 'python', 'code'],groups = [0, 1, 0, 1]) == ['hello', 'world', 'python', 'code']
    assert candidate(words = ['dog', 'cat', 'bat', 'rat'],groups = [0, 1, 0, 1]) == ['dog', 'cat', 'bat', 'rat']
    assert candidate(words = ['hello', 'world', 'python', 'code'],groups = [1, 0, 1, 0]) == ['hello', 'world', 'python', 'code']
    assert candidate(words = ['hello', 'world', 'abc', 'def'],groups = [0, 1, 0, 1]) == ['hello', 'world', 'abc', 'def']
    assert candidate(words = ['red', 'blue', 'green', 'yellow'],groups = [0, 1, 0, 1]) == ['red', 'blue', 'green', 'yellow']
    assert candidate(words = ['umbrella', 'tornado', 'rainbow', 'ocean', 'mountain', 'lake', 'island', 'forest', 'desert', 'canyon', 'volcano', 'glacier', 'river'],groups = [0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0]) == ['umbrella', 'tornado', 'ocean', 'lake', 'forest', 'canyon', 'glacier']
    assert candidate(words = ['sun', 'moon', 'star', 'planet', 'galaxy'],groups = [0, 1, 0, 1, 0]) == ['sun', 'moon', 'star', 'planet', 'galaxy']
    assert candidate(words = ['x', 'y', 'z', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w'],groups = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) == ['x', 'y', 'z', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w']
    assert candidate(words = ['ocean', 'sea', 'lake', 'river', 'stream', 'creek', 'pond'],groups = [0, 1, 0, 1, 0, 1, 0]) == ['ocean', 'sea', 'lake', 'river', 'stream', 'creek', 'pond']
    assert candidate(words = ['sun', 'moon', 'star', 'planet', 'galaxy', 'universe', 'constellation', 'comet', 'asteroid', 'supernova'],groups = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == ['sun', 'moon', 'star', 'planet', 'galaxy', 'universe', 'constellation', 'comet', 'asteroid', 'supernova']
    assert candidate(words = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
    assert candidate(words = ['sun', 'moon', 'star', 'comet', 'planet', 'galaxy', 'universe'],groups = [0, 1, 1, 0, 1, 0, 1]) == ['sun', 'moon', 'comet', 'planet', 'galaxy', 'universe']
    assert candidate(words = ['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta'],groups = [0, 1, 1, 0, 0, 1]) == ['alpha', 'beta', 'delta', 'zeta']
    assert candidate(words = ['quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog'],groups = [1, 0, 1, 0, 1, 0, 1, 0]) == ['quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']
    assert candidate(words = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't']
    assert candidate(words = ['flower', 'tree', 'bush', 'shrub', 'vine', 'grass', 'moss'],groups = [0, 1, 0, 1, 0, 1, 0]) == ['flower', 'tree', 'bush', 'shrub', 'vine', 'grass', 'moss']
    assert candidate(words = ['sun', 'moon', 'star', 'planet', 'comet', 'asteroid', 'galaxy', 'universe'],groups = [0, 1, 0, 1, 0, 1, 0, 1]) == ['sun', 'moon', 'star', 'planet', 'comet', 'asteroid', 'galaxy', 'universe']
    assert candidate(words = ['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta'],groups = [1, 1, 0, 0, 1, 1, 0, 0]) == ['alpha', 'gamma', 'epsilon', 'eta']
    assert candidate(words = ['sun', 'moon', 'star', 'planet', 'galaxy', 'universe', 'constellation', 'asteroid'],groups = [0, 1, 0, 1, 0, 1, 0, 1]) == ['sun', 'moon', 'star', 'planet', 'galaxy', 'universe', 'constellation', 'asteroid']
    assert candidate(words = ['orange', 'lemon', 'lime', 'mango', 'papaya', 'guava', 'kiwi'],groups = [1, 0, 0, 1, 1, 0, 1]) == ['orange', 'lemon', 'mango', 'guava', 'kiwi']
    assert candidate(words = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve'],groups = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve']
    assert candidate(words = ['car', 'truck', 'bike', 'motorcycle', 'bicycle', 'scooter', 'skateboard', 'longboard', 'tricycle'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1]) == ['car', 'truck', 'bike', 'motorcycle', 'bicycle', 'scooter', 'skateboard', 'longboard', 'tricycle']
    assert candidate(words = ['ocean', 'sea', 'lake', 'river', 'creek', 'stream', 'pond'],groups = [1, 0, 1, 0, 1, 0, 1]) == ['ocean', 'sea', 'lake', 'river', 'creek', 'stream', 'pond']
    assert candidate(words = ['zebra', 'yak', 'xylophone', 'wolf', 'vulture', 'toucan', 'snake', 'raven', 'quetzal', 'parrot'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) == ['zebra', 'yak', 'xylophone', 'wolf', 'vulture', 'toucan', 'snake', 'raven', 'quetzal', 'parrot']
    assert candidate(words = ['zebra', 'elephant', 'giraffe', 'hippo', 'rhino', 'lion', 'tiger', 'bear'],groups = [0, 0, 1, 1, 0, 0, 1, 1]) == ['zebra', 'giraffe', 'rhino', 'tiger']
    assert candidate(words = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o']
    assert candidate(words = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet'],groups = [0, 1, 1, 0, 0, 1, 1]) == ['red', 'orange', 'green', 'indigo']
    assert candidate(words = ['apple', 'banana', 'cherry', 'date', 'elderberry', 'fig', 'grape'],groups = [1, 0, 1, 0, 1, 0, 1]) == ['apple', 'banana', 'cherry', 'date', 'elderberry', 'fig', 'grape']
    assert candidate(words = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],groups = [1, 0, 1, 0, 1, 0, 1]) == ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']
    assert candidate(words = ['x', 'y', 'z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == ['x', 'y', 'z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v']
    assert candidate(words = ['puppy', 'kitten', 'fish', 'bird', 'dog', 'cat', 'hamster', 'gerbil', 'rabbit'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1]) == ['puppy', 'kitten', 'fish', 'bird', 'dog', 'cat', 'hamster', 'gerbil', 'rabbit']
    assert candidate(words = ['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta', 'iota', 'kappa', 'lambda'],groups = [1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1]) == ['alpha', 'beta', 'delta', 'zeta', 'eta', 'theta', 'iota', 'kappa', 'lambda']
    assert candidate(words = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
    assert candidate(words = ['ocean', 'sea', 'lake', 'river', 'pond', 'brook', 'creek', 'stream'],groups = [0, 1, 1, 0, 0, 1, 0, 0]) == ['ocean', 'sea', 'river', 'brook', 'creek']
    assert candidate(words = ['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta', 'iota', 'kappa'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) == ['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta', 'iota', 'kappa']
    assert candidate(words = ['cat', 'dog', 'bird', 'fish', 'ant', 'bee', 'moth', 'fly', 'antelope', 'giraffe'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) == ['cat', 'dog', 'bird', 'fish', 'ant', 'bee', 'moth', 'fly', 'antelope', 'giraffe']
    assert candidate(words = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet'],groups = [0, 1, 0, 1, 0, 1, 0]) == ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet']
    assert candidate(words = ['car', 'bike', 'truck', 'bus', 'motorcycle', 'scooter', 'bicycle'],groups = [1, 0, 0, 1, 1, 0, 0]) == ['car', 'bike', 'bus', 'scooter']
    assert candidate(words = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) == ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve']
    assert candidate(words = ['orange', 'lemon', 'lime', 'grapefruit', 'kiwi', 'mango', 'papaya', 'guava', 'dragonfruit'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1]) == ['orange', 'lemon', 'lime', 'grapefruit', 'kiwi', 'mango', 'papaya', 'guava', 'dragonfruit']
    assert candidate(words = ['red', 'green', 'blue', 'yellow', 'purple', 'cyan', 'magenta', 'black', 'white'],groups = [0, 1, 0, 1, 0, 1, 0, 1, 0]) == ['red', 'green', 'blue', 'yellow', 'purple', 'cyan', 'magenta', 'black', 'white']
    assert candidate(words = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen']
    assert candidate(words = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten'],groups = [0, 0, 1, 1, 0, 0, 1, 1, 0, 0]) == ['one', 'three', 'five', 'seven', 'nine']
    assert candidate(words = ['cat', 'dog', 'rat', 'bat', 'owl', 'fox', 'wolf', 'bear'],groups = [0, 1, 0, 1, 0, 1, 0, 1]) == ['cat', 'dog', 'rat', 'bat', 'owl', 'fox', 'wolf', 'bear']
    assert candidate(words = ['sun', 'moon', 'star', 'planet', 'comet', 'asteroid', 'galaxy', 'universe', 'nebula', 'blackhole'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) == ['sun', 'moon', 'star', 'planet', 'comet', 'asteroid', 'galaxy', 'universe', 'nebula', 'blackhole']
    assert candidate(words = ['zebra', 'giraffe', 'elephant', 'lion', 'tiger', 'bear', 'wolf', 'hippo'],groups = [0, 1, 0, 1, 0, 1, 0, 1]) == ['zebra', 'giraffe', 'elephant', 'lion', 'tiger', 'bear', 'wolf', 'hippo']
    assert candidate(words = ['x', 'y', 'z', 'w', 'v', 'u', 't', 's', 'r', 'q'],groups = [1, 1, 0, 1, 0, 0, 1, 0, 1, 1]) == ['x', 'z', 'w', 'v', 't', 's', 'r']
    assert candidate(words = ['a', 'bb', 'ccc', 'dddd', 'eeeee', 'ffffff', 'ggggggg', 'hhhhhhhh', 'iiiiiiiii', 'jjjjjjjjjj'],groups = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == ['a', 'bb', 'ccc', 'dddd', 'eeeee', 'ffffff', 'ggggggg', 'hhhhhhhh', 'iiiiiiiii', 'jjjjjjjjjj']
    assert candidate(words = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet'],groups = [1, 1, 0, 1, 0, 1, 0]) == ['red', 'yellow', 'green', 'blue', 'indigo', 'violet']
    assert candidate(words = ['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta'],groups = [0, 1, 0, 1, 0, 1, 0, 1]) == ['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta']
    assert candidate(words = ['sun', 'moon', 'star', 'planet', 'comet', 'asteroid', 'galaxy'],groups = [0, 1, 1, 0, 1, 0, 1]) == ['sun', 'moon', 'planet', 'comet', 'asteroid', 'galaxy']
    assert candidate(words = ['red', 'blue', 'green', 'yellow', 'purple', 'pink', 'orange', 'black', 'white', 'gray', 'brown'],groups = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) == ['red', 'blue', 'green', 'yellow', 'purple', 'pink', 'orange', 'black', 'white', 'gray', 'brown']
    assert candidate(words = ['zebra', 'giraffe', 'elephant', 'lion', 'tiger', 'bear', 'wolf', 'fox'],groups = [0, 1, 0, 1, 0, 1, 0, 1]) == ['zebra', 'giraffe', 'elephant', 'lion', 'tiger', 'bear', 'wolf', 'fox']
    assert candidate(words = ['apple', 'banana', 'cherry', 'date', 'elderberry', 'fig', 'grape'],groups = [0, 1, 0, 1, 0, 1, 0]) == ['apple', 'banana', 'cherry', 'date', 'elderberry', 'fig', 'grape']
    assert candidate(words = ['sunrise', 'sunset', 'dawn', 'dusk', 'midnight', 'noon', 'evening', 'morning'],groups = [1, 0, 1, 0, 1, 0, 1, 0]) == ['sunrise', 'sunset', 'dawn', 'dusk', 'midnight', 'noon', 'evening', 'morning']
    assert candidate(words = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen'],groups = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) == ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen']
    assert candidate(words = ['sun', 'moon', 'star', 'planet', 'comet', 'asteroid', 'nebula'],groups = [1, 0, 1, 0, 1, 0, 1]) == ['sun', 'moon', 'star', 'planet', 'comet', 'asteroid', 'nebula']
    assert candidate(words = ['piano', 'guitar', 'violin', 'drums', 'flute', 'trumpet', 'saxophone', 'balalaika'],groups = [0, 1, 0, 1, 0, 1, 0, 1]) == ['piano', 'guitar', 'violin', 'drums', 'flute', 'trumpet', 'saxophone', 'balalaika']
    assert candidate(words = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet'],groups = [1, 1, 0, 0, 1, 1, 0]) == ['red', 'yellow', 'blue', 'violet']
    assert candidate(words = ['ocean', 'river', 'lake', 'stream', 'pond', 'fountain', 'basin'],groups = [1, 0, 1, 0, 1, 0, 1]) == ['ocean', 'river', 'lake', 'stream', 'pond', 'fountain', 'basin']
    assert candidate(words = ['zebra', 'giraffe', 'elephant', 'tiger', 'lion', 'bear', 'wolf', 'fox', 'coyote', 'lynx'],groups = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == ['zebra', 'giraffe', 'elephant', 'tiger', 'lion', 'bear', 'wolf', 'fox', 'coyote', 'lynx']
    assert candidate(words = ['zebra', 'lion', 'tiger', 'giraffe', 'elephant', 'rhino', 'hippo', 'monkey'],groups = [0, 1, 1, 0, 0, 1, 1, 0]) == ['zebra', 'lion', 'giraffe', 'rhino', 'monkey']
    assert candidate(words = ['mountain', 'hill', 'peak', 'valley', 'canyon', 'cliff', 'ridge'],groups = [1, 0, 1, 0, 1, 0, 1]) == ['mountain', 'hill', 'peak', 'valley', 'canyon', 'cliff', 'ridge']
    assert candidate(words = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'],groups = [1, 0, 0, 1, 1, 0, 0, 1, 1, 0]) == ['a', 'b', 'd', 'f', 'h', 'j']
    assert candidate(words = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet', 'ultraviolet'],groups = [1, 0, 1, 0, 1, 0, 1, 0]) == ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet', 'ultraviolet']
    assert candidate(words = ['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta', 'iota', 'kappa'],groups = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == ['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta', 'iota', 'kappa']
    assert candidate(words = ['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta', 'iota', 'kappa', 'lambda'],groups = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) == ['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta', 'iota', 'kappa', 'lambda']
    assert candidate(words = ['cat', 'dog', 'fish', 'bird', 'cat', 'dog', 'fish', 'bird', 'cat', 'dog', 'fish', 'bird', 'cat', 'dog', 'fish', 'bird', 'cat', 'dog', 'fish', 'bird'],groups = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == ['cat', 'dog', 'fish', 'bird', 'cat', 'dog', 'fish', 'bird', 'cat', 'dog', 'fish', 'bird', 'cat', 'dog', 'fish', 'bird', 'cat', 'dog', 'fish', 'bird']
    assert candidate(words = ['sushi', 'pizza', 'burger', 'steak', 'salad', 'pasta', 'taco', 'burrito', 'sandwich', 'omelette'],groups = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == ['sushi', 'pizza', 'burger', 'steak', 'salad', 'pasta', 'taco', 'burrito', 'sandwich', 'omelette']
    assert candidate(words = ['hello', 'world', 'python', 'programming', 'is', 'fun'],groups = [0, 1, 1, 0, 0, 1]) == ['hello', 'world', 'programming', 'fun']
    assert candidate(words = ['zebra', 'giraffe', 'elephant', 'lion', 'tiger', 'bear', 'monkey'],groups = [0, 1, 0, 1, 0, 1, 0]) == ['zebra', 'giraffe', 'elephant', 'lion', 'tiger', 'bear', 'monkey']
    assert candidate(words = ['zebra', 'giraffe', 'elephant', 'tiger', 'lion', 'bear', 'panda', 'rhino', 'hippo', 'flamingo'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) == ['zebra', 'giraffe', 'elephant', 'tiger', 'lion', 'bear', 'panda', 'rhino', 'hippo', 'flamingo']
    assert candidate(words = ['hello', 'world', 'python', 'programming', 'is', 'fun', 'and', 'challenging'],groups = [0, 1, 1, 0, 1, 0, 1, 0]) == ['hello', 'world', 'programming', 'is', 'fun', 'and', 'challenging']
    assert candidate(words = ['ant', 'bee', 'cow', 'dog', 'elephant', 'frog', 'goat', 'horse', 'iguana', 'jaguar'],groups = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == ['ant', 'bee', 'cow', 'dog', 'elephant', 'frog', 'goat', 'horse', 'iguana', 'jaguar']
    assert candidate(words = ['zebra', 'elephant', 'tiger', 'lion', 'giraffe', 'rhino'],groups = [1, 0, 1, 0, 1, 0]) == ['zebra', 'elephant', 'tiger', 'lion', 'giraffe', 'rhino']
    assert candidate(words = ['red', 'blue', 'green', 'yellow', 'red', 'blue', 'green', 'yellow', 'red', 'blue', 'green', 'yellow', 'red', 'blue', 'green'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == ['red', 'blue', 'green', 'yellow', 'red', 'blue', 'green', 'yellow', 'red', 'blue', 'green', 'yellow', 'red', 'blue', 'green']
    assert candidate(words = ['orange', 'lemon', 'lime', 'mango', 'kiwi', 'papaya', 'guava', 'melon'],groups = [0, 1, 0, 1, 0, 1, 0, 1]) == ['orange', 'lemon', 'lime', 'mango', 'kiwi', 'papaya', 'guava', 'melon']
    assert candidate(words = ['ocean', 'river', 'lake', 'pond', 'stream', 'creek', 'bay', 'gulf'],groups = [1, 0, 1, 0, 1, 0, 1, 0]) == ['ocean', 'river', 'lake', 'pond', 'stream', 'creek', 'bay', 'gulf']
    assert candidate(words = ['x', 'y', 'z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) == ['x', 'y', 'z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']
    assert candidate(words = ['panda', 'koala', 'kangaroo', 'polarbear', 'dolphin', 'seal', 'walrus'],groups = [0, 1, 0, 1, 0, 1, 0]) == ['panda', 'koala', 'kangaroo', 'polarbear', 'dolphin', 'seal', 'walrus']
    assert candidate(words = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],groups = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
    assert candidate(words = ['ant', 'bee', 'ant', 'bee', 'ant', 'bee', 'ant', 'bee', 'ant', 'bee', 'ant', 'bee'],groups = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == ['ant', 'bee', 'ant', 'bee', 'ant', 'bee', 'ant', 'bee', 'ant', 'bee', 'ant', 'bee']
    assert candidate(words = ['sun', 'moon', 'star', 'planet', 'comet', 'asteroid', 'galaxy'],groups = [1, 0, 1, 0, 1, 0, 1]) == ['sun', 'moon', 'star', 'planet', 'comet', 'asteroid', 'galaxy']
    assert candidate(words = ['aardvark', 'beaver', 'capybara', 'dugong', 'elephant', 'flamingo', 'giraffe', 'hippopotamus', 'iguana'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1]) == ['aardvark', 'beaver', 'capybara', 'dugong', 'elephant', 'flamingo', 'giraffe', 'hippopotamus', 'iguana']
    assert candidate(words = ['car', 'bike', 'plane', 'train', 'boat', 'ship', 'bus'],groups = [1, 0, 1, 0, 1, 0, 1]) == ['car', 'bike', 'plane', 'train', 'boat', 'ship', 'bus']
    assert candidate(words = ['ocean', 'river', 'lake', 'pond', 'waterfall', 'creek', 'stream'],groups = [0, 1, 0, 1, 0, 1, 0]) == ['ocean', 'river', 'lake', 'pond', 'waterfall', 'creek', 'stream']
    assert candidate(words = ['north', 'south', 'east', 'west', 'northeast', 'northwest', 'southeast', 'southwest'],groups = [1, 0, 1, 0, 1, 0, 1, 0]) == ['north', 'south', 'east', 'west', 'northeast', 'northwest', 'southeast', 'southwest']
    assert candidate(words = ['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta'],groups = [0, 1, 0, 1, 0, 1]) == ['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta']
    assert candidate(words = ['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta', 'iota', 'kappa', 'lambda', 'mu', 'nu', 'xi', 'omicron', 'pi', 'rho', 'sigma', 'tau', 'upsilon', 'phi', 'chi', 'psi', 'omega'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) == ['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta', 'iota', 'kappa', 'lambda', 'mu', 'nu', 'xi', 'omicron', 'pi', 'rho', 'sigma', 'tau', 'upsilon', 'phi', 'chi', 'psi', 'omega']
    assert candidate(words = ['x', 'y', 'z', 'w', 'v', 'u', 't', 's', 'r', 'q'],groups = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) == ['x', 'y', 'z', 'w', 'v', 'u', 't', 's', 'r', 'q']
    assert candidate(words = ['one', 'two', 'three', 'four'],groups = [0, 1, 1, 0]) == ['one', 'two', 'four']
    assert candidate(words = ['red', 'blue', 'green', 'yellow'],groups = [0, 0, 1, 1]) == ['red', 'green']
    assert candidate(words = ['red', 'green', 'blue'],groups = [1, 1, 0]) == ['red', 'blue']
    assert candidate(words = ['x', 'y', 'z'],groups = [0, 0, 0]) == ['x']
    assert candidate(words = ['dog', 'cat', 'bird', 'fish'],groups = [1, 0, 1, 0]) == ['dog', 'cat', 'bird', 'fish']
    assert candidate(words = ['hello', 'world', 'python'],groups = [0, 1, 0]) == ['hello', 'world', 'python']
    assert candidate(words = ['zebra', 'lion', 'tiger', 'bear'],groups = [1, 0, 1, 0]) == ['zebra', 'lion', 'tiger', 'bear']
    assert candidate(words = ['a', 'b'],groups = [0, 1]) == ['a', 'b']
    assert candidate(words = ['apple', 'banana', 'cherry'],groups = [0, 1, 0]) == ['apple', 'banana', 'cherry']
    assert candidate(words = ['dog', 'cat', 'mouse', 'elephant'],groups = [1, 0, 1, 0]) == ['dog', 'cat', 'mouse', 'elephant']
    assert candidate(words = ['x', 'y', 'z', 'w', 'v'],groups = [0, 1, 0, 1, 0]) == ['x', 'y', 'z', 'w', 'v']
    assert candidate(words = ['hello', 'world'],groups = [0, 0]) == ['hello']
    assert candidate(words = ['a', 'b', 'c', 'd', 'e'],groups = [0, 1, 0, 1, 0]) == ['a', 'b', 'c', 'd', 'e']
    assert candidate(words = ['apple', 'banana', 'cherry', 'date'],groups = [1, 1, 0, 0]) == ['apple', 'cherry']
    assert candidate(words = ['a', 'b', 'a', 'b', 'a', 'b'],groups = [0, 1, 0, 1, 0, 1]) == ['a', 'b', 'a', 'b', 'a', 'b']
    assert candidate(words = ['one', 'two', 'three', 'four'],groups = [1, 1, 1, 0]) == ['one', 'four']
    assert candidate(words = ['dog', 'cat', 'bird', 'fish'],groups = [1, 1, 0, 0]) == ['dog', 'bird']
    assert candidate(words = ['sun', 'moon', 'star', 'planet'],groups = [0, 1, 0, 1]) == ['sun', 'moon', 'star', 'planet']
    assert candidate(words = ['up', 'down', 'left', 'right'],groups = [1, 0, 1, 0]) == ['up', 'down', 'left', 'right']
    assert candidate(words = ['apple', 'banana', 'cherry'],groups = [0, 1, 0]) == ['apple', 'banana', 'cherry']
    assert candidate(words = ['red', 'blue', 'green', 'yellow', 'black'],groups = [0, 0, 1, 1, 0]) == ['red', 'green', 'black']
    assert candidate(words = ['up', 'down', 'left', 'right'],groups = [0, 1, 0, 1]) == ['up', 'down', 'left', 'right']
    assert candidate(words = ['light', 'dark'],groups = [0, 1]) == ['light', 'dark']
    assert candidate(words = ['a', 'b', 'c', 'd', 'e'],groups = [1, 1, 1, 1, 1]) == ['a']
    assert candidate(words = ['one', 'two', 'three', 'four', 'five', 'six'],groups = [1, 0, 1, 0, 1, 0]) == ['one', 'two', 'three', 'four', 'five', 'six']
    assert candidate(words = ['dog', 'cat', 'mouse'],groups = [1, 0, 1]) == ['dog', 'cat', 'mouse']
    assert candidate(words = ['fast', 'slow', 'big', 'small'],groups = [1, 0, 1, 0]) == ['fast', 'slow', 'big', 'small']
    assert candidate(words = ['red', 'blue', 'green', 'yellow'],groups = [1, 0, 1, 0]) == ['red', 'blue', 'green', 'yellow']
    assert candidate(words = ['alpha', 'beta', 'gamma', 'delta'],groups = [0, 1, 0, 1]) == ['alpha', 'beta', 'gamma', 'delta']
    assert candidate(words = ['red', 'blue', 'green'],groups = [0, 1, 0]) == ['red', 'blue', 'green']
    assert candidate(words = ['one', 'two', 'three', 'four', 'five'],groups = [1, 1, 0, 0, 1]) == ['one', 'three', 'five']
    assert candidate(words = ['one', 'two', 'three'],groups = [1, 1, 1]) == ['one']
    assert candidate(words = ['cat', 'dog', 'mouse'],groups = [0, 0, 1]) == ['cat', 'mouse']
    assert candidate(words = ['apple', 'banana', 'cherry', 'date', 'elderberry'],groups = [1, 0, 1, 0, 1]) == ['apple', 'banana', 'cherry', 'date', 'elderberry']
    assert candidate(words = ['red', 'blue', 'green', 'yellow', 'purple', 'orange'],groups = [1, 0, 1, 0, 1, 0]) == ['red', 'blue', 'green', 'yellow', 'purple', 'orange']
    assert candidate(words = ['x', 'y', 'z'],groups = [0, 0, 0]) == ['x']
    assert candidate(words = ['sun', 'moon', 'star', 'planet'],groups = [0, 1, 1, 0]) == ['sun', 'moon', 'planet']
    assert candidate(words = ['one', 'two', 'three', 'four', 'five'],groups = [1, 0, 1, 0, 1]) == ['one', 'two', 'three', 'four', 'five']
    assert candidate(words = ['hello', 'world', 'foo', 'bar'],groups = [0, 1, 0, 1]) == ['hello', 'world', 'foo', 'bar']
    assert candidate(words = ['red', 'blue', 'green', 'yellow'],groups = [1, 1, 1, 0]) == ['red', 'yellow']
    assert candidate(words = ['sun', 'moon', 'star'],groups = [0, 1, 0]) == ['sun', 'moon', 'star']
    assert candidate(words = ['alpha', 'beta', 'gamma', 'delta'],groups = [1, 0, 1, 0]) == ['alpha', 'beta', 'gamma', 'delta']
    assert candidate(words = ['fast', 'slow', 'high', 'low'],groups = [1, 0, 1, 0]) == ['fast', 'slow', 'high', 'low']
    assert candidate(words = ['sun', 'moon', 'star', 'planet'],groups = [1, 1, 1, 1]) == ['sun']
    assert candidate(words = ['cat', 'dog', 'elephant'],groups = [1, 0, 1]) == ['cat', 'dog', 'elephant']
    assert candidate(words = ['apple', 'banana', 'cherry', 'date'],groups = [0, 1, 0, 1]) == ['apple', 'banana', 'cherry', 'date']
    assert candidate(words = ['red', 'blue', 'green', 'yellow', 'purple'],groups = [0, 1, 0, 1, 0]) == ['red', 'blue', 'green', 'yellow', 'purple']
    assert candidate(words = ['a', 'b', 'c', 'd', 'e'],groups = [1, 0, 1, 0, 1]) == ['a', 'b', 'c', 'd', 'e']
    assert candidate(words = ['dog', 'cat', 'fish', 'bird'],groups = [1, 0, 1, 1]) == ['dog', 'cat', 'fish']
    assert candidate(words = ['dog', 'cat', 'bird'],groups = [0, 0, 1]) == ['dog', 'bird']
    assert candidate(words = ['dog', 'cat', 'fish', 'bird'],groups = [1, 0, 1, 0]) == ['dog', 'cat', 'fish', 'bird']
    assert candidate(words = ['up', 'down', 'left', 'right'],groups = [1, 0, 1, 0]) == ['up', 'down', 'left', 'right']
    assert candidate(words = ['cat', 'dog', 'bird', 'fish'],groups = [0, 1, 0, 1]) == ['cat', 'dog', 'bird', 'fish']
    assert candidate(words = ['dog', 'cat', 'bird', 'fish'],groups = [1, 0, 1, 1]) == ['dog', 'cat', 'bird']
    assert candidate(words = ['red', 'blue', 'green', 'yellow'],groups = [1, 1, 0, 0]) == ['red', 'green']
    assert candidate(words = ['hello', 'world'],groups = [0, 1]) == ['hello', 'world']
    assert candidate(words = ['cat', 'dog', 'elephant', 'fox'],groups = [1, 0, 1, 0]) == ['cat', 'dog', 'elephant', 'fox']
    assert candidate(words = ['red', 'blue', 'green'],groups = [0, 0, 0]) == ['red']
    assert candidate(words = ['cat', 'dog', 'bird'],groups = [0, 1, 0]) == ['cat', 'dog', 'bird']
    assert candidate(words = ['x', 'y', 'z', 'w'],groups = [0, 1, 0, 1]) == ['x', 'y', 'z', 'w']
    assert candidate(words = ['cat', 'dog', 'bird', 'fish'],groups = [1, 0, 1, 0]) == ['cat', 'dog', 'bird', 'fish']
    assert candidate(words = ['sun', 'moon', 'star'],groups = [0, 1, 1]) == ['sun', 'moon']
    assert candidate(words = ['red', 'green', 'blue', 'yellow'],groups = [1, 1, 0, 0]) == ['red', 'blue']
    assert candidate(words = ['sun', 'moon', 'star', 'planet'],groups = [1, 0, 1, 1]) == ['sun', 'moon', 'star']
    assert candidate(words = ['hello', 'world', 'python', 'programming'],groups = [0, 1, 0, 1]) == ['hello', 'world', 'python', 'programming']
    assert candidate(words = ['one', 'two', 'three', 'four', 'five'],groups = [0, 1, 0, 1, 0]) == ['one', 'two', 'three', 'four', 'five']
    assert candidate(words = ['one', 'two', 'three', 'four'],groups = [0, 1, 0, 1]) == ['one', 'two', 'three', 'four']
    assert candidate(words = ['red', 'blue', 'green'],groups = [0, 1, 1]) == ['red', 'blue']
    assert candidate(words = ['red', 'blue', 'green', 'yellow', 'black'],groups = [1, 0, 1, 0, 1]) == ['red', 'blue', 'green', 'yellow', 'black']
    assert candidate(words = ['a', 'b', 'c', 'd', 'e', 'f'],groups = [1, 0, 1, 0, 1, 0]) == ['a', 'b', 'c', 'd', 'e', 'f']
    assert candidate(words = ['cat', 'dog', 'fish', 'bird', 'lizard'],groups = [0, 1, 0, 1, 0]) == ['cat', 'dog', 'fish', 'bird', 'lizard']
    assert candidate(words = ['x', 'y', 'z', 'w'],groups = [1, 0, 1, 0]) == ['x', 'y', 'z', 'w']
    assert candidate(words = ['x', 'y', 'z'],groups = [1, 0, 1]) == ['x', 'y', 'z']
    assert candidate(words = ['hello', 'world', 'python', 'code'],groups = [1, 0, 1, 0]) == ['hello', 'world', 'python', 'code']
    assert candidate(words = ['a', 'b', 'c', 'd', 'e', 'f'],groups = [1, 0, 1, 0, 1, 0]) == ['a', 'b', 'c', 'd', 'e', 'f']
    assert candidate(words = ['apple', 'banana', 'cherry', 'date'],groups = [0, 1, 0, 1]) == ['apple', 'banana', 'cherry', 'date']
    assert candidate(words = ['hello', 'world', 'python', 'code'],groups = [0, 1, 0, 1]) == ['hello', 'world', 'python', 'code']
    assert candidate(words = ['red', 'blue', 'green'],groups = [1, 1, 1]) == ['red']
    assert candidate(words = ['a', 'b', 'c', 'd', 'e', 'f'],groups = [0, 1, 0, 1, 0, 1]) == ['a', 'b', 'c', 'd', 'e', 'f']
    assert candidate(words = ['sun', 'moon', 'star', 'planet'],groups = [0, 0, 1, 1]) == ['sun', 'star']
    assert candidate(words = ['sun', 'moon', 'star', 'planet'],groups = [1, 0, 1, 0]) == ['sun', 'moon', 'star', 'planet']
    assert candidate(words = ['dog', 'cat', 'fish', 'bird'],groups = [0, 1, 0, 1]) == ['dog', 'cat', 'fish', 'bird']
    assert candidate(words = ['red', 'blue', 'green', 'yellow'],groups = [0, 1, 0, 1]) == ['red', 'blue', 'green', 'yellow']
    assert candidate(words = ['fast', 'slow', 'quick', 'lazy'],groups = [1, 0, 1, 0]) == ['fast', 'slow', 'quick', 'lazy']
    assert candidate(words = ['red', 'blue', 'green'],groups = [0, 0, 1]) == ['red', 'green']
    assert candidate(words = ['fast', 'slow', 'big', 'small'],groups = [1, 0, 1, 0]) == ['fast', 'slow', 'big', 'small']
    assert candidate(words = ['red', 'blue', 'green'],groups = [1, 0, 1]) == ['red', 'blue', 'green']
    assert candidate(words = ['hello', 'world'],groups = [1, 0]) == ['hello', 'world']
    assert candidate(words = ['hello', 'world', 'python', 'code'],groups = [1, 1, 0, 0]) == ['hello', 'python']
    assert candidate(words = ['alpha', 'beta', 'gamma', 'delta', 'epsilon'],groups = [1, 0, 1, 0, 1]) == ['alpha', 'beta', 'gamma', 'delta', 'epsilon']
    assert candidate(words = ['sun', 'moon', 'star', 'planet'],groups = [0, 1, 0, 1]) == ['sun', 'moon', 'star', 'planet']
    assert candidate(words = ['dog', 'cat', 'fish'],groups = [1, 0, 1]) == ['dog', 'cat', 'fish']
    assert candidate(words = ['cat', 'dog', 'fish', 'bird', 'elephant'],groups = [1, 0, 1, 0, 1]) == ['cat', 'dog', 'fish', 'bird', 'elephant']
    assert candidate(words = ['left', 'right', 'up', 'down'],groups = [0, 1, 0, 1]) == ['left', 'right', 'up', 'down']
    assert candidate(words = ['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta'],groups = [0, 0, 1, 1, 0, 1]) == ['alpha', 'gamma', 'epsilon', 'zeta']
    assert candidate(words = ['sun', 'moon', 'star'],groups = [1, 0, 1]) == ['sun', 'moon', 'star']
    assert candidate(words = ['one', 'two', 'three', 'four', 'five', 'six'],groups = [0, 0, 1, 1, 0, 0]) == ['one', 'three', 'five']
    assert candidate(words = ['hello', 'world'],groups = [0, 1]) == ['hello', 'world']
    assert candidate(words = ['one', 'two', 'three', 'four', 'five'],groups = [0, 0, 1, 1, 0]) == ['one', 'three', 'five']
    assert candidate(words = ['hello', 'world', 'python', 'programming'],groups = [1, 0, 1, 0]) == ['hello', 'world', 'python', 'programming']
    assert candidate(words = ['hello', 'world', 'python', 'code'],groups = [0, 0, 1, 1]) == ['hello', 'python']
    assert candidate(words = ['a', 'b', 'c', 'd', 'e', 'f', 'g'],groups = [0, 1, 0, 1, 0, 1, 0]) == ['a', 'b', 'c', 'd', 'e', 'f', 'g']
    assert candidate(words = ['one', 'two', 'three', 'four', 'five'],groups = [0, 1, 0, 1, 0]) == ['one', 'two', 'three', 'four', 'five']
    assert candidate(words = ['one', 'two', 'three', 'four', 'five'],groups = [1, 1, 0, 0, 1]) == ['one', 'three', 'five']
    assert candidate(words = ['quick', 'brown', 'fox'],groups = [1, 0, 1]) == ['quick', 'brown', 'fox']
    assert candidate(words = ['one', 'two', 'three', 'four', 'five'],groups = [0, 0, 1, 1, 0]) == ['one', 'three', 'five']
    assert candidate(words = ['sun', 'moon', 'star', 'planet'],groups = [1, 0, 1, 1]) == ['sun', 'moon', 'star']
    assert candidate(words = ['hello', 'world', 'python', 'programming'],groups = [0, 0, 1, 1]) == ['hello', 'python']
    assert candidate(words = ['x', 'y', 'z', 'w', 'v'],groups = [0, 0, 0, 1, 1]) == ['x', 'w']
