# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abcabcbb") == 3
    assert candidate(s = "bbbbb") == 1
    assert candidate(s = "pwwkew") == 3
    assert candidate(s = "abcdabcabcabcd") == 4
    assert candidate(s = "abcdefgabcdefgabcdefgabcdefg") == 7
    assert candidate(s = "aabbccddeeff") == 2
    assert candidate(s = "sldfjldskfjdslkfjsdkljflkjsdfljfsdlkflskdjflsdjflskdjflsdkjflsdfjlsd") == 6
    assert candidate(s = "racecar") == 4
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "aabacbebebe") == 4
    assert candidate(s = "ekdvdfis") == 5
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz1234567890abcdefghijklmnopqrstuvwxyz") == 36
    assert candidate(s = "abbaabbaabba") == 2
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 2
    assert candidate(s = "abcdefghihgfedcba") == 9
    assert candidate(s = "abcdeffedcba") == 6
    assert candidate(s = "aaaaaaaabbbbbbbccccccdddddeeeeeeffffffffggggggg") == 2
    assert candidate(s = "tmmzuxt") == 5
    assert candidate(s = "nfpdmpi") == 5
    assert candidate(s = "anviaj") == 5
    assert candidate(s = "abcdeabcde") == 5
    assert candidate(s = "abcdabcabcd") == 4
    assert candidate(s = "dvdf") == 3
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba") == 26
    assert candidate(s = "abcdabcdeabcdabcdeabcd") == 5
    assert candidate(s = "rjqzupkoz") == 8
    assert candidate(s = "ababababababababab") == 2
    assert candidate(s = "!@#$%^&*()_+!@#$%^&*()_+") == 12
    assert candidate(s = "cdddddddddddddd") == 2
    assert candidate(s = "wobgrovw") == 6
    assert candidate(s = "abba") == 2
    assert candidate(s = "abcbacabc") == 3
    assert candidate(s = "ohvhjdml") == 6
    assert candidate(s = "123456789012345678901234567890") == 10
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz1234567890!@#$%^&*()_+") == 23
    assert candidate(s = "12345678901234567890") == 10
    assert candidate(s = "abcdabcabcabcd") == 4
    assert candidate(s = "abcdefgabcdefgabcdefgabcdefg") == 7
    assert candidate(s = "aabbccddeeff") == 2
    assert candidate(s = "sldfjldskfjdslkfjsdkljflkjsdfljfsdlkflskdjflsdjflskdjflsdkjflsdfjlsd") == 6
    assert candidate(s = "racecar") == 4
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "aabacbebebe") == 4
    assert candidate(s = "ekdvdfis") == 5
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz1234567890abcdefghijklmnopqrstuvwxyz") == 36
    assert candidate(s = "abbaabbaabba") == 2
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 2
    assert candidate(s = "abcdefghihgfedcba") == 9
    assert candidate(s = "abcdeffedcba") == 6
    assert candidate(s = "aaaaaaaabbbbbbbccccccdddddeeeeeeffffffffggggggg") == 2
    assert candidate(s = "tmmzuxt") == 5
    assert candidate(s = "nfpdmpi") == 5
    assert candidate(s = "anviaj") == 5
    assert candidate(s = "abcdeabcde") == 5
    assert candidate(s = "abcdabcabcd") == 4
    assert candidate(s = "dvdf") == 3
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba") == 26
    assert candidate(s = "abcdabcdeabcdabcdeabcd") == 5
    assert candidate(s = "rjqzupkoz") == 8
    assert candidate(s = "ababababababababab") == 2
    assert candidate(s = "!@#$%^&*()_+!@#$%^&*()_+") == 12
    assert candidate(s = "cdddddddddddddd") == 2
    assert candidate(s = "wobgrovw") == 6
    assert candidate(s = "abba") == 2
    assert candidate(s = "abcbacabc") == 3
    assert candidate(s = "ohvhjdml") == 6
    assert candidate(s = "123456789012345678901234567890") == 10
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz1234567890!@#$%^&*()_+") == 23
    assert candidate(s = "12345678901234567890") == 10
