# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(strs = ['hello', 'helium', 'helper']) == "hel"
    assert candidate(strs = ['a']) == "a"
    assert candidate(strs = ['', '', '', '']) == ""
    assert candidate(strs = ['apple', 'app', 'apricot']) == "ap"
    assert candidate(strs = ['abcd', 'abce', 'abcf']) == "abc"
    assert candidate(strs = ['apple', 'app', 'application']) == "app"
    assert candidate(strs = ['interview', 'interrupt', 'inter']) == "inter"
    assert candidate(strs = ['test', 'testing', 'tester']) == "test"
    assert candidate(strs = ['hello', 'hell', 'hella']) == "hell"
    assert candidate(strs = ['flower', 'flow', 'flight']) == "fl"
    assert candidate(strs = ['same', 'same', 'same']) == "same"
    assert candidate(strs = ['single']) == "single"
    assert candidate(strs = ['ab', 'abc', 'abcd']) == "ab"
    assert candidate(strs = ['abc', 'abc', 'abc']) == "abc"
    assert candidate(strs = ['abcd', 'dcba', 'abdc']) == ""
    assert candidate(strs = ['', 'b', 'abc']) == ""
    assert candidate(strs = ['a', 'ab', 'abc']) == "a"
    assert candidate(strs = ['dog', 'racecar', 'car']) == ""
    assert candidate(strs = ['a', 'a', 'a', 'a']) == "a"
    assert candidate(strs = ['', '', 'abc']) == ""
    assert candidate(strs = ['abc', 'abcd', 'abcde']) == "abc"
    assert candidate(strs = ['abcd', 'abc', 'ab', 'a']) == "a"
    assert candidate(strs = ['banana', 'bandana', 'banner']) == "ban"
    assert candidate(strs = ['aaaa', 'aaab', 'aaac']) == "aaa"
    assert candidate(strs = ['mississippi', 'mississauga', 'mission', 'missed']) == "miss"
    assert candidate(strs = ['commonality', 'commonwealth', 'common', 'commons']) == "common"
    assert candidate(strs = ['different', 'prefixes', 'here']) == ""
    assert candidate(strs = ['repetition', 'repetitive', 'repeat', 'repel', 'repeal', 'repetend']) == "repe"
    assert candidate(strs = ['million', 'millionaire', 'millionth', 'millionfold']) == "million"
    assert candidate(strs = ['algorithm', 'algorithmic', 'algebra', 'alignment']) == "al"
    assert candidate(strs = ['difficult', 'difficulty', 'differ']) == "diff"
    assert candidate(strs = ['environment', 'environmental', 'envision', 'enzyme']) == "en"
    assert candidate(strs = ['a', 'aa', 'aaa', 'aaaa']) == "a"
    assert candidate(strs = ['xylophone', 'xylotomy', 'xylography', 'xylograph']) == "xylo"
    assert candidate(strs = ['a', 'aa', 'aaa', 'aaaa', 'aaaaa']) == "a"
    assert candidate(strs = ['abcde', 'abc', 'ab', 'a', 'abcde']) == "a"
    assert candidate(strs = ['unique', 'unit', 'universe', 'unity', 'un']) == "un"
    assert candidate(strs = ['same', 'same', 'same', 'same']) == "same"
    assert candidate(strs = ['abcdef', 'abcde', 'abcd', 'abc', 'ab', 'a']) == "a"
    assert candidate(strs = ['short', 'small', 'shallow', 'shrink']) == "s"
    assert candidate(strs = ['zebra', 'zoo', 'zenith', 'zest', 'zone', 'zephyr']) == "z"
    assert candidate(strs = ['multidimensional', 'multidimensionalities', 'multidimensionally', 'multidimensionalization']) == "multidimensional"
    assert candidate(strs = ['computation', 'compute', 'computer', 'comedy']) == "com"
    assert candidate(strs = ['abcd', 'ab', 'a', 'abcde']) == "a"
    assert candidate(strs = ['abcde', 'abcdf', 'abcde', 'abcda', 'abcde', 'abcdf']) == "abcd"
    assert candidate(strs = ['zebra', 'zoo', 'zealot']) == "z"
    assert candidate(strs = ['abcd', 'abcde', 'ab', 'a']) == "a"
    assert candidate(strs = ['microphone', 'microwave', 'microscope', 'microbial']) == "micro"
    assert candidate(strs = ['longest', 'long', 'lonely']) == "lon"
    assert candidate(strs = ['prefix', 'preprocessor', 'prevent']) == "pre"
    assert candidate(strs = ['algorithm', 'algorithmically', '', 'algorithmic']) == ""
    assert candidate(strs = ['algorithm', 'alert', 'alibaba', 'allied']) == "al"
    assert candidate(strs = ['unbelievable', 'unbeliever', 'unbelievably', 'unbelievability']) == "unbeliev"
    assert candidate(strs = ['prefix', 'preposition', 'prevent', 'premier']) == "pre"
    assert candidate(strs = ['prefix', 'prefixes', 'prefixation', 'prefixed']) == "prefix"
    assert candidate(strs = ['a', 'b', 'c', 'd']) == ""
    assert candidate(strs = ['', 'same', 'same', 'same', 'same']) == ""
    assert candidate(strs = ['same', 'same', 'same', 'same', 'same']) == "same"
    assert candidate(strs = ['optimization', 'optimization', 'optimized', 'optimizer']) == "optimiz"
    assert candidate(strs = ['communication', 'communicate', 'commune', 'communist']) == "commun"
    assert candidate(strs = ['a', 'ab', 'abc', 'abcd', 'abcde', 'abcdef']) == "a"
    assert candidate(strs = ['algorithm', 'algorithmically', 'algebra', 'allegro']) == "al"
    assert candidate(strs = ['common', 'commotion', 'communicate', 'community']) == "comm"
    assert candidate(strs = ['flower', 'flow', 'flight', 'flew', 'flying', 'flowing']) == "fl"
    assert candidate(strs = ['single', 'singlehandedly', 'singlemindedness', 'singlehanded']) == "single"
    assert candidate(strs = ['algorithm', 'algebra', 'alaska']) == "al"
    assert candidate(strs = ['congratulations', 'congruity', 'congruent']) == "congr"
    assert candidate(strs = ['a', 'ab', 'abc', 'abcd']) == "a"
    assert candidate(strs = ['algorithm', 'algorithmic', 'algorithmically', 'algorithmically']) == "algorithm"
    assert candidate(strs = ['preference', 'prefix', 'prevent', 'prey']) == "pre"
    assert candidate(strs = ['abracadabra', 'abracadabras', 'abracadabaster', 'abracadabration']) == "abracadab"
    assert candidate(strs = ['supercalifragilisticexpialidocious', 'super', 'supersonic']) == "super"
    assert candidate(strs = ['unanimity', 'unanimous', 'unanimously', 'unanimated']) == "unanim"
    assert candidate(strs = ['orthogonal', 'orthodox', 'orthopedic', 'orthography']) == "ortho"
    assert candidate(strs = ['abcd', 'abcde', 'abcdef', 'abcdefg']) == "abcd"
    assert candidate(strs = ['programming', 'programmer', 'programmatic', 'program']) == "program"
    assert candidate(strs = ['sequential', 'sequence', 'sequent', 'sequel']) == "seque"
    assert candidate(strs = ['abracadabra', 'abr', 'abracadabrador', 'abrac']) == "abr"
    assert candidate(strs = ['consistent', 'consistency', 'consistently', 'consist']) == "consist"
    assert candidate(strs = ['common', 'community', 'comma', 'communist']) == "comm"
    assert candidate(strs = ['zebra', 'zoo', 'zealot', 'zest']) == "z"
    assert candidate(strs = ['a', 'a', 'a', 'a', 'a']) == "a"
    assert candidate(strs = ['algorithm', 'algebra', 'altitude', 'altimeter']) == "al"
    assert candidate(strs = ['supercalifragilisticexpialidocious', 'super', 'supercal']) == "super"
    assert candidate(strs = ['maximum', 'maximize', 'maximal']) == "maxim"
    assert candidate(strs = ['complex', 'complicated', 'complect', 'complete']) == "compl"
    assert candidate(strs = ['prefix', 'pre', 'preface', 'prefer', 'preference', 'prefixing']) == "pre"
    assert candidate(strs = ['abcd', 'abcde', 'abcdef', 'abcdefg', 'abcdefgh', 'abcdefghi']) == "abcd"
    assert candidate(strs = ['abcdefghij', 'abcdefgh', 'abcdefg', 'abcdef', 'abcde', 'abcd', 'abc', 'ab', 'a']) == "a"
    assert candidate(strs = ['abcde', 'abcde', 'abcde', 'abcde']) == "abcde"
    assert candidate(strs = ['algorithm', 'algorhythm', 'algae']) == "alg"
    assert candidate(strs = ['', '', '', '', 'a']) == ""
    assert candidate(strs = ['xylophone', 'xylography', 'xylogen', 'xylophonist']) == "xylo"
    assert candidate(strs = ['onomatopoeia', 'onomatopoetic', 'onomatope', 'onomatologist']) == "onomato"
    assert candidate(strs = ['rehabilitation', 'rehabilitate', 'rehabilitative', 'rehabilitated']) == "rehabilitat"
    assert candidate(strs = ['mississippi', 'missile', 'mission', 'missive']) == "missi"
    assert candidate(strs = ['longest', 'longevity', 'longitudinal']) == "long"
    assert candidate(strs = ['psychological', 'psychologist', 'psychology', 'psychic']) == "psych"
    assert candidate(strs = ['environment', 'envelope', 'envoy', 'evening']) == "e"
    assert candidate(strs = ['short', 'shorthand', 'shortfall']) == "short"
    assert candidate(strs = ['parallel', 'parallelogram', 'parallactic', 'paralactic']) == "paral"
    assert candidate(strs = ['cryptography', 'cryptographic', 'cryptanalysis', 'cryptanalytic']) == "crypt"
    assert candidate(strs = ['zebra', 'zoo', 'zero', 'zapper']) == "z"
    assert candidate(strs = ['singleword', 'single', 'singleton']) == "single"
    assert candidate(strs = ['anthropomorphic', 'anthropologist', 'anthropology', 'anthropocentric']) == "anthropo"
    assert candidate(strs = ['', '', '', 'a']) == ""
    assert candidate(strs = ['a', 'ab', 'abc', 'abcd', 'abcde']) == "a"
    assert candidate(strs = ['common', 'commune', 'command', 'community']) == "comm"
    assert candidate(strs = ['same', 'samsung', 'sample', 'sand', 'satellite', 'saturn']) == "sa"
    assert candidate(strs = ['algorithm', 'algebra', 'altitude']) == "al"
    assert candidate(strs = ['implementation', 'implement', 'implementing', 'implementor']) == "implement"
    assert candidate(strs = ['abracadabra', 'abracadabra', 'abracadabra']) == "abracadabra"
    assert candidate(strs = ['reorganization', 'reorganize', 'reorganized', 'reorganizing']) == "reorganiz"
    assert candidate(strs = ['university', 'universe', 'unique', 'unicorn']) == "uni"
    assert candidate(strs = ['', 'longest', 'longevity', 'logistics']) == ""
    assert candidate(strs = ['', '', '', 'abc']) == ""
    assert candidate(strs = ['environment', 'envy', 'envelop', 'enviable']) == "env"
    assert candidate(strs = ['unique', 'unicorn', 'unify', 'unity']) == "uni"
    assert candidate(strs = ['aabbcc', 'aabbc', 'aabb', 'aab', 'aa']) == "aa"
    assert candidate(strs = ['zebra', 'zoo', 'zeal', 'zither']) == "z"
    assert candidate(strs = ['', 'a', 'ab', 'abc', 'abcd']) == ""
    assert candidate(strs = ['aardvark', 'aardwolf', 'aardvark', 'aard']) == "aard"
    assert candidate(strs = ['zzzzzzzz', 'zzzzz', 'zzzz', 'zzz', 'zz', 'z']) == "z"
    assert candidate(strs = ['separation', 'separately', 'separated', 'separating']) == "separat"
    assert candidate(strs = ['mississippi', 'missile', 'mission', 'miss']) == "miss"
    assert candidate(strs = ['algorithm', 'algebra', 'alien', 'alert']) == "al"
    assert candidate(strs = ['commonality', 'common', 'commune', 'community', 'communicate', 'commemorative']) == "comm"
    assert candidate(strs = ['supercalifragilisticexpialidocious', 'supercalifragilistic', 'supercalifragili', 'super']) == "super"
    assert candidate(strs = ['parallel', 'parallelepiped', 'paralleled', 'paralegal']) == "paral"
    assert candidate(strs = ['prefix', 'preference', 'presentation']) == "pre"
    assert candidate(strs = ['unified', 'uniform', 'universe', 'unique']) == "uni"
    assert candidate(strs = ['anagram', 'anagrams', 'anagrammatic', 'anagrammatical']) == "anagram"
    assert candidate(strs = ['environment', 'environmental', 'environments', 'environmentally']) == "environment"
    assert candidate(strs = ['xylophone', 'xylography', 'xylophonist', 'xylophonics']) == "xylo"
    assert candidate(strs = ['prefix', '', 'prefix', 'prefix']) == ""
    assert candidate(strs = ['algorithm', 'algebra', 'altimeter']) == "al"
    assert candidate(strs = ['recognition', 'recognizable', 'recognize', 'recognizably']) == "recogni"
    assert candidate(strs = ['prefix', 'preposition', 'presentation']) == "pre"
    assert candidate(strs = ['challenges', 'challenging', 'challenge', 'challengingly']) == "challeng"
    assert candidate(strs = ['universally', 'universe', 'universal', 'universality', 'universes', 'universally']) == "univers"
    assert candidate(strs = ['mississippi', 'missile', 'missionary', 'misspell']) == "miss"
    assert candidate(strs = ['photosynthesis', 'photosynthetic', 'photosynthesize', 'photosynthetically']) == "photosynthe"
    assert candidate(strs = ['apple', 'apply', 'appetite', 'apparatus']) == "app"
    assert candidate(strs = ['prefix', 'pretext', 'prevent']) == "pre"
    assert candidate(strs = ['development', 'develop', 'developer', 'developmental', 'developing', 'devel']) == "devel"
    assert candidate(strs = ['prefix', 'preference', 'presentation', 'president', 'pressure', 'premier']) == "pre"
    assert candidate(strs = ['', 'unique', 'unanimous', 'unicorn', 'unicycle', 'unify']) == ""
    assert candidate(strs = ['complex', 'complicated', 'completion']) == "compl"
