# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(text = "abcabc") == 2
    assert candidate(text = "abcabcabc") == 3
    assert candidate(text = "level") == 5
    assert candidate(text = "zyxzyxzyx") == 3
    assert candidate(text = "madam") == 5
    assert candidate(text = "aaaaa") == 5
    assert candidate(text = "merchant") == 1
    assert candidate(text = "aabbccddeedccbbaa") == 15
    assert candidate(text = "repaper") == 7
    assert candidate(text = "ghiabcdefhelloadamhelloabcdefghi") == 7
    assert candidate(text = "aaa") == 3
    assert candidate(text = "antaprezatepzapreanta") == 11
    assert candidate(text = "abcdabcdabcdabcd") == 4
    assert candidate(text = "abacaba") == 7
    assert candidate(text = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 52
    assert candidate(text = "xyzzyx") == 6
    assert candidate(text = "abcddcba") == 8
    assert candidate(text = "rotor") == 5
    assert candidate(text = "abcdedcba") == 9
    assert candidate(text = "refer") == 5
    assert candidate(text = "redder") == 6
    assert candidate(text = "peep") == 4
    assert candidate(text = "abba") == 4
    assert candidate(text = "racecar") == 7
    assert candidate(text = "civic") == 5
    assert candidate(text = "abcdabcd") == 2
    assert candidate(text = "a") == 1
    assert candidate(text = "abcabcabcabcabcabc") == 6
    assert candidate(text = "xyzzyxxyzzyx") == 12
    assert candidate(text = "noon") == 4
    assert candidate(text = "deified") == 7
    assert candidate(text = "racecarlevelracecar") == 19
    assert candidate(text = "deed") == 4
    assert candidate(text = "abccba") == 6
    assert candidate(text = "abab") == 2
    assert candidate(text = "aabbccddeeddccbbaa") == 18
    assert candidate(text = "abcba") == 5
    assert candidate(text = "abcdeedcba") == 10
    assert candidate(text = "levellevel") == 10
    assert candidate(text = "ababababab") == 5
    assert candidate(text = "bananaananabayananabanana") == 13
    assert candidate(text = "abcdabcabcabcabcd") == 5
    assert candidate(text = "racecarannakayakracecar") == 15
    assert candidate(text = "abcabcabcabcabcabcabc") == 7
    assert candidate(text = "xxyyxxyyxyyxxyyxxyy") == 5
    assert candidate(text = "xylophonephoneyloxyxylophonephoneyloxy") == 10
    assert candidate(text = "leveloneleveltwolevelonelevel") == 23
    assert candidate(text = "aaaaabaaaabaaaa") == 13
    assert candidate(text = "abacababacaba") == 13
    assert candidate(text = "rotorcarrot") == 3
    assert candidate(text = "leveloneonetwothreefourthreefourtwoonelevel") == 15
    assert candidate(text = "aaaaabaaaabaaaaaaaabaaaaabaaaabaaaa") == 27
    assert candidate(text = "noonnoonnoonnoonnoonnoon") == 24
    assert candidate(text = "annakayakannakayakannakayakannakayakannakayak") == 5
    assert candidate(text = "abcdefghihgfedcbaabcdefghihgfedcba") == 34
    assert candidate(text = "abcdefgfedcbaabcdefgfedcbaabcdefgfedcba") == 39
    assert candidate(text = "abacabaabacaba") == 14
    assert candidate(text = "qwertyuiopasdfghjklzxcvbnmmnbvcxzlkjhgfdsapoiuytrewq") == 52
    assert candidate(text = "madamimadamimadam") == 17
    assert candidate(text = "kayak") == 5
    assert candidate(text = "thisisaverylongstringwhichdoesnotrepeatthisisaverylongstring") == 3
    assert candidate(text = "deifiedrotorcarcaretordeified") == 21
    assert candidate(text = "madamimadamimadamimadamimadam") == 29
    assert candidate(text = "noonnoonnoonnoonnoonnoonnoonnoon") == 32
    assert candidate(text = "deifiedrotordeified") == 19
    assert candidate(text = "noonracecarnoon") == 15
    assert candidate(text = "madamimadam") == 11
    assert candidate(text = "repaperdeified") == 1
    assert candidate(text = "deededeed") == 9
    assert candidate(text = "ananaananaananananananananananana") == 15
    assert candidate(text = "racecarlevelracecarlevelracecarlevel") == 3
    assert candidate(text = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 18
    assert candidate(text = "racecarlevelmadamracecar") == 15
    assert candidate(text = "leveloneonelevel") == 12
    assert candidate(text = "xyzyxzyzyxzyzyxzyx") == 15
    assert candidate(text = "abcdefghihgfedcba") == 17
    assert candidate(text = "abbaabbaabbaabbaabba") == 20
    assert candidate(text = "abacabaabacabaabacaba") == 21
    assert candidate(text = "abcdabcdeedcbadcbabcd") == 3
    assert candidate(text = "abccbaabccba") == 12
    assert candidate(text = "abracadabra") == 7
    assert candidate(text = "madammadam") == 10
    assert candidate(text = "aaaaaaaaabbbbbbbbbbbbbbbccccccccccccccccccccdd") == 1
    assert candidate(text = "deifiedrotorleveldeified") == 15
    assert candidate(text = "racecarlevelracecarlevelracecarlevelracecarlevel") == 4
    assert candidate(text = "madaminnadammadam") == 11
    assert candidate(text = "leveldeifiedmadamdeifiedlevel") == 29
    assert candidate(text = "abacabacabacabac") == 4
    assert candidate(text = "aaaabbbbccccaaaabbbbcccc") == 2
    assert candidate(text = "noonnoonnoon") == 12
    assert candidate(text = "xyzyxzyzyxzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyx") == 33
    assert candidate(text = "abcdefgabcdefgabcdefg") == 3
    assert candidate(text = "abracadabraabracadabra") == 14
    assert candidate(text = "civiccivic") == 10
    assert candidate(text = "annakayakannakayakannakayakannakayakannakayakannakayakannakayak") == 7
    assert candidate(text = "rotorcarrots") == 1
    assert candidate(text = "abracadabraacarab") == 11
    assert candidate(text = "kayakkayakkayak") == 15
    assert candidate(text = "nun") == 3
    assert candidate(text = "annakayakannakayakannakayak") == 3
    assert candidate(text = "rotorlevelrotor") == 15
    assert candidate(text = "qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm") == 2
    assert candidate(text = "aabbccddeeddccbaa") == 7
    assert candidate(text = "abbaabbaabba") == 12
    assert candidate(text = "xyzxyzxyzxyzxyzxyzxyzxyz") == 8
    assert candidate(text = "levellevellevellevel") == 20
    assert candidate(text = "abccbaabccbaabccba") == 18
    assert candidate(text = "abcdeedcbaabcdeedcbaabcdeedcba") == 30
    assert candidate(text = "abcdefgfedcbaabcdefg") == 3
    assert candidate(text = "levelmadamlevel") == 15
    assert candidate(text = "abcabcabcabc") == 4
    assert candidate(text = "abacabadabacabaabacabadabacaba") == 30
    assert candidate(text = "rotorcarcaretor") == 7
    assert candidate(text = "annakayakannakayakannakayakannakayak") == 4
    assert candidate(text = "levellevellevellevellevellevellevellevellevellevellevellevel") == 60
    assert candidate(text = "levellevellevellevellevellevel") == 30
    assert candidate(text = "aaaaabbbbbaaaabbbbbaaaaa") == 24
    assert candidate(text = "abcdabcabcabcd") == 4
    assert candidate(text = "aaaabbbbccccbbbbaaaa") == 20
    assert candidate(text = "madamimadamimadamimadamimadamimadamimadamimadam") == 47
    assert candidate(text = "abcdxyzyxzyxcddcbaabcdxyzyxzyxcddcba") == 18
    assert candidate(text = "abacabadabacabadabacaba") == 23
    assert candidate(text = "deifieddeified") == 14
    assert candidate(text = "deifiedracecardeified") == 21
    assert candidate(text = "noonnoonnoonnoon") == 16
    assert candidate(text = "radar") == 5
    assert candidate(text = "abacabadabacaba") == 15
    assert candidate(text = "annakayakannakayak") == 2
    assert candidate(text = "abcdabcdefgabcdefgdcba") == 10
    assert candidate(text = "racecarannakayak") == 1
    assert candidate(text = "abbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabba") == 44
    assert candidate(text = "abacabadabacabad") == 2
    assert candidate(text = "rotorrotor") == 10
    assert candidate(text = "abcabcabcabcabc") == 5
    assert candidate(text = "abracadabracadabra") == 11
    assert candidate(text = "levellevellevellevellevel") == 25
    assert candidate(text = "aaaaaabaaaaa") == 11
    assert candidate(text = "aabbccddeedcbaabbccdd") == 3
    assert candidate(text = "hellohellobellohellobellohello") == 4
    assert candidate(text = "xyzzxyzzxyzz") == 3
    assert candidate(text = "xxyyzzzyyxxyyyzzzzyyxx") == 15
    assert candidate(text = "aabbccddeeeedddccbbaaa") == 5
    assert candidate(text = "deifiedrotor") == 1
    assert candidate(text = "abcdeedcbaabcdeedcba") == 20
    assert candidate(text = "abababababababab") == 8
    assert candidate(text = "abacabaabacabaabacabaabacaba") == 28
    assert candidate(text = "aaaabbbbccccddddeeeeffffeeeeggggccccbbbbaaaaffff") == 1
    assert candidate(text = "wow") == 3
    assert candidate(text = "abcdabccbaabcd") == 8
    assert candidate(text = "abcabcabcabcabcabcabcd") == 1
    assert candidate(text = "abcxyzzyxcba") == 12
    assert candidate(text = "racecarlevelracecarlevelracecarlevelracecarlevelracecarlevel") == 5
    assert candidate(text = "madamimadamimadamimadamimadamimadam") == 35
    assert candidate(text = "noonabbadacabbaaddaabbnoon") == 15
    assert candidate(text = "xyzzyxzyxzyxzyxzyxzyxzyxyz") == 15
    assert candidate(text = "levellevellevellevellevellevellevellevel") == 40
    assert candidate(text = "abababababababababababab") == 12
    assert candidate(text = "mississippiississimississimississippi") == 17
    assert candidate(text = "aabbccddeedcba") == 3
    assert candidate(text = "xyzyxzyzyxzyx") == 11
    assert candidate(text = "aaaaabaaa") == 7
    assert candidate(text = "abcdcdeabcdcdeabcdcdeabcd") == 7
    assert candidate(text = "racecarracecar") == 14
    assert candidate(text = "rotorrotorrotor") == 15
    assert candidate(text = "racecarlevelracecarlevel") == 2
    assert candidate(text = "kayakkayak") == 10
    assert candidate(text = "noonnoon") == 8
    assert candidate(text = "racecarlevelmadamracecarlevelmadam") == 2
    assert candidate(text = "abcxyzzyxcbaabcxyzzyxcba") == 24
    assert candidate(text = "redividerrotorredivider") == 23
    assert candidate(text = "ababababababababababababababababab") == 17
    assert candidate(text = "referrefer") == 10
    assert candidate(text = "noonnoonnoonnoonnoonnoonnoonnoonnoonnoon") == 40
    assert candidate(text = "madamimadamimadamimadam") == 23
    assert candidate(text = "abbaabbaabbaabba") == 16
    assert candidate(text = "mississippi") == 1
    assert candidate(text = "aabbccddeedccbbaaa") == 5
    assert candidate(text = "abcdeabcdeabcde") == 3
    assert candidate(text = "racecarracecarracecar") == 21
    assert candidate(text = "redivider") == 9
    assert candidate(text = "thisisaverylongstringwithnorepeatedpattern") == 1
