# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "(()())") == 6
    assert candidate(s = "())") == 2
    assert candidate(s = "())(()") == 2
    assert candidate(s = "((((((()))))))") == 14
    assert candidate(s = "((())()())()") == 12
    assert candidate(s = ")()(()(()))") == 10
    assert candidate(s = "(()(()(()(()))))") == 16
    assert candidate(s = ")()())") == 4
    assert candidate(s = "()()()()()()()()") == 16
    assert candidate(s = "()(()(()))") == 10
    assert candidate(s = "()()(())") == 8
    assert candidate(s = "") == 0
    assert candidate(s = "(()))()") == 4
    assert candidate(s = "(()))(()))") == 4
    assert candidate(s = "(()))") == 4
    assert candidate(s = "(()(()))") == 8
    assert candidate(s = "((()))(())()()") == 14
    assert candidate(s = "((())()())") == 10
    assert candidate(s = "(()(())())()()") == 14
    assert candidate(s = "()(()(()(()(()(()))))") == 18
    assert candidate(s = "((((((((((()))))))))))") == 22
    assert candidate(s = "())()(()") == 2
    assert candidate(s = "()(()") == 2
    assert candidate(s = "(()") == 2
    assert candidate(s = "()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()") == 72
    assert candidate(s = "(((())))()()()") == 14
    assert candidate(s = "(()((())()())())") == 16
    assert candidate(s = "()()()()()()()()()") == 18
    assert candidate(s = "((())((()))") == 10
    assert candidate(s = "((()))") == 6
    assert candidate(s = "(()))(()())") == 6
    assert candidate(s = "()()") == 4
    assert candidate(s = "()()()()") == 8
    assert candidate(s = "()()()()()()()()()()()()()()()()()()") == 36
    assert candidate(s = "()()()()()()()()()()()()()()()()()") == 34
    assert candidate(s = "()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()") == 80
    assert candidate(s = "(()(()(()(()(())))))") == 20
    assert candidate(s = "()(()(()))()()") == 14
    assert candidate(s = "(()((())()()))") == 14
    assert candidate(s = "()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()") == 60
    assert candidate(s = "((((()))))((((()))))((((()))))") == 30
    assert candidate(s = "(()((((())))))") == 14
    assert candidate(s = "(((((((((((((())))))))))()))))))))))))))))))()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()") == 60
    assert candidate(s = "((())()(()))") == 12
    assert candidate(s = "(((((())))))") == 12
    assert candidate(s = "(()((())())())") == 14
    assert candidate(s = "()((((((()))))))()") == 18
    assert candidate(s = "(((()(()(()(()(()(()()))))))))") == 30
    assert candidate(s = "((((()))))(((())))") == 18
    assert candidate(s = "(((())))(((())))(((())))(((())))") == 32
    assert candidate(s = "((((((((((())))))))))))") == 22
    assert candidate(s = "()(()(((()))()))") == 16
    assert candidate(s = "(((((())))))(((((())))))") == 24
    assert candidate(s = "()()(()(()))(()(()))()()") == 24
    assert candidate(s = "(()(()(()(()(()))))())") == 22
    assert candidate(s = "(()())(()())(()())") == 18
    assert candidate(s = "()()()(()(()(()(()(()()))))") == 20
    assert candidate(s = "(()(()))(()(()))(()(()))(()(()))") == 32
    assert candidate(s = "((((((((()))))))))") == 18
    assert candidate(s = "((()()()()()()))((()()()()()()))") == 32
    assert candidate(s = "()((()))()(()(()))()") == 20
    assert candidate(s = "(((((()(()(()(()(()(()()))))))))))()()()") == 40
    assert candidate(s = "(()(()(()(()(()(()(()(())))))))()()") == 34
    assert candidate(s = "(()(()(()(()))()))") == 18
    assert candidate(s = "()(()())(()(()))") == 16
    assert candidate(s = "(()(()(()(()(()(()(()(())))))))))") == 32
    assert candidate(s = "()(()(()(()(()(()(()(()(()))()))))))()()") == 40
    assert candidate(s = "()(()(()))()()()") == 16
    assert candidate(s = "(()(()(()(()(()(()(()(()(()(()(()))))))))))))))") == 44
    assert candidate(s = "((()))((()))") == 12
    assert candidate(s = "((()()(()())))()()") == 18
    assert candidate(s = "()(()(()(()(()(()(()(()))))))))))))()(()(()(()))()()()()()()()()") == 30
    assert candidate(s = "(()((())((()))(((())))))") == 24
    assert candidate(s = "()()()()()()()()()()") == 20
    assert candidate(s = "((((((((()))))))(()(()(()(()(()(()(()))))))))()()") == 48
    assert candidate(s = "(()(()(()(()(()(()(()(()(()(()(())))))()))))))))") == 46
    assert candidate(s = "(()(()(()(()(()(()()))))))") == 26
    assert candidate(s = "(()(()(()(()(()(()))))))") == 24
    assert candidate(s = "(()(()(()(()(()(()(()(()(()(()(()()))))))))))()())") == 50
    assert candidate(s = "()(()(()(()(()(())))))") == 22
    assert candidate(s = "(((()(()))(()(()))))") == 20
    assert candidate(s = "()((((()))))()(()(()))") == 22
    assert candidate(s = "(()((((()))))))()()") == 14
    assert candidate(s = "((((()))))(()(()))") == 18
    assert candidate(s = "(()(()(()(()(()(()))))())()()") == 28
    assert candidate(s = "(()(()(()(()(()(()(()(()(()(()(()(()(()))()))))))))))))))))))") == 54
    assert candidate(s = "(()(()(()(()(()(()(()))))))))))))()(()(()(()))") == 28
    assert candidate(s = "(()(()(()))(()(())))") == 20
    assert candidate(s = "(()(()))(()(()))") == 16
    assert candidate(s = "(((()()(()())()(()(())))))()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()") == 126
    assert candidate(s = "(()(()(()(()(()(()(()(()(())))))))))") == 36
    assert candidate(s = "(()(()))()(()())") == 16
    assert candidate(s = "()((((((((())))))))))()()") == 20
    assert candidate(s = "()(()(()(()(()(()(())))))()()()") == 28
    assert candidate(s = "(()(()(()(()(()(()(()()))))))))") == 30
    assert candidate(s = "((())())(()(()(()())))") == 22
    assert candidate(s = "((()))((()))((()))((()))") == 24
    assert candidate(s = "((()))()((()))()((()))") == 22
    assert candidate(s = "(()(()(()(()(()(()(()))))))))))))()") == 28
    assert candidate(s = "(()(())((())))") == 14
    assert candidate(s = "((((((((()))))))))))))))") == 18
    assert candidate(s = "(()(()(()(()(()(()(())))))))") == 28
    assert candidate(s = "(()(()(()(()(()(()(()))))))())") == 30
    assert candidate(s = "()()(()(()(()(()()))))") == 22
    assert candidate(s = "()(()))(()(()))") == 8
    assert candidate(s = "(()(()(()(()(()(()(()(())))))())))") == 34
    assert candidate(s = "(()(()(()(()(()(()(()(()(()))))))))))))()(()(()(()))()()()()()()()()(()(()(())))") == 38
    assert candidate(s = "()(()(()(()(()(()(()(())))))))") == 30
    assert candidate(s = "(()()(()))((())())") == 18
    assert candidate(s = "(((((())))))(((()(()))(()))(()(()))(()(()))(()(()))(()(())))") == 60
    assert candidate(s = "(()(()(()(()(()(()(())))))())()()()") == 34
    assert candidate(s = "()(()(()(()(()(())))))()()") == 26
    assert candidate(s = "((()))(()(()))") == 14
    assert candidate(s = "())(()())(()(()()(())))") == 20
    assert candidate(s = "((())())(()(()(()(()))))") == 24
    assert candidate(s = "(((()))(()))(()())") == 18
    assert candidate(s = "((())())(()(()))") == 16
    assert candidate(s = "(()(()))(()(()))(()(()))") == 24
    assert candidate(s = "(()(()(())))()()()(()(()))") == 26
    assert candidate(s = "()()()()()()()()()()()()") == 24
    assert candidate(s = "(((((()(()))(()(())))))())") == 26
    assert candidate(s = "()(()(()(()(()(()(()(()))))))))") == 30
    assert candidate(s = "((())((()))(()(()))(()))") == 24
    assert candidate(s = "()(()()(()(()())))") == 18
    assert candidate(s = "((()(()())))()((()(())))") == 24
    assert candidate(s = "((((()))()()()(()))") == 18
    assert candidate(s = "((((((()))))))(()(()(())))") == 26
    assert candidate(s = "(((()(()(()(()())))))()())") == 26
    assert candidate(s = "()(()(()(()(()(()(())))))") == 22
    assert candidate(s = "()()()()()()()()()()()()()()()()()()()()") == 40
    assert candidate(s = "()()()()()()()()()()()()()()()") == 30
    assert candidate(s = "((((((()))))))(()(()(()(()))))") == 30
    assert candidate(s = "(()())(())(()(()(()(())))())") == 28
