# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "pypypypypypypypypyp") == 17
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 0
    assert candidate(s = "abababab") == 6
    assert candidate(s = "abcabcabc") == 6
    assert candidate(s = "abracadabra") == 4
    assert candidate(s = "abcabcabcabc") == 9
    assert candidate(s = "abcdabcabc") == 3
    assert candidate(s = "abbaba") == 2
    assert candidate(s = "xyzxyzxyz") == 6
    assert candidate(s = "banana") == 3
    assert candidate(s = "aabcaabdaab") == 3
    assert candidate(s = "abcdefgabcdefg") == 7
    assert candidate(s = "abcdefgh") == 0
    assert candidate(s = "abcd") == 0
    assert candidate(s = "hellohello") == 5
    assert candidate(s = "aaaa") == 3
    assert candidate(s = "mississippi") == 4
    assert candidate(s = "xyzxyzxyzxyz") == 9
    assert candidate(s = "abcdefg") == 0
    assert candidate(s = "pwwkewpwwkewpwwkew") == 12
    assert candidate(s = "acacacacacacac") == 12
    assert candidate(s = "aabbccddeeffaabbccddeeffaabbccddeeff") == 24
    assert candidate(s = "thisisaverylongstringwithrepeatingthisisaverylong") == 15
    assert candidate(s = "abcdeabcd") == 4
    assert candidate(s = "xyzxyzxyzxyzxyzxyzxyz") == 18
    assert candidate(s = "aaaaaaaaaa") == 9
    assert candidate(s = "abcdefghijabcdefghijabcdefghij") == 20
    assert candidate(s = "abcdabcdabcd") == 8
    assert candidate(s = "xyxxyxyxyxyxyxyxyxyxyxxyxyxyxyx") == 17
    assert candidate(s = "abacabadabacabad") == 8
    assert candidate(s = "bananaananabananabanana") == 11
    assert candidate(s = "abcbacbcba") == 4
    assert candidate(s = "zabzabzabzabzab") == 12
    assert candidate(s = "mississippimississippi") == 11
    assert candidate(s = "abcdabcabcdabcabcd") == 11
    assert candidate(s = "bananaananabanana") == 6
    assert candidate(s = "abcabcabcabcabcabcabc") == 18
    assert candidate(s = "aaaaabaaaabaaaabaaaab") == 15
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 36
    assert candidate(s = "qwertyuiopqwertyuiop") == 10
    assert candidate(s = "bananaananaban") == 5
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc") == 27
    assert candidate(s = "abcababcababcab") == 10
    assert candidate(s = "mississipississippi") == 8
    assert candidate(s = "xyzabcxyzabcxyz") == 9
    assert candidate(s = "abracadabraabracadabraabracadabra") == 22
    assert candidate(s = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyz") == 27
    assert candidate(s = "ababababababababab") == 16
    assert candidate(s = "anappleapernapple") == 6
    assert candidate(s = "abcdabcabcdabcdabc") == 7
    assert candidate(s = "abcabcabcabcabcabc") == 15
    assert candidate(s = "qwertqwertyuiopasdfghjklzxcvbnm") == 5
    assert candidate(s = "xyxxyxyxyxyx") == 7
    assert candidate(s = "aaaaabbbaaaabbbaaa") == 10
    assert candidate(s = "aaaaaaa") == 6
    assert candidate(s = "abcbcbcbcbcbcbcb") == 13
    assert candidate(s = "aaaaa") == 4
    assert candidate(s = "abacabadabacaba") == 7
    assert candidate(s = "abcdefghiabcdefghi") == 9
    assert candidate(s = "xyzxyzxyzxyzxyzxyz") == 15
    assert candidate(s = "pqrstpqrstpqrstpqrst") == 15
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz") == 19
    assert candidate(s = "abcdabcabcabcd") == 6
    assert candidate(s = "abcdeabcdeabcdeabcde") == 15
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnmqwertyuiop") == 10
    assert candidate(s = "bananaananabanananaban") == 8
    assert candidate(s = "abcdefghijkabcdefghij") == 10
    assert candidate(s = "abracadabraabracadabra") == 11
    assert candidate(s = "xyzxyzxyzxyzxyz") == 12
    assert candidate(s = "xyxyxyxyxyxyxyxyxyxyxy") == 20
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 1
    assert candidate(s = "aaaaabbbbbccccddddd") == 4
    assert candidate(s = "abcdefghabcdefghabcdefgh") == 16
    assert candidate(s = "aabbccddeeffaabbccddeeff") == 12
    assert candidate(s = "abacabadabacabadabacabad") == 16
    assert candidate(s = "aabcaabdaabaabcaabdaabaabcaabdaab") == 22
    assert candidate(s = "bananaananabananan") == 6
    assert candidate(s = "abcdeabcdeabcde") == 10
    assert candidate(s = "xyzxyzxyzxyzxyzxyzxyzxyz") == 21
    assert candidate(s = "repeatedrepeatedrepeated") == 16
    assert candidate(s = "abcdefgabcdefgabcdefg") == 14
    assert candidate(s = "abcdefghijabcdefghij") == 10
    assert candidate(s = "abcabcabcabcabcabcabcabc") == 21
    assert candidate(s = "zxyxzyzyzxzyzyzyzxzyzyzyz") == 13
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "abcdefghabcdefgh") == 8
    assert candidate(s = "pneumonoultramicroscopicsilicovolcanoconiosis") == 2
    assert candidate(s = "pqpqppqpqppqpqpqpqppqp") == 10
    assert candidate(s = "abcdefggfedcbabcdefggfedcb") == 13
    assert candidate(s = "xyzzxyzzxyzzxyzzxyzzxyzz") == 20
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaab") == 21
    assert candidate(s = "mnopqmnopqmnopqmnopq") == 15
    assert candidate(s = "qwertqwertqwert") == 10
    assert candidate(s = "xyzxyzyzxyzxyzyz") == 8
    assert candidate(s = "abacabadabacabadabacabada") == 17
    assert candidate(s = "abcabcabcabcabc") == 12
    assert candidate(s = "repeatedrepeatedrepeatedrepeatedrepeated") == 32
    assert candidate(s = "pqpqppqpqppqpqp") == 10
    assert candidate(s = "ananananaanana") == 7
