# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "aabbccc") == 7
    assert candidate(s = "abccccdd") == 7
    assert candidate(s = "zyyzzzzz") == 8
    assert candidate(s = "abcdedcba") == 9
    assert candidate(s = "aabbbb") == 6
    assert candidate(s = "aaaaa") == 5
    assert candidate(s = "aabbccddee") == 10
    assert candidate(s = "a") == 1
    assert candidate(s = "aaabbbaa") == 7
    assert candidate(s = "aabbbccc") == 7
    assert candidate(s = "aabbbbccc") == 9
    assert candidate(s = "zzzz") == 4
    assert candidate(s = "aabbc") == 5
    assert candidate(s = "") == 0
    assert candidate(s = "aabbb") == 5
    assert candidate(s = "abcde") == 1
    assert candidate(s = "Aa") == 1
    assert candidate(s = "racecar") == 7
    assert candidate(s = "aabb") == 4
    assert candidate(s = "abbccc") == 5
    assert candidate(s = "abcadcb") == 7
    assert candidate(s = "abcABC") == 1
    assert candidate(s = "abba") == 4
    assert candidate(s = "abc") == 1
    assert candidate(s = "aabbccddeeffgghhii") == 18
    assert candidate(s = "aabbccddeeff") == 12
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcbaabcdefghijklmnopqrstuvwxyz") == 52
    assert candidate(s = "aabbbbcccc") == 10
    assert candidate(s = "zzzzzzzz") == 8
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba") == 1
    assert candidate(s = "abcdefg") == 1
    assert candidate(s = "aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ") == 1
    assert candidate(s = "abAB") == 1
    assert candidate(s = "aaAAbbBBccCCddDDeeEEffFFggGGhhHHiiJJkkLLmmNNooPPqqRRssSStttUuuVvvWwwXxxYyyZzz") == 71
    assert candidate(s = "aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaA") == 49
    assert candidate(s = "deified") == 7
    assert candidate(s = "AaBbCcDdEeFfGg") == 1
    assert candidate(s = "abcABCabcABCabcABC") == 13
    assert candidate(s = "abcdeABCDEabcdeABCDEabcdeABCDEabcdeABCDE") == 40
    assert candidate(s = "abcdabcabcdabcabcdabcabcdabcabcdabcabcdabcabcdabcabcdabcdabcabcdabcabcdabc") == 71
    assert candidate(s = "Aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 51
    assert candidate(s = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz") == 1
    assert candidate(s = "abacabadabacaba") == 15
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzAAAaaaBBBbbbCCCcccDDDdddEEEeeeFFFfffGGGgggHHHhhhIIIiiiJJJjjjKKKkkkLLLlllMMMmmmNNNnnnOOOoooPPPpppQQQqqqRRRrrrSSSsssTTTtttUUUuuuVVVvvvWWWwwwXXXxxxYYYyyyZZZzzz") == 157
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ") == 1
    assert candidate(s = "abacabadabacabadabacabadabacabad") == 32
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcbaABCDEFGHIJKLMNOPQRSTUVWXYZ") == 1
    assert candidate(s = "bAabA") == 5
    assert candidate(s = "rotor") == 5
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyz") == 51
    assert candidate(s = "noon") == 4
    assert candidate(s = "banana") == 5
    assert candidate(s = "abcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefg") == 56
    assert candidate(s = "abbcccdddd") == 9
    assert candidate(s = "aabbccddeeeffffffgggg") == 21
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 52
    assert candidate(s = "bbaaaacccddeeefffggghhhiiijjjkkklllmmmnnooopppqqqrrrssstttuuuvvvwwwxxxyyyzzz") == 55
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 71
    assert candidate(s = "abbacdfee") == 7
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzz") == 58
    assert candidate(s = "AxA") == 3
    assert candidate(s = "aaabbbbcccc") == 11
    assert candidate(s = "thisisatest") == 7
    assert candidate(s = "mississippi") == 11
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 52
    assert candidate(s = "zyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyx") == 49
    assert candidate(s = "level") == 5
    assert candidate(s = "Aaaaaaaa") == 7
