# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(name = "zzzzzzzz",typed = "zzzzzzzz") == True
    assert candidate(name = "abcd",typed = "abcde") == False
    assert candidate(name = "test",typed = "ttest") == True
    assert candidate(name = "dfuyalc",typed = "fuuyallc") == False
    assert candidate(name = "zzzyyyyy",typed = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == False
    assert candidate(name = "abcd",typed = "abcddcba") == False
    assert candidate(name = "alex",typed = "aaleexa") == False
    assert candidate(name = "kikcxmvzi",typed = "kiikcxxmmvvzzz") == False
    assert candidate(name = "pyplrz",typed = "ppyypllrz") == True
    assert candidate(name = "ggggggg",typed = "ggggggg") == True
    assert candidate(name = "laiden",typed = "laiden") == True
    assert candidate(name = "saeed",typed = "ssaaedd") == False
    assert candidate(name = "a",typed = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == True
    assert candidate(name = "a",typed = "b") == False
    assert candidate(name = "abcd",typed = "abc") == False
    assert candidate(name = "pyplrz",typed = "ppyypllr") == False
    assert candidate(name = "a",typed = "aaaaaa") == True
    assert candidate(name = "leelee",typed = "lleeelee") == True
    assert candidate(name = "zzzaaa",typed = "zzzzzaaaa") == True
    assert candidate(name = "alex",typed = "aaleex") == True
    assert candidate(name = "vtkgn",typed = "vttkgnn") == True
    assert candidate(name = "alex",typed = "ale") == False
    assert candidate(name = "hello",typed = "hheeelllloo") == True
    assert candidate(name = "mississippi",typed = "miiiiiiissssssippiiiiii") == False
    assert candidate(name = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",typed = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzz") == True
    assert candidate(name = "repeated",typed = "repeeeaatteedd") == True
    assert candidate(name = "testing",typed = "testings") == False
    assert candidate(name = "mississippi",typed = "mmiissssippip") == False
    assert candidate(name = "aabbcc",typed = "aaabbbccc") == True
    assert candidate(name = "abcdefghij",typed = "aabbccddeeffgghhiijj") == True
    assert candidate(name = "mississippi",typed = "mmiiisssssiiiippp") == False
    assert candidate(name = "flower",typed = "ffflowweerrr") == True
    assert candidate(name = "consistent",typed = "cccooonnsisstiisstteeennnttt") == False
    assert candidate(name = "algorithm",typed = "aaalgggggorithm") == True
    assert candidate(name = "programming",typed = "pprooggrammmiinngg") == True
    assert candidate(name = "mississippi",typed = "mmiiississipppi") == True
    assert candidate(name = "friend",typed = "ffriiieeeennnd") == True
    assert candidate(name = "longpressed",typed = "lllooonngggppprrreeesssppeeeedd") == False
    assert candidate(name = "longpressed",typed = "lllongggppppreeesssssssedd") == True
    assert candidate(name = "polygon",typed = "pppollooogooonnnggg") == False
    assert candidate(name = "unique",typed = "uuunnnnuuuuuuuuqeeeuuuuuuuuuueee") == False
    assert candidate(name = "consistent",typed = "ccoonnsissssttttiinnnsss") == False
    assert candidate(name = "mississippi",typed = "mmiississippip") == False
    assert candidate(name = "xxyyzz",typed = "xxyyzzzxxxyyyzzz") == False
    assert candidate(name = "alexandria",typed = "aaalllexxaandria") == True
    assert candidate(name = "qwert",typed = "qqqqwweeeerrrttt") == True
    assert candidate(name = "vtkgn",typed = "vtttkkkgggnnn") == True
    assert candidate(name = "rhinoceros",typed = "rrrhhiinnoocceerrrsss") == False
    assert candidate(name = "longpressed",typed = "lllooonngggpppreesssed") == True
    assert candidate(name = "qwerty",typed = "qqqwwweeeerrrrttyyyy") == True
    assert candidate(name = "xylophone",typed = "xxyyylloophooneee") == True
    assert candidate(name = "rhythm",typed = "rhythm") == True
    assert candidate(name = "aabbcc",typed = "aaabbcccc") == True
    assert candidate(name = "mississippi",typed = "miiisiiisssiiipppii") == False
    assert candidate(name = "queue",typed = "qqquuuuuuuuueee") == False
    assert candidate(name = "abcdefghij",typed = "aabbbbccccddddeeeeffffgggghhhhiiiijjjj") == True
    assert candidate(name = "ababab",typed = "aabbababb") == True
    assert candidate(name = "qlssqwwfw",typed = "qqllssqqwwwwwfwf") == False
    assert candidate(name = "aabbcc",typed = "aabbbcccc") == True
    assert candidate(name = "flower",typed = "ffffllllooower") == True
    assert candidate(name = "programming",typed = "ppprroogrraammmmiinngggg") == True
    assert candidate(name = "mississippi",typed = "mmyisssssippis") == False
    assert candidate(name = "longpress",typed = "lloongggppppreeessss") == True
    assert candidate(name = "aaaabbbbcccc",typed = "aaaabbbbbbcccc") == True
    assert candidate(name = "xy",typed = "xyxyxyxyxyxyxyxy") == False
    assert candidate(name = "unique",typed = "uunniiquee") == True
    assert candidate(name = "longpressed",typed = "lllllooonnggggppprrreeesss") == False
    assert candidate(name = "abcdefgh",typed = "aabbbcccdddddeeeeeffffffgggghhhh") == True
    assert candidate(name = "algorithm",typed = "aalllgggggoooooorrrriiitthhhhhmmmmm") == True
    assert candidate(name = "kikcxmvzi",typed = "kiikcxxmmvvvzzzii") == True
    assert candidate(name = "abcde",typed = "abcdeabcde") == False
    assert candidate(name = "keyboard",typed = "kkkkeeyyyboooaarrdd") == True
    assert candidate(name = "a",typed = "aaaaaaaaaaa") == True
    assert candidate(name = "qwerty",typed = "qqqqwwwwertyyyyy") == True
    assert candidate(name = "leetcode",typed = "lleettcoodde") == True
    assert candidate(name = "laiden",typed = "laidenlaiden") == False
    assert candidate(name = "aabbcc",typed = "aabbbccc") == True
    assert candidate(name = "characters",typed = "ccccchaarrrrrttaaaaccchhhhheeeersss") == False
    assert candidate(name = "xylophone",typed = "xyyylloophooneee") == True
    assert candidate(name = "keyboard",typed = "kkkkeeyyyboaaaarrrddddd") == True
    assert candidate(name = "elephant",typed = "eleelphhhaannnttt") == False
    assert candidate(name = "longnamehere",typed = "lllooonnggnnaaammmeehheerrree") == True
    assert candidate(name = "zebra",typed = "zzzeebrraaa") == True
    assert candidate(name = "function",typed = "fffuunncctttiooonnnn") == True
    assert candidate(name = "abcdefg",typed = "abcdeeeefg") == True
    assert candidate(name = "qwertyuiop",typed = "qqqwwweerrttyyuuiioopp") == True
    assert candidate(name = "hello",typed = "heeeelllllooo") == True
    assert candidate(name = "robert",typed = "rroobbeerrtt") == True
    assert candidate(name = "repeated",typed = "rrreeeepppeeeaaatteeeedd") == True
    assert candidate(name = "rhell",typed = "rhellllllll") == True
    assert candidate(name = "mississippi",typed = "mmiisssssippppi") == False
    assert candidate(name = "supercalifragilisticexpialidocious",typed = "ssuupercccaliiifffragggiilissticceexpiialiiddoouuusss") == False
    assert candidate(name = "triangle",typed = "tttriiaanngggllee") == True
    assert candidate(name = "variable",typed = "vvvvvaaarriiiaabbbblllee") == True
    assert candidate(name = "aabbc",typed = "aabbbcc") == True
    assert candidate(name = "abcd",typed = "aabbbccccdddd") == True
    assert candidate(name = "hello",typed = "heeeelllllllllo") == True
    assert candidate(name = "typing",typed = "ttypiinggggg") == True
    assert candidate(name = "longpressed",typed = "lllllonggggppppreeeesssssssppppeeeedd") == False
    assert candidate(name = "unique",typed = "uunniiqueee") == True
    assert candidate(name = "aaab",typed = "aaaaaabbbb") == True
    assert candidate(name = "",typed = "") == True
    assert candidate(name = "elephant",typed = "eeelleeeephhhhaaaalllllltttt") == False
    assert candidate(name = "ggg",typed = "ggggggggggg") == True
    assert candidate(name = "abcd",typed = "aabbccddeeffgg") == False
    assert candidate(name = "testing",typed = "testtinngg") == True
    assert candidate(name = "abcdef",typed = "aabbccddeeffgg") == False
    assert candidate(name = "sequence",typed = "sseeqqqquuuuuuennnnccccceee") == True
    assert candidate(name = "carlosgomez",typed = "cccarllloossgggoommezz") == True
    assert candidate(name = "elephant",typed = "eeellllepphaaannntt") == True
    assert candidate(name = "aaaaaa",typed = "aaaaaaaaaaaa") == True
    assert candidate(name = "programming",typed = "ppprroogggrraammmiinnnggg") == True
    assert candidate(name = "aaabbbccc",typed = "aabbbccc") == False
    assert candidate(name = "algorithm",typed = "aalllggggorrrrithhhoonnmmm") == False
    assert candidate(name = "abcdabcd",typed = "aabbccddeeffgg") == False
    assert candidate(name = "programming",typed = "pprrrooggggrrraaaaammmmmmiiiiinnnggggggggg") == True
    assert candidate(name = "sequence",typed = "sseeeequuuuueeeennnnncceeeeee") == True
    assert candidate(name = "farruh",typed = "faaarrrruuhhhh") == True
    assert candidate(name = "abcdefghijk",typed = "aabbcdddeeeffggghhhiiiijjjkkk") == True
    assert candidate(name = "xylophone",typed = "xyyyylloophooneee") == True
    assert candidate(name = "xylophone",typed = "xxxyyylloooophooooneee") == True
    assert candidate(name = "abcdefg",typed = "abcdddddeeeffffffggg") == True
    assert candidate(name = "carlos",typed = "cccaaarlllooss") == True
    assert candidate(name = "mississippi",typed = "miisissiipppi") == False
    assert candidate(name = "challenge",typed = "chhaalllaannggeee") == False
    assert candidate(name = "abcd",typed = "aabbccdd") == True
    assert candidate(name = "consistent",typed = "ccconinnsisttteeennnsssstt") == False
    assert candidate(name = "consistent",typed = "cccooonnsiisstteeeennnttt") == True
    assert candidate(name = "abababa",typed = "aabbaabbaabbaaba") == False
    assert candidate(name = "mississippi",typed = "mmiissssssiiipppp") == False
    assert candidate(name = "example",typed = "eexxaammmppllee") == True
    assert candidate(name = "testcase",typed = "tteeeessttccaaase") == True
    assert candidate(name = "aaa",typed = "aaaaa") == True
    assert candidate(name = "friend",typed = "frrriieeedd") == False
    assert candidate(name = "algorithm",typed = "aalllgggggoooooorrriiithhhhhmmmmm") == True
    assert candidate(name = "xyz",typed = "xxxyyyzzz") == True
    assert candidate(name = "xyz",typed = "xxyyyzzz") == True
    assert candidate(name = "longpressed",typed = "lllllooonngggpppprrreeeesssssseeeedd") == True
    assert candidate(name = "complexity",typed = "cccomppplleexxiittiityyy") == False
    assert candidate(name = "zebra",typed = "zzzeeebrrraa") == True
