# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abcba") == 5
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 1
    assert candidate(s = "abcdcba") == 7
    assert candidate(s = "abcdedcba") == 9
    assert candidate(s = "noonhighnoon") == 11
    assert candidate(s = "a") == 1
    assert candidate(s = "cbbd") == 2
    assert candidate(s = "ab") == 1
    assert candidate(s = "aabaa") == 5
    assert candidate(s = "abcde") == 1
    assert candidate(s = "racecar") == 7
    assert candidate(s = "abcb") == 3
    assert candidate(s = "bcbab") == 3
    assert candidate(s = "noon") == 4
    assert candidate(s = "banana") == 5
    assert candidate(s = "deeee") == 4
    assert candidate(s = "agbdba") == 5
    assert candidate(s = "abccba") == 6
    assert candidate(s = "aaaa") == 4
    assert candidate(s = "character") == 5
    assert candidate(s = "level") == 5
    assert candidate(s = "bbbab") == 4
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba") == 1
    assert candidate(s = "abcdefg") == 1
    assert candidate(s = "aabcdefggfedcbagfedcba") == 16
    assert candidate(s = "noonappa") == 4
    assert candidate(s = "aacaagttaccagtcacaagttaacaagttaccagtcacaagttaac") == 33
    assert candidate(s = "abbdbba") == 7
    assert candidate(s = "abracadabra") == 7
    assert candidate(s = "abcabcabcabc") == 7
    assert candidate(s = "levelmadam") == 5
    assert candidate(s = "abbaababa") == 8
    assert candidate(s = "abcdaedcba") == 9
    assert candidate(s = "babbbabbbbabbb") == 12
    assert candidate(s = "tattarrattat") == 12
    assert candidate(s = "aaaabaaaa") == 9
    assert candidate(s = "noonnoon") == 8
    assert candidate(s = "abccbaabccba") == 12
    assert candidate(s = ('elrmenmet',)) == 1
    assert candidate(s = "aabbccddeeaabbccddeeff") == 6
    assert candidate(s = "madamracecar") == 7
    assert candidate(s = "nogood") == 3
    assert candidate(s = "abcdcbazxyzyxcba") == 11
    assert candidate(s = "epelppel") == 5
    assert candidate(s = "aabaaabbabaaabbbaabaa") == 19
    assert candidate(s = "abcdaabcd") == 4
    assert candidate(s = "zazalxlkjlkjlkjljlkjljlkjlkjljlkjljlkjljlkjljlkjljlkjljlkjljlkjlkjljlkjljlkjljlkjljlkjljlkjlkjljlkjljlkjljlkjl") == 81
    assert candidate(s = "xyzabcba") == 5
    assert candidate(s = "aabacbebebe") == 5
    assert candidate(s = "kayak") == 5
    assert candidate(s = "rotorotor") == 9
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 52
    assert candidate(s = "zyxzyxzyxzyxzyx") == 9
    assert candidate(s = "elkfaodfnofowefwaefewfafwefawfawfawfawfawfawfawfawfawfawfaw") == 35
    assert candidate(s = "abcdefggfedcba") == 14
    assert candidate(s = "attacking") == 4
    assert candidate(s = "nursesrun") == 9
    assert candidate(s = "aabbccddeeaabbccddeeaabbccddeeaabbccddeeaabbccddeeaabbccddeeaabbccdd") == 26
    assert candidate(s = "aibohphobia") == 11
    assert candidate(s = "abcaebcabcbcabcbc") == 11
    assert candidate(s = "deeeeved") == 7
    assert candidate(s = "madam") == 5
    assert candidate(s = "ababababababa") == 13
    assert candidate(s = "radar") == 5
    assert candidate(s = "pwwkew") == 3
    assert candidate(s = "aabbccddeeeffggghhhhiiii") == 4
    assert candidate(s = "bcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbc") == 109
    assert candidate(s = "abcdefghikjlmnopqrstuvwxyz") == 1
    assert candidate(s = "xyzabcdedcbazyx") == 15
    assert candidate(s = "aabcbab") == 5
    assert candidate(s = "abcadacaabc") == 7
    assert candidate(s = "aabaaa") == 5
    assert candidate(s = "anana") == 5
    assert candidate(s = "aabbabbaaabbabbaaabbabbaaabbabba") == 31
    assert candidate(s = "aabbccddeeffgg") == 2
    assert candidate(s = "xyzyxzyxzyxzyxzyx") == 13
    assert candidate(s = "aabaaaabaaabaaaba") == 15
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 2
    assert candidate(s = "longestpalindromicsubsequence") == 9
    assert candidate(s = "zxcvbnnbvxcz") == 10
    assert candidate(s = "racecarannakayak") == 8
    assert candidate(s = "abcdefghgfedcba") == 15
    assert candidate(s = "abcdefghiijkmlkjihgfedcba") == 23
    assert candidate(s = "mimimum") == 5
    assert candidate(s = "aannnaaaa") == 7
    assert candidate(s = "repaper") == 7
    assert candidate(s = "mamadmim") == 5
    assert candidate(s = "mamad") == 3
    assert candidate(s = "abacdfgdcaba") == 11
    assert candidate(s = "abcddcba") == 8
    assert candidate(s = "civic") == 5
    assert candidate(s = "rotor") == 5
    assert candidate(s = "abcdefghihgfedcba") == 17
    assert candidate(s = "intersubjective") == 7
    assert candidate(s = "lrfipxxl") == 4
    assert candidate(s = "mississippi") == 7
    assert candidate(s = "madaminnadamsandnoon") == 10
    assert candidate(s = "forgeeksskeegfor") == 12
    assert candidate(s = "aaaaabbbbbccccc") == 5
    assert candidate(s = "refer") == 5
