# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(str1 = "aaa",str2 = "a") == True
    assert candidate(str1 = "hello",str2 = "heo") == True
    assert candidate(str1 = "abcd",str2 = "bd") == True
    assert candidate(str1 = "zyxwvutsrqponmlkjihgfedcba",str2 = "abcdefghijklmnopqrstuvwxyz") == False
    assert candidate(str1 = "abacaba",str2 = "aaa") == True
    assert candidate(str1 = "xyz",str2 = "yza") == True
    assert candidate(str1 = "abc",str2 = "abc") == True
    assert candidate(str1 = "ab",str2 = "d") == False
    assert candidate(str1 = "az",str2 = "ba") == True
    assert candidate(str1 = "abcde",str2 = "aec") == False
    assert candidate(str1 = "azazaz",str2 = "zzz") == True
    assert candidate(str1 = "abcde",str2 = "ae") == True
    assert candidate(str1 = "aabbccddeeff",str2 = "abcdef") == True
    assert candidate(str1 = "abcde",str2 = "ace") == True
    assert candidate(str1 = "a",str2 = "b") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "abcdefghijklmnopqrstuvwxyz") == True
    assert candidate(str1 = "aabbcc",str2 = "abc") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "z") == True
    assert candidate(str1 = "aaa",str2 = "b") == True
    assert candidate(str1 = "abc",str2 = "acb") == False
    assert candidate(str1 = "zc",str2 = "ad") == True
    assert candidate(str1 = "abcxyz",str2 = "adz") == True
    assert candidate(str1 = "abc",str2 = "ad") == True
    assert candidate(str1 = "abcd",str2 = "dddd") == False
    assert candidate(str1 = "a",str2 = "a") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "za") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "gh") == True
    assert candidate(str1 = "mnopqrstuvwxyza",str2 = "mnopqr") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = ('adaceg',)) == False
    assert candidate(str1 = "acegikmoqsuwy",str2 = "abcdefghijklmnopqrstuvwxyz") == False
    assert candidate(str1 = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc",str2 = "abcabcabc") == True
    assert candidate(str1 = "a",str2 = "z") == False
    assert candidate(str1 = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd",str2 = "acegikmoqsuwy") == False
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",str2 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == False
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyza",str2 = "abcdefghijklmnopqrstuvwxyza") == True
    assert candidate(str1 = "b",str2 = "a") == False
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "op") == True
    assert candidate(str1 = "aaabbbcccdddeeefffggghhhiiiijjjjkkkkllllmmmnnnooopppqqqrrrssstttuuuvvvwwwxxxyyyzzz",str2 = "abcdefghijklmnopqrstuvwxyz") == True
    assert candidate(str1 = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz",str2 = ('xyzxyzxyz',)) == False
    assert candidate(str1 = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",str2 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == False
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",str2 = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "wx") == True
    assert candidate(str1 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",str2 = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "acegikmoqsuwy") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "qr") == True
    assert candidate(str1 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",str2 = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyzaaa",str2 = "abcdefghijklmnopqrstuvwxyz") == True
    assert candidate(str1 = "abczyxwvutsrqponmlkjihgfedcba",str2 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == False
    assert candidate(str1 = "mnopqrstuvwxyza",str2 = "monp") == False
    assert candidate(str1 = "mnopqrstuvwxyza",str2 = "mno") == True
    assert candidate(str1 = "zyxwvutsrqponmlkjihgfedcba",str2 = "a") == True
    assert candidate(str1 = "abcabcabcabcabcabc",str2 = ('accaaa',)) == False
    assert candidate(str1 = "abz",str2 = "abc") == False
    assert candidate(str1 = "abacabadabacaba",str2 = "abcd") == True
    assert candidate(str1 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",str2 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == True
    assert candidate(str1 = "mnopqrstuvwxyza",str2 = "nopqrstuvwxyz") == True
    assert candidate(str1 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",str2 = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "zxcvbnmlkjhgfedcba") == False
    assert candidate(str1 = "abcdabcdabcdabcdabcdabcdabcd",str2 = "dddddddddd") == True
    assert candidate(str1 = "mnopqrstuvwxyza",str2 = "nopqrstuvwy") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",str2 = "zzz") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",str2 = "zz") == True
    assert candidate(str1 = "zyxwvutsrqponmlkjihgfedcba",str2 = "mnopqrst") == False
    assert candidate(str1 = "aaaaabbbbbaaaaabbbbbaaaaabbbbb",str2 = ('aaaaaabbbbb',)) == False
    assert candidate(str1 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",str2 = ('zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',)) == False
    assert candidate(str1 = "zyxwvutsrqponmlkjihgfedcba",str2 = ('abcdefghijklmnopqrstuvwxyz',)) == False
    assert candidate(str1 = "abcdeffedcbaz",str2 = "zzzz") == False
    assert candidate(str1 = "ababababababababababababababab",str2 = "bababa") == True
    assert candidate(str1 = "mnopqrstuvwxyza",str2 = "mn") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "abcdefghijklmnopqrstuvwxyza") == False
    assert candidate(str1 = "abcdabcdabcd",str2 = "abdc") == True
    assert candidate(str1 = "mnopqrstuvwxyza",str2 = "mnopqrstu") == True
    assert candidate(str1 = "aaabbbccc",str2 = "abc") == True
    assert candidate(str1 = "zyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyx",str2 = "zyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyx") == True
    assert candidate(str1 = "bdfhjlnprtvxz",str2 = "abcdefghijklmnopqrstuvwxyz") == False
    assert candidate(str1 = "abcdeffedcba",str2 = "abcdef") == True
    assert candidate(str1 = "abcabcabcabcabcabcabcabc",str2 = "acbacbacbacbacbacbacbacbac") == False
    assert candidate(str1 = "mnopqrstuvwxyza",str2 = "mnopqrs") == True
    assert candidate(str1 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",str2 = "zzz") == True
    assert candidate(str1 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzz",str2 = "aaaaaa") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "ef") == True
    assert candidate(str1 = "abcdeffedcba",str2 = "ace") == True
    assert candidate(str1 = "abcabcabcabcabcabcabcabcabcabc",str2 = "aaa") == True
    assert candidate(str1 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",str2 = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == False
    assert candidate(str1 = "z",str2 = "a") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == False
    assert candidate(str1 = "xyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",str2 = "ad") == False
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyzaabcdefghijklmnopqrstuvwxyz",str2 = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == True
    assert candidate(str1 = "zyxwvutsrqponmlkjihgfedcba",str2 = "zaa") == False
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "bd") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyzaabcdefghijklmnopqrstuvwxyz",str2 = "abcdefghijklmnopqrstuvwxyz") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",str2 = "zabc") == True
    assert candidate(str1 = "aaaabbbbccccddddaaaabbbbccccdddd",str2 = "abcdabcd") == True
    assert candidate(str1 = "abcxyz",str2 = "abcxyz") == True
    assert candidate(str1 = "abcde",str2 = "edcba") == False
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == False
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "mn") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "zzz") == False
    assert candidate(str1 = "mnopqrsmnopqrsmnopqrs",str2 = "mnopqrspqrsmn") == True
    assert candidate(str1 = "mnopqrstuvwxyza",str2 = "mnopqrstv") == True
    assert candidate(str1 = "zyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyx",str2 = "zyxzyxzyx") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "zzzzzzzzzz") == False
    assert candidate(str1 = "abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde",str2 = ('abcdabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc',)) == False
    assert candidate(str1 = "mnopqrstuvwxyza",str2 = "mnopqrst") == True
    assert candidate(str1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",str2 = "abcdefghijklmnopqrstuvwxyz") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",str2 = "abcdefghijklmnopqrstuvwxyz") == True
    assert candidate(str1 = "aaaabbbbcccc",str2 = "abac") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "uv") == True
    assert candidate(str1 = "xyzz",str2 = "az") == True
    assert candidate(str1 = "mnopqrstuvwxyza",str2 = "mnop") == True
    assert candidate(str1 = "mnopqrstuvwxyzabcdefghijk",str2 = "mnopqrstuvwxyz") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",str2 = "zyxwvutsrqponmlkjihgfedcba") == False
    assert candidate(str1 = "zzzzzzzzzzzzzzzzzzzz",str2 = "aaaaaaaaaa") == True
    assert candidate(str1 = "zyxwvutsrqponmlkjihgfedcba",str2 = "az") == True
    assert candidate(str1 = "abz",str2 = "acz") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",str2 = ('zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',)) == False
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "kl") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyza",str2 = ('abcdefghijklmnopqrstuvwxz',)) == False
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyza",str2 = "abcdefghijklmnopqrstuvwxyz") == True
    assert candidate(str1 = "mnopqrstuvwxyza",str2 = "m") == True
    assert candidate(str1 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",str2 = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "ij") == True
    assert candidate(str1 = "abcdexyz",str2 = "acz") == True
    assert candidate(str1 = "zzz",str2 = "aaa") == True
    assert candidate(str1 = "mnopqrstuvwxyza",str2 = "mnopqrstvw") == True
    assert candidate(str1 = "abcxyz",str2 = "zzz") == False
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "ac") == True
    assert candidate(str1 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",str2 = ('zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',)) == False
    assert candidate(str1 = "zaaaaaaaaabcdezzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",str2 = "ad") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyza",str2 = ('abcdefghijklmnopqrstuvwxyzz',)) == False
    assert candidate(str1 = "aaaaazzzzzaaaaazzzzzaaaaazzzzz",str2 = ('zzzzzaaaaazzzzz',)) == False
    assert candidate(str1 = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc",str2 = "adadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadad") == False
    assert candidate(str1 = "bxyz",str2 = "abcd") == False
    assert candidate(str1 = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",str2 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == False
    assert candidate(str1 = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",str2 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == False
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "bdfhjlnprtvxz") == True
    assert candidate(str1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",str2 = "abcdefghijklmnopqrstuvwxyza") == True
    assert candidate(str1 = "yzabcd",str2 = "ad") == True
    assert candidate(str1 = "abcabcabcabcabcabcabcabc",str2 = "aaabbbccc") == True
    assert candidate(str1 = "mnopqrstuvwxyza",str2 = "") == True
    assert candidate(str1 = "aaaabbbbccccddddeeeeffffgggghhhhiiii",str2 = "abcdefghi") == True
    assert candidate(str1 = "aaaabbbbcccc",str2 = "abc") == True
    assert candidate(str1 = "abacabadabacaba",str2 = "abc") == True
    assert candidate(str1 = "aaaabbbbcccc",str2 = ('abcb',)) == False
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "zabcdefghijklmnopqrstuvwxyz") == False
    assert candidate(str1 = "zyzzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyz",str2 = ('zyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyz',)) == False
    assert candidate(str1 = "mnopqrstuvwxyza",str2 = "mnopq") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyza",str2 = "xyz") == True
    assert candidate(str1 = "abcdabcdabcdabcdabcdabcdabcdabcd",str2 = ('abcdabcdabcd',)) == False
    assert candidate(str1 = "zyxwvutsrqponmlkjihgfedcba",str2 = "azbycxdwevfugthsisrjrqponmlkjihgfedcba") == False
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "yz") == True
    assert candidate(str1 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",str2 = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == True
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "st") == True
