# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(text = "bbbb",pattern = "bb") == 10
    assert candidate(text = "aaaaa",pattern = "aa") == 15
    assert candidate(text = "zzzz",pattern = "zz") == 10
    assert candidate(text = "abdcdbc",pattern = "ac") == 4
    assert candidate(text = "abc",pattern = "ca") == 1
    assert candidate(text = "babab",pattern = "ba") == 6
    assert candidate(text = "zzz",pattern = "zz") == 6
    assert candidate(text = "abcabc",pattern = "aa") == 3
    assert candidate(text = "a",pattern = "ab") == 1
    assert candidate(text = "ab",pattern = "ba") == 1
    assert candidate(text = "aabb",pattern = "ab") == 6
    assert candidate(text = "aaa",pattern = "aa") == 6
    assert candidate(text = "b",pattern = "ab") == 1
    assert candidate(text = "aaaa",pattern = "aa") == 10
    assert candidate(text = "xyzxyz",pattern = "yx") == 3
    assert candidate(text = "abcabc",pattern = "ac") == 5
    assert candidate(text = "xyz",pattern = "xz") == 2
    assert candidate(text = "",pattern = "ab") == 0
    assert candidate(text = "",pattern = "xy") == 0
    assert candidate(text = "abxyabxyabxy",pattern = "bx") == 9
    assert candidate(text = "zxyzxyzxyz",pattern = "yz") == 10
    assert candidate(text = "xyzyzyzyzyzx",pattern = "yx") == 10
    assert candidate(text = "zzzzzzzzzzz",pattern = "zz") == 66
    assert candidate(text = "pqrsrstq",pattern = "pq") == 4
    assert candidate(text = "bbabbaaa",pattern = "ba") == 18
    assert candidate(text = "ababababab",pattern = "ba") == 15
    assert candidate(text = "aaaaabbbbb",pattern = "ab") == 30
    assert candidate(text = "aaabbbccc",pattern = "ac") == 12
    assert candidate(text = "abacabacaba",pattern = "ac") == 12
    assert candidate(text = "abcdefabcdef",pattern = "cf") == 5
    assert candidate(text = "bbaabb",pattern = "ba") == 8
    assert candidate(text = "bcbcbcbcbb",pattern = "bc") == 16
    assert candidate(text = "bbaabaabaabbb",pattern = "ab") == 31
    assert candidate(text = "bbbbba",pattern = "ba") == 10
    assert candidate(text = "acbacbacba",pattern = "ac") == 10
    assert candidate(text = "mnopqr",pattern = "pq") == 2
    assert candidate(text = "xyxzyxzyxzyx",pattern = "yx") == 15
    assert candidate(text = "zzyzxzyzxzy",pattern = "yz") == 12
    assert candidate(text = "xyyxxyyxxyy",pattern = "yx") == 18
    assert candidate(text = "aabbccdd",pattern = "ac") == 6
    assert candidate(text = "abcdabcdabcd",pattern = "ac") == 9
    assert candidate(text = "mississippi",pattern = "is") == 10
    assert candidate(text = "zzzzzzzzzz",pattern = "zz") == 55
    assert candidate(text = "ababababab",pattern = "ab") == 20
    assert candidate(text = "aabbaabbaabbaabbaabbaabbaabbaabb",pattern = "bb") == 136
    assert candidate(text = "qwertyuiop",pattern = "qp") == 2
    assert candidate(text = "aaaaaaa",pattern = "aa") == 28
    assert candidate(text = "abcdabcdabcd",pattern = "da") == 6
    assert candidate(text = "zzzzz",pattern = "zz") == 15
    assert candidate(text = "abababababab",pattern = "ba") == 21
    assert candidate(text = "abababababa",pattern = "ab") == 21
    assert candidate(text = "abcabcabcabc",pattern = "ac") == 14
    assert candidate(text = "aabbbcc",pattern = "ac") == 6
    assert candidate(text = "aabbaabbaabbaabbaabb",pattern = "aa") == 55
    assert candidate(text = "babcbabcba",pattern = "bc") == 11
    assert candidate(text = "aabbccddeeff",pattern = "bf") == 6
    assert candidate(text = "abcabcabc",pattern = "ab") == 9
    assert candidate(text = "bcbcbcbcbc",pattern = "bc") == 20
    assert candidate(text = "xyxxyxyxyx",pattern = "yx") == 17
    assert candidate(text = "abcabcabcabcabcabc",pattern = "ca") == 21
    assert candidate(text = "xzyxzyxzyz",pattern = "zy") == 10
    assert candidate(text = "zzzzzz",pattern = "zz") == 21
    assert candidate(text = "aabbbaaabbbb",pattern = "ab") == 33
    assert candidate(text = "aaabbb",pattern = "ab") == 12
    assert candidate(text = "nnaaaannaa",pattern = "an") == 14
    assert candidate(text = "xyxyxyxyxy",pattern = "yx") == 15
    assert candidate(text = "cccccc",pattern = "cc") == 21
    assert candidate(text = "abacabadabacaba",pattern = "ba") == 24
    assert candidate(text = "bababababababababa",pattern = "bb") == 45
    assert candidate(text = "dcbabcdabcba",pattern = "ab") == 9
    assert candidate(text = "xyzzyxzyxzyxzyx",pattern = "zy") == 19
    assert candidate(text = "aaaaaabbbb",pattern = "ab") == 30
    assert candidate(text = "cccccccc",pattern = "cc") == 36
    assert candidate(text = "babcbacbab",pattern = "bc") == 10
    assert candidate(text = "abcdefghijklmnopqrstuvwxyz",pattern = "zy") == 1
    assert candidate(text = "zzzyyy",pattern = "yz") == 3
    assert candidate(text = "zzzzzzzzzzzzzzzzzzzzzzzzzzzz",pattern = "zz") == 406
    assert candidate(text = "mnopqrqpomn",pattern = "mn") == 5
    assert candidate(text = "aabbaabb",pattern = "bb") == 10
    assert candidate(text = "aabbccddeeffgg",pattern = "ag") == 6
    assert candidate(text = "ccbaaa",pattern = "ab") == 3
    assert candidate(text = "xyzzyxzyzxzyxzyx",pattern = "yz") == 20
    assert candidate(text = "aaaaaaaaa",pattern = "aa") == 45
    assert candidate(text = "aabbaabb",pattern = "ab") == 16
    assert candidate(text = "bababababababa",pattern = "ba") == 35
    assert candidate(text = "bababababa",pattern = "ba") == 20
    assert candidate(text = "zyxwvutsrqponmlkjihgfedcba",pattern = "yz") == 1
    assert candidate(text = "qqqqqqqqqq",pattern = "qp") == 10
    assert candidate(text = "qwertyuiopasdfghjklzxcvbnm",pattern = "mn") == 1
    assert candidate(text = "abcabcdabc",pattern = "bc") == 9
    assert candidate(text = "zzzzyyyy",pattern = "zy") == 20
    assert candidate(text = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",pattern = "xz") == 6
    assert candidate(text = "abacabacab",pattern = "ac") == 11
    assert candidate(text = "fedcba",pattern = "ab") == 1
    assert candidate(text = "ccccbbbaaa",pattern = "ba") == 12
    assert candidate(text = "mmnnnmmnnm",pattern = "mn") == 19
    assert candidate(text = "abcabcabc",pattern = "ba") == 6
    assert candidate(text = "xyzxyzxyzxyz",pattern = "yx") == 10
    assert candidate(text = "qqqqqppppp",pattern = "pq") == 5
    assert candidate(text = "aaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbb",pattern = "ba") == 20
    assert candidate(text = "abbaba",pattern = "ab") == 7
    assert candidate(text = "zzzzzzzzzzzzz",pattern = "zz") == 91
    assert candidate(text = "zzyzxzyzxzyz",pattern = "yz") == 16
    assert candidate(text = "aabbaabb",pattern = "aa") == 10
    assert candidate(text = "abcabcabcabcabc",pattern = "ab") == 20
    assert candidate(text = "babbabababababababa",pattern = "ba") == 63
    assert candidate(text = "aaabbbcccddd",pattern = "ad") == 12
    assert candidate(text = "abcdef",pattern = "fe") == 1
    assert candidate(text = "bbbbbbbbbb",pattern = "bb") == 55
    assert candidate(text = "bbbbbaaaaa",pattern = "ab") == 5
    assert candidate(text = "abcde",pattern = "ae") == 2
    assert candidate(text = "abracadabra",pattern = "ra") == 10
    assert candidate(text = "abcdefghij",pattern = "ae") == 2
    assert candidate(text = "aaabbbccc",pattern = "ab") == 12
    assert candidate(text = "abcdefghij",pattern = "aj") == 2
    assert candidate(text = "xyzzyxzyxzyxzyxzyxzyxzyx",pattern = "zx") == 43
    assert candidate(text = "mmnmmnmmn",pattern = "mn") == 18
    assert candidate(text = "aabbccddeeff",pattern = "ef") == 6
    assert candidate(text = "zzzzzzzz",pattern = "zz") == 36
    assert candidate(text = "ccccccc",pattern = "cc") == 28
    assert candidate(text = "abcabcabc",pattern = "bc") == 9
    assert candidate(text = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",pattern = "az") == 6
    assert candidate(text = "abcdefghij",pattern = "af") == 2
    assert candidate(text = "bbbbbaaaaa",pattern = "ba") == 30
    assert candidate(text = "xyzyxzyxzy",pattern = "yx") == 9
    assert candidate(text = "aabccbaa",pattern = "ac") == 8
    assert candidate(text = "abacabadabacaba",pattern = "ab") == 24
    assert candidate(text = "aabccccdddd",pattern = "cd") == 20
    assert candidate(text = "aaaaaaaaaa",pattern = "aa") == 55
    assert candidate(text = "aaaabbbb",pattern = "ab") == 20
    assert candidate(text = "aaaaaaaaaaaabbbbbbbbbbbb",pattern = "ab") == 156
    assert candidate(text = "abcdefghijklnmopqrstuvwxyz",pattern = "az") == 2
    assert candidate(text = "abcd",pattern = "da") == 1
    assert candidate(text = "abcdabcdabcd",pattern = "ad") == 9
    assert candidate(text = "lkjqwpmr",pattern = "qw") == 2
    assert candidate(text = "aabbaabbcc",pattern = "ab") == 16
    assert candidate(text = "abcabcabc",pattern = "ac") == 9
    assert candidate(text = "baabbaab",pattern = "ba") == 12
