# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "racecar",k = 2) == 1
    assert candidate(s = "mnoonm",k = 2) == 1
    assert candidate(s = "zzzzzz",k = 1) == 6
    assert candidate(s = "abcde",k = 3) == 0
    assert candidate(s = "abcdeedcba",k = 2) == 1
    assert candidate(s = "zz",k = 1) == 2
    assert candidate(s = "adbcda",k = 2) == 0
    assert candidate(s = "",k = 1) == 0
    assert candidate(s = "abcde",k = 1) == 5
    assert candidate(s = "aaaaa",k = 2) == 2
    assert candidate(s = "racecar",k = 3) == 1
    assert candidate(s = "abbaeaeabba",k = 3) == 3
    assert candidate(s = "abbaabba",k = 3) == 2
    assert candidate(s = "noonhighnoon",k = 4) == 2
    assert candidate(s = "abacdfgdcaba",k = 3) == 2
    assert candidate(s = "aaaa",k = 2) == 2
    assert candidate(s = "a",k = 1) == 1
    assert candidate(s = "abcdedcba",k = 5) == 1
    assert candidate(s = "racecarannakayak",k = 3) == 3
    assert candidate(s = "abcba",k = 5) == 1
    assert candidate(s = "abaccdbbd",k = 3) == 2
    assert candidate(s = "abbaeae",k = 2) == 2
    assert candidate(s = "z",k = 1) == 1
    assert candidate(s = "aaabaaaabaaaa",k = 5) == 2
    assert candidate(s = "levellevellevel",k = 5) == 3
    assert candidate(s = "abcabcabcabc",k = 3) == 0
    assert candidate(s = "ababababa",k = 3) == 3
    assert candidate(s = "abcbaabccba",k = 3) == 2
    assert candidate(s = "level",k = 5) == 1
    assert candidate(s = "xyxxyxyxyx",k = 1) == 10
    assert candidate(s = "aabbaaabbbaaaa",k = 2) == 6
    assert candidate(s = "ababababababab",k = 2) == 4
    assert candidate(s = "rotorreferredder",k = 4) == 3
    assert candidate(s = "popopopopopop",k = 3) == 4
    assert candidate(s = "abaaaaba",k = 4) == 1
    assert candidate(s = "xyxzyzyzyxzyx",k = 3) == 3
    assert candidate(s = "madamimadam",k = 2) == 3
    assert candidate(s = "aaaaaaaaaaaaaaaaaa",k = 10) == 1
    assert candidate(s = "abbaabbaabba",k = 4) == 3
    assert candidate(s = "aabbccddeeff",k = 2) == 6
    assert candidate(s = "rotor",k = 5) == 1
    assert candidate(s = "abcddcbaabcddcba",k = 6) == 2
    assert candidate(s = "palindromemordnilap",k = 6) == 1
    assert candidate(s = "aabbccddeeefffggghhhiii",k = 4) == 0
    assert candidate(s = "xyxzyzyzxzyxzyx",k = 3) == 3
    assert candidate(s = "aaaaaaaabaaaa",k = 5) == 2
    assert candidate(s = "levelracecaraabba",k = 4) == 3
    assert candidate(s = "racecarannakayak",k = 5) == 2
    assert candidate(s = "abccbaabccba",k = 3) == 2
    assert candidate(s = "abcabcabcabcabcabcabc",k = 3) == 0
    assert candidate(s = "abcdedcbaedcbba",k = 5) == 1
    assert candidate(s = "noonnoonnoon",k = 3) == 3
    assert candidate(s = "abbaaccddccaaabbbcccdd",k = 3) == 5
    assert candidate(s = "abcbabcba",k = 5) == 1
    assert candidate(s = "aabbabbaaabbabba",k = 4) == 3
    assert candidate(s = "abbaaccddccbaabba",k = 3) == 3
    assert candidate(s = "abbaacccbaaabbcc",k = 3) == 3
    assert candidate(s = "civiccivic",k = 4) == 2
    assert candidate(s = "aaabaaaacaaaaaa",k = 3) == 4
    assert candidate(s = "abracadabra",k = 3) == 1
    assert candidate(s = "abcdcbaabcdcba",k = 5) == 2
    assert candidate(s = "xyzyzyzyzyzyzyzy",k = 2) == 5
    assert candidate(s = "madamracecarlevel",k = 5) == 3
    assert candidate(s = "xyxzyzyzyzxzyzyx",k = 3) == 5
    assert candidate(s = "bananaabacaxxx",k = 3) == 3
    assert candidate(s = "noonnoonnoon",k = 4) == 3
    assert candidate(s = "abcdefghij",k = 3) == 0
    assert candidate(s = "zzzzyyyyxxxx",k = 4) == 3
    assert candidate(s = "aaaabbbbccccdddd",k = 4) == 4
    assert candidate(s = "civicracecardeified",k = 3) == 3
    assert candidate(s = "aabbccddeeffgg",k = 2) == 7
    assert candidate(s = "madamimadam",k = 5) == 2
    assert candidate(s = "aaaabaaaabaaaaabaaabaaa",k = 2) == 9
    assert candidate(s = "racecar",k = 6) == 1
    assert candidate(s = "xyxxyxyxyxyx",k = 2) == 4
    assert candidate(s = "abcbabcba",k = 3) == 2
    assert candidate(s = "abcabcabcabc",k = 1) == 12
    assert candidate(s = "abcdefgfedcba",k = 7) == 1
    assert candidate(s = "mamadadadadammadam",k = 3) == 5
    assert candidate(s = "madamimadam",k = 3) == 3
    assert candidate(s = "babaddabba",k = 3) == 2
    assert candidate(s = "aabbabaaaabbabaab",k = 3) == 4
    assert candidate(s = "babbbabbbab",k = 3) == 3
    assert candidate(s = "aabaaaabbbaaa",k = 3) == 4
    assert candidate(s = "aabbaabbaaabbbaabbaab",k = 3) == 4
    assert candidate(s = "abccbaabc",k = 4) == 1
    assert candidate(s = "abracadabra",k = 5) == 0
    assert candidate(s = "abbaabbaabba",k = 2) == 5
    assert candidate(s = "aaaaaabbbbbbaaaaaabbbbb",k = 5) == 4
    assert candidate(s = "abcbaabababaabcba",k = 3) == 4
    assert candidate(s = "abcabcabc",k = 2) == 0
    assert candidate(s = "abccbaabcabcabcabcba",k = 5) == 2
    assert candidate(s = "abccbaabcba",k = 5) == 2
    assert candidate(s = "mississippi",k = 3) == 2
    assert candidate(s = "abbaabbabbaabb",k = 2) == 6
    assert candidate(s = "abcdefedcba",k = 5) == 1
    assert candidate(s = "abcdefghihgfedcba",k = 7) == 1
    assert candidate(s = "noonmoonnoonmoon",k = 4) == 2
    assert candidate(s = "abcdefedcbafedcbabcdef",k = 5) == 2
    assert candidate(s = "abbaabba",k = 2) == 3
    assert candidate(s = "deeeeinedede",k = 4) == 2
    assert candidate(s = "abcdedcba",k = 4) == 1
    assert candidate(s = "aabbccddeeeffgg",k = 2) == 7
    assert candidate(s = "abcdedcbaabacdfgdcaba",k = 5) == 1
    assert candidate(s = "zzzzyyyxxxwwvvuuttssrrqqppoonnmmlkkjjiihhggffeeddccbbaaa",k = 4) == 1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 2) == 26
    assert candidate(s = "aaaaabbbaaaaa",k = 4) == 3
    assert candidate(s = "abacabadabacaba",k = 4) == 2
    assert candidate(s = "madamimadam",k = 4) == 2
