# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "zzzzzzzzz") == 2
    assert candidate(s = "aaabbbccc") == 4
    assert candidate(s = "aabbaa") == 4
    assert candidate(s = "abababab") == 4
    assert candidate(s = "aabacbebebe") == 6
    assert candidate(s = "abacabadabacaba") == 5
    assert candidate(s = "abab") == 4
    assert candidate(s = "abcabcabc") == 6
    assert candidate(s = "aabbc") == 5
    assert candidate(s = "aabacbacbac") == 6
    assert candidate(s = "ababababab") == 4
    assert candidate(s = "abcabc") == 6
    assert candidate(s = "aabb") == 4
    assert candidate(s = "zzzzyyxx") == 6
    assert candidate(s = "xyzxyzxyz") == 6
    assert candidate(s = "bcbbbcba") == 4
    assert candidate(s = "zzzzzzzzzz") == 2
    assert candidate(s = "zzzzzzzzzzzz") == 2
    assert candidate(s = "abacabad") == 5
    assert candidate(s = "abababababab") == 4
    assert candidate(s = "aabbccddeeffgg") == 14
    assert candidate(s = "aaabbb") == 4
    assert candidate(s = "aaaa") == 2
    assert candidate(s = "aabbccddeeffgghh") == 16
    assert candidate(s = "aabbccddeeff") == 12
    assert candidate(s = "abcdeabcde") == 10
    assert candidate(s = "aabbcc") == 6
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 52
    assert candidate(s = "aabbccddeeffgghhiijj") == 20
    assert candidate(s = "abacaba") == 5
    assert candidate(s = "abcdefg") == 7
    assert candidate(s = "aaabbbaaabbbaaabbbaaabbbaaabbbaaabbbaaabbbaaabbbaaabbbaaabbbaaabbbaaabbbaaabbb") == 4
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzz") == 52
    assert candidate(s = "aabbaaabbbaaaabbbaaaa") == 4
    assert candidate(s = "abacabadabacabadabacaba") == 5
    assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghij") == 20
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 6
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 6
    assert candidate(s = "aaaabbbbccccaaaabbbbccccaaaabbbbccccaaaabbbbccccaaaabbbbcccc") == 4
    assert candidate(s = "mnopqrsmnopqrsmnopqrsmnopqrsmnopqrsmnopqrsmnopqrsmnopqrsmnopqrs") == 14
    assert candidate(s = "abcdabcdeabcdabcdeabcdabcdeabcdabcdeabcdabcdeabcdabcdeabcdabcdeabcdabcdabcdabcd") == 10
    assert candidate(s = "aaabbbcccdddeeefffggghhhiiiijjjkkklllmmmnnnooopppqqqrrrssstttuuuvvvwwwxxxyyyzzz") == 4
    assert candidate(s = "aabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabb") == 4
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc") == 6
    assert candidate(s = "aabbaabbaabbaabbaabbaabbaabbaabb") == 4
    assert candidate(s = "abcdefghijklaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 52
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 52
    assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij") == 20
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzyxwvutsrqponmlkjihgfedcba") == 52
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 6
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz") == 2
    assert candidate(s = "aabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabb") == 4
    assert candidate(s = "xyzzzyxyzzzyxyzzzyxyzzzyxyzzzyxyzzzyxyzzzyxyzzzyxyzzzyxyzzzyxyzzzyxyzzz") == 5
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabad") == 5
    assert candidate(s = "aaabbbcccdddeeefffggghhhiiijjjkkklllmmmnnnoooppqqrrrsssttuuvvwwxxyyzz") == 16
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzzzzzzzz") == 27
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 52
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzz") == 52
    assert candidate(s = "zzzzzyzyzyzyzyzyzy") == 4
    assert candidate(s = "abcabcbacbacbabcabcabcabcabcabcabc") == 6
    assert candidate(s = "abcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdef") == 12
    assert candidate(s = "abcabcabcabcabcabc") == 6
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 2
    assert candidate(s = "aabbaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzz") == 52
    assert candidate(s = "aabccddeeffaabbccddeeffaabbccddeeff") == 12
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzyyxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccbbaa") == 52
    assert candidate(s = "abcdefghijklmnopqrstuvabcdefghijklmnopqrstuv") == 44
    assert candidate(s = "aabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabba") == 4
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzz") == 52
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzz") == 52
    assert candidate(s = "aabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabb") == 4
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 8
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 6
    assert candidate(s = "abcabcabcabcabc") == 6
    assert candidate(s = "abcdaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzz") == 52
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 8
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 6
    assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij") == 20
