# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "aaaa",maxLetters = 1,minSize = 3,maxSize = 3) == 2
    assert candidate(s = "abacabadabacaba",maxLetters = 3,minSize = 3,maxSize = 5) == 4
    assert candidate(s = "xyzxyzxyz",maxLetters = 3,minSize = 3,maxSize = 3) == 3
    assert candidate(s = "abacaba",maxLetters = 2,minSize = 2,maxSize = 5) == 2
    assert candidate(s = "aabcabcabc",maxLetters = 2,minSize = 2,maxSize = 3) == 3
    assert candidate(s = "xyzxyz",maxLetters = 3,minSize = 2,maxSize = 4) == 2
    assert candidate(s = "abcde",maxLetters = 3,minSize = 2,maxSize = 3) == 1
    assert candidate(s = "xyzxyzxyz",maxLetters = 3,minSize = 1,maxSize = 2) == 3
    assert candidate(s = "abcde",maxLetters = 3,minSize = 2,maxSize = 4) == 1
    assert candidate(s = "abcde",maxLetters = 5,minSize = 1,maxSize = 5) == 1
    assert candidate(s = "abacabadabacaba",maxLetters = 2,minSize = 2,maxSize = 3) == 4
    assert candidate(s = "abacabadaba",maxLetters = 2,minSize = 2,maxSize = 3) == 3
    assert candidate(s = "aababcaab",maxLetters = 2,minSize = 3,maxSize = 4) == 2
    assert candidate(s = "abcabcabc",maxLetters = 3,minSize = 3,maxSize = 9) == 3
    assert candidate(s = "mnopqrstuvmnopqrstuvmnopqrstuvmnopqrstuvmnopqrstuvmnopq",maxLetters = 5,minSize = 10,maxSize = 15) == 0
    assert candidate(s = "thisisjustatest",maxLetters = 4,minSize = 4,maxSize = 5) == 1
    assert candidate(s = "abababababababababababab",maxLetters = 2,minSize = 2,maxSize = 4) == 12
    assert candidate(s = "abcdefabcdefabcdef",maxLetters = 3,minSize = 5,maxSize = 6) == 0
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",maxLetters = 15,minSize = 7,maxSize = 14) == 1
    assert candidate(s = "zzzzzzzzzzzz",maxLetters = 1,minSize = 5,maxSize = 7) == 8
    assert candidate(s = "abcdefabcdefabcdef",maxLetters = 3,minSize = 3,maxSize = 3) == 3
    assert candidate(s = "abcabcabcabc",maxLetters = 3,minSize = 3,maxSize = 9) == 4
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",maxLetters = 3,minSize = 3,maxSize = 5) == 1
    assert candidate(s = "xyzzxyzzxyzzxyzzxyzzxyzzxyzzxyzzxyzzxyzzxyzzxyzzxyzzxyzzxyzzxyzzxyzz",maxLetters = 3,minSize = 4,maxSize = 8) == 17
    assert candidate(s = "xyzxyzxyzxyz",maxLetters = 2,minSize = 1,maxSize = 3) == 4
    assert candidate(s = "abcabcabcabcabcabc",maxLetters = 3,minSize = 3,maxSize = 6) == 6
    assert candidate(s = "aabbccddeeffgg",maxLetters = 3,minSize = 2,maxSize = 4) == 1
    assert candidate(s = "xyxyxyxyxyxyxy",maxLetters = 2,minSize = 3,maxSize = 6) == 6
    assert candidate(s = "mnopmnopmnop",maxLetters = 4,minSize = 5,maxSize = 7) == 2
    assert candidate(s = "abababababababab",maxLetters = 2,minSize = 3,maxSize = 6) == 7
    assert candidate(s = "abcdefghij",maxLetters = 5,minSize = 3,maxSize = 4) == 1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",maxLetters = 10,minSize = 5,maxSize = 10) == 1
    assert candidate(s = "abcdabcdabcd",maxLetters = 4,minSize = 4,maxSize = 4) == 3
    assert candidate(s = "mississippiissi",maxLetters = 3,minSize = 2,maxSize = 5) == 3
    assert candidate(s = "abcdefgabcdefg",maxLetters = 2,minSize = 4,maxSize = 5) == 0
    assert candidate(s = "pneumonoultramicroscopicsilicovolcanoconiosis",maxLetters = 10,minSize = 10,maxSize = 20) == 1
    assert candidate(s = "aabbccddeeaabbccddeeaabb",maxLetters = 3,minSize = 4,maxSize = 5) == 3
    assert candidate(s = "mnopqrstuvmnopqrstuvmnopqrstuvmnopqrstuvmnopqrstuvmnopqrstuvmnopqrstuvmnopqrstuvmnopqrstuv",maxLetters = 10,minSize = 10,maxSize = 15) == 9
    assert candidate(s = "abacabadabacabadabacabadabacaba",maxLetters = 3,minSize = 5,maxSize = 7) == 4
    assert candidate(s = "abacabadabacaba",maxLetters = 2,minSize = 4,maxSize = 4) == 0
    assert candidate(s = "abacabadabacabadabacaba",maxLetters = 3,minSize = 3,maxSize = 7) == 6
    assert candidate(s = "abcabcabcabc",maxLetters = 1,minSize = 1,maxSize = 1) == 4
    assert candidate(s = "abcabcabcabc",maxLetters = 3,minSize = 2,maxSize = 5) == 4
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",maxLetters = 26,minSize = 1,maxSize = 10) == 2
    assert candidate(s = "pqrstuvwpqrstu",maxLetters = 7,minSize = 5,maxSize = 8) == 2
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd",maxLetters = 4,minSize = 8,maxSize = 12) == 13
    assert candidate(s = "abcdefabcdefabcdef",maxLetters = 6,minSize = 6,maxSize = 6) == 3
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcd",maxLetters = 4,minSize = 4,maxSize = 8) == 8
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",maxLetters = 5,minSize = 5,maxSize = 10) == 1
    assert candidate(s = "abcabcabcabc",maxLetters = 3,minSize = 2,maxSize = 4) == 4
    assert candidate(s = "abracadabraabracadabra",maxLetters = 4,minSize = 5,maxSize = 7) == 2
    assert candidate(s = "mnopqr",maxLetters = 6,minSize = 1,maxSize = 6) == 1
    assert candidate(s = "aabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabb",maxLetters = 2,minSize = 3,maxSize = 4) == 18
    assert candidate(s = "xyzyzyzyzyz",maxLetters = 2,minSize = 3,maxSize = 4) == 4
    assert candidate(s = "abcabcabcabc",maxLetters = 3,minSize = 4,maxSize = 6) == 3
    assert candidate(s = "pppppppppppppppppppppppppppppppppppppppppp",maxLetters = 1,minSize = 50,maxSize = 100) == 0
    assert candidate(s = "zzzzzzzzzzzzzz",maxLetters = 1,minSize = 5,maxSize = 10) == 10
    assert candidate(s = "ababababababab",maxLetters = 2,minSize = 4,maxSize = 6) == 6
    assert candidate(s = "xyzxyzxyz",maxLetters = 3,minSize = 2,maxSize = 5) == 3
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd",maxLetters = 4,minSize = 4,maxSize = 8) == 29
    assert candidate(s = "aabbccddeeffaabbccddeeffaabbccddeeff",maxLetters = 3,minSize = 6,maxSize = 12) == 3
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",maxLetters = 26,minSize = 1,maxSize = 26) == 1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",maxLetters = 26,minSize = 15,maxSize = 20) == 1
    assert candidate(s = "xyxzyxzyxzyxzyxzyxzyxz",maxLetters = 3,minSize = 3,maxSize = 4) == 7
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",maxLetters = 10,minSize = 10,maxSize = 20) == 1
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz",maxLetters = 1,minSize = 5,maxSize = 10) == 16
    assert candidate(s = "abcdabcdabcd",maxLetters = 4,minSize = 3,maxSize = 3) == 3
    assert candidate(s = "bananaananabanananaanananana",maxLetters = 3,minSize = 3,maxSize = 6) == 11
    assert candidate(s = "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",maxLetters = 1,minSize = 25000,maxSize = 25000) == 0
    assert candidate(s = "thisisaverylongstringthatwilltestthelimits",maxLetters = 10,minSize = 5,maxSize = 15) == 1
    assert candidate(s = "xyzxyzxyzxyz",maxLetters = 3,minSize = 4,maxSize = 6) == 3
    assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij",maxLetters = 5,minSize = 10,maxSize = 15) == 0
    assert candidate(s = "ababababababababababababababababababababababababababababababababababab",maxLetters = 2,minSize = 4,maxSize = 8) == 34
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",maxLetters = 26,minSize = 1,maxSize = 26) == 2
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc",maxLetters = 3,minSize = 3,maxSize = 6) == 31
    assert candidate(s = "abcdefabcdefabcdef",maxLetters = 6,minSize = 6,maxSize = 12) == 3
    assert candidate(s = "tuvwxyzuvwxy",maxLetters = 10,minSize = 4,maxSize = 7) == 2
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad",maxLetters = 4,minSize = 4,maxSize = 8) == 8
    assert candidate(s = "mnopqrsmnopqr",maxLetters = 7,minSize = 5,maxSize = 8) == 2
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc",maxLetters = 3,minSize = 3,maxSize = 6) == 10
    assert candidate(s = "xxyxxxyxyxyxyxyxyxyxyxyxyxyxyxyxyx",maxLetters = 2,minSize = 5,maxSize = 10) == 13
    assert candidate(s = "aabbccddeeff",maxLetters = 3,minSize = 3,maxSize = 5) == 1
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",maxLetters = 1,minSize = 5,maxSize = 10) == 54
    assert candidate(s = "mnopqrstuvmnopqrstuvmnopqrstuvmn",maxLetters = 10,minSize = 5,maxSize = 15) == 3
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcd",maxLetters = 4,minSize = 6,maxSize = 8) == 7
    assert candidate(s = "abcdefabcdefabcdef",maxLetters = 6,minSize = 3,maxSize = 6) == 3
    assert candidate(s = "mississippiississippiississi",maxLetters = 4,minSize = 5,maxSize = 8) == 3
    assert candidate(s = "abcdefabcdef",maxLetters = 6,minSize = 3,maxSize = 6) == 2
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzz",maxLetters = 1,minSize = 5,maxSize = 10) == 20
    assert candidate(s = "abracadabraabracadabra",maxLetters = 5,minSize = 5,maxSize = 10) == 2
    assert candidate(s = "xyxxyxyxyx",maxLetters = 2,minSize = 1,maxSize = 3) == 6
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",maxLetters = 10,minSize = 5,maxSize = 8) == 1
    assert candidate(s = "ababababababababababababababababababababababababababababababababababab",maxLetters = 2,minSize = 2,maxSize = 4) == 35
    assert candidate(s = "ababababababababababababababab",maxLetters = 2,minSize = 4,maxSize = 8) == 14
    assert candidate(s = "abababababab",maxLetters = 2,minSize = 2,maxSize = 3) == 6
    assert candidate(s = "llllllllllllll",maxLetters = 1,minSize = 6,maxSize = 8) == 9
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",maxLetters = 1,minSize = 10,maxSize = 20) == 21
    assert candidate(s = "xyzxyzxyz",maxLetters = 3,minSize = 3,maxSize = 6) == 3
    assert candidate(s = "ababababababababababababababab",maxLetters = 2,minSize = 2,maxSize = 2) == 15
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad",maxLetters = 4,minSize = 5,maxSize = 10) == 8
    assert candidate(s = "abababababababababab",maxLetters = 2,minSize = 4,maxSize = 6) == 9
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz",maxLetters = 1,minSize = 10,maxSize = 15) == 11
    assert candidate(s = "abcabcabcabc",maxLetters = 3,minSize = 3,maxSize = 4) == 4
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnm",maxLetters = 10,minSize = 5,maxSize = 10) == 1
    assert candidate(s = "abababababababab",maxLetters = 2,minSize = 2,maxSize = 4) == 8
    assert candidate(s = "pqrspqrspqrspqrs",maxLetters = 4,minSize = 5,maxSize = 8) == 3
    assert candidate(s = "abcabcabcabc",maxLetters = 3,minSize = 1,maxSize = 10) == 4
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm",maxLetters = 10,minSize = 5,maxSize = 10) == 2
    assert candidate(s = "aabbccddeeff",maxLetters = 3,minSize = 4,maxSize = 6) == 1
    assert candidate(s = "aaabbbcccdddeee",maxLetters = 2,minSize = 2,maxSize = 3) == 2
    assert candidate(s = "abcabcabcabcabcabc",maxLetters = 3,minSize = 2,maxSize = 4) == 6
    assert candidate(s = "aabbccddeeff",maxLetters = 3,minSize = 2,maxSize = 6) == 1
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzz",maxLetters = 1,minSize = 5,maxSize = 10) == 22
    assert candidate(s = "zzzzzzzzzzzz",maxLetters = 1,minSize = 5,maxSize = 6) == 8
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzz",maxLetters = 1,minSize = 50000,maxSize = 50000) == 0
    assert candidate(s = "abababababababababababababab",maxLetters = 2,minSize = 3,maxSize = 5) == 13
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",maxLetters = 5,minSize = 10,maxSize = 15) == 0
