# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abababababababababababababababababababababababababababababababababababababababababababababababab") == 48
    assert candidate(s = "aaabaab") == 4
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 90
    assert candidate(s = "abacabadabacaba") == 1
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 29
    assert candidate(s = "abcabcabcabc") == 4
    assert candidate(s = "abcdabcdabcd") == 3
    assert candidate(s = "abcdefghijklmnopqrstuvsuwxyzabcdefghijklmnopqrstuvsuwxyz") == 2
    assert candidate(s = "abcabcdabc") == 2
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 2
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 102
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 66
    assert candidate(s = "abcdef") == 1
    assert candidate(s = "abababab") == 4
    assert candidate(s = "abcd") == 1
    assert candidate(s = "aaaaa") == 5
    assert candidate(s = "aabbccddeeff") == 2
    assert candidate(s = "abacabadabacabadabacaba") == 2
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 32
    assert candidate(s = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz") == 26
    assert candidate(s = "aabbccddeeffaabbccddeeffaabbccddeeff") == 4
    assert candidate(s = "abcababcababcababcababcababcababcababcababcababcababcab") == 11
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad") == 13
    assert candidate(s = "abacabadabacabadabacabadabacabad") == 4
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 26
    assert candidate(s = "abcdefabcdefabcdefabcdefabcdef") == 5
    assert candidate(s = "abcdefghabcdefghabcdefghabcdefgh") == 4
    assert candidate(s = "aabbccddeeffaabbccddeeffaabbccddeeffaabbccddeeffaabbccddeeffaabbccddeeffaabbccddeeffaabbccddeeff") == 9
    assert candidate(s = "aabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabb") == 19
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad") == 10
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 24
    assert candidate(s = "abababababababababababababababababababababababababababababababab") == 32
    assert candidate(s = "abababababababcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 20
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 27
    assert candidate(s = "ababccababccababccababccababcc") == 6
    assert candidate(s = "aaaaabbbbbccccdddd") == 5
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 28
    assert candidate(s = "abcabcabcabcabcabcabcabcabcab") == 9
    assert candidate(s = "abcdabcabcdabcabcd") == 2
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 106
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 20
    assert candidate(s = "ababababababababababababababababababababababababababababababababababababab") == 37
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 18
    assert candidate(s = "abababababababababababababababababababc") == 19
    assert candidate(s = "abacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabac") == 20
    assert candidate(s = "abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh") == 8
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzwwxxyyzzwwxxyyzz") == 2
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad") == 12
    assert candidate(s = "aaaaaaaaaaabaaaaaaaaaabaaaaaaaaaabaaaaaaaaaabaaaaaaaaaabaaaaaaaaaabaaaaaaaaaabaaaaaaaaaabaaaaaaaaaabaaaaaaaaaab") == 20
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc") == 10
    assert candidate(s = "aabbaabbaabbaabbaabbaabbaabbaabb") == 9
    assert candidate(s = "abcdabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 1
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 94
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd") == 10
    assert candidate(s = "abracadabraabracadabraabracadabra") == 3
    assert candidate(s = "aaabaaaabaaaaabaaaaaaaabaaaaaaaaabaaaaaaaaaabaaaaaaaaaaaabaaaaaaaaaaaaabaaaaaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaab") == 11
    assert candidate(s = "aabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabb") == 24
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 110
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 21
    assert candidate(s = "abababababababababababababababababababababab") == 22
    assert candidate(s = "ababababababababababababababababababababababababababababababababab") == 33
    assert candidate(s = "ababccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 2
    assert candidate(s = "aabbccddeeaabbccddeeaabbccddeeaabbccddeeaabbccddeeaabbccddeeaabbccdd") == 7
    assert candidate(s = "ababababababababababababababababa") == 16
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 25
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad") == 14
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad") == 11
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad") == 18
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad") == 9
    assert candidate(s = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz") == 16
    assert candidate(s = "aabbccddeeffaabbccddeeffaabbccddeeffaabbccddeeffaabbccddeeffaabbccddeeffaabbccddeeff") == 8
    assert candidate(s = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz") == 27
    assert candidate(s = "abacabadabcaba") == 1
    assert candidate(s = "banana") == 1
    assert candidate(s = "abacabacabacabacabacabacabacabac") == 8
    assert candidate(s = "aaabbbcccdddcccbbbcccaaa") == 3
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 30
    assert candidate(s = "aabbccddeeffaabbccddeeffaabbccddeeffaabbccddeeffaabbccddeeff") == 6
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 21
    assert candidate(s = "abcdabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 1
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad") == 8
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 22
    assert candidate(s = "ababcabcabcabcabcabc") == 7
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 16
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabad") == 6
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcd") == 10
    assert candidate(s = "abacabadabacabadabacabad") == 3
    assert candidate(s = "abababababababababababababababababababababababababababababababababababababababababababababab") == 46
    assert candidate(s = "abababababababababababababababababababababababababababababababababababababababab") == 40
    assert candidate(s = "ababccababccababccababccababccababccababccababccababccababccababccababccababccababccababcc") == 16
    assert candidate(s = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz") == 29
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzabcdabcdabcdabcdabcd") == 2
    assert candidate(s = "abababababababababababababababababababababababababababababababababababcabcabc") == 37
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzwwxxyyzz") == 2
    assert candidate(s = "abacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabac") == 21
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabc") == 11
    assert candidate(s = "ababccababccababccababccababccababccababccababccababccababccababccababccababcc") == 14
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzabacabadabacabadabacabadabacabad") == 2
    assert candidate(s = "abacabacabacabacabacabacabacabacabac") == 9
    assert candidate(s = "mississippi") == 1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzabacabadabacabadabacabadabacabadabacabadabacabad") == 2
    assert candidate(s = "ababababababababababababababababababababababababababababababababababababababababab") == 41
