# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "xyzyx") == 6
    assert candidate(s = "aabbcc") == 4
    assert candidate(s = "aaaa") == 4
    assert candidate(s = "accbcaxxcxx") == 25
    assert candidate(s = "madam") == 6
    assert candidate(s = "noon") == 4
    assert candidate(s = "racecar") == 12
    assert candidate(s = "deified") == 12
    assert candidate(s = "noonhighnoon") == 35
    assert candidate(s = "abcdcba") == 12
    assert candidate(s = "abacaba") == 12
    assert candidate(s = "level") == 6
    assert candidate(s = "abcdedcba") == 20
    assert candidate(s = "abcde") == 1
    assert candidate(s = "rotor") == 6
    assert candidate(s = "leetcodecom") == 9
    assert candidate(s = "bb") == 1
    assert candidate(s = "refer") == 6
    assert candidate(s = "palindromeabcdcba") == 20
    assert candidate(s = "aaabbbccc") == 9
    assert candidate(s = "xxyyzzxxyyzz") == 36
    assert candidate(s = "noonnoonnoon") == 36
    assert candidate(s = "repaper") == 12
    assert candidate(s = "abbaabbaabba") == 36
    assert candidate(s = "xyzzyxzyxz") == 25
    assert candidate(s = "aababababab") == 30
    assert candidate(s = "xyzyzyzyzyzy") == 30
    assert candidate(s = "racecarlevelmadam") == 45
    assert candidate(s = "aabbbbaa") == 16
    assert candidate(s = "abababa") == 12
    assert candidate(s = "babadab") == 9
    assert candidate(s = "referrefer") == 25
    assert candidate(s = "rotorrotor") == 25
    assert candidate(s = "abracadabra") == 25
    assert candidate(s = "abacdfgdcaba") == 35
    assert candidate(s = "mammam") == 9
    assert candidate(s = "noonbedalabamoon") == 35
    assert candidate(s = "levelonelevel") == 35
    assert candidate(s = "abccbaabcba") == 30
    assert candidate(s = "redderredder") == 36
    assert candidate(s = "redivider") == 20
    assert candidate(s = "zzzyzzyyzzyzz") == 42
    assert candidate(s = "racecarabc") == 15
    assert candidate(s = "noonabbadammadam") == 32
    assert candidate(s = "noonnoon") == 16
    assert candidate(s = "abcdzdcba") == 20
    assert candidate(s = "abcdefghihgfedcba") == 72
    assert candidate(s = "levelup") == 6
    assert candidate(s = "rotorositor") == 25
    assert candidate(s = "madamracecarmadam") == 72
    assert candidate(s = "abcddcbaabcddcba") == 64
    assert candidate(s = "abcdefgfedcba") == 42
    assert candidate(s = "zyxzyxzyxzyxzyx") == 49
    assert candidate(s = "zzzzzzzzzzzz") == 36
    assert candidate(s = "xyzyxzyzyx") == 25
    assert candidate(s = "deeee") == 4
    assert candidate(s = "noonappaloopnoon") == 56
    assert candidate(s = "abcabcabcabcabcabc") == 81
    assert candidate(s = "abcbaabcba") == 25
    assert candidate(s = "aabbbaaaabbbb") == 42
    assert candidate(s = "aabbccddeeffgg") == 4
    assert candidate(s = "aabbccddeeefff") == 9
    assert candidate(s = "deeeevee") == 12
    assert candidate(s = "aaabaaa") == 12
    assert candidate(s = "aabbccddeeff") == 4
    assert candidate(s = "levellevel") == 25
    assert candidate(s = "madamimadam") == 30
    assert candidate(s = "mississippi") == 24
    assert candidate(s = "madamatadammadamada") == 81
    assert candidate(s = "xyzzazxy") == 15
    assert candidate(s = "xyxxyxyxyxyx") == 35
    assert candidate(s = "levelracecarlevel") == 72
    assert candidate(s = "programming") == 12
    assert candidate(s = "zyxzyxzyxzyx") == 36
    assert candidate(s = "levelracecara") == 35
    assert candidate(s = "zzzzzyzzzz") == 25
    assert candidate(s = "racecarannakayak") == 40
    assert candidate(s = "aabbaabbaa") == 25
    assert candidate(s = "xyzabcdcba") == 12
    assert candidate(s = "optimization") == 15
    assert candidate(s = "abccbaabc") == 15
