# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "ELEELEELLL") == 3
    assert candidate(s = "EEEEEEE") == 7
    assert candidate(s = "EELLEELLL") == 2
    assert candidate(s = "E") == 1
    assert candidate(s = "EELLEL") == 2
    assert candidate(s = "ELE") == 1
    assert candidate(s = "LE") == 0
    assert candidate(s = "ELEEL") == 2
    assert candidate(s = "ELELEEL") == 2
    assert candidate(s = "ELLEEL") == 1
    assert candidate(s = "EEEEELLLL") == 5
    assert candidate(s = "EEEELEEL") == 5
    assert candidate(s = "ELLEELLEELLE") == 1
    assert candidate(s = "LELELEL") == 0
    assert candidate(s = "LELELELEL") == 0
    assert candidate(s = "ELELELELEL") == 1
    assert candidate(s = "EL") == 1
    assert candidate(s = "EEELLLL") == 3
    assert candidate(s = "ELEELLEL") == 2
    assert candidate(s = "ELLELE") == 1
    assert candidate(s = "ELLEELLEEL") == 1
    assert candidate(s = "LEELLEEL") == 1
    assert candidate(s = "EEEELEEEE") == 7
    assert candidate(s = "L") == 0
    assert candidate(s = "LLL") == 0
    assert candidate(s = "EELEEL") == 3
    assert candidate(s = "ELLELELEL") == 1
    assert candidate(s = "LEELLEELEELLELEEL") == 2
    assert candidate(s = "EEEEEEEEEELLLLLLLLLLLL") == 10
    assert candidate(s = "ELLEELLEELLEELLEELLEELLEELLEELLEELLEELLEELLEELLEELLEELLEEL") == 1
    assert candidate(s = "EEEEEEEEEEEEEEEEEEELLLLLLLLLLLLLLLLLLLL") == 19
    assert candidate(s = "EEEEEEEEEEEEEEEEEEEE") == 20
    assert candidate(s = "EELLEELLEE") == 2
    assert candidate(s = "ELEELLEELLEELLLL") == 2
    assert candidate(s = "ELLEELLEEELLEELLE") == 2
    assert candidate(s = "EEEEEEELEELLLLEEEE") == 8
    assert candidate(s = "ELEELLEELLEELLEELLEELLE") == 2
    assert candidate(s = "LEELEELLEELEELLEELEELLEELEELLEELEEL") == 6
    assert candidate(s = "EEEEELLEELLEELLEELLEEE") == 6
    assert candidate(s = "LELELELELELELELELELELELELELELELELELELELELELELELELELELELELELELELELELELELELELELELELELELELELELELELELE") == 0
    assert candidate(s = "ELELELELELELEL") == 1
    assert candidate(s = "LEEELLLLLEEEEEE") == 3
    assert candidate(s = "EEEEEELLLLLL") == 6
    assert candidate(s = "EEEELEEEEELEEEEELEEEEELEEEEELEEEEELEEEEELEEE") == 30
    assert candidate(s = "EEEEELLLLEELLL") == 5
    assert candidate(s = "LLELELELELELELEE") == 0
    assert candidate(s = "EEEEEEEEEELELELELELELE") == 10
    assert candidate(s = "ELELLELLELLELLELLE") == 1
    assert candidate(s = "EEEEELEELLLLLE") == 6
    assert candidate(s = "ELELELLELELLEL") == 1
    assert candidate(s = "ELEELLEELLEELLEELLEELLEELLEELLEELLEELL") == 2
    assert candidate(s = "EEEELELEELLEEEE") == 7
    assert candidate(s = "ELEELLEELLEELLEL") == 2
    assert candidate(s = "EEELLLLLLEELEELLEEL") == 3
    assert candidate(s = "EEEEEEEEEEEEEEEEEEEEEELE") == 22
    assert candidate(s = "LEEEEELELELEEL") == 5
    assert candidate(s = "ELLEEELLEELLEELLEELLEELLE") == 2
    assert candidate(s = "EEEELELELELELELEL") == 4
    assert candidate(s = "EEEEEEEEELLLL") == 9
    assert candidate(s = "ELLEELLEELLEELLE") == 1
    assert candidate(s = "ELEELLEELLEELLEELLEELLEELLEELLEELLE") == 2
    assert candidate(s = "EELEELEELEELEE") == 6
    assert candidate(s = "EEEEELLLLEEEEEELLLLLEEE") == 7
    assert candidate(s = "LEELLEELLEELLEELL") == 1
    assert candidate(s = "EEEEEEEELELLELLE") == 8
    assert candidate(s = "LELELELELELELELELE") == 0
    assert candidate(s = "LEELLEELLEELLEEL") == 1
    assert candidate(s = "LLEELLELLEELLE") == 0
    assert candidate(s = "ELELELELELELE") == 1
    assert candidate(s = "ELLEELLEELLEELLEELLEELLEELLEELLEELLEELLEELLEELLEELLEELLEELLEELLE") == 1
    assert candidate(s = "EEEEEEEEEEELELELELELELELELELELELELELELELEEEE") == 14
    assert candidate(s = "EEEEELLEELLEELLEELLE") == 5
    assert candidate(s = "EEEEEEEEEEEEEEEEEEEEEEEEEEELLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL") == 27
    assert candidate(s = "EELLEELLEELE") == 2
    assert candidate(s = "LEELLEELLEELLEELLEEL") == 1
    assert candidate(s = "ELLEEELLEEELLEEELLEEELLEEELLEE") == 6
    assert candidate(s = "ELELELELELEL") == 1
    assert candidate(s = "EEEEELLEELLELLLL") == 5
    assert candidate(s = "EELEELLEELLEEELLEELLE") == 4
    assert candidate(s = "EEEEEELLLLLLLL") == 6
    assert candidate(s = "ELLLLLLEEEEEEL") == 1
    assert candidate(s = "EEEEELLLLEELLLLL") == 5
    assert candidate(s = "LEEEEEEEEEEEEEEEEEEEEEEE") == 22
    assert candidate(s = "ELLEELLEEELLEEELLEEELLEEEL") == 5
    assert candidate(s = "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE") == 40
    assert candidate(s = "EEEEEEEEEEELLL") == 11
    assert candidate(s = "EELEEEELLLLLLLEELLLL") == 5
    assert candidate(s = "ELEELEELLELEEELLELEL") == 4
    assert candidate(s = "EEEEELLLLLEELLLLLEEEE") == 5
    assert candidate(s = "EEEELLLLLLLLEEE") == 4
    assert candidate(s = "EELEEELEEELEEELEEELEEELEEELE") == 14
    assert candidate(s = "EEEEELLEELLLEELL") == 5
    assert candidate(s = "EEEEELLLLLEEEE") == 5
    assert candidate(s = "EEEEEEEEEEEEEEEELLLLLLLLLLLLLLL") == 16
    assert candidate(s = "LELLELELLELELLELELLELLEL") == 0
    assert candidate(s = "ELLEELLEELLEELLEELLEEEEE") == 4
    assert candidate(s = "ELLEELLEELLEELLEELLEELLEELLEELLEELLEELLEELLE") == 1
    assert candidate(s = "ELELELELELELELELEL") == 1
    assert candidate(s = "ELLEELLEELLEELLL") == 1
    assert candidate(s = "EEEEELLLLEEEEE") == 6
    assert candidate(s = "EEEELELLLL") == 4
    assert candidate(s = "LEEELEEELEEELEEELEEELEEELEEELEEELEEELEEEEE") == 22
    assert candidate(s = "EEEEEEEEEEEEEEEEEEEEE") == 21
    assert candidate(s = "LELELELELELELELELELELELELELELELELELELELELELE") == 0
    assert candidate(s = "EEEEELLEEEEEEELLLLEEEE") == 10
    assert candidate(s = "LLEELLELLEELLEELLEELLEELLE") == 0
    assert candidate(s = "EEELLEELLEELLEELLEELLEEL") == 3
    assert candidate(s = "LELELELELELELELELELELEL") == 0
    assert candidate(s = "LEELLEELLEELLELL") == 1
    assert candidate(s = "ELLEELLEELLEELLLLL") == 1
    assert candidate(s = "EEEEEEEEEELEEEEEEEEELEEEEEEEEEEELEEEEEEEEE") == 36
    assert candidate(s = "LELELELELELELELELELELELELELELELELELELELELELELE") == 0
    assert candidate(s = "ELLEELLEELLEELLEELLEELLEELLEELLE") == 1
    assert candidate(s = "ELLEELLEELLEELLEELLEELLEELLEELLEELLEEL") == 1
    assert candidate(s = "ELLELELLELLEELLE") == 1
    assert candidate(s = "ELELLELLELLELLEL") == 1
    assert candidate(s = "EEEEEEEEELLLLLLLLL") == 9
    assert candidate(s = "EEEEEEEEELLLLLLLLLLLL") == 9
    assert candidate(s = "LELELELELELELELELELELELELELELELELELELELELELELELEL") == 0
    assert candidate(s = "ELLEELLELLEE") == 1
    assert candidate(s = "ELLEELLEELLEELLEELLEELL") == 1
    assert candidate(s = "EEELLEELLEELLE") == 3
    assert candidate(s = "LELELELELELELELELELE") == 0
    assert candidate(s = "ELEELLEELLEELLEELLEELLEELLEELLEELLEELLEELLEEL") == 2
    assert candidate(s = "ELEELLEELLEELLEELLEELLEELLEELLEELLEELLEELLEELL") == 2
    assert candidate(s = "EELLEELEELLEELEELLEELEELLEELEELLEE") == 6
    assert candidate(s = "LEELLEELLEELLEELLEELLEELLEELLEEL") == 1
    assert candidate(s = "EEEEEEELLLLLLLELLL") == 7
    assert candidate(s = "ELLEELLEELLEELLEELLE") == 1
    assert candidate(s = "LLLLLLLLLLEEEEEEEEEE") == 0
    assert candidate(s = "EEEEEEELLLLLLLEEEE") == 7
    assert candidate(s = "LEELLEELLEELLEELLEELLEEL") == 1
    assert candidate(s = "EEEEELLEELLEELLEELLEELLEELLEELLEELLEEL") == 5
    assert candidate(s = "ELLEELLEELLEEL") == 1
    assert candidate(s = "ELLELEELLELEELLELEELLELEEL") == 1
    assert candidate(s = "LEELLEEELLEL") == 2
    assert candidate(s = "EEEEELLLLLLLEEELLLLLEEELLLLLLLEEEEE") == 5
    assert candidate(s = "ELEELLEEL") == 2
    assert candidate(s = "LEEEEEELLEEEEEELLEEEEEELLE") == 13
    assert candidate(s = "EELLEELLLEELL") == 2
    assert candidate(s = "EEEEEEEEEEEEEEEEEEEEEEEEEELELELELELELELELELELELELELELELELELELELELELELELELELELE") == 26
    assert candidate(s = "EELLEELLLLEEEL") == 2
    assert candidate(s = "LELELELELELELELELELELELE") == 0
    assert candidate(s = "ELEELEELEELEELEELEE") == 7
