# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(word = "QWERTYUIOPASDFGHJKLZXCVBNM") == 52
    assert candidate(word = "ZZZZZ") == 0
    assert candidate(word = "CAKE") == 3
    assert candidate(word = "RHYTHM") == 9
    assert candidate(word = "FINGER") == 8
    assert candidate(word = "ALPHABET") == 12
    assert candidate(word = "ABCD") == 2
    assert candidate(word = "QWERTYUIOPASDFGHJKLMZXCVBNM") == 54
    assert candidate(word = "NEW") == 3
    assert candidate(word = "HAPPY") == 6
    assert candidate(word = "ABCMN") == 3
    assert candidate(word = "LONGEST") == 8
    assert candidate(word = "MISSISSIPPI") == 5
    assert candidate(word = "YEAR") == 7
    assert candidate(word = "ZXY") == 1
    assert candidate(word = "OPTIMIZATION") == 17
    assert candidate(word = "YYYYYY") == 0
    assert candidate(word = "ACB") == 1
    assert candidate(word = "ABCDEFGHIJKLMNOPQRSTUVWXYZ") == 36
    assert candidate(word = "MOUSE") == 5
    assert candidate(word = "ZZZZ") == 0
    assert candidate(word = "AA") == 0
    assert candidate(word = "TRANSFER") == 15
    assert candidate(word = "ABCDEFGHIJKLMNOP") == 18
    assert candidate(word = "PYTHON") == 6
    assert candidate(word = "QRSTUVWXYZ") == 12
    assert candidate(word = "KEYBOARD") == 15
    assert candidate(word = "ABAB") == 0
    assert candidate(word = "A") == 0
    assert candidate(word = "ABCDEFG") == 5
    assert candidate(word = "DISTANCE") == 11
    assert candidate(word = "ALGORITHMS") == 14
    assert candidate(word = "CAPABILITY") == 13
    assert candidate(word = "HASHMAP") == 9
    assert candidate(word = "LONGWORDLONGWORDLONGWORDLONGWORDLONGWORDLONGWORDLONGWORD") == 122
    assert candidate(word = "SPECIAL") == 12
    assert candidate(word = "DEPLOYMENT") == 14
    assert candidate(word = "VOLCANOES") == 15
    assert candidate(word = "VICTORY") == 10
    assert candidate(word = "BACKSPACENOTPOSSIBLE") == 35
    assert candidate(word = "PROSPERING") == 18
    assert candidate(word = "METHOD") == 7
    assert candidate(word = "ROBUST") == 7
    assert candidate(word = "PLANNING") == 11
    assert candidate(word = "JOY") == 2
    assert candidate(word = "DEPTHFIRSTSEARCH") == 29
    assert candidate(word = "CONCEPT") == 7
    assert candidate(word = "INTEGRATION") == 19
    assert candidate(word = "PLENTY") == 7
    assert candidate(word = "COORDINATION") == 18
    assert candidate(word = "ACCOMPLISHED") == 18
    assert candidate(word = "RUBY") == 7
    assert candidate(word = "SERVER") == 10
    assert candidate(word = "PYTHONIC") == 8
    assert candidate(word = "PRODUCT") == 8
    assert candidate(word = "JUST") == 3
    assert candidate(word = "RESEARCH") == 13
    assert candidate(word = "PYTHONCODING") == 15
    assert candidate(word = "INITIATION") == 9
    assert candidate(word = "OBJECTORIENTED") == 22
    assert candidate(word = "REQUIREMENT") == 15
    assert candidate(word = "BANANA") == 1
    assert candidate(word = "FINANCE") == 10
    assert candidate(word = "HELLOFROMTHEOTHERSIDE") == 35
    assert candidate(word = "DEDICATED") == 10
    assert candidate(word = "SUPERLONGWORD") == 23
    assert candidate(word = "ACCOMPLISHMENT") == 20
    assert candidate(word = "PROGRAMMER") == 13
    assert candidate(word = "SPECIALCHARACTERS") == 32
    assert candidate(word = "NETWORK") == 10
    assert candidate(word = "AWESOME") == 11
    assert candidate(word = "PROGRESS") == 9
    assert candidate(word = "WIN") == 2
    assert candidate(word = "OBJECTIVE") == 15
    assert candidate(word = "FLOURISH") == 10
    assert candidate(word = "PROSPEROUS") == 16
    assert candidate(word = "EXPERIMENT") == 14
    assert candidate(word = "FINGERBOARD") == 20
    assert candidate(word = "PATIENCE") == 13
    assert candidate(word = "ADJUSTMENT") == 13
    assert candidate(word = "EXCEL") == 6
    assert candidate(word = "SUPERCALIFRAGILISTICEXPIALIDOCIOUS") == 59
    assert candidate(word = "FRANK") == 7
    assert candidate(word = "SOFTWARE") == 18
    assert candidate(word = "TWOPOINTERS") == 15
    assert candidate(word = "ANALYSIS") == 13
    assert candidate(word = "RESOLUTION") == 15
    assert candidate(word = "LONGWORDFORTESTING") == 32
    assert candidate(word = "INTERACTION") == 18
    assert candidate(word = "UNOBTRUDES") == 17
    assert candidate(word = "FINGERMOVEMENT") == 20
    assert candidate(word = "PEACE") == 5
    assert candidate(word = "DEPONIBLE") == 11
    assert candidate(word = "ASTARSEARCH") == 22
    assert candidate(word = "ANGULAR") == 10
    assert candidate(word = "SERVICE") == 12
    assert candidate(word = "PROSPERITY") == 19
    assert candidate(word = "RECOGNITION") == 13
    assert candidate(word = "KINDNESS") == 7
    assert candidate(word = "PYTHONPYTHONPYTHON") == 26
    assert candidate(word = "PARTNER") == 12
    assert candidate(word = "IDEAL") == 5
    assert candidate(word = "PRODUCTIVE") == 14
    assert candidate(word = "HARMONY") == 10
    assert candidate(word = "MYSQL") == 5
    assert candidate(word = "PYTHONISFUN") == 17
    assert candidate(word = "UNIVERSAL") == 16
    assert candidate(word = "KEYBOARDLAYOUT") == 29
    assert candidate(word = "SAFE") == 4
    assert candidate(word = "TYPESCRIPT") == 20
    assert candidate(word = "TREE") == 3
    assert candidate(word = "FINGERFINGER") == 20
    assert candidate(word = "AAAAA") == 0
    assert candidate(word = "GENTLE") == 7
    assert candidate(word = "ETHICAL") == 8
    assert candidate(word = "BACKTRACKING") == 21
    assert candidate(word = "AFFLUENT") == 11
    assert candidate(word = "TIMECOMPLEXITY") == 27
    assert candidate(word = "HUMBLE") == 11
    assert candidate(word = "API") == 2
    assert candidate(word = "OVERCOME") == 14
    assert candidate(word = "DOBRE") == 8
    assert candidate(word = "PRACTICE") == 13
    assert candidate(word = "PLAIN") == 8
    assert candidate(word = "ACHIEVEMENT") == 14
    assert candidate(word = "COMPUTERSCIENCE") == 28
    assert candidate(word = "SUCCESSFUL") == 9
    assert candidate(word = "GOAL") == 5
    assert candidate(word = "CHANGE") == 9
    assert candidate(word = "FULFILLMENT") == 12
    assert candidate(word = "PRINCIPLE") == 13
    assert candidate(word = "CODER") == 5
    assert candidate(word = "ALLOCATION") == 13
    assert candidate(word = "DIJKSTRAS") == 14
    assert candidate(word = "INTERPRETATION") == 22
    assert candidate(word = "INTEGRITY") == 16
    assert candidate(word = "HACK") == 4
    assert candidate(word = "QWJRTYUPASDFGZXCVB") == 43
    assert candidate(word = "SUPERLATIVE") == 23
    assert candidate(word = "PERSISTENT") == 16
    assert candidate(word = "MULTIPLEFINGERS") == 24
    assert candidate(word = "OPERATION") == 16
    assert candidate(word = "DELIVERY") == 14
    assert candidate(word = "DETERMINATION") == 20
    assert candidate(word = "DATASTRUCTURE") == 24
    assert candidate(word = "CALCULATION") == 19
    assert candidate(word = "OPULANCE") == 15
    assert candidate(word = "TOP") == 1
    assert candidate(word = "SIMULATION") == 19
    assert candidate(word = "ATTENTIVE") == 12
    assert candidate(word = "PROFILING") == 9
    assert candidate(word = "EFFICIENT") == 7
    assert candidate(word = "MEMORYMANAGEMENT") == 26
    assert candidate(word = "STRATEGY") == 18
    assert candidate(word = "THRIVE") == 9
    assert candidate(word = "ENERGETIC") == 15
    assert candidate(word = "THEQUICKBROWNFOXJUMPSOVERTHELAZYDOG") == 73
    assert candidate(word = "CUSTOMIZATION") == 20
    assert candidate(word = "OPTIMIZE") == 11
    assert candidate(word = "ELITE") == 6
    assert candidate(word = "PROGRAMMINGISFUN") == 24
    assert candidate(word = "COMMITTED") == 9
    assert candidate(word = "EFFECTIVE") == 10
    assert candidate(word = "REPORT") == 6
    assert candidate(word = "SPACESAVING") == 22
    assert candidate(word = "INTERFACE") == 15
    assert candidate(word = "NEURALNETWORKS") == 29
    assert candidate(word = "CORRECT") == 9
    assert candidate(word = "KNIGHTMARCH") == 17
    assert candidate(word = "SIMPLE") == 8
    assert candidate(word = "TECHNOLOGY") == 16
    assert candidate(word = "QUEUE") == 2
    assert candidate(word = "ABACAXABABACAB") == 15
    assert candidate(word = "PROGRAMMING") == 14
    assert candidate(word = "SEARCH") == 10
    assert candidate(word = "MULTIPLEWORDSHEREANDTHERE") == 49
    assert candidate(word = "LOAD") == 7
    assert candidate(word = "CONFIDENT") == 11
    assert candidate(word = "HTML") == 4
    assert candidate(word = "SECURE") == 10
    assert candidate(word = "MECHANISM") == 13
    assert candidate(word = "WEALTHY") == 15
    assert candidate(word = "FLAWLESS") == 12
    assert candidate(word = "MORAL") == 6
    assert candidate(word = "RESPONSIBLE") == 19
    assert candidate(word = "DEVOTED") == 6
    assert candidate(word = "PASSIONATE") == 15
    assert candidate(word = "RANDOMKEYPAD") == 24
    assert candidate(word = "BACKSPACENEEDED") == 20
    assert candidate(word = "JAVA") == 2
    assert candidate(word = "CHALLENGE") == 11
    assert candidate(word = "PRESENTATION") == 17
    assert candidate(word = "BOOMING") == 7
    assert candidate(word = "HELLOWORLD") == 13
    assert candidate(word = "EQUITABLE") == 16
    assert candidate(word = "GREATEST") == 10
    assert candidate(word = "DATASTRUCTURES") == 26
    assert candidate(word = "EXCELLENCE") == 14
    assert candidate(word = "PRECISE") == 10
    assert candidate(word = "OBTAINED") == 11
    assert candidate(word = "EXECUTION") == 9
    assert candidate(word = "DELICATE") == 11
    assert candidate(word = "KRUSKALSMST") == 16
    assert candidate(word = "AAABBBCCCDDD") == 2
    assert candidate(word = "BEST") == 4
    assert candidate(word = "ABCDEFGHIJABCDEFGHIJ") == 24
    assert candidate(word = "EXEMPLARY") == 19
    assert candidate(word = "PRIMSMST") == 9
    assert candidate(word = "MANAGER") == 10
    assert candidate(word = "RELATIONSHIP") == 19
    assert candidate(word = "COMMUNICATION") == 15
    assert candidate(word = "FINGERPRINT") == 17
    assert candidate(word = "RECOMMENDATION") == 18
    assert candidate(word = "MULTITHREADING") == 24
    assert candidate(word = "MEETING") == 8
    assert candidate(word = "TRIUMPHANT") == 17
    assert candidate(word = "PRIDE") == 5
    assert candidate(word = "STRETCH") == 8
    assert candidate(word = "FINGERLATERALMOVEMENT") == 38
    assert candidate(word = "CLIENT") == 6
    assert candidate(word = "BOOM") == 2
    assert candidate(word = "AFFLUENCE") == 13
    assert candidate(word = "CONSECUTIVE") == 16
    assert candidate(word = "GREAT") == 8
    assert candidate(word = "MARKET") == 9
    assert candidate(word = "GENUINE") == 8
    assert candidate(word = "BIGDATAANALYSIS") == 24
    assert candidate(word = "CONVINCED") == 10
    assert candidate(word = "UNIT") == 3
    assert candidate(word = "CONFIGURATION") == 25
    assert candidate(word = "PLAN") == 6
    assert candidate(word = "ADAPTABLE") == 13
    assert candidate(word = "TEAMWORK") == 15
    assert candidate(word = "AAAAAAAAA") == 0
    assert candidate(word = "ACHIEVE") == 8
    assert candidate(word = "UTILIZATION") == 17
    assert candidate(word = "THRIVING") == 10
    assert candidate(word = "PERFORMANCE") == 20
    assert candidate(word = "MODEST") == 6
    assert candidate(word = "DEVELOPMENT") == 13
    assert candidate(word = "ACHIEVED") == 9
    assert candidate(word = "BREADTHFIRSTSEARCH") == 35
    assert candidate(word = "ASSURED") == 9
    assert candidate(word = "TRIUMPH") == 12
    assert candidate(word = "ENTHUSIASTIC") == 17
    assert candidate(word = "BUSINESS") == 11
    assert candidate(word = "PHP") == 0
    assert candidate(word = "EARNED") == 10
    assert candidate(word = "BBBBC") == 0
    assert candidate(word = "LONGKEYSEQUENCE") == 20
    assert candidate(word = "RIGHT") == 5
    assert candidate(word = "PERFECTION") == 14
    assert candidate(word = "PRINCIPLED") == 14
    assert candidate(word = "DEBUGGINGISSLOW") == 23
    assert candidate(word = "GUARANTEED") == 13
    assert candidate(word = "PROSPER") == 11
    assert candidate(word = "SYNCHRONIZATION") == 25
    assert candidate(word = "ACCOUNTABLE") == 14
    assert candidate(word = "VIVACIOUS") == 10
    assert candidate(word = "ACCURATE") == 14
    assert candidate(word = "INITIALIZE") == 17
    assert candidate(word = "ABUNDANCE") == 12
    assert candidate(word = "EXACT") == 10
    assert candidate(word = "PREMIERE") == 12
    assert candidate(word = "PNEUMONULA") == 19
    assert candidate(word = "SYNTAXERRORHANDLING") == 36
    assert candidate(word = "PYTHONANDJAVA") == 15
    assert candidate(word = "PROBLEM") == 10
    assert candidate(word = "DECIDED") == 4
    assert candidate(word = "INFORMATION") == 18
    assert candidate(word = "CODINGCHALLENGES") == 23
    assert candidate(word = "TRANSACTION") == 16
    assert candidate(word = "CONTESTSAREFUN") == 24
    assert candidate(word = "DYNAMIC") == 11
    assert candidate(word = "PATTERN") == 11
    assert candidate(word = "CONCURRENT") == 12
    assert candidate(word = "TEST") == 2
    assert candidate(word = "SUPERIOR") == 10
    assert candidate(word = "LOVEPYTHON") == 17
    assert candidate(word = "COLLABORATION") == 22
    assert candidate(word = "MINIMALIZATION") == 20
    assert candidate(word = "MACHINELEARNING") == 28
    assert candidate(word = "PLETHORA") == 16
    assert candidate(word = "MEMORIZATION") == 21
    assert candidate(word = "PROTECTED") == 11
    assert candidate(word = "JAVASCRIPT") == 19
    assert candidate(word = "EXCEPTIONAL") == 20
    assert candidate(word = "FLOURISHING") == 15
    assert candidate(word = "COORDINATOR") == 17
    assert candidate(word = "VARIABLESANDTYPES") == 33
    assert candidate(word = "TEAM") == 6
    assert candidate(word = "TRAVELINGSALESMANPROBLEM") == 51
    assert candidate(word = "VUE") == 1
    assert candidate(word = "DIRECT") == 10
    assert candidate(word = "AVOIDDISTANCE") == 17
    assert candidate(word = "PREMIUM") == 10
    assert candidate(word = "FLEXIBLE") == 12
    assert candidate(word = "CPLUSPLUS") == 15
    assert candidate(word = "BUG") == 2
    assert candidate(word = "COOLCODE") == 8
    assert candidate(word = "CONGRATULATIONS") == 25
    assert candidate(word = "MONGODB") == 8
    assert candidate(word = "NETWORKFLOW") == 16
    assert candidate(word = "SIMULATEDANNEALING") == 34
    assert candidate(word = "STRONG") == 6
    assert candidate(word = "POSTGRESQL") == 17
    assert candidate(word = "TARGET") == 11
    assert candidate(word = "PROJECT") == 10
    assert candidate(word = "ARTIFICIALINTELLIGENCE") == 37
    assert candidate(word = "DATABASE") == 10
    assert candidate(word = "RECURSION") == 13
    assert candidate(word = "REACT") == 9
    assert candidate(word = "FRAMEWORK") == 16
    assert candidate(word = "OPTIMAL") == 10
    assert candidate(word = "REACHED") == 8
    assert candidate(word = "EXCELLENT") == 12
    assert candidate(word = "KANGAROO") == 11
    assert candidate(word = "GENETICALGORITHM") == 24
    assert candidate(word = "STRESS") == 5
    assert candidate(word = "PYTHONPROGRAMMING") == 23
    assert candidate(word = "GRAPH") == 5
    assert candidate(word = "MIGHTY") == 6
    assert candidate(word = "HONEST") == 6
    assert candidate(word = "ACCELERATION") == 18
    assert candidate(word = "XYLOPHONE") == 15
    assert candidate(word = "LUXURY") == 6
    assert candidate(word = "LOYAL") == 8
    assert candidate(word = "DIVIDEANDCONQUER") == 25
    assert candidate(word = "IDENTIFICATION") == 19
    assert candidate(word = "HONORABLE") == 11
    assert candidate(word = "TYPINGISAWAYTORELAX") == 37
    assert candidate(word = "ENGINEERING") == 15
    assert candidate(word = "TYPINGWITHTWOFINGERS") == 39
    assert candidate(word = "COMPANY") == 10
    assert candidate(word = "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ") == 84
    assert candidate(word = "ARRAY") == 4
    assert candidate(word = "CSS") == 0
    assert candidate(word = "CYBER") == 7
    assert candidate(word = "ENGINEER") == 9
    assert candidate(word = "FUTURE") == 7
    assert candidate(word = "APPLICATION") == 14
    assert candidate(word = "STACK") == 6
    assert candidate(word = "VICTORIOUS") == 13
    assert candidate(word = "IMPLEMENTATION") == 18
    assert candidate(word = "HELLOUNIVERSE") == 23
    assert candidate(word = "PROCESS") == 9
    assert candidate(word = "FUNCTION") == 9
    assert candidate(word = "CAREER") == 6
    assert candidate(word = "INITIATIVE") == 12
    assert candidate(word = "RESULT") == 8
    assert candidate(word = "EMPATHY") == 12
    assert candidate(word = "ABILITY") == 8
    assert candidate(word = "SUPPLIER") == 10
    assert candidate(word = "INTERVENTION") == 20
    assert candidate(word = "ATTAINED") == 8
    assert candidate(word = "ALGORITHM") == 13
    assert candidate(word = "LEADER") == 7
    assert candidate(word = "SOFTWAREENGINEERING") == 36
    assert candidate(word = "SUPERABUNDANCE") == 26
    assert candidate(word = "TENACIOUS") == 11
    assert candidate(word = "FAIR") == 5
    assert candidate(word = "HELLOWORLDHELLOWORLD") == 29
    assert candidate(word = "REFACTOR") == 14
    assert candidate(word = "SATISFACTION") == 20
    assert candidate(word = "ALGORITHMSANDDATA") == 26
    assert candidate(word = "PROLIFIC") == 5
    assert candidate(word = "GRAPHALGORITHMS") == 24
    assert candidate(word = "CAREFUL") == 12
    assert candidate(word = "ECONOMY") == 7
    assert candidate(word = "OUTSTANDING") == 12
    assert candidate(word = "GREEDYALGORITHM") == 27
    assert candidate(word = "VIP") == 1
    assert candidate(word = "BAAABBBCCCDDDDEEEEFFFFGGGGHHHHIIIIJJJJKKKKLLLLMMMMNNNNOOOOPPPPQQQQRRRRSSSSTTTTUUUUVVVVWWWWWXXXXYYYYZZZZZ") == 36
    assert candidate(word = "COMPASSION") == 12
    assert candidate(word = "ARCHITECTURE") == 20
    assert candidate(word = "BELLMANFORD") == 17
    assert candidate(word = "WORKFLOW") == 10
    assert candidate(word = "NODEJS") == 7
    assert candidate(word = "RESILIENT") == 14
    assert candidate(word = "ZYXWVUTSRQPONMLKJIHGFEDCBA") == 36
    assert candidate(word = "HAPPINESS") == 12
    assert candidate(word = "RELIABLE") == 10
    assert candidate(word = "POWERFUL") == 11
    assert candidate(word = "PERFECT") == 10
    assert candidate(word = "TRUSTWORTHY") == 18
    assert candidate(word = "TRANSPARENT") == 23
    assert candidate(word = "MINIMIZE") == 8
    assert candidate(word = "COMPLEXITY") == 20
    assert candidate(word = "TENDER") == 6
    assert candidate(word = "ACCEPTANCE") == 13
    assert candidate(word = "FLASK") == 5
    assert candidate(word = "KNOWLEDGE") == 13
    assert candidate(word = "RICH") == 3
    assert candidate(word = "ENVIRONMENT") == 17
    assert candidate(word = "GAINED") == 7
    assert candidate(word = "DISCOVER") == 13
    assert candidate(word = "DOUBTFREE") == 13
    assert candidate(word = "LUXURIOUS") == 9
    assert candidate(word = "SECURITY") == 14
    assert candidate(word = "INDUSTRY") == 13
    assert candidate(word = "MOVEMENTOFKEYS") == 19
    assert candidate(word = "DJANGO") == 6
    assert candidate(word = "FUNCTIONCALLSARE") == 28
    assert candidate(word = "CONSCIENTIOUS") == 16
    assert candidate(word = "HELLOORLD") == 9
    assert candidate(word = "REVISION") == 11
    assert candidate(word = "INNOVATION") == 12
    assert candidate(word = "EXCLUSIVE") == 18
    assert candidate(word = "SURE") == 5
    assert candidate(word = "TRUST") == 4
    assert candidate(word = "DYNAMICPROGRAMMING") == 31
    assert candidate(word = "LEARN") == 8
    assert candidate(word = "SUCCESS") == 5
    assert candidate(word = "AAAAAAAAAABBBBBBBBBBCCCCCCCCCC") == 1
    assert candidate(word = "EVOLUTION") == 11
    assert candidate(word = "SOLUTION") == 10
    assert candidate(word = "OPPORTUNITY") == 14
    assert candidate(word = "ABUNDANT") == 9
    assert candidate(word = "FAILURE") == 10
    assert candidate(word = "REVOLUTION") == 14
    assert candidate(word = "SEQUENCE") == 11
    assert candidate(word = "FINGERFINGERFINGER") == 32
    assert candidate(word = "LINKEDLIST") == 14
    assert candidate(word = "EXPERIENCE") == 14
    assert candidate(word = "OPEN") == 3
    assert candidate(word = "LOVE") == 4
    assert candidate(word = "CONCLUSION") == 14
    assert candidate(word = "SKILL") == 5
    assert candidate(word = "EVALUATION") == 19
    assert candidate(word = "FINGERTYPINGISFUN") == 32
    assert candidate(word = "MAGNIFICENT") == 13
    assert candidate(word = "LEETCODE") == 8
    assert candidate(word = "CUSTOMER") == 12
    assert candidate(word = "STRIGHT") == 8
    assert candidate(word = "SPACECOMPLEXITY") == 28
    assert candidate(word = "DEPENDABLE") == 13
    assert candidate(word = "DEVELOPER") == 10
    assert candidate(word = "EXPRESS") == 11
    assert candidate(word = "KEYPADTYPING") == 24
    assert candidate(word = "PROFESSION") == 12
    assert candidate(word = "REPOSITION") == 11
    assert candidate(word = "KNAPSACKPROBLEM") == 28
    assert candidate(word = "DESIGN") == 8
    assert candidate(word = "DEBUG") == 6
    assert candidate(word = "TRACING") == 11
    assert candidate(word = "STURDY") == 9
    assert candidate(word = "WEALTH") == 11
    assert candidate(word = "TRANSFORMATION") == 29
    assert candidate(word = "EFFORT") == 5
    assert candidate(word = "EXERCISE") == 11
