# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "(()))") == 1
    assert candidate(s = "())") == 1
    assert candidate(s = "()") == 0
    assert candidate(s = "((((((()))") == 4
    assert candidate(s = "())(()") == 2
    assert candidate(s = "((()))") == 0
    assert candidate(s = "((") == 2
    assert candidate(s = "") == 0
    assert candidate(s = "(()))(") == 2
    assert candidate(s = "(())") == 0
    assert candidate(s = "(()))(()") == 2
    assert candidate(s = "()))((") == 4
    assert candidate(s = "))(()()((()(()))))") == 2
    assert candidate(s = "()()(()(()))(()(()(()(()))))") == 0
    assert candidate(s = "((((((((((()))))))))") == 2
    assert candidate(s = "(())))(()") == 3
    assert candidate(s = ")(()))()()") == 2
    assert candidate(s = "(()((())()()))") == 0
    assert candidate(s = "((((((())") == 5
    assert candidate(s = "()(()(()))") == 0
    assert candidate(s = "(()(()))()()(()(()()()(()())())") == 1
    assert candidate(s = "((((()()()(()))))") == 1
    assert candidate(s = "(()(()(()(()(()())())))") == 1
    assert candidate(s = "(()(()))))((()") == 4
    assert candidate(s = "(()(()))(()(()(()(()))))") == 0
    assert candidate(s = "(()())((()))") == 0
    assert candidate(s = "()))(((((()))))())") == 2
    assert candidate(s = "(((()(()(()(()))))))") == 0
    assert candidate(s = "((()))(())()(()(()))") == 0
    assert candidate(s = "(()(()(()(()(()))))())") == 0
    assert candidate(s = "(()())(()())(()())") == 0
    assert candidate(s = "()()()(()(()))((()))(()(()(()(())))()(()))") == 0
    assert candidate(s = "((()))())((())()())") == 1
    assert candidate(s = "()()()()()()()()()()()()()()") == 0
    assert candidate(s = "(()))(((()))()()(()(()(()))))(())") == 1
    assert candidate(s = "((((((((())))))))()()") == 1
    assert candidate(s = "((((((()))))") == 2
    assert candidate(s = "))(()(()))") == 2
    assert candidate(s = "((((((()))))))") == 0
    assert candidate(s = "(()((())()(()))") == 1
    assert candidate(s = ")((((((((((())") == 10
    assert candidate(s = "(()(()(()(()))))") == 0
    assert candidate(s = "(()(()(()(()(()()))))(()(()(()))))()") == 0
    assert candidate(s = "(()(()(()(()))(()(()))))") == 0
    assert candidate(s = "((((((())))))))") == 1
    assert candidate(s = "(()))(()((()())(()())))") == 1
    assert candidate(s = "(()())())") == 1
    assert candidate(s = "())()()()(((())))") == 1
    assert candidate(s = "(()(()))(()())(()(()))") == 0
    assert candidate(s = "(((()))(()(())))") == 0
    assert candidate(s = "()()(()))(()((()())))") == 1
    assert candidate(s = "((())(()(()(()))))") == 0
    assert candidate(s = "(()()(()))(()(()(()))(()(()))))") == 1
    assert candidate(s = "(()(()))") == 0
    assert candidate(s = ")((((((()())") == 6
    assert candidate(s = "(((()))(()(()))(()(()))") == 1
    assert candidate(s = ")()(()))(()") == 3
    assert candidate(s = "()()()()") == 0
    assert candidate(s = "(((())(())))") == 0
    assert candidate(s = "(()(()(()(()(()(()))))))") == 0
    assert candidate(s = "((())())(()(()(()))())") == 0
    assert candidate(s = "(()(()(()())))") == 0
    assert candidate(s = "())(()))(()(()))") == 2
    assert candidate(s = "(()(()(()(()(()(()())())))())())") == 0
    assert candidate(s = "(()())((()()(())))") == 0
    assert candidate(s = "(()(())))") == 1
    assert candidate(s = "(()()(()(())))()(()(()))") == 0
    assert candidate(s = "(((((())))))()()()(((()(()))))()()") == 0
    assert candidate(s = "(()(()(()(()(()(()(()))))))))") == 1
    assert candidate(s = "()(()(()(()(()))))") == 0
    assert candidate(s = "(()(()))(()(()))") == 0
    assert candidate(s = "()(()(()(()())))") == 0
    assert candidate(s = "())(((())))") == 1
    assert candidate(s = "()())(()(()))(()") == 2
    assert candidate(s = ")(()(()(()(()(())))))") == 1
    assert candidate(s = "((((((((((()))))))))))") == 0
    assert candidate(s = "(())))))(((()()()(()(()))))))") == 5
    assert candidate(s = ")(()(()(()(()))))") == 1
    assert candidate(s = "()(()(()))(()(()(()(()))))") == 0
    assert candidate(s = "(((((((())))))))") == 0
    assert candidate(s = "())(()))(()(()(()())))((()())())") == 2
    assert candidate(s = "(((((((())))))") == 2
    assert candidate(s = "(((()())()))") == 0
    assert candidate(s = "(()(()(()(()))))())") == 1
    assert candidate(s = "(()))(()))(())))") == 4
    assert candidate(s = "()()()(()()())()()()()") == 0
    assert candidate(s = "(()())(()())") == 0
    assert candidate(s = "(()(()))(()(()(()(()(())))))") == 0
    assert candidate(s = ")()()()()()()") == 1
    assert candidate(s = "()(()))((())((())())") == 2
    assert candidate(s = "())(()(()))") == 1
    assert candidate(s = "())())())())())())") == 6
    assert candidate(s = "(()))())(()") == 3
    assert candidate(s = "()()()()()()()()") == 0
    assert candidate(s = "((())(()))") == 0
    assert candidate(s = "(())))))()") == 4
    assert candidate(s = "()(()((())))()()(()(()))))") == 2
    assert candidate(s = "(()(()))()(()(()))") == 0
    assert candidate(s = "(()))(()))") == 2
    assert candidate(s = "(((()))(()))") == 0
    assert candidate(s = "()()()()()()") == 0
    assert candidate(s = ")()(()()((()())))") == 1
    assert candidate(s = "(()))((())(()(())))") == 1
    assert candidate(s = "()(()()(()(()())))") == 0
    assert candidate(s = "())((())") == 2
    assert candidate(s = "(((((((()))())())())(())))))") == 2
    assert candidate(s = "(((((())))))()") == 0
    assert candidate(s = "))))))))))))") == 12
    assert candidate(s = "()()()(((()))))((()))(()(()))(()())") == 1
    assert candidate(s = "((())()(()(()))") == 1
    assert candidate(s = "())(()()") == 2
    assert candidate(s = "(()(((((((((()))))))") == 4
    assert candidate(s = "((((()))))") == 0
    assert candidate(s = "(((((())))))()(()(()))") == 0
    assert candidate(s = "(()(((())))())") == 0
