# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abcba") == 0
    assert candidate(s = "letelt") == 2
    assert candidate(s = "abcdcba") == 0
    assert candidate(s = "aabbaa") == 0
    assert candidate(s = "abcdedcba") == 0
    assert candidate(s = "mamad") == 3
    assert candidate(s = "aabbc") == 4
    assert candidate(s = "aabb") == 2
    assert candidate(s = "racecar") == 0
    assert candidate(s = "abcdefgfedcba") == 0
    assert candidate(s = "noon") == 0
    assert candidate(s = "deeee") == 2
    assert candidate(s = "nnnnn") == 0
    assert candidate(s = "aabbcc") == 6
    assert candidate(s = "elvtoelvtoe") == 6
    assert candidate(s = "aabbab") == 3
    assert candidate(s = "asflkj") == 5
    assert candidate(s = "abca") == 1
    assert candidate(s = "abcdefghgfedcba") == 0
    assert candidate(s = "zzzyzzyzz") == 1
    assert candidate(s = "noonappa") == 8
    assert candidate(s = "abcdcbad") == 3
    assert candidate(s = "aabaaabbaaaaaabbbbaa") == 11
    assert candidate(s = "aabbaabbaabb") == 6
    assert candidate(s = "jlvaj") == 1
    assert candidate(s = "xyzyzyzyzyx") == 0
    assert candidate(s = "qpwoeirutoip") == 12
    assert candidate(s = "abbbacaba") == 3
    assert candidate(s = "abcabcabcabc") == 6
    assert candidate(s = "noonnoon") == 0
    assert candidate(s = "aaaaabbbb") == 10
    assert candidate(s = "mnopqponmlkjihgfedcbaaaabbbccc") == 161
    assert candidate(s = "aabbccddeeefffgggggffffeeeeddccbaaabb") == 37
    assert candidate(s = "lplllp") == 1
    assert candidate(s = "aabbbbaaa") == 2
    assert candidate(s = "aaabbbcccdddcccbbaaa") == 5
    assert candidate(s = "mmnmm") == 0
    assert candidate(s = "mnvovnm") == 0
    assert candidate(s = "aabbccddeee") == 24
    assert candidate(s = "xyzzyx") == 0
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnmmlkjhgfdsapoiuytrewq") == 9
    assert candidate(s = "aabbaabbaabbaabb") == 8
    assert candidate(s = "abcdddcb") == 4
    assert candidate(s = "abcdxyzzyxcba") == 3
    assert candidate(s = "aabbccddeeeeddcbaabbaa") == 22
    assert candidate(s = "aabbccddeeefffgggghhhggggfffeeeedddccbbaa") == 20
    assert candidate(s = "aaaabbbbccccddddeeeeffffggggggg") == 204
    assert candidate(s = "ppqqrrssrqqpp") == 1
    assert candidate(s = "aaabbbb") == 6
    assert candidate(s = "abcdedcbaa") == 4
    assert candidate(s = "aabbccddeeffeecdccbbaa") == 7
    assert candidate(s = "aabbccddeeefffggggffffeeeeddccbaaabb") == 38
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 0
    assert candidate(s = "abcdeedcba") == 0
    assert candidate(s = "abacabad") == 4
    assert candidate(s = "xyzyxzyxzyxzyx") == 2
    assert candidate(s = "aaabbbaaa") == 0
    assert candidate(s = "aabbabaa") == 1
    assert candidate(s = "abcbaabcba") == 0
    assert candidate(s = "zazbzazbzaz") == 0
    assert candidate(s = "abcdeffedcba") == 0
    assert candidate(s = "abcbca") == 1
    assert candidate(s = "abcdefedcba") == 0
    assert candidate(s = "aabbccdd") == 12
    assert candidate(s = "level") == 0
    assert candidate(s = "abcabcba") == 1
    assert candidate(s = "aaaabbbb") == 8
    assert candidate(s = "madam") == 0
    assert candidate(s = "aabababaab") == 3
    assert candidate(s = "aabccbaa") == 0
    assert candidate(s = "abacabadabacaba") == 0
    assert candidate(s = "aabbccddeeeffffgggghhhiiijjjkkklllmmmnnnooopppqqqrrrssstttuuuvvvwwxxyyzz") == 1192
    assert candidate(s = "qwertewq") == 1
    assert candidate(s = "qwertytrewq") == 0
    assert candidate(s = "abcbad") == 3
    assert candidate(s = "abbaaccdaabb") == 5
    assert candidate(s = "aababbaaabbbbbaaaaa") == 8
    assert candidate(s = "aabaaa") == 1
    assert candidate(s = "aaabaaaabbaa") == 4
    assert candidate(s = "xyzyzyx") == 0
    assert candidate(s = "abccba") == 0
    assert candidate(s = "zxcvbnmlkjhgfdasqwertyuiopoiuytrewqasdfghjklmnbvcxz") == 1
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbbaaaaaaaaa") == 6
    assert candidate(s = "aabbccddeeeeddcbbbaa") == 10
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 650
    assert candidate(s = "aabbabba") == 2
    assert candidate(s = "mmnnllkkjjiihhggffeeddccbbaa") == 182
    assert candidate(s = "aaaaabbbaaaa") == 2
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba") == 25
    assert candidate(s = "nnnmmmnnn") == 0
    assert candidate(s = "repaper") == 0
    assert candidate(s = "abacdfgdcaba") == 1
    assert candidate(s = "aabbccddeeefffgggfhheeeddccbaa") == 22
    assert candidate(s = "abbaabba") == 0
    assert candidate(s = "zyxzyzyx") == 4
    assert candidate(s = "abcddcba") == 0
    assert candidate(s = "rotor") == 0
    assert candidate(s = "abcdefghihgfedcba") == 0
    assert candidate(s = "aabbccddeeeffggffeeddccbbaa") == 3
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcbaedcba") == 115
    assert candidate(s = "aabbccddeeeffffgggghhhiiijjjkkklllmmmnnnooopppqqqrrrssstttuuuvvvwwwxxxyyyzzz") == 1311
    assert candidate(s = "levellol") == 6
    assert candidate(s = "mississippi") == 13
    assert candidate(s = "abcdeffgfedcba") == 1
    assert candidate(s = "aabbccddeedcbaa") == 6
