# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(word = "abcdefgh",k = 2) == 4
    assert candidate(word = "xyz",k = 1) == 3
    assert candidate(word = "zzzzzz",k = 2) == 1
    assert candidate(word = "abcdabcd",k = 4) == 1
    assert candidate(word = "abacaba",k = 3) == 2
    assert candidate(word = "abcabcabc",k = 1) == 3
    assert candidate(word = "abcdefg",k = 7) == 1
    assert candidate(word = "abacaba",k = 4) == 1
    assert candidate(word = "aabbccddeeff",k = 2) == 6
    assert candidate(word = "zzzzzzzzzzzz",k = 5) == 1
    assert candidate(word = "a",k = 1) == 1
    assert candidate(word = "repeatrepeat",k = 6) == 1
    assert candidate(word = "abcabcabcabc",k = 3) == 1
    assert candidate(word = "abcabcabc",k = 3) == 1
    assert candidate(word = "abcdabcd",k = 2) == 2
    assert candidate(word = "hellohello",k = 5) == 1
    assert candidate(word = "aaaa",k = 1) == 1
    assert candidate(word = "abcdabcdabcd",k = 4) == 1
    assert candidate(word = "aaaa",k = 2) == 1
    assert candidate(word = "abcbabcd",k = 2) == 4
    assert candidate(word = "abcdef",k = 6) == 1
    assert candidate(word = "aaaaabbbbbccccddddaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 15) == 5
    assert candidate(word = "abcabcabcabcabcabcabcabc",k = 7) == 3
    assert candidate(word = "abcdefgabcdefg",k = 7) == 1
    assert candidate(word = "aaaabbbbccccddddeeeeffff",k = 4) == 6
    assert candidate(word = "qwertyuiopqwertyuiopqwertyuiopqwerty",k = 11) == 4
    assert candidate(word = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij",k = 10) == 1
    assert candidate(word = "abacabadabacabadabacabad",k = 5) == 5
    assert candidate(word = "abacabadabacabad",k = 3) == 6
    assert candidate(word = "abcdeabcdeabcdeabcdeabcde",k = 6) == 5
    assert candidate(word = "ababababababababababababababababababababababababab",k = 3) == 2
    assert candidate(word = "ababababababab",k = 4) == 1
    assert candidate(word = "abcdefgabcdefgabcdefg",k = 7) == 1
    assert candidate(word = "samepatterneverywhereeverywhereeverywhere",k = 11) == 4
    assert candidate(word = "hellohellohellohellohellohello",k = 6) == 5
    assert candidate(word = "abababababababababababababab",k = 10) == 1
    assert candidate(word = "abababababababab",k = 4) == 1
    assert candidate(word = "aaaaaabaaaaa",k = 3) == 3
    assert candidate(word = "abacabadabacabad",k = 6) == 3
    assert candidate(word = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd",k = 13) == 4
    assert candidate(word = "zzzzzzzzzzzzzzzzzz",k = 7) == 1
    assert candidate(word = "hellohellohellohellohello",k = 7) == 4
    assert candidate(word = "abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad",k = 9) == 8
    assert candidate(word = "abcabcabcabcabcabcabcabcabcabc",k = 10) == 3
    assert candidate(word = "abcdabcdabcdabcdabcdabcdabcdabcd",k = 8) == 1
    assert candidate(word = "xyzxyzxyzxyz",k = 5) == 3
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",k = 26) == 1
    assert candidate(word = "hellohellohellohellohello",k = 5) == 1
    assert candidate(word = "aaaaaabbbbbbcccccc",k = 3) == 6
    assert candidate(word = "aaaaabbbbbcccc",k = 5) == 3
    assert candidate(word = "abacabadabacabadabacabadabacabadaba",k = 7) == 5
    assert candidate(word = "xyzxyzxyzxyzxyzxyzxyzxyz",k = 7) == 3
    assert candidate(word = "abcabcabcabcabcabc",k = 5) == 3
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzz",k = 2) == 1
    assert candidate(word = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",k = 2) == 1
    assert candidate(word = "abababababab",k = 4) == 1
    assert candidate(word = "abcdefgabcdefgabcdefgabcdefgabcdefg",k = 9) == 4
    assert candidate(word = "ababababababababababab",k = 5) == 2
    assert candidate(word = "abcabcabcabcabcabcabcabcabcabcabcabc",k = 7) == 3
    assert candidate(word = "qwertyuiopqwertyuiopqwertyuiop",k = 9) == 4
    assert candidate(word = "zyxzyxzyxzyxzyxzyxzyxzyx",k = 6) == 1
    assert candidate(word = "xyzxyzxyzxyzxyzxyz",k = 6) == 1
    assert candidate(word = "abcdefabcdefabcdef",k = 6) == 1
    assert candidate(word = "ababababababababababababababababababa",k = 1) == 2
    assert candidate(word = "abcdefabcdefabcdefabcdefabcdefabcdef",k = 3) == 2
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 10) == 6
    assert candidate(word = "abcabcabcabcabc",k = 6) == 1
    assert candidate(word = "abcabcabcabcabcabcabcabcabcabcabcabc",k = 9) == 1
    assert candidate(word = "banana",k = 2) == 3
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",k = 13) == 2
    assert candidate(word = "abcdefghijklmnopqrstuvwxyz",k = 13) == 2
    assert candidate(word = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc",k = 12) == 1
    assert candidate(word = "abcdefgabcdefgabcdefgabcdefg",k = 5) == 6
    assert candidate(word = "xyzxyzxyzxyz",k = 2) == 3
    assert candidate(word = "zzzzzzzzzzzzzzzzzz",k = 9) == 1
    assert candidate(word = "abacabadabacabadabacabadabacabadaba",k = 8) == 1
    assert candidate(word = "ababababababababababababababababababa",k = 6) == 1
    assert candidate(word = "abacabadabacabadabacabadabacabadabacabadabacabad",k = 6) == 4
    assert candidate(word = "aaaaaaa",k = 2) == 1
    assert candidate(word = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz",k = 4) == 3
    assert candidate(word = "aabbaabbaabbaabbaabbaabb",k = 3) == 4
    assert candidate(word = "abcdefghijabcdefghijabcdefghij",k = 10) == 1
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 26) == 2
    assert candidate(word = "abcdefghijabcdefghijabcdefghijabcdefghij",k = 10) == 1
    assert candidate(word = "abacabadabacabadabacabad",k = 4) == 2
    assert candidate(word = "xyzxyzxyzxyzxyzxyz",k = 5) == 3
    assert candidate(word = "repeatrepeatrepeatrepeatrepeat",k = 3) == 2
    assert candidate(word = "abababababab",k = 1) == 2
    assert candidate(word = "abcabcabcabcabcabcabcabcabcabcabcabc",k = 5) == 3
    assert candidate(word = "abracadabraabracadabraabracadabra",k = 7) == 5
    assert candidate(word = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd",k = 12) == 1
    assert candidate(word = "repeatedrepeatedrepeated",k = 7) == 4
    assert candidate(word = "abcdabcdabcdabcdabcd",k = 8) == 1
    assert candidate(word = "abcdefghijklmnopqrstuvwxyz",k = 25) == 2
    assert candidate(word = "abababababababab",k = 5) == 2
    assert candidate(word = "aabbccddeeffgghhiijjkkll",k = 11) == 3
    assert candidate(word = "mississippimississippimississippi",k = 4) == 9
    assert candidate(word = "abacabadabacaba",k = 3) == 4
    assert candidate(word = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij",k = 13) == 6
    assert candidate(word = "abcdabcdabcdabcd",k = 5) == 4
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 15) == 1
    assert candidate(word = "mississippi",k = 4) == 3
    assert candidate(word = "abacabadabacabadabacabadabacabadaba",k = 10) == 4
    assert candidate(word = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd",k = 15) == 4
    assert candidate(word = "abcabcabcabcabcabcabcabc",k = 8) == 3
    assert candidate(word = "abcabcabcabcabcabcabcabc",k = 9) == 1
    assert candidate(word = "abababababab",k = 2) == 1
    assert candidate(word = "abcabcabcabcabcabcabcabc",k = 4) == 3
