# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "aaaa",t = "bbbb") == 8
    assert candidate(s = "aabbcc",t = "abc") == 3
    assert candidate(s = "anagram",t = "nagaram") == 0
    assert candidate(s = "rat",t = "car") == 2
    assert candidate(s = "xyz",t = "zyxwvut") == 4
    assert candidate(s = "",t = "") == 0
    assert candidate(s = "leetcode",t = "coats") == 7
    assert candidate(s = "aaaaa",t = "bbbbb") == 10
    assert candidate(s = "ab",t = "ba") == 0
    assert candidate(s = "night",t = "thing") == 0
    assert candidate(s = "abacabadaba",t = "zzzzz") == 16
    assert candidate(s = "aa",t = "bb") == 4
    assert candidate(s = "a",t = "a") == 0
    assert candidate(s = "abcd",t = "dcba") == 0
    assert candidate(s = "abc",t = "def") == 6
    assert candidate(s = "a",t = "b") == 2
    assert candidate(s = "abacabadabacaba",t = "abcde") == 12
    assert candidate(s = "same",t = "same") == 0
    assert candidate(s = "aabbccddeeff",t = "abcdef") == 6
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "") == 26
    assert candidate(s = "oneonetwothree",t = "threeonetwoone") == 0
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "aaaaaaaaaaaaaaaaaaaaaaaaaa") == 50
    assert candidate(s = "thisisateststring",t = "testingstring") == 8
    assert candidate(s = "aabbccddeeff",t = "ffeeddccbbAA") == 4
    assert candidate(s = "anagram",t = "mangaar") == 0
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",t = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb") == 88
    assert candidate(s = "hello",t = "world") == 6
    assert candidate(s = "mississippi",t = "ississimppimiss") == 4
    assert candidate(s = "pythonprogramming",t = "javaprogramming") == 10
    assert candidate(s = "repeatrepeatrepeat",t = "peatpeatpeatre") == 4
    assert candidate(s = "xxyyzz",t = "zzzzyyxx") == 2
    assert candidate(s = "deified",t = "deified") == 0
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba",t = "abcdefghijklmnopqrstuvwxyz") == 0
    assert candidate(s = "pythonprogramming",t = "programmingpython") == 0
    assert candidate(s = "thisisalongstringsample",t = "samplesamplealongstringthisis") == 6
    assert candidate(s = "complexinputfortesting",t = "testingfortestingcomplex") == 6
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzxxccvvaabbeeffgghhiijjkkllmmnnooppqqrrssttuuvvww") == 6
    assert candidate(s = "abracadabra",t = "barbarian") == 6
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzzyyxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccbbaa") == 1
    assert candidate(s = "abracadabra",t = "abrakadabracadabra") == 7
    assert candidate(s = "balancedstring",t = "stringbalanced") == 0
    assert candidate(s = "abcdefghij",t = "abcdefghijjihgfedcba") == 10
    assert candidate(s = "abcdefghijklmnopqrstuvwxy",t = "zyxwvutsrqponmlkjihgfedcba") == 1
    assert candidate(s = "aaabbbccc",t = "bbbaaaccc") == 0
    assert candidate(s = "thisisatest",t = "testthisis") == 1
    assert candidate(s = "encyclopedia",t = "dictionary") == 8
    assert candidate(s = "mississippi",t = "missisippi") == 1
    assert candidate(s = "aaaaabbbbbcccccd",t = "dddddccccbbbbbaaaaa") == 5
    assert candidate(s = "repeatedcharacterss",t = "charactersrepeatedss") == 1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "") == 52
    assert candidate(s = "thisisananagram",t = "isananagramthis") == 0
    assert candidate(s = "abcdefg",t = "hijklmn") == 14
    assert candidate(s = "aaaabbbbccccdddd",t = "ddddccccbbbbaaaa") == 0
    assert candidate(s = "rhinoceros",t = "orchestrer") == 6
    assert candidate(s = "samecharacters",t = "characterssame") == 0
    assert candidate(s = "onetwothreefourfivesixseveneightnine",t = "nineseveneightsixfvierthreeonotwo") == 3
    assert candidate(s = "12345",t = "54321") == 0
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyz") == 1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzyyxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccbbaa") == 0
    assert candidate(s = "anagram",t = "manga") == 2
    assert candidate(s = "samestring",t = "samestring") == 0
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "abcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "thisisaverylongstringthatwearegoingtouseasourtestcase",t = "anotherlongstringthatwillbeusedasourtestcase") == 17
    assert candidate(s = "uniquecharacters",t = "charactersunique") == 0
    assert candidate(s = "elephant",t = "television") == 8
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz",t = "abcdefghijklmnopqrstuvwxyz") == 44
    assert candidate(s = "repeatedcharactersrepeated",t = "charactersrepeatedcharacters") == 10
    assert candidate(s = "thequickbrownfoxjumpsoverthelazydog",t = "doglazytheoverjumpsonbrowquickthe") == 2
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zyxwvutsrqponmlkjihgfedcba") == 26
    assert candidate(s = "abcd",t = "efghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "a",t = "abcdefghijklmnopqrstuvwxyz") == 25
    assert candidate(s = "level",t = "level") == 0
    assert candidate(s = "equalnumberofchars",t = "equalnumberofchars") == 0
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnm",t = "zyxwvutsrqponmlkjihgfedcba") == 0
    assert candidate(s = "supercalifragilisticexpialidocious",t = "pneumonoultramicroscopicsilicovolcanoconiosis") == 25
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 0
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",t = "zzzzzzzzzzzzzzzzzzzz") == 68
    assert candidate(s = "longstringwithrepeatedcharacters",t = "characterswithrepeatedlongstring") == 0
    assert candidate(s = "uniquecharacters",t = "differentcharacters") == 9
    assert candidate(s = "",t = "b") == 1
    assert candidate(s = "mississippi",t = "pensil") == 11
    assert candidate(s = "xyxxyxyxyx",t = "yyxyxyxyxy") == 4
    assert candidate(s = "abracadabra",t = "abracadabracadabra") == 7
    assert candidate(s = "redder",t = "redder") == 0
    assert candidate(s = "hello",t = "billion") == 6
    assert candidate(s = "xylophone",t = "xylophon") == 1
    assert candidate(s = "thqwhrwhrwhr",t = "tttttttttttt") == 22
    assert candidate(s = "xylophone",t = "polyrhythm") == 9
    assert candidate(s = "unique",t = "distinct") == 10
    assert candidate(s = "mississippi",t = "pensylvania") == 16
    assert candidate(s = "xyzxyzxyz",t = "abcabcabc") == 18
    assert candidate(s = "racecar",t = "carrace") == 0
    assert candidate(s = "abcdefg",t = "hijklmnopqrstuvwxyz") == 26
    assert candidate(s = "a",t = "") == 1
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnm",t = "mnbvcxzlkjhgfdsapoiuytrewq") == 0
    assert candidate(s = "abcde",t = "fghij") == 10
    assert candidate(s = "abcdabcdabcdabcd",t = "dcba") == 12
    assert candidate(s = "",t = "abcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "longerstringwithmorecharacters",t = "shortstring") == 19
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "zyxwvutsrqponmlkjihgfedcba") == 0
    assert candidate(s = "longerstringhere",t = "short") == 11
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzzyyxxwwvvuuttssrrqqppoonnmlkkjjiihhggffeeeeddccbbaa") == 5
    assert candidate(s = "thequickbrownfoxjumpsoverthelazydog",t = "thequickbrownfoxjumpsoverthelazydog") == 0
    assert candidate(s = "abcdefghijkllllllllllllmnopqrstuvwxyz",t = "zyxwvutsrqponmlkjihgfedcba") == 11
    assert candidate(s = "xxyyzz",t = "xxxyyyzzz") == 3
    assert candidate(s = "elephant",t = "relevant") == 4
    assert candidate(s = "pythonprogramming",t = "java") == 19
    assert candidate(s = "mississippi",t = "pennsylvania") == 17
    assert candidate(s = "aaaaa",t = "bbbbbbaaaaa") == 6
    assert candidate(s = "rotor",t = "rotor") == 0
