# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(word = "aabbcc",k = 2) == 3
    assert candidate(word = "hello",k = 5) == 1
    assert candidate(word = "xyzxyzxyz",k = 4) == 3
    assert candidate(word = "abcdef",k = 1) == 6
    assert candidate(word = "ababab",k = 2) == 1
    assert candidate(word = "pattern",k = 1) == 7
    assert candidate(word = "abcdefg",k = 2) == 4
    assert candidate(word = "abacaba",k = 3) == 2
    assert candidate(word = "abacaba",k = 4) == 1
    assert candidate(word = "xyzxyz",k = 2) == 3
    assert candidate(word = "banana",k = 3) == 2
    assert candidate(word = "abcabcabc",k = 3) == 1
    assert candidate(word = "hellohello",k = 5) == 1
    assert candidate(word = "racecar",k = 2) == 3
    assert candidate(word = "abcd",k = 1) == 4
    assert candidate(word = "aaaa",k = 1) == 1
    assert candidate(word = "aaaa",k = 2) == 1
    assert candidate(word = "abcbabcd",k = 2) == 4
    assert candidate(word = "abcdef",k = 6) == 1
    assert candidate(word = "rotate",k = 3) == 2
    assert candidate(word = "abcdefghiabcdefghiabcdefghi",k = 9) == 1
    assert candidate(word = "abcabcabcabcabcabcabcabc",k = 7) == 3
    assert candidate(word = "abcdefabcdef",k = 2) == 3
    assert candidate(word = "mississippi",k = 2) == 6
    assert candidate(word = "abcdefghabcdefgh",k = 5) == 4
    assert candidate(word = "abacabadabacabadabacabad",k = 5) == 5
    assert candidate(word = "abacabadabacabad",k = 2) == 4
    assert candidate(word = "abacabacabacabacabacaba",k = 5) == 4
    assert candidate(word = "racecar",k = 1) == 6
    assert candidate(word = "abcabcabcabcabcabcabcabc",k = 6) == 1
    assert candidate(word = "aaaaaa",k = 1) == 1
    assert candidate(word = "cascadecascade",k = 2) == 7
    assert candidate(word = "aaabbbcccdddaa",k = 3) == 4
    assert candidate(word = "zzzzzzzzzzzzzzzz",k = 3) == 1
    assert candidate(word = "aaaabbbbcccc",k = 4) == 3
    assert candidate(word = "abcabcabcabc",k = 3) == 1
    assert candidate(word = "abcdefabcdefabcdefabcdef",k = 6) == 1
    assert candidate(word = "qwertyuiopqwertyuiopqwertyuiop",k = 8) == 4
    assert candidate(word = "abcabcabcabcabc",k = 5) == 3
    assert candidate(word = "abcdefgabcdefg",k = 3) == 5
    assert candidate(word = "abcdefgabcdefg",k = 5) == 3
    assert candidate(word = "aabbccddeeff",k = 6) == 2
    assert candidate(word = "abcdefghabcdefghabcdefgh",k = 8) == 1
    assert candidate(word = "aaaaabbbbbccccdddd",k = 4) == 5
    assert candidate(word = "abcdefghabcdefgh",k = 8) == 1
    assert candidate(word = "abcdeabcdeabcdeabcdeabcdeabcde",k = 9) == 4
    assert candidate(word = "xyzxyzxyzxyz",k = 3) == 1
    assert candidate(word = "qwertyuiopqwertyuiopqwerty",k = 11) == 3
    assert candidate(word = "abcdabcdabcdabcdabcdabcdabcdabcd",k = 8) == 1
    assert candidate(word = "mnopqrstmnopqrstmnopqr",k = 7) == 4
    assert candidate(word = "hellohellohello",k = 5) == 1
    assert candidate(word = "deeddeed",k = 4) == 1
    assert candidate(word = "abababababababab",k = 3) == 2
    assert candidate(word = "repetitionrepetition",k = 7) == 3
    assert candidate(word = "civiccivicciviccivic",k = 4) == 5
    assert candidate(word = "aabbccddeeaabbccddee",k = 5) == 2
    assert candidate(word = "mnopmnopmnopmnop",k = 2) == 2
    assert candidate(word = "abcabcabcabcabcabc",k = 5) == 3
    assert candidate(word = "aabbccddeeffgghhiijj",k = 10) == 2
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzz",k = 10) == 1
    assert candidate(word = "qqwweerrttyy",k = 2) == 6
    assert candidate(word = "abcdabcdabcdabcd",k = 4) == 1
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzz",k = 10) == 1
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 10) == 1
    assert candidate(word = "abababababababababababab",k = 9) == 2
    assert candidate(word = "pneumonoultramicroscopicsilicovolcanoconiosis",k = 10) == 5
    assert candidate(word = "abcdefabcdefabcdef",k = 6) == 1
    assert candidate(word = "banana",k = 1) == 6
    assert candidate(word = "abracadabraabracadabra",k = 5) == 5
    assert candidate(word = "repeatedrepeated",k = 8) == 1
    assert candidate(word = "repeatedstringrepeatedstring",k = 9) == 4
    assert candidate(word = "abcdefgabcdefgabcdefg",k = 6) == 4
    assert candidate(word = "banana",k = 2) == 3
    assert candidate(word = "abcdefabcdef",k = 3) == 2
    assert candidate(word = "abababababababababababab",k = 3) == 2
    assert candidate(word = "aabbccddeeff",k = 2) == 6
    assert candidate(word = "abcabcabcabc",k = 4) == 3
    assert candidate(word = "abcdefghijabcdefghijabcdefghij",k = 10) == 1
    assert candidate(word = "xyxxyxyxxyxyxy",k = 3) == 4
    assert candidate(word = "abcdabcdabcd",k = 5) == 3
    assert candidate(word = "aaaabbbbccccddddeeeeffff",k = 5) == 5
    assert candidate(word = "abcdefghijklmnopqrstuvwxyz",k = 1) == 26
    assert candidate(word = "mississippi",k = 3) == 4
    assert candidate(word = "repetitionrepetitionrepetition",k = 6) == 5
    assert candidate(word = "aabbccddeeff",k = 3) == 4
    assert candidate(word = "abcdabcdabcdabcd",k = 7) == 3
    assert candidate(word = "abacabadabacaba",k = 4) == 2
    assert candidate(word = "aaaaabbbbbccccc",k = 5) == 3
    assert candidate(word = "aaaaaaaaaa",k = 1) == 1
    assert candidate(word = "abracadabra",k = 5) == 2
    assert candidate(word = "abcdabcdabcd",k = 3) == 4
    assert candidate(word = "hellohellohello",k = 6) == 3
    assert candidate(word = "aaaaabbbbb",k = 5) == 2
    assert candidate(word = "abacabadabacaba",k = 5) == 3
    assert candidate(word = "bananaananabayananabanana",k = 5) == 5
    assert candidate(word = "palindromemordnilap",k = 8) == 3
    assert candidate(word = "abracadabraabracadabra",k = 7) == 3
    assert candidate(word = "abcdefghijkabcdefghijk",k = 7) == 4
    assert candidate(word = "abcdabcdabcdabcd",k = 5) == 4
    assert candidate(word = "mississippi",k = 4) == 3
    assert candidate(word = "xyxzyzyzxzyzyzxzyz",k = 3) == 6
    assert candidate(word = "aabbccddeeffgghhiijj",k = 6) == 4
    assert candidate(word = "xyzxyzxyzxyzxyzxyzxyzxyz",k = 8) == 3
    assert candidate(word = "abcabcabcabcabcabc",k = 4) == 3
    assert candidate(word = "mnopqrnopqrmon",k = 6) == 3
    assert candidate(word = "abcdefghabcdefghabcdefghabcdefgh",k = 7) == 5
    assert candidate(word = "abcdabcdabcd",k = 4) == 1
    assert candidate(word = "qwertyqwertyqwerty",k = 6) == 1
