# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "mmmmmmmmmmmmmmmm") == 16
    assert candidate(s = "mississippi") == 11
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 51
    assert candidate(s = "banana") == 6
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 102
    assert candidate(s = "abcdefghijkl") == 15
    assert candidate(s = "hello世界") == 7
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzz") == 26
    assert candidate(s = "programming") == 11
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzz") == 24
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzzzzzzzzzzzzzz") == 76
    assert candidate(s = "apple") == 5
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba") == 51
    assert candidate(s = "thequickbrownfoxjumpsoverthelazydog") == 60
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnm") == 51
    assert candidate(s = "abacabadabacaba") == 15
    assert candidate(s = "optimization") == 12
    assert candidate(s = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb") == 52
    assert candidate(s = "aabbbccccdddd") == 13
    assert candidate(s = "thisisaverylongstringwithmanycharactersandletters") == 60
    assert candidate(s = "allthesametheallthesametheallthesamethe") == 39
    assert candidate(s = "exampleofaverylongstringthatneedsmanykeypresses") == 61
    assert candidate(s = "datastructuresandalgorithms") == 33
    assert candidate(s = "verylongstringwithvariouscharactersandfrequencies") == 64
    assert candidate(s = "algorithmoptimization") == 24
    assert candidate(s = "bananaananabay") == 14
    assert candidate(s = "averylongstringthatincludesmanylettersrepeatedmultipletimes") == 73
    assert candidate(s = "shortstring") == 11
    assert candidate(s = "aaaaaaaaaabbbbbbbbcccccccc") == 26
    assert candidate(s = "oneoneonetwoonetwoonethreeoneoneonetwoonetwothree") == 49
    assert candidate(s = "frequencydistribution") == 26
    assert candidate(s = "zzzaaayyxbbbxxccc") == 17
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 64
    assert candidate(s = "abracadabra") == 11
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 56
    assert candidate(s = "cloudcomputingisthemostmodernwayofdeliveringservices") == 71
    assert candidate(s = "uniquecharactersarespecialtoo") == 34
    assert candidate(s = "keypadmappingoptimization") == 29
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 153
    assert candidate(s = "occurrencesoflettersareirrelevant") == 37
    assert candidate(s = "complexityanalysiscomplexityanalysis") == 44
    assert candidate(s = "frequencydistributionoflettersinenglish") == 48
    assert candidate(s = "equalfrequencyaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 117
    assert candidate(s = "aaaaaaaaaabbbbbbbbccccccccdddddddd") == 34
    assert candidate(s = "abcdefghijkabcdefghijkabcdefghijkabcdefghijkabcdefghijk") == 65
    assert candidate(s = "thisisaverylongstringwithrepeatedcharacters") == 52
    assert candidate(s = "hellohellohellohellohellohellohellohellohellohello") == 50
    assert candidate(s = "frequenciesoffrequentelementsandcharacters") == 50
    assert candidate(s = "frequencydistributionofcharacters") == 42
    assert candidate(s = "repeatedlettersllllllllllllllll") == 31
    assert candidate(s = "pythonprogrammingchallenge") == 32
    assert candidate(s = "uniquenesschecking") == 19
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 51
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 102
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzz") == 104
    assert candidate(s = "algorithms") == 11
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 398
    assert candidate(s = "abcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefg") == 56
    assert candidate(s = "thisisaverylongstringthatweneedtotestthealgorithm") == 59
    assert candidate(s = "repeatedcharactersrepeatedcharactersrepeatedcharacters") == 54
    assert candidate(s = "thisisaverylongstringthatcontainsmanycharactersandshouldrequiremultiplekeypresses") == 106
    assert candidate(s = "pneumonoultramicroscopicsilicovolcanoconiosis") == 52
    assert candidate(s = "optimizationiskeytoefficientcoding") == 41
    assert candidate(s = "xylophoneisamusicalinstrument") == 37
    assert candidate(s = "pressingbuttonsforlongstrings") == 33
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 52
    assert candidate(s = "pythonprogrammingisfun") == 27
    assert candidate(s = "mississippiissimississippi") == 26
    assert candidate(s = "aaaaaaaaaaabbbbbbbbccccccccddddddd") == 34
    assert candidate(s = "toimpressyourinterviewerwithcomplexstrings") == 52
    assert candidate(s = "bananaananabana") == 15
    assert candidate(s = "algorithmsanddatastructures") == 33
    assert candidate(s = "thisisaverylongstringwithmanycharacters") == 48
    assert candidate(s = "thequickbrownfoxjumpsoverthelazydogthequickbrownfoxjumpsoverthelazydog") == 120
    assert candidate(s = "pythonisaveryversatilelanguage") == 38
    assert candidate(s = "optimizationofthekeypadlayout") == 36
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 28
