# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(croakOfFrogs = "croakcroakcroak") == 1
    assert candidate(croakOfFrogs = "croak") == 1
    assert candidate(croakOfFrogs = "cccrroooaaakkk") == -1
    assert candidate(croakOfFrogs = "crcoakroak") == 2
    assert candidate(croakOfFrogs = "crrcooakak") == -1
    assert candidate(croakOfFrogs = "k") == -1
    assert candidate(croakOfFrogs = "crocakroak") == 2
    assert candidate(croakOfFrogs = "ccccrrrrooooaaaakkkk") == 4
    assert candidate(croakOfFrogs = "crrrroooaaaakkk") == -1
    assert candidate(croakOfFrogs = "ccroooakk") == -1
    assert candidate(croakOfFrogs = "ccroakroak") == 2
    assert candidate(croakOfFrogs = "crrrroooookkkkaaa") == -1
    assert candidate(croakOfFrogs = "ccccrrrroooaaaaakkkkkk") == -1
    assert candidate(croakOfFrogs = "kakakakakakakakakakakakakakakakakakakakakakakakakakakakakakakakakak") == -1
    assert candidate(croakOfFrogs = "ccccroakroakroak") == -1
    assert candidate(croakOfFrogs = "kkkrrrooocccaaa") == -1
    assert candidate(croakOfFrogs = "ccccrrrroooaaaaakkkkk") == -1
    assert candidate(croakOfFrogs = "croakcrook") == -1
    assert candidate(croakOfFrogs = "crorocroakakak") == -1
    assert candidate(croakOfFrogs = "crocroak") == -1
    assert candidate(croakOfFrogs = "croakcroakcroakcroakcroakcroakcroakcroakcroakcroak") == 1
    assert candidate(croakOfFrogs = "c") == -1
    assert candidate(croakOfFrogs = "crorocakak") == -1
    assert candidate(croakOfFrogs = "ccccrrrroooaaaakkk") == -1
    assert candidate(croakOfFrogs = "kroac") == -1
    assert candidate(croakOfFrogs = "crocak") == -1
    assert candidate(croakOfFrogs = "crcroaoakk") == 2
    assert candidate(croakOfFrogs = "kraoc") == -1
    assert candidate(croakOfFrogs = "ccccrrooookkkk") == -1
    assert candidate(croakOfFrogs = "") == 0
    assert candidate(croakOfFrogs = "ccrroookkaak") == -1
    assert candidate(croakOfFrogs = "crocroakakroak") == -1
    assert candidate(croakOfFrogs = "croakcroak") == 1
    assert candidate(croakOfFrogs = "ccccrrroooookkkkaaaaaaaaaaaaaaaaa") == -1
    assert candidate(croakOfFrogs = "ccccccroooooorrrraaaaaakkkkk") == -1
    assert candidate(croakOfFrogs = "ccccrrrrrrroooooooooookkkkkkkkaaaaaaaaaacrrrrrrroooooooooookkkkkkkkaaaaaaaaa") == -1
    assert candidate(croakOfFrogs = "croakccccrrroooookkkkroak") == -1
    assert candidate(croakOfFrogs = "crocroakcrocroakcroak") == -1
    assert candidate(croakOfFrogs = "cccrroooakkkaaaa") == -1
    assert candidate(croakOfFrogs = "croakcroakcroakcroakcroakcroakcroakcroakcroakcroakcroak") == 1
    assert candidate(croakOfFrogs = "crocakroakroakroak") == -1
    assert candidate(croakOfFrogs = "croakccroakrrrooookkkkaaaa") == -1
    assert candidate(croakOfFrogs = "ccccrrroooookkkk") == -1
    assert candidate(croakOfFrogs = "ccccrooookaaaakkkkk") == -1
    assert candidate(croakOfFrogs = "crocakcroakcroak") == -1
    assert candidate(croakOfFrogs = "croakkkkroakkkkroakkkk") == -1
    assert candidate(croakOfFrogs = "croakkkkkkkkkk") == -1
    assert candidate(croakOfFrogs = "crrrroookaaaaaakkkk") == -1
    assert candidate(croakOfFrogs = "ccccrrroooookkkkaaaa") == -1
    assert candidate(croakOfFrogs = "crcrooakakro") == -1
    assert candidate(croakOfFrogs = "crocakroakcroakcroakcroakcroak") == 2
    assert candidate(croakOfFrogs = "crocroakcroakccccrrroooookkkkaaaa") == -1
    assert candidate(croakOfFrogs = "ccccrrrooooookkkkkaaa") == -1
    assert candidate(croakOfFrogs = "ccccrrrrooooaaaakkkkccrrrrooooaaaakkkkccrrrrooooaaaakkkk") == -1
    assert candidate(croakOfFrogs = "crcrccrooaaakk") == -1
    assert candidate(croakOfFrogs = "cccrrooookkkkraaacroak") == -1
    assert candidate(croakOfFrogs = "croakccroakcroak") == -1
    assert candidate(croakOfFrogs = "ccccrrrroooookkkkaaaa") == -1
    assert candidate(croakOfFrogs = "crrroooookkkkaaaakkk") == -1
    assert candidate(croakOfFrogs = "cccrooookkkkrrrooookkkk") == -1
    assert candidate(croakOfFrogs = "crrrcroakroakroakroakroak") == -1
    assert candidate(croakOfFrogs = "croakcroakccroakcroak") == -1
    assert candidate(croakOfFrogs = "crocroakcroakcroakcroakcroakcroakcroakcroak") == -1
    assert candidate(croakOfFrogs = "crrroooookkkkkaaaakkkk") == -1
    assert candidate(croakOfFrogs = "crocroakcrocroakcrocroak") == -1
    assert candidate(croakOfFrogs = "croakkkkrooocrakcroak") == -1
    assert candidate(croakOfFrogs = "crcrooakrakok") == -1
    assert candidate(croakOfFrogs = "crocakrocakrocak") == -1
    assert candidate(croakOfFrogs = "croakcrocakcroakcrocakcrocak") == -1
    assert candidate(croakOfFrogs = "ccccrrrrooooaaaakkkkccccrrrrooooaaaakkkkccccrrrrooooaaaakkkkccccrrrrooooaaaakkkk") == 4
    assert candidate(croakOfFrogs = "croakkkkrooocrakcroakcroakcroak") == -1
    assert candidate(croakOfFrogs = "crcoakrcoak") == -1
    assert candidate(croakOfFrogs = "crrrrooooookkkkkkaaaa") == -1
    assert candidate(croakOfFrogs = "ccccroooaaaaakkkakkkakkk") == -1
    assert candidate(croakOfFrogs = "ccccroooaaaaakkkakkk") == -1
    assert candidate(croakOfFrogs = "crorocokakak") == -1
    assert candidate(croakOfFrogs = "crrrrroooookkkkaaaa") == -1
    assert candidate(croakOfFrogs = "croakcrrooakroakroakcroak") == -1
    assert candidate(croakOfFrogs = "crcrooakkaakrook") == -1
    assert candidate(croakOfFrogs = "crocakroakroakroakroakroakroakroakroakroakroak") == -1
    assert candidate(croakOfFrogs = "crcrooakrakokcrcrooakrakokcrcrooakrakok") == -1
    assert candidate(croakOfFrogs = "ccccrooookaaaakkkkkkk") == -1
    assert candidate(croakOfFrogs = "ccrrroooookkkkaaaa") == -1
    assert candidate(croakOfFrogs = "croakccrookraaaakkk") == -1
    assert candidate(croakOfFrogs = "ccccccccrrrrrroooooookkkkkkkkkkkaaaaaaaaa") == -1
    assert candidate(croakOfFrogs = "crocroakkkk") == -1
    assert candidate(croakOfFrogs = "croakrcoakcroak") == -1
    assert candidate(croakOfFrogs = "croakkkkrooocrakcroakcroak") == -1
    assert candidate(croakOfFrogs = "ccccrrrooooookkkkaaaa") == -1
    assert candidate(croakOfFrogs = "crocrocrocrocroakroakroak") == -1
    assert candidate(croakOfFrogs = "crrrroooookkkkaaaak") == -1
    assert candidate(croakOfFrogs = "croakkkkkkrrroooooooaaaaaaa") == -1
    assert candidate(croakOfFrogs = "crcoakroakcrcoakroak") == 2
    assert candidate(croakOfFrogs = "crocrocrocrocrocroakroakroakroakroak") == -1
    assert candidate(croakOfFrogs = "ccccrrroooookkkkkaaaa") == -1
    assert candidate(croakOfFrogs = "crocakroakcroakcroak") == 2
    assert candidate(croakOfFrogs = "crcrcooakokrakraokakcroakcroak") == -1
    assert candidate(croakOfFrogs = "crrrroooookkkkaaaakkkk") == -1
    assert candidate(croakOfFrogs = "ccccroooaaaakkkk") == -1
    assert candidate(croakOfFrogs = "croakkkkkkkkkkroakroakroakcroak") == -1
    assert candidate(croakOfFrogs = "ccccccroooooorrrraaaaaakkkkkkk") == -1
    assert candidate(croakOfFrogs = "crcroakroakcrcoak") == -1
    assert candidate(croakOfFrogs = "ccrrroooookkkkaaaak") == -1
    assert candidate(croakOfFrogs = "crocroakcroakcroakcroakcroakcroakcroakcroakcroak") == -1
    assert candidate(croakOfFrogs = "crcoakrcoakrcoak") == -1
    assert candidate(croakOfFrogs = "ccccrrrooookkkkaaaakkkkroakroak") == -1
    assert candidate(croakOfFrogs = "ccccccccrrrrrrrrrrroooooooooookkkkkkkkaaaaaaaa") == -1
    assert candidate(croakOfFrogs = "ccrooakrkkaocroakcraok") == -1
    assert candidate(croakOfFrogs = "crcrooakrakokcrcrooakrakok") == -1
    assert candidate(croakOfFrogs = "crorarokkorakocraok") == -1
    assert candidate(croakOfFrogs = "croakroakroakcroakroakroakroakcroakroakroak") == -1
    assert candidate(croakOfFrogs = "ccccrrroooookkkkaaaaaaaaa") == -1
    assert candidate(croakOfFrogs = "cccrroooraaakk") == -1
    assert candidate(croakOfFrogs = "crocrocrocrocroakroakroakroak") == -1
    assert candidate(croakOfFrogs = "crocroakcroakcroakcroakcroakcroakcroakcroakcroakcroak") == -1
    assert candidate(croakOfFrogs = "ccccroooraaaakkkkk") == -1
    assert candidate(croakOfFrogs = "crocroakroakcroak") == -1
    assert candidate(croakOfFrogs = "crocroakroakroakroak") == -1
    assert candidate(croakOfFrogs = "croakcroakcrorocroak") == -1
    assert candidate(croakOfFrogs = "croakcroakroakcroakcroak") == -1
    assert candidate(croakOfFrogs = "crrrrroooookkkkaaaaakkkk") == -1
    assert candidate(croakOfFrogs = "ccccroooaarrrkkk") == -1
    assert candidate(croakOfFrogs = "ccccroooaaaaakkkaaa") == -1
    assert candidate(croakOfFrogs = "crrrrrrrrroooooooooookkkkkkkkaaaaaaaaa") == -1
    assert candidate(croakOfFrogs = "croakcroakcroakcroakcroakcroakcroakcroakcroak") == 1
    assert candidate(croakOfFrogs = "ccrroooaakkccrooakaakk") == -1
    assert candidate(croakOfFrogs = "ccrrroooookkkkaaaacccrrroooookkkkaaaa") == -1
    assert candidate(croakOfFrogs = "ccccroakcroakcroakroakcroak") == -1
    assert candidate(croakOfFrogs = "crcrooakakroccrooakakro") == -1
    assert candidate(croakOfFrogs = "croakcroakroakroakroakroakroakroak") == -1
    assert candidate(croakOfFrogs = "ccroakroakroak") == -1
    assert candidate(croakOfFrogs = "crocrokakakcroakroakroak") == -1
    assert candidate(croakOfFrogs = "croakcroakcroakcroak") == 1
    assert candidate(croakOfFrogs = "ccccrrrrooooaaaakkkkccccrrrrooooaaaakkkkccccrrrrooooaaaakkkk") == 4
    assert candidate(croakOfFrogs = "ccroakccroakccroak") == -1
    assert candidate(croakOfFrogs = "ccccrrroooookkkkkk") == -1
    assert candidate(croakOfFrogs = "cccrroooookkkkaaaakkkk") == -1
    assert candidate(croakOfFrogs = "crrrroooookkkkac") == -1
    assert candidate(croakOfFrogs = "crorokokokakakc") == -1
    assert candidate(croakOfFrogs = "crocakcroakcroakcroak") == -1
    assert candidate(croakOfFrogs = "crrrooookkkkaaacrrrooookkkkaaa") == -1
    assert candidate(croakOfFrogs = "crocroakroakroakcroakcroak") == -1
    assert candidate(croakOfFrogs = "ccrroookkaaa") == -1
    assert candidate(croakOfFrogs = "crrrooookkkk") == -1
    assert candidate(croakOfFrogs = "crocrokakakcroakroak") == -1
    assert candidate(croakOfFrogs = "ccrroooaakkccrooakaakkccrroooaakk") == -1
    assert candidate(croakOfFrogs = "ccccrrroooookkkkaaaacrrroooookkkkaaaacrrroooookkkkaaa") == -1
    assert candidate(croakOfFrogs = "croakcroakcroakcroakcroakcroakcroakcroak") == 1
    assert candidate(croakOfFrogs = "croakcroakcroakcroakcroakcroakcroak") == 1
    assert candidate(croakOfFrogs = "croakcroakcroakcroakcroakcroakcroakcroakcroakcroakcroakcroakcroakcroakcroakcroak") == 1
    assert candidate(croakOfFrogs = "crcrrooookkkaaa") == -1
    assert candidate(croakOfFrogs = "crocroakroakroakroakcroakcroak") == -1
    assert candidate(croakOfFrogs = "crocroakcroak") == -1
    assert candidate(croakOfFrogs = "crrrcroakroakroakroakroakroak") == -1
    assert candidate(croakOfFrogs = "crrroookkkkrrroooookkkk") == -1
    assert candidate(croakOfFrogs = "crrrooookkkkaaa") == -1
    assert candidate(croakOfFrogs = "crocrokrocroakakak") == -1
    assert candidate(croakOfFrogs = "crrookkcraaacroakcroak") == -1
    assert candidate(croakOfFrogs = "crcrcooakokrakraokak") == -1
    assert candidate(croakOfFrogs = "crocroakcrocroakcrocroakcroak") == -1
    assert candidate(croakOfFrogs = "croakcroakcroakcroakccroooaakk") == -1
    assert candidate(croakOfFrogs = "ccccrrrrrrrooooooookkkkkkkaaaaaaa") == -1
    assert candidate(croakOfFrogs = "croakcroakccroaaaakkk") == -1
    assert candidate(croakOfFrogs = "crocroakroakcroakcroak") == -1
    assert candidate(croakOfFrogs = "crocroakroakcroakcroakcroak") == -1
    assert candidate(croakOfFrogs = "crocroakroakroakroakroakroakroakroakroakroakcroakcroak") == -1
    assert candidate(croakOfFrogs = "crrroooookkkkaaaakkkkkkk") == -1
    assert candidate(croakOfFrogs = "ccccrrrooookkkkaaakk") == -1
    assert candidate(croakOfFrogs = "crrcroakroakcroakroakroak") == -1
    assert candidate(croakOfFrogs = "ccccrrrrroooookkkkaaaakkkk") == -1
    assert candidate(croakOfFrogs = "ccccrrroooookkkkaaaakkkk") == -1
    assert candidate(croakOfFrogs = "ccroakcroakcroakcroakcroakcroak") == -1
    assert candidate(croakOfFrogs = "croakcrocakcroakcrocak") == -1
    assert candidate(croakOfFrogs = "ccccrrrrooooaaaakkkkccccrrrrooooaaaakkkk") == 4
    assert candidate(croakOfFrogs = "croakcroakcrcoakroakcrocroak") == -1
    assert candidate(croakOfFrogs = "crcrooakakroccrooakakroccrooakakro") == -1
    assert candidate(croakOfFrogs = "crocakcroakcroakcroakcroakcroakcroakcroakcroakcroakcroakcroak") == -1
    assert candidate(croakOfFrogs = "crocroakroakcroakcroakcroakcroak") == -1
    assert candidate(croakOfFrogs = "croakkkcroak") == -1
    assert candidate(croakOfFrogs = "ccroakroakroakroak") == -1
    assert candidate(croakOfFrogs = "ccccrooorkkkaa") == -1
    assert candidate(croakOfFrogs = "crcrooakrakokcrcrooakrakokcrcrooakrakokcrcrooakrakok") == -1
    assert candidate(croakOfFrogs = "crcrooakrakokcrcrooakrakokcrcrooakrakokcrcrooakrakokcrcrooakrakok") == -1
    assert candidate(croakOfFrogs = "croakcroakcroakcroakcroakcroak") == 1
    assert candidate(croakOfFrogs = "cccroooraakk") == -1
    assert candidate(croakOfFrogs = "crrrooookkkkkaaa") == -1
    assert candidate(croakOfFrogs = "ccccrrrrroooookkkkaaaa") == -1
    assert candidate(croakOfFrogs = "crrroookkkkrrroooookkkkrrroooookkkk") == -1
    assert candidate(croakOfFrogs = "crocrocrocroakroakroakroak") == -1
    assert candidate(croakOfFrogs = "crocrocrocrocrocrocrocrocrocrocrocrocroak") == -1
    assert candidate(croakOfFrogs = "croakcroakcroakcroakcroak") == 1
    assert candidate(croakOfFrogs = "crrrooookkkkaaaa") == -1
    assert candidate(croakOfFrogs = "crrrrroooookkkkaaaaacrrrrroooookkkkaaaa") == -1
    assert candidate(croakOfFrogs = "ccccrrrooookkkkaaaaaaaaaa") == -1
    assert candidate(croakOfFrogs = "cccroaaakkkkroooraak") == -1
    assert candidate(croakOfFrogs = "croakcroakcrocroakroak") == -1
    assert candidate(croakOfFrogs = "crcroakroakroakroakroakroak") == -1
