# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "aabbcc",k = 3) == 0
    assert candidate(s = "abccba",k = 2) == 2
    assert candidate(s = "aabbccdd",k = 4) == 0
    assert candidate(s = "abcabcabc",k = 4) == 4
    assert candidate(s = "aaaaaa",k = 2) == 0
    assert candidate(s = "abcabcabcabc",k = 4) == 3
    assert candidate(s = "abccba",k = 1) == 0
    assert candidate(s = "aabbaa",k = 3) == 0
    assert candidate(s = "racecar",k = 1) == 0
    assert candidate(s = "abcac",k = 2) == 1
    assert candidate(s = "zzzzzz",k = 2) == 0
    assert candidate(s = "abcdabc",k = 2) == 2
    assert candidate(s = "abcdefg",k = 2) == 3
    assert candidate(s = "abcdcba",k = 3) == 2
    assert candidate(s = "abcdefg",k = 3) == 3
    assert candidate(s = "abcabcabc",k = 3) == 3
    assert candidate(s = "aaaa",k = 2) == 0
    assert candidate(s = "abcdabc",k = 3) == 3
    assert candidate(s = "abcabc",k = 3) == 3
    assert candidate(s = "abcdef",k = 2) == 2
    assert candidate(s = "abccba",k = 3) == 2
    assert candidate(s = "ababab",k = 3) == 3
    assert candidate(s = "qwertyuiopqwertyuiopqwertyuiop",k = 6) == 5
    assert candidate(s = "aabbccddeeaabbccddeeaabbccdd",k = 6) == 2
    assert candidate(s = "abcdefedcbafedcba",k = 3) == 1
    assert candidate(s = "abcdabcdabcdabcdabcdabcd",k = 5) == 2
    assert candidate(s = "abcdabcdabcdabcd",k = 4) == 2
    assert candidate(s = "xyzxyzxyzxyz",k = 4) == 3
    assert candidate(s = "xyzxyzxyzxyzxyz",k = 3) == 1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba",k = 5) == 4
    assert candidate(s = "abcdeabcdeabcde",k = 4) == 5
    assert candidate(s = "level",k = 1) == 0
    assert candidate(s = "banana",k = 2) == 1
    assert candidate(s = "aabbaabbaabbaabb",k = 4) == 0
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmlloo",k = 5) == 6
    assert candidate(s = "abccbaabccbaabccba",k = 4) == 2
    assert candidate(s = "abracadabraabracadabra",k = 4) == 5
    assert candidate(s = "redder",k = 2) == 2
    assert candidate(s = "repaper",k = 2) == 3
    assert candidate(s = "abababaabab",k = 3) == 0
    assert candidate(s = "abcdefghij",k = 2) == 4
    assert candidate(s = "abcdefabcdef",k = 4) == 4
    assert candidate(s = "abcdefghiabcdefghiabcdefghi",k = 4) == 3
    assert candidate(s = "xyzxyzxyzxyzxyz",k = 5) == 4
    assert candidate(s = "aabbaaabbbaa",k = 3) == 1
    assert candidate(s = "aaabbbcccdddaaa",k = 4) == 2
    assert candidate(s = "abcdefgabcdefg",k = 4) == 5
    assert candidate(s = "xyxzyxzyxzyxzyxzyx",k = 4) == 1
    assert candidate(s = "xyxyxyxyxyxyxy",k = 3) == 0
    assert candidate(s = "aaaaabbbbbcccc",k = 3) == 0
    assert candidate(s = "ababababababab",k = 3) == 0
    assert candidate(s = "abcdefghabcdefghabcdefgh",k = 6) == 5
    assert candidate(s = "mississippi",k = 2) == 2
    assert candidate(s = "abccbaabccba",k = 2) == 0
    assert candidate(s = "abcdefabcdefabcdef",k = 6) == 6
    assert candidate(s = "abcdefggfedcba",k = 2) == 5
    assert candidate(s = "noonnoonnoon",k = 3) == 0
    assert candidate(s = "aabbccddeeffgghhiijj",k = 5) == 4
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnoopp",k = 6) == 8
    assert candidate(s = "aaabaaabaaabaaab",k = 5) == 1
    assert candidate(s = "aabbccddeeff",k = 3) == 4
    assert candidate(s = "abcdefgabcdefg",k = 2) == 5
    assert candidate(s = "racecar",k = 3) == 2
    assert candidate(s = "abababab",k = 3) == 1
    assert candidate(s = "ababababababab",k = 5) == 1
    assert candidate(s = "abcabcabcabcabcabc",k = 6) == 5
    assert candidate(s = "mnopqrnopqr",k = 3) == 4
    assert candidate(s = "deified",k = 1) == 0
    assert candidate(s = "abcdefghijabcdefghijabcdefghij",k = 5) == 4
    assert candidate(s = "abcabcabcabcabcabcabc",k = 7) == 6
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 7) == 0
    assert candidate(s = "abcdefghij",k = 5) == 5
    assert candidate(s = "noon",k = 1) == 0
    assert candidate(s = "aaaaaaaaaa",k = 5) == 0
    assert candidate(s = "abcdefghijklnmopqrstuvwxyz",k = 5) == 9
    assert candidate(s = "abcdefghij",k = 3) == 4
    assert candidate(s = "racecar",k = 2) == 3
    assert candidate(s = "rotor",k = 1) == 0
    assert candidate(s = "abracadabraabracadabra",k = 5) == 4
    assert candidate(s = "xyzyxzyxzyx",k = 4) == 3
    assert candidate(s = "aaaaabbbbccccdddd",k = 4) == 0
    assert candidate(s = "aaabbbcccdddeeefffggg",k = 5) == 3
    assert candidate(s = "aaaabbbbccccdddd",k = 4) == 0
    assert candidate(s = "abcabcabcabcabcabcabcabc",k = 6) == 3
    assert candidate(s = "ababababab",k = 3) == 0
    assert candidate(s = "aabaaabaaabaaa",k = 4) == 1
    assert candidate(s = "aabbccddeeffgg",k = 4) == 4
    assert candidate(s = "aaaaabbbbcccc",k = 3) == 0
    assert candidate(s = "mnopqrsmnopqrsmno",k = 3) == 6
    assert candidate(s = "aabbccddeeffgg",k = 6) == 2
    assert candidate(s = "zzzaaaabbbccc",k = 4) == 0
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",k = 10) == 10
    assert candidate(s = "abababababababab",k = 4) == 0
    assert candidate(s = "mnopqrspqrspqr",k = 3) == 2
    assert candidate(s = "abacabadaba",k = 3) == 1
    assert candidate(s = "mississippi",k = 3) == 1
    assert candidate(s = "abacabadabacaba",k = 5) == 2
    assert candidate(s = "abacabadabacaba",k = 3) == 0
    assert candidate(s = "zzzzzyzzzzzz",k = 5) == 0
    assert candidate(s = "xyxyxyxyxyxy",k = 6) == 6
    assert candidate(s = "abcdeedcba",k = 2) == 4
    assert candidate(s = "abcdabcdabcdabcdabcd",k = 4) == 1
    assert candidate(s = "abcdefedcba",k = 5) == 4
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaa",k = 5) == 0
    assert candidate(s = "zzzzzyzzzzz",k = 2) == 0
    assert candidate(s = "abcabcabcabcabc",k = 5) == 4
    assert candidate(s = "abcdefabcdef",k = 2) == 1
    assert candidate(s = "abcdefabcdefabcdefabcdef",k = 5) == 3
    assert candidate(s = "anana",k = 1) == 0
    assert candidate(s = "abcdefghijabcdefghij",k = 5) == 7
    assert candidate(s = "aaaabbbb",k = 2) == 0
    assert candidate(s = "xyzyzyzyz",k = 4) == 3
    assert candidate(s = "mnopqrstuvwx",k = 4) == 4
    assert candidate(s = "zzzzzzyyyzzzzzyyy",k = 2) == 0
    assert candidate(s = "reviled",k = 2) == 3
    assert candidate(s = "aaabbbbccccaaa",k = 3) == 3
    assert candidate(s = "abacabadabacaba",k = 4) == 1
    assert candidate(s = "aabbccddeeff",k = 4) == 2
    assert candidate(s = "xyzxyzxyzxyzxyz",k = 4) == 3
