# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "zzzzzzzzz") == 1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "abababab") == 2
    assert candidate(s = "a") == 1
    assert candidate(s = "abcabcabcabc") == 3
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "aa") == 1
    assert candidate(s = "xyzxyzxyz") == 3
    assert candidate(s = "abba") == 2
    assert candidate(s = "abcdeedcba") == 5
    assert candidate(s = "abcdabcdabcd") == 4
    assert candidate(s = "abacabadabacabad") == 8
    assert candidate(s = "aabbccddeeffgghh") == 16
    assert candidate(s = "aaaa") == 1
    assert candidate(s = "abcbcacabbaccba") == 3
    assert candidate(s = "aabbcc") == 6
    assert candidate(s = "cdef") == 4
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 52
    assert candidate(s = "xyzxyzxyzxyz") == 3
    assert candidate(s = "abcdabcdabcdabcd") == 4
    assert candidate(s = "abcdefg") == 7
    assert candidate(s = "thisisaverylongstringthatwillrequireauniquestringtobeformedanditshouldbechecked") == 79
    assert candidate(s = "abacabadabacabadabacabadabacaba") == 31
    assert candidate(s = "abracadabrabracadabrabracadabrabracadabrabracadabraca") == 53
    assert candidate(s = "ninnininnininnininininininininininininininininininininininininin") == 64
    assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghij") == 10
    assert candidate(s = "mnopqrstmnopqrstmnopqrstmnopqrstmnopqrstmnopqrstmnopqrst") == 8
    assert candidate(s = "abcabcabcabcaa") == 7
    assert candidate(s = "tomatotomatotomatotomatotomatotomatotomatotomatotomato") == 6
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc") == 3
    assert candidate(s = "xyxxyxyxxyxxyxyxxyxxyxyxxyxxyxyxxyxxyxyxxyxxyxyxxyxxyxyxxyxxyxyxxyxxyxyx") == 8
    assert candidate(s = "mamamamamamamamamamamamamamamamamamamamamama") == 2
    assert candidate(s = "abracadabraacarbadrabracadabraacarbadrabracadabraacarbadrabracadabra") == 68
    assert candidate(s = "racecarracecarracecar") == 7
    assert candidate(s = "shortyetuniquestringwithanagramstestcase") == 40
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm") == 26
    assert candidate(s = "lollipoplollipoplollipoplollipoplollipoplollipoplollipoplollipop") == 8
    assert candidate(s = "abcdefgabcdefgabcdefgabcdefgabcdefgabcdefg") == 7
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 4
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcd") == 4
    assert candidate(s = "mnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 66
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzabcdef") == 58
    assert candidate(s = "abcdefgabcdefgabcdefgabcdefg") == 7
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "mnopqrstmnopqrstmnopqrstmnopqrstmnopqrstmnopqrstmnopqrstmnopqrstmnopqrstu") == 73
    assert candidate(s = "ppppeeeaaaallllllaaaabbbbcccdddd") == 32
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "abcdefghijklmnopqrstuvwxyza") == 27
    assert candidate(s = "abcdefghijabcdefghijabcdefghij") == 10
    assert candidate(s = "zyxzyxzyxzyxzyx") == 3
    assert candidate(s = "elephantelephantelephantelephantelephantelephant") == 8
    assert candidate(s = "abcdefabcdefabcdefabcdefabcdefabcdefabcdef") == 6
    assert candidate(s = "xyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyz") == 63
    assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij") == 10
    assert candidate(s = "aaabbbcccdddaa") == 14
    assert candidate(s = "mmnnooppqqrrssttuuvvwwxxyyzz") == 28
    assert candidate(s = "aabbaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 56
    assert candidate(s = "qqwweerrttyyuuiiooppaassddffgg") == 30
    assert candidate(s = "abcabcabcabccbaabccbaabc") == 3
    assert candidate(s = "xyzxyzxyzxyzxyz") == 3
    assert candidate(s = "abcdefghijlmnopqrstuvwxyzmnopqrstuvwxyzabcdefghij") == 49
    assert candidate(s = "aaaaabbbbccccddddeeeeeffffffggggghhhhiiiiijjjjjkkkkklllllmmmmmnnnnnooooo") == 72
    assert candidate(s = "mississippimississippi") == 11
    assert candidate(s = "mnopqrstmnopqrstmnopqrstmnopqrst") == 8
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 4
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabc") == 3
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "abcdefghijkabcdefghijkabcdefghijkabcdefghijkabcdefghijkabcdefghijkabcdefghijkabcdefghijk") == 11
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "bananaananabanana") == 17
