# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(word = "aaabbbccc") == 11
    assert candidate(word = "zyxwvut") == 14
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 29
    assert candidate(word = "mnbvcxzlkjhgfdsapoiuytrewq") == 178
    assert candidate(word = "qpwoeirutyalskdjfhgzmxncbv") == 191
    assert candidate(word = "zjpc") == 34
    assert candidate(word = "abcdz") == 12
    assert candidate(word = "pqrstuvwxyzabcdefghijklmno") == 62
    assert candidate(word = "aaa") == 3
    assert candidate(word = "mnopqrstuvwxyzabcdefghijkl") == 63
    assert candidate(word = "z") == 2
    assert candidate(word = "aaaaaaaaaaaaaaaaaaaaaaaaaa") == 26
    assert candidate(word = "qpwoeirutyalskdjfhgzmxncbva") == 197
    assert candidate(word = "za") == 4
    assert candidate(word = "zzz") == 4
    assert candidate(word = "qpwoeirutyalskdjfhgzmxcvbn") == 193
    assert candidate(word = "mnonmonmomnonmon") == 47
    assert candidate(word = "a") == 1
    assert candidate(word = "bza") == 7
    assert candidate(word = "abc") == 5
    assert candidate(word = "az") == 3
    assert candidate(word = "zyxwvutsrqponmlkjihgfedcba") == 52
    assert candidate(word = "abcdefghijklmnopqrstuvwxyz") == 51
    assert candidate(word = "abacabadabacaba") == 37
    assert candidate(word = "mnbvcxzlkjhgfdsapoiuytrewqmnbvcxzlkjhgfdsapoiuytrewq") == 348
    assert candidate(word = "adgjmpsvxzbehiklnortuwfyqc") == 110
    assert candidate(word = "bbaaccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 79
    assert candidate(word = "aazzbbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 81
    assert candidate(word = "mamamamamamamamamamamamamam") == 351
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 47
    assert candidate(word = "abcdezyxwvut") == 27
    assert candidate(word = "zaqwsxcderfvgytujnhytgfrdxcvbnmzaqwsxcderfv") == 328
    assert candidate(word = "mnopqrstuvmnopqrstuvmnopqrstuv") == 87
    assert candidate(word = "qwertyuioplkjhgfdsazxcvbnmnbvcxzlkjhgfdsapoiuytrewq") == 323
    assert candidate(word = "mamamamamamamamamamamamamamamamamamamamamamamamamamama") == 702
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzzzzzzzz") == 70
    assert candidate(word = "qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm") == 346
    assert candidate(word = "lkjhgfdsapoiuytrewqzxcvbnm") == 174
    assert candidate(word = "mjmlkdjfhakjdhfkahdfkldshfklsjdhfkjd") == 217
    assert candidate(word = "aaaabbbbccccddddeeeeffffgggghhhhiiiiijjjjkkkkllllmmmmnnnnooooppppqqqqrrrrssssttttuuuuvvvvwwwwxxxxyyyyzzzz") == 130
    assert candidate(word = "aaaabbbbccccddddeeeeffffgggghhhhiiii") == 44
    assert candidate(word = "lkjhgfdsapoiuytrewqmasdfghjkl") == 178
    assert candidate(word = "qponmlkjihgfedcba") == 43
    assert candidate(word = "jklmnopqrstuvwxyzaaaazzzzz") == 53
    assert candidate(word = "wvutsrqponmlkjihgfedcba") == 49
    assert candidate(word = "wertyuioplkjhgfdsamnbvcxzabcd") == 164
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 33
    assert candidate(word = "abcdpqrsuvxyzefghijkmnotwxyz") == 79
    assert candidate(word = "qwertypasdfghjklzxcvbnmqwertypasdfghjklzxcvbnm") == 312
    assert candidate(word = "bdfhjlnprtvxz") == 38
    assert candidate(word = "qzcvmlkjhgfdsapoiuytrwer") == 157
    assert candidate(word = "mnopqrstuvwxynmlkjihgfedcbazyxw") == 83
    assert candidate(word = "abcdefghijklmnopqrstuvwxyza") == 53
    assert candidate(word = "zyzzzzzzzzzzzzzzzzzzzzzzzzz") == 30
    assert candidate(word = "qwerasdfzxcv") == 99
    assert candidate(word = "abcdefghijklnmopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 104
    assert candidate(word = "abcdpqrsuvxyzefghijkmnotw") == 73
    assert candidate(word = "dcbazyxwvutsrqponmlkjihgfedcba") == 62
    assert candidate(word = "fedcbaZYXWVUTSRQPONMLKJIHGFEDCBA") == 74
    assert candidate(word = "acdfghjklmnpqrstvwxyz") == 46
    assert candidate(word = "mnopqrstuzyxwvutsrqponmlkjihgfedcba") == 85
    assert candidate(word = "zxcvbnmlkjhgfdsapoiuytrewqzxcvbnmlkjhgfdsapoiuytrewq") == 320
    assert candidate(word = "lkjhgfdsapoiuytrewqzxcvbnmzxcvbnmlkjhgfdsapoiuytrewq") == 342
    assert candidate(word = "fedcbazyxwvutsrqponmlkjihg") == 56
    assert candidate(word = "aaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbb") == 40
    assert candidate(word = "mnopqrlkjihgfedcbazyxwvut") == 66
    assert candidate(word = "qpwoeirutyalskdjfhgzxcvbnm") == 172
    assert candidate(word = "mlkjihgfedcba") == 37
    assert candidate(word = "yzab") == 9
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 102
    assert candidate(word = "qzmlkihgfedcba") == 58
    assert candidate(word = "bcadefghijklmnopqrstuvwxyz") == 55
    assert candidate(word = "aaaaaaaaaaaabbbbbbbbccccccccdddddd") == 37
    assert candidate(word = "llllllllllllllllllllllllllllllllllllllllllllllllllllllll") == 67
    assert candidate(word = "nlbnlkbnlkbnlkbnlkbnlkbnlkbnlkbnlkbnlkbnlkbnlkbnlkbnlkb") == 392
    assert candidate(word = "lkjhgfdsazxcvbnmmnbvcxzlkjhgfdsa") == 176
    assert candidate(word = "mnopqrsvxyz") == 36
    assert candidate(word = "poiuytrewqlkjhgfdsamnbvcxzpoiuytrewqlkjhgfdsamnbvcxz") == 341
    assert candidate(word = "qwertypoiuytrewertyuiop") == 178
    assert candidate(word = "aaaaabbbbbcccccdddddeeeee") == 29
    assert candidate(word = "uqwertyuioplkjhgfdsamnbvcxz") == 170
    assert candidate(word = "zyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcba") == 104
    assert candidate(word = "qrstuvzxcvbnmlkjhgfedcba") == 88
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 35
    assert candidate(word = "qwerasdfzxcvqwerasdfzxcvqwerasdfzxcv") == 287
    assert candidate(word = "lkmlkmlkmlkmlkmlkmlkmlkmlkmlkmlkmlkmlkmlkmlkmlkmlkmlkm") == 136
    assert candidate(word = "zazazazazazazazazazazazazazazaz") == 62
    assert candidate(word = "aazzzzyyyyxxxwwvvuuttrrssqqppoonnmmlkkjjiihhggffeeddaa") == 82
    assert candidate(word = "jqpnfjwmsvkmrekjijgqpxvukz") == 175
    assert candidate(word = "lkjhgfdsapoiuytrewqasdfghjklmnbvcxz") == 212
    assert candidate(word = "ejpmytlrzwhgodicuvnkxfsab") == 190
    assert candidate(word = "qwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnm") == 310
    assert candidate(word = "qrstuvwxyzaeiou") == 55
    assert candidate(word = "aeiouyaeiouyaeiouyaeiouy") == 126
    assert candidate(word = "zyxwvutsrqponmlkjihgfedcbaa") == 53
    assert candidate(word = "poiuytrewqasdfghjklzxcvbnmpoiuytrewqasdfghjklzxcvbnmpoiuytrewq") == 414
    assert candidate(word = "abcdefghjklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 101
    assert candidate(word = "qazwsxedcrfvtgbyhnujmikolpqwazxsedcrfvtgbyhnujmikolpqwaz") == 361
    assert candidate(word = "mzaixmsdcvnbmqwerty") == 169
    assert candidate(word = "zabcdefghijklmnopqrstuvwxyz") == 54
    assert candidate(word = "poiuytrewqlkjhgfdsamnbvcxz") == 171
    assert candidate(word = "zyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyx") == 111
    assert candidate(word = "aaaaaaaaaaaaaaaaaaaaaaaaaaab") == 29
    assert candidate(word = "pppppppppppppppppppppppppppp") == 39
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 103
    assert candidate(word = "abcdefghijkmnopqrstuvwxyz") == 50
    assert candidate(word = "azzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 58
    assert candidate(word = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 97
    assert candidate(word = "zaazaaazzaa") == 17
    assert candidate(word = "zzzaaazzzaaazzzaaazzzaaazzzaaazzz") == 44
    assert candidate(word = "zyxcbaqwertyuiopasdfghjklmnbvcxz") == 181
    assert candidate(word = "asdfghjklqwertyuiopzxcvbnm") == 158
    assert candidate(word = "pqrstuvwxyzyxwvutsrqponmlkjihgfedcba") == 82
    assert candidate(word = "zabcdefghijklmnopqrstuvwxyza") == 56
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzza") == 54
    assert candidate(word = "tgbnhyujmkiolpvcxz") == 125
    assert candidate(word = "qwertyuiopasdfghjklzxcvbnm") == 176
    assert candidate(word = "qazwsxedcrfvtgbyhnujmikolp") == 177
    assert candidate(word = "zyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyx") == 118
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 77
    assert candidate(word = "mnbvcxzlkjhgfdsapoiuytrewqasdfghjklpoiuytrewq") == 295
    assert candidate(word = "lkjlkjlkjlkjlkjlkjlkjlkjlkjlkjlkjlkjlkjlkjlkjlkjlkjlkj") == 135
    assert candidate(word = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 103
    assert candidate(word = "bcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbc") == 64
    assert candidate(word = "mnopqrstuvwx") == 35
    assert candidate(word = "zyxwvutsrqponmlkjihgfedcbaqwertyuiop") == 129
    assert candidate(word = "abacabadabacabadabacaba") == 59
    assert candidate(word = "fedcbazyxwvutsrqponmlkjihgfedcba") == 68
    assert candidate(word = "zaqwsxcderfvgytuhjnmkiolp") == 156
