# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "zzzzyzyzyyzzyzz") == 3
    assert candidate(s = "abcba") == 5
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "abaacbcbb") == 5
    assert candidate(s = "aabbaa") == 4
    assert candidate(s = "aabbccddeeeedddccbaa") == 8
    assert candidate(s = "abababab") == 4
    assert candidate(s = "a") == 1
    assert candidate(s = "abacabadabacaba") == 7
    assert candidate(s = "abcabcabc") == 3
    assert candidate(s = "abcabcabcabc") == 6
    assert candidate(s = "aa") == 2
    assert candidate(s = "abcddcba") == 8
    assert candidate(s = "zzzzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzzzz") == 3
    assert candidate(s = "abcde") == 5
    assert candidate(s = "aabb") == 4
    assert candidate(s = "aabbccddeeeedddccba") == 7
    assert candidate(s = "abcdeedcba") == 10
    assert candidate(s = "zzzzzzzzzz") == 2
    assert candidate(s = "abcdefgfedcba") == 13
    assert candidate(s = "abcdabcdabcd") == 4
    assert candidate(s = "zzzyzzyyzzyyzzzzzyyzyzyzyz") == 4
    assert candidate(s = "abacabad") == 6
    assert candidate(s = "aabbaaabbbaaa") == 3
    assert candidate(s = "abcd") == 4
    assert candidate(s = "aabbccddeeff") == 12
    assert candidate(s = "aabbcc") == 6
    assert candidate(s = "mississippi") == 7
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 52
    assert candidate(s = "aabbccddeeffgghhiijj") == 20
    assert candidate(s = "aabbccddeeaabbccddeeff") == 12
    assert candidate(s = "aabbccdd") == 8
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 52
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 2
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnmnbvcxzlkjhgfdsapoiuytrewqqwertyuiopasdfghjklzxcvbnm") == 27
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzxyz") == 49
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzyxwvutsrqponmlkjihgfedcba") == 26
    assert candidate(s = "abababababababababababababababababababababababababababababababababababababababab") == 4
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba") == 51
    assert candidate(s = "xyzzyxzyzxzyzyzyzyz") == 3
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 4
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcba") == 26
    assert candidate(s = "aaabbbbccccddddeeeeefffffggggghhhhhiiiiijjjjjkkkkklllllmmmmmnnnnnooooo") == 18
    assert candidate(s = "aaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaab") == 3
    assert candidate(s = "aabbaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 52
