# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "ABCDBA") == 2
    assert candidate(s = "CDCDCD") == 0
    assert candidate(s = "ABABAB") == 0
    assert candidate(s = "ACBBD") == 5
    assert candidate(s = "ABFCACDB") == 2
    assert candidate(s = "AAAA") == 4
    assert candidate(s = "") == 0
    assert candidate(s = "BACD") == 2
    assert candidate(s = "ABCDABCD") == 0
    assert candidate(s = "ABACDBACDB") == 0
    assert candidate(s = "ABABABABABABABABAB") == 0
    assert candidate(s = "ACDBABCDACDB") == 0
    assert candidate(s = "ABCDBCDBCDCDBABCDB") == 4
    assert candidate(s = "FCABABCDABCDF") == 3
    assert candidate(s = "CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD") == 0
    assert candidate(s = "ABCABCABCABC") == 4
    assert candidate(s = "CDCDCDCDCDCDCD") == 0
    assert candidate(s = "ABABCDABABCD") == 0
    assert candidate(s = "ABCDABCDBABCDABCDB") == 2
    assert candidate(s = "CCCCCCCC") == 8
    assert candidate(s = "CDABCDAB") == 0
    assert candidate(s = "DDDDDDDD") == 8
    assert candidate(s = "CDCDCDCD") == 0
    assert candidate(s = "ACBDCDBDCB") == 8
    assert candidate(s = "ABABABAB") == 0
    assert candidate(s = "CDCDCDCDCDCDCDCD") == 0
    assert candidate(s = "AAABBBCCCDDD") == 0
    assert candidate(s = "CDCDCDCDABABABAB") == 0
    assert candidate(s = "ABABABABAB") == 0
    assert candidate(s = "ABABABCDCDABCDCD") == 0
    assert candidate(s = "ABCDABCDBACDBACDABCD") == 2
    assert candidate(s = "AABBCCDDBBAA") == 4
    assert candidate(s = "ABCDABCDAB") == 0
    assert candidate(s = "DCABDCABDCABDCAB") == 2
    assert candidate(s = "DCABDCABDCABDCABDCABDCABDCABDCAB") == 2
    assert candidate(s = "CDCDCDCDCDAB") == 0
    assert candidate(s = "DCBADCBAABCDDC") == 10
    assert candidate(s = "ABCDABCDCDABCDABCDCD") == 0
    assert candidate(s = "ABCDBACDBACD") == 2
    assert candidate(s = "DCBA") == 4
    assert candidate(s = "FCABFCABFCABFCABFCABFCABFCABFCABFCAB") == 18
    assert candidate(s = "DBABABCD") == 2
    assert candidate(s = "ABABABABABAB") == 0
    assert candidate(s = "BACDBACDBACDAB") == 2
    assert candidate(s = "AAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBB") == 0
    assert candidate(s = "ACDBCDABABCD") == 0
    assert candidate(s = "ACDBABABCDACDB") == 0
    assert candidate(s = "BACDBACD") == 2
    assert candidate(s = "ABCDBACDAB") == 2
    assert candidate(s = "ABCDBCDBCDAB") == 2
    assert candidate(s = "BACDBACDBACDBACDB") == 1
    assert candidate(s = "ABCDABCDCDABCD") == 0
    assert candidate(s = "ABCDABCDCD") == 0
    assert candidate(s = "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB") == 40
    assert candidate(s = "ABCDCDAB") == 0
    assert candidate(s = "ABABABABABCDABCD") == 0
    assert candidate(s = "ABCDABCDBABCDBAB") == 2
    assert candidate(s = "CDCDCDCDCD") == 0
    assert candidate(s = "ABABABABABABABABABCDCDCDCD") == 0
    assert candidate(s = "ABCDABCDBAB") == 1
    assert candidate(s = "CDCDCDABABCDABABCDABABCD") == 0
    assert candidate(s = "ABABCDABABCDABABCDABABCDAB") == 0
    assert candidate(s = "ACDBACDBACDBACDBACDB") == 0
    assert candidate(s = "CDABCDABCDABCD") == 0
    assert candidate(s = "ACDBABABABCDAB") == 0
    assert candidate(s = "DCABDCAB") == 2
    assert candidate(s = "ABABABABABABAB") == 0
    assert candidate(s = "ABCDCBAABCDBCDABCDCBAABCDBCD") == 4
    assert candidate(s = "ABCDABCDBABCDABCDBABCDABCDBABCDABCDB") == 4
    assert candidate(s = "ACDBACDBACDBACDBACDBACDBACDBACDBACDB") == 0
    assert candidate(s = "DBACBADC") == 8
    assert candidate(s = "ACDBACDBACDBACDB") == 0
    assert candidate(s = "BACDBACDBACDBACDBACD") == 2
    assert candidate(s = "AAAAAAAA") == 8
    assert candidate(s = "CDABCDABCDABCDABCDAB") == 0
    assert candidate(s = "CDABCDABCDABCDABCDABCDABCDABCDABCDAB") == 0
    assert candidate(s = "CDCDCDCDCDCD") == 0
    assert candidate(s = "ABACBCADCD") == 6
    assert candidate(s = "ABCDABCDBACDBACD") == 2
    assert candidate(s = "ABABCDABABCDAB") == 0
    assert candidate(s = "ABCDDCBA") == 4
    assert candidate(s = "ABCDABCDABCDABCDABCDABCDABCDABCD") == 0
    assert candidate(s = "BACDBACDBACDBACD") == 2
    assert candidate(s = "XYZ") == 3
    assert candidate(s = "ABABABABABABABABABAB") == 0
    assert candidate(s = "BBBBBBBBBBBBBBBB") == 16
    assert candidate(s = "CDCDCDABABCD") == 0
    assert candidate(s = "AAAAAAAAAAAAAAAA") == 16
    assert candidate(s = "BBBBBBBB") == 8
    assert candidate(s = "CDCDABAB") == 0
    assert candidate(s = "CDABCDABCDAB") == 0
    assert candidate(s = "ABCDABCDABCD") == 0
    assert candidate(s = "CDABCDABCD") == 0
    assert candidate(s = "ABCDABCDABCDBACD") == 2
    assert candidate(s = "ACBDCDBDCBDCB") == 11
    assert candidate(s = "ABABABABABCD") == 0
    assert candidate(s = "AAAAABBBBB") == 0
    assert candidate(s = "ABCDBCDABCDBCDABCDBCDABCDBCD") == 4
    assert candidate(s = "ABABABABABABABABABABABABABABABABABAB") == 0
    assert candidate(s = "BBCCCDDDAABB") == 2
    assert candidate(s = "ABCCBAABCCBA") == 8
    assert candidate(s = "ACBDABFCDC") == 6
    assert candidate(s = "ABCDABCDABCDAB") == 0
    assert candidate(s = "BBBBBAAAAA") == 10
    assert candidate(s = "FFFFFFFFFFFFFFFF") == 16
    assert candidate(s = "CABACDBABC") == 2
    assert candidate(s = "CDCDCDCDCDABABABAB") == 0
    assert candidate(s = "ABABDCDCCCDA") == 4
    assert candidate(s = "ACBDACBDACBD") == 12
    assert candidate(s = "AACBBCCDAD") == 8
    assert candidate(s = "ABCDCBAABCDBCD") == 2
    assert candidate(s = "ABCDABCDBACD") == 2
    assert candidate(s = "DCBADCBABC") == 8
    assert candidate(s = "BACDBACDBACDB") == 1
    assert candidate(s = "ABCDABCDBACDAB") == 2
    assert candidate(s = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA") == 40
    assert candidate(s = "FCABFCABFCABFCABFCAB") == 10
    assert candidate(s = "FCABFCABFCAB") == 6
    assert candidate(s = "BACDBACDBACDBACDBACDBACDBACDBACDBACDB") == 1
    assert candidate(s = "ABCDABCDBABD") == 2
    assert candidate(s = "ACBACDBCDB") == 4
    assert candidate(s = "ABACDABACDABACD") == 3
    assert candidate(s = "BACDBACDBACDBACDBACDBACD") == 2
    assert candidate(s = "ABABABABABABABABABABABABAB") == 0
    assert candidate(s = "BACDBACDBACD") == 2
    assert candidate(s = "CDCDCDCDCDCDCDCDCD") == 0
    assert candidate(s = "ABCDBCDBCDABCDBCDABCDBCDABCDBCD") == 5
    assert candidate(s = "ABCDABCDBABC") == 2
    assert candidate(s = "ABCDABCDBABCDABCDBABCDABCDBAB") == 3
    assert candidate(s = "ABCDABCDCDAB") == 0
    assert candidate(s = "ABCDEFGHABCD") == 4
    assert candidate(s = "AAAAAAAAAABBBBBBBBBB") == 0
    assert candidate(s = "BBBBBBBBBAAAAAAAAABBBBBBBBBBAAAAAAAAAA") == 20
    assert candidate(s = "AABABBCCDDBBCC") == 4
    assert candidate(s = "ABCDABCDABCDABCD") == 0
    assert candidate(s = "ABCDABCDABCDABCDABCDABCDABCDABCDABCDABCD") == 0
    assert candidate(s = "ACDBACDBACDB") == 0
    assert candidate(s = "BACDBACDBABCDABCD") == 1
    assert candidate(s = "DCABDCABDCABDCABDCABDCABDCABDCABDCABDCABDCAB") == 2
    assert candidate(s = "ABACADABAD") == 6
    assert candidate(s = "ABCD") == 0
    assert candidate(s = "BBBBBBBBBAAAAAAAAA") == 18
    assert candidate(s = "ABCDABCDABCDABCDABCD") == 0
    assert candidate(s = "ABABABABABCDABCDBACDBACD") == 2
    assert candidate(s = "DCDABABABABABABCD") == 1
    assert candidate(s = "ABABABABCDABCDBACDBACDABABABAB") == 2
    assert candidate(s = "CDCDCDCDCDCDCDCDCDCDCDCD") == 0
    assert candidate(s = "ACDBACDB") == 0
    assert candidate(s = "ABABCDABCD") == 0
    assert candidate(s = "AACBBCCCDD") == 6
    assert candidate(s = "ABABABABABABCD") == 0
    assert candidate(s = "AACCBBAADD") == 10
    assert candidate(s = "ABABCDABABCDABCD") == 0
