# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "XXXXXXXXXX") == 4
    assert candidate(s = "OOXOOX") == 2
    assert candidate(s = "OOXOOXOOXO") == 3
    assert candidate(s = "OOXXOOXXOO") == 2
    assert candidate(s = "XXOX") == 2
    assert candidate(s = "OXOXOXOXOX") == 3
    assert candidate(s = "XOOOXXOOOX") == 3
    assert candidate(s = "XXX") == 1
    assert candidate(s = "OOOO") == 0
    assert candidate(s = "XOOXOX") == 2
    assert candidate(s = "OXOXOX") == 2
    assert candidate(s = "OOOXXOOOXXOOO") == 2
    assert candidate(s = "XOXOXOXOXO") == 3
    assert candidate(s = "XXXXXX") == 2
    assert candidate(s = "XOOXOOXOOX") == 4
    assert candidate(s = "XXXXXXXXX") == 3
    assert candidate(s = "XOXOXO") == 2
    assert candidate(s = "OOXXOOX") == 2
    assert candidate(s = "OOXOXO") == 1
    assert candidate(s = "XOOOOXOOXOXXXX") == 4
    assert candidate(s = "XOOXOXOOXOXOXO") == 4
    assert candidate(s = "OOXOXOXXOXXOOXOX") == 4
    assert candidate(s = "XOXOXOXOXOXOXOXOXOXOXOXOXOXOXO") == 8
    assert candidate(s = "XOXOOXOXOOXOXOXOXOOXOXOXOOXOXOXOOXO") == 9
    assert candidate(s = "XOOXOXOOXOOXOOXOOXOOXOOXOOXOOX") == 10
    assert candidate(s = "XOXOXXOOXOXOXXXOXO") == 5
    assert candidate(s = "XOOXOXOOXOXOOXOXOOX") == 5
    assert candidate(s = "OOXOOXOOXOOXOO") == 4
    assert candidate(s = "XOXOXOXOXOXOXOXOXOXOXOXOXO") == 7
    assert candidate(s = "OXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOX") == 12
    assert candidate(s = "OXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOX") == 9
    assert candidate(s = "XOOOXOOOXOOOXOOOXOOO") == 5
    assert candidate(s = "XOOXOXOXOXOXOXOX") == 5
    assert candidate(s = "OOOOOOOOOOOOOOOOO") == 0
    assert candidate(s = "OOOOOOOOOOOOOOOOOOO") == 0
    assert candidate(s = "XXOOOOXXOOOOXXOOOOXXOOOOXXOOOOXXOOOOXXOOOOXX") == 8
    assert candidate(s = "OOXXOOXXOOXXXX") == 4
    assert candidate(s = "XOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXO") == 9
    assert candidate(s = "XOOXXOOXXOOXXOOXX") == 5
    assert candidate(s = "XOXOXOXOXOOOXOXO") == 4
    assert candidate(s = "XXXOXOXOXOXO") == 3
    assert candidate(s = "XXOOXOXOXOXOXX") == 4
    assert candidate(s = "OXXOXOXOXOXO") == 3
    assert candidate(s = "XXXXXXXXXXXXXXXXXXX") == 7
    assert candidate(s = "OOXOXOXOXOOO") == 2
    assert candidate(s = "OXOXOXOXOXOX") == 3
    assert candidate(s = "XXOOXOXOXOXOXXOXOXXOXOXXOXOXXOXOXX") == 10
    assert candidate(s = "XOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOX") == 14
    assert candidate(s = "XOXOXOXOXOXO") == 3
    assert candidate(s = "XOOOXXXXOOOXXXXOOO") == 5
    assert candidate(s = "XXOXOXOXOXOXOXOXOXOXOXOXOX") == 7
    assert candidate(s = "XXOOXXOOXXOOXXOOXXOOX") == 6
    assert candidate(s = "XXXXXXXXXXXXXXXX") == 6
    assert candidate(s = "XXXOXOXOXOXOXOXO") == 4
    assert candidate(s = "XOXXXXXXXXXOXOXOXOXOXOXOXO") == 8
    assert candidate(s = "XOXOXXXXXXXXXOXXXXXXXXXOXXXXXXXXXOXXXXXXXXXO") == 13
    assert candidate(s = "OOXOXOXOXOXOXOXO") == 4
    assert candidate(s = "XOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXO") == 12
    assert candidate(s = "OXOXOXOXOXOXOXOXOXOXOX") == 6
    assert candidate(s = "OOXXOOXXOOXXOOXXOOXXOO") == 5
    assert candidate(s = "OXOXOXOXOXOXOXOXOXOXOXOX") == 6
    assert candidate(s = "XXXXXXXXXOOOOOOOOOXXXXXXXXX") == 6
    assert candidate(s = "XXOOXXOOXXOOXXOOXX") == 5
    assert candidate(s = "XOOXOOXOOXOOXOOX") == 6
    assert candidate(s = "OOXOXOXOXOXOXOXOXOXOXOXOXOXOXOOO") == 7
    assert candidate(s = "OOXOOXOOXOOXOOXO") == 5
    assert candidate(s = "XXXXXXXXXXXXX") == 5
    assert candidate(s = "XXOOXOXOXOXOXO") == 4
    assert candidate(s = "XXXOOOOXOXOOXOXO") == 3
    assert candidate(s = "XOXOXOXOXOXOXOXOXOXOXOXO") == 6
    assert candidate(s = "XXOOXXOOXXOOXX") == 4
    assert candidate(s = "XOOXOOXOOXOXOX") == 5
    assert candidate(s = "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO") == 0
    assert candidate(s = "XXOOXOXOXOXOXOXOXO") == 5
    assert candidate(s = "XOOXOOXOOXOOXOOXOOX") == 7
    assert candidate(s = "OOOXXXOOOXXXOOO") == 2
    assert candidate(s = "XXXOXOXOXXXO") == 3
    assert candidate(s = "XOXOXXOOXOXO") == 3
    assert candidate(s = "OXXXXOOOXXXXOOOXXX") == 5
    assert candidate(s = "OOOXOXOXOXOXOXOOOO") == 3
    assert candidate(s = "XOOXOOXOOXOOXOOXOOXOOX") == 8
    assert candidate(s = "OOXOOXOOXOOXOOXOOXOO") == 6
    assert candidate(s = "OOXOOXOOXOOXOOX") == 5
    assert candidate(s = "XXXXXXXXXXXXXXXXXXXXXXXX") == 8
    assert candidate(s = "OOXOXOXOXOXOXOOO") == 3
    assert candidate(s = "XOXXOXXOXXOXXOXX") == 6
    assert candidate(s = "XXOOXOXOXOXOXOXOXOXX") == 6
    assert candidate(s = "XOOXOOXOOXOOXOOXOOXOOXOOXOOXOOXOOXOOXO") == 13
    assert candidate(s = "XOXOXOXOXOXOXO") == 4
    assert candidate(s = "OXOXOXOXOXOXOX") == 4
    assert candidate(s = "XXOXOXOXOXOXOXOXOXOX") == 6
    assert candidate(s = "XXXXOXXXXOXXXXO") == 5
    assert candidate(s = "XOXOXOXOXOXOXOXOXOXOXOXOXOXO") == 7
    assert candidate(s = "XOOXOXOOXOXOOXOXOOXOXOOX") == 6
    assert candidate(s = "OOOOXXOOXXOOXX") == 3
    assert candidate(s = "XXOOXXOOXXOOXXOOXXOOXXOOXXOOX") == 8
    assert candidate(s = "XXXXOOXXXXOOXXXXOO") == 6
    assert candidate(s = "XXOXXOXXOXXOXX") == 5
    assert candidate(s = "OOOOOOOOOOOOO") == 0
    assert candidate(s = "OOXXXXXXOOXXXXXXOOXXXXXX") == 6
    assert candidate(s = "XOXOXXXOXOXOXXX") == 4
    assert candidate(s = "XOXOXOXOXOXOXOXOXO") == 5
    assert candidate(s = "XOXOXOOXOXOX") == 4
    assert candidate(s = "XXOOXXOOXXOOXXOOXXOO") == 5
    assert candidate(s = "XXXXXXXXXXXXXXXXXX") == 6
    assert candidate(s = "XXXXXXXXXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXO") == 13
    assert candidate(s = "XXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOX") == 9
    assert candidate(s = "XXOXOXOXOXOXOXOX") == 5
    assert candidate(s = "XOOXOOXOOXOOXOOXOOXOOXOOX") == 9
    assert candidate(s = "XOOOXOOOXOOOXOOO") == 4
    assert candidate(s = "OOXXOOXXOOXXOO") == 3
    assert candidate(s = "XOXOXOXOXOXOX") == 4
    assert candidate(s = "XOXOXOXOXOXOXOXOXOXO") == 5
    assert candidate(s = "XXOXOXOXOXOX") == 4
    assert candidate(s = "OOXOXOXOXO") == 2
    assert candidate(s = "XOOOXXOOOOXXOOOXXOOO") == 4
    assert candidate(s = "OOXOOXOOXOOXOOXOOXOOXOOX") == 8
    assert candidate(s = "XXOXOXOXOXOXOX") == 4
    assert candidate(s = "OXOXOXOXOXOXOXOXOX") == 5
    assert candidate(s = "OXOOXOOXOOXOOXOOXOOXOOX") == 8
    assert candidate(s = "OOXOOXOOXOOXOOXOOXOOXOOXOOXOO") == 9
    assert candidate(s = "OXXOXOXXOXOXXOXO") == 5
    assert candidate(s = "XXXXXXXXOXOXO") == 4
    assert candidate(s = "XXXXXXXXOOOXXXXX") == 5
    assert candidate(s = "OOXXOOXXOOXXOOXXOOXXOOXXOO") == 6
    assert candidate(s = "OOXOOXOOXOOXOOXOOXOOXOOXOOXOOXOOXOOXOO") == 12
    assert candidate(s = "XOOXOXXOXOXXOX") == 5
    assert candidate(s = "OOOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOO") == 9
    assert candidate(s = "OXOXOXOXOXOXOXOXOXO") == 5
    assert candidate(s = "OXOXOXOXOXOXO") == 3
    assert candidate(s = "XXXXOXXXXOXXXXOXXXXOXXXXOXXXXOXXXXO") == 11
    assert candidate(s = "XOXOXXXXXXXXOXXXXXXXXX") == 7
    assert candidate(s = "XOOXOOXOOXOOXOOXOOXOOXOOXOOXOOXOOX") == 12
    assert candidate(s = "XOOOXXOOOXXOOOXXOOO") == 4
    assert candidate(s = "OOOXOXOXOXOXOXOXOXOXOXOOOO") == 5
    assert candidate(s = "XOXXOXOXXOXOXXOXOXXOXXO") == 7
    assert candidate(s = "OOXOXOXOXOXOXOXOXOXOXOXOXO") == 6
    assert candidate(s = "OOOOOOOOOOOOOO") == 0
    assert candidate(s = "XXOXXOXXOXXO") == 4
    assert candidate(s = "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO") == 0
    assert candidate(s = "OXOXOXOXOXOXOXOX") == 4
    assert candidate(s = "XXXXXXXXXXXXXXXXXOOOOOOOOOOOO") == 6
    assert candidate(s = "OOOOOOOOOOOOOOOOOO") == 0
    assert candidate(s = "XXXXXXXXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOX") == 11
    assert candidate(s = "XXXOOXOXOOXOXX") == 4
    assert candidate(s = "XOXOXOXOXOXOXOXO") == 4
    assert candidate(s = "XOOOOXOOOOXOOOOXOOOO") == 4
    assert candidate(s = "XOOXXOOXXOOXXOOX") == 5
    assert candidate(s = "OOOXOXOXOXOXOOOO") == 3
    assert candidate(s = "OOXOOXOOXOOXOOXOOXOOXOOXOOXOOXOOXOOX") == 12
    assert candidate(s = "XOOOOXOOOXOOO") == 3
    assert candidate(s = "XXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXX") == 11
    assert candidate(s = "OOXOXOXOXOXOXOXOXO") == 4
    assert candidate(s = "XOXOXOOXOXOXOO") == 4
    assert candidate(s = "XOOOOXOOOOXOOOOXOOOOXOOOO") == 5
    assert candidate(s = "XOOXOXOXOXOX") == 4
    assert candidate(s = "OOXOOOXOOOXOOOXOOOXOOOXOOOXOOOXOOOXOOOXOOO") == 10
    assert candidate(s = "XXOOXXOOXXOO") == 3
    assert candidate(s = "XXXXXXXXOOOOXXXXXXXX") == 6
    assert candidate(s = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") == 14
    assert candidate(s = "XXXXXXXXXXXXXXXXX") == 6
    assert candidate(s = "XOXOOXOXOOXOXOXO") == 4
    assert candidate(s = "OXOOXOOOXOXOOXOO") == 4
    assert candidate(s = "XXOXOXXOXOXOXXOX") == 5
    assert candidate(s = "OOOOOOOOOOOOOOOOOOOOOOOOOOOO") == 0
    assert candidate(s = "XXXXXXXXXXXXXX") == 5
