# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(word = "ghijkl") == 6
    assert candidate(word = "npqrstvwxy") == 12
    assert candidate(word = "abcdefghi") == 10
    assert candidate(word = "vwxyz") == 5
    assert candidate(word = "abcdefghijklmnopq") == 27
    assert candidate(word = "abcdefghijklmnopqrs") == 33
    assert candidate(word = "abcdefghijklmnopqrstu") == 39
    assert candidate(word = "pqrstu") == 6
    assert candidate(word = "abcdefghijkl") == 16
    assert candidate(word = "abcdefghijk") == 14
    assert candidate(word = "pqrstuvw") == 8
    assert candidate(word = "defghi") == 6
    assert candidate(word = "abcdefghijklm") == 18
    assert candidate(word = "efghijkl") == 8
    assert candidate(word = "abcdef") == 6
    assert candidate(word = "abcdefghijklmn") == 20
    assert candidate(word = "qrstuvw") == 7
    assert candidate(word = "uvwxyza") == 7
    assert candidate(word = "bcdefg") == 6
    assert candidate(word = "tuvwxy") == 6
    assert candidate(word = "qrstuv") == 6
    assert candidate(word = "tuvwxyz") == 7
    assert candidate(word = "wxyzabc") == 7
    assert candidate(word = "abcdefghij") == 12
    assert candidate(word = "nopqrs") == 6
    assert candidate(word = "nopqrst") == 7
    assert candidate(word = "xycdefghij") == 12
    assert candidate(word = "hijklmno") == 8
    assert candidate(word = "mnopqrstu") == 10
    assert candidate(word = "vwxyza") == 6
    assert candidate(word = "abcdefghijklmnopqr") == 30
    assert candidate(word = "abcdefghijkmnopqrstuvwxyzabc") == 64
    assert candidate(word = "rstvwxy") == 7
    assert candidate(word = "zabcdef") == 7
    assert candidate(word = "abcdefghijklmnop") == 24
    assert candidate(word = "klmnopq") == 7
    assert candidate(word = "stuvwx") == 6
    assert candidate(word = "mnop") == 4
    assert candidate(word = "xyz") == 3
    assert candidate(word = "qrstuvwx") == 8
    assert candidate(word = "abcdefghijlkmnopqrstuvwxyz") == 56
    assert candidate(word = "yz") == 2
    assert candidate(word = "lmnopqrs") == 8
    assert candidate(word = "ab") == 2
    assert candidate(word = "abcde") == 5
    assert candidate(word = "abcd") == 4
    assert candidate(word = "abcdefg") == 7
    assert candidate(word = "a") == 1
    assert candidate(word = "ijklmn") == 6
    assert candidate(word = "klmnop") == 6
    assert candidate(word = "mnopqr") == 6
    assert candidate(word = "ghijklm") == 7
    assert candidate(word = "ijklmnop") == 8
    assert candidate(word = "zabcde") == 6
    assert candidate(word = "abcdefghijklmnopqrst") == 36
    assert candidate(word = "abc") == 3
    assert candidate(word = "opqrstuv") == 8
    assert candidate(word = "hijklm") == 6
    assert candidate(word = "abcdefghijklmnopqrstuv") == 42
    assert candidate(word = "abcdefghijkmnopqrstuvwx") == 45
    assert candidate(word = "defghij") == 7
    assert candidate(word = "efghij") == 6
    assert candidate(word = "abcdefghijklmnopqrstuvwxyz") == 56
    assert candidate(word = "mnopqrstuvwxyz") == 20
    assert candidate(word = "yzabcdef") == 8
    assert candidate(word = "defghijkl") == 10
    assert candidate(word = "jklmno") == 6
    assert candidate(word = "abcdefgh") == 8
    assert candidate(word = "bcdfghjkl") == 10
    assert candidate(word = "bcdefghijklmnopqrstuvwxyzafe") == 64
    assert candidate(word = "abcdefghijklmnopqrstuvwx") == 48
    assert candidate(word = "nopqrstuvwxyz") == 18
    assert candidate(word = "stuvwxyzabcdefghij") == 30
    assert candidate(word = "wxyzabcdefghijklmnopqrstuv") == 56
    assert candidate(word = "xyzmnopqrstuabc") == 22
    assert candidate(word = "stuvwxyzabcdefghijkl") == 36
    assert candidate(word = "qrstuvwxyzabcdefghij") == 36
    assert candidate(word = "nopqrstuvwxyzabcdefghijk") == 48
    assert candidate(word = "lmnopqrstuvwxyzabc") == 30
    assert candidate(word = "opqrstuvwxyzabcde") == 27
    assert candidate(word = "uvwxyzabcdefghijklmnopqrstuvwxy") == 76
    assert candidate(word = "lmnopqrstuvwxyzabcdefghijk") == 56
    assert candidate(word = "zxcvbnmlkjhgfedcba") == 30
    assert candidate(word = "xyzabcdefghijklmnop") == 33
    assert candidate(word = "qrstuvwxyzzzzz") == 20
    assert candidate(word = "abcdefghijlmnopqrstuvwxyz") == 52
    assert candidate(word = "jklmnopqrstuvwx") == 22
    assert candidate(word = "klmnopqrstuvwxyzabcdefghij") == 56
    assert candidate(word = "zxcvbnmlkjhgfdsapoiuytrewq") == 56
    assert candidate(word = "nopqrstuvwxyzabcdefghijklmno") == 64
    assert candidate(word = "opqrstuvwxyzabcdefghijklmnop") == 64
    assert candidate(word = "nopqrstuvwxyzabcdefghijklm") == 56
    assert candidate(word = "pqrstuvwxy") == 12
    assert candidate(word = "efghijklmnop") == 16
    assert candidate(word = "yzabcdefghijklmnopqrstuvwx") == 56
    assert candidate(word = "tuvxyzabcdefghijklmnopqrs") == 52
    assert candidate(word = "mnopqrstuvwxzyabc") == 27
    assert candidate(word = "lmnopqrstu") == 12
    assert candidate(word = "bdfhjlnprtvxz") == 18
    assert candidate(word = "mnopqrstuvwxyzabc") == 27
    assert candidate(word = "mnopqrst") == 8
    assert candidate(word = "mnopqrstuvwxzy") == 20
    assert candidate(word = "abcdpqrs") == 8
    assert candidate(word = "abcdefghijklmnopqrstuvwxzy") == 56
    assert candidate(word = "aeiouaeiou") == 12
    assert candidate(word = "xyzabcdefghijklmnopqrstuvwx") == 60
    assert candidate(word = "abcdefgxyz") == 12
    assert candidate(word = "defghijklmnopqrstuvwxyzabc") == 56
    assert candidate(word = "klmnopqrstuabcdefghij") == 39
    assert candidate(word = "abcdefghijkmnop") == 22
    assert candidate(word = "abcdefgxyzijklmnop") == 30
    assert candidate(word = "stuvxyzabcdefghijklmnopqr") == 52
    assert candidate(word = "ghijklmnopqrstuvwxyzabcde") == 52
    assert candidate(word = "zyxcvbnm") == 8
    assert candidate(word = "nopqrstuvwxyzabcdefghijkl") == 52
    assert candidate(word = "abcdefghjklmno") == 20
    assert candidate(word = "hijklmnopqrstuvwxyz") == 33
    assert candidate(word = "vwxyzabcd") == 10
    assert candidate(word = "pqrstuvwlmnoefghij") == 30
    assert candidate(word = "yzabcdefghijklmnopqrstuvwxy") == 60
    assert candidate(word = "zabcdefghijklmnopq") == 30
    assert candidate(word = "defghijklmnopqrstuvwxyza") == 48
    assert candidate(word = "opqrstuvwxyzabcdefghijklmn") == 56
    assert candidate(word = "mnopqrstuvwxyzabcdefghijxyz") == 60
    assert candidate(word = "mnopqrstuvwxyzaefghijkl") == 45
    assert candidate(word = "wxyzabcdefghijklmnopqrstuvwxy") == 68
    assert candidate(word = "abcdefghijmnopqrstuvwxyz") == 48
    assert candidate(word = "bcdefghijklmnopqrstuvwxyza") == 56
    assert candidate(word = "xyzabc") == 6
    assert candidate(word = "poiuytrewq") == 12
    assert candidate(word = "bcdfghjklmnpqrstvwxyz") == 39
    assert candidate(word = "qwertyuiop") == 12
    assert candidate(word = "abcdefhijklmno") == 20
    assert candidate(word = "qrstuvwxyz") == 12
    assert candidate(word = "uvwxyzaeiou") == 14
    assert candidate(word = "abcdefghilmnopqrstuvwxyz") == 48
    assert candidate(word = "abcdefghijxyzklmnopqr") == 39
    assert candidate(word = "xyzdefghijklmnopqrstuvw") == 45
    assert candidate(word = "abcdefghijkmnopqrst") == 33
    assert candidate(word = "wxyzabcdefghijklmnopqrst") == 48
    assert candidate(word = "tuvwxyzabcdefghijklmnopqrs") == 56
    assert candidate(word = "qrstuvwxyzabcdefghijklmnop") == 56
    assert candidate(word = "ghijklmnopqrstuvwxyzab") == 42
    assert candidate(word = "nopqrstuvwxyzabc") == 24
    assert candidate(word = "abcdefghiklmnopqrstuvwxyz") == 52
    assert candidate(word = "yzabcd") == 6
    assert candidate(word = "ghijklmnopqrstu") == 22
    assert candidate(word = "vwxyzabcdefghijklmnopqrstu") == 56
    assert candidate(word = "vwxyzabcdefghijklmnopq") == 42
    assert candidate(word = "zabcdefghijklmnop") == 27
    assert candidate(word = "ijklmnopqrstuvwxyzabcdefgh") == 56
    assert candidate(word = "lkjihgfedcba") == 16
    assert candidate(word = "klmno") == 5
    assert candidate(word = "pqrstuvwxyzabcdefghijklmno") == 56
    assert candidate(word = "stuvwxyzabcdefghijklmnopqr") == 56
    assert candidate(word = "abcdefg hijklmnop qrstuv wxyz") == 68
    assert candidate(word = "lmnopqrstuvwxyz") == 22
    assert candidate(word = "rstuvxyzabcdefghijklmnopqrst") == 64
    assert candidate(word = "qrstuvwxyza") == 14
    assert candidate(word = "abcdefghilmnopqr") == 24
    assert candidate(word = "yzabcdefghijklmnopqrstuvw") == 52
    assert candidate(word = "xyzabcdefghijklmnopq") == 36
    assert candidate(word = "bcdefghijklmnopqrstuvwx") == 45
    assert candidate(word = "abcdefghijklmnopqrstuvmnop") == 56
    assert candidate(word = "zxcvbnm") == 7
    assert candidate(word = "xyzabcdefghijklmnopqrstuvw") == 56
    assert candidate(word = "qrstuvwxyzabcdefg") == 27
    assert candidate(word = "abcdefghijkmnopqrstuvwxy") == 48
    assert candidate(word = "abcdefghilmnopqrstuvwxyzz") == 52
    assert candidate(word = "defghijklmnopqrstu") == 30
    assert candidate(word = "vwxyzabcdefghijklmno") == 36
    assert candidate(word = "vwxyzabcdefghijklmnopqrstuvwx") == 68
    assert candidate(word = "zxcvbnmasdfghjklqwertyuiop") == 56
    assert candidate(word = "mnopqrstuv") == 12
    assert candidate(word = "zabcdefghijklmnopqrstuvwxy") == 56
    assert candidate(word = "defghijklmnopqrstuabcdefgh") == 56
    assert candidate(word = "asdfghjkl") == 10
    assert candidate(word = "abcdefghijklmno") == 22
    assert candidate(word = "ghijklmnopqrstuvwxyzabcdef") == 56
    assert candidate(word = "yzabcdefghijklmnop") == 30
    assert candidate(word = "qrstuvwxyzabcdefghijklmnoprstuvw") == 80
    assert candidate(word = "rstuvwxyzabcdefghijklmnopq") == 56
    assert candidate(word = "zabcdefghijklmnopqrstuvwx") == 52
    assert candidate(word = "nopqrstuvwxyzabcd") == 27
    assert candidate(word = "bcdefghijkl") == 14
    assert candidate(word = "nopqrstuvwxyzabcde") == 30
    assert candidate(word = "abcdefhijklmnopqrstuvwxyz") == 52
    assert candidate(word = "abcdefghijkmnopqrstuv") == 39
    assert candidate(word = "tuvwx") == 5
    assert candidate(word = "pqrstuvwxyzabcdef") == 27
    assert candidate(word = "jklmnopqrst") == 14
    assert candidate(word = "bcdefghijklmnopqrstvwxyz") == 48
    assert candidate(word = "lkjhgfdsa") == 10
    assert candidate(word = "pqrstuvwxyzabc") == 20
    assert candidate(word = "jklmnopqr") == 10
    assert candidate(word = "uvwxyzabcdefghijklmnopqrst") == 56
    assert candidate(word = "qrstuvwlmnop") == 16
    assert candidate(word = "acdegikmoqsuwy") == 20
    assert candidate(word = "pqrstuvwxyza") == 16
    assert candidate(word = "qrstuabcdefghijk") == 24
    assert candidate(word = "mnopqrstuvwx") == 16
    assert candidate(word = "hgfedcba") == 8
