# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abacabadabacaba",t = "abcadbabacabaab") == 1
    assert candidate(s = "transform",t = "formartin") == 1
    assert candidate(s = "hello",t = "billion") == 4
    assert candidate(s = "aabbcc",t = "ccbbaa") == 0
    assert candidate(s = "minimum",t = "numinum") == 2
    assert candidate(s = "hello",t = "bello") == 1
    assert candidate(s = "leetcode",t = "practice") == 5
    assert candidate(s = "aaabbb",t = "bbbaaa") == 0
    assert candidate(s = "transform",t = "formtrans") == 0
    assert candidate(s = "anagram",t = "mangaar") == 0
    assert candidate(s = "abcd",t = "dcba") == 0
    assert candidate(s = "transform",t = "formant") == 0
    assert candidate(s = "bab",t = "aba") == 1
    assert candidate(s = "aaa",t = "bbb") == 3
    assert candidate(s = "abc",t = "def") == 3
    assert candidate(s = "abcde",t = "edcba") == 0
    assert candidate(s = "xyz",t = "zyx") == 0
    assert candidate(s = "antidisestablishmentarianism",t = "staimnariesmedtahilbesdisantii") == 3
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzyyxwwvvuuttrrssqqppoonnmmllkkjjiihhggffeeeeddccbbaa") == 2
    assert candidate(s = "optimization",t = "inipotizaton") == 1
    assert candidate(s = "pneumonoultramicroscopicsilicovolcanoconiosis",t = "sinsivocnoclaocivlospercimicroscopoultraomneupnc") == 5
    assert candidate(s = "thisisaverylongstringthatwearetesting",t = "testingaverylongstringthatwesarethis") == 0
    assert candidate(s = "pythonprogramming",t = "gnimmargorpnohtyp") == 0
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzyyxwwvvuuttrrssqqppoonnmmllkkjjiihhggeeffddccbbaa") == 0
    assert candidate(s = "floccinaucinihilipilification",t = "nicihilopilicifinaucinnilociflloa") == 5
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba",t = "abcdefghijklmnopqrstuvwzyx") == 0
    assert candidate(s = "mississippi",t = "ppissimissim") == 1
    assert candidate(s = "aquickbrownfoxjumpsoverthelazydog",t = "aquickbrownfoxjumpsoverthelazydog") == 0
    assert candidate(s = "aaaaabbbbccccddddd",t = "dddddaaaaabbbcccc") == 0
    assert candidate(s = "bbaacc",t = "aabacc") == 1
    assert candidate(s = "aabbccddeeff",t = "fedcbafedcba") == 0
    assert candidate(s = "xylophone",t = "poloxynhe") == 0
    assert candidate(s = "almostthere",t = "lmostahere") == 0
    assert candidate(s = "abcdabcdabcd",t = "ddddccccbbbaaa") == 2
    assert candidate(s = "strength",t = "grenstht") == 0
    assert candidate(s = "pythonprogramming",t = "prognimmargyphnot") == 0
    assert candidate(s = "algorithms",t = "logarithms") == 0
    assert candidate(s = "pythonprogramming",t = "programmingpython") == 0
    assert candidate(s = "supercalifragilisticexpialidocious",t = "pseudopseudohypoparathyroidism") == 11
    assert candidate(s = "characterization",t = "carricahztinoe") == 0
    assert candidate(s = "thequickbrownfoxjumpsoverthelazydog",t = "doglazythequickbrownfoxjumpsoverthelazy") == 4
    assert candidate(s = "longestword",t = "wordlongset") == 0
    assert candidate(s = "photosynthesis",t = "synthesphotosis") == 1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzyyxxwwvvuuttrrssqqppoonnmmllkkjjiihhggffeeddccbbaa") == 0
    assert candidate(s = "supercalifragilisticexpialidocious",t = "ecilafragisticexpialidocuosspr") == 0
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzyyxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeeeddccbbaa") == 2
    assert candidate(s = "onomatopoeia",t = "pneumonoultramicroscopicsilicovolcanoconiosis") == 33
    assert candidate(s = "mississippi",t = "ppissimisss") == 1
    assert candidate(s = "mississippi",t = "pississippi") == 1
    assert candidate(s = "abcdefghij",t = "jihgfedcba") == 0
    assert candidate(s = "abracadabra",t = "arabracadab") == 0
    assert candidate(s = "permutations",t = "interpromust") == 1
    assert candidate(s = "aabbcceeddffee",t = "eeddffccbbbaaa") == 2
    assert candidate(s = "programmingisfun",t = "funprogrammingis") == 0
    assert candidate(s = "abracadabra",t = "occipital") == 7
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzyyxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccbbaa") == 0
    assert candidate(s = "aabbccddeeff",t = "zzzzyyxxwwvvuutt") == 16
    assert candidate(s = "elephant",t = "tehlanpe") == 0
    assert candidate(s = "elephant",t = "talehpen") == 0
    assert candidate(s = "permutations",t = "pertumations") == 0
    assert candidate(s = "synchronized",t = "chronizedsyn") == 0
    assert candidate(s = "elevenletters",t = "twelvethletters") == 4
    assert candidate(s = "thisisaverylongstring",t = "stringlongaverythisis") == 0
    assert candidate(s = "interstellar",t = "stellarestri") == 1
    assert candidate(s = "mississippi",t = "pisissmipis") == 0
    assert candidate(s = "supercalifragilisticexpialidocious",t = "ciousiliexpalodicisgratefulsuper") == 2
    assert candidate(s = "xylophone",t = "polyphonex") == 1
    assert candidate(s = "elephant",t = "telephone") == 2
    assert candidate(s = "mississippi",t = "psissimippi") == 1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "abcdefghijklmnopqrstuvwxyzzzyxwvutsrqponmlkjihgfedcba") == 1
    assert candidate(s = "mississippi",t = "pissimissi") == 0
    assert candidate(s = "amazingrace",t = "raceingazam") == 0
    assert candidate(s = "mississippi",t = "pississimissm") == 3
    assert candidate(s = "algorithm",t = "logarithmxx") == 2
    assert candidate(s = "reducibility",t = "reducibility") == 0
    assert candidate(s = "recharacterization",t = "characterizationre") == 0
    assert candidate(s = "programming",t = "gimmnoprram") == 1
    assert candidate(s = "frequencydistribution",t = "charactercount") == 5
    assert candidate(s = "thecommunistmanifesto",t = "theCommunistManifesto") == 2
    assert candidate(s = "characterization",t = "intercharacterization") == 5
    assert candidate(s = "aaaaabbbbcccccdddddeeeee",t = "eeeeeaaaaabbbbbcccccddddd") == 1
    assert candidate(s = "xylophone",t = "polyphonicx") == 3
    assert candidate(s = "thisisaverylongstringwithvariouscharacters",t = "thisisanotherlongstringwithdifferentcharacters") == 10
    assert candidate(s = "supercalifragilisticexpialidocious",t = "ecilapersixfulicadogstcilxpiaiodisu") == 2
    assert candidate(s = "characterization",t = "charizmatation") == 1
    assert candidate(s = "programming",t = "remmprogain") == 1
    assert candidate(s = "supercalifragilisticexpialidocious",t = "pronunciationdictionary") == 7
    assert candidate(s = "multimedia",t = "meediamult") == 1
    assert candidate(s = "xylophone",t = "phonexylo") == 0
    assert candidate(s = "mississippi",t = "ssissippiim") == 0
    assert candidate(s = "development",t = "elopmentd") == 0
    assert candidate(s = "interviewquestion",t = "questioverntein") == 0
    assert candidate(s = "anagramanagram",t = "mangaarmangaar") == 0
    assert candidate(s = "congratulations",t = "congratulations") == 0
    assert candidate(s = "programming",t = "pgmromanig") == 0
    assert candidate(s = "thequickbrownfox",t = "quickbrownfoxt") == 0
    assert candidate(s = "algorithm",t = "logarithm") == 0
    assert candidate(s = "racecar",t = "carrace") == 0
    assert candidate(s = "congratulations",t = "gratulationscon") == 0
    assert candidate(s = "optimization",t = "tionsimipazy") == 2
    assert candidate(s = "rhythm",t = "myrthh") == 0
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnm",t = "mnbvcxzlkjhgfdsapoiuytrewq") == 0
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",t = "zyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcba") == 0
    assert candidate(s = "aabbccddeeff",t = "ffeeddccbbaa") == 0
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "zyxwvutsrqponmlkjihgfedcba") == 0
    assert candidate(s = "unitedstates",t = "statedinutes") == 0
    assert candidate(s = "supercalifragilisticexpialidocious",t = "expialidocioussupercalifragilistic") == 0
    assert candidate(s = "unanimous",t = "manusiousun") == 2
    assert candidate(s = "abacabadabacabadabacabad",t = "bacdabcdabcdabcdabcdabcd") == 6
    assert candidate(s = "characterization",t = "recharacterization") == 2
    assert candidate(s = "abacaxi",t = "xicabaa") == 0
    assert candidate(s = "programming",t = "gnimmargorp") == 0
    assert candidate(s = "mississippi",t = "ppiimississ") == 0
