# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(hamsters = "H") == -1
    assert candidate(hamsters = "H.H.H.H.H.H") == 3
    assert candidate(hamsters = "HH.H.H.H.H.H.H.H.H.H.H.H.H.H") == -1
    assert candidate(hamsters = "H.H.H.H.H.H.H.H.H.H") == 5
    assert candidate(hamsters = ".....") == 0
    assert candidate(hamsters = ".") == 0
    assert candidate(hamsters = "H..H") == 2
    assert candidate(hamsters = "H.H") == 1
    assert candidate(hamsters = "H....H") == 2
    assert candidate(hamsters = "H.H.H.H.H") == 3
    assert candidate(hamsters = "HHHH") == -1
    assert candidate(hamsters = "H.H.H.H.H.H.H") == 4
    assert candidate(hamsters = "HH") == -1
    assert candidate(hamsters = "H.H.HH") == -1
    assert candidate(hamsters = ".HHH.") == -1
    assert candidate(hamsters = "HH.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H") == -1
    assert candidate(hamsters = "HH.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H") == -1
    assert candidate(hamsters = "H.H.H.H.H.H.H.H.H.H.H.H.H.H.H") == 8
    assert candidate(hamsters = "HH.HH.HH") == -1
    assert candidate(hamsters = "H.H.H") == 2
    assert candidate(hamsters = "HH.H.H.H.H") == -1
    assert candidate(hamsters = "H.H.H.H") == 2
    assert candidate(hamsters = "HH.HH") == -1
    assert candidate(hamsters = "HH.H.H.H.H.H.H.H.H.H.H") == -1
    assert candidate(hamsters = "HH.H.H.H.H.H.H.H.H.H.H.H") == -1
    assert candidate(hamsters = ".H.H.") == 1
    assert candidate(hamsters = "H.H.H.H.H.H.H.H") == 4
    assert candidate(hamsters = "H.HH") == -1
    assert candidate(hamsters = "H.H.H.H.H.H.H.H.H.H.H.H.H") == 7
    assert candidate(hamsters = "HHHHHH") == -1
    assert candidate(hamsters = "HH.H.H") == -1
    assert candidate(hamsters = "HH.H") == -1
    assert candidate(hamsters = "H.H.H.H.H.H.H.H.H") == 5
    assert candidate(hamsters = "HH.H.H.H.H.H.H") == -1
    assert candidate(hamsters = "H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H") == 10
    assert candidate(hamsters = "HH.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H") == -1
    assert candidate(hamsters = "HH.H.HH") == -1
    assert candidate(hamsters = "......") == 0
    assert candidate(hamsters = "H.H.H.H.H.H.H.H.H.H.H") == 6
    assert candidate(hamsters = "...") == 0
    assert candidate(hamsters = "H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H") == 9
    assert candidate(hamsters = "H.H.HH.H.H") == 4
    assert candidate(hamsters = "H.....H") == 2
    assert candidate(hamsters = "H.H.H.H.H.H.H") == 4
    assert candidate(hamsters = "H.....H") == 2
    assert candidate(hamsters = ".......") == 0
    assert candidate(hamsters = "HH.HHHHH.HH") == -1
    assert candidate(hamsters = ".H.H.") == 1
    assert candidate(hamsters = "H.H.H.H.HH") == -1
    assert candidate(hamsters = "........") == 0
    assert candidate(hamsters = "H.H.H.H.H.H.H.H.H") == 5
    assert candidate(hamsters = "..H.H..") == 1
    assert candidate(hamsters = "H.H.H.H.H") == 3
    assert candidate(hamsters = "HH.H.H.HH") == -1
    assert candidate(hamsters = "HH") == -1
    assert candidate(hamsters = "H.HH.H") == 2
    assert candidate(hamsters = "HH.HH.HH.HH.HH.HH.HH.HH") == -1
    assert candidate(hamsters = "...") == 0
    assert candidate(hamsters = "H.") == 1
    assert candidate(hamsters = "H.H..H.H") == 2
    assert candidate(hamsters = "H.......H") == 2
    assert candidate(hamsters = "..H..H..") == 2
    assert candidate(hamsters = "HHHHH") == -1
    assert candidate(hamsters = "HH.HH") == -1
    assert candidate(hamsters = "HH.H.H.H.HH") == -1
    assert candidate(hamsters = "H...H") == 2
    assert candidate(hamsters = "HH.HHH.HH") == -1
    assert candidate(hamsters = "........") == 0
    assert candidate(hamsters = "H.H.H.HH.H") == 3
    assert candidate(hamsters = "HH.HH.HH.HH") == -1
    assert candidate(hamsters = "H.H.H.H") == 2
    assert candidate(hamsters = ".") == 0
    assert candidate(hamsters = "HHHHHHHHHH") == -1
    assert candidate(hamsters = ".HHH.") == -1
    assert candidate(hamsters = "H.H.H.HH") == -1
    assert candidate(hamsters = ".H") == 1
    assert candidate(hamsters = ".H.H.H.H.") == 2
    assert candidate(hamsters = "H.H.H") == 2
    assert candidate(hamsters = "H") == -1
    assert candidate(hamsters = ".........") == 0
    assert candidate(hamsters = ".H.H.H.H.H.H.H.H.H.") == 5
    assert candidate(hamsters = ".H.H.H.H.H.H.H.H.") == 4
    assert candidate(hamsters = "HHHHHHH") == -1
    assert candidate(hamsters = "HH...HH") == -1
    assert candidate(hamsters = "H.H.H.H.H.H.H.H.H.H.H.H") == 6
    assert candidate(hamsters = "H......H") == 2
    assert candidate(hamsters = "H.H") == 1
    assert candidate(hamsters = "HH.HH.HH.HH.HH") == -1
    assert candidate(hamsters = "H..H") == 2
    assert candidate(hamsters = "HH..HH") == -1
    assert candidate(hamsters = "HHHH") == -1
