# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "ZzZzZzZ") == 0
    assert candidate(s = "QwErTyUiOpAsDfGhJkLzXcVbNm") == 25
    assert candidate(s = "ABCDEFG") == 6
    assert candidate(s = "A") == 0
    assert candidate(s = "AaAaAaaA") == 0
    assert candidate(s = "zZyYxXwW") == 3
    assert candidate(s = "zZyYxXwWvVuUtTsSrRqQpPoOnNmMlLkKjJiIhHgGfFeEdDcCbBaA") == 25
    assert candidate(s = "aAbBcC") == 2
    assert candidate(s = "aBcDeFg") == 6
    assert candidate(s = "aBAcB") == 4
    assert candidate(s = "AbCdEfGhIjK") == 10
    assert candidate(s = "zzzzzzzz") == 0
    assert candidate(s = "aAaAaAaAaA") == 0
    assert candidate(s = "AAAAaaaAAA") == 0
    assert candidate(s = "AAaaaAA") == 0
    assert candidate(s = "a") == 0
    assert candidate(s = "abcdefg") == 6
    assert candidate(s = "aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ") == 25
    assert candidate(s = "abcABCdefDEFghiGHIjklJKLmnoMNOpqrPQRstuSTUvwxVWXyzYZ") == 51
    assert candidate(s = "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ") == 51
    assert candidate(s = "AbCdEfGhIjKlMnoPqRsTuVwXyZ") == 25
    assert candidate(s = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZzAaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz") == 51
    assert candidate(s = "aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaA") == 0
    assert candidate(s = "aBCdeFGhIJKlmNoPQRstUVwXYz") == 25
    assert candidate(s = "AbCdEfGhIjKlMnOpQrStUvWxYzA") == 26
    assert candidate(s = "aBcDefGhIjKlMnOpQrStUvWxYz") == 25
    assert candidate(s = "aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaA") == 0
    assert candidate(s = "abcDefGhIjKlMnOpQrStUvWxYzABC") == 28
    assert candidate(s = "AaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAa") == 0
    assert candidate(s = "abABcdCDefEFghGHijIJklKLmnMNopOPqrQRstSTuvUVwxWXyzYZ") == 51
    assert candidate(s = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz") == 25
    assert candidate(s = "aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaA") == 0
    assert candidate(s = "aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAa") == 0
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ") == 51
    assert candidate(s = "bAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAz") == 48
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz") == 77
    assert candidate(s = "aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ") == 51
    assert candidate(s = "mNbvCxZlkJhGfDsApOiUrYtWeQ") == 25
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ") == 77
    assert candidate(s = "aBcDeFgHiJkLmNoPqRsTuVwXyZ") == 25
    assert candidate(s = "abcdEFGHijklMNOPqrstUVWXyz") == 25
    assert candidate(s = "zYxWvUtSrQpOnMlKjIhGfEdCbA") == 25
    assert candidate(s = "aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAb") == 1
    assert candidate(s = "AbCdEfGhIjKlMnOpQrStUvWxYz") == 25
    assert candidate(s = "aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaA") == 0
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(s = "aBcDeFgHiJkLmNoPqRsTuVwXyZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ") == 77
    assert candidate(s = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZzAa") == 26
    assert candidate(s = "aBcDeFgHiJkLmNoPqRsTuVwXyZaBc") == 28
    assert candidate(s = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZzAaBbCcDdEeFf") == 31
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcde") == 30
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 51
    assert candidate(s = "abcdefGHIJKLmnopQRstuvwxyzAbCdEfGHIJKLmnopQRstuvwxyz") == 51
    assert candidate(s = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz") == 51
    assert candidate(s = "aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZ") == 51
    assert candidate(s = "zZyYxXwWvVuUtTsSrRpPqQoOnNmMlLkKjJiIhHgGfFeEdDaA") == 23
    assert candidate(s = "aBcDabcdEFGHefghIJKLijklMNOpQRmnopqrSTUVstuvWXYZwxyz") == 51
    assert candidate(s = "aBcDabcdEFGHefghIJKLijklMNOpQRmnopqrSTUVstuvWXYZwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ") == 77
    assert candidate(s = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZzBb") == 26
    assert candidate(s = "zZyYxXwWvVuUtTsSrRpPqQoOnNmMlLkJiIhHgGfFeEdDcCbBaA") == 25
    assert candidate(s = "aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZ") == 77
    assert candidate(s = "aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaA") == 0
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(s = "aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaA") == 0
    assert candidate(s = "AaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAa") == 0
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcDEFdef") == 34
    assert candidate(s = "AbCdEfGhIjKlMnOpQrStUvWxYzAaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz") == 51
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ") == 103
    assert candidate(s = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZzAaBbCc") == 28
    assert candidate(s = "abcdEFGHijklMNOpQRstUVWXyz") == 25
    assert candidate(s = "aBcDefGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYz") == 51
    assert candidate(s = "AaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAa") == 0
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 25
    assert candidate(s = "ZYXWVUTSRQPONMLKJIHGFEDCBAzyxwvutsrqponmlkjihgfedcba") == 51
    assert candidate(s = "zYxWvUtSrQpOnMlKjIhGfEdCbAbaCBEDFGHIJKLNMOPQRSTU VWXYZ") == 53
    assert candidate(s = "AbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYz") == 51
    assert candidate(s = "aAaAaAaAaAaAaAaAaAaAaAaAaAaAaA") == 0
    assert candidate(s = "mNbVcXzLkJhGfDsApoIuYtReWq") == 25
