# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(word = "aaabbbccc") == 27
    assert candidate(word = "aaa") == 6
    assert candidate(word = "z") == 1
    assert candidate(word = "bdh") == 4
    assert candidate(word = "abcdefghij") == 22
    assert candidate(word = "asdf") == 6
    assert candidate(word = "zzz") == 6
    assert candidate(word = "world") == 10
    assert candidate(word = "zzzz") == 10
    assert candidate(word = "xyz") == 6
    assert candidate(word = "lmnopqrs") == 17
    assert candidate(word = "hello") == 7
    assert candidate(word = "qwertyuiop") == 25
    assert candidate(word = "abcd") == 6
    assert candidate(word = "abcdefg") == 14
    assert candidate(word = "abcabcabc") == 12
    assert candidate(word = "a") == 1
    assert candidate(word = "mnopqr") == 11
    assert candidate(word = "abc") == 4
    assert candidate(word = "zyxwvutsrqponmlkjihgfedcba") == 95
    assert candidate(word = "programming") == 22
    assert candidate(word = "abcdefghijklmnopqrstuvwxyz") == 95
    assert candidate(word = "hellohellohellohellohello") == 66
    assert candidate(word = "noon") == 5
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzmnopqrstuvwxyzabcdefghij") == 380
    assert candidate(word = "divisible") == 18
    assert candidate(word = "bananabanana") == 34
    assert candidate(word = "mississippi") == 28
    assert candidate(word = "xzyxzyxzyxzy") == 78
    assert candidate(word = "amazingrace") == 31
    assert candidate(word = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 60
    assert candidate(word = "racecar") == 14
    assert candidate(word = "civic") == 10
    assert candidate(word = "hellohellohellohello") == 50
    assert candidate(word = "alphanumericmappings") == 53
    assert candidate(word = "abcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefg") == 700
    assert candidate(word = "thisisateststring") == 47
    assert candidate(word = "xyzwvutsrqponmlkjihgfedcba") == 95
    assert candidate(word = "zzzzzzzzzz") == 55
    assert candidate(word = "abcdefgabcdefgabcdefg") == 105
    assert candidate(word = "pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp") == 4656
    assert candidate(word = "level") == 10
    assert candidate(word = "mnopqrstuvwxyzabcdefghijkl") == 84
    assert candidate(word = "xyzxyz") == 21
    assert candidate(word = "abcdabcdabcdabcd") == 24
    assert candidate(word = "banana") == 14
    assert candidate(word = "deified") == 16
    assert candidate(word = "thequickbrownfoxjumpsoverthelazydog") == 114
    assert candidate(word = "mnopqrnopqrmnopqr") == 64
    assert candidate(word = "example") == 12
    assert candidate(word = "abcdefghijklnmopqrstuvwxyz") == 95
    assert candidate(word = "supercalifragilisticexpialidocious") == 104
    assert candidate(word = "kayak") == 7
    assert candidate(word = "aquickbrownfoxjumpsoverthelazydog") == 106
    assert candidate(word = "thisisaverylongwordthatshouldhavemanydivisiblesubstrings") == 187
    assert candidate(word = "rotor") == 5
    assert candidate(word = "mnopqrstuvmnopqrstuv") == 52
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 222
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 4656
    assert candidate(word = "qwertyuiopasdfghjklzxcvbnm") == 85
    assert candidate(word = "divisibilitycheck") == 38
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1378
    assert candidate(word = "mnopqrstopqrstmnopqrstopqrstmnopqrstopqrstmnopqrstopqrstmnopqrstopqrstmnopqrst") == 192
    assert candidate(word = "ababababab") == 55
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzz") == 210
    assert candidate(word = "perfectprogramming") == 43
    assert candidate(word = "alibabacloud") == 28
    assert candidate(word = "xyzxyzxyz") == 45
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 266
    assert candidate(word = "pneumonoultramicroscopicsilicovolcanoconiosis") == 134
    assert candidate(word = "qwertypoiuzxcvbnmnbvcxzpoiuytrewq") == 127
    assert candidate(word = "xzyxzyxzy") == 45
    assert candidate(word = "substring") == 20
    assert candidate(word = "abababababababababababababababababababababababababababababababababababababababababab") == 3570
    assert candidate(word = "hellohellohello") == 34
    assert candidate(word = "helloprogrammingworld") == 63
    assert candidate(word = "abcdefghijabcdefghijabcdefghij") == 82
    assert candidate(word = "pythonprogramming") == 46
    assert candidate(word = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij") == 232
    assert candidate(word = "xylophone") == 18
    assert candidate(word = "abracadabra") == 24
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 903
    assert candidate(word = "repeatedcharacterssssssss") == 101
    assert candidate(word = "aaaaabbbbccccdddd") == 81
    assert candidate(word = "abababababab") == 78
    assert candidate(word = "xyzabcxyzabcxyzabc") == 46
    assert candidate(word = "zzzzzz") == 21
    assert candidate(word = "repeatedrepeatedrepeated") == 61
    assert candidate(word = "abacabadabacaba") == 27
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 224
