# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "aaabbbccc") == 9
    assert candidate(s = "abcba") == 5
    assert candidate(s = "cba") == 1
    assert candidate(s = "cbaacb") == 8
    assert candidate(s = "bbbacbac") == 18
    assert candidate(s = "ccccabc") == 9
    assert candidate(s = "abcabcabc") == 28
    assert candidate(s = "abcabcabcabc") == 55
    assert candidate(s = "aabbc") == 2
    assert candidate(s = "cccbaab") == 9
    assert candidate(s = "aabbbc") == 2
    assert candidate(s = "aabcbc") == 6
    assert candidate(s = "abcabc") == 10
    assert candidate(s = "aabbaacc") == 8
    assert candidate(s = "abacbc") == 8
    assert candidate(s = "abacabacabc") == 41
    assert candidate(s = "aaaabbbbcccc") == 16
    assert candidate(s = "ccbaaabb") == 10
    assert candidate(s = "baccab") == 7
    assert candidate(s = "bca") == 1
    assert candidate(s = "abc") == 1
    assert candidate(s = "ccccbaaa") == 12
    assert candidate(s = "aaacb") == 3
    assert candidate(s = "ccccbaab") == 12
    assert candidate(s = "abcababc") == 18
    assert candidate(s = "aabbcc") == 4
    assert candidate(s = "aaaabbbccc") == 12
    assert candidate(s = "abacbac") == 14
    assert candidate(s = "abcacbacbacbabc") == 89
    assert candidate(s = "aabbcacabcabc") == 59
    assert candidate(s = "ccabababc") == 17
    assert candidate(s = "abacbabacbabacbab") == 112
    assert candidate(s = "aabccbabcbacbac") == 85
    assert candidate(s = "abcabcabccba") == 52
    assert candidate(s = "aabbccbaa") == 18
    assert candidate(s = "aaabbbcccbbbccc") == 27
    assert candidate(s = "acbacbacbacbacb") == 91
    assert candidate(s = "abacbacbacb") == 44
    assert candidate(s = "aabcbacbacbabc") == 75
    assert candidate(s = "bcabcabcabcabc") == 78
    assert candidate(s = "aaabbbcccabcabcabc") == 115
    assert candidate(s = "abacbacbacbacbabcababcabc") == 271
    assert candidate(s = "acbacbacbacb") == 55
    assert candidate(s = "abacbacbacbabc") == 76
    assert candidate(s = "cccbbbaaa") == 9
    assert candidate(s = "caabcbacbacb") == 52
    assert candidate(s = "abbbcccaabbbabc") == 59
    assert candidate(s = "abacbcabc") == 26
    assert candidate(s = "aaabbbcccbbbaaa") == 45
    assert candidate(s = "bacbacbacbacb") == 66
    assert candidate(s = "cabcbacbacbabcb") == 88
    assert candidate(s = "abacbcacab") == 31
    assert candidate(s = "bbbbbbcccaaa") == 18
    assert candidate(s = "aaaaaaaaaabbbccc") == 30
    assert candidate(s = "ccbbbaaabbbccc") == 36
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc") == 406
    assert candidate(s = "abcabcabcab") == 45
    assert candidate(s = "aabbaaccabcabcabc") == 104
    assert candidate(s = "bacbacbacbacbacba") == 120
    assert candidate(s = "ccccbbbaaaaa") == 20
    assert candidate(s = "abababababababab") == 0
    assert candidate(s = "abacbcabcabcab") == 76
    assert candidate(s = "abababababab") == 0
    assert candidate(s = "cacbacbacbac") == 54
    assert candidate(s = "cabbacbac") == 25
    assert candidate(s = "aabbaacccbaab") == 45
    assert candidate(s = "abcabcabcabcabcabc") == 136
    assert candidate(s = "cbacbacbacbac") == 66
    assert candidate(s = "aabbbcccaaaabbbccc") == 86
    assert candidate(s = "bacbacbacbacba") == 78
    assert candidate(s = "aabacababaac") == 40
    assert candidate(s = "abcababccbaabc") == 69
    assert candidate(s = "ababababcabcab") == 57
    assert candidate(s = "aaabbbcccbbb") == 18
    assert candidate(s = "abcabcabcabcababc") == 117
    assert candidate(s = "abccbaabccbaab") == 66
    assert candidate(s = "baccabaccabacc") == 69
    assert candidate(s = "abacbcacbacb") == 52
    assert candidate(s = "cccccbbaaaabbbccc") == 68
    assert candidate(s = "bbcccaabbcccaab") == 65
    assert candidate(s = "aabbbccccaaaabbbbccc") == 103
    assert candidate(s = "abababab") == 0
    assert candidate(s = "cbacbacbacbacbacbacbacbacbacbacb") == 465
    assert candidate(s = "abcbaabcbaabc") == 58
    assert candidate(s = "aabcbabacabc") == 49
    assert candidate(s = "aabacbacbacbac") == 75
    assert candidate(s = "aabbaaccbbacbbacaacabcbacbacbacbac") == 498
    assert candidate(s = "abacbabacbabac") == 71
    assert candidate(s = "aabbbcccaabbbabc") == 70
    assert candidate(s = "aaaabbccccabbbccc") == 85
    assert candidate(s = "cccaaaabbbcccbbb") == 51
    assert candidate(s = "ccccbbaaaabc") == 30
    assert candidate(s = "acbacbacbacbacbacbacbacbacbacbac") == 465
    assert candidate(s = "abcbbccaaa") == 20
    assert candidate(s = "cccaabbbaaacc") == 34
    assert candidate(s = "ccccccccabbaabbcbbb") == 100
    assert candidate(s = "cccbababac") == 23
    assert candidate(s = "ccccabcabcabc") == 60
    assert candidate(s = "aabacbababcabc") == 69
    assert candidate(s = "aaabbbcccbbbaaabbbc") == 87
    assert candidate(s = "abccabccabccabc") == 85
    assert candidate(s = "abcbacbacbacbaca") == 103
    assert candidate(s = "abcabcabcabacbacb") == 119
    assert candidate(s = "aabbbcccabcabcabc") == 103
    assert candidate(s = "abacbcabcabc") == 53
    assert candidate(s = "aabbaaccaabbcc") == 52
    assert candidate(s = "abcabcabacbcab") == 76
    assert candidate(s = "aabbbccc") == 6
    assert candidate(s = "aabbaacccbbcabab") == 77
    assert candidate(s = "babababacacacacbcbbcbcbcbacbacbacb") == 441
    assert candidate(s = "cacbacbacbacbacbac") == 135
    assert candidate(s = "cccbbaaaabacbacb") == 78
    assert candidate(s = "ccccbbbaaa") == 12
    assert candidate(s = "aaaaaaaaaabcabcabcabcabc") == 208
    assert candidate(s = "aabbbccccaaa") == 23
    assert candidate(s = "abacbacbac") == 35
    assert candidate(s = "aabbbaccccba") == 36
    assert candidate(s = "ccbaabccababab") == 62
    assert candidate(s = "ccccbaabccc") == 33
    assert candidate(s = "ccccbaa") == 8
    assert candidate(s = "bacabcabcabcabcabcabcabc") == 252
    assert candidate(s = "ccccccaaaabbbccc") == 48
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabc") == 496
    assert candidate(s = "abacbabcc") == 25
    assert candidate(s = "abacbacbacbacb") == 77
    assert candidate(s = "bacbacbacbacbacbacbac") == 190
    assert candidate(s = "abcabcabcabcabc") == 91
    assert candidate(s = "bbaacccaaaabbccba") == 76
    assert candidate(s = "aaaaabbbbbccccc") == 25
    assert candidate(s = "aaabbbcccabc") == 34
