# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "xyzxyzxyz") == 4
    assert candidate(s = "aabbcc") == 1
    assert candidate(s = "abcde") == 0
    assert candidate(s = "abcdefghij") == 1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 1
    assert candidate(s = "aabbccddeeffgghhiijj") == 1
    assert candidate(s = "abacaba") == 0
    assert candidate(s = "aacaba") == 2
    assert candidate(s = "aabbbcc") == 2
    assert candidate(s = "aaa") == 2
    assert candidate(s = "abcd") == 1
    assert candidate(s = "aaaaa") == 4
    assert candidate(s = "xyz") == 0
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba") == 1
    assert candidate(s = "aabbccddeeff") == 1
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 45
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzxywvutsrqponmlkjihgfedcba") == 1
    assert candidate(s = "aabacadaeafagahaiajakalalamanaoaopapaqaraasatauavaawaxayaza") == 0
    assert candidate(s = "ababababababababababababababababababababababababab") == 47
    assert candidate(s = "abacabadabacabadabacabad") == 12
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzz") == 1
    assert candidate(s = "aaaaaabbccdddeeffggghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 1
    assert candidate(s = "abababababababababababababababababababababababababababababababababababababababab") == 77
    assert candidate(s = "nnnnaaaaccccbbbbbddddnnnnaaaaccccbbbbbdddd") == 7
    assert candidate(s = "thisisaverylongstringwithavarietyofcharactersandrepeatpatterns") == 3
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 3
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm") == 27
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzqqqqqqqq") == 1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "abbaccddeeffaabbccddeeff") == 3
    assert candidate(s = "aaabbbcccdddeeefffggghhhiiiijjjkkklllmmmnnnooopppqqqrrrssstttuuuvvvwwwxxxyyyzzz") == 1
    assert candidate(s = "abacabadabacaba") == 0
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadab") == 84
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 89
    assert candidate(s = "abracadabra") == 2
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc") == 25
    assert candidate(s = "pppppppppppppppppppppppppppppppppppppppppppppppp") == 47
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 73
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzyxwvutsrqponmlkjihgfedcba") == 2
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 63
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzyyxwwvvuutsrrqponmlkjihgfedcba") == 2
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcd") == 25
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzabcdefghijklmnopqrstuvwxyz") == 2
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd") == 1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyz") == 1
    assert candidate(s = "mississississississippi") == 16
    assert candidate(s = "abcdefghihgfedcba") == 0
    assert candidate(s = "abracadabraabracadabraabracadabra") == 20
    assert candidate(s = "pppppppppppppppppppppppppppppp") == 29
    assert candidate(s = "11223344556677889900112233445566778899001122334455667788990011223344556677889900") == 43
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 61
    assert candidate(s = "mnbvcxzlkjhgfdsapoiuytrewqasdfghjklzxcvbnmmnbvcxzlkjhgfdsapoiuytrewq") == 17
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad") == 68
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 1
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcbaedcba") == 1
    assert candidate(s = "mississippimississippimississippimississippimississippi") == 36
    assert candidate(s = "bacaabacababacaacbacaaacaaacaacbaaaacaacaaacaacaaacaaacaa") == 29
    assert candidate(s = "abcdefghijklnmopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 77
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 51
    assert candidate(s = "abracadabraabracadabraabracadabraabracadabraabracadabraabracadabra") == 53
    assert candidate(s = "abbaccddeeffaabbccddeeffaabbccddeeff") == 15
    assert candidate(s = "nnnnaaaaccccbbbbbdddd") == 3
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 79
    assert candidate(s = "mississippi") == 4
    assert candidate(s = "aaaabbbbccccddddeeeeffffgggghhhhiiiijjjjkkkkllllmmmnnnooooppppqqqqrrrrssssttttuuuuvvvvwwwwxxxxyyyyzzzz") == 1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba") == 0
    assert candidate(s = "aaabbbcccddd") == 1
    assert candidate(s = "abababababababababababababababababababababababababababa") == 52
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 81
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcde") == 1
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 73
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcd") == 21
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 49
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcbaabcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 53
    assert candidate(s = "aabbaabbaabbaabb") == 11
