# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "aaaabbbb") == 24
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 351
    assert candidate(s = "abac") == 9
    assert candidate(s = "abababab") == 15
    assert candidate(s = "aaaaa") == 5
    assert candidate(s = "a") == 1
    assert candidate(s = "pwwkew") == 19
    assert candidate(s = "abcabcabc") == 24
    assert candidate(s = "p") == 1
    assert candidate(s = "abracadabra") == 54
    assert candidate(s = "ab") == 3
    assert candidate(s = "aa") == 2
    assert candidate(s = "xyxyxyxyxy") == 19
    assert candidate(s = "aaa") == 3
    assert candidate(s = "abcde") == 15
    assert candidate(s = "xyz") == 6
    assert candidate(s = "xyzxyzxyz") == 24
    assert candidate(s = "banana") == 15
    assert candidate(s = "abc") == 6
    assert candidate(s = "aabbaba") == 21
    assert candidate(s = "abcd") == 10
    assert candidate(s = "aaaa") == 4
    assert candidate(s = "mississippi") == 53
    assert candidate(s = "z") == 1
    assert candidate(s = "abacaba") == 21
    assert candidate(s = "abcdefg") == 28
    assert candidate(s = "aaaabbbbccccdddd") == 112
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzz") == 1760
    assert candidate(s = "lkseropqwertyuiopasdfghjklzxcvbnmlkser") == 717
    assert candidate(s = "longerstringwithmultiplesubstringsubstring") == 824
    assert candidate(s = "elephantmanelephant") == 150
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 200
    assert candidate(s = "abbaabbaabba") == 40
    assert candidate(s = "longstringwithrepeatedsubstringsubstring") == 742
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 44
    assert candidate(s = "abacabacabac") == 41
    assert candidate(s = "nlpnlplpnlplp") == 57
    assert candidate(s = "abcdefghijlkmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 1351
    assert candidate(s = "aaaaabaaaabbbaabababab") == 193
    assert candidate(s = "zzyzxzyzyxzyz") == 71
    assert candidate(s = "hellohellogoodbyegoodbye") == 253
    assert candidate(s = "xyxxxyxyxyxyxyxyxyxyxyxyxy") == 133
    assert candidate(s = "abacabadabacaba") == 85
    assert candidate(s = "xyzyzyzyxzyzyzy") == 83
    assert candidate(s = "abcabcabcabc") == 33
    assert candidate(s = "xyzyxzyzyxzyzyxzyzyx") == 101
    assert candidate(s = "ababababab") == 19
    assert candidate(s = "ababaabababaababa") == 83
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz") == 20
    assert candidate(s = "thelongeststringwithdistinctsubstringstothetestthesolution") == 1634
    assert candidate(s = "nndbymxkbmsnnvkze") == 146
    assert candidate(s = "abcdabcd") == 26
    assert candidate(s = "aaaaaaaaaa") == 10
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnm") == 351
    assert candidate(s = "racecar") == 25
    assert candidate(s = "aaaaaaaaaab") == 21
    assert candidate(s = "zxyxzyzxzyxzyxzy") == 101
    assert candidate(s = "abcdefghijabcdefghij") == 155
    assert candidate(s = "aaaaaabbbaaaaab") == 81
    assert candidate(s = "repeatedsubstringsubstring") == 301
    assert candidate(s = "aaaaaa") == 6
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 1027
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 54
    assert candidate(s = "noon") == 8
    assert candidate(s = "noonnoonnoonnoonnoonnoonnoonnoon") == 120
    assert candidate(s = "abcdabcdabcd") == 42
    assert candidate(s = "aaaabbbbcccc") == 60
    assert candidate(s = "pneumonoultramicroscopicsilicovolcanoconiosis") == 996
    assert candidate(s = "abcabcabcabcabcabc") == 51
    assert candidate(s = "hellohello") == 39
    assert candidate(s = "aaaaabbbbbaaaa") == 75
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 1077
    assert candidate(s = "aaaaabbbbbccccdddd") == 139
    assert candidate(s = "thisisaverylongstringthatincludesmanyrepeatedsubstringstomakethetestmoreinteresting") == 3379
    assert candidate(s = "abcdefghij") == 55
    assert candidate(s = "madamimadam") == 49
    assert candidate(s = "repeatedpatternrepeatedpattern") == 335
    assert candidate(s = "aabbaabbbaaaabbbbaabbbaaabbaabbbaaaabbbbaabbbaaabbaabbbaaaabbbb") == 1102
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 1352
    assert candidate(s = "thisisaverylongstringwithmanysubstrings") == 738
    assert candidate(s = "abcabcabcabcabc") == 42
    assert candidate(s = "abcdabcdabcdabcd") == 58
    assert candidate(s = "aaaaaaa") == 7
    assert candidate(s = "thisisaverylongstringwithsomerepeatedpatterns") == 1000
