# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "a",count = 5) == 0
    assert candidate(s = "abcdefg",count = 3) == 0
    assert candidate(s = "abcabcabc",count = 3) == 1
    assert candidate(s = "abccbaabc",count = 3) == 1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",count = 2) == 351
    assert candidate(s = "abcabcabc",count = 1) == 24
    assert candidate(s = "",count = 1) == 0
    assert candidate(s = "abcabcabc",count = 2) == 4
    assert candidate(s = "zzzzzz",count = 2) == 5
    assert candidate(s = "aaaabbbbcccc",count = 4) == 6
    assert candidate(s = "abababab",count = 2) == 5
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",count = 1) == 351
    assert candidate(s = "abcabcabcabc",count = 2) == 7
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzaaa",count = 1) == 379
    assert candidate(s = "aaabcbbcc",count = 3) == 3
    assert candidate(s = "ababab",count = 2) == 3
    assert candidate(s = "zzzzzzzzzzz",count = 5) == 7
    assert candidate(s = "aaaabbbbccccddddeeeeffffgggghhhhiiiijjjjkkkkllllmmmmnnnnoooo",count = 4) == 120
    assert candidate(s = "xyz",count = 1) == 6
    assert candidate(s = "abcdefg",count = 1) == 28
    assert candidate(s = "zzzzzzzzz",count = 3) == 7
    assert candidate(s = "abacabadabacaba",count = 2) == 0
    assert candidate(s = "abcd",count = 2) == 0
    assert candidate(s = "aaaaabbbbcccccdddddeeeeeffffffggggghhhhhiiiii",count = 5) == 21
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",count = 1) == 77
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",count = 3) == 1
    assert candidate(s = "xyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxy",count = 5) == 45
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",count = 26) == 37
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",count = 15) == 52
    assert candidate(s = "mississippiississippi",count = 4) == 2
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc",count = 3) == 22
    assert candidate(s = "mnopqrstuvwxyzabcdefghijkl",count = 1) == 351
    assert candidate(s = "qqwweerrttyyuuiiooppllaaakkkjjjhhhgggfffeeeddccbbbaaa",count = 3) == 31
    assert candidate(s = "abcdefghijklmnopqrstuvwxyza",count = 1) == 377
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",count = 7) == 26
    assert candidate(s = "qqwweerrttyyuuiiooppaassddffgg",count = 2) == 120
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc",count = 3) == 52
    assert candidate(s = "abcdabcdeabcdeabcdefabcdefgabcdefgabcdefghabcdefghijk",count = 1) == 330
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd",count = 10) == 10
    assert candidate(s = "xyzzxyzzxyzz",count = 3) == 0
    assert candidate(s = "abcdefghijabcdefghijabcdefghij",count = 1) == 255
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabad",count = 2) == 0
    assert candidate(s = "xyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",count = 30) == 39
    assert candidate(s = "mississippiississi",count = 2) == 16
    assert candidate(s = "abacabadabacaba",count = 3) == 0
    assert candidate(s = "xyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",count = 15) == 36
    assert candidate(s = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz",count = 3) == 28
    assert candidate(s = "aaaabbbbccccddddeeeeffffgggghhhhiiiijjjjkkkkllllmmmmnnnnooooppppqqqqrrrrssssttttuuuuvvvvwwwwxxxxyyyyzzzz",count = 4) == 351
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyza",count = 26) == 0
    assert candidate(s = "aabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabb",count = 2) == 69
    assert candidate(s = "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq",count = 10) == 45
    assert candidate(s = "pqrstuvwxyzaaaabbbccccddddeeeeffffgggghhhhiiiii",count = 4) == 30
    assert candidate(s = "mnopqrstuvwxyzyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcba",count = 2) == 1
    assert candidate(s = "nnnooppnnooppnnoopp",count = 3) == 1
    assert candidate(s = "aabccddeeffaabbccddeeffaabbccddeeffaabbccddeeff",count = 2) == 135
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",count = 25) == 54
    assert candidate(s = "aaabbbcccddd",count = 3) == 10
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzaaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",count = 3) == 2
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",count = 10) == 31
    assert candidate(s = "abcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdef",count = 3) == 43
    assert candidate(s = "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq",count = 10) == 95
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc",count = 3) == 64
    assert candidate(s = "xzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzy",count = 3) == 40
    assert candidate(s = "aaaaabbbbbaaaaabbbbbaaaaabbbbbaaaaabbbbbaaaaabbbbbaaaaa",count = 5) == 57
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",count = 4) == 0
    assert candidate(s = "nnnneeeeeeeeccccccccccccvvvvvvvvvvvvvvvvvvvvvvvvvv",count = 5) == 36
    assert candidate(s = "xyzzzzzzzzzzyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxy",count = 3) == 41
    assert candidate(s = "xyzzzzzzzzzxyzzzzzzzzzxyzzzzzzzzz",count = 7) == 9
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",count = 10) == 43
    assert candidate(s = "aaaaabbbbbcccccddddd",count = 5) == 10
    assert candidate(s = "aabbaabbaabbaabbaabbaabbaabbaabbaabb",count = 3) == 15
    assert candidate(s = "abcdefghijabcdefghijabcdefghij",count = 3) == 1
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc",count = 3) == 40
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",count = 3) == 0
    assert candidate(s = "abcabcabcabcabcabc",count = 2) == 13
    assert candidate(s = "abababababababababababababababababababababababab",count = 2) == 45
    assert candidate(s = "thisisjustarandomstringwithvariedcharacters",count = 2) == 1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",count = 10) == 67
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd",count = 5) == 27
    assert candidate(s = "abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde",count = 5) == 36
    assert candidate(s = "pppppppppppppppppppppppppppppp",count = 15) == 16
    assert candidate(s = "aaabbbcccdddeeefffggghhhhiiiijjjjkkkkllllmmmmnnnnoooo",count = 4) == 36
    assert candidate(s = "xyzzzzzxyzzzzzxyzzzzz",count = 5) == 3
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc",count = 3) == 49
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",count = 25) == 30
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",count = 30) == 59
    assert candidate(s = "aaabbbaaabbbccc",count = 3) == 14
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",count = 10) == 35
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",count = 2) == 1
    assert candidate(s = "lkjlkjlkjlkjlkjlkjlkjlkjlkjlkjlkjlkjlkjlkjlkjlkj",count = 3) == 40
    assert candidate(s = "abcdefghijkabcdefghijkabcdefghijkabcdefghijkabcdefghijk",count = 5) == 1
    assert candidate(s = "mississippi",count = 2) == 8
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzaaa",count = 3) == 1
    assert candidate(s = "aaaabbbbccccddddeeeeffffgggghhhhiiii",count = 4) == 45
    assert candidate(s = "abcdefghijabcdefghij",count = 2) == 1
    assert candidate(s = "mississippiississippiississippi",count = 4) == 4
    assert candidate(s = "ababababababababababababababababababababababab",count = 4) == 39
