# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(word = "aaaaaaaaaa") == 55
    assert candidate(word = "aabbccddeeffgghhiijj") == 165
    assert candidate(word = "aba") == 4
    assert candidate(word = "aaaabbbbcccc") == 66
    assert candidate(word = "babcbabcbab") == 32
    assert candidate(word = "abcdefghija") == 11
    assert candidate(word = "abcdcba") == 10
    assert candidate(word = "aaa") == 6
    assert candidate(word = "aabb") == 9
    assert candidate(word = "aabbccddeeffgg") == 84
    assert candidate(word = "abcdefghij") == 10
    assert candidate(word = "jihgfedcba") == 10
    assert candidate(word = "aabbccddeeff") == 63
    assert candidate(word = "abcabc") == 9
    assert candidate(word = "abacaba") == 12
    assert candidate(word = "jij") == 4
    assert candidate(word = "xyz") == 0
    assert candidate(word = "abcdefghijabcdefghij") == 23
    assert candidate(word = "abcde") == 5
    assert candidate(word = "ijji") == 8
    assert candidate(word = "jjjjj") == 15
    assert candidate(word = "jijijijiji") == 40
    assert candidate(word = "aabbaa") == 19
    assert candidate(word = "abcabcabc") == 21
    assert candidate(word = "he") == 2
    assert candidate(word = "a") == 1
    assert candidate(word = "abcdefghijabcdefghijabcdefghij") == 63
    assert candidate(word = "jijjjijijj") == 41
    assert candidate(word = "aaaaaaa") == 28
    assert candidate(word = "aaaaa") == 15
    assert candidate(word = "abacabadabacaba") == 32
    assert candidate(word = "aaaaaaaabbbbbbbbaaaaaaaabbbbbbbb") == 464
    assert candidate(word = "jihgfedcbajihgfedcbajihgfedcbajihgfedcbajihgfedcba") == 176
    assert candidate(word = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij") == 1038
    assert candidate(word = "jijijiijijijiijijijiijijijiijijijiijijijiijijiij") == 879
    assert candidate(word = "abcdefghijabcde") == 15
    assert candidate(word = "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj") == 903
    assert candidate(word = "acacacacacacacacacac") == 155
    assert candidate(word = "jijijiijjjjijiijijijiijjjjijiijijijiijjjjijiijijijiijjjjijiijijijiijjjjijiijijijiijjjjijiijijijiijjjjijiijijijiijjjjj") == 5171
    assert candidate(word = "abcdefghijabcdefghijabcdefghijabcdefghij") == 106
    assert candidate(word = "aabbccddeeaabbccddeeaabbccddeeaabbccddeeaabbccddeeaabbccddeeaabbccddeeaabbccddeeaabbccddeeaabbccddeeaabbccdd") == 4720
    assert candidate(word = "aabbaaabbbaaabbaaa") == 126
    assert candidate(word = "jjiijjiijjjiiijjiiijjjijjjiiijjiiijjjijjjjj") == 721
    assert candidate(word = "aabbaabbaabbaabb") == 120
    assert candidate(word = "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj") == 990
    assert candidate(word = "aabbaabbaabbaabbccddeeffgghhiijj") == 420
    assert candidate(word = "abcabcabcabcabcabcabcabcabcabc") == 225
    assert candidate(word = "abcdeedcba") == 23
    assert candidate(word = "aaaabbbbccccddddeeeeffffgggghhhhiiiijjjj") == 640
    assert candidate(word = "abcdabcdaabbccddeeffgghhiijj") == 222
    assert candidate(word = "ababababababababababababababababababababab") == 672
    assert candidate(word = "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj") == 2485
    assert candidate(word = "jijijiijjjijiiiiij") == 132
    assert candidate(word = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij") == 176
    assert candidate(word = "ababababababababababababab") == 260
    assert candidate(word = "aabbaaabbbaaabbaaabbba") == 187
    assert candidate(word = "acccabbbdcbaaaccbbaaccbbcdac") == 161
    assert candidate(word = "aabbaaabbbaaaabbbaaa") == 159
    assert candidate(word = "abcabcabcabcabc") == 57
    assert candidate(word = "jjjjjjjjjj") == 55
    assert candidate(word = "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd") == 670
    assert candidate(word = "abcdefghijkabcdefghijkabcdefghijk") == 63
    assert candidate(word = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij") == 452
    assert candidate(word = "aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee") == 1025
    assert candidate(word = "abcdefghijabcdeijfgh") == 23
    assert candidate(word = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 820
    assert candidate(word = "aaaaaaaaaabbbbbbbbbbbbccccccccccdddddddddd") == 738
    assert candidate(word = "aabbccddeeaabbccddeeaabbccddeedcba") == 403
    assert candidate(word = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij") == 715
    assert candidate(word = "babababababababababa") == 155
    assert candidate(word = "aabbccddeeffgghhiijjijjiihhggeeffddccbbaa") == 501
    assert candidate(word = "aabbccddeeffgghhiijjabcdefghijabcdefghijabcdefghijabcdefghij") == 363
    assert candidate(word = "abcabccbaabccbaabcabccbaabccba") == 225
    assert candidate(word = "abcdefghijjihgfedcba") == 48
    assert candidate(word = "abacabadabacabadabacabad") == 90
    assert candidate(word = "abababababababababababababababab") == 392
    assert candidate(word = "abacabadabacabadabacabadabacabad") == 154
