# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "123",t = "1234") == True
    assert candidate(s = "abc",t = "abcd") == True
    assert candidate(s = "ab",t = "acb") == True
    assert candidate(s = "abcd",t = "abde") == False
    assert candidate(s = "cat",t = "dog") == False
    assert candidate(s = "123",t = "113") == True
    assert candidate(s = "",t = "") == False
    assert candidate(s = "abc",t = "ab") == True
    assert candidate(s = "aAbB",t = "aabb") == False
    assert candidate(s = "abcd",t = "abcde") == True
    assert candidate(s = "a",t = "") == True
    assert candidate(s = "abcd",t = "abcf") == True
    assert candidate(s = "1234",t = "2234") == True
    assert candidate(s = "abc",t = "aabbcc") == False
    assert candidate(s = "1234",t = "123") == True
    assert candidate(s = "123",t = "143") == True
    assert candidate(s = "abcdef",t = "abcde") == True
    assert candidate(s = "abcd",t = "abdc") == False
    assert candidate(s = "abcd",t = "abc") == True
    assert candidate(s = "123",t = "12") == True
    assert candidate(s = "aAbB",t = "aAb") == True
    assert candidate(s = "abc",t = "adc") == True
    assert candidate(s = "cat",t = "catt") == True
    assert candidate(s = "teacher",t = "teach") == False
    assert candidate(s = "123",t = "123") == False
    assert candidate(s = "",t = "a") == True
    assert candidate(s = "aAbB",t = "aAbBB") == True
    assert candidate(s = "abc",t = "abc") == False
    assert candidate(s = "umbrella",t = "umbrell") == True
    assert candidate(s = "algorithm",t = "alorithm") == True
    assert candidate(s = "abcdefghijk",t = "aefghijkl") == False
    assert candidate(s = "abcd",t = "ab") == False
    assert candidate(s = "abcdefghijk",t = "abcdefghikl") == False
    assert candidate(s = "algorithm",t = "algoritm") == True
    assert candidate(s = "abcdefghij",t = "abxdefghij") == True
    assert candidate(s = "abcde",t = "abcd") == True
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnm",t = "qwertyuiopasdfghjklzxcvbn") == True
    assert candidate(s = "abcdefghij",t = "abcdefghi") == True
    assert candidate(s = "abcdefghij",t = "abcdefgha") == False
    assert candidate(s = "abcdefghijk",t = "a") == False
    assert candidate(s = "zoo",t = "zoology") == False
    assert candidate(s = "a1b2c3d4",t = "a1b2c3d4e5") == False
    assert candidate(s = "abcdefg",t = "abecdefg") == True
    assert candidate(s = "abcde",t = "abcdex") == True
    assert candidate(s = "aaaaaa",t = "aaaaaaa") == True
    assert candidate(s = "abcdefghijk",t = "abcdefg") == False
    assert candidate(s = "abcdefghijk",t = "abcdefghijk") == False
    assert candidate(s = "abacaxi",t = "abacax") == True
    assert candidate(s = "abcdefghij",t = "abcdefghjk") == False
    assert candidate(s = "gumbo",t = "gambol") == False
    assert candidate(s = "happy",t = "happiness") == False
    assert candidate(s = "abcdefghijk",t = "abcdefghikj") == False
    assert candidate(s = "abcdefgh",t = "abcdfgh") == True
    assert candidate(s = "abcdexyz",t = "abcdexyz") == False
    assert candidate(s = "hello world",t = "hello wold") == True
    assert candidate(s = "aabbcc",t = "aabbca") == True
    assert candidate(s = "aabbcc",t = "aabbc") == True
    assert candidate(s = "abcdefghij",t = "abcdefghix") == True
    assert candidate(s = "umbrella",t = "umbralra") == False
    assert candidate(s = "abcd",t = "abec") == False
    assert candidate(s = "abcdefghijk",t = "abcd") == False
    assert candidate(s = "abcdefghijk",t = "abcdefghi") == False
    assert candidate(s = "abc",t = "abcde") == False
    assert candidate(s = "abcdefghij",t = "abcdefghijkabc") == False
    assert candidate(s = "12345",t = "12346") == True
    assert candidate(s = "abcd",t = "dabc") == False
    assert candidate(s = "abcdefgh",t = "abcdegh") == True
    assert candidate(s = "abcdefgh",t = "abcdef") == False
    assert candidate(s = "algorithm",t = "algoritam") == True
    assert candidate(s = "abcdefghijk",t = "abcdefghijkdefghijk") == False
    assert candidate(s = "abcdefghijk",t = "abcdefghijka") == True
    assert candidate(s = "abcdefghijk",t = "abcdefghijkij") == False
    assert candidate(s = "abcdefgh",t = "abcdefh") == True
    assert candidate(s = "abcdefghijk",t = "abcdefghijl") == True
    assert candidate(s = "abcdefghijk",t = "abchijk") == False
    assert candidate(s = "abcdefghijk",t = "abcdefghijkabcdefghijkabcdefghijk") == False
    assert candidate(s = "pale",t = "ple") == True
    assert candidate(s = "abcdefghijk",t = "abcdefghijkabcdefghijkabcdefghijkabcdefghijkabcdefghijkabcdefghijk") == False
    assert candidate(s = "abcdefghij",t = "abcdefghia") == True
    assert candidate(s = "abcd",t = "acbd") == False
    assert candidate(s = "mississippi",t = "missisipi") == False
    assert candidate(s = "abcdef",t = "abcdefg") == True
    assert candidate(s = "abcdefghijk",t = "abcdefghijkj") == True
    assert candidate(s = "abcdefghijk",t = "abc") == False
    assert candidate(s = "abcd",t = "abx") == False
    assert candidate(s = "abcdefghij",t = "abcdefghijabc") == False
    assert candidate(s = "algorithm",t = "alorhythm") == False
    assert candidate(s = "example",t = "exmple") == True
    assert candidate(s = "abcd",t = "dcba") == False
    assert candidate(s = "abcd",t = "abfd") == True
    assert candidate(s = "abcdefghij",t = "abcdefghijab") == False
    assert candidate(s = "a",t = "b") == True
    assert candidate(s = "abcdefgh",t = "abcdefghi") == True
    assert candidate(s = "abcdefghij",t = "abcdefghijx") == True
    assert candidate(s = "abcde",t = "abcde") == False
    assert candidate(s = "abcd",t = "abce") == True
    assert candidate(s = "abcdefghij",t = "abcdefghijabchij") == False
    assert candidate(s = "abcdefghij",t = "abcdefghijac") == False
    assert candidate(s = "abcdefghijk",t = "abcde") == False
    assert candidate(s = "abcdefghijk",t = "abcdefghijabc") == False
    assert candidate(s = "abcdefg",t = "abcdegh") == False
    assert candidate(s = "short",t = "forty") == False
    assert candidate(s = "abcdefghijk",t = "abcdefghjik") == False
    assert candidate(s = "12345",t = "1234") == True
    assert candidate(s = "elephant",t = "eleppant") == True
    assert candidate(s = "abcdefghijk",t = "") == False
    assert candidate(s = "12345",t = "123456") == True
    assert candidate(s = "abcdefghijk",t = "abcdefghijlk") == True
    assert candidate(s = "abcdefgh",t = "abcefg") == False
    assert candidate(s = "hello",t = "h3llo") == True
    assert candidate(s = "abcdefghijk",t = "abcdefghijkk") == True
    assert candidate(s = "abcdefghij",t = "abcdefghijk") == True
    assert candidate(s = "abcdefg",t = "abcdef") == True
    assert candidate(s = "kitten",t = "sitting") == False
    assert candidate(s = "abcdefghijk",t = "abcdefghijkkl") == False
    assert candidate(s = "",t = "abcdefghijk") == False
    assert candidate(s = "distance",t = "distane") == True
    assert candidate(s = "gumbo",t = "sumo") == False
    assert candidate(s = "abcdefghijk",t = "abcdef") == False
    assert candidate(s = "abcdefghi",t = "abcdefghij") == True
    assert candidate(s = "abcdefghijk",t = "bacdefghijk") == False
    assert candidate(s = "123456",t = "12345") == True
    assert candidate(s = "abcdefghijk",t = "abcdefghij") == True
    assert candidate(s = "abcd",t = "abdd") == True
    assert candidate(s = "abcdefghijk",t = "abcdefgh") == False
    assert candidate(s = "abcdefghij",t = "abcdefghixj") == True
    assert candidate(s = "abracadabra",t = "abracadabrA") == True
    assert candidate(s = "accomodate",t = "accommodate") == True
    assert candidate(s = "abcdefghijk",t = "abcdefghijkaa") == False
    assert candidate(s = "abacax",t = "abacaxx") == True
    assert candidate(s = "hello",t = "hallo") == True
    assert candidate(s = "1234567890",t = "12345678901") == True
    assert candidate(s = "abcdefghijk",t = "abcdefghijkabcdefghijkabcdefghijkabcdefghijk") == False
    assert candidate(s = "abcde",t = "abfde") == True
    assert candidate(s = "algorithm",t = "altruistic") == False
    assert candidate(s = "abcdefgh",t = "abcdefg") == True
    assert candidate(s = "abcdefghijk",t = "abcdefghijkabcdefghijk") == False
    assert candidate(s = "abcdefghijk",t = "abcdefghijkabcdefghijkabcdefghijkabcdefghijkabcdefghijkabcdefghijkabcdefghijkabcdefghijk") == False
    assert candidate(s = "flaw",t = "lawn") == False
    assert candidate(s = "aaaaaa",t = "aaaaa") == True
    assert candidate(s = "abcdefghijk",t = "abcdefghijkabcdefghijkabcdefghijkabcdefghijkabcdefghijk") == False
    assert candidate(s = "qwertyuiop",t = "qwertyuiopo") == True
    assert candidate(s = "abcdefghijk",t = "abcdefgijk") == True
    assert candidate(s = "mississippi",t = "mississipp") == True
    assert candidate(s = "abcdefghijk",t = "abcdefghijkabcdefghijkabcdefghijkabcdefghijkabcdefghijkabcdefghijkabcdefghijk") == False
    assert candidate(s = "0123456789",t = "1234567890") == False
    assert candidate(s = "karolin",t = "kathrin") == False
    assert candidate(s = "abcdefghijk",t = "abcdefghiij") == False
    assert candidate(s = "phoneme",t = "phonam") == False
    assert candidate(s = "abcdefghijk",t = "abcdefghijak") == True
    assert candidate(s = "racecar",t = "racecer") == True
    assert candidate(s = "abcde",t = "abc") == False
    assert candidate(s = "abcdefghijk",t = "abcdefghijkg") == True
    assert candidate(s = "xylophone",t = "xyophone") == True
    assert candidate(s = "algorithm",t = "altrithm") == False
    assert candidate(s = "abcd",t = "") == False
    assert candidate(s = "abcdefghij",t = "abcdefghiabc") == False
    assert candidate(s = "interspecies",t = "interpres") == False
    assert candidate(s = "mississippi",t = "mssissippi") == True
    assert candidate(s = "mississippi",t = "mississsippi") == True
    assert candidate(s = "abcdefghij",t = "abcdefghj") == True
    assert candidate(s = "algorithm",t = "altrithem") == False
    assert candidate(s = "supercalifragilisticexpialidocious",t = "superduperfragilisticexpialidocious") == False
    assert candidate(s = "intention",t = "execution") == False
    assert candidate(s = "abcdefgh",t = "abcefgh") == True
    assert candidate(s = "computer",t = "comuter") == True
    assert candidate(s = "abcdefghijk",t = "abcdefghik") == True
    assert candidate(s = "123456",t = "123457") == True
    assert candidate(s = "abcdefghijk",t = "ab") == False
    assert candidate(s = "abcdefghij",t = "abcdefghija") == True
    assert candidate(s = "umbrella",t = "umbrellaa") == True
    assert candidate(s = "same",t = "same") == False
    assert candidate(s = "a1b2c3",t = "a1b2c4") == True
    assert candidate(s = "abcdefghijk",t = "abcdefghija") == True
    assert candidate(s = "abcdefghijk",t = "bcdefghijk") == True
