# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abcba") == 0
    assert candidate(s = "aabbaa") == 0
    assert candidate(s = "abcdcba") == 0
    assert candidate(s = "abababab") == 1
    assert candidate(s = "a") == 0
    assert candidate(s = "ab") == 1
    assert candidate(s = "noonnoon") == 0
    assert candidate(s = "aabaa") == 0
    assert candidate(s = "aabb") == 1
    assert candidate(s = "racecar") == 0
    assert candidate(s = "abba") == 0
    assert candidate(s = "abcdabcdabcd") == 11
    assert candidate(s = "abc") == 2
    assert candidate(s = "abcd") == 3
    assert candidate(s = "abccba") == 0
    assert candidate(s = "aab") == 1
    assert candidate(s = "abcbm") == 2
    assert candidate(s = "aabbcc") == 2
    assert candidate(s = "mississippi") == 3
    assert candidate(s = "leet") == 2
    assert candidate(s = "abcdefg") == 6
    assert candidate(s = "ababcbabcba") == 2
    assert candidate(s = "abacdcbaabcdeedcba") == 4
    assert candidate(s = "abacdfgdcabaedcba") == 12
    assert candidate(s = "aabcbabcbabcba") == 1
    assert candidate(s = "abaaabaaabaaab") == 1
    assert candidate(s = "abcabcabcabc") == 11
    assert candidate(s = "abcdeedcbaeedcba") == 5
    assert candidate(s = "acbbccaaa") == 3
    assert candidate(s = "aaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbb") == 1
    assert candidate(s = "aabaaabaaabaaa") == 1
    assert candidate(s = "abacdbacabcbaabcbaabcba") == 6
    assert candidate(s = "aabbababaabbaabb") == 4
    assert candidate(s = "abacdbacabcbaab") == 5
    assert candidate(s = "abacba") == 3
    assert candidate(s = "aaaaabaaaabaaabaaa") == 2
    assert candidate(s = "abacdbacabcbaabcbaabcbaabcbaabcba") == 6
    assert candidate(s = "abacdcbaabcdeedcbaabcdeedcba") == 4
    assert candidate(s = "aaaabaaaaa") == 1
    assert candidate(s = "noonmoonnoon") == 3
    assert candidate(s = "abccbaabccba") == 0
    assert candidate(s = "abacabacaba") == 0
    assert candidate(s = "aaaaabbbbb") == 1
    assert candidate(s = "abbbabbabbbabbabbbabbabbbabbbabbb") == 1
    assert candidate(s = "abbaabbabbabba") == 1
    assert candidate(s = "noonnoonnoonnoon") == 0
    assert candidate(s = "abcdcbe") == 2
    assert candidate(s = "ababbbababbbaba") == 0
    assert candidate(s = "abacaba") == 0
    assert candidate(s = "madamracecar") == 1
    assert candidate(s = "abcbac") == 1
    assert candidate(s = "abcdedcbafedcbabcd") == 3
    assert candidate(s = "aaaabaaa") == 1
    assert candidate(s = "aabbaabbaabbaabb") == 1
    assert candidate(s = "abbbabbabbbabbabbbabbabbb") == 1
    assert candidate(s = "abcbaababcba") == 3
    assert candidate(s = "abbabbaabbabba") == 0
    assert candidate(s = "abacabadabacabadabacabadabacaba") == 0
    assert candidate(s = "abab") == 1
    assert candidate(s = "abcdcbaefghfeabcdcba") == 7
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(s = "racecarabcba") == 1
    assert candidate(s = "xyzyxzyxyzyx") == 3
    assert candidate(s = "aabbccddeeeffffggg") == 6
    assert candidate(s = "levelup") == 2
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 0
    assert candidate(s = "abababababababab") == 1
    assert candidate(s = "abcdeedcba") == 0
    assert candidate(s = "ababababababab") == 1
    assert candidate(s = "noon") == 0
    assert candidate(s = "aaaaaa") == 0
    assert candidate(s = "xyxzyzyxzyxzyx") == 9
    assert candidate(s = "abababababab") == 1
    assert candidate(s = "deeee") == 1
    assert candidate(s = "abcbaabcba") == 0
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 0
    assert candidate(s = "xyzyxzyzyxzyx") == 6
    assert candidate(s = "abcdeedcbaabcdeedcbaabcdeedcbaabcdeedcba") == 0
    assert candidate(s = "zyxxyzyxyzyx") == 2
    assert candidate(s = "abcdabcdabcdabcd") == 15
    assert candidate(s = "level") == 0
    assert candidate(s = "bananaabananabana") == 4
    assert candidate(s = "abcdefghiijihgfedcba") == 17
    assert candidate(s = "aabaabaaa") == 1
    assert candidate(s = "abacdbacabcbaabcbaabcbaabcbaab") == 5
    assert candidate(s = "abcdabcdabcdabcdabcd") == 19
    assert candidate(s = "madam") == 0
    assert candidate(s = "abbbba") == 0
    assert candidate(s = "aaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaa") == 0
    assert candidate(s = "ababababcba") == 2
    assert candidate(s = "rotorcarcarecat") == 10
    assert candidate(s = "abacabadabacaba") == 0
    assert candidate(s = "abababa") == 0
    assert candidate(s = "aabbccddeeefffggg") == 6
    assert candidate(s = "ababbabaababbabaababbab") == 1
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(s = "abacdbacabcbaabcbaabcbaabcba") == 6
    assert candidate(s = "abbabbabb") == 1
    assert candidate(s = "abbbabbbbabb") == 2
    assert candidate(s = "abcbabcba") == 0
    assert candidate(s = "banana") == 1
    assert candidate(s = "abcbddcba") == 5
    assert candidate(s = "abcbaeabcdedcba") == 2
    assert candidate(s = "abcbabcbabcba") == 0
    assert candidate(s = "bcbabbc") == 3
    assert candidate(s = "ababababababababababababab") == 1
    assert candidate(s = "anana") == 0
    assert candidate(s = "aababababababababababababababababababababababababababababababababababababab") == 1
    assert candidate(s = "aabbccddeeffgg") == 6
    assert candidate(s = "abbacdcba") == 3
    assert candidate(s = "aabbccddeeff") == 5
    assert candidate(s = "abaca") == 2
    assert candidate(s = "abacdbacaba") == 4
    assert candidate(s = "madamimadam") == 0
    assert candidate(s = "abcdefghij") == 9
    assert candidate(s = "abcbaabcbaabcbaabcbaabcbaabcba") == 0
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 25
    assert candidate(s = "aabbabba") == 1
    assert candidate(s = "bananaabananabananaabananabanana") == 6
    assert candidate(s = "aabbccddeeefffgggbbb") == 7
    assert candidate(s = "abacdbacabcbaabcbaab") == 5
    assert candidate(s = "racecarannakayak") == 2
    assert candidate(s = "amanaplanacanalpanama") == 0
    assert candidate(s = "aaaaaaaaaaaaaaaaaab") == 1
    assert candidate(s = "noonracecar") == 1
    assert candidate(s = "noonnoonnoon") == 0
    assert candidate(s = "abacdbacabcba") == 6
    assert candidate(s = "noonmoonnoonnoonnoonnoonnoon") == 3
    assert candidate(s = "abcdedcba") == 0
    assert candidate(s = "abcdeedcbabacdcba") == 5
    assert candidate(s = "mamad") == 2
    assert candidate(s = "aaaaaaaaaabbbbbbbbbccccccccc") == 2
    assert candidate(s = "abcdefgfedcbamnoponmabcdedcba") == 2
    assert candidate(s = "noonhighnoon") == 5
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 0
    assert candidate(s = "racecarlevelmadamracecar") == 3
    assert candidate(s = "abacdfgdcaba") == 7
    assert candidate(s = "aabaaabbaabbaabb") == 2
    assert candidate(s = "abcdabcabcde") == 11
    assert candidate(s = "ababababab") == 1
    assert candidate(s = "abcdedcbaabcdedcbaabcdedcba") == 0
    assert candidate(s = "abacdbacabcbaabcba") == 6
    assert candidate(s = "rotor") == 0
    assert candidate(s = "abcadacbdb") == 3
    assert candidate(s = "xyzzazxzyx") == 6
    assert candidate(s = "aabba") == 1
    assert candidate(s = "abcabcabcabcabcabcabcabc") == 23
    assert candidate(s = "ababbbababbbababb") == 1
    assert candidate(s = "aabbccddeeefff") == 5
    assert candidate(s = "abacdbacabcbaabcbaabcbaab") == 5
    assert candidate(s = "abcdcbabcdcbabcdcbabcdcb") == 1
    assert candidate(s = "aabbccddeeefffggghhhhiiiii") == 8
    assert candidate(s = "abcabcabcabcabc") == 14
    assert candidate(s = "abacdcaba") == 0
    assert candidate(s = "aaaaabbbbbccccc") == 2
    assert candidate(s = "aabbababab") == 2
    assert candidate(s = "xyxzyzyx") == 3
    assert candidate(s = "abbab") == 1
