# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abcdef") == False
    assert candidate(s = "zyyzzzzz") == True
    assert candidate(s = "abcdedcba") == True
    assert candidate(s = "a") == True
    assert candidate(s = "abcabcabc") == False
    assert candidate(s = "zzzz") == True
    assert candidate(s = "abcaac") == False
    assert candidate(s = "aa") == True
    assert candidate(s = "") == True
    assert candidate(s = "abcde") == False
    assert candidate(s = "racecar") == True
    assert candidate(s = "abcadcb") == True
    assert candidate(s = "noon") == True
    assert candidate(s = "zyz") == True
    assert candidate(s = "abcd") == False
    assert candidate(s = "aab") == True
    assert candidate(s = "carerac") == True
    assert candidate(s = "aabbcc") == True
    assert candidate(s = "abca") == False
    assert candidate(s = "code") == False
    assert candidate(s = "zyzzyzzyzzyz") == True
    assert candidate(s = "aabbccccddeeeeffffgggghhhhiiiijjjjkkkkllllmmmmnnnnooooppqqrrssttuuvvwwxxyyzzzzz") == True
    assert candidate(s = "twocharacterssameaa") == False
    assert candidate(s = "aaaaaaaaaaaabbbbbbbbbbbccccccccccddddddddddddeeeeeeeeffffffffffgggggggggg") == True
    assert candidate(s = "ivicc") == True
    assert candidate(s = "rotorrotor") == True
    assert candidate(s = "abracadabra") == False
    assert candidate(s = "aabbc") == True
    assert candidate(s = "anagram") == False
    assert candidate(s = "racecarx") == False
    assert candidate(s = "zxcvbnmlkjhgfdsapoiuytrewqqwertyuiopasdfghjklzxcvbnm") == True
    assert candidate(s = "aabbccddeeefffgghhiiiijjjjk") == False
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbbbbbbbbbbccccccccccccccccccccdddddddddddd") == True
    assert candidate(s = "racecarrace") == False
    assert candidate(s = "redder") == True
    assert candidate(s = "aabbccddeee") == True
    assert candidate(s = "aabbccddeeefffg") == False
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == True
    assert candidate(s = "aaabbbbcccccdddddeeeeeffffffggggg") == False
    assert candidate(s = "onecharacterstringa") == False
    assert candidate(s = "xyzzxyz") == True
    assert candidate(s = "aabbccddeeffgghhi") == True
    assert candidate(s = "aabbcccddddeeeefffff") == False
    assert candidate(s = "aabbccdde") == True
    assert candidate(s = "abababababababab") == True
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == True
    assert candidate(s = "xyzzyxw") == True
    assert candidate(s = "deeee") == True
    assert candidate(s = "thisisaverylongstringwithrandomcharactersandthensomeotherrandomcharacters") == False
    assert candidate(s = "aabbccddeeffgghhii") == True
    assert candidate(s = "aabbccddeeffgghhijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == True
    assert candidate(s = "software") == False
    assert candidate(s = "abcdeffedcba") == True
    assert candidate(s = "wasitacaroracatisaw") == True
    assert candidate(s = "abcdefghijklimnopqrstuvwxyz") == False
    assert candidate(s = "level") == True
    assert candidate(s = "aabbccc") == True
    assert candidate(s = "abcdefghijjihgfedcba") == True
    assert candidate(s = "madam") == True
    assert candidate(s = "iviccivic") == True
    assert candidate(s = "abacabadabacaba") == True
    assert candidate(s = "aabbbbccccdddd") == True
    assert candidate(s = "step on no pets") == True
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz") == True
    assert candidate(s = "aabbccddeeffgghhijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzzzz") == True
    assert candidate(s = "abcdefghijkmlkjihgfedcba") == False
    assert candidate(s = "twocharactersdifferentab") == False
    assert candidate(s = "aaabbbcccdddeeefffggghhhhiiiiijjjjjkkkkkkllllllmmmmmmmnnnnnnn") == False
    assert candidate(s = "aabbccddeeffgg") == True
    assert candidate(s = "nonoffnoon") == True
    assert candidate(s = "bbaaaccceee") == False
    assert candidate(s = "racecarcar") == False
    assert candidate(s = "abccba") == True
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == True
    assert candidate(s = "amanaplanacanalpanama") == True
    assert candidate(s = "eleven plus two") == False
    assert candidate(s = "thequickbrownfoxjumpsoverthelazydog") == False
    assert candidate(s = "abcdefg") == False
    assert candidate(s = "abccccba") == True
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == False
    assert candidate(s = "aabbccddeffgghhiii") == False
    assert candidate(s = "repaper") == True
    assert candidate(s = "mamad") == True
    assert candidate(s = "tactcoa") == True
    assert candidate(s = "noonhighnoon") == False
    assert candidate(s = "aabbcccd") == False
    assert candidate(s = "ababababab") == False
    assert candidate(s = "civic") == True
    assert candidate(s = "rotor") == True
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyz") == True
    assert candidate(s = "racecarwithapositionchange") == False
    assert candidate(s = "aaabbbbccccc") == False
    assert candidate(s = "aabbccddeeffgghhijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzzzzz") == False
    assert candidate(s = "abacabadaba") == False
    assert candidate(s = "thisisaverylongstringwithmanycharactersandrepeatedcharacters") == False
    assert candidate(s = "aabbccddeeffgghh") == True
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzz") == True
    assert candidate(s = "aabbccddeeffgghhijjkkllmmnnooppqqrrssttuuvvwwxxyyzzz") == False
    assert candidate(s = "thisisatest") == False
    assert candidate(s = "mississippi") == True
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcba") == True
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == True
    assert candidate(s = "permutation") == False
    assert candidate(s = "deed") == True
    assert candidate(s = "racecarthe") == False
