# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abc",k = 2) == 1
    assert candidate(s = "abababa",k = 4) == 1
    assert candidate(s = "aaaa",k = 2) == 0
    assert candidate(s = "leetcode",k = 8) == 0
    assert candidate(s = "abcd",k = 2) == 1
    assert candidate(s = "racecar",k = 5) == 0
    assert candidate(s = "nnn",k = 1) == 0
    assert candidate(s = "abac",k = 3) == 1
    assert candidate(s = "racecar",k = 1) == 0
    assert candidate(s = "aabbc",k = 3) == 0
    assert candidate(s = "abacdfgdcaba",k = 3) == 1
    assert candidate(s = "palindrome",k = 2) == 4
    assert candidate(s = "aaaabbbbcccc",k = 3) == 0
    assert candidate(s = "aabbccdd",k = 4) == 0
    assert candidate(s = "zzzzzzzzzz",k = 1) == 0
    assert candidate(s = "palindrome",k = 4) == 3
    assert candidate(s = "mississippi",k = 4) == 0
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 13) == 14
    assert candidate(s = "banana",k = 2) == 0
    assert candidate(s = "abcdefg",k = 7) == 0
    assert candidate(s = "aabbaabbaabbaabb",k = 4) == 0
    assert candidate(s = "ababababab",k = 5) == 1
    assert candidate(s = "abcdefg",k = 4) == 2
    assert candidate(s = "aabbccddeeff",k = 6) == 0
    assert candidate(s = "abcdcbaabcdcba",k = 4) == 0
    assert candidate(s = "xyxyxyxyxy",k = 5) == 1
    assert candidate(s = "mamamamamama",k = 5) == 1
    assert candidate(s = "zxyxzyxzyxzyx",k = 4) == 2
    assert candidate(s = "aababababa",k = 5) == 0
    assert candidate(s = "xyxyxyxyxyxyxyxyxy",k = 9) == 1
    assert candidate(s = "zazapapa",k = 3) == 1
    assert candidate(s = "xyxyxyxyx",k = 5) == 0
    assert candidate(s = "abababab",k = 5) == 1
    assert candidate(s = "abcde",k = 3) == 1
    assert candidate(s = "mnopqrstu",k = 5) == 2
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 50) == 0
    assert candidate(s = "abcdedcba",k = 3) == 0
    assert candidate(s = "abcbcaabc",k = 3) == 1
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 26) == 0
    assert candidate(s = "abcdefgabcdefg",k = 2) == 6
    assert candidate(s = "aaaaaaaaaaa",k = 2) == 0
    assert candidate(s = "aabbaa",k = 3) == 0
    assert candidate(s = "racecar",k = 3) == 0
    assert candidate(s = "abcdefghijk",k = 3) == 4
    assert candidate(s = "aabbccddeeffgghh",k = 8) == 0
    assert candidate(s = "xyzzyxzyxzyxzyxzyxzyx",k = 5) == 4
    assert candidate(s = "levelmadammadam",k = 4) == 0
    assert candidate(s = "abcdefghij",k = 5) == 3
    assert candidate(s = "abcdabcdabcd",k = 3) == 3
    assert candidate(s = "noonnoonnoon",k = 6) == 0
    assert candidate(s = "aaaaaaaaaa",k = 5) == 0
    assert candidate(s = "banana",k = 3) == 1
    assert candidate(s = "noonnoonnoon",k = 4) == 0
    assert candidate(s = "racecar",k = 2) == 3
    assert candidate(s = "abacdefghijklmnopqrstuvwxyz",k = 26) == 1
    assert candidate(s = "xyzyxzyzxzyx",k = 6) == 0
    assert candidate(s = "abcbabc",k = 3) == 0
    assert candidate(s = "aabbaa",k = 2) == 1
    assert candidate(s = "aaaaabbbbb",k = 2) == 0
    assert candidate(s = "abccba",k = 1) == 0
    assert candidate(s = "abcbabcba",k = 4) == 1
    assert candidate(s = "abcdefghi",k = 3) == 3
    assert candidate(s = "abcdefgh",k = 8) == 0
    assert candidate(s = "abcdefghi",k = 9) == 0
    assert candidate(s = "xyzyzyzyzyzyz",k = 3) == 0
    assert candidate(s = "abcdefg",k = 3) == 2
    assert candidate(s = "aabaaa",k = 2) == 0
    assert candidate(s = "abcdefg",k = 1) == 3
    assert candidate(s = "ababab",k = 2) == 0
    assert candidate(s = "abcdabc",k = 3) == 1
    assert candidate(s = "xyzxyzxyz",k = 3) == 2
    assert candidate(s = "abccccba",k = 2) == 2
    assert candidate(s = "mississippi",k = 3) == 1
    assert candidate(s = "zzzzzzzzzz",k = 5) == 0
    assert candidate(s = "abababababababababab",k = 10) == 0
    assert candidate(s = "ababababa",k = 5) == 0
    assert candidate(s = "abacabadabacaba",k = 7) == 0
    assert candidate(s = "abccccba",k = 3) == 0
    assert candidate(s = "abcdefghi",k = 5) == 2
    assert candidate(s = "abacaxaba",k = 4) == 1
    assert candidate(s = "aababbaab",k = 4) == 0
    assert candidate(s = "aaaaabbbbbcccccddddd",k = 10) == 0
    assert candidate(s = "racecarannakayak",k = 4) == 1
    assert candidate(s = "abbaabba",k = 4) == 0
    assert candidate(s = "abacaxabac",k = 5) == 1
    assert candidate(s = "zzzzzzzzz",k = 5) == 0
    assert candidate(s = "aaaaabbbbb",k = 5) == 0
    assert candidate(s = "abcdabcdabcd",k = 4) == 2
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba",k = 26) == 0
