# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(expression = "!(!(t))") == True
    assert candidate(expression = "|(t,t,t)") == True
    assert candidate(expression = "|(f,f,f,t)") == True
    assert candidate(expression = "&(t,t,t,t,t,t)") == True
    assert candidate(expression = "!(&(&(t,f),|(t,t)))") == True
    assert candidate(expression = "&(|(f,t),&(t,f))") == False
    assert candidate(expression = "!(|(t,t))") == False
    assert candidate(expression = "|(&(t,f),&(f,t))") == False
    assert candidate(expression = "!(&(f,t))") == True
    assert candidate(expression = "|(f,t,f,t)") == True
    assert candidate(expression = "!(f)") == True
    assert candidate(expression = "&(f,t)") == False
    assert candidate(expression = "&(!(t),f)") == False
    assert candidate(expression = "!(&(|(f),&(f,t)))") == True
    assert candidate(expression = "&(t,|(f,f,f,t),!(&(f,t)))") == True
    assert candidate(expression = "&(t,t,t,t)") == True
    assert candidate(expression = "&(|(f))") == False
    assert candidate(expression = "!(&(|(t),|(f)),&(t,f))") == True
    assert candidate(expression = "|(f,f,f,f,f,f)") == False
    assert candidate(expression = "t") == True
    assert candidate(expression = "|(t,f)") == True
    assert candidate(expression = "f") == False
    assert candidate(expression = "|(|(t,f),&(f,f))") == True
    assert candidate(expression = "!(t)") == False
    assert candidate(expression = "|(&(t,f),t)") == True
    assert candidate(expression = "!(!(!(t)))") == False
    assert candidate(expression = "|(&(f,t),|(t,f))") == True
    assert candidate(expression = "&(|(t,f),&(f,t),|(t,t),&(f,f))") == False
    assert candidate(expression = "|(t,f,t,f)") == True
    assert candidate(expression = "&(t,t,t)") == True
    assert candidate(expression = "&(|(t,f),|(f,t))") == True
    assert candidate(expression = "|(f,&(t,f),|(f,f))") == False
    assert candidate(expression = "&(|(t,f),&(f,t))") == False
    assert candidate(expression = "|(&(t,f),|(t,t))") == True
    assert candidate(expression = "|(f,!(t),&(|(f,f),|(t,t)))") == False
    assert candidate(expression = "&(|(|(|(t,f),f),t),!(f),&(t,!(f)))") == True
    assert candidate(expression = "|(&(t,|(f,f),t),&(f,!(t),t),|(t,f,f))") == True
    assert candidate(expression = "!(&(|(f,t,f),&(t,f)),|(t,t,f))") == True
    assert candidate(expression = "&(|(t,&(f,f),t),&(f,|(t,f),t),|(&(f,t),f))") == False
    assert candidate(expression = "|(&(t,|(f,f,f)),!(|(t,t,t)),&(f,f))") == False
    assert candidate(expression = "&(|(&(t,f),&(f,f)),&(t,!(t)),f)") == False
    assert candidate(expression = "&(|(f,t),&(t,f),|(f,t),&(t,f),|(f,t),&(t,f),|(f,t),&(t,f))") == False
    assert candidate(expression = "&(f,!(t),|(&(t,!(t)),|(t,f,f,t,f)),&(f,f,t,t,t,t,f,t))") == False
    assert candidate(expression = "&(t,|(f,!(t),&(t,f,t,t),|(f,f,f,f)),&(f,|(t,f,t,t,t)),!(f,|(t,f,f,f,f)),&(t,t,t),t)") == False
    assert candidate(expression = "|(&(t,f),&(f,t),|(t,t),|(f,f),!(t),!(f),&(t,|(t,t)),|(t,&(t,f)))") == True
    assert candidate(expression = "|(&(f,t),&(t,f),&(f,t),&(t,f),&(f,t),&(t,f),&(f,t),&(t,f))") == False
    assert candidate(expression = "|(|(|(|(|(|(|(|(t),f),t),f),f),f),&(t,t,t,t,t,t,t,t),|(t,f,f,t,f),&(f,f,t,t,t,t,f,t),f,t)") == False
    assert candidate(expression = "|(&(t,!(f)),&(f,!(t)),&(t,t),!(f))") == True
    assert candidate(expression = "|(f,!(t),&(t,f),!(f))") == True
    assert candidate(expression = "|(&(f,t),|(t,f),!(f))") == True
    assert candidate(expression = "!(&(|(f,t),&(f,f)),|(t,t,t))") == True
    assert candidate(expression = "&(|(f,f,t),!(t),|(f,f,f),&(|(t,f),f),|(t,t,t))") == False
    assert candidate(expression = "!(&(|(t,f,f),f),|(t,t,t))") == True
    assert candidate(expression = "&(f,!(t),&(t,!(f)),|(f,t))") == False
    assert candidate(expression = "&(|(t,f),|(f,t),&(t,t),|(t,t),&(t,f),|(f,t))") == False
    assert candidate(expression = "!(&(|(f,!(t),&(t,f)),!(|(f,f,t)),&(t,f),|(f,t,t,t),&(t,|(f,f,f),t),&(t,f,f,t),|(t,!(f),f),f,!(t),&(f,t,f),|(t,f,t),f,!(t),&(f,t,f),|(t,f,t),f))") == True
    assert candidate(expression = "!(&(|(&(f,t),f),f))") == True
    assert candidate(expression = "|(f,!(f),&(t,f),|(t,t,f,f),&(t,t,t,t))") == True
    assert candidate(expression = "&(|(f,f,t),!(t),|(f,t,f))") == False
    assert candidate(expression = "!(&(|(&(t,f),&(f,f)),&(t,t),f))") == True
    assert candidate(expression = "&(f,!(t),|(f,f,t),&(t,t,t))") == False
    assert candidate(expression = "&(t,|(f,!(t),&(t,f,t),|(f,f,f)),&(f,|(t,f,t,t)),!(f,|(t,f)))") == False
    assert candidate(expression = "!(&(|(t,f),f),&(t,t,t))") == True
    assert candidate(expression = "&(t,|(f,!(t),&(t,f)),&(f,|(t,f,t)),!(f))") == False
    assert candidate(expression = "&(&(t,t),&(t,|(t,t)),&(t,|(t,|(t,t))),&(t,|(t,|(t,|(t,t)))))") == True
    assert candidate(expression = "!(&(|(f,t),&(t,f)),|(f,f,f,f))") == True
    assert candidate(expression = "&(|(f,f,t),!(t),|(f,f,f))") == False
    assert candidate(expression = "&(f,|(&(f,t),f),|(t,t),!(&(f,t)))") == False
    assert candidate(expression = "!(&(|(|(f,t),f),&(f,t,f,t)),|(f,f,f,f,f,t,t),&(t,t,t,t,t,t,t,t))") == True
    assert candidate(expression = "&(f,!(t),|(&(t,!(t)),|(t,f,f,t,f)),&(f,f,t,t,t,t),&(t,t,t,t,t,t,t,t),f)") == False
    assert candidate(expression = "&(|(|(|(f),f),t),&(t,f,t),!(f))") == False
    assert candidate(expression = "!(&(|(t,f),&(f,t)),|(t,t))") == True
    assert candidate(expression = "&(|(t,t,t),&(t,t,t),&(f,f,f),|(t,t,t),|(f,f,f))") == False
    assert candidate(expression = "!(&(!(f),t),|(f,&(t,f),f),&(t,f))") == True
    assert candidate(expression = "&(|(t,!(f),&(t,f)),!(|(f,f,t)),&(t,f),|(f,t,t,t))") == False
    assert candidate(expression = "&(|(t,!(f),&(f,t)),|(t,!(t),&(f,f)),|(t,t))") == True
    assert candidate(expression = "|(&(t,!(t)),f,!(f),t)") == True
    assert candidate(expression = "!(&(&(t,t),&(f,f)),|(&(t,f),&(t,t)))") == True
    assert candidate(expression = "&(f,|(&(f,t),f),|(t,t))") == False
    assert candidate(expression = "|(&(t,!(t)),f,!(f),t,!(|(&(f,t),f)))") == True
    assert candidate(expression = "!(&(f,|(&(t,f),f),&(t,t,t)))") == True
    assert candidate(expression = "|(f,&(|(t,f),&(t,f)),|(t,f))") == True
    assert candidate(expression = "&(t,!(f),|(&(t,t),|(f,f)),&(|(t,f),f))") == False
    assert candidate(expression = "!(&(|(&(t,f),t),&(f,|(t,f,t))),|(f,!(t),&(t,f,t)),!(f))") == True
    assert candidate(expression = "&(|(t,f),&(t,f),|(t,t),|(f,f),&(t,!(f)))") == False
    assert candidate(expression = "|(|(|(f),f),f)") == False
    assert candidate(expression = "&(f,!(t),&(t,!(f)),|(f,t),!(&(t,!(t))))") == False
    assert candidate(expression = "|(|(|(|(|(t),f),t),f),&(t,!(f)))") == True
    assert candidate(expression = "|(|(|(|(|(|(|(|(f),f),f),f),f),f),f),f)") == False
    assert candidate(expression = "!(&(|(f,f,f,t),!(t),|(t,t,t)),|(f,&(t,|(f,t),&(f,f)),!(f)))") == True
    assert candidate(expression = "&(|(|(|(|(t),f),t),f),&(t,t,t,t,t,t,t,t),|(t,f,f,t,f),&(f,f,t,t,t,t,f,t),f)") == False
    assert candidate(expression = "|(f,&(|(f,f),t),&(f,|(t,f),f),!(f))") == True
    assert candidate(expression = "&(|(|(t,f),f),&(t,!(f)),!(|(t,f)))") == False
    assert candidate(expression = "&(|(f,f,f),|(t,f,t),&(t,t))") == False
    assert candidate(expression = "&(|(t,&(f,t)),|(t,|(f,f)),&(t,|(t,|(f,t))),|(t,&(f,|(f,t))))") == True
    assert candidate(expression = "!(|(f,&(t,|(t,f)),!(t)))") == False
    assert candidate(expression = "!(&(|(|(|(|(f),t),f),t),&(t,f,t),!(f),|(t,f)))") == True
    assert candidate(expression = "!(&(|(t,f),&(f,f)),!(|(t,t,t,t)))") == True
    assert candidate(expression = "&(|(f,f,t),&(f,f,f),!(t),|(t,f,f,f,t),&(f,t,t,f))") == False
    assert candidate(expression = "!(&(|(&(t,|(f,t)),t),&(f,!(t),t)),|(t,!(f),&(f,f)))") == True
    assert candidate(expression = "&(|(f,f,f,t),|(t,f,t,f),&(t,t,t,t))") == True
    assert candidate(expression = "|(f,&(t,|(f,t),&(f,f)),!(f))") == True
    assert candidate(expression = "|(|(|(|(|(|(|(t),f),t),f),f),f),&(t,t,t,t,t,t,t,t),&(t,t,t,t,t,t,t,t))") == True
    assert candidate(expression = "&(|(t,f),!(f),&(t,t,t))") == True
    assert candidate(expression = "|(t,&(|(f,f),&(t,f)),&(t,|(t,f),&(f,f)))") == True
    assert candidate(expression = "!(|(|(|(f,t),t),f),&(f,|(t,!(t),f),&(t,t,t,t,t,t)))") == True
    assert candidate(expression = "!(|(&(f,t),|(t,f),&(f,f),|(t,t),&(t,f),|(f,f)))") == False
    assert candidate(expression = "|(&(t,t,t,t),|(|(f,f),f),&(t,f,f,t,t),!(t))") == True
    assert candidate(expression = "|(&(f,t),&(t,f),|(t,t))") == True
    assert candidate(expression = "|(|(f,f,f),&(t,t,t),!(|(f,f)))") == True
    assert candidate(expression = "!(&(|(&(f,f),t),f),|(f,|(t,f),&(f,t)))") == True
    assert candidate(expression = "|(&(t,t,t,t),|(f,f,f,f),&(t,f,t,f))") == True
    assert candidate(expression = "|(&(t,f,!(t)),&(t,f,t),&(f,!(t)),!(f),t)") == True
    assert candidate(expression = "&(|(|(f,t),t),f),&(f,|(t,!(t),f),&(t,t,t,t,t,t)),!(|(t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t))") == False
    assert candidate(expression = "!(&(t,!(f),&(t,t),|(t,f),&(t,!(t),&(f,f))))") == True
    assert candidate(expression = "!(&(|(f,f),&(t,t),&(t,f)),|(t,!(t),&(t,f)),&(t,t))") == True
    assert candidate(expression = "!(&(|(|(|(|(|(f),t),f),t),&(t,f,t),!(f),|(t,f)),&(f,t,t,f),!(t))") == False
    assert candidate(expression = "|(&(t,f),&(t,t,t),!(f),&(f,!(t)))") == True
    assert candidate(expression = "!(!(!(!(!(t)))))") == False
    assert candidate(expression = "&(|(t,f),|(f,t),&(t,t),|(t,t),&(t,f),|(f,t),!(t),!(f),&(t,|(t,t)),|(t,&(t,f)),&(f,|(t,f)),|(f,|(t,f)))") == False
    assert candidate(expression = "&(f,|(t,|(f,!(t))))") == False
    assert candidate(expression = "|(|(|(|(|(f),f),t),&(t,f,t),!(f),|(t,f)),&(f,t,t,f))") == True
    assert candidate(expression = "!(&(&(t,t),|(f,f),&(f,t)))") == True
    assert candidate(expression = "!(&(|(&(t,f),f),&(t,|(t,f))),|(t,!(f),t))") == True
    assert candidate(expression = "!(&(|(&(t,f),t),&(f,|(t,f))),|(f,!(t)))") == True
    assert candidate(expression = "&(f,&(|(f,f,t),!(t),|(f,f,f)),|(f,&(t,|(f,t),&(f,f)),!(f)),!(&(|(f,f,f,t),!(t),|(t,t,t)),|(f,&(t,|(f,t),&(f,f)),!(f))))") == False
    assert candidate(expression = "|(&(f,t,f),|(t,f,t),&(t,t,t,t,t))") == True
    assert candidate(expression = "|(|(|(t,f),f),&(|(t,t),&(f,t))),!(t)") == True
    assert candidate(expression = "!(|(t,!(t),&(t,!(f))))") == False
    assert candidate(expression = "!(|(&(t,!(t)),&(f,!(f)),&(t,t),!(f)))") == False
