# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(path = "NEESWNWWSNNWNSSSWEWEWEWE") == True
    assert candidate(path = "NNNSSSSSSEEEEEEEWWWWWWWWW") == True
    assert candidate(path = "NEWSNEWS") == True
    assert candidate(path = "EWEWEWEW") == True
    assert candidate(path = "NESWW") == True
    assert candidate(path = "NSSS") == True
    assert candidate(path = "N") == False
    assert candidate(path = "NNSSEEEWWS") == True
    assert candidate(path = "NSSSWEWNNEE") == True
    assert candidate(path = "") == False
    assert candidate(path = "NSNSNSNS") == True
    assert candidate(path = "NNNSSSSS") == True
    assert candidate(path = "NESWNE") == True
    assert candidate(path = "NNESSEWSWNWNWSSSNW") == True
    assert candidate(path = "NS") == True
    assert candidate(path = "NNESSWW") == True
    assert candidate(path = "NENESSWW") == True
    assert candidate(path = "EWE") == True
    assert candidate(path = "NES") == False
    assert candidate(path = "NEWS") == True
    assert candidate(path = "NNNNSSSSWWWWEEEE") == True
    assert candidate(path = "WEWEWEWE") == True
    assert candidate(path = "NWSWEWNWNW") == True
    assert candidate(path = "NNEESSWW") == True
    assert candidate(path = "NNEEESSWWNNNEEESSWWNNNESSWWN") == True
    assert candidate(path = "EEEE") == False
    assert candidate(path = "EESSEENN") == False
    assert candidate(path = "WEWN") == True
    assert candidate(path = "EENW") == False
    assert candidate(path = "NEEEEWWWWSSSSNNN") == True
    assert candidate(path = "ENWSWNESWSWNESWS") == True
    assert candidate(path = "NENWSEWSWESWESWESW") == True
    assert candidate(path = "NNEWSSEESSEENNNWNNNW") == True
    assert candidate(path = "NNNSSSWEWEWESWNWNWNWWSWSWENENE") == True
    assert candidate(path = "ENWNENWENW") == True
    assert candidate(path = "NWSNWSNWSNWSNWS") == True
    assert candidate(path = "EEEEEWWWWWSSSSSNNNNN") == True
    assert candidate(path = "NWNWNWNWNWSWSWSWSW") == False
    assert candidate(path = "NESWWNESWWNESWW") == True
    assert candidate(path = "EESWWNNESWNESESW") == True
    assert candidate(path = "WENWENWENW") == True
    assert candidate(path = "NSEENWNNWSSSWEE") == True
    assert candidate(path = "NNSSEEEWWW") == True
    assert candidate(path = "NEWSNEWSNEWSNEWSNEWS") == True
    assert candidate(path = "SSNNEEWW") == True
    assert candidate(path = "NNWNWSSSWNEEEEEN") == True
    assert candidate(path = "NNESWSWNWNWS") == True
    assert candidate(path = "NNNNSSSSWWWW") == True
    assert candidate(path = "EENWNWSS") == True
    assert candidate(path = "NNNNEEESSEWWNNNNEE") == True
    assert candidate(path = "NESEWNESEWNESEW") == True
    assert candidate(path = "EENNWWSSNNSSEE") == True
    assert candidate(path = "SSSSNNNNEEEEWWWW") == True
    assert candidate(path = "EEEEEEEEEEEEEEEWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSNNNNNNNNNNNNNNN") == True
    assert candidate(path = "NNNSSSNNNSSS") == True
    assert candidate(path = "NEWSNEWSNEWS") == True
    assert candidate(path = "ENSNWNWNWN") == True
    assert candidate(path = "ESSNNWWSSEN") == True
    assert candidate(path = "SWENSWENSWENSWEN") == True
    assert candidate(path = "WESSNNESWWSE") == True
    assert candidate(path = "NENWSWSENENW") == True
    assert candidate(path = "WSEWSEWSEWSEW") == True
    assert candidate(path = "NNNSSSSSSEEWWWW") == True
    assert candidate(path = "WENSNWSWES") == True
    assert candidate(path = "NWWWSSENNE") == True
    assert candidate(path = "NEESWNESWSWN") == True
    assert candidate(path = "WEWNSWESWESWESW") == True
    assert candidate(path = "NNWESWSWSEENW") == True
    assert candidate(path = "WNWSSNSSWEEENEEN") == True
    assert candidate(path = "EWEWEWEWEEWWEWEEWWSWWSW") == True
    assert candidate(path = "NSSSSEEEEWWWNNSNWEEE") == True
    assert candidate(path = "SSENNWESSW") == True
    assert candidate(path = "NEEEEESWWWWNSSSSS") == True
    assert candidate(path = "NNNNNSSSSSAAAABBBB") == True
    assert candidate(path = "NESWNEESWW") == True
    assert candidate(path = "NENWSEWSWENWSEWSW") == True
    assert candidate(path = "NNNNNNNNSSSSSSSSWWWWWWWWEEEEEEEE") == True
    assert candidate(path = "ENENEWNWNWSWSW") == True
    assert candidate(path = "NENENENENESESESESESWSWSWSWSW") == False
    assert candidate(path = "ENEWWNNEWSWE") == True
    assert candidate(path = "NNNNNNNNNN") == False
    assert candidate(path = "ENWESWNESEENWSWEN") == True
    assert candidate(path = "NESESWWSSWNE") == True
    assert candidate(path = "NENENENENEWWWWWW") == True
    assert candidate(path = "NNNEEEESSSNNNWWSW") == True
    assert candidate(path = "NENENENENNENESESWSWWSW") == True
    assert candidate(path = "ENSWNESWNESEWS") == True
    assert candidate(path = "ENWSESWNESWENSWE") == True
    assert candidate(path = "ENEENWNNWSSSSNE") == True
    assert candidate(path = "EEESSSNNNW") == True
    assert candidate(path = "NNNSSSSSSEEEWWWW") == True
    assert candidate(path = "EESNNWWSSEEN") == True
    assert candidate(path = "NNNEEESSEESWWNN") == True
    assert candidate(path = "EENWNNWSSNNWEE") == True
    assert candidate(path = "NEWWNWSSWSEWSSN") == True
    assert candidate(path = "NESESWNESESWNESESW") == True
    assert candidate(path = "NENWSWNWNWSWNWNW") == True
    assert candidate(path = "NENWSESWNESWNES") == True
    assert candidate(path = "NENENNENNE") == False
    assert candidate(path = "NEWSNEWSNEWSNEWS") == True
    assert candidate(path = "NSEWSSEEEWWWNNEENW") == True
    assert candidate(path = "NNWESSSWNE") == True
    assert candidate(path = "ESSSWWNNEEEWWNNSSEEE") == True
    assert candidate(path = "NESWNESWNESW") == True
    assert candidate(path = "NESESWWSWN") == False
    assert candidate(path = "NESWNESESWNESESW") == True
    assert candidate(path = "NENWSEWSWNNWSEWSW") == True
    assert candidate(path = "ENWNNWSSNWNWEE") == True
    assert candidate(path = "NNWSENNWWSSSEEE") == True
    assert candidate(path = "WNWSSNSSWEEENEENE") == True
    assert candidate(path = "NSEWNSSEWW") == True
    assert candidate(path = "ENWSENWSENWSENWS") == True
    assert candidate(path = "SSSSWWWWNNEE") == False
    assert candidate(path = "NSSSWWNEEENNEESSE") == True
    assert candidate(path = "ENWSWWSESNWEN") == True
    assert candidate(path = "NSSSNWWNEEEE") == True
    assert candidate(path = "NNSESSWWNE") == True
    assert candidate(path = "NESWENSWEWNENSWSEWNESW") == True
    assert candidate(path = "WESSNNWESSNNWESSNN") == True
    assert candidate(path = "SSWWSSENNE") == True
    assert candidate(path = "ESWENSWENSWENSWENSWEN") == True
    assert candidate(path = "NESWNSWENSWE") == True
    assert candidate(path = "NESWWSEN") == True
    assert candidate(path = "EWEWNEWEWN") == True
    assert candidate(path = "EENNWWNSSSNEEE") == True
    assert candidate(path = "EESWWNNEWSNEWSNEWS") == True
    assert candidate(path = "WEWNENEWNWNWSWSNEN") == True
    assert candidate(path = "NESWNSWENWEWSWEWNSWEWENWSWEN") == True
    assert candidate(path = "NENWSEWNENWSEWNENWSEW") == True
    assert candidate(path = "WNESSWNESSWNE") == True
    assert candidate(path = "WENWNNWENWSE") == True
    assert candidate(path = "NSEWNNNSSSWEWEWEWWE") == True
    assert candidate(path = "NENWNWNWSENW") == True
    assert candidate(path = "WNEEESSNWWWEN") == True
    assert candidate(path = "EEENNWWWWNEESSS") == True
    assert candidate(path = "SSSSNNNNWWEEEE") == True
    assert candidate(path = "EEENNNEEWWSSSWWN") == True
    assert candidate(path = "EEEEEEEWWWWWWSSSSSSNNNNNN") == True
    assert candidate(path = "EEEEEENNNNNNSSSSSWEWE") == True
    assert candidate(path = "NSSSSWWWWEEEEEENNN") == True
    assert candidate(path = "SSSSEEEEWWWWNNNN") == True
    assert candidate(path = "SSSSSSSSSS") == False
    assert candidate(path = "NSSSWWEENNSSSWWEEN") == True
    assert candidate(path = "EENNWWSSNWNWEEWN") == True
    assert candidate(path = "NENENENE") == False
    assert candidate(path = "NENESWNESE") == True
    assert candidate(path = "ENWSWEWNWSWEWNWS") == True
    assert candidate(path = "NENWSEWSWNESWESW") == True
    assert candidate(path = "WWEENNWEES") == True
    assert candidate(path = "EWEWNEWNWSWE") == True
    assert candidate(path = "NNNSSSSSSSWWWWWWWWWEEEEE") == True
    assert candidate(path = "NWSWNWSWNW") == False
    assert candidate(path = "NNSSWWEENN") == True
    assert candidate(path = "NSEENWNNWSSSWEEE") == True
    assert candidate(path = "NENWSNWSNESW") == True
    assert candidate(path = "NNSWESWESWESWESW") == True
    assert candidate(path = "NESNESNESNESNES") == True
    assert candidate(path = "NESWNNNWWWEES") == True
    assert candidate(path = "SSNNSSNNSS") == True
    assert candidate(path = "NEWSWNNWSSNWNWEE") == True
    assert candidate(path = "NNWNWSSSWNEEE") == True
    assert candidate(path = "NENWNSNS") == True
    assert candidate(path = "EWSWNWESWE") == True
    assert candidate(path = "NNEEWWSS") == True
    assert candidate(path = "SEENENENEWSWSWNENE") == True
    assert candidate(path = "WNWSSNSSSENEEN") == True
    assert candidate(path = "NESESWSEWN") == True
    assert candidate(path = "NNEWSWSEWSSNENW") == True
    assert candidate(path = "EWEWEWEWEW") == True
    assert candidate(path = "SSEWEEWEEE") == True
    assert candidate(path = "NSSSSEEEEEWWWWNNNN") == True
    assert candidate(path = "NNNWWWSSSE") == False
    assert candidate(path = "NSSSNEEEWNWSS") == True
    assert candidate(path = "NESWNESW") == True
    assert candidate(path = "ESESWNEWSWSWNENESE") == True
    assert candidate(path = "NNNWWSSSNE") == True
    assert candidate(path = "NEWSWNESWESWNES") == True
    assert candidate(path = "NNESSEWW") == True
    assert candidate(path = "WEEWEEWEEE") == True
    assert candidate(path = "NENENWENWENWENWENW") == True
    assert candidate(path = "NNSSEEEWWWS") == True
    assert candidate(path = "SWSWSWSWNENENENENE") == True
    assert candidate(path = "SSSEEESSSWWNNN") == True
    assert candidate(path = "NNSSNNSS") == True
    assert candidate(path = "NNSEESSWNW") == True
    assert candidate(path = "NNNSSSWEWEWESWNWNWNWWSWSWENENESESESESNESWENSWEWNENSWSEWNESW") == True
