# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "jjjj",letter = "k") == 0
    assert candidate(s = "foobar",letter = "o") == 33
    assert candidate(s = "mississippi",letter = "i") == 36
    assert candidate(s = "python",letter = "y") == 16
    assert candidate(s = "abcabcabc",letter = "a") == 33
    assert candidate(s = "hello",letter = "l") == 40
    assert candidate(s = "world",letter = "d") == 20
    assert candidate(s = "zzzz",letter = "z") == 100
    assert candidate(s = "b",letter = "a") == 0
    assert candidate(s = "solution",letter = "o") == 25
    assert candidate(s = "aaaaabbbbb",letter = "b") == 50
    assert candidate(s = "a",letter = "a") == 100
    assert candidate(s = "abcdefg",letter = "h") == 0
    assert candidate(s = "zzzzzz",letter = "z") == 100
    assert candidate(s = "aabbcc",letter = "b") == 33
    assert candidate(s = "aabbccddeeff",letter = "c") == 16
    assert candidate(s = "abcdefg",letter = "a") == 14
    assert candidate(s = "zzzzzzzzz",letter = "z") == 100
    assert candidate(s = "abcdefg",letter = "x") == 0
    assert candidate(s = "characterization",letter = "c") == 12
    assert candidate(s = "examplewithrepeatedletterzzzz",letter = "z") == 13
    assert candidate(s = "qwertypoiuytrewqasdfghjklzxcvbnmasdfghjklzxcvbnm",letter = "q") == 4
    assert candidate(s = "oneletterone",letter = "n") == 16
    assert candidate(s = "parameter",letter = "r") == 22
    assert candidate(s = "alphabet",letter = "p") == 12
    assert candidate(s = "determinethepercentage",letter = "e") == 31
    assert candidate(s = "programming",letter = "m") == 18
    assert candidate(s = "supercalifragilisticexpialidocious",letter = "i") == 20
    assert candidate(s = "abracadabra",letter = "a") == 45
    assert candidate(s = "development",letter = "e") == 27
    assert candidate(s = "abcdefghij",letter = "a") == 10
    assert candidate(s = "abcdefghijk",letter = "a") == 9
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzz",letter = "z") == 100
    assert candidate(s = "abcdefghij",letter = "j") == 10
    assert candidate(s = "visualization",letter = "i") == 23
    assert candidate(s = "programming",letter = "g") == 18
    assert candidate(s = "development",letter = "d") == 9
    assert candidate(s = "charactercounting",letter = "c") == 17
    assert candidate(s = "percentage",letter = "e") == 30
    assert candidate(s = "classification",letter = "f") == 7
    assert candidate(s = "environment",letter = "n") == 27
    assert candidate(s = "xyz",letter = "z") == 33
    assert candidate(s = "charactercountexample",letter = "e") == 14
    assert candidate(s = "testtesttesttest",letter = "t") == 50
    assert candidate(s = "computation",letter = "i") == 9
    assert candidate(s = "performance",letter = "n") == 9
    assert candidate(s = "understanding",letter = "d") == 15
    assert candidate(s = "consistencyiskey",letter = "i") == 12
    assert candidate(s = "xyxzyzyzxzyzyzxzyzyzxzyzyzxzyzyzxzyzyzxzyzyzxzyzyzxzyzyzxzyzyzxzyzyzxzyzyzxzyzyzxzyzyzxzyzyz",letter = "y") == 33
    assert candidate(s = "algorithm",letter = "g") == 11
    assert candidate(s = "representation",letter = "r") == 14
    assert candidate(s = "communication",letter = "m") == 15
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",letter = "z") == 3
    assert candidate(s = "mississippi",letter = "s") == 36
    assert candidate(s = "thisisaverylongstringwithrandomcharacters",letter = "t") == 9
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",letter = "z") == 100
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",letter = "z") == 100
    assert candidate(s = "variable",letter = "b") == 12
    assert candidate(s = "pythonprogramming",letter = "p") == 11
    assert candidate(s = "xyzzxyzz",letter = "z") == 50
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",letter = "a") == 3
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnm",letter = "m") == 3
    assert candidate(s = "xylophone",letter = "p") == 11
    assert candidate(s = "characterization",letter = "t") == 12
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",letter = "z") == 100
    assert candidate(s = "synchronous",letter = "s") == 18
    assert candidate(s = "congratulations",letter = "t") == 13
    assert candidate(s = "mississippi",letter = "x") == 0
    assert candidate(s = "example",letter = "a") == 14
    assert candidate(s = "development",letter = "l") == 9
    assert candidate(s = "averylongstringwithvariouscharacters",letter = "a") == 11
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba",letter = "z") == 3
    assert candidate(s = "thequickbrownfoxjumpsoverthelazydog",letter = "e") == 8
    assert candidate(s = "uniquecharacters",letter = "u") == 12
    assert candidate(s = "hello world",letter = "l") == 27
    assert candidate(s = "hellotheregeneralkenobi",letter = "l") == 13
    assert candidate(s = "asynchronous",letter = "y") == 8
    assert candidate(s = "helloalibabacloud",letter = "a") == 17
    assert candidate(s = "mathematics",letter = "a") == 18
    assert candidate(s = "function",letter = "u") == 12
    assert candidate(s = "expression",letter = "s") == 20
    assert candidate(s = "thisisaverylongstringthatshouldtestthemaximumlengthoftheinputwhichisonehundredcharacters",letter = "s") == 7
    assert candidate(s = "lkjashdflkjhaskldjfhlasjdhflkajshdfjklsahjfdlkjahs",letter = "l") == 14
    assert candidate(s = "xyxyxyxyxyxyxyxyxyxyxyxy",letter = "x") == 50
    assert candidate(s = "programminglanguage",letter = "g") == 21
    assert candidate(s = "abcdefghij",letter = "m") == 0
    assert candidate(s = "percentageletter",letter = "t") == 18
    assert candidate(s = "encyclopedia",letter = "o") == 8
    assert candidate(s = "alphanumericcharacters123",letter = "a") == 16
    assert candidate(s = "thisisaverylongstringindeedtoseeifitworks",letter = "s") == 12
    assert candidate(s = "alphabet",letter = "z") == 0
    assert candidate(s = "programminglanguage",letter = "a") == 15
    assert candidate(s = "statistics",letter = "s") == 30
    assert candidate(s = "xylophone",letter = "x") == 11
    assert candidate(s = "encyclopedia",letter = "e") == 16
    assert candidate(s = "nolettersmatch",letter = "z") == 0
    assert candidate(s = "elephant",letter = "l") == 12
    assert candidate(s = "character",letter = "c") == 22
    assert candidate(s = "banana",letter = "a") == 50
    assert candidate(s = "congratulations",letter = "o") == 13
    assert candidate(s = "longstringwithvariouscharacters",letter = "v") == 3
    assert candidate(s = "algorithm",letter = "l") == 11
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc",letter = "b") == 33
    assert candidate(s = "alabama",letter = "b") == 14
    assert candidate(s = "zzzzzzzzzz",letter = "z") == 100
    assert candidate(s = "sequence",letter = "q") == 12
    assert candidate(s = "banana",letter = "n") == 33
