# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "zyxwvutsrqponmlkjihgfedcba") == 338
    assert candidate(s = "mnopqr",t = "qrpmno") == 18
    assert candidate(s = "abcde",t = "edbac") == 12
    assert candidate(s = "abcxyz",t = "xyzabc") == 18
    assert candidate(s = "qrstuv",t = "vutsrq") == 18
    assert candidate(s = "abc",t = "bac") == 2
    assert candidate(s = "mnopqr",t = "rqponm") == 18
    assert candidate(s = "uvwxy",t = "yxuvw") == 12
    assert candidate(s = "mnopqr",t = "qrponm") == 18
    assert candidate(s = "a",t = "a") == 0
    assert candidate(s = "abcd",t = "dcba") == 8
    assert candidate(s = "xyz",t = "zyx") == 4
    assert candidate(s = "ab",t = "ba") == 2
    assert candidate(s = "mnopqrstuvwxyzabcdefghijkl",t = "qrstuvwxyzabcdefghijklmno") == 154
    assert candidate(s = "abcdpqrs",t = "srqpdcba") == 32
    assert candidate(s = "qazwsxedcrfvtgbyhnujmiklop",t = "plokmijnuhbygvtfcrdxeszwaq") == 338
    assert candidate(s = "fedcba",t = "abcdef") == 18
    assert candidate(s = "lkjhgfedcba",t = "abcdefghjkl") == 60
    assert candidate(s = "abcdefg",t = "gfedcba") == 24
    assert candidate(s = "abcdfghijklmnopqrstuvwxyzef",t = "efghijklmnopqrstuvwxyzabcd") == 198
    assert candidate(s = "lmnopqrstuvwxy",t = "yxwvutsrqponml") == 98
    assert candidate(s = "mnopqrstu",t = "tusrqpmon") == 40
    assert candidate(s = "ijklmnopqr",t = "rqponmlkji") == 50
    assert candidate(s = "abcdefghijl",t = "ljihgfedcba") == 60
    assert candidate(s = "hijklmnop",t = "ponmlkjih") == 40
    assert candidate(s = "qzjrwbyfc",t = "bfywzcrjq") == 38
    assert candidate(s = "xyzabcdefghijklmnopqrstuvw",t = "wvutsrqponmlkjihgfedcbazyx") == 338
    assert candidate(s = "abcdefghijklmnop",t = "ponmlkjihgfedcba") == 128
    assert candidate(s = "abcdefghij",t = "ghijabcdfe") == 48
    assert candidate(s = "abcdefghijk",t = "kjihgfedcba") == 60
    assert candidate(s = "zabcdefghijklmnopqrstuvwxy",t = "yzxwvutsrqponmlkjihgfedcba") == 314
    assert candidate(s = "jklmnopqrabcdefghistuvwxy",t = "tuvxyabcdefghistuvwklmnoj") == 267
    assert candidate(s = "abcdefghij",t = "jabcdefghi") == 18
    assert candidate(s = "pqrstuv",t = "vutsrqp") == 24
    assert candidate(s = "vwxyzabcdefghijklmnopqrst",t = "rstqponmlkjihgfedcbazyxwv") == 312
    assert candidate(s = "asdfghjkl",t = "lkjhgfdsa") == 40
    assert candidate(s = "abcdefghij",t = "ihgfedcbaj") == 40
    assert candidate(s = "abcdefghij",t = "jihgfedcba") == 50
    assert candidate(s = "abcdef",t = "fedcba") == 18
    assert candidate(s = "pqrstuvw",t = "vutsrqwp") == 26
    assert candidate(s = "abcdefghijk",t = "fedcbaghijk") == 18
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "abcdefghijklmnopqrstuvwxyza") == 26
    assert candidate(s = "xyzabcdefghijklmnopqrstuvw",t = "vutsrqponmlkjihgfedcbazyxw") == 312
    assert candidate(s = "thequickbrown",t = "nkbrohwiqctue") == 82
    assert candidate(s = "lmnopqrt",t = "tqrponml") == 32
    assert candidate(s = "abcdefghijkmnopqrstuvwxyzl",t = "lmnopqrstuvwxyzabcdefghijk") == 330
    assert candidate(s = "xyzuvw",t = "uvwzyx") == 18
    assert candidate(s = "abcdefghilmnopqrstuvwxyzjk",t = "jklmnopqrstuvwxyzabcdefghi") == 306
    assert candidate(s = "abc",t = "cba") == 4
    assert candidate(s = "abcdefghijkmnopqrstvuwxyz",t = "xyzuvwtpqrsmnkjihgfedcba") == 297
    assert candidate(s = "acdefghijklmnopqrstuvwxyzb",t = "bzabcdefghijklmnopqrstuvwxy") == 141
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "qpjohuxivtnrckdsmgflweazyb") == 246
    assert candidate(s = "abcdxyz",t = "zyxcba") == 21
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "qrstuvwxyabcdefghijklmnop") == 288
    assert candidate(s = "abcdefghijkmnopqrstuvwxyzl",t = "lnopqrstuvwxyzabcdefghijkml") == 337
    assert candidate(s = "qrstuv",t = "tvusqr") == 18
    assert candidate(s = "abcdefghijk",t = "kabcdefghij") == 20
    assert candidate(s = "rplumabc",t = "mucrlpba") == 22
    assert candidate(s = "mnopqrstuvwxyzabcde",t = "edcbamnopqrstuvwxyz") == 140
    assert candidate(s = "aeiouy",t = "uyioea") == 16
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "bacdefghijklmnopqrstuvwxyza") == 28
    assert candidate(s = "abcdefghijklmnopqrstuvwxy",t = "yxwvutsrqponmlkjihgfedcba") == 312
    assert candidate(s = "zxcvbnm",t = "mnbvcxz") == 24
    assert candidate(s = "lkjhgfdsapoiuytrewqmnbvcxz",t = "xcvbnmqwertypoiuytsdfghjkl") == 318
    assert candidate(s = "xyzxyz",t = "zzzyyx") == 15
    assert candidate(s = "xyzabcdefghijklmnopqrstuvw",t = "stuvwxabcdefghijklmnopqrzy") == 210
    assert candidate(s = "abcdefghij",t = "ijhgfedcba") == 50
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnm",t = "mnbvcxzlkjhgfdsapoiuytrewq") == 338
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "bcazdefghijklmnopqrstuvwxy") == 48
    assert candidate(s = "tuvrstxyzwqpomnlkjihgfedcba",t = "cabfedghijklmnopqrstuvwxyz") == 338
    assert candidate(s = "abcxyz",t = "zyxcba") == 18
    assert candidate(s = "qwertyuiop",t = "poiuytrewq") == 50
    assert candidate(s = "abcdefghijk",t = "kijhgfedcba") == 60
    assert candidate(s = "abcdefghijlm",t = "mljihgfedcba") == 72
    assert candidate(s = "mnopqrstu",t = "ustqrpmno") == 40
    assert candidate(s = "abcdefgh",t = "hgfedcba") == 32
    assert candidate(s = "qrstuvw",t = "tuvwsrq") == 24
    assert candidate(s = "abcdefghijklm",t = "mlkjihgfedcba") == 84
    assert candidate(s = "abcdefghij",t = "abcdefghij") == 0
    assert candidate(s = "ghijklmn",t = "nmlkjihg") == 32
