# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(votes = ['ABC', 'ACB', 'ABC', 'ACB', 'ACB']) == "ACB"
    assert candidate(votes = ['WXYZ', 'XYZW']) == "XWYZ"
    assert candidate(votes = ['BCA', 'CAB', 'ACB', 'BAC', 'CBA', 'ABC']) == "ABC"
    assert candidate(votes = ['A', 'B', 'C', 'D', 'E']) == "ABCDE"
    assert candidate(votes = ['ABCDEF', 'BCDEFA', 'CDEFAB', 'DEFABC', 'EFABCD', 'FABCDE']) == "ABCDEF"
    assert candidate(votes = ['BCA', 'CAB', 'CBA', 'ABC', 'ACB', 'BAC']) == "ABC"
    assert candidate(votes = ['A', 'A', 'A', 'A', 'A']) == "A"
    assert candidate(votes = ['BCA', 'CAB', 'ACB', 'ABC', 'ABC', 'ACB']) == "ACB"
    assert candidate(votes = ['A', 'A', 'A', 'A']) == "A"
    assert candidate(votes = ['ZMNAGUEDSJYLBOPHRQICWFXTVK']) == "ZMNAGUEDSJYLBOPHRQICWFXTVK"
    assert candidate(votes = ['RGB', 'GBR', 'BRG', 'RBB', 'BBR', 'RBB', 'RRG', 'GRR']) == "RBG"
    assert candidate(votes = ['ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'ZYXWVUTSRQPONMLKJIHGFEDCBA']) == "AZBYCXDWEVFUGTHSIRJQKPLOMN"
    assert candidate(votes = ['BCA', 'CAB', 'ABC', 'ACB', 'BAC']) == "ABC"
    assert candidate(votes = ['GHIJKL', 'LKHGJI', 'HKLGJI', 'IGJLKH', 'JIGKHL', 'KGLHJI', 'GHILJK']) == "GHKILJ"
    assert candidate(votes = ['LMNO', 'NOLM', 'OLMN', 'MNLO', 'LNMO', 'ONML', 'MLOL', 'LONM', 'MOLN', 'NOML', 'OMNL', 'LMON', 'NLMO', 'OMLN', 'LMNO', 'NOLM', 'OLMN', 'MNLO', 'LNMO', 'ONML', 'MLOL', 'LONM', 'MOLN', 'NOML', 'OMNL']) == "OLMN"
    assert candidate(votes = ['ABCDEFGH', 'BCDEFGHA', 'CDEFGHAB', 'DEFGHABC', 'EFGHABCD', 'FGHABCDE', 'GHABCDEF', 'HABCDEFG']) == "ABCDEFGH"
    assert candidate(votes = ['ABCDEFG', 'GFEDCBA', 'FBCDEAG', 'BCDEAFG', 'CDEABGF', 'DEABCFG', 'EABCDFG']) == "BCEDAFG"
    assert candidate(votes = ['ABCD', 'BCDA', 'CDAB', 'DABC', 'ABCD', 'ABCD']) == "ABCD"
    assert candidate(votes = ['QWOP', 'WOPQ', 'OPQW', 'PQWO', 'QWPO', 'WPOQ', 'OPWQ', 'POWQ']) == "PWOQ"
    assert candidate(votes = ['QWERTYUIOPASDFGHJKLZXCVBNM', 'MNBVCXZLKJHGFDSAPOIUYTREWQ', 'QWERTYUIOPASDFGHJKLZXCVBNM', 'MNBVCXZLKJHGFDSAPOIUYTREWQ', 'QWERTYUIOPASDFGHJKLZXCVBNM', 'MNBVCXZLKJHGFDSAPOIUYTREWQ', 'QWERTYUIOPASDFGHJKLZXCVBNM', 'MNBVCXZLKJHGFDSAPOIUYTREWQ', 'QWERTYUIOPASDFGHJKLZXCVBNM', 'MNBVCXZLKJHGFDSAPOIUYTREWQ']) == "MQNWBERVCTXYUZILKOJPAHGSDF"
    assert candidate(votes = ['MNO', 'OMN', 'NMO', 'MON', 'NMN', 'OMM', 'NMM', 'MMM']) == "MNO"
    assert candidate(votes = ['UVWXYZ', 'VWXYZU', 'WXYZUV', 'XYZUVW', 'YZUVWX', 'ZUVWXY', 'UVWXYZ', 'VWXYZU', 'WXYZUV', 'XYZUVW', 'YZUVWX', 'ZUVWXY', 'UVWXYZ', 'VWXYZU', 'WXYZUV', 'XYZUVW', 'YZUVWX', 'ZUVWXY', 'UVWXYZ']) == "UVWXYZ"
    assert candidate(votes = ['MATH', 'TEAM', 'META', 'HATE', 'HEAT', 'MATE', 'TAME', 'TIME']) == "TMHAEI"
    assert candidate(votes = ['ZYX', 'XYZ', 'YZX', 'XZY', 'YXZ', 'ZXY']) == "XYZ"
    assert candidate(votes = ['PQRST', 'QPRST', 'RQPST', 'SPQRT', 'TQPRS', 'PQRST', 'QPRST', 'RQPST', 'SPQRT', 'TQPRS', 'PQRST', 'QPRST', 'RQPST', 'SPQRT', 'TQPRS']) == "QPRST"
    assert candidate(votes = ['ABCD', 'BCDA', 'CDAB', 'DABC', 'ACBD']) == "ACBD"
    assert candidate(votes = ['PQR', 'QPR', 'RQP', 'PRQ', 'RPQ', 'QRP', 'PQR', 'RQP', 'QRP', 'PRQ']) == "PQR"
    assert candidate(votes = ['ZYX', 'YZX', 'XZY', 'XYZ', 'YXZ', 'ZXY', 'YZX', 'ZXY']) == "ZYX"
    assert candidate(votes = ['ABCDE', 'EDCBA', 'CBADE', 'BCADE', 'DECAB']) == "BCDEA"
    assert candidate(votes = ['ABC', 'BAC', 'BCA', 'CAB', 'CBA', 'ACB', 'BAC', 'CAB', 'CBA', 'BCA', 'ACB', 'CAB', 'CBA', 'BCA', 'ACB', 'BAC', 'CAB', 'CBA', 'BCA', 'ACB', 'BAC', 'CAB', 'CBA', 'BCA', 'ACB']) == "CBA"
    assert candidate(votes = ['ABCD', 'BCDA', 'CDAB', 'DABC']) == "ABCD"
    assert candidate(votes = ['AB', 'BA', 'AB', 'BA', 'AB', 'BA', 'AB', 'BA', 'AB', 'BA', 'AB', 'BA', 'AB', 'BA', 'AB', 'BA', 'AB', 'BA', 'AB', 'BA']) == "AB"
    assert candidate(votes = ['QWERTYUIOPASDFGHJKLZXCVBNM', 'QWERTYUIOPASDFGHJKLZXCVBNM', 'QWERTYUIOPASDFGHJKLZXCVBNM']) == "QWERTYUIOPASDFGHJKLZXCVBNM"
    assert candidate(votes = ['XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY', 'XYZ', 'YZX', 'ZXY']) == "XYZ"
    assert candidate(votes = ['EFGHI', 'FGHIJ', 'GHIJE', 'HIJEF', 'IJEFG', 'EFGHI', 'FGHIJ', 'GHIJE', 'HIJEF', 'IJEFG', 'EFGHI', 'FGHIJ', 'GHIJE', 'HIJEF', 'IJEFG', 'EFGHI', 'FGHIJ', 'GHIJE', 'HIJEF', 'IJEFG', 'EFGHI', 'FGHIJ', 'GHIJE', 'HIJEF', 'IJEFG', 'EFGHI', 'FGHIJ', 'GHIJE', 'HIJEF', 'IJEFG', 'EFGHI', 'FGHIJ', 'GHIJE', 'HIJEF', 'IJEFG']) == "IHGFEJ"
    assert candidate(votes = ['XYZ', 'YZX', 'ZXY', 'YXZ', 'XZY', 'ZYX', 'XYZ', 'YZX']) == "YXZ"
    assert candidate(votes = ['AB', 'BA', 'AB', 'BA', 'AB', 'BA', 'AB', 'BA', 'AB', 'BA', 'AB', 'BA']) == "AB"
    assert candidate(votes = ['TLI', 'LIT', 'ITL', 'TIL', 'ILT', 'LTI', 'TIL', 'LTI', 'ILT', 'TLI']) == "TLI"
    assert candidate(votes = ['QWERTY', 'QWRETY', 'QWRTEY', 'QWRTYE', 'QWRYTE']) == "QWRETY"
    assert candidate(votes = ['ZEBRA', 'BRACE', 'BEZAR', 'RABZE', 'AREBZ', 'ZERBA']) == "BZRAEC"
    assert candidate(votes = ['ZYX', 'YXZ', 'XYZ', 'YZX', 'XZY', 'ZXY']) == "XYZ"
    assert candidate(votes = ['GHIJK', 'HIJKG', 'IJKGH', 'JKGHI', 'KGIJH', 'GHIJK', 'HGIJK', 'IGHJK', 'JGIHK', 'KGIJH']) == "GHIJK"
    assert candidate(votes = ['WXYZ', 'YZWX', 'ZWXY', 'XWYZ', 'WZYX', 'XYZW']) == "WXZY"
    assert candidate(votes = ['PQRSTU', 'QPRSTU', 'QRPTSU', 'QRSTUP', 'QPRTSU', 'QTRPSU', 'QTRSPU', 'QTSRPU', 'QTSPUR', 'QTPRSU', 'QTPSUR', 'QTUSPR', 'QTUSRP', 'QTURPS', 'QTURSP', 'QTUPRS', 'QTUPSR', 'QTRSPU', 'QTSRPU', 'QTRPUS', 'QTRUPS', 'QTPRSU', 'QTPSUR', 'QTUSPR', 'QTURPS', 'QTURSP', 'QTUPRS', 'QTUPSR']) == "QPTRUS"
    assert candidate(votes = ['ABCD', 'DCBA', 'BCAD', 'CADB', 'ACDB', 'DABC', 'BCDA']) == "ABDC"
    assert candidate(votes = ['LOVE', 'VOTE', 'LEVO', 'OVEL', 'VOLE', 'ELOV']) == "VLOET"
    assert candidate(votes = ['LMNO', 'MLON', 'OLNM', 'NOLM', 'ONML', 'MNLO', 'LOMN', 'LONM', 'NMLO', 'OMNL', 'NOLM', 'OLNM']) == "OLNM"
    assert candidate(votes = ['A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'C', 'C', 'C', 'C', 'D', 'D', 'D', 'D', 'E', 'E', 'E', 'E', 'F', 'F', 'F', 'F', 'G', 'G', 'G', 'G', 'H', 'H', 'H', 'H', 'I', 'I', 'I', 'I', 'J', 'J', 'J', 'J', 'K', 'K', 'K', 'K', 'L', 'L', 'L', 'L', 'M', 'M', 'M', 'M', 'N', 'N', 'N', 'N', 'O', 'O', 'O', 'O', 'P', 'P', 'P', 'P', 'Q', 'Q', 'Q', 'Q', 'R', 'R', 'R', 'R', 'S', 'S', 'S', 'S', 'T', 'T', 'T', 'T', 'U', 'U', 'U', 'U', 'V', 'V', 'V', 'V', 'W', 'W', 'W', 'W', 'X', 'X', 'X', 'X', 'Y', 'Y', 'Y', 'Y', 'Z', 'Z', 'Z', 'Z']) == "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    assert candidate(votes = ['ABCDEF', 'FEDCBA', 'DEFABC', 'BCDAFE', 'CBAFED', 'AFECBD', 'BDFECA']) == "BAFDCE"
    assert candidate(votes = ['AC', 'CA', 'AC', 'CA', 'AC', 'CA', 'AC', 'CA', 'AC', 'CA']) == "AC"
    assert candidate(votes = ['LMNO', 'MLNO', 'NOLM', 'OLMN', 'NOML', 'OMNL', 'LONM', 'OLNM', 'MOLN', 'LNOM', 'LOMN', 'MONL', 'NLOM', 'LNMO', 'LNMN', 'OMLN', 'NOLM', 'NLMO', 'MOLN', 'ONLM', 'OMNL', 'LONM', 'OLNM', 'MOLN', 'LNOM', 'LOMN', 'MONL', 'NLOM', 'LNMO', 'LNMN']) == "LONM"
    assert candidate(votes = ['PQRST', 'QPRST', 'RSPTQ', 'TRPQS', 'SQPTR', 'PRQST', 'PQRST', 'RQPTS', 'TQRS', 'SPRQT']) == "PRSTQ"
    assert candidate(votes = ['PQR', 'QRP', 'RPQ', 'PRQ', 'QPR', 'RQP', 'PQR', 'QRP', 'RPQ', 'PRQ', 'QPR', 'RQP']) == "PQR"
    assert candidate(votes = ['ABCDE', 'ACBDE', 'CABDE', 'BCADE', 'DCABE']) == "ACBDE"
    assert candidate(votes = ['XYZ', 'YXZ', 'YZX', 'ZXY', 'ZYX', 'XZY', 'YZX', 'ZYX', 'XYZ', 'YXZ', 'XZY', 'XYZ']) == "XYZ"
    assert candidate(votes = ['FGHIJK', 'GHIJKF', 'HIJKFG', 'IJKFGH', 'JKFGHI', 'KFGHIJ', 'FGHIJK', 'GHIJKF', 'HIJKFG', 'IJKFGH']) == "IHGFJK"
    assert candidate(votes = ['ACBD', 'BDAC', 'CDAB', 'DABC', 'ABCD', 'BACD', 'CABD', 'DABC', 'ACDB', 'BCDA']) == "ABCD"
    assert candidate(votes = ['ABCD', 'ABDC', 'ACBD', 'ACDB', 'ADBC', 'ADCB', 'BACD', 'BADC', 'BCAD', 'BCDA', 'BDAC', 'BDCA', 'CABD', 'CADB', 'CBAD', 'CBDA', 'CDAB', 'CDBA', 'DABC', 'DACB', 'DBAC', 'DBCA', 'DCAB', 'DCBA']) == "ABCD"
    assert candidate(votes = ['UVWX', 'VWXU', 'WXUV', 'XUVW', 'UVWX', 'VWXU', 'WXUV', 'XUVW', 'UVWX', 'VWXU']) == "VUWX"
    assert candidate(votes = ['ZR', 'RZ', 'ZR', 'RZ', 'ZR']) == "ZR"
    assert candidate(votes = ['SUNNY', 'UNNYS', 'NUNYS', 'NNYSU', 'NUYNS', 'USNNY', 'NSUNY']) == "NUSY"
    assert candidate(votes = ['HELLO', 'OLLEH', 'LOHEL', 'LLOEH', 'HLOEL', 'ELOHL', 'ELLOH', 'OLEHL', 'LELOH', 'OHELL']) == "LOEH"
    assert candidate(votes = ['ACB', 'BAC', 'CBA', 'BCA', 'CAB', 'ACB', 'BAC', 'CBA', 'BCA', 'CAB', 'ACB', 'BAC', 'CBA']) == "CBA"
    assert candidate(votes = ['EFGHI', 'FGHIJ', 'GHIJE', 'HIJEF', 'IJEFG', 'JEFGH', 'EFGIH', 'FGHIJ', 'GHIJE', 'HIJEF', 'IJEFG', 'JEFGH', 'EFGIH', 'FGHIJ', 'GHIJE', 'HIJEF', 'IJEFG', 'JEFGH', 'EFGIH', 'FGHIJ', 'GHIJE', 'HIJEF', 'IJEFG', 'JEFGH', 'EFGIH']) == "EFGIJH"
    assert candidate(votes = ['QWRTY', 'QWYRT', 'WQRTY', 'WQYRT', 'RTQWY', 'RTYQW', 'YRQWT', 'YRTQW', 'TWQRY', 'TYWQR']) == "WQRTY"
    assert candidate(votes = ['PYTHON', 'TYHONP', 'YHTNPO', 'HNOTYP', 'NOTYHP', 'OTHNYP']) == "YTHONP"
    assert candidate(votes = ['MNO', 'NOM', 'OMN', 'MON', 'NMO', 'OMN', 'MNO']) == "MNO"
    assert candidate(votes = ['MNO', 'OMN', 'NMO', 'MON', 'NOM', 'OMN']) == "MON"
    assert candidate(votes = ['ABCD', 'DCBA', 'BCDA', 'CBAD', 'ADBC', 'BDAC', 'ACBD', 'CADB', 'DABC', 'DBCA']) == "ADBC"
    assert candidate(votes = ['FGHIJ', 'IJFGH', 'JFGHI', 'HGIJF', 'IGHFJ', 'GFHIJ']) == "IGFJH"
    assert candidate(votes = ['VWXYZ', 'YZWXV', 'ZWXYV', 'XWYZV', 'WZYXV', 'XYZWV', 'VWYZX', 'WVXYZ', 'XYZVW', 'YZXVW', 'ZXYVW', 'VZWXY', 'WXYVZ', 'XVZXY', 'YZVWX', 'ZVXYW', 'VXYWZ', 'XYWVZ', 'YWVZX', 'YVZXW', 'VZXWY', 'ZXWYV', 'XWYVZ']) == "XVYZW"
    assert candidate(votes = ['ABCDE', 'ABCDE', 'ABCDE', 'EABCD', 'DEABC']) == "AEDBC"
    assert candidate(votes = ['UV', 'VU', 'UV', 'UV', 'VU', 'UV', 'UV', 'VU', 'VU', 'VU', 'UV', 'VU', 'VU', 'VU', 'VU', 'VU', 'VU', 'VU', 'VU', 'VU']) == "VU"
