# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(ransomNote = "abc",magazine = "def") == False
    assert candidate(ransomNote = "hello",magazine = "hll") == False
    assert candidate(ransomNote = "mississippi",magazine = "mspsisgp") == False
    assert candidate(ransomNote = "aa",magazine = "ab") == False
    assert candidate(ransomNote = "aabbcc",magazine = "abc") == False
    assert candidate(ransomNote = "construct",magazine = "nstructco") == True
    assert candidate(ransomNote = "abc",magazine = "cba") == True
    assert candidate(ransomNote = "",magazine = "abc") == True
    assert candidate(ransomNote = "hello",magazine = "ohell") == True
    assert candidate(ransomNote = "abc",magazine = "aabbcc") == True
    assert candidate(ransomNote = "world",magazine = "dlrow") == True
    assert candidate(ransomNote = "hello",magazine = "ehlol") == True
    assert candidate(ransomNote = "zzz",magazine = "zzzz") == True
    assert candidate(ransomNote = "abc",magazine = "") == False
    assert candidate(ransomNote = "testcase",magazine = "case测试") == False
    assert candidate(ransomNote = "aa",magazine = "aab") == True
    assert candidate(ransomNote = "a",magazine = "a") == True
    assert candidate(ransomNote = "abcdef",magazine = "fedcba") == True
    assert candidate(ransomNote = "python",magazine = "ypthon") == True
    assert candidate(ransomNote = "world",magazine = "word") == False
    assert candidate(ransomNote = "hello",magazine = "hello") == True
    assert candidate(ransomNote = "a",magazine = "b") == False
    assert candidate(ransomNote = "abc",magazine = "aabbc") == True
    assert candidate(ransomNote = "algorithm",magazine = "logarithm") == True
    assert candidate(ransomNote = "test",magazine = "ttewst") == True
    assert candidate(ransomNote = "xyz",magazine = "abcxyz") == True
    assert candidate(ransomNote = "",magazine = "") == True
    assert candidate(ransomNote = "datastructures",magazine = "structuredatas") == True
    assert candidate(ransomNote = "aaabb",magazine = "aab") == False
    assert candidate(ransomNote = "zzzz",magazine = "zzzzzzzz") == True
    assert candidate(ransomNote = "elephant",magazine = "telephantl") == True
    assert candidate(ransomNote = "example",magazine = "ampleex") == True
    assert candidate(ransomNote = "uniquecharacters",magazine = "charactersunique") == True
    assert candidate(ransomNote = "abcdefghijklmnopqrstuvwxyz",magazine = "zyxwvutsrqponmlkjihgfedcba") == True
    assert candidate(ransomNote = "xylophone",magazine = "phonepolyx") == True
    assert candidate(ransomNote = "zzzzz",magazine = "zzzzzzzzzz") == True
    assert candidate(ransomNote = "aquickbrownfoxjumpsoverthelazydog",magazine = "thequickbrownfoxjumpsoverthelazydog") == False
    assert candidate(ransomNote = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",magazine = "zzzzzyyyyxxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeeeddccbbaa") == True
    assert candidate(ransomNote = "programming",magazine = "gimmnoprramg") == True
    assert candidate(ransomNote = "abcdabcdabcd",magazine = "abcabcabc") == False
    assert candidate(ransomNote = "casecasecase",magazine = "casecase") == False
    assert candidate(ransomNote = "abacabadabacaba",magazine = "aaaaaaaaaabbbbbbbbbbcccccccccc") == False
    assert candidate(ransomNote = "almost",magazine = "almostly") == True
    assert candidate(ransomNote = "abracadabra",magazine = "acabradabra") == True
    assert candidate(ransomNote = "supercalifragilisticexpialidocious",magazine = "supercalifragilisticexpialidocious") == True
    assert candidate(ransomNote = "characters",magazine = "characterscharacters") == True
    assert candidate(ransomNote = "unavailable",magazine = "availableun") == True
    assert candidate(ransomNote = "repeatedletters",magazine = "rreeppddeeaatteedllettterss") == True
    assert candidate(ransomNote = "thedefaultvalue",magazine = "thedefultvalue") == False
    assert candidate(ransomNote = "abcdabcd",magazine = "dcba") == False
    assert candidate(ransomNote = "aabbaabb",magazine = "abababab") == True
    assert candidate(ransomNote = "xyz",magazine = "zyxzyxzyx") == True
    assert candidate(ransomNote = "thisisanadditionaltest",magazine = "thisisanadditionalteest") == True
    assert candidate(ransomNote = "aaaaabbbbcccc",magazine = "abcabcabcabcabc") == True
    assert candidate(ransomNote = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",magazine = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == True
    assert candidate(ransomNote = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",magazine = "zzzyyxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccbbaa") == True
    assert candidate(ransomNote = "pythonprogramming",magazine = "programmingpython") == True
    assert candidate(ransomNote = "algorithm",magazine = "logarithmz") == True
    assert candidate(ransomNote = "aaaaaaabbbbbbb",magazine = "bbbbbbbbaaaaaa") == False
    assert candidate(ransomNote = "longerstringwithmorecharacters",magazine = "longerstringwithmorecharactersandextraletters") == True
    assert candidate(ransomNote = "datastructure",magazine = "structureadta") == True
    assert candidate(ransomNote = "uniqueletters",magazine = "eulinettsqu") == False
    assert candidate(ransomNote = "alabama",magazine = "aalabmmab") == True
    assert candidate(ransomNote = "abcde",magazine = "fghij") == False
    assert candidate(ransomNote = "programming",magazine = "progarmmnig") == True
    assert candidate(ransomNote = "racecar",magazine = "carrace") == True
    assert candidate(ransomNote = "abcdabcd",magazine = "dcbaabcd") == True
    assert candidate(ransomNote = "x",magazine = "y") == False
    assert candidate(ransomNote = "noleftovers",magazine = "noleftovers") == True
    assert candidate(ransomNote = "abracadabra",magazine = "acarambadbr") == False
    assert candidate(ransomNote = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",magazine = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == True
    assert candidate(ransomNote = "abcabcabcabc",magazine = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == False
    assert candidate(ransomNote = "congratulations",magazine = "congratulationsareinorder") == True
    assert candidate(ransomNote = "longerransomnote",magazine = "longerransomnoteandmore") == True
    assert candidate(ransomNote = "lowercaseonly",magazine = "lowercaseonlylowercaseonly") == True
    assert candidate(ransomNote = "thisisaverylongstringthatweneedtocheck",magazine = "thisisaverylongstringthatwehave") == False
    assert candidate(ransomNote = "abcdefghijk",magazine = "kjihgfedcba") == True
    assert candidate(ransomNote = "thequickbrownfoxjumpsoverthelazydog",magazine = "quickbrownfoxjumpsoverthelazydogthe") == True
    assert candidate(ransomNote = "mississippi",magazine = "mmississippi") == True
    assert candidate(ransomNote = "longstringwithmanysamecharacterssssssss",magazine = "sssssssssssssssssssssssssssssssssss") == False
    assert candidate(ransomNote = "unique",magazine = "ueinque") == True
    assert candidate(ransomNote = "qwertyuiopasdfghjklzxcvbnm",magazine = "qwertyuiopasdfghjklzxcvbnm") == True
    assert candidate(ransomNote = "mississippi",magazine = "ppissimiss") == False
    assert candidate(ransomNote = "sampleinput",magazine = "sampleinputandsomeextraletters") == True
    assert candidate(ransomNote = "aabbcc",magazine = "abcabc") == True
    assert candidate(ransomNote = "same",magazine = "same") == True
    assert candidate(ransomNote = "repeatedcharacters",magazine = "repeatedcharacterse") == True
    assert candidate(ransomNote = "abacax",magazine = "abcax") == False
    assert candidate(ransomNote = "unique",magazine = "unqeiu") == True
    assert candidate(ransomNote = "abracadabra",magazine = "aacdrabbra") == False
    assert candidate(ransomNote = "aabbccddeeff",magazine = "fedcba") == False
    assert candidate(ransomNote = "zzzz",magazine = "zzzzzzzzzz") == True
    assert candidate(ransomNote = "mississippi",magazine = "sssinppimm") == False
    assert candidate(ransomNote = "xxyyzz",magazine = "xzyyzzxx") == True
    assert candidate(ransomNote = "mississippi",magazine = "ssssmissipppii") == True
    assert candidate(ransomNote = "mississippi",magazine = "misisapip") == False
    assert candidate(ransomNote = "complexity",magazine = "txicopmlxity") == False
    assert candidate(ransomNote = "onemore",magazine = "onemoreexample") == True
    assert candidate(ransomNote = "thisisaverylongstringthatshouldpass",magazine = "thisisaverylongstringthatshouldpassandmore") == True
    assert candidate(ransomNote = "mississippi",magazine = "ppisissimm") == False
    assert candidate(ransomNote = "banana",magazine = "anbananab") == True
    assert candidate(ransomNote = "programming",magazine = "rgmepnmoainrg") == True
    assert candidate(ransomNote = "construction",magazine = "ncostruticion") == True
    assert candidate(ransomNote = "banana",magazine = "nabnanaa") == True
    assert candidate(ransomNote = "short",magazine = "shortandlong") == True
    assert candidate(ransomNote = "overlap",magazine = "overlaplap") == True
    assert candidate(ransomNote = "aabbcc",magazine = "abcabcabc") == True
    assert candidate(ransomNote = "zxy",magazine = "zyxzyx") == True
    assert candidate(ransomNote = "xylophone",magazine = "enphonxylox") == True
    assert candidate(ransomNote = "hellohellohello",magazine = "hellohellohellobbb") == True
    assert candidate(ransomNote = "single",magazine = "singles") == True
    assert candidate(ransomNote = "thisisaverylongstringthatshouldpass",magazine = "thisisaverylongstringthatshouldpass") == True
    assert candidate(ransomNote = "zzzzzz",magazine = "zzzzzzzzzz") == True
    assert candidate(ransomNote = "abcd",magazine = "dcba") == True
    assert candidate(ransomNote = "mississippi",magazine = "ppisimiss") == False
    assert candidate(ransomNote = "almostthere",magazine = "almostherethere") == True
    assert candidate(ransomNote = "thisisatest",magazine = "thisisnotatest") == True
    assert candidate(ransomNote = "complexity",magazine = "xxxxcomplexityyyyy") == True
    assert candidate(ransomNote = "python",magazine = "nohtyp") == True
    assert candidate(ransomNote = "toolong",magazine = "too") == False
    assert candidate(ransomNote = "a",magazine = "abcdefghijklmnopqrstuvwxyz") == True
    assert candidate(ransomNote = "abracadabra",magazine = "acazabra") == False
    assert candidate(ransomNote = "programming",magazine = "grammproing") == True
    assert candidate(ransomNote = "zapples",magazine = "paplezzzas") == True
    assert candidate(ransomNote = "caseinsensitive",magazine = "CaseInsensitive") == False
    assert candidate(ransomNote = "python",magazine = "typythonn") == True
    assert candidate(ransomNote = "programming",magazine = "progmminglanguage") == False
    assert candidate(ransomNote = "abcdefg",magazine = "gfedcba") == True
    assert candidate(ransomNote = "thisisaverylongstringthatshouldfail",magazine = "thisisaverylongstringthatshoul") == False
    assert candidate(ransomNote = "challenge",magazine = "lengchalleng") == True
    assert candidate(ransomNote = "hellohellohello",magazine = "hellohello") == False
    assert candidate(ransomNote = "thisisaverylongransomnotethatwillsurelymakethetestcaseinteresting",magazine = "thisisaverylongmagazinesamplethatshouldcontainmanyoftheransomletters") == False
    assert candidate(ransomNote = "missingchar",magazine = "missingcha") == False
    assert candidate(ransomNote = "interview",magazine = "vwnteriview") == True
    assert candidate(ransomNote = "repeatedletters",magazine = "repetettadledtresletters") == True
    assert candidate(ransomNote = "aabbccddeeffgg",magazine = "aabbccddeeffgghh") == True
    assert candidate(ransomNote = "repeatedletters",magazine = "lettersrepated") == False
    assert candidate(ransomNote = "abcdabcdabcd",magazine = "abcdabcd") == False
    assert candidate(ransomNote = "racecar",magazine = "racecar") == True
    assert candidate(ransomNote = "programming",magazine = "gnimmargorp") == True
    assert candidate(ransomNote = "aabbc",magazine = "aabbc") == True
