# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "aa",p = "a*") == True
    assert candidate(s = "aab",p = "c*a*b") == True
    assert candidate(s = "ab",p = ".*") == True
    assert candidate(s = "aa",p = "a") == False
    assert candidate(s = "mississippi",p = "mis*is*p*.") == False
    assert candidate(s = "aabbccddeeff",p = "a*b*c*d*e*f*f*") == True
    assert candidate(s = "abababa",p = "(ab)*a") == False
    assert candidate(s = "abcde",p = "a*.*e") == True
    assert candidate(s = "ababcd",p = "a.*a.*d") == True
    assert candidate(s = "aabbbbc",p = "a*b*c") == True
    assert candidate(s = "aaaaaa",p = "a*a*a*a*a*a") == True
    assert candidate(s = "aabb",p = "ab*a*b*") == True
    assert candidate(s = "abcccccaaaa",p = "ab*c*a*.*") == True
    assert candidate(s = "abcdef",p = "abc.*f") == True
    assert candidate(s = "ababab",p = "(ab)*") == False
    assert candidate(s = "ab",p = "a*b*c*d*.*e*") == True
    assert candidate(s = "xaymz",p = "x.*z") == True
    assert candidate(s = "xaybz",p = "xa*y*b*z") == True
    assert candidate(s = "abcdefgh",p = "a*d*fh") == False
    assert candidate(s = "aaa",p = "a*a*a*a*a*a*a*a*a*a*a*a*a*a*a*a*a*a*a*a") == True
    assert candidate(s = "mississippi",p = "mi*ss*is*si*p*i*") == True
    assert candidate(s = "zzzz",p = "z*") == True
    assert candidate(s = "abcdefgh",p = "a.h") == False
    assert candidate(s = "ababab",p = "(ab)*b*") == False
    assert candidate(s = "abcdefgh",p = "a.*h") == True
    assert candidate(s = "mississippi",p = "mi.*is.*p*i") == True
    assert candidate(s = "abcdefgh",p = "abcdefgh") == True
    assert candidate(s = "abcdefg",p = "a*bc.d*efg") == True
    assert candidate(s = "abcdefgh",p = "a*b*c*d*e*f*g*h") == True
    assert candidate(s = "abcdefgh",p = "a*b*c*d*e*f*g*h*") == True
    assert candidate(s = "abcd",p = "a.b.c.d") == False
    assert candidate(s = "aabbcc",p = "a*b*c*c") == True
    assert candidate(s = "abc",p = "abc.") == False
    assert candidate(s = "mississippi",p = "m*is*i*s*i*p*i") == True
    assert candidate(s = "mississippi",p = "m*i*ss*i*p*i*") == False
    assert candidate(s = "abcde",p = "a.*de") == True
    assert candidate(s = "abcdeabcde",p = "abc*de*abc*de*") == True
    assert candidate(s = "abcd",p = "a*b*c*d*") == True
    assert candidate(s = "abcde",p = "a*.b*c*e*") == False
    assert candidate(s = "aabbbcccddd",p = "a*b*c*d*") == True
    assert candidate(s = "abc",p = "a.b.c") == False
    assert candidate(s = "abababab",p = "(ab)*") == False
    assert candidate(s = "hello",p = "he*llo*") == True
    assert candidate(s = "hello",p = "he.*o") == True
    assert candidate(s = "abcd",p = "d*") == False
    assert candidate(s = "abcde",p = "a..de") == True
    assert candidate(s = "abcabcabcabc",p = "(abc)*d") == False
    assert candidate(s = "abcdabcd",p = "abcd*") == False
    assert candidate(s = "aabb",p = "aab*b*") == True
    assert candidate(s = "xyzzy",p = "x*zy") == False
    assert candidate(s = "abcd",p = "a.*d") == True
    assert candidate(s = "xxyyzz",p = "x*y*z*") == True
    assert candidate(s = "abc",p = "a.c") == True
    assert candidate(s = "xyxxyxyx",p = "(xy)*x") == False
    assert candidate(s = "aabbbccc",p = "a*b*c*") == True
    assert candidate(s = "abcabcabcabc",p = "(abc)*") == False
    assert candidate(s = "abcdef",p = "a*bcdef") == True
    assert candidate(s = "aaaab",p = "a*b*") == True
    assert candidate(s = "complex",p = "c*o*m*p*l*e*x*") == True
    assert candidate(s = "aaa",p = "a*a") == True
    assert candidate(s = "xyz",p = "x*y*z*") == True
    assert candidate(s = "abcdefgh",p = "a.*g") == False
    assert candidate(s = "abcde",p = "a*b.c*d*e*") == True
    assert candidate(s = "abcde",p = "a*b*c*d*e*") == True
    assert candidate(s = "zzzzzzzzzzzz",p = "z*z*z*z*z*z*z*z*z*z*z*z*z*z*z*z*z*") == True
    assert candidate(s = "aabbccddeeff",p = "a*b*c*d*e*f*") == True
    assert candidate(s = "hello",p = "he.*") == True
    assert candidate(s = "abcde",p = "a*b*c*d.e") == False
    assert candidate(s = "aaaaabbb",p = "a*b*.*") == True
    assert candidate(s = "aabbccddeeffgghh",p = "a*b*c*d*e*f*g*h*") == True
    assert candidate(s = "abbabb",p = "a*b*b*") == False
    assert candidate(s = "sequence",p = "s.e*q*u*e*n*c*e*") == True
    assert candidate(s = "abcdabcd",p = "a*b*c*d*") == False
    assert candidate(s = "abcdedef",p = "abcd*e*f*") == False
    assert candidate(s = "abcdefgh",p = "a.b.c.d.e.f.g.h") == False
    assert candidate(s = "mississippi",p = "mi.*.pi.*") == True
    assert candidate(s = "hello",p = "he*ll*o") == True
    assert candidate(s = "abcde",p = "a*bc.e*") == True
    assert candidate(s = "aaaab",p = "a*a*a*a") == False
    assert candidate(s = "abcde",p = "a.*e") == True
    assert candidate(s = "aabbb",p = "a*b*b") == True
    assert candidate(s = "regex",p = "r.e*g*e*x*") == True
    assert candidate(s = "abcdef",p = "a*b*c*d*e*f*") == True
    assert candidate(s = "aaaa",p = "a*a*a*a") == True
    assert candidate(s = "teststring",p = "te*t*st*ring") == False
    assert candidate(s = "abcde",p = "a*b*c*de") == True
    assert candidate(s = "bbbac",p = "ba*ac") == False
    assert candidate(s = "aabbccddeeffgg",p = "a*b*c*d*e*f*g*") == True
    assert candidate(s = "abcde",p = "a*bc*de") == True
    assert candidate(s = "xyxyxyxyxyx",p = "x.y.x.y.x.y.x.y.x.y.x") == False
    assert candidate(s = "a",p = "a*a*a*a*") == True
    assert candidate(s = "abababab",p = "a*b*a*b*a*b*a*b") == True
    assert candidate(s = "abcdeabcdeabcde",p = "abc*de*abc*de*abc*de*f*") == True
    assert candidate(s = "abbbba",p = "ab*ba") == True
    assert candidate(s = "teststring",p = "t.*st.*r.*ing") == True
    assert candidate(s = "abcabc",p = "abc*") == False
    assert candidate(s = "abcd",p = "a*b*c*d*.*") == True
    assert candidate(s = "zzzzzzzzzzzz",p = "z*") == True
    assert candidate(s = "mississippi",p = "m.*s*is*p*i*.*") == True
    assert candidate(s = "abcdefgh",p = ".*") == True
    assert candidate(s = "abcdefg",p = ".*f.*") == True
    assert candidate(s = "abccde",p = "abc*d*e") == True
    assert candidate(s = "aabbbccdd",p = "aa*bbb*cc*dd*") == True
    assert candidate(s = "foobar",p = "fo*oba*r") == True
    assert candidate(s = "abcde",p = "a.*f") == False
    assert candidate(s = "aabb",p = "a*b*b*a*") == True
    assert candidate(s = "zabczabcz",p = "z*abc*z*") == False
    assert candidate(s = "aaaabbbb",p = "a*b*b*") == True
    assert candidate(s = "aabbcc",p = "a*b*b*c*c*") == True
    assert candidate(s = "abc",p = "a*b*c*") == True
    assert candidate(s = "abcdeabcdeabcde",p = "abc*de*abc*de*abc*de*") == True
    assert candidate(s = "abcde",p = "a*c*e") == False
    assert candidate(s = "xyzzaz",p = "x*y*.*z*") == True
    assert candidate(s = "ababab",p = "(ab)*b") == False
    assert candidate(s = "abcdef",p = "abc.def") == False
    assert candidate(s = "xyx",p = "x*y*x*") == True
    assert candidate(s = "aaaaaa",p = "a*a*a*a*") == True
    assert candidate(s = "abbb",p = "ab*") == True
    assert candidate(s = "a",p = ".") == True
    assert candidate(s = "abcdexyz",p = "abc.*xyz") == True
    assert candidate(s = "aabbcc",p = "a*b*c*") == True
    assert candidate(s = "leetcode",p = "le.*e.*tcode") == True
    assert candidate(s = "aaa",p = "ab*a*c*a") == True
    assert candidate(s = "abcd",p = "a.d") == False
    assert candidate(s = "xylophone",p = "x.l*o.h.p*ne") == True
    assert candidate(s = "abcde",p = ".*") == True
    assert candidate(s = "abxyzbcd",p = "ab.*bc*d") == True
    assert candidate(s = "zzzzz",p = "z*") == True
    assert candidate(s = "aaa",p = "a*a*") == True
    assert candidate(s = "aaaaaaab",p = "a*a*a*a*a*a*a*b") == True
    assert candidate(s = "hello world",p = "h.*o w*r*d") == False
    assert candidate(s = "abcdefgh",p = "a.*b.*c.*d.*e.*f.*g.*h") == True
    assert candidate(s = "hello",p = "h.l.o") == True
    assert candidate(s = "abcd",p = "a.b*c.d") == False
    assert candidate(s = "abcdefgh",p = "abcdefgh.") == False
    assert candidate(s = "a",p = "ab*a") == False
    assert candidate(s = "patternmatching",p = "pat*tern*m*atching*") == True
    assert candidate(s = "abcabcabc",p = "(abc)*") == False
    assert candidate(s = "ababab",p = "(ab)*ab*") == False
    assert candidate(s = "abcd",p = "a.c*d*") == True
    assert candidate(s = "a",p = ".*") == True
    assert candidate(s = "abcdef",p = "abcd.e*f") == True
    assert candidate(s = "aabb",p = "a*bb") == True
    assert candidate(s = "abcdefgh",p = "abcdefgh*") == True
    assert candidate(s = "aaa",p = "a*a*a*a*a*a*") == True
    assert candidate(s = "aaaaaa",p = "a*a*a*a*a*a*") == True
    assert candidate(s = "abab",p = "(ab)*") == False
    assert candidate(s = "mississippi",p = "mi*s*is*ip*pi*s*") == True
    assert candidate(s = "aaaaab",p = "a*ba*") == True
    assert candidate(s = "abc",p = ".b.") == True
    assert candidate(s = "abcd",p = "a*b.c*d*") == True
