# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(colors = "AABBAABB") == False
    assert candidate(colors = "AAAAAAAAA") == True
    assert candidate(colors = "AAABAAAAABBBB") == True
    assert candidate(colors = "ABABABABAB") == False
    assert candidate(colors = "AABBBBAAA") == False
    assert candidate(colors = "BBBBB") == False
    assert candidate(colors = "BBBAAAABB") == True
    assert candidate(colors = "AAAAAAAA") == True
    assert candidate(colors = "AAAAA") == True
    assert candidate(colors = "AAABBBAAABBBA") == False
    assert candidate(colors = "AAABABB") == True
    assert candidate(colors = "AABBBBAA") == False
    assert candidate(colors = "AAAABBBB") == False
    assert candidate(colors = "BBBBBBBBB") == False
    assert candidate(colors = "ABBBBBBBAAA") == False
    assert candidate(colors = "ABABABABABA") == False
    assert candidate(colors = "ABABABAB") == False
    assert candidate(colors = "AAAAABBAAA") == True
    assert candidate(colors = "AABAABBBBAAA") == False
    assert candidate(colors = "ABABAB") == False
    assert candidate(colors = "BBBAAABB") == False
    assert candidate(colors = "ABAAABAA") == True
    assert candidate(colors = "AA") == False
    assert candidate(colors = "BBBBAAAABBB") == False
    assert candidate(colors = "AAAABBBAA") == True
    assert candidate(colors = "AABBBAAABBB") == False
    assert candidate(colors = "ABABABABABABAB") == False
    assert candidate(colors = "AAABBBAAABBBAABBBAAABBBAABBB") == False
    assert candidate(colors = "AABBABBABBABBABBABBA") == False
    assert candidate(colors = "ABAABAABAABAABAABA") == False
    assert candidate(colors = "BBBBBBBBBBAAAABBB") == False
    assert candidate(colors = "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB") == False
    assert candidate(colors = "AAABAAAABBAAABBBBAAAABBB") == True
    assert candidate(colors = "AABAABAABAABAABAA") == False
    assert candidate(colors = "AABBBAAABBBAABBAAABBBAABB") == False
    assert candidate(colors = "BBBBBBBBBBABBBBBBBBB") == False
    assert candidate(colors = "ABABABABABABABABABABAB") == False
    assert candidate(colors = "ABABABABABABABABABABABABABABABABABAB") == False
    assert candidate(colors = "AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBB") == False
    assert candidate(colors = "AABBBAAABBBAAABBB") == False
    assert candidate(colors = "AABBAABBBAABBBAABBBAABBA") == False
    assert candidate(colors = "ABABABABABABABABABABABABABABABABABABABABAB") == False
    assert candidate(colors = "AAABAAAAAAAAABBBBBBB") == True
    assert candidate(colors = "AAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBB") == True
    assert candidate(colors = "ABABABABABABABABA") == False
    assert candidate(colors = "BBBBBBBBBBAAAAAAAAAAB") == False
    assert candidate(colors = "BBBAAAABBBAAAABBBAAAABBBAAAABBBAAAABBB") == True
    assert candidate(colors = "BBABBABBABBABBABB") == False
    assert candidate(colors = "BAAAAAAAAAABBBBBBBBBB") == False
    assert candidate(colors = "AAABAAABBBAAABBBBAA") == False
    assert candidate(colors = "AABBBAAAABBBAAB") == False
    assert candidate(colors = "AABBAAAABBAAAABB") == True
    assert candidate(colors = "BBBAABBBAAABBBAABBB") == False
    assert candidate(colors = "AAAABBBAAABBBAAABBBAAABBBAAABBBAAABBBAAABBB") == True
    assert candidate(colors = "AAAAAAAAAABBBBBBBBBBB") == False
    assert candidate(colors = "AAAABBBBBBAAAABBBBBB") == False
    assert candidate(colors = "AAAAAABAAAAAABAAAAAAB") == True
    assert candidate(colors = "BBBAAAAAAAAABBBBBB") == True
    assert candidate(colors = "BBABABABABABABABABAB") == False
    assert candidate(colors = "AAABBBAAABBBAAABBBAAABBBAAABBBAAABBB") == False
    assert candidate(colors = "AAAAAAAAAAAAAAAAAAAAAAAAA") == True
    assert candidate(colors = "AAAAAAAABBBBBBBBBB") == False
    assert candidate(colors = "ABBBAAAAABBAAAAAAA") == True
    assert candidate(colors = "BBBAAAABBAAAABBAAAABBAAAABBAAAABB") == True
    assert candidate(colors = "AAAABAAAABBAAAABBAAAABBAAAABBAAAAB") == True
    assert candidate(colors = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA") == True
    assert candidate(colors = "AAAAAAAAAAAAAABBBBBBBBBBBB") == True
    assert candidate(colors = "AAAAAAAAAAAAAAAAA") == True
    assert candidate(colors = "AABBBAAAAABBBBAAA") == True
    assert candidate(colors = "AAAAAAAAAABBBBBBBBBB") == False
    assert candidate(colors = "AAABBBAAAABBBAAABBBAAABBBAA") == True
    assert candidate(colors = "AAABAAAABAAABAAAABAA") == True
    assert candidate(colors = "AAAAAAAAAAAAAAAAAA") == True
    assert candidate(colors = "AAAAAAAAABBBBBBBBAABBBBBBBBA") == False
    assert candidate(colors = "BBBAAAABBBAAAABBB") == True
    assert candidate(colors = "ABABABAAAABBBABAABAB") == True
    assert candidate(colors = "ABBBAAAABBAAAABBBA") == True
    assert candidate(colors = "AAABBBAABBBAAABBBA") == False
    assert candidate(colors = "AAABBBAABBBAABBBAAB") == False
    assert candidate(colors = "AAABBBAAAABBBAAABBBAA") == True
    assert candidate(colors = "ABABABABABABABABABABABABABABABAB") == False
    assert candidate(colors = "BBBAAAABBBAAAABAA") == True
    assert candidate(colors = "AAABBBAAAABBBAAAABBBAAA") == True
    assert candidate(colors = "BBBBBAABAAAAAAABBB") == True
    assert candidate(colors = "AAABBAAAABBAAAABBAAAABBBAAAABB") == True
    assert candidate(colors = "BBBBBAAAAAAAAABBBBB") == True
    assert candidate(colors = "AAAAAAAAABBBBBBBBBBBB") == False
    assert candidate(colors = "BABAABABABABABABAB") == False
    assert candidate(colors = "AAABBBBAABBBBAA") == False
    assert candidate(colors = "BBAAABBBAAABBBAAABB") == True
    assert candidate(colors = "AAABAAABAAABAAABA") == True
    assert candidate(colors = "AAABBBAAABBBAAABBBAAABBBAAABBB") == False
    assert candidate(colors = "BBBBBBBBBB") == False
    assert candidate(colors = "BBAAAABBBAAABBBAAABB") == True
    assert candidate(colors = "AAAAAAAAAABBBBBBBB") == True
    assert candidate(colors = "BBBBBAAAABBBBBBBAAAAA") == False
    assert candidate(colors = "BBBBBAAAABBBBBAAAABBBBBAAAABBBBB") == False
    assert candidate(colors = "AAAAABBBBBAAAAABBBBBAAAAA") == True
    assert candidate(colors = "ABBBAAAABBAAAABBBAABA") == True
    assert candidate(colors = "AAAABBBBAAAABBBBAAAABBBB") == False
    assert candidate(colors = "BBBBAAAABBBBBBBBAAA") == False
    assert candidate(colors = "ABABABABABABABABABABABABABABABABAB") == False
    assert candidate(colors = "BBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBB") == True
    assert candidate(colors = "BBBBBBAAAABBBBBBBBAAA") == False
    assert candidate(colors = "AABAAAAAAABBBBBBBBA") == False
    assert candidate(colors = "BBBAABBBAAAABBBAAABBB") == False
    assert candidate(colors = "ABABABABAAAAAAAABBBBBBBB") == False
    assert candidate(colors = "BBAAAABBBAAAABBAAA") == True
    assert candidate(colors = "BBAABBAAAABBAAAABBBB") == True
    assert candidate(colors = "AAABBBAABBAAABBBAAAAAAABBBB") == True
    assert candidate(colors = "AAAAABBAAAABBAAAAB") == True
    assert candidate(colors = "ABBBAAAABBBBAAA") == False
    assert candidate(colors = "BBBBBBBBBBBBBBBBB") == False
    assert candidate(colors = "BBBBBBAAAAAAAAAA") == True
    assert candidate(colors = "BBAAAABBBAAAABBBAAAABBB") == True
    assert candidate(colors = "ABBBAAAABBBAAAABB") == True
    assert candidate(colors = "BBBBBAABBBBAABBBBAABBBBA") == False
    assert candidate(colors = "BBBBBBBBBBBBBBBBBBBBBBBBB") == False
    assert candidate(colors = "BBBBBBBAAAAAAAAAAAABB") == True
    assert candidate(colors = "AAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBB") == False
    assert candidate(colors = "ABABABABABABABABABABABABABABABABABABABAB") == False
    assert candidate(colors = "BBBBAAAABBBBBAAAABBBBBAAAABB") == False
    assert candidate(colors = "AABAAABAABAAABAAA") == True
    assert candidate(colors = "ABABABABABABABABAB") == False
    assert candidate(colors = "BBBAAAABBAAAABBAAAABBB") == True
    assert candidate(colors = "AAAAAAAAAAAAAAAAABBBBBBBBBBBAAAAAAAAAAAAAAAAABBBBBBBBBBB") == True
    assert candidate(colors = "AABBBAAABBAAAABBAAAAB") == True
    assert candidate(colors = "AAABAAABAAABAAABAAABAAAB") == True
    assert candidate(colors = "ABABABABABABABABABABABABABAB") == False
    assert candidate(colors = "AAAAAABBBBBBAAA") == True
    assert candidate(colors = "BBBAAAABBBAAAABBBAAAABBB") == True
    assert candidate(colors = "ABABABABABABABABABABA") == False
    assert candidate(colors = "AAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBB") == False
    assert candidate(colors = "AAAABBAABBABBAABBBAAA") == True
    assert candidate(colors = "ABAAAABBBBAABBBBAA") == False
    assert candidate(colors = "AAABAAAABBBBAAAABBBBAAAABBBBAAAABBB") == True
    assert candidate(colors = "AAAAAAAAAAAAABBBBBBBBBBBBB") == False
    assert candidate(colors = "AAAAAAAAAAAAAAAABBBBBBBBBBBBBBBB") == False
    assert candidate(colors = "BABAABBAABBBBAAAABBBB") == False
    assert candidate(colors = "AABBAABBAABBAAA") == True
    assert candidate(colors = "AAAAAAAAABBBBBBBB") == True
    assert candidate(colors = "BBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAA") == True
    assert candidate(colors = "BBAABBAAAABBBBAAAAABBBAAABBBAAABBBB") == True
    assert candidate(colors = "AAAAAAAAABBAAAAAAAAA") == True
    assert candidate(colors = "AAAABBBAAAABBB") == True
    assert candidate(colors = "AABBAAAABBBAAAABBB") == True
    assert candidate(colors = "AAAAAAAABBBBBBBBBBAAA") == False
    assert candidate(colors = "AAAABBBAAAABBBAAAABBB") == True
    assert candidate(colors = "AAAAAAAAABBBBBBB") == True
    assert candidate(colors = "BBAAAABBAAAABBAAAABBAAAABBB") == True
    assert candidate(colors = "AABBBAAAABBBAAA") == True
    assert candidate(colors = "BBBBBBBBAAAABBBBBBB") == False
    assert candidate(colors = "BBBBBAAAABBBBBAAAABBBBBAAAABBBBBAAAABBBBBAAAABBBBB") == False
    assert candidate(colors = "BBABABABBABABABBABABABBB") == False
    assert candidate(colors = "BBAABBAAAABBAAAABBAAAABBB") == True
    assert candidate(colors = "BBBAAAABBAAAABBB") == True
    assert candidate(colors = "BBBBBBBBBBBBBBBBBB") == False
    assert candidate(colors = "AAAABBBBAAAA") == True
    assert candidate(colors = "BBBBAABBBAABBBAAB") == False
    assert candidate(colors = "AAAAAAAAAA") == True
    assert candidate(colors = "BBBBBBAAAABBBBBBAAAABBBBBB") == False
    assert candidate(colors = "BAAABAAABAAABBB") == True
    assert candidate(colors = "AAABBBAAAABBBAAAABBB") == True
    assert candidate(colors = "AAAAAABBBBAAAABBBBAAAAA") == True
    assert candidate(colors = "BBBAAAAAAAABBBBBB") == True
    assert candidate(colors = "AAABBBAABBBAAABBBAABBB") == False
    assert candidate(colors = "BABABABABABABABAB") == False
    assert candidate(colors = "AABAAAAABBAAABAAAAABB") == True
    assert candidate(colors = "BBBBBAAAABBBBBAAAABBBBBAAAABBBBBAAAABBBBB") == False
    assert candidate(colors = "BBBAAABBBAAABBBAAA") == False
    assert candidate(colors = "AAABAAAAAAAABBBBBBB") == True
    assert candidate(colors = "BBBBBBBBAAAAAAAAAA") == True
    assert candidate(colors = "ABABABABABABABABABAB") == False
    assert candidate(colors = "ABBBBAAAAAABBBBBAAA") == False
    assert candidate(colors = "AAABAAABBBABBAAA") == True
    assert candidate(colors = "AABBBAAAAAAAAABBBBB") == True
    assert candidate(colors = "BBAAAABBBAAAABBBAAAABBBAAA") == True
    assert candidate(colors = "BBBBBBBAAAAAAAAAA") == True
    assert candidate(colors = "AABBBAAAABBBAAAABBB") == True
    assert candidate(colors = "AAAAAAAAAABBBBBBBBAAAAAAAAAABBBBBBBB") == True
    assert candidate(colors = "AABAAABAAABAAABAAABAAABAAABAAABAAAB") == True
    assert candidate(colors = "BBBBBAAAABBBBBAAAAABBBBBAAABBBAAAB") == False
