# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "b") == 1
    assert candidate(s = "aabbab") == 2
    assert candidate(s = "baba") == 2
    assert candidate(s = "aababb") == 2
    assert candidate(s = "abbaab") == 2
    assert candidate(s = "ab") == 2
    assert candidate(s = "a") == 1
    assert candidate(s = "ababa") == 1
    assert candidate(s = "bbaabaaa") == 2
    assert candidate(s = "aabbaa") == 1
    assert candidate(s = "") == 1
    assert candidate(s = "abb") == 2
    assert candidate(s = "baabb") == 2
    assert candidate(s = "aaaa") == 1
    assert candidate(s = "bbbb") == 1
    assert candidate(s = "abab") == 2
    assert candidate(s = "baaaabb") == 2
    assert candidate(s = "aaaaaaaaaabbbbbbbbbb") == 2
    assert candidate(s = "babbabbbaba") == 2
    assert candidate(s = "baabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabba") == 2
    assert candidate(s = "bababababababababa") == 2
    assert candidate(s = "bbaabbababb") == 2
    assert candidate(s = "baaabaaaaaabbaaab") == 2
    assert candidate(s = "aabbaabbaabb") == 2
    assert candidate(s = "baabbaab") == 1
    assert candidate(s = "baaababbabaababbabaababbabaababbabaababbabaababbabaababbabaababbabaababbabaababbabaababbabaababb") == 2
    assert candidate(s = "abaababaababaababa") == 2
    assert candidate(s = "aaabbaabbaabbaabba") == 2
    assert candidate(s = "aabaaaab") == 2
    assert candidate(s = "bbaaabbaaabbaaabbaa") == 2
    assert candidate(s = "aabbabbaa") == 1
    assert candidate(s = "bababa") == 2
    assert candidate(s = "aaaaaaaabbaaaaaaa") == 2
    assert candidate(s = "aaabbbbbabbaabbbbabbaabbbbabbaabbbbabbaabbbbabbaabbbbabbaabbbbabbaabbbbabbaabbbbabbaabbbbabbaabbbb") == 2
    assert candidate(s = "aabbbbbaaa") == 2
    assert candidate(s = "abbbabbbabbb") == 2
    assert candidate(s = "abbaababbababbab") == 2
    assert candidate(s = "aabbaabbabbaabbaabbabbaabbabbaabbaabbabbaabbabbaabbaabbabbaabbaabbabbaabbaabbabbaabbaabbabbaabbaabb") == 2
    assert candidate(s = "baabbaabbbaaba") == 2
    assert candidate(s = "bbbbbaaaaaaaaabbbb") == 2
    assert candidate(s = "abbaabbbaabbaabbba") == 2
    assert candidate(s = "aaabbbabaabbaa") == 2
    assert candidate(s = "aaabbbbaaaaabbbbaa") == 2
    assert candidate(s = "bbbbbaaaaa") == 2
    assert candidate(s = "aabbbaaabbbaa") == 1
    assert candidate(s = "bbbbbaaabbbbbaaabbbb") == 2
    assert candidate(s = "baababababababababab") == 2
    assert candidate(s = "bbbaabbaabbaabbaabbb") == 1
    assert candidate(s = "bbbbbbbbbba") == 2
    assert candidate(s = "bbaabbaabbaabbaab") == 2
    assert candidate(s = "abbbabbbabbbbaba") == 2
    assert candidate(s = "babbabbabbabbabbab") == 1
    assert candidate(s = "abaaabbaaabbbaaaab") == 2
    assert candidate(s = "aabbaabbaab") == 2
    assert candidate(s = "aabbaabbbaabbaabbba") == 2
    assert candidate(s = "bbaabbaab") == 2
    assert candidate(s = "bbaabbbaaabb") == 2
    assert candidate(s = "bbbbbbbbbbb") == 1
    assert candidate(s = "abbaaabaaa") == 2
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 1
    assert candidate(s = "ababbbababbbabaabb") == 2
    assert candidate(s = "abbaabbaabbaabba") == 1
    assert candidate(s = "aabbbbaaabaaaabbbb") == 2
    assert candidate(s = "abbbabbbabbbabbbabbb") == 2
    assert candidate(s = "babababababababab") == 1
    assert candidate(s = "abbaabbbaabbaabbaa") == 2
    assert candidate(s = "bbaabaaaabb") == 2
    assert candidate(s = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb") == 1
    assert candidate(s = "bababababa") == 2
    assert candidate(s = "aaabbbaaabbbbaaa") == 2
    assert candidate(s = "aaaaaaaaaabbbbbbbb") == 2
    assert candidate(s = "aabbaaabbbaaabbaaa") == 2
    assert candidate(s = "ababababababab") == 2
    assert candidate(s = "aaaaaa") == 1
    assert candidate(s = "abababababa") == 1
    assert candidate(s = "abababababababab") == 2
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbaaaaaaaaaaabbbbbbbbbbaaaaaaaaaaabbbbbbbbbbaaaaaaaaaaabbbbbbbbbbaaaaaaaaaa") == 1
    assert candidate(s = "baaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaa") == 2
    assert candidate(s = "abababababab") == 2
    assert candidate(s = "ababababababababab") == 2
    assert candidate(s = "aabaaabbaaaab") == 2
    assert candidate(s = "abababbabababababab") == 2
    assert candidate(s = "baaaabbbaabb") == 2
    assert candidate(s = "bbbbbbbbaaaaaabbbbbbbbaaaaaabbbbbbbbaaaaaabbbbbbbbaaaaaabbbbbbbbaaaaaabbbbbbbbaaaaaabbbbbbbbaaaaaa") == 2
    assert candidate(s = "aaaaaaaaaaaaaaaaaa") == 1
    assert candidate(s = "bbbababaabbabababb") == 2
    assert candidate(s = "bbbbabbbbb") == 2
    assert candidate(s = "aaaaaaabbbbb") == 2
    assert candidate(s = "bbaabbbaa") == 2
    assert candidate(s = "baabbaaabbbaabbaab") == 2
    assert candidate(s = "abbbbbba") == 1
    assert candidate(s = "bbbbbbbbbbbbbbbbbbb") == 1
    assert candidate(s = "babbbbabbbbabbbbab") == 1
    assert candidate(s = "abababababababababababababab") == 2
    assert candidate(s = "aabbbaaaabbbbaa") == 2
    assert candidate(s = "abaabaabaabaabaaba") == 1
    assert candidate(s = "aabbaabbbaaabbbaab") == 2
    assert candidate(s = "aabababababa") == 2
    assert candidate(s = "aaaabbbb") == 2
    assert candidate(s = "abbaabbbaabbaa") == 2
    assert candidate(s = "ababababababababababab") == 2
    assert candidate(s = "baabbaabbaabbaab") == 1
    assert candidate(s = "ababbababbab") == 2
    assert candidate(s = "abababababababababab") == 2
    assert candidate(s = "abaabaabaabaabaabaa") == 2
    assert candidate(s = "abababab") == 2
    assert candidate(s = "bbbbbaaabbbbabab") == 2
    assert candidate(s = "bababababababa") == 2
    assert candidate(s = "babababab") == 1
    assert candidate(s = "aabbabbbabaabbabbb") == 2
    assert candidate(s = "abababa") == 1
    assert candidate(s = "aabbbbbaa") == 1
    assert candidate(s = "bbbaaaabbbbbaaaabb") == 2
    assert candidate(s = "aabbaabbaabbaabbaabbaab") == 2
    assert candidate(s = "ababbbabaabab") == 2
    assert candidate(s = "aaaaaaaaaabbbaaaaaaaaaaabbbaaaaaaaaaaabbbaaaaaaaaaaabbbaaaaaaaaaaabbbaaaaaaaaaaabbbaaaaaaaaaaa") == 2
    assert candidate(s = "babab") == 1
    assert candidate(s = "abababababababababababa") == 1
    assert candidate(s = "aabbaabbbaa") == 2
    assert candidate(s = "babababababababababa") == 2
    assert candidate(s = "abbabbabb") == 2
    assert candidate(s = "bbbbbaaaabaaaabbbb") == 2
    assert candidate(s = "bbbbbbbbbaaaaaaaaaa") == 2
    assert candidate(s = "ababababbababa") == 2
    assert candidate(s = "ababbbaba") == 1
    assert candidate(s = "abababaabbabababab") == 2
    assert candidate(s = "bbbbbbbbbbbbbbbbbb") == 1
    assert candidate(s = "aabbaabbaabbaabbaa") == 1
    assert candidate(s = "aaaaabbbbbaaaa") == 2
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbbaaaaaaaaa") == 2
    assert candidate(s = "aabbaabbabbaaabb") == 2
    assert candidate(s = "bbaabbaabbaa") == 2
    assert candidate(s = "aabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabb") == 2
    assert candidate(s = "bababbbabababbbaba") == 2
    assert candidate(s = "baabbaabbaabba") == 2
    assert candidate(s = "ababab") == 2
    assert candidate(s = "aabbabba") == 2
    assert candidate(s = "ababbbbaababbbbaabab") == 2
    assert candidate(s = "bbaaabaaabaaaaabbb") == 2
    assert candidate(s = "bababababab") == 1
    assert candidate(s = "bababababababab") == 1
    assert candidate(s = "bbaaaabbbbaaa") == 2
    assert candidate(s = "bbbaabbbbabbbabbbba") == 2
    assert candidate(s = "abbaabbaabba") == 1
    assert candidate(s = "bbaabbaabbaabbaabbaabbaab") == 2
    assert candidate(s = "abaababa") == 2
    assert candidate(s = "ababbbababbbababbbab") == 2
    assert candidate(s = "ababbababbabab") == 2
    assert candidate(s = "baaaaab") == 1
    assert candidate(s = "aababbabaab") == 2
    assert candidate(s = "aabbaaabbaa") == 1
    assert candidate(s = "abababababababababa") == 1
    assert candidate(s = "aaaaaaaaabbbbbbbbb") == 2
    assert candidate(s = "bbbaaabbbbaaaabbba") == 2
    assert candidate(s = "bbaaaaabbbbba") == 2
    assert candidate(s = "abbbbaaaaabbba") == 2
    assert candidate(s = "abbaabba") == 1
    assert candidate(s = "aaaaaaaaaaaaaaaaaaa") == 1
    assert candidate(s = "aabbaaaabbbbaaabbbbaaaabbbaaabbbbaaaabbbaaabbbbaaaabbbaaabbbbaaaabbbaaabbbbaaaabbbaaabbbbaaaabbbbaaaabb") == 2
    assert candidate(s = "abbbbabbbbabbbbabbbb") == 2
    assert candidate(s = "ababababa") == 1
    assert candidate(s = "abababbabaabbababbab") == 2
    assert candidate(s = "babbbbbbbabbbbbbb") == 2
    assert candidate(s = "bbaaaaaabbbaaaaaab") == 2
    assert candidate(s = "abababababababababababababababababababababababababababababababababababababababababababababababababab") == 2
    assert candidate(s = "bbbbbaaaaabbbbbaaaaa") == 2
    assert candidate(s = "ababbababa") == 2
    assert candidate(s = "babababa") == 2
    assert candidate(s = "aababbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabb") == 2
    assert candidate(s = "baabbaabbaab") == 1
    assert candidate(s = "ababbbababbbabaab") == 2
    assert candidate(s = "ababababababababababababababababababababababababababababababababababababababababababababababababababababababababab") == 2
