# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == "abcdefghijklmnopqrstuvwxyz"
    assert candidate(s = "acbbcaa") == "a"
    assert candidate(s = "aabbaa") == ""
    assert candidate(s = "abcdef") == "abcdef"
    assert candidate(s = "abbacdcd") == "cdcd"
    assert candidate(s = "aaaaa") == "a"
    assert candidate(s = "abbaca") == "ca"
    assert candidate(s = "a") == "a"
    assert candidate(s = "aabbccddccbaaabbccdd") == "ba"
    assert candidate(s = "") == ""
    assert candidate(s = "abcddcba") == ""
    assert candidate(s = "abba") == ""
    assert candidate(s = "zyz") == "zyz"
    assert candidate(s = "abc") == "abc"
    assert candidate(s = "abbacca") == "a"
    assert candidate(s = "abcd") == "abcd"
    assert candidate(s = "abbazzyy") == ""
    assert candidate(s = "aabbccddeeff") == ""
    assert candidate(s = "aabbcc") == ""
    assert candidate(s = "mississippi") == "m"
    assert candidate(s = "aaaaaaaaa") == "a"
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == ""
    assert candidate(s = "aaaaaaaa") == ""
    assert candidate(s = "zzzyyxxwwvvuuttrrqqqllopssmmnnllkkjjiihhggffeeddccbbaa") == "zqop"
    assert candidate(s = "aabbccdd") == ""
    assert candidate(s = "azxxzy") == "ay"
    assert candidate(s = "aabbbccddeeeffggghhhiiiijjjjkkkkllllmmmmnnnnooopppqqqqrrrrssssttttuuuuvvvvwwwwwxxxxxyyyyyzzzzz") == "beghopwxyz"
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == ""
    assert candidate(s = "abcdeedcba") == ""
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc") == "abcabcabcabcabcabcabcabcabcabc"
    assert candidate(s = "abcdabcdbcaabbccdd") == "abcdabcdbc"
    assert candidate(s = "xyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyx") == "xyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyx"
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz"
    assert candidate(s = "aabbaaabbbaaaabbbaaaaabbbbbbaaaaaaaaa") == "a"
    assert candidate(s = "mississiissippi") == "m"
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzyxwvutsrqponmlkjihgfedcba") == "zyxwvutsrqponmlkjihgfedcba"
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba") == "abcdefghijklmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba"
    assert candidate(s = "aaaabbbbccccddddeeeeffffgggghhhhiiiijjjjkkkkllllmmmmnnnnooooppppqqqqrrrrssssttttuuuuvvvvwwwwxxxxyyyyzzzz") == ""
    assert candidate(s = "aaabbbcccdddcccbbbaaa") == "abcdcba"
    assert candidate(s = "abccbaabccbaabccbaabccbaabccbaabccbaabccbaabccba") == ""
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == ""
    assert candidate(s = "abacadaeafagahaiajakalamananapapaqara saratasaunaavawaxayaz") == "abacadaeafagahaiajakalamananapapaqara saratasaunvawaxayaz"
