# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(word = "aabbccd") == True
    assert candidate(word = "aaabbbccc") == False
    assert candidate(word = "zazaza") == False
    assert candidate(word = "aaaaabbbbbcccc") == False
    assert candidate(word = "zzzzzzzz") == True
    assert candidate(word = "aabbccddeff") == True
    assert candidate(word = "aabbbbcccc") == False
    assert candidate(word = "aazz") == False
    assert candidate(word = "aabbbccccc") == False
    assert candidate(word = "aaa") == True
    assert candidate(word = "aabbbccddd") == False
    assert candidate(word = "abcdef") == True
    assert candidate(word = "aabbcccddd") == False
    assert candidate(word = "aabbc") == True
    assert candidate(word = "aabbccddeee") == True
    assert candidate(word = "abacabad") == False
    assert candidate(word = "abcdabcd") == False
    assert candidate(word = "aabbbccc") == False
    assert candidate(word = "aabbccdde") == True
    assert candidate(word = "aabbbcccc") == False
    assert candidate(word = "aabbbcccccc") == False
    assert candidate(word = "zzzz") == True
    assert candidate(word = "abcc") == True
    assert candidate(word = "xyyz") == True
    assert candidate(word = "aab") == True
    assert candidate(word = "aabbcc") == False
    assert candidate(word = "abcde") == True
    assert candidate(word = "aaabbbb") == True
    assert candidate(word = "aabbbb") == False
    assert candidate(word = "abcd") == True
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == False
    assert candidate(word = "abbbccddde") == False
    assert candidate(word = "abcabcabc") == False
    assert candidate(word = "qwerty") == True
    assert candidate(word = "aabbbcccd") == False
    assert candidate(word = "aabbccddd") == True
    assert candidate(word = "abc") == True
    assert candidate(word = "abcddd") == False
    assert candidate(word = "abcdefghijklmnopqrstuvwxzy") == True
    assert candidate(word = "aaaabbbb") == False
    assert candidate(word = "aabbccc") == True
    assert candidate(word = "abcdabcdabcd") == False
    assert candidate(word = "abcdefghi") == True
    assert candidate(word = "aabbcccd") == False
    assert candidate(word = "abcdefghijj") == True
    assert candidate(word = "aabbbcccdddde") == False
    assert candidate(word = "aabbcccc") == False
    assert candidate(word = "aabbccddeeefffg") == False
    assert candidate(word = "aabbccddeeeffffgggg") == False
    assert candidate(word = "aabbbccccddddeeeeeffffffggggg") == False
    assert candidate(word = "aabbccddeeffg") == True
    assert candidate(word = "zzzzzzzzzz") == True
    assert candidate(word = "aabbbccccdddde") == False
    assert candidate(word = "aabbccddeeffgg") == False
    assert candidate(word = "abcdefghij") == True
    assert candidate(word = "aabbccddeeffgggh") == False
    assert candidate(word = "aabbccddeeff") == False
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == True
    assert candidate(word = "abcabcabcabcabcabcabcabc") == False
    assert candidate(word = "zzzzzyyyyy") == False
    assert candidate(word = "aaaabbbbccccdddd") == False
    assert candidate(word = "aabbbccccdddd") == False
    assert candidate(word = "aabbbcccddd") == False
    assert candidate(word = "abcdefg") == True
    assert candidate(word = "aabbbccccddddeeeeeffffff") == False
    assert candidate(word = "abcdefghijjk") == True
    assert candidate(word = "aabbbcccde") == False
    assert candidate(word = "abbbbcccccdddddeeeeee") == False
    assert candidate(word = "aabbccddeeeffff") == False
    assert candidate(word = "aabbbccccddddeeeee") == False
    assert candidate(word = "aabbccddeeffggghhhh") == False
    assert candidate(word = "abcabcabcabc") == False
    assert candidate(word = "aabbbcccdddd") == False
    assert candidate(word = "aabbcddd") == False
