# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(word = "abddez") == 2
    assert candidate(word = "qrstuvwpqrstuvwxyz") == 8
    assert candidate(word = "abecidof") == 1
    assert candidate(word = "zzz") == 1
    assert candidate(word = "abacaba") == 2
    assert candidate(word = "abababab") == 4
    assert candidate(word = "acacacac") == 0
    assert candidate(word = "xyz") == 1
    assert candidate(word = "abcde") == 2
    assert candidate(word = "aabbcc") == 3
    assert candidate(word = "zzzzz") == 2
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 26
    assert candidate(word = "abcdefg") == 3
    assert candidate(word = "a") == 0
    assert candidate(word = "mnonmo") == 2
    assert candidate(word = "abc") == 1
    assert candidate(word = "acxz") == 0
    assert candidate(word = "zyxwvutsrqponmlkjihgfedcba") == 13
    assert candidate(word = "aaaaa") == 2
    assert candidate(word = "abcdefghijklmnopqrstuvwxyz") == 13
    assert candidate(word = "qwert") == 0
    assert candidate(word = "zyxyxyz") == 3
    assert candidate(word = "aabbaabbaabbaabbaabbaabb") == 12
    assert candidate(word = "aaabbbccc") == 4
    assert candidate(word = "aaaaabbbbbaaaa") == 7
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 39
    assert candidate(word = "zzzyyxxwwvvuuttrrssqqppoonnllkkjjiihhggffeeddccbbaa") == 25
    assert candidate(word = "abbbccddeeefffggghhhhiiiiijjjjkkkkllllmmmmmnnnnnooooo") == 26
    assert candidate(word = "mississippi") == 3
    assert candidate(word = "aaaabbbbccccddddeeeeffffgggghhhhiiiijjjjkkkkllllmmmnnnooopppqqqqrrrrssssttttuuuuvvvvwwwwxxxxyyyyzzzz") == 50
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzyyyxxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccbbbaaaa") == 54
    assert candidate(word = "aabbbcccddddeeeeffffgggghhhhiiiiijjjjkkkkllllmmmmnnnnooooppppqqqqrrrrssssttttuuuuvvvvwwwwwxxxxxyyyyyzzzzz") == 52
    assert candidate(word = "aazzbbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 27
    assert candidate(word = "zzzzyyyyxxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccbbbaaaa") == 30
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba") == 25
    assert candidate(word = "aaaabbbbcccc") == 6
    assert candidate(word = "qwerttyuiiooppllkkiijjhhggffeedcvvbbnnaassddffgghhjjiikkllppoouuyyttrewqq") == 32
    assert candidate(word = "aaaabbbbccccaaaabbbbcccc") == 12
    assert candidate(word = "aaaabbbbccccddddeeeeffffgggghhhhiiiijjjjkkkkllllmmmnnnooopppqqqqrrrrssssttttuuuuuvvvvwwwwxxxxyyyyzzzz") == 50
    assert candidate(word = "zyxwvutsrqponmlkjihgfedcbaabcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 39
    assert candidate(word = "aabbaaabbbaaa") == 6
    assert candidate(word = "banana") == 1
    assert candidate(word = "abcabcabcabcabcabc") == 6
    assert candidate(word = "abcdeedcba") == 5
    assert candidate(word = "zyxzyxzyx") == 3
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 50
    assert candidate(word = "ababababababababababc") == 10
    assert candidate(word = "zyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyx") == 18
    assert candidate(word = "aaabbbcccdddeeefffggghhhiiiijjjkkklllmmmnnnooopppqqqrrrssstttuuuvvvwwwxxxxyyyzzz") == 40
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 26
    assert candidate(word = "aabbccddeeaabbccddee") == 10
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzz") == 27
    assert candidate(word = "ababababababababababababababababababababab") == 21
    assert candidate(word = "zyxzyxzyxzyxzyxzyxzyxzyx") == 8
    assert candidate(word = "mnopqrspqrstmnopqrspqrstmnopqrspqrst") == 15
    assert candidate(word = "aaaaabbbbbaaaaabbbbbaaaa") == 12
    assert candidate(word = "aaaabbbbccccdddd") == 8
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 26
    assert candidate(word = "abzycxyxbwaxavauatassarapaoanamaalakajaiagafae") == 5
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzyxwvutsrqponmlkjihgfedcba") == 39
    assert candidate(word = "ababababab") == 5
    assert candidate(word = "abzabzabzabzabz") == 5
    assert candidate(word = "aabbaabbccddeeffaabbccddeeff") == 14
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzz") == 10
    assert candidate(word = "abacabcabacabcabacabcabacabcabacabcabacabc") == 12
    assert candidate(word = "abacabadabacabadaba") == 5
    assert candidate(word = "zyxwvutsrqponmlkjihgfedcbaaaaaaaaaaaaa") == 19
    assert candidate(word = "aaaaabbbbbccccc") == 7
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcb") == 25
    assert candidate(word = "zzzyyyxxxwwwwvvvuuuuttttssssrrrrqqqqppppllllooooiiiihhhhhgggggffffffeeeeeeeedddddccccbbbbaaa") == 46
    assert candidate(word = "abcabcabc") == 3
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 25
    assert candidate(word = "acxzacxzacxzacxzacxzacxz") == 0
    assert candidate(word = "zzzyyxxwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccbbbaaa") == 27
    assert candidate(word = "zazazazazazazazazaza") == 0
    assert candidate(word = "ababababababababababababababababababababababababababababababab") == 31
    assert candidate(word = "bookkeeper") == 3
    assert candidate(word = "abababababababababababababababababab") == 18
    assert candidate(word = "abababababababababababababab") == 14
    assert candidate(word = "zazazazazazazazazaabc") == 2
    assert candidate(word = "abczyxabczyxabczyx") == 6
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 41
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 21
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzaa") == 27
    assert candidate(word = "zyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcba") == 26
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcbaabcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 52
    assert candidate(word = "abzabzabz") == 3
    assert candidate(word = "abacabadabacabadabacabad") == 6
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 22
    assert candidate(word = "abcdabcdabcdabcdabcdabcd") == 12
    assert candidate(word = "abcabcabcabc") == 4
    assert candidate(word = "abacabadabacabadabacabadabacabad") == 8
    assert candidate(word = "abacabadabacaba") == 4
    assert candidate(word = "abababababababababab") == 10
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 26
