# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(instructions = "GGLGRGLL") == True
    assert candidate(instructions = "LLLL") == True
    assert candidate(instructions = "GLLRLLRL") == True
    assert candidate(instructions = "GRGL") == False
    assert candidate(instructions = "LLGRL") == True
    assert candidate(instructions = "LRRL") == True
    assert candidate(instructions = "LLGRR") == False
    assert candidate(instructions = "LRRRRLL") == True
    assert candidate(instructions = "LL") == True
    assert candidate(instructions = "RRGRRG") == True
    assert candidate(instructions = "GGGG") == False
    assert candidate(instructions = "GGRRGG") == True
    assert candidate(instructions = "GLGLG") == True
    assert candidate(instructions = "GGLLGG") == True
    assert candidate(instructions = "L") == True
    assert candidate(instructions = "GL") == True
    assert candidate(instructions = "R") == True
    assert candidate(instructions = "GG") == False
    assert candidate(instructions = "GLGLGLGL") == True
    assert candidate(instructions = "RRRR") == True
    assert candidate(instructions = "G") == False
    assert candidate(instructions = "GLGLGRRG") == False
    assert candidate(instructions = "GLLRLLRR") == True
    assert candidate(instructions = "RR") == True
    assert candidate(instructions = "LGLLGLLGRRRRGG") == True
    assert candidate(instructions = "LGR") == False
    assert candidate(instructions = "GLGLGRRR") == True
    assert candidate(instructions = "GRRG") == True
    assert candidate(instructions = "GRRGRRGRRGRRGRRGLG") == True
    assert candidate(instructions = "GLRGLRGLRGLRGLRGLR") == False
    assert candidate(instructions = "GGGGGRRRRRLLLLL") == False
    assert candidate(instructions = "GGRRLLGGRRLLGGRRLL") == False
    assert candidate(instructions = "LGGRRGGRRGGRRG") == True
    assert candidate(instructions = "RRRLLLLGGGGRRRLLL") == True
    assert candidate(instructions = "RRLLRRLLRRLLRR") == True
    assert candidate(instructions = "GLRGLRGLRGLRGLR") == False
    assert candidate(instructions = "RRRRGGGGLLGGGG") == True
    assert candidate(instructions = "GLGLGLGLGLGLGLGLGL") == True
    assert candidate(instructions = "RRRRRRRRRRRRRR") == True
    assert candidate(instructions = "RRLLGGGLLLRRRR") == True
    assert candidate(instructions = "LGLLGLGLLGLGRR") == True
    assert candidate(instructions = "GGRRLLGGLLRR") == False
    assert candidate(instructions = "GGGGGLLLRRRGGGGGLLLRRR") == False
    assert candidate(instructions = "LRRLRLRLRLRLRLRL") == True
    assert candidate(instructions = "LLLLRRRRLLLLRRRR") == True
    assert candidate(instructions = "GLGRGLGRGLGRGL") == True
    assert candidate(instructions = "GLRRLGLRRL") == False
    assert candidate(instructions = "GRRGRRGRRGRRGRRGRR") == True
    assert candidate(instructions = "LLLLRRRRLLLLRRRRGG") == False
    assert candidate(instructions = "GGGGRRRLLLLGGGRR") == True
    assert candidate(instructions = "GRRGRLGLGG") == True
    assert candidate(instructions = "RRLLGGGGLLRRLG") == True
    assert candidate(instructions = "GGLLGGRRLLRRGG") == False
    assert candidate(instructions = "GLGRRGLLGLLRRGGG") == True
    assert candidate(instructions = "LRRLGRLGRLGRLRLR") == True
    assert candidate(instructions = "GLLRRGGLLRRGGLLRR") == False
    assert candidate(instructions = "GGGRRRGRRRRGGGRRR") == True
    assert candidate(instructions = "RRLLGGGGLLRRG") == False
    assert candidate(instructions = "LRRRRLLRRRRLLRRR") == True
    assert candidate(instructions = "GRRGRRGRRGRRGG") == False
    assert candidate(instructions = "GGGLGGGLGGGLGGGL") == True
    assert candidate(instructions = "GGRRGGRRGGRRGGRR") == True
    assert candidate(instructions = "LLRRGGGGLLRRGG") == False
    assert candidate(instructions = "GGLRLRGGRRLL") == False
    assert candidate(instructions = "LRRGGLLLGGRRGG") == False
    assert candidate(instructions = "GLRRGLRRGLRR") == True
    assert candidate(instructions = "LLLLGRRGGGLLRLLRRR") == True
    assert candidate(instructions = "GLRLRLRLRLRRGGGG") == True
    assert candidate(instructions = "RRGLLRRGLLRRGLLRRG") == True
    assert candidate(instructions = "GLLGRRGRRGLLGRR") == True
    assert candidate(instructions = "LGGGGRLRRRRGLLGG") == True
    assert candidate(instructions = "GRRGGLLLGGRRGG") == True
    assert candidate(instructions = "LLLLRRRLLLLRRR") == True
    assert candidate(instructions = "LRLLRRLLRRLLRRLL") == True
    assert candidate(instructions = "RRLLGGGLLLRRGG") == True
    assert candidate(instructions = "RRGRLGGRLGRLG") == True
    assert candidate(instructions = "GGGLLLGGRRRRGGGL") == False
    assert candidate(instructions = "GLGGRLGRLGLGRLGLGG") == True
    assert candidate(instructions = "GGLGGLGGRRRR") == True
    assert candidate(instructions = "LGLRLGLRLGLRLGLRL") == True
    assert candidate(instructions = "GLGLGLGLGRRGRRGL") == True
    assert candidate(instructions = "LGGRLGRRGLLGRRGLGRR") == True
    assert candidate(instructions = "RRRLLLLRRRLLLL") == True
    assert candidate(instructions = "GLRGLRLRLGRRGGGG") == True
    assert candidate(instructions = "LGGRRGLGGLLRRGL") == True
    assert candidate(instructions = "GGGGLLLRRRGGRRRL") == True
    assert candidate(instructions = "GLRLRLRLRLRLRLRL") == True
    assert candidate(instructions = "GLGRRGGLLRRGGLLRR") == True
    assert candidate(instructions = "GGGGRRRLLLLLGGGG") == True
    assert candidate(instructions = "RRRGLLGGLLLGGG") == True
    assert candidate(instructions = "GGRRLLGGRRLL") == False
    assert candidate(instructions = "LGRGLRLRLGRR") == True
    assert candidate(instructions = "LGGRRGRRLLGGRL") == True
    assert candidate(instructions = "GLLLRRRRGLLLRRRR") == True
    assert candidate(instructions = "GGGLLLGGGLLLGGGL") == True
    assert candidate(instructions = "GLRLGLRLGLRLGLRL") == True
    assert candidate(instructions = "LGLLGLGLLGLGRRGLGRR") == False
    assert candidate(instructions = "GLGRLLRLRRRL") == False
    assert candidate(instructions = "LGLGLLRLRLRLRL") == False
    assert candidate(instructions = "GLGLGLGLGLGL") == True
    assert candidate(instructions = "LLGGRRLLGGRRLLGG") == True
    assert candidate(instructions = "GLGGRLGRLGLGRL") == True
    assert candidate(instructions = "LGLLGLGLGLGLLGLL") == True
    assert candidate(instructions = "LRLRLRLRLRLRLRLRLR") == True
    assert candidate(instructions = "GGLRLRRLLGLGGGG") == True
    assert candidate(instructions = "GGGGGGGGGGGGGG") == False
    assert candidate(instructions = "GRRRLRLLGLGLGRLR") == False
    assert candidate(instructions = "GGGLGGGLGGGLGGGLGG") == False
    assert candidate(instructions = "LGLRLGLRLGLRLGLRLR") == True
    assert candidate(instructions = "GLGLGLGLGLGLGLGL") == True
    assert candidate(instructions = "LGLGLGLGLGLGLGLG") == True
    assert candidate(instructions = "LLLLLLLLLLLLLL") == True
    assert candidate(instructions = "LGLGLGLGLGLGLG") == True
    assert candidate(instructions = "GGRRGLGRRGRRGRR") == True
    assert candidate(instructions = "LRLRLRLRLRLRLRLR") == True
    assert candidate(instructions = "GLGLGLGLGL") == True
    assert candidate(instructions = "GRRGRRGRRGRRGRRG") == True
    assert candidate(instructions = "GRRGLLRLLGRGLL") == True
    assert candidate(instructions = "LGLRLGLRLG") == True
    assert candidate(instructions = "GGLRLGLLGGRR") == True
    assert candidate(instructions = "GLRRLLRRLLRRLLRR") == True
    assert candidate(instructions = "RRLLRRLLRRLLRRLLRR") == True
    assert candidate(instructions = "GLRLRLRLRLRLRLRLGG") == True
    assert candidate(instructions = "RRGGLLRGGLLRRGLL") == True
    assert candidate(instructions = "GGGGGGGGGGGGGGGG") == False
    assert candidate(instructions = "GRRGLRGGGLLRLLGRR") == True
    assert candidate(instructions = "GLRRGLLLGGGGRRRR") == True
    assert candidate(instructions = "RRRRLLLLGGGG") == False
    assert candidate(instructions = "GLRRGLGLRLRR") == True
    assert candidate(instructions = "LGGRLGRRGLG") == False
    assert candidate(instructions = "GGGGRRRRLLLL") == False
    assert candidate(instructions = "RGLLRLGLGRRG") == True
    assert candidate(instructions = "RRLLRRLLRRLLRRLL") == True
    assert candidate(instructions = "GLRLGLRLGLRL") == True
    assert candidate(instructions = "GLGRRRRRGGGLLGLGRR") == True
    assert candidate(instructions = "GGGLRRLLGLRRLL") == True
    assert candidate(instructions = "GGLLGGGGLLGGGG") == False
    assert candidate(instructions = "LRRLRLRLRL") == True
    assert candidate(instructions = "GRRGGGGLLLRRGGLG") == False
    assert candidate(instructions = "LRRGLLRRGLLRRGLLRR") == True
