# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 25
    assert candidate(s = "a") == 0
    assert candidate(s = "abracadabra") == 78
    assert candidate(s = "zzzz") == 0
    assert candidate(s = "zyx") == 2
    assert candidate(s = "mnopqr") == 5
    assert candidate(s = "python") == 34
    assert candidate(s = "aaa") == 0
    assert candidate(s = "abcdabcd") == 9
    assert candidate(s = "zzz") == 0
    assert candidate(s = "xyz") == 2
    assert candidate(s = "zaz") == 50
    assert candidate(s = "zyxwvut") == 6
    assert candidate(s = "abc") == 2
    assert candidate(s = "hello") == 13
    assert candidate(s = "aabbcc") == 2
    assert candidate(s = "mississippi") == 58
    assert candidate(s = "qpqpqpqp") == 7
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba") == 25
    assert candidate(s = "qwerty") == 44
    assert candidate(s = "aaaabbbbccccdddd") == 3
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnmqwertyui") == 276
    assert candidate(s = "abcdabcdabcdabcdabcd") == 27
    assert candidate(s = "lkjlkjlkjlkjlkjlkjlkjlkjlkjlkjlkjlkjlkj") == 50
    assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghij") == 63
    assert candidate(s = "learning") == 49
    assert candidate(s = "helloalibaba") == 51
    assert candidate(s = "aaabbbcccdddeeefffggghhhiiiijjjkkklllmmmnnnooopppqqqrrrssstttuuuvvvwwwxxxyyyzzz") == 25
    assert candidate(s = "thisisaverylongstringwithavarietyofcharacters") == 447
    assert candidate(s = "abacabadabacaba") == 22
    assert candidate(s = "code") == 24
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzzzzyxwvutsrqponmlkjihgfedcba") == 50
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc") == 38
    assert candidate(s = "hellohellohellohellohello") == 93
    assert candidate(s = "abcdabcda") == 12
    assert candidate(s = "data") == 41
    assert candidate(s = "challenge") == 48
    assert candidate(s = "artificial") == 67
    assert candidate(s = "abcabcabcabc") == 14
    assert candidate(s = "mnopqrstmnopqrstmnopqr") == 33
    assert candidate(s = "hellotherefriends") == 119
    assert candidate(s = "quickbrownfoxjumpsoverthelazydog") == 282
    assert candidate(s = "qrstuvpqponmlkjihgfedcba") == 28
    assert candidate(s = "aaaabbbbccccddddeeeeffff") == 5
    assert candidate(s = "abczzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 25
    assert candidate(s = "science") == 48
    assert candidate(s = "thefiveboxingwizardsjumpquickly") == 295
    assert candidate(s = "aaaaabbbbbcccccdddddee") == 4
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnm") == 212
    assert candidate(s = "mnbvcxzlkjhgfdsapoiuytrewqmnbvcxzlkjhgfdsapoiuytrewq") == 428
    assert candidate(s = "zazazazazazazazazazazazazazazazazazazazazazazazaza") == 1225
    assert candidate(s = "ejhjhehjhejhejhejhejhej") == 69
    assert candidate(s = "developer") == 70
    assert candidate(s = "abababababababab") == 15
    assert candidate(s = "abcdefghijklmnopqrstuvwxyza") == 50
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 75
    assert candidate(s = "noon") == 2
    assert candidate(s = "solution") == 35
    assert candidate(s = "lkjasdlfkjsadlkfjasdlkfjasdlkfjasdlkfjsadlkfj") == 340
    assert candidate(s = "qpwoeirutyalskdjfhgzmxcvbnm") == 234
    assert candidate(s = "abcabcabcabcabcabc") == 22
    assert candidate(s = "abcdefgfe_dcba") == 22
    assert candidate(s = "algorithm") == 64
    assert candidate(s = "sdjfnwiehfuiwehfiuhweihufew") == 242
    assert candidate(s = "thisisaverylongstringwithvariouscharacters") == 417
    assert candidate(s = "jfkienfehndsjdfhienfhisodfns") == 151
    assert candidate(s = "intelligence") == 62
    assert candidate(s = "qwen") == 33
    assert candidate(s = "alibabacloud") == 61
    assert candidate(s = "fun") == 22
    assert candidate(s = "hellothereitisacoldwinter") == 210
    assert candidate(s = "aaabbbcccdddeeefffggghhhiiiijjjjkkkkllllmmmmnnnnooopppqqqqrrrrssssttttuuuuvvvvwwwwxxxxyyyyzzzz") == 25
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 25
    assert candidate(s = "asciiisawesome") == 136
    assert candidate(s = "programming") == 69
    assert candidate(s = "qwertypoiuytrewq") == 120
    assert candidate(s = "abczabcyabcbabczabcyabcbabcz") == 229
    assert candidate(s = "level") == 48
    assert candidate(s = "thisisaverylongstringthatcontainsmanycharacters") == 461
    assert candidate(s = "qazwsxedcrfvtgbyhnujmiklop") == 215
    assert candidate(s = "thisisaverylongstringwithmanycharacters") == 389
    assert candidate(s = "azbycxdwevfugthsijrkqlponm") == 314
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(s = "thequickbrownfoxjumpsoverthelazydog") == 309
    assert candidate(s = "mnopqrstmnopqrst") == 21
    assert candidate(s = "abcdefg") == 6
    assert candidate(s = "expert") == 53
