# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "(()())") == 4
    assert candidate(s = "(()(()))") == 6
    assert candidate(s = "()") == 1
    assert candidate(s = "((()))") == 4
    assert candidate(s = "((()()()))") == 12
    assert candidate(s = "()()(())") == 4
    assert candidate(s = "()()") == 2
    assert candidate(s = "(()(()(())))") == 14
    assert candidate(s = "()(())") == 3
    assert candidate(s = "(())") == 2
    assert candidate(s = "((())())") == 6
    assert candidate(s = "()((()))") == 5
    assert candidate(s = "(()(()(()())))") == 22
    assert candidate(s = "(((())()))") == 12
    assert candidate(s = "(())((()))") == 6
    assert candidate(s = "()(((())))") == 9
    assert candidate(s = "()()()") == 3
    assert candidate(s = "(())(())") == 4
    assert candidate(s = "()(()(()(())))") == 15
    assert candidate(s = "(()((())()))") == 14
    assert candidate(s = "(()())(()())") == 8
    assert candidate(s = "(()((()))(()))") == 14
    assert candidate(s = "((()()()()))") == 16
    assert candidate(s = "((()))()()") == 6
    assert candidate(s = "((())(()))") == 8
    assert candidate(s = "()(()(()))") == 7
    assert candidate(s = "((()())(()))") == 12
    assert candidate(s = "((()(()(())))())") == 30
    assert candidate(s = "(()(()()(())))") == 18
    assert candidate(s = "(((()))(()))") == 12
    assert candidate(s = "((()))()") == 5
    assert candidate(s = "(()(())(()))") == 10
    assert candidate(s = "((()))(())()") == 7
    assert candidate(s = "((()(()))())") == 14
    assert candidate(s = "()((())())") == 7
    assert candidate(s = "(((())))") == 8
    assert candidate(s = "(()())(())") == 6
    assert candidate(s = "((())()())") == 8
    assert candidate(s = "((()(())))") == 12
    assert candidate(s = "()(())(()(()))") == 9
    assert candidate(s = "((()()(())))") == 16
    assert candidate(s = "(((()()())))") == 24
    assert candidate(s = "(((()()(()))))") == 32
    assert candidate(s = "((((()))))") == 16
    assert candidate(s = "(()()(()))") == 8
    assert candidate(s = "(()((())))") == 10
    assert candidate(s = "()((()()()))") == 13
    assert candidate(s = "((()())())") == 10
    assert candidate(s = "(())(()(()))") == 8
    assert candidate(s = "(((()())()))") == 20
    assert candidate(s = "()((())()())") == 9
    assert candidate(s = "()()()()") == 4
    assert candidate(s = "((()))(())") == 6
    assert candidate(s = "((()()))") == 8
    assert candidate(s = "()(())(())") == 5
