# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(keyboard = "abcdefghijklmnopqrstuvwxyz",word = "a") == 0
    assert candidate(keyboard = "abcdefghijklmnopqrstuvwxyz",word = "pqrstuvwxyzabcdefghijklmno") == 64
    assert candidate(keyboard = "zyxwvutsrqponmlkjihgfedcba",word = "zyxwvutsrqponmlkjihgfedcba") == 25
    assert candidate(keyboard = "qwertyuiopasdfghjklzxcvbnm",word = "internationalization") == 188
    assert candidate(keyboard = "abcdefghijklmnopqrstuvwxyz",word = "cba") == 4
    assert candidate(keyboard = "abcdefghijklmnopqrstuvwxyz",word = "thequickbrownfoxjumpsoverthelazydog") == 328
    assert candidate(keyboard = "pqrstuvwxyzabcdefghijklmno",word = "leetcode") == 73
    assert candidate(keyboard = "qwertyuioplkjhgfdsazxcvbnm",word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 19
    assert candidate(keyboard = "poiuytrewqlkjhgfdsamnbvcxz",word = "programmingcontestisfun") == 224
    assert candidate(keyboard = "qwertyuiopasdfghjklzxcvbnm",word = "abacabadabacaba") == 162
    assert candidate(keyboard = "qwertyuiopasdfghjklzxcvbnm",word = "supercalifragilisticexpialidocious") == 275
    assert candidate(keyboard = "qwertyuioplkjhgfdsazxcvbnm",word = "hellofromtheotherworld") == 174
    assert candidate(keyboard = "poiuytrewqlkjhgfdsamnbvcxz",word = "abcdefghijklmnopqrstuvwxyz") == 229
    assert candidate(keyboard = "qwertyuiopasdfghjklzxcvbnm",word = "thequickbrownfoxjumpsoverthelazydog") == 322
    assert candidate(keyboard = "poiuytrewqlkjhgfdsamnbvcxz",word = "rhythm") == 37
    assert candidate(keyboard = "cvbnmasdfghjklpoiuytrewqzxc",word = "xylophone") == 79
    assert candidate(keyboard = "lkjhgfdsapoiuytrewqmnbvcxz",word = "softwareengineering") == 114
    assert candidate(keyboard = "poiuytrewqlkjhgfdsamnbvcxz",word = "bazinga") == 82
    assert candidate(keyboard = "qwertyuiopasdfghjklzxcvbnm",word = "neuromuscular") == 151
    assert candidate(keyboard = "abcdefghijklmnopqrstuvwxyz",word = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 75
    assert candidate(keyboard = "zyxwvutsrqponmlkjihgfedcba",word = "zyxwvutsrqponmlkjihgfedcbaabcdefghijklmnopqrstuvwxyz") == 50
    assert candidate(keyboard = "mnbvcxzlkjhgfdsapoiuytrewq",word = "supercalifragilisticexpialidocious") == 278
    assert candidate(keyboard = "fedcbaonmlkjihgtsrqpzyxwvu",word = "programmingisfun") == 139
    assert candidate(keyboard = "mnbvcxzlkjhgfdsapoiuytrewq",word = "quantization") == 119
    assert candidate(keyboard = "asdfghjklzxcvbnmqwertyuiop",word = "antidisestablishmentarianism") == 367
    assert candidate(keyboard = "qwertyuiopasdfghjklzxcvbnm",word = "mississippi") == 63
    assert candidate(keyboard = "mnbvcxzlkjhgfdsapoiuytrewq",word = "aquickbrownfoxjumpsoverthelazydog") == 317
    assert candidate(keyboard = "ejkflqzcvbnpitywrdxhgmosau",word = "exponentially") == 114
    assert candidate(keyboard = "poiuytrewqlkjhgfdsamnbvcxz",word = "antidisestablishmentarianism") == 295
    assert candidate(keyboard = "poiuytrewqlkjhgfdsamnbvcxz",word = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 447
    assert candidate(keyboard = "zyxwvutsrqponmlkjihgfedcba",word = "abacabadabacaba") == 47
    assert candidate(keyboard = "mnbvcxzlkjhgfdsapoiuytrewq",word = "algorithm") == 66
    assert candidate(keyboard = "poiuytrewqasdfghjklzxcvbnm",word = "congratulations") == 161
    assert candidate(keyboard = "mnbvcxzlkjhgfdsapoiuytrewq",word = "thequickbrownfoxjumpsoverthelazydog") == 339
    assert candidate(keyboard = "mnbvcxzlkjhgfdsapoiuytrewq",word = "racecar") == 96
    assert candidate(keyboard = "poiuytrewqlkjhgfdsamnbvcxz",word = "honorificabilitudinitatibus") == 313
    assert candidate(keyboard = "mnbvcxzlkjhgfdsapoiuytrewq",word = "alibabacloud") == 121
    assert candidate(keyboard = "asdfghjklqwertyuiopzxcvbnm",word = "supercalifragilisticexpialidocious") == 283
    assert candidate(keyboard = "zxcvbnmlkjhgfdsapoiuytrewq",word = "extraterrestrialization") == 181
    assert candidate(keyboard = "yuiophgfdlkjhgfdsazxcvbnmqwerty",word = "abcdefghijklmnopqrstuvwxyz") == 246
    assert candidate(keyboard = "lkjhgfdsazxcvbnmqwertyuiop",word = "thisisaverylongwordthatwilltestthekeyboardlayout") == 510
    assert candidate(keyboard = "zxcvbnmlkjhgfdsapoiuytrewq",word = "abcdefghijklmnopqrstuvwxyz") == 224
    assert candidate(keyboard = "zxcvbnmlkjhgfdsapoiuytrewq",word = "floccinaucinihilipilification") == 271
    assert candidate(keyboard = "asdfghjklqwertyuiopzxcvbnm",word = "juxtaposition") == 104
    assert candidate(keyboard = "mnbvcxzlkjhgfdsapoiuytrewq",word = "rhythm") == 66
    assert candidate(keyboard = "abcdefghijklmnopqrstuvwxyz",word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 25
    assert candidate(keyboard = "qwertyuioplkjhgfdsazxcvbnm",word = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 18
    assert candidate(keyboard = "zyxwvutsrqponmlkjihgfedcba",word = "reverseengineering") == 149
    assert candidate(keyboard = "mnbvcxzlkjhgfdsapoiuytrewq",word = "congratulationsonwinningthetournament") == 397
    assert candidate(keyboard = "abcdefghijklmnopqrstuvwxyz",word = "zzzzzzzzzzzzzzzzzzzz") == 25
    assert candidate(keyboard = "vbnm,asdfghjklpoiuytrewqzxc",word = "elephant") == 73
    assert candidate(keyboard = "abcdefghijklmnopqrstuvwxyz",word = "hellohellohellohellohellohellohellohello") == 160
    assert candidate(keyboard = "ploazxykrmnghijfdscwutevbq",word = "characterization") == 136
    assert candidate(keyboard = "lkjhgfdsazxcvbnm qwertyuiop",word = "serendipitously") == 110
    assert candidate(keyboard = "zxcvbnmlkjhgfdsapoiuytrewq",word = "quixotically") == 122
    assert candidate(keyboard = "qwertyuiopasdfghjklzxcvbnm",word = "aabbccddeeffgghhiijjkkllmmooppqqrrssttuuvvwwxxyyzz") == 215
    assert candidate(keyboard = "zxcvbnmlkjhgfdsapoiuytrewq",word = "antidisestablishmentarianism") == 232
    assert candidate(keyboard = "qwertyuioplkjhgfdsazxcvbnm",word = "supercalifragilisticexpialidocious") == 293
    assert candidate(keyboard = "qwertyuiopasdfghjklzxcvbnm",word = "everygoodboydoesfine") == 166
    assert candidate(keyboard = "qazwsxedcrfvtgbyhnujmiklop",word = "pneumonoultramicroscopicsilicovolcanoconiosis") == 442
    assert candidate(keyboard = "ejkflsdcxzivhnutybgrqompatwe",word = "thequickbrownfoxjumpsoverthelazydog") == 380
    assert candidate(keyboard = "asdfghjklzxcvbnmqwertyuiop",word = "thelazybrownfoxjumpsoverthelazydog") == 394
    assert candidate(keyboard = "fghijklmnopqrstuvwxyzabcde",word = "pythonprogramming") == 109
    assert candidate(keyboard = "asdfghjklzxcvbnmqwertyuiop",word = "pseudopseudohypoparathyroidism") == 441
    assert candidate(keyboard = "poeiuytrewqkjhgfdsalcvbnmzx",word = "algorithmsanddatastructures") == 175
    assert candidate(keyboard = "mnbvcxzasdfghjklpoiuytrewq",word = "quixotically") == 94
    assert candidate(keyboard = "poiuytrewqlkjhgfdsamnbvcxz",word = "floccinaucinihilipilification") == 330
    assert candidate(keyboard = "cvbnmloiuytrqwedpasdfgzxhbkj",word = "microelectromechanical") == 197
    assert candidate(keyboard = "fghijklmnopqrstuvwxyzabcde",word = "fedcbazyxwvutsrqponmlkjihgf") == 50
    assert candidate(keyboard = "asdfghjklqwertyuiopzxcvbnm",word = "programmingisfun") == 174
    assert candidate(keyboard = "qwertyuiopasdfghjklzxcvbnm",word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 215
    assert candidate(keyboard = "mnbvcxzlkjhgfdsapoiuytrewq",word = "programmingisfun") == 149
    assert candidate(keyboard = "ghijklmnopqrstuvwxyzabcdef",word = "thisisaverylongwordthatwilltestyouralgorithm") == 362
    assert candidate(keyboard = "cvbnmasdfghjklpoiuytrewqzxc",word = "congratulationsyouhavecompletedthelastlevel") == 383
    assert candidate(keyboard = "asdfghjklzxcvbnmqwertyuiop",word = "mississippi") == 115
    assert candidate(keyboard = "ejkpfghizxncovmwbartldsqyu",word = "onomatopoeia") == 77
    assert candidate(keyboard = "zyxwvutsrqponmlkjihgfedcba",word = "racecar") == 50
    assert candidate(keyboard = "abcdefghijklmnopqrstuvwxyz",word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 25
    assert candidate(keyboard = "abcdefgxyzhijklmnopqrtuvw",word = "programminglanguage") == 196
    assert candidate(keyboard = "bnmzxcvbnmlkjhgfdsapoiuytrewq",word = "cryptographically") == 129
    assert candidate(keyboard = "mnbvcxzlkjhgfdsapoiuytrewq",word = "qwertyuioplkjhgfdsazxcvbnm") == 66
    assert candidate(keyboard = "qwertyuioplkjhgfdsazxcvbnm",word = "floccinaucinihilipilification") == 242
    assert candidate(keyboard = "qwertyuioplkjhgfdsazxcvbnm",word = "incomprehensible") == 178
    assert candidate(keyboard = "asdfghjklzxcvbnmqwertyuiop",word = "thequickbrownfoxjumpsoverthelazydog") == 378
    assert candidate(keyboard = "mnbvcxzlkjhgfdsapoiuytrewq",word = "abababababababababababababababababababababababababababababab") == 782
    assert candidate(keyboard = "mnbvcxzlkjhgfdsapoiuytrewq",word = "algorithmically") == 130
    assert candidate(keyboard = "mnbvcxzasdfghjklpoiuytrewq",word = "floccinaucinihilipilification") == 237
    assert candidate(keyboard = "qwertyuiopasdfghjklzxcvbnm",word = "thelazybrownfoxjumpsoverthelazydog") == 354
    assert candidate(keyboard = "poiuytrewqlkjhgfdsamnbvcxz",word = "supercalifragilisticexpialidocious") == 377
    assert candidate(keyboard = "cvbnmasdfghjklpoiuytrewqzxc",word = "anexampleofaverylongwordthatneedstobechecked") == 387
    assert candidate(keyboard = "lkjhgfdsapoiuytrewqzxcvbnm",word = "mellifluous") == 93
    assert candidate(keyboard = "qwertyuioplkjhgfdsazxcvbnm",word = "bipartisan") == 86
    assert candidate(keyboard = "poiuytrewqlkjhgfdsazxcvbnm",word = "interstellar") == 94
    assert candidate(keyboard = "zxcvbnmlkjhgfdsapoiuytrewq",word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 224
    assert candidate(keyboard = "asdfghjklpoiuytrewqzxcvbnm",word = "mississippi") == 83
