# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "eight8 seven7 six6 five5 four4 three3 two2 one1") == "one two three four five six seven eight"
    assert candidate(s = "seven7 six6 five5 four4 three3 two2 one1") == "one two three four five six seven"
    assert candidate(s = "nine9 eight8 seven7 six6 five5 four4 three3 two2 one1") == "one two three four five six seven eight nine"
    assert candidate(s = "three3 two2 one1") == "one two three"
    assert candidate(s = "is2 sentence4 This1 a3") == "This is a sentence"
    assert candidate(s = "five5 four4 three3 two2 one1") == "one two three four five"
    assert candidate(s = "A9 B8 C7 D6 E5 F4 G3 H2 I1") == "I H G F E D C B A"
    assert candidate(s = "Myself2 Me1 I4 and3") == "Me Myself and I"
    assert candidate(s = "nine9 eight8 seven7 six6 five5 four4 three3 two2 one1 zero0") == "one two three four five six seven eight nine zero"
    assert candidate(s = "six6 five5 four4 three3 two2 one1") == "one two three four five six"
    assert candidate(s = "one1") == "one"
    assert candidate(s = "two1 one2") == "two one"
    assert candidate(s = "four4 three3 two2 one1") == "one two three four"
    assert candidate(s = "quick5 brown3 fox2 jumps9 over8 lazy4 the7 dog6 a1") == "a fox brown lazy quick dog the over jumps"
    assert candidate(s = "Quick5 brown4 fox3 jumps2 over1") == "over jumps fox brown Quick"
    assert candidate(s = "big2 bigger3 biggest1") == "biggest big bigger"
    assert candidate(s = "order10 words9 in8 correct7 sequence6 is5 important4 for3 understanding2 this1") == "this understanding for important is sequence correct in words order1"
    assert candidate(s = "a1 bc2 def3 ghij4 klmno5 pqrstu6 vwxyz7 abcdefg8 hijklmno9") == "a bc def ghij klmno pqrstu vwxyz abcdefg hijklmno"
    assert candidate(s = "abc1 def2 ghi3 jkl4 mno5 pqr6 stu7 vwx8 yza9") == "abc def ghi jkl mno pqr stu vwx yza"
    assert candidate(s = "Data2 Science1") == "Science Data"
    assert candidate(s = "alpha10 beta9 gamma8 delta7 epsilon6 zeta5 eta4 theta3 iota2 kappa1") == "kappa iota theta eta zeta epsilon delta gamma beta alpha1"
    assert candidate(s = "Quick5 Brown4 Fox3 Jumps2 Over1") == "Over Jumps Fox Brown Quick"
    assert candidate(s = "Digital2 Transformation1") == "Transformation Digital"
    assert candidate(s = "zebra9 yellow8 xenon7 winter6 volcano5 umbrella4 tornado3 storm2 rainbow1") == "rainbow storm tornado umbrella volcano winter xenon yellow zebra"
    assert candidate(s = "short1 longerWord2 evenLongerWord3") == "short longerWord evenLongerWord"
    assert candidate(s = "one9 two8 three7 four6 five5 six4 seven3 eight2 nine1") == "nine eight seven six five four three two one"
    assert candidate(s = "apple8 banana7 cherry6 date5 elderberry4 fig3 grape2 huckleberry1") == "huckleberry grape fig elderberry date cherry banana apple"
    assert candidate(s = "apple9 banana8 cherry7 date6 elderberry5 fig4 grape3 honeydew2 ice1") == "ice honeydew grape fig elderberry date cherry banana apple"
    assert candidate(s = "MixedCASE1 Word2 with3 DIFFERENT4 cases5") == "MixedCASE Word with DIFFERENT cases"
    assert candidate(s = "Python1 is2 great3") == "Python is great"
    assert candidate(s = "a9 b8 c7 d6 e5 f4 g3 h2 i1") == "i h g f e d c b a"
    assert candidate(s = "single1") == "single"
    assert candidate(s = "one1 two2 three3 four4 five5 six6 seven7 eight8 nine9") == "one two three four five six seven eight nine"
    assert candidate(s = "reverse9 order8 words7 in6 a5 sentence4 for3 testing2 purposes1") == "purposes testing for sentence a in words order reverse"
    assert candidate(s = "sun8 moon7 stars6 galaxy5 universe4 planets3 asteroid2 comet1") == "comet asteroid planets universe galaxy stars moon sun"
    assert candidate(s = "two2 one1 three3 four4 five5 six6 seven7 eight8 nine9") == "one two three four five six seven eight nine"
    assert candidate(s = "complex1 testing2 cases3 with4 multiple5 digits6 and7 shuffled8 order9") == "complex testing cases with multiple digits and shuffled order"
    assert candidate(s = "Sustainability1") == "Sustainability"
    assert candidate(s = "Hard2 Work3 Makes1 Success4") == "Makes Hard Work Success"
    assert candidate(s = "A5 B4 C3 D2 E1 F6 G7 H8 I9") == "E D C B A F G H I"
    assert candidate(s = "Alphabetically9 Better8 Christmas7 Does6 Everyone5 Feel4 Good3 Happy2 Indeed1") == "Indeed Happy Good Feel Everyone Does Christmas Better Alphabetically"
    assert candidate(s = "sun9 moon8 star7 planet6 comet5 asteroid4 meteor3 satellite2 galaxy1") == "galaxy satellite meteor asteroid comet planet star moon sun"
    assert candidate(s = "The9 quick8 brown7 fox6 jumps5 over4 lazy3 dog2 one1") == "one dog lazy over jumps fox brown quick The"
    assert candidate(s = "short6 longer5 very4 much3 more2 words1") == "words more much very longer short"
    assert candidate(s = "first1 second2 third3 fourth4 fifth5 sixth6 seventh7 eighth8 ninth9") == "first second third fourth fifth sixth seventh eighth ninth"
    assert candidate(s = "Two2 Words1") == "Words Two"
    assert candidate(s = "Complicated1 Sorting2 becomes3 significantly4 more5 challenging6 when7 words8 overlap9") == "Complicated Sorting becomes significantly more challenging when words overlap"
    assert candidate(s = "Python10 Java9 C8 Cpp7 Rust6 Go5 Ruby4 Swift3 Kotlin2 TypeScript1") == "TypeScript Kotlin Swift Ruby Go Rust Cpp C Java Python1"
    assert candidate(s = "zZ9 yY8 xX7 wW6 vV5 uU4 tT3 sS2 rR1") == "rR sS tT uU vV wW xX yY zZ"
    assert candidate(s = "A9 lot8 of7 testing6 needs5 to4 be3 done2 always1") == "always done be to needs testing of lot A"
    assert candidate(s = "z9 y8 x7 w6 v5 u4 t3 s2 r1") == "r s t u v w x y z"
    assert candidate(s = "twoWords2 oneWord1") == "oneWord twoWords"
    assert candidate(s = "ab9 cd8 ef7 gh6 ij5 kl4 mn3 op2 qr1") == "qr op mn kl ij gh ef cd ab"
    assert candidate(s = "Open3 Source2 Software1") == "Software Source Open"
    assert candidate(s = "a9 quick8 brown7 fox6 jumps5 over4 lazy3 dogs2 one1") == "one dogs lazy over jumps fox brown quick a"
    assert candidate(s = "aA9 bB8 cC7 dD6 eE5 fF4 gG3 hH2 iI1") == "iI hH gG fF eE dD cC bB aA"
    assert candidate(s = "shuffle7 sentence6 original5 reconstruct4 and3 a2 is1") == "is a and reconstruct original sentence shuffle"
    assert candidate(s = "shuffle9 words8 correctly7 to6 get5 the4 right3 order2 one1") == "one order right the get to correctly words shuffle"
    assert candidate(s = "HELLO1 woRLD2") == "HELLO woRLD"
    assert candidate(s = "Short1 words2 can3 also4 be5 tricky6") == "Short words can also be tricky"
    assert candidate(s = "Python3 Java2 C1 Ruby4 Go5") == "C Java Python Ruby Go"
    assert candidate(s = "mixed8 case7 word6 CASE5 Mixed4 CASE3 mixed2 CASE1") == "CASE mixed CASE Mixed CASE word case mixed"
    assert candidate(s = "Python3 Java2 C1") == "C Java Python"
    assert candidate(s = "This8 is7 a6 sample5 sentence4 with3 various2 words1") == "words various with sentence sample a is This"
    assert candidate(s = "ninja9 samurai8 katana7 wakizashi6 tanto5 yoroi4 kusarigama3 tsurugi2 ninja1") == "ninja tsurugi kusarigama yoroi tanto wakizashi katana samurai ninja"
    assert candidate(s = "alpha9 beta8 gamma7 delta6 epsilon5 zeta4 eta3 theta2 iota1") == "iota theta eta zeta epsilon delta gamma beta alpha"
    assert candidate(s = "zebra9 yak8 xenon7 wolf6 vulture5 unicorn4 tiger3 snake2 rabbit1") == "rabbit snake tiger unicorn vulture wolf xenon yak zebra"
    assert candidate(s = "repeated1 same2 numbers3 in4 different5 words6 should7 not8 be9 valid10") == "repeated same numbers in different words should not be valid1"
    assert candidate(s = "reverse9 order8 words7 in6 this5 shuffled4 sentence3 into2 proper1") == "proper into sentence shuffled this in words order reverse"
    assert candidate(s = "Single1") == "Single"
