# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(words = ['no-separator'],separator = ",") == ['no-separator']
    assert candidate(words = ['hello.world', 'foo.bar.baz'],separator = ".") == ['hello', 'world', 'foo', 'bar', 'baz']
    assert candidate(words = ['test|test|test'],separator = "|") == ['test', 'test', 'test']
    assert candidate(words = ['#a#b#', 'c#d', 'e#f#g'],separator = "#") == ['a', 'b', 'c', 'd', 'e', 'f', 'g']
    assert candidate(words = ['a,b,c', 'd,e', 'f,g,h'],separator = ",") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
    assert candidate(words = ['...'],separator = ".") == []
    assert candidate(words = ['multiple,,,commas'],separator = ",") == ['multiple', 'commas']
    assert candidate(words = ['@a@', 'b@c@d', 'e@f@g@h'],separator = "@") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
    assert candidate(words = ['no-separator-here'],separator = "-") == ['no', 'separator', 'here']
    assert candidate(words = ['|a|b|c|', 'd|e|f', 'g|h|i|j'],separator = "|") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
    assert candidate(words = ['|a|b|c|d|'],separator = "|") == ['a', 'b', 'c', 'd']
    assert candidate(words = ['abc', 'def', 'ghi'],separator = ".") == ['abc', 'def', 'ghi']
    assert candidate(words = ['hello.world', 'how.are.you'],separator = ".") == ['hello', 'world', 'how', 'are', 'you']
    assert candidate(words = ['1.2.3', '4.5.6.7'],separator = ".") == ['1', '2', '3', '4', '5', '6', '7']
    assert candidate(words = ['test|string|data'],separator = "|") == ['test', 'string', 'data']
    assert candidate(words = [',,', ',,'],separator = ",") == []
    assert candidate(words = ['hello.world', 'example.test'],separator = ".") == ['hello', 'world', 'example', 'test']
    assert candidate(words = ['#abc#', '#def#', '#ghi#'],separator = "#") == ['abc', 'def', 'ghi']
    assert candidate(words = ['hello.world', 'python.is.awesome'],separator = ".") == ['hello', 'world', 'python', 'is', 'awesome']
    assert candidate(words = ['###', '@#@', '$#$'],separator = "#") == ['@', '@', '$', '$']
    assert candidate(words = ['hello.world', 'python.code'],separator = ".") == ['hello', 'world', 'python', 'code']
    assert candidate(words = ['@hello@world', '@foo@bar@baz'],separator = "@") == ['hello', 'world', 'foo', 'bar', 'baz']
    assert candidate(words = ['$easy$', '$problem$'],separator = "$") == ['easy', 'problem']
    assert candidate(words = ['|||'],separator = "|") == []
    assert candidate(words = ['a,b,c', 'd,e,f', 'g,h'],separator = ",") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
    assert candidate(words = ['abc', 'def', 'ghi'],separator = ",") == ['abc', 'def', 'ghi']
    assert candidate(words = ['#a#b#c#'],separator = "#") == ['a', 'b', 'c']
    assert candidate(words = ['one.two.three', 'four.five', 'six'],separator = ".") == ['one', 'two', 'three', 'four', 'five', 'six']
    assert candidate(words = ['a.b.c.d.e'],separator = ".") == ['a', 'b', 'c', 'd', 'e']
    assert candidate(words = ['a.b.c', 'd.e', 'f'],separator = ".") == ['a', 'b', 'c', 'd', 'e', 'f']
    assert candidate(words = ['same|same|same', 'different|path|here'],separator = "|") == ['same', 'same', 'same', 'different', 'path', 'here']
    assert candidate(words = ['special,characters|.,|$#@|example'],separator = "|") == ['special,characters', '.,', '$#@', 'example']
    assert candidate(words = ['.,.', '.a.b.', '.c.d.e.'],separator = ".") == [',', 'a', 'b', 'c', 'd', 'e']
    assert candidate(words = ['hello|world|foo|bar', 'baz|qux|quux', 'corge|grault|garply'],separator = "|") == ['hello', 'world', 'foo', 'bar', 'baz', 'qux', 'quux', 'corge', 'grault', 'garply']
    assert candidate(words = ['this$that', 'and', 'the$other', 'thing'],separator = "$") == ['this', 'that', 'and', 'the', 'other', 'thing']
    assert candidate(words = ['.a.b.c.', '.d.e.', '.f.g.h.'],separator = ".") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
    assert candidate(words = ['a.b.c.d.e', 'f.g', 'h', 'i..j', 'k..l..m'],separator = ".") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm']
    assert candidate(words = ['a.b.c.d', 'e.f.g', 'h.i'],separator = ".") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']
    assert candidate(words = ['complex..string', 'string..with..multiple..dots', 'empty..'],separator = ".") == ['complex', 'string', 'string', 'with', 'multiple', 'dots', 'empty']
    assert candidate(words = ['##word1##', '##word2##word3##', 'word4##word5##'],separator = "#") == ['word1', 'word2', 'word3', 'word4', 'word5']
    assert candidate(words = ['1,2,3', '4,,5', ',6,'],separator = ",") == ['1', '2', '3', '4', '5', '6']
    assert candidate(words = ['start|end', 'middle|middle|middle', 'no|change'],separator = "|") == ['start', 'end', 'middle', 'middle', 'middle', 'no', 'change']
    assert candidate(words = ['noSeparatorHere', 'neitherHere', 'orHere'],separator = "|") == ['noSeparatorHere', 'neitherHere', 'orHere']
    assert candidate(words = ['a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z'],separator = "|") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
    assert candidate(words = ['|||', '||||', '|||||'],separator = "|") == []
    assert candidate(words = ['nested..dots.and||pipes', 'and#hashes', 'mixed##..|||characters'],separator = ".") == ['nested', 'dots', 'and||pipes', 'and#hashes', 'mixed##', '|||characters']
    assert candidate(words = ['nested|split|.|string|example'],separator = "|") == ['nested', 'split', '.', 'string', 'example']
    assert candidate(words = ['|a||b||c|', '|d||e|', 'f|||g'],separator = "|") == ['a', 'b', 'c', 'd', 'e', 'f', 'g']
    assert candidate(words = ['a|b|c', 'd.e.f', 'g#h#i'],separator = "|") == ['a', 'b', 'c', 'd.e.f', 'g#h#i']
    assert candidate(words = ['abc#def#ghi#jkl', 'mno#pqr', 'stu#vw'],separator = "#") == ['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vw']
    assert candidate(words = ['a|b|c|d|e', 'f|g|h|i', 'j|k|l|m|n|o'],separator = "|") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o']
    assert candidate(words = ['@start@middle@end', '@multiple@parts@here', '@only@one'],separator = "@") == ['start', 'middle', 'end', 'multiple', 'parts', 'here', 'only', 'one']
    assert candidate(words = ['abc...def...ghi', 'jkl...mno', 'pqr...stu...vwx...yz'],separator = "...") == ['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz']
    assert candidate(words = ['one..two...three', 'four....five', 'six......'],separator = ".") == ['one', 'two', 'three', 'four', 'five', 'six']
    assert candidate(words = ['abc.def.ghi', 'jklmno.pqr.stu', 'vwxyz.123.456'],separator = ".") == ['abc', 'def', 'ghi', 'jklmno', 'pqr', 'stu', 'vwxyz', '123', '456']
    assert candidate(words = ['a.b.c.d.e.f.g'],separator = ".") == ['a', 'b', 'c', 'd', 'e', 'f', 'g']
    assert candidate(words = ['hello###world', '###foo###bar', 'baz###'],separator = "###") == ['hello', 'world', 'foo', 'bar', 'baz']
    assert candidate(words = ['###abc###', 'def###ghi', '###jkl###'],separator = "#") == ['abc', 'def', 'ghi', 'jkl']
    assert candidate(words = ['|a||b|c|', '|d|e||f|', 'g|h|i||j'],separator = "|") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
    assert candidate(words = ['no|separator', 'only|one|separator', 'two|separators|here'],separator = "|") == ['no', 'separator', 'only', 'one', 'separator', 'two', 'separators', 'here']
    assert candidate(words = ['test$test$test', '$test$test', 'test$$test'],separator = "$") == ['test', 'test', 'test', 'test', 'test', 'test', 'test']
    assert candidate(words = ['nested|separators|are|here', 'nested|separators|again'],separator = "|") == ['nested', 'separators', 'are', 'here', 'nested', 'separators', 'again']
    assert candidate(words = ['noSeparatorHere', 'norHere', 'stillNotHere'],separator = ".") == ['noSeparatorHere', 'norHere', 'stillNotHere']
    assert candidate(words = ['||||', '...', '####'],separator = "|") == ['...', '####']
    assert candidate(words = ['one$two$three', 'four$five', '$six$'],separator = "$") == ['one', 'two', 'three', 'four', 'five', 'six']
    assert candidate(words = ['hello|world|python|programming'],separator = "|") == ['hello', 'world', 'python', 'programming']
    assert candidate(words = ['abc@def@ghi', 'jkl@@mno@pqr', 'stu@vwx@@yz'],separator = "@") == ['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz']
    assert candidate(words = ['word1@word2', 'word3', 'word4@word5@word6'],separator = "@") == ['word1', 'word2', 'word3', 'word4', 'word5', 'word6']
    assert candidate(words = ['example.com', 'user@example.co.uk'],separator = ".") == ['example', 'com', 'user@example', 'co', 'uk']
    assert candidate(words = ['abc', 'def', 'ghi'],separator = "z") == ['abc', 'def', 'ghi']
    assert candidate(words = ['@@@@', '####', '&&&&'],separator = "@") == ['####', '&&&&']
    assert candidate(words = ['a.b.c.d.e', 'f.g', 'h'],separator = ".") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
    assert candidate(words = ['@#$|%|^&*', '!@#$%^&*()', '|{}[]<>:'],separator = "$") == ['@#', '|%|^&*', '!@#', '%^&*()', '|{}[]<>:']
    assert candidate(words = ['startmiddleend', 'doubletriplequadruple'],separator = "#") == ['startmiddleend', 'doubletriplequadruple']
    assert candidate(words = ['hello###world', 'foo###bar', 'baz###qux'],separator = "###") == ['hello', 'world', 'foo', 'bar', 'baz', 'qux']
    assert candidate(words = ['hello.world$,another.world', 'yet.another.world', 'one.more.world'],separator = "$") == ['hello.world', ',another.world', 'yet.another.world', 'one.more.world']
    assert candidate(words = ['a,b,c,d,e', 'f,g,h,i,j', 'k,l,m,n,o'],separator = ",") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o']
    assert candidate(words = ['||a||b||c||', '|||', 'd|||e'],separator = "|") == ['a', 'b', 'c', 'd', 'e']
    assert candidate(words = ['multiple...dots...here', 'and...here', 'and...and...and'],separator = "...") == ['multiple', 'dots', 'here', 'and', 'here', 'and', 'and', 'and']
    assert candidate(words = ['multiple$$$dollar$$$signs', 'another$$$test$$$case'],separator = "$$$") == ['multiple', 'dollar', 'signs', 'another', 'test', 'case']
    assert candidate(words = ['hello||world', 'foo|bar|baz', 'qux|||quux'],separator = "|") == ['hello', 'world', 'foo', 'bar', 'baz', 'qux', 'quux']
    assert candidate(words = ['word1#word2#word3', 'word4#word5', 'word6'],separator = "#") == ['word1', 'word2', 'word3', 'word4', 'word5', 'word6']
    assert candidate(words = ['x|y|z|w|v|u|t', 's|r|q', 'p|o|n|m'],separator = "|") == ['x', 'y', 'z', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm']
    assert candidate(words = ['a.b.c.d.e', 'f.g', 'h.i.j'],separator = ".") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
    assert candidate(words = ['|||', '|a|b|c|', 'd|e|f|'],separator = "|") == ['a', 'b', 'c', 'd', 'e', 'f']
    assert candidate(words = ['###', '@#@'],separator = "#") == ['@', '@']
    assert candidate(words = ['......', '$.|$.|$.|$.|$.|$.|$.|$.|$.|$.|$.|$.|$.|$.|$.|$.|$.|$.|$.|$.|$.'],separator = "$") == ['......', '.|', '.|', '.|', '.|', '.|', '.|', '.|', '.|', '.|', '.|', '.|', '.|', '.|', '.|', '.|', '.|', '.|', '.|', '.|', '.|', '.']
    assert candidate(words = ['start.with.dot.', '.end.with.dot', '.both.ends.'],separator = ".") == ['start', 'with', 'dot', 'end', 'with', 'dot', 'both', 'ends']
    assert candidate(words = ['nested|path|to|file', 'another|path|with|multiple|segments'],separator = "|") == ['nested', 'path', 'to', 'file', 'another', 'path', 'with', 'multiple', 'segments']
    assert candidate(words = ['..', '$.$', '#@#@'],separator = ".") == ['$', '$', '#@#@']
    assert candidate(words = [',,a,,b,,c,,', ',,,', 'd,,,e'],separator = ",") == ['a', 'b', 'c', 'd', 'e']
    assert candidate(words = ['a.b.c.d.e', 'f.g.h', 'i.j'],separator = ".") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
    assert candidate(words = ['#start#middle#end', '##double##triple###', '###quadruple####'],separator = "#") == ['start', 'middle', 'end', 'double', 'triple', 'quadruple']
    assert candidate(words = ['###abc###', '###def###ghi###', '###'],separator = "#") == ['abc', 'def', 'ghi']
    assert candidate(words = ['multiple$$$separators', 'here$$$again$$$and$$$again'],separator = "$") == ['multiple', 'separators', 'here', 'again', 'and', 'again']
    assert candidate(words = ['noSeparator', 'alsoNoSeparatorHere'],separator = "$") == ['noSeparator', 'alsoNoSeparatorHere']
    assert candidate(words = ['abc#def#ghi', 'jkl|mno|pqr', 'stu,vwx,yz'],separator = "#") == ['abc', 'def', 'ghi', 'jkl|mno|pqr', 'stu,vwx,yz']
    assert candidate(words = [',,comma,,', 'separated,,values', ',,'],separator = ",") == ['comma', 'separated', 'values']
    assert candidate(words = ['leading|trailing|', '|trailing|only', 'only|leading|'],separator = "|") == ['leading', 'trailing', 'trailing', 'only', 'only', 'leading']
    assert candidate(words = ['no|separators', 'here', 'either'],separator = "|") == ['no', 'separators', 'here', 'either']
    assert candidate(words = ['a@b@c@d', 'e@f@g', 'h@i@j@k@l'],separator = "@") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l']
    assert candidate(words = ['1234567890', '', '0987654321'],separator = "5") == ['1234', '67890', '09876', '4321']
    assert candidate(words = ['x|y|z|w|v|u', 't|s|r|q', 'p|o|n|m|l|k|j|i|h|g|f|e|d|c|b|a'],separator = "|") == ['x', 'y', 'z', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']
    assert candidate(words = ['###', '@@@', '$$$'],separator = "#") == ['@@@', '$$$']
    assert candidate(words = ['|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|', '|'],separator = "|") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
    assert candidate(words = ['|a||b||c|', 'd||e|f||', '|g|h|i|'],separator = "|") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']
    assert candidate(words = ['nested.delimiters|inside|string', 'another|one|here'],separator = "|") == ['nested.delimiters', 'inside', 'string', 'another', 'one', 'here']
    assert candidate(words = ['....', '|||', '@@@'],separator = ".") == ['|||', '@@@']
    assert candidate(words = ['$first$$second$$third', 'fourth$$$$fifth', 'sixth$$$$'],separator = "$") == ['first', 'second', 'third', 'fourth', 'fifth', 'sixth']
    assert candidate(words = ['a.b.c.d.e', 'f.g', 'h'],separator = ".") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
    assert candidate(words = ['@start', 'end@', '@both@'],separator = "@") == ['start', 'end', 'both']
    assert candidate(words = ['###', '#foo#bar#', '###baz##'],separator = "#") == ['foo', 'bar', 'baz']
    assert candidate(words = ['repeated..dots', 'triple|||pipes', 'quadruple@@@@at'],separator = ".") == ['repeated', 'dots', 'triple|||pipes', 'quadruple@@@@at']
    assert candidate(words = ['a@b@c@d', 'e@f', 'g@h@i@j@k'],separator = "@") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k']
    assert candidate(words = ['multiple.separators.in.one.string', 'another|string|with|separators'],separator = ".") == ['multiple', 'separators', 'in', 'one', 'string', 'another|string|with|separators']
    assert candidate(words = ['complex@punctuation@marks', '@leading@', '@trailing@', '@@multiple@@@'],separator = "@") == ['complex', 'punctuation', 'marks', 'leading', 'trailing', 'multiple']
    assert candidate(words = ['a.b.c.d', 'e.f', 'g.h.i.j.k'],separator = ".") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k']
    assert candidate(words = ['end.with.dot.', '.start.with.dot', '.middle.dot.'],separator = ".") == ['end', 'with', 'dot', 'start', 'with', 'dot', 'middle', 'dot']
    assert candidate(words = ['x##y##z', '##', 'w####v'],separator = "#") == ['x', 'y', 'z', 'w', 'v']
    assert candidate(words = ['|||abc|||', 'def|||ghi|||', '|||jkl|||mno|||'],separator = "|") == ['abc', 'def', 'ghi', 'jkl', 'mno']
    assert candidate(words = ['word', 'anotherword', 'yetanotherword'],separator = "x") == ['word', 'anotherword', 'yetanotherword']
    assert candidate(words = ['........', '...', '.'],separator = ".") == []
    assert candidate(words = ['#example#test#case', '##', 'no#separator'],separator = "#") == ['example', 'test', 'case', 'no', 'separator']
    assert candidate(words = ['........'],separator = ".") == []
    assert candidate(words = ['apple,banana,cherry', 'date,elderberry', 'fig,grape'],separator = ",") == ['apple', 'banana', 'cherry', 'date', 'elderberry', 'fig', 'grape']
    assert candidate(words = ['..', '...', '....'],separator = ".") == []
    assert candidate(words = ['|||||||'],separator = "|") == []
    assert candidate(words = ['abc.def.ghi', 'jkl..mno', 'pqr'],separator = ".") == ['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr']
    assert candidate(words = ['nested#(separators)#inside#strings', '#multiple##hashes##here', '#no#trailing#hash'],separator = "#") == ['nested', '(separators)', 'inside', 'strings', 'multiple', 'hashes', 'here', 'no', 'trailing', 'hash']
    assert candidate(words = ['multiple...dots', 'here||||are', 'pipes', 'and###hashes'],separator = ".") == ['multiple', 'dots', 'here||||are', 'pipes', 'and###hashes']
    assert candidate(words = ['a|b||c|||d||||e'],separator = "|") == ['a', 'b', 'c', 'd', 'e']
    assert candidate(words = [',,apple,,,banana,,,', 'cherry,,,', 'date,'],separator = ",") == ['apple', 'banana', 'cherry', 'date']
    assert candidate(words = ['@start@', 'middle@', '@end'],separator = "@") == ['start', 'middle', 'end']
    assert candidate(words = ['#a#b#c#d', '#e##f#', 'g#h#i#'],separator = "#") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']
    assert candidate(words = ['a.b.c.d.e', 'f.g.h', 'i.j.k.l'],separator = ".") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l']
    assert candidate(words = ['a.b.c.d.e', 'f.g.h', 'i.j.k.l.m'],separator = ".") == ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm']
    assert candidate(words = ['special$characters$@#|$|@$#|', '@|#$|$#@|', '|@#$#@$|'],separator = "|") == ['special$characters$@#', '$', '@$#', '@', '#$', '$#@', '@#$#@$']
    assert candidate(words = ['foo$bar$baz', 'qux$quux', 'corge$grault$garply'],separator = "$") == ['foo', 'bar', 'baz', 'qux', 'quux', 'corge', 'grault', 'garply']
