# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "RRLLRRLL") == 2
    assert candidate(s = "RLRRRLLRLL") == 2
    assert candidate(s = "RRRRLLLLRRRRLLLL") == 2
    assert candidate(s = "LRRLLRRL") == 4
    assert candidate(s = "LLLLRRRRLLRRRR") == 2
    assert candidate(s = "RLLLLRRR") == 2
    assert candidate(s = "RLLRRLRR") == 3
    assert candidate(s = "RLRRLLRLRL") == 4
    assert candidate(s = "RRLLRRLLRL") == 3
    assert candidate(s = "LLRRLLRRLL") == 2
    assert candidate(s = "RRLRRLRLRL") == 0
    assert candidate(s = "RRLLRRLLRR") == 2
    assert candidate(s = "RLRRLLRL") == 3
    assert candidate(s = "LRRLRLLRRL") == 5
    assert candidate(s = "RLRLRLRLRL") == 5
    assert candidate(s = "LLRRLLRR") == 2
    assert candidate(s = "RLRLRLRL") == 4
    assert candidate(s = "RRRRLLLL") == 1
    assert candidate(s = "RRLRLLRLRL") == 3
    assert candidate(s = "LLRRLLRRLR") == 3
    assert candidate(s = "LRLRLRLRLR") == 5
    assert candidate(s = "LLRRRLLL") == 2
    assert candidate(s = "LRLRLRLR") == 4
    assert candidate(s = "LLLLRRRR") == 1
    assert candidate(s = "RLRRLLRRLLRRRRLLLLRRLLRR") == 5
    assert candidate(s = "RRLLRRLLRRLLRRLL") == 4
    assert candidate(s = "LLLLLLLLRRRRRRRR") == 1
    assert candidate(s = "LLLLRRRLLLLRRRLLLLRRR") == 0
    assert candidate(s = "RRRLLLRRRLLLRRRLLL") == 3
    assert candidate(s = "LLRRLLRRLLRRLLRRLLRRLLRRLLRRLLRRLLRRLLRRLLRRLLRRLLRR") == 13
    assert candidate(s = "LRLRLRLRLRRRRLLLLRRRRLLLL") == 8
    assert candidate(s = "RLLLLRRRRLLRLRRLRRLLRLRLRL") == 10
    assert candidate(s = "RLRLRLRLRLRLRLRLRL") == 9
    assert candidate(s = "RLRRLLRLRRLLRLRRLLRLRRLLRLRLRRLLRLRRLLRLRLRR") == 15
    assert candidate(s = "RLRLRLRLRLRLRLRL") == 8
    assert candidate(s = "RLLLLRRRRLLRRRRLLR") == 4
    assert candidate(s = "RLRRLLRLRRLLRLRLRRLLRLRL") == 9
    assert candidate(s = "LRRLRLRLRLRLRLRLRL") == 9
    assert candidate(s = "RRRRRRLLLLLLRRRRLL") == 1
    assert candidate(s = "LLLLRRRRLLLLRRRRLLLLRRRRLLLLRRRRLLLLRRRR") == 5
    assert candidate(s = "RRLRRLRRLRRLRRLRRL") == 0
    assert candidate(s = "RLRRLLRLRRLLRLRLRRLLRLRLRRLLRLRLRRLLRLRL") == 15
    assert candidate(s = "RRRLLLLLRRRLLLLLRRRLLLLL") == 3
    assert candidate(s = "LRLRLRLRRRLLLLRRRLLLLRRRLRLR") == 10
    assert candidate(s = "LLRRLRRLRRLRRLRR") == 3
    assert candidate(s = "RLRLRLRLRLRLRLRLRLRL") == 10
    assert candidate(s = "RRRRLLLLRRRRLLLLRRRRLLLLRRRRLLLLRRRRLLLLRRRRLLLL") == 6
    assert candidate(s = "RLLLLLLLLLLLLLLLLRRRRRRRRRRRRRRRR") == 2
    assert candidate(s = "RRLLRRLRLRRLRLRR") == 1
    assert candidate(s = "RLRLRLRLRRRRLLLL") == 5
    assert candidate(s = "LRLRLRLRLRLRLRLRLR") == 9
    assert candidate(s = "RLLRRLLRRLLRRLLRRLLRRLLRRLLRRLLRRLLRRLLRRLL") == 21
    assert candidate(s = "LLLLLLLLRRRRRRRRLLLLLLLLRRRRRRRRLLLLLLLLRRRRRRRR") == 3
    assert candidate(s = "RLLLLRRRRLLLLRRRRLLLLRRRRLLLLRRRRLLLLRRRR") == 10
    assert candidate(s = "LRRRLLRRLRRRLLRRRLLR") == 2
    assert candidate(s = "RLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRL") == 16
    assert candidate(s = "LLLLRRRRRRRRLLLLRRRR") == 2
    assert candidate(s = "LLLLLLLLRRRRRRRRRRRRRRRR") == 1
    assert candidate(s = "LLRRRLLLLRRRRLLLLRRRR") == 5
    assert candidate(s = "LLRRLLRRLLLLRRRR") == 3
    assert candidate(s = "RLLRRLLRRLLRRLLRRLLRRLLRRLLRRLLRR") == 16
    assert candidate(s = "RRRRLLLLRRRRRRLLLLLLLLRRRRLLLLLLLLRRRRLLLL") == 4
    assert candidate(s = "RRRRLLLLLRRRRLLLLLRRRRLLLLLRRRRLLLLL") == 7
    assert candidate(s = "LLLLLLRRRRRRLLLLLLRRRRRRLLLLLLRRRRRR") == 3
    assert candidate(s = "RRRRRRLLLLLLRRRRRRLLLLLLRRRRRRLLLLLL") == 3
    assert candidate(s = "LRRRRLLLLLRRRRLLLLLRRRRLLLLLRRRRLLLLL") == 7
    assert candidate(s = "RLRRLLRLRLRLRRLLRLRLRRLLRLRL") == 11
    assert candidate(s = "LLLLRRRRLLLLRRRR") == 2
    assert candidate(s = "LLLLRRRRRLRRLLRRLLRRLLRRRRLLLLRRLLRRRRLLLLRRLLRR") == 9
    assert candidate(s = "RRRRRRLLLLLLLLRRRRRRLLLLLLLLRRRRRRLLLLLLLL") == 5
    assert candidate(s = "RRRRRRRRRRLLLLLLLLLLRRRRRRRRRRLLLLLLLLLL") == 2
    assert candidate(s = "LRRLRLRLRLRLRLRL") == 8
    assert candidate(s = "RRRLLRLLRRLRRLLRLLRR") == 2
    assert candidate(s = "RLRRLLRLRLRRLLRLRLRRLLRLRL") == 10
    assert candidate(s = "LLRRLLRRLLRRLLRRLLRRLLRR") == 6
    assert candidate(s = "LLLLRRRRLLLLRRRRLLLLRRRR") == 3
    assert candidate(s = "RRLLRRLLRRLLRRLLRRLL") == 5
    assert candidate(s = "RRRRLLLLRRRRLLLLRRRRLLLLRRRR") == 3
    assert candidate(s = "RLLLLLLLLLLLLLLRRRRRRRRRRRRRRRRRRRRLLLLLLLLLLLLL") == 3
    assert candidate(s = "LRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLR") == 26
    assert candidate(s = "RLRRLLRLRRLLRLRL") == 6
    assert candidate(s = "LRLRLRLRLRLRLRLR") == 8
    assert candidate(s = "RRLLRRLLRRLLRRLLRRLLRRLLRRLLRRLLRRLLRRLL") == 10
    assert candidate(s = "RLLLLRRRRRLRRRLLLLLRRRRRLLLL") == 5
    assert candidate(s = "RRLLRRLLRRLLRRLLRRLLRRLL") == 6
    assert candidate(s = "RRRRLLLLRRRRLLLLRRRRLLLLRRRRLLLL") == 4
    assert candidate(s = "LLLLLLLLLLLLRRRRRRRRRRRR") == 1
    assert candidate(s = "RRLLRLRLRRLLRLRL") == 6
    assert candidate(s = "RRRRRRRRLLLLLLLL") == 1
    assert candidate(s = "RLRRLLRLRLRLRRLLRLRRLLRLRL") == 10
    assert candidate(s = "LLRRLLRRLLRRLLRRLLRRLLRRLLRRLLRR") == 8
    assert candidate(s = "RLLLLLLLLLLLLRRRRRRRRRRRRR") == 2
    assert candidate(s = "LLLLRRRRRRRRLLLL") == 2
    assert candidate(s = "RRRLLLLRRRLLLLRRRLLLL") == 5
    assert candidate(s = "RLRRLLRLLRLRRLLRLR") == 8
    assert candidate(s = "RRRRLLLLRRRLLLLRRRRLLLLRRRLLLLRRRRLLLLRRRLLLLRRR") == 11
    assert candidate(s = "RLRRLLRLRLRRLLRLRL") == 7
    assert candidate(s = "RLRRLLRLRRLLRLRLRR") == 6
    assert candidate(s = "RRRRLLLLLLLLRRRRLLLL") == 2
    assert candidate(s = "RLRRRLRRRLRRRLRRRLRRRLRRRLRRRLRRRLRRRLRR") == 1
    assert candidate(s = "RRRRLLLLRRLLRRLLRRLLRRLL") == 5
    assert candidate(s = "RRRRRRRRLLLLLLLLRRRRRRRRLLLLLLLLRRRRRRRRLLLLLLLL") == 3
    assert candidate(s = "LLRRLLRRLLRRLLRR") == 4
    assert candidate(s = "LRRRLLLRRLRRLLRR") == 5
    assert candidate(s = "LLLLRRRRLLLLRRRRLLLLRRRRLLLLRRRR") == 4
    assert candidate(s = "RLRRLLRLRLRLRLRRLLRLRLRRLLRLRLRLRRLLRLRL") == 16
    assert candidate(s = "RLLLLRRRRLLRRLLRRLRRLRL") == 7
    assert candidate(s = "RRRRLLLLRRRRLLLLRRRRLLLL") == 3
    assert candidate(s = "RRLLLLRRLLLLRRLLLL") == 2
    assert candidate(s = "LRRLLRRLLRRLLRRLLRRLLRRLL") == 12
    assert candidate(s = "RLRRLLRLRRLLRLRRLLRLRRLL") == 8
    assert candidate(s = "LRRRRLLLLRRRRLLLL") == 4
    assert candidate(s = "RRRLLRLLRRRLLRLL") == 2
    assert candidate(s = "RLRLRLRLRLRRLLRRLLRLRLRLRL") == 11
    assert candidate(s = "LLRRLRRLRRLRRLRRLRRL") == 3
    assert candidate(s = "RRRRRRRRLLLLLLLLRRRRRRRRLLLLLLLL") == 2
    assert candidate(s = "RLLLLLRRRRLLRRRLLLRLLLLLRRRRRRLLLLRRRLLRRRRLLRLLL") == 8
    assert candidate(s = "LLLLLLLLLLLLLLLLRRRRRRRRRRRRRRRR") == 1
