# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(a = "abcdefg",b = "gfedcba") == True
    assert candidate(a = "abcxxcba",b = "abcdcba") == True
    assert candidate(a = "aabbcc",b = "ccbbdd") == True
    assert candidate(a = "ulacfd",b = "jizalu") == True
    assert candidate(a = "aabbaa",b = "aabbaa") == True
    assert candidate(a = "abba",b = "abba") == True
    assert candidate(a = "abcba",b = "abcba") == True
    assert candidate(a = "x",b = "y") == True
    assert candidate(a = "xbdef",b = "xecab") == False
    assert candidate(a = "abccba",b = "abccba") == True
    assert candidate(a = "noon",b = "noon") == True
    assert candidate(a = "race",b = "ecar") == True
    assert candidate(a = "abcd",b = "dcba") == True
    assert candidate(a = "aabbcc",b = "ccbbaa") == True
    assert candidate(a = "abc",b = "def") == False
    assert candidate(a = "abcde",b = "edcba") == True
    assert candidate(a = "abacaba",b = "bacabab") == True
    assert candidate(a = "rotor",b = "rotor") == True
    assert candidate(a = "noonappapoon",b = "poongggnop") == False
    assert candidate(a = "abacax",b = "xananaba") == False
    assert candidate(a = "abcdedcba",b = "afghihgfa") == True
    assert candidate(a = "abcdefghijk",b = "kjihgfedcba") == True
    assert candidate(a = "xyzzzzzxy",b = "yxzzzzzxy") == True
    assert candidate(a = "abcdabcdabcd",b = "dcbaedcbadcb") == False
    assert candidate(a = "aaaaabaaaa",b = "bbbbabbbbb") == False
    assert candidate(a = "abcdeedcba",b = "fghijijihgf") == True
    assert candidate(a = "rotorabc",b = "abcrotor") == True
    assert candidate(a = "abcdeffedcba",b = "mnopqrstsrqponm") == True
    assert candidate(a = "abac",b = "cab") == True
    assert candidate(a = "abcdexyzabc",b = "cbazyxcdeba") == True
    assert candidate(a = "abcdefgxyz",b = "zyxgfedcba") == True
    assert candidate(a = "abcdef",b = "fedcba") == True
    assert candidate(a = "aabbccddeeffgghhiijj",b = "jjiihhggfeeddccbaa") == True
    assert candidate(a = "abcdefgh",b = "hgfedcba") == True
    assert candidate(a = "xyzzxy",b = "yxzzyx") == True
    assert candidate(a = "mnopqr",b = "rqponm") == True
    assert candidate(a = "abcdefghij",b = "utvwxzyabc") == False
    assert candidate(a = "levelupx",b = "xyzlevol") == False
    assert candidate(a = "abcdefghijkjihgfedcba",b = "nopqrstuvwxyzzyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcba") == True
    assert candidate(a = "abcdefggfedcba",b = "xyzzyxzyxzyx") == True
    assert candidate(a = "aabbccddeeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",b = "zzyyxxwwvvuuttssrrqqponnmmllkkjjiihhggffeeddccbaabb") == False
    assert candidate(a = "abcdxyzabc",b = "cbazyxdcba") == True
    assert candidate(a = "abcxxy",b = "yxxcba") == True
    assert candidate(a = "abcdeedcba",b = "zzzzzzzzzz") == True
    assert candidate(a = "xyzzzzyx",b = "abcdef") == True
    assert candidate(a = "abcdefghijabc",b = "cbazyxwvut") == False
    assert candidate(a = "abcdedcba",b = "xyzdedcba") == True
    assert candidate(a = "abcdefg",b = "hgfedcb") == False
    assert candidate(a = "aabbccddeeefffggg",b = "gggfffeeeddccbbaa") == True
    assert candidate(a = "abcdefghij",b = "jihgfedcba") == True
    assert candidate(a = "abcdabcdeedcba",b = "zzzzzzzzzzzzzzzzzzzz") == True
    assert candidate(a = "abcdeffedcba",b = "xyzzyxwvutsrqponmlkjihgfedcba") == True
    assert candidate(a = "racecarx",b = "xmadam") == True
    assert candidate(a = "xyzzzzzyx",b = "abcdcba") == True
    assert candidate(a = "redivider",b = "repaidred") == True
    assert candidate(a = "aabbccddeeaabbccddee",b = "eeddccbbaaeeddccbbaa") == True
    assert candidate(a = "noon",b = "moon") == True
    assert candidate(a = "abababab",b = "babababa") == True
    assert candidate(a = "abacabadabacaba",b = "fedcbadcba") == True
    assert candidate(a = "zxcvbnm",b = "mlkjihg") == False
    assert candidate(a = "abcdefggfedcba",b = "abcdggfedcba") == True
    assert candidate(a = "qwertyuiop",b = "poiuytrewq") == True
    assert candidate(a = "zzzzzzzzzzz",b = "aaaaaaaaaaa") == True
    assert candidate(a = "aabbccddeeffgghhiijjkk",b = "kkjjiihhggfeeddccbaa") == True
    assert candidate(a = "noon",b = "racecar") == True
    assert candidate(a = "abcdex",b = "xcdeba") == False
    assert candidate(a = "zyxwvutsrqponmlkjihgfedcba",b = "abcdefghijklmnopqrstuvwxyz") == True
    assert candidate(a = "abccba",b = "abcdef") == True
    assert candidate(a = "abccba",b = "xyzzyx") == True
    assert candidate(a = "aabbccdd",b = "aabbccdd") == False
    assert candidate(a = "abcdabc",b = "cbadacb") == True
    assert candidate(a = "xyxzyxzyx",b = "yzxzyxzyz") == False
    assert candidate(a = "abcdexyz",b = "zyxcdeba") == False
    assert candidate(a = "abacaxbacad",b = "dadcabaxbacba") == False
    assert candidate(a = "abacaba",b = "zzzazzz") == True
    assert candidate(a = "aabbccdd",b = "ddeebbaa") == True
    assert candidate(a = "racecar",b = "level") == True
    assert candidate(a = "abcdefghij",b = "abcdefghij") == False
    assert candidate(a = "aaaa",b = "bbbb") == True
    assert candidate(a = "level",b = "deified") == True
    assert candidate(a = "abacdfgdcaba",b = "abacdgfdcaba") == True
    assert candidate(a = "abcdeabcde",b = "edcbaedcba") == True
    assert candidate(a = "abcdexyzzyxcdeba",b = "mnopqrstuutsrqpomn") == False
    assert candidate(a = "abxyzyxcba",b = "cdyxzyxdc") == False
    assert candidate(a = "madam",b = "refer") == True
    assert candidate(a = "aabbcc",b = "ccbaab") == True
    assert candidate(a = "abcddcba",b = "xyzzyx") == True
    assert candidate(a = "abracadabra",b = "arbadacarba") == True
    assert candidate(a = "abcddcba",b = "efghihgf") == True
    assert candidate(a = "abcdefxyzzyxcba",b = "pqrstuvwzyxwvutsrqp") == False
    assert candidate(a = "aaaabaaa",b = "bbbbbabb") == False
    assert candidate(a = "abacdfgdcaba",b = "abaffghffaba") == False
    assert candidate(a = "abacabad",b = "daadacab") == False
    assert candidate(a = "abcdexyz",b = "zyxeabcd") == True
    assert candidate(a = "abcdef",b = "xyzzzzyx") == True
    assert candidate(a = "abacdfgdcaba",b = "abcdcba") == True
    assert candidate(a = "abccba",b = "defedf") == True
    assert candidate(a = "xyzyx",b = "xzyzx") == True
    assert candidate(a = "palindrome",b = "emordnilap") == True
    assert candidate(a = "zzzzzzzzzzzzzzzzzz",b = "aaaaaaaaaaaaaaaa") == True
    assert candidate(a = "abccba",b = "defed") == True
    assert candidate(a = "abccba",b = "fghihgf") == True
    assert candidate(a = "tacocat",b = "racecar") == True
    assert candidate(a = "abcdef",b = "ghijkl") == False
    assert candidate(a = "aaaabbbb",b = "bbbbaaaa") == True
    assert candidate(a = "abcdefghihgfedcba",b = "abcdefghihgfedcba") == True
    assert candidate(a = "aabbccddeeff",b = "ffeeddccbbaa") == True
    assert candidate(a = "abcdexyzabcd",b = "dcbaxyzedcba") == False
    assert candidate(a = "abacabadabacaba",b = "abacabadabacaba") == True
    assert candidate(a = "abcxyzz",b = "zzzyxcba") == True
    assert candidate(a = "abacabadabacaba",b = "zzzzzzzzzzzzzzzzz") == True
    assert candidate(a = "abcabcabcabc",b = "cbacbacbacba") == True
    assert candidate(a = "abcxxa",b = "bxxcba") == True
    assert candidate(a = "racecar",b = "madam") == True
    assert candidate(a = "aaaaaaabbbbb",b = "bbbbbaaaaaaa") == True
    assert candidate(a = "abcdabcdabcd",b = "dcbaabcdabcd") == False
    assert candidate(a = "deifiedxx",b = "yytefified") == True
    assert candidate(a = "aaaaaaa",b = "bbbbbbb") == True
    assert candidate(a = "abab",b = "baba") == True
    assert candidate(a = "abcdeffedcba",b = "xyzzyxwxyzzyx") == True
    assert candidate(a = "abcdabcd",b = "dcbaabcd") == True
    assert candidate(a = "abcdeffedcba",b = "xyzzyxwvut") == True
    assert candidate(a = "abcdedcba",b = "mnopqrstuv") == True
    assert candidate(a = "abcdefghihgfedcba",b = "ijklmnopponmlkjihgf") == True
    assert candidate(a = "aabbcc",b = "zzxxzz") == True
    assert candidate(a = "abcdexyz",b = "zyxwvuts") == False
