# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "pppppppp") == 1
    assert candidate(s = "abcba") == 3
    assert candidate(s = "aabbaa") == 2
    assert candidate(s = "zzzzy") == 2
    assert candidate(s = "abababab") == 5
    assert candidate(s = "ppqpqr") == 4
    assert candidate(s = "a") == 1
    assert candidate(s = "abcabcabc") == 7
    assert candidate(s = "aabbc") == 3
    assert candidate(s = "aabaa") == 2
    assert candidate(s = "abcabc") == 5
    assert candidate(s = "abcdabcd") == 7
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnm") == 26
    assert candidate(s = "abcdabcdabcd") == 10
    assert candidate(s = "abc") == 3
    assert candidate(s = "abcd") == 4
    assert candidate(s = "aaabbb") == 2
    assert candidate(s = "zzzzyyyxx") == 3
    assert candidate(s = "aabbccddeeff") == 6
    assert candidate(s = "aba") == 2
    assert candidate(s = "aabbcc") == 3
    assert candidate(s = "abacaba") == 4
    assert candidate(s = "abca") == 3
    assert candidate(s = "abacabadabacabadabacaba") == 12
    assert candidate(s = "aabbaabbaabb") == 4
    assert candidate(s = "abababababaabababa") == 9
    assert candidate(s = "abcabcabcabc") == 9
    assert candidate(s = "abacabadabacabadabacabadabacabad") == 17
    assert candidate(s = "abcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefg") == 43
    assert candidate(s = "zzyzxzyzxzyzxzyzxzyzxzyzxzyz") == 14
    assert candidate(s = "aabbccddeeaabbccddeeaabbcc") == 11
    assert candidate(s = "aabbaaabbbaaa") == 3
    assert candidate(s = "abcdefghabcdeghijklmno") == 21
    assert candidate(s = "aaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbcccccccccccccccccc") == 3
    assert candidate(s = "aabbccddeeaabbccddeeaabbccddeeaabbcc") == 15
    assert candidate(s = "zzzzzyyyzzzzyyy") == 3
    assert candidate(s = "ababababababababababababababababababababababababababababababababababababababababababababa") == 45
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc") == 21
    assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij") == 46
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 33
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 26
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzz") == 26
    assert candidate(s = "abacabad") == 5
    assert candidate(s = "aaaabbbbccccddddeeeeaabbcc") == 7
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "abcabcabcabcabcabc") == 13
    assert candidate(s = "zzzzzzzzzzzzzzy") == 2
    assert candidate(s = "aabbccddeeffgghhii") == 9
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzy") == 2
    assert candidate(s = "abcdeffedcba") == 6
    assert candidate(s = "aaaaaaaaaabbbbbbbbccccccccddddddddeeeeeeeefffffffff") == 6
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 1
    assert candidate(s = "abcdefedcba") == 6
    assert candidate(s = "aabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabb") == 13
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 1
    assert candidate(s = "abababababababababababababab") == 15
    assert candidate(s = "abcdeedcbaedcbaedcba") == 13
    assert candidate(s = "abacabadabacaba") == 8
    assert candidate(s = "abababababababababababababababababababababababab") == 25
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbcccccccccc") == 3
    assert candidate(s = "aaabbbcccdddfffgggaaa") == 6
    assert candidate(s = "aaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbccccccccccccccccccccdddddddddddddddddd") == 4
    assert candidate(s = "zzyyxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccba") == 26
    assert candidate(s = "aabbccddeeffaabbccddeeffaabbccddeeffaabbccddeeff") == 21
    assert candidate(s = "abcdefghijihgfedcba") == 10
    assert candidate(s = "aabbccddeeaabbccddeeaabbccddeeee") == 13
    assert candidate(s = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz") == 33
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabad") == 21
    assert candidate(s = "aaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbccccccccccccccccccccddddddddddddddddddaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbcccccccccccccccccc") == 6
    assert candidate(s = "zzzyyxxwvvuuttrrqqppoonnmmllkkjjiihhggffeeddccbbaa") == 25
    assert candidate(s = "ababababababababababababab") == 14
    assert candidate(s = "aabbccddeeffgg") == 7
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabad") == 29
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 26
    assert candidate(s = "aabbccddeeffgghhiijj") == 10
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabad") == 25
    assert candidate(s = "abcdefg") == 7
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 26
    assert candidate(s = "abcabcabcabcabcabcabcabcaabbcc") == 19
    assert candidate(s = "abacabadabacabadabacabad") == 13
    assert candidate(s = "aaabaaabaaabaaabaaabaaabaaabaaabaaabaaabaaabaaab") == 13
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "abcbaabcbaabcba") == 7
    assert candidate(s = "aabbbcccdddaaabbccccddeee") == 8
    assert candidate(s = "aaaabbbbccccddddeeeeffffgggghhhhiiiijjjjkkkkllll") == 12
    assert candidate(s = "ababababab") == 6
    assert candidate(s = "abcddcba") == 4
    assert candidate(s = "aabbaabbccddeeffaabb") == 8
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcd") == 25
    assert candidate(s = "abcdefghihgfedcba") == 9
    assert candidate(s = "abcabcabcabcabcabcabcabcabc") == 19
    assert candidate(s = "abcabcabcabcabcabcabcabc") == 17
    assert candidate(s = "abcdabcdbaba") == 8
    assert candidate(s = "xyzyxzyzyxzyzyxzyz") == 11
    assert candidate(s = "abcdefghijhgfedcba") == 10
    assert candidate(s = "mississippi") == 5
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "ababababababababababababababababababababababababababa") == 27
    assert candidate(s = "abcabcabcabcabc") == 11
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 37
    assert candidate(s = "aabbccddeeaabbcc") == 7
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
