# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "bcdefghijklmnopqrstuvwxyza") == False
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "bcadefghijklmnopqrstuvwxzy") == False
    assert candidate(str1 = "leetcode",str2 = "codeleet") == False
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "abcdefghijklmnopqrstuvwxyz") == True
    assert candidate(str1 = "aaa",str2 = "aaa") == True
    assert candidate(str1 = "aabcc",str2 = "ccdee") == True
    assert candidate(str1 = "abc",str2 = "abc") == True
    assert candidate(str1 = "aabbcc",str2 = "bbccdd") == True
    assert candidate(str1 = "abc",str2 = "bcd") == True
    assert candidate(str1 = "zzzz",str2 = "aaaa") == True
    assert candidate(str1 = "zzz",str2 = "aaa") == True
    assert candidate(str1 = "abac",str2 = "bcbd") == True
    assert candidate(str1 = "abcd",str2 = "abcf") == True
    assert candidate(str1 = "abcd",str2 = "dddd") == True
    assert candidate(str1 = "abcabcabcabcabc",str2 = "defdefdefdefdef") == True
    assert candidate(str1 = "xyzz",str2 = "zzxy") == False
    assert candidate(str1 = "exampleexample",str2 = "fyemplyfyemply") == False
    assert candidate(str1 = "aaaabbbbccccdddd",str2 = "bbbbccccddddeeee") == True
    assert candidate(str1 = "aaaabbbb",str2 = "ccccdddd") == True
    assert candidate(str1 = "abcdefg",str2 = "ghijklm") == True
    assert candidate(str1 = "mississippi",str2 = "nittinnttin") == False
    assert candidate(str1 = "abcdefghijklnopqrstuvwxyz",str2 = "bcdefghijklnopqrstuvwxyza") == True
    assert candidate(str1 = "mississippi",str2 = "bbbbbbbbbba") == False
    assert candidate(str1 = "abcabcabcabc",str2 = "defdefdefdef") == True
    assert candidate(str1 = "abcdefghij",str2 = "jihgfedcba") == True
    assert candidate(str1 = "abcdefghij",str2 = "abcdefghij") == True
    assert candidate(str1 = "transform",str2 = "formtrans") == False
    assert candidate(str1 = "abacabadabacaba",str2 = "xyxyxyxyxyxyxyx") == True
    assert candidate(str1 = "aabbcc",str2 = "aabbcc") == True
    assert candidate(str1 = "thisisatest",str2 = "thisisbtest") == True
    assert candidate(str1 = "abcdefghijklmnop",str2 = "bcadefghijklmnop") == True
    assert candidate(str1 = "abacabadabacaba",str2 = "xyzxyzxyzxyzxyz") == False
    assert candidate(str1 = "abcdabcd",str2 = "dcbaabdc") == False
    assert candidate(str1 = "abcdabcd",str2 = "dcbaabcd") == False
    assert candidate(str1 = "ababababab",str2 = "bababababa") == True
    assert candidate(str1 = "character",str2 = "haracteerc") == False
    assert candidate(str1 = "abcdef",str2 = "fedcba") == True
    assert candidate(str1 = "aaaaaaaaaaaaaaaaaaaa",str2 = "bbbbbbbbbbbbbbbbbbbb") == True
    assert candidate(str1 = "uniquestring",str2 = "stringunique") == False
    assert candidate(str1 = "ababab",str2 = "xyzxyz") == False
    assert candidate(str1 = "abcde",str2 = "fghij") == True
    assert candidate(str1 = "aabbccddeeff",str2 = "bbccddeeffgg") == True
    assert candidate(str1 = "abcdefgh",str2 = "abcdefgh") == True
    assert candidate(str1 = "abcabcabc",str2 = "defdefdef") == True
    assert candidate(str1 = "abacabadabacaba",str2 = "xyzxyxzyxzyxzzy") == False
    assert candidate(str1 = "abcabcabcabcabcabc",str2 = "xyzxyzxyzxyzxyzxyz") == True
    assert candidate(str1 = "abcabcabcabcabcabcabc",str2 = "xyzxyzxyzxyzxyzxyzxyz") == True
    assert candidate(str1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",str2 = "zzxxwwvvuuttssrrqqlloonnmmkkjjiihhggffeeddccbaa") == False
    assert candidate(str1 = "circular",str2 = "ircularc") == False
    assert candidate(str1 = "aabcc",str2 = "bbaad") == False
    assert candidate(str1 = "thisisatest",str2 = "tististest") == False
    assert candidate(str1 = "abcdefghijabcdefghij",str2 = "jihgfedcbajihgfedcba") == True
    assert candidate(str1 = "xyzz",str2 = "zzzx") == False
    assert candidate(str1 = "multipleoccurrences",str2 = "llliiuuutececcurren") == False
    assert candidate(str1 = "abcdefghij",str2 = "jabcdefghi") == True
    assert candidate(str1 = "transform",str2 = "transfrme") == False
    assert candidate(str1 = "qwertyuiop",str2 = "poiuytrewq") == True
    assert candidate(str1 = "abcdabcdabcdabcd",str2 = "xyzaxyzaxyzaxyza") == True
    assert candidate(str1 = "abababab",str2 = "babababa") == True
    assert candidate(str1 = "aabbccddeeff",str2 = "ffeeddccbaaa") == False
    assert candidate(str1 = "sameple",str2 = "samplee") == False
    assert candidate(str1 = "xyzxyzxyz",str2 = "zyxzyxzyx") == True
    assert candidate(str1 = "aaaaabbbbcccccdddddeeeee",str2 = "eeeeeaaaaabbbbcccccdddd") == False
    assert candidate(str1 = "abacabadabacabad",str2 = "xyzxyzxyzxyz") == False
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyza",str2 = "bcdefghijklmnopqrstuvwxyza") == False
    assert candidate(str1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",str2 = "zzxxwwvvuuttrrssqqppoonnmmllkkjjiihhggffeeddccbbaa") == True
    assert candidate(str1 = "abababab",str2 = "acacacac") == True
    assert candidate(str1 = "mississippi",str2 = "ssissippi") == False
    assert candidate(str1 = "samelettereverywhere",str2 = "samelettereverywhere") == True
    assert candidate(str1 = "transform",str2 = "convert") == True
    assert candidate(str1 = "repeated",str2 = "prepearde") == False
    assert candidate(str1 = "aaaaaaabbbbbbbcccccc",str2 = "ccccccccdddddddddddd") == False
    assert candidate(str1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",str2 = "zyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcba") == False
    assert candidate(str1 = "transform",str2 = "formation") == True
    assert candidate(str1 = "almostthere",str2 = "almoszthere") == False
    assert candidate(str1 = "abacabadabacaba",str2 = "xyzxyzxyxzyzxzy") == False
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyz",str2 = "zyxwvutsrqponmlkjihgfedcba") == False
    assert candidate(str1 = "abcdefghijabcdefghij",str2 = "abcdefghijabcdefghij") == True
    assert candidate(str1 = "abacabadabacaba",str2 = "xyzxyxzyxzyxzyxzy") == False
    assert candidate(str1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",str2 = "zzyyxxwwvvuuttrrssqqppoonnmmllkkjjiihhggffeeddccbbaa") == False
    assert candidate(str1 = "allcharacters",str2 = "llcharactera") == False
    assert candidate(str1 = "conversionexample",str2 = "exampleremnoscvoi") == False
    assert candidate(str1 = "transformable",str2 = "formabletra") == False
    assert candidate(str1 = "abababab",str2 = "bcbcbcbc") == True
    assert candidate(str1 = "unique",str2 = "euinque") == False
    assert candidate(str1 = "xyzxyzxyzxyz",str2 = "zyxzyxzyxzyxzyxzyx") == True
    assert candidate(str1 = "conversion",str2 = "conversions") == True
    assert candidate(str1 = "mnopqr",str2 = "nopqrm") == True
    assert candidate(str1 = "allcharacters",str2 = "llcharactersa") == False
    assert candidate(str1 = "abcdefgh",str2 = "hgfedcba") == True
    assert candidate(str1 = "aabbccddeeffgg",str2 = "hhiggeeffdccbbaa") == False
    assert candidate(str1 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ",str2 = "zyxwvutsrqponmlkjihgfedcba") == False
    assert candidate(str1 = "verylongstringthatweneedmorecomplexity",str2 = "vyerlongstrngthatweneedmorecmplxty") == False
    assert candidate(str1 = "almostthesame",str2 = "almostthesame") == True
    assert candidate(str1 = "mississippi",str2 = "ppississippi") == False
    assert candidate(str1 = "uniquestring",str2 = "uniqegstring") == False
    assert candidate(str1 = "mnopqr",str2 = "nopqrs") == True
    assert candidate(str1 = "aaaabbbbccccdddd",str2 = "wwwwxxxyyyyzzzz") == False
    assert candidate(str1 = "transformation",str2 = "artifomncstion") == False
    assert candidate(str1 = "unconvertible",str2 = "convertiblenu") == False
    assert candidate(str1 = "abacabadaba",str2 = "acacacacaca") == True
    assert candidate(str1 = "abcabcabcabc",str2 = "xyzxyzxyzxyz") == True
    assert candidate(str1 = "zyxwvutsrqponmlkjihgfedcba",str2 = "abcdefghijklmnopqrstuvwxyz") == False
    assert candidate(str1 = "puzzling",str2 = "uzzlingp") == False
    assert candidate(str1 = "allcharactersareunique",str2 = "quenihartseacrrulaaa") == False
    assert candidate(str1 = "mississippi",str2 = "ppiimssissi") == False
    assert candidate(str1 = "aaaaaaaaaa",str2 = "bbbbbbbbbb") == True
    assert candidate(str1 = "samestrings",str2 = "samestrings") == True
    assert candidate(str1 = "abcdabcdabcdabcd",str2 = "wxyzwxyzwxyzwxyz") == True
    assert candidate(str1 = "conversion",str2 = "onversionc") == False
    assert candidate(str1 = "mississippi",str2 = "hhhhhhhhhii") == False
    assert candidate(str1 = "abcdeabcde",str2 = "edcbaedcba") == True
    assert candidate(str1 = "zzzzzzzz",str2 = "yyyyyyzz") == False
    assert candidate(str1 = "abcdefghijklmnopqrstuvwxyzz",str2 = "bcdefghijklmnopqrstuvwxyzz") == True
    assert candidate(str1 = "abcdefgabcdefg",str2 = "gfedcbagfedcba") == True
    assert candidate(str1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",str2 = "bbaacceeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == True
    assert candidate(str1 = "abcdabcd",str2 = "xyzaxyzaxyza") == True
    assert candidate(str1 = "aaaaaabbbbbbccccccdddddd",str2 = "eeeeeeffffffgggggg") == True
    assert candidate(str1 = "aaaabbbbcccc",str2 = "ddddeeeeffff") == True
    assert candidate(str1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",str2 = "abcdefghijklmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba") == False
    assert candidate(str1 = "repeatedconversions",str2 = "eevnorseducepntr") == False
    assert candidate(str1 = "aabbbcccddeefffgghhiijjkkklllmmmnnnnoopppqqqqrrrrsstttuuuuvvvvwwwwxxxxyyyyzzzz",str2 = "zzzyyxxxwwwwvvvvuuuuuuuuuuuuttttrrrrrqqqqppppoonnnnmmmlllkkkjjjiiihhhgggffffffeeecccbbaaa") == False
    assert candidate(str1 = "samecharacters",str2 = "amecharacterss") == False
    assert candidate(str1 = "justonechar",str2 = "different") == True
