# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abcabcabc",k = 5) == 3
    assert candidate(s = "aaabcccd",k = 2) == 4
    assert candidate(s = "aabcc",k = 1) == 4
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 20) == 32
    assert candidate(s = "aabccabcc",k = 2) == 5
    assert candidate(s = "nnnhoorq",k = 2) == 5
    assert candidate(s = "aaaaaaaaaaa",k = 0) == 3
    assert candidate(s = "aabbaa",k = 2) == 2
    assert candidate(s = "abbbcccaaaa",k = 3) == 5
    assert candidate(s = "abbbabbbcabbbabbbb",k = 3) == 6
    assert candidate(s = "aabbccddeeff",k = 6) == 6
    assert candidate(s = "abababababababababababababababababababab",k = 15) == 12
    assert candidate(s = "a",k = 0) == 1
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz",k = 10) == 3
    assert candidate(s = "aabbbcccbbaa",k = 3) == 6
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 10) == 3
    assert candidate(s = "abcdabcdabcd",k = 6) == 5
    assert candidate(s = "a",k = 1) == 0
    assert candidate(s = "aabbcc",k = 1) == 5
    assert candidate(s = "aabcccccaaa",k = 2) == 5
    assert candidate(s = "abcde",k = 2) == 3
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcd",k = 15) == 21
    assert candidate(s = "aabbccddeeff",k = 4) == 8
    assert candidate(s = "abcdefghijaaaaaaaaaaaaaa",k = 5) == 8
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzzzzzz",k = 30) == 23
    assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij",k = 25) == 64
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd",k = 30) == 14
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq",k = 35) == 18
    assert candidate(s = "mississippi",k = 3) == 6
    assert candidate(s = "aaaaaabbbbccccddddeeeeffffgggghhhh",k = 8) == 12
    assert candidate(s = "xyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxy",k = 15) == 58
    assert candidate(s = "abacabadabacaba",k = 5) == 6
    assert candidate(s = "xyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyx",k = 30) == 25
    assert candidate(s = "xyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 25) == 3
    assert candidate(s = "aaabbbcccddddeeefffggghhhiiijjjkkklllmmmnnnooopppqqqrrrssstttuuuvvvwwwww",k = 30) == 26
    assert candidate(s = "aabbaabbaabbaabbaabbaabbcccccccccccdddddddddd",k = 20) == 6
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd",k = 5) == 8
    assert candidate(s = "mnopqrstuvmnopqrstuvmnopqrstuvmnopqrstuvmnopqrstuvmnopqrstuvmnopqrstuvmnopqrstuvmnopq",k = 10) == 75
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzz",k = 10) == 18
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",k = 25) == 53
    assert candidate(s = "aaabaaaacaaadaaaeaaafaaagaaahaaaiaaa",k = 10) == 3
    assert candidate(s = "xyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxy",k = 25) == 26
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 30) == 3
    assert candidate(s = "abcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcde",k = 25) == 60
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnm",k = 10) == 16
    assert candidate(s = "abababababab",k = 3) == 7
    assert candidate(s = "zzzzzyyyyyxxxyyyxxxxzzzzzzz",k = 15) == 3
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd",k = 20) == 55
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 26) == 26
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabc",k = 15) == 15
    assert candidate(s = "ppppppppppqqqqqqqqqqrrrrrrrrrrsssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",k = 50) == 3
    assert candidate(s = "abbbcccdddeeeeeffgggghhhiiijjjjj",k = 10) == 12
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 25) == 3
    assert candidate(s = "aabbaacccaaadd",k = 4) == 6
    assert candidate(s = "abbbccccddee",k = 4) == 5
    assert candidate(s = "abababababababababababababababababababababababababababababababababababababababababababab",k = 20) == 50
    assert candidate(s = "aaaaaaaaaabbbbbbbbbccccccccddddddddeeeeeeeeeffffffffgggggggghhhhhhhhiiiiiiiiijjjjjjj",k = 25) == 14
    assert candidate(s = "pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",k = 30) == 3
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",k = 25) == 27
    assert candidate(s = "ababababababababababababababababababababab",k = 10) == 24
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd",k = 15) == 6
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 30) == 3
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc",k = 5) == 24
    assert candidate(s = "xyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxy",k = 30) == 26
    assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij",k = 20) == 59
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcd",k = 12) == 13
    assert candidate(s = "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",k = 45) == 3
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 0) == 52
    assert candidate(s = "abcdefg",k = 3) == 4
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 10) == 3
    assert candidate(s = "aabbaabbaabbaabbaabbaabb",k = 10) == 4
    assert candidate(s = "xyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 50) == 0
    assert candidate(s = "xyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxy",k = 20) == 52
    assert candidate(s = "abababababababababababababab",k = 10) == 10
    assert candidate(s = "pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",k = 50) == 3
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzz",k = 40) == 13
    assert candidate(s = "aaaaabbbbbaaaaabbbbbaaaaabbbbbaaaaabbbbbaaaaa",k = 10) == 11
    assert candidate(s = "aaaaaaaaaabbbbbbbbbcccccdddddeeeeeeeeeeee",k = 20) == 5
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",k = 15) == 37
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee",k = 10) == 10
    assert candidate(s = "ppppppqqqqqqqqqqqqqqqqqqqqqqrrrrrrrrrrrrrrrrsssssssssssttttttttttt",k = 30) == 6
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 10) == 3
    assert candidate(s = "aaaaaaaaaaabbbbbbbbbbbccccccccccdddddddddd",k = 10) == 8
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeffffffffffgggggggggg",k = 25) == 10
