# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "AALL") == False
    assert candidate(s = "LLA") == True
    assert candidate(s = "PPALLPLL") == True
    assert candidate(s = "PLPLPL") == True
    assert candidate(s = "PA") == True
    assert candidate(s = "LLLLL") == False
    assert candidate(s = "LPPALLP") == True
    assert candidate(s = "PPALLP") == True
    assert candidate(s = "PPALLL") == False
    assert candidate(s = "ALPALP") == False
    assert candidate(s = "LLLP") == False
    assert candidate(s = "ALP") == True
    assert candidate(s = "AA") == False
    assert candidate(s = "PLLPLL") == True
    assert candidate(s = "PPPLLL") == False
    assert candidate(s = "LLL") == False
    assert candidate(s = "ALLL") == False
    assert candidate(s = "AAA") == False
    assert candidate(s = "A") == True
    assert candidate(s = "PPPPPPP") == True
    assert candidate(s = "LL") == True
    assert candidate(s = "ALPLL") == True
    assert candidate(s = "PPPPPP") == True
    assert candidate(s = "AALLPPP") == False
    assert candidate(s = "AALPLL") == False
    assert candidate(s = "PL") == True
    assert candidate(s = "PLLPLP") == True
    assert candidate(s = "PPALLAP") == False
    assert candidate(s = "ALLAPL") == False
    assert candidate(s = "PPALLAPA") == False
    assert candidate(s = "PPA") == True
    assert candidate(s = "AAAA") == False
    assert candidate(s = "AP") == True
    assert candidate(s = "APLLAA") == False
    assert candidate(s = "L") == True
    assert candidate(s = "PPLLP") == True
    assert candidate(s = "PPAALP") == False
    assert candidate(s = "P") == True
    assert candidate(s = "PPPP") == True
    assert candidate(s = "APLPALPPAL") == False
    assert candidate(s = "PPALLAPLPP") == False
    assert candidate(s = "AAPAAPA") == False
    assert candidate(s = "PPPPLLLPPP") == False
    assert candidate(s = "APLLPPPPPPPLL") == True
    assert candidate(s = "ALLPPAAPLPLP") == False
    assert candidate(s = "PLLLPLPLLPLLPPP") == False
    assert candidate(s = "APLPLPALPLPALPPPP") == False
    assert candidate(s = "AALLPPAPLALLPP") == False
    assert candidate(s = "APLLLLP") == False
    assert candidate(s = "APLPLPALPLPALPP") == False
    assert candidate(s = "LLLLPPPAPPLPPP") == False
    assert candidate(s = "ALALALAL") == False
    assert candidate(s = "APALLPAPL") == False
    assert candidate(s = "PPPPPPPPPPPP") == True
    assert candidate(s = "AAPALLPPALL") == False
    assert candidate(s = "PPPLLLLPP") == False
    assert candidate(s = "ALPPALP") == False
    assert candidate(s = "PPLPPPLLPPA") == True
    assert candidate(s = "PLLPLLPLLPLLPLLPLLPLL") == True
    assert candidate(s = "ALPLLPLLPLLPLLPLLPLLPLLPLL") == True
    assert candidate(s = "LPLPLPLPLPLPLP") == True
    assert candidate(s = "PPLPPPLPPLLPPP") == True
    assert candidate(s = "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLP") == False
    assert candidate(s = "AALPLPLLPLL") == False
    assert candidate(s = "PLPPPLPPPL") == True
    assert candidate(s = "PPLPPLPLL") == True
    assert candidate(s = "PPPPPPLPPPP") == True
    assert candidate(s = "PPALLPALPPALLP") == False
    assert candidate(s = "LPLLPLLPLLPLLPLLPLLPLLPLL") == True
    assert candidate(s = "PPLPPPLPPPLPPPLPPPLPPPLPPPLPPPLPPPLPPPLPPPLPPPLPPPLPPPLPPP") == True
    assert candidate(s = "PLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLLPLP") == True
    assert candidate(s = "PPALPPALPP") == False
    assert candidate(s = "PLPLPLPLPLPL") == True
    assert candidate(s = "PLAPLLPLPAL") == False
    assert candidate(s = "LLPALPALPALP") == False
    assert candidate(s = "LLLLLPLPPPPP") == False
    assert candidate(s = "AAPAPAPAPAPAPAPAPAPAPAPAPAPAPAPAPAPA") == False
    assert candidate(s = "APLALPALPALP") == False
    assert candidate(s = "PLLPPLPLLPLLPPP") == True
    assert candidate(s = "ALLPPAPL") == False
    assert candidate(s = "PPLPPPLPPLLPPPPP") == True
    assert candidate(s = "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP") == True
    assert candidate(s = "APLPLPLLAPA") == False
    assert candidate(s = "PLLPLLPLLPLL") == True
    assert candidate(s = "AAPLAPPLAPLPPP") == False
    assert candidate(s = "PLPLPLPLPLLPPPLP") == True
    assert candidate(s = "LPLLPLLPLL") == True
    assert candidate(s = "PPPPPPPPLLLPPPPP") == False
    assert candidate(s = "APALPPALPPAL") == False
    assert candidate(s = "PLLAPLLP") == True
    assert candidate(s = "ALALALALALALAL") == False
    assert candidate(s = "ALALALALALAL") == False
    assert candidate(s = "APLPLPALPLPA") == False
    assert candidate(s = "PLLPPLLPLPLL") == True
    assert candidate(s = "LLAALLLLPLLPPP") == False
    assert candidate(s = "LLPPPPPPPPPPPPPPPPPPPPPPPPPPPPLLPPPPPP") == True
    assert candidate(s = "PPALLPA") == False
    assert candidate(s = "PPPPPPPPPPPPLL") == True
    assert candidate(s = "PLPLPLPLPLLPPPA") == True
    assert candidate(s = "PLLALPPLPLL") == True
    assert candidate(s = "APAPAPAPAP") == False
    assert candidate(s = "PPALLLPPALLP") == False
    assert candidate(s = "LLPLLLP") == False
    assert candidate(s = "LLPPPPPPPPPP") == True
    assert candidate(s = "PPAPAPAP") == False
    assert candidate(s = "PPALLPLPA") == False
    assert candidate(s = "PLPLPLPLPL") == True
    assert candidate(s = "PPALLPLLALLPP") == False
    assert candidate(s = "PPLPPPPPLP") == True
    assert candidate(s = "AAPPPPPPPPPPPPPPPPPPPPPPPPPPPPPLLPPPPPP") == False
    assert candidate(s = "PPPPPPPPPPPPPPPPPPPPPPP") == True
    assert candidate(s = "PLPLLPLLPLLAP") == True
    assert candidate(s = "AAAAAAAA") == False
    assert candidate(s = "LLAALLAALLAALLAALLAALLAALLAALLAALLAALLAALLAALLAALLAALLAALL") == False
    assert candidate(s = "PALPALPALP") == False
    assert candidate(s = "ALLPLALPA") == False
    assert candidate(s = "PPPPPLPPPPLL") == True
    assert candidate(s = "PAPAPAPAPA") == False
    assert candidate(s = "PPPLAPLLPA") == False
    assert candidate(s = "PLPPPPLPPPLPPP") == True
    assert candidate(s = "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPLLL") == False
    assert candidate(s = "PALLPLLP") == True
    assert candidate(s = "LLPPLLPLP") == True
    assert candidate(s = "LLPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP") == True
    assert candidate(s = "PPALLPLLPLPPP") == True
    assert candidate(s = "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPAL") == True
    assert candidate(s = "PLALLAPLLP") == False
    assert candidate(s = "LLAAPLLAALLP") == False
    assert candidate(s = "ALPLPALPALLP") == False
    assert candidate(s = "PPPPPPPPPPPPPPPPPPPPPPPPPPPPP") == True
    assert candidate(s = "PPALPLPLPLPA") == False
    assert candidate(s = "PLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLL") == True
    assert candidate(s = "PPPLLPPPLLPPPLL") == True
    assert candidate(s = "AAAAAAAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP") == False
    assert candidate(s = "AAAAA") == False
    assert candidate(s = "PPPLAALLPPPL") == False
    assert candidate(s = "LPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLLPLP") == True
    assert candidate(s = "PALPALPALPAL") == False
    assert candidate(s = "PAALPAALPPA") == False
    assert candidate(s = "ALALALALAL") == False
    assert candidate(s = "LLALALALALL") == False
    assert candidate(s = "PLLPPPLLPPPPPPLL") == True
    assert candidate(s = "LLLL") == False
    assert candidate(s = "PLPLLPLLPLLPLLPLLPL") == True
    assert candidate(s = "PPPPPLPPPPLP") == True
    assert candidate(s = "LLLPLLPPP") == False
    assert candidate(s = "PLLPLLPLL") == True
    assert candidate(s = "PPALLPLLPA") == False
    assert candidate(s = "PPPPPPPPPPPPPPLL") == True
    assert candidate(s = "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPLL") == True
    assert candidate(s = "PLPPPPLPPPPPP") == True
    assert candidate(s = "AAPAAPAAPAAPAP") == False
    assert candidate(s = "APAPAPAPAPAP") == False
    assert candidate(s = "AAPPLL") == False
    assert candidate(s = "PPAALLL") == False
    assert candidate(s = "PPAPLPLAPL") == False
    assert candidate(s = "LLLLPPLP") == False
    assert candidate(s = "PPALLPLLAP") == False
    assert candidate(s = "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP") == True
    assert candidate(s = "PPPLLLPPPLLPP") == False
    assert candidate(s = "ALLPPLLAPL") == False
    assert candidate(s = "PPALLPLLALLL") == False
    assert candidate(s = "PLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLP") == True
    assert candidate(s = "PPPPPPPPPPLL") == True
    assert candidate(s = "PPLPALPALPAL") == False
    assert candidate(s = "PPALLLL") == False
    assert candidate(s = "LLPLLLPLL") == False
    assert candidate(s = "PPAALPPALLP") == False
    assert candidate(s = "PLAPLLPLPAPL") == False
    assert candidate(s = "LLPPLLPLPLLPLL") == True
    assert candidate(s = "PLLAPPPALPLL") == False
    assert candidate(s = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALLL") == False
    assert candidate(s = "PAPAPAPAPAPAPAPAPAPA") == False
    assert candidate(s = "LLPPALLPLL") == True
    assert candidate(s = "LLLLPPL") == False
    assert candidate(s = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA") == False
    assert candidate(s = "PPPLPPPPLLPPPLL") == True
    assert candidate(s = "PPALLALPLAL") == False
    assert candidate(s = "PPALLPLLALLP") == False
    assert candidate(s = "LLPPLLPLL") == True
    assert candidate(s = "LLPLLPALL") == True
