# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "zxyxzyxzyxz") == 26
    assert candidate(s = "abcba") == 7
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "abaacababa") == 28
    assert candidate(s = "abababab") == 20
    assert candidate(s = "aaaaa") == 15
    assert candidate(s = "a") == 1
    assert candidate(s = "aabcaabxcaabcxaabcaabc") == 88
    assert candidate(s = "abcabcabc") == 18
    assert candidate(s = "ababababab") == 30
    assert candidate(s = "aaa") == 6
    assert candidate(s = "zzz") == 6
    assert candidate(s = "abba") == 6
    assert candidate(s = "aaaabbbbcccc") == 30
    assert candidate(s = "zzzzzzzzzz") == 55
    assert candidate(s = "banana") == 10
    assert candidate(s = "abacad") == 9
    assert candidate(s = "aaabaaa") == 22
    assert candidate(s = "mississippi") == 24
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 78
    assert candidate(s = "xyzzyx") == 9
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba") == 26
    assert candidate(s = "abcdefg") == 7
    assert candidate(s = "rhythms") == 8
    assert candidate(s = "zzyxwwxyzzzxxzzzywxyz") == 76
    assert candidate(s = "abcdabcdabcdabcdabcd") == 60
    assert candidate(s = "madam") == 7
    assert candidate(s = "abacaxbacab") == 25
    assert candidate(s = "deified") == 10
    assert candidate(s = "abacabadabacabadabacabad") == 111
    assert candidate(s = "aabbaabbaabbaabbaabb") == 110
    assert candidate(s = "repaper") == 10
    assert candidate(s = "aabbaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzz") == 125
    assert candidate(s = "aabbaa") == 13
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 820
    assert candidate(s = "aabbbaabbbaabbbaabbb") == 114
    assert candidate(s = "kayak") == 7
    assert candidate(s = "nootnootnootnootnootnoot") == 120
    assert candidate(s = "abacabadabacaba") == 50
    assert candidate(s = "abbaabbaabbaabba") == 72
    assert candidate(s = "abracadabra") == 23
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc") == 165
    assert candidate(s = "thefactisthatthefactisthat") == 71
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm") == 78
    assert candidate(s = "aabbaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzz") == 104
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz") == 210
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd") == 220
    assert candidate(s = "abcdabcabc") == 19
    assert candidate(s = "aaaaaaaaaa") == 55
    assert candidate(s = "rotor") == 7
    assert candidate(s = "abbaabbaabbaabbaabba") == 110
    assert candidate(s = "racecar") == 10
    assert candidate(s = "aabbaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzz") == 117
    assert candidate(s = "abcdeedcbaabcdeedcba") == 50
    assert candidate(s = "aabbaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzz") == 110
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnmnbvcxzlkjhgfdsapoiuytrewq") == 76
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 78
    assert candidate(s = "abcdefghijabcdefghijabcdefghij") == 60
    assert candidate(s = "noon") == 6
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzz") == 85
    assert candidate(s = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyz") == 165
    assert candidate(s = "reviled") == 8
    assert candidate(s = "xyzzyxzyxzyxzyxzyxzyx") == 84
    assert candidate(s = "pneumonoultramicroscopicsilicovolcanoconiosis") == 131
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnmqwertyuiop") == 46
    assert candidate(s = "aabbaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 92
    assert candidate(s = "abcdeffedcba") == 18
    assert candidate(s = "redder") == 9
    assert candidate(s = "reviver") == 10
    assert candidate(s = "xyzxyzxyzxyzxyz") == 45
    assert candidate(s = "nflibpnflibpnflibp") == 36
    assert candidate(s = "abcabcabcabcabc") == 45
    assert candidate(s = "aaaaabbbbbccccdddddeeeee") == 70
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 2346
    assert candidate(s = "level") == 7
    assert candidate(s = "abccbaabccbaabccbaabccbaabccba") == 165
    assert candidate(s = "racecarcarcar") == 31
    assert candidate(s = "refer") == 7
