# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "wordgoodgoodgoodbestword",words = ['word', 'good', 'best', 'word']) == []
    assert candidate(s = "a",words = ['a', 'a', 'a']) == []
    assert candidate(s = "abababab",words = ['a', 'b', 'a', 'b']) == [0, 1, 2, 3, 4]
    assert candidate(s = "lingmindraboofooowingdingbarrwingmonkeypoundcake",words = ['fooo', 'barr', 'wing', 'ding', 'wing']) == [13]
    assert candidate(s = "barfoothefoobarman",words = ['foo', 'bar']) == [0, 9]
    assert candidate(s = "barfoofoobarthefoobarman",words = ['bar', 'foo', 'the']) == [6, 9, 12]
    assert candidate(s = "aaa",words = ['a', 'a']) == [0, 1]
    assert candidate(s = "thisisjustafancysentencewithallthesewordsin",words = ['this', 'is', 'a', 'just', 'fancy', 'sentence', 'with', 'all', 'these', 'words', 'in']) == []
    assert candidate(s = "overlaplaplaplaplaplaplaplaplaplap",words = ['lap', 'laplap', 'laplap', 'laplap', 'laplap', 'laplap', 'laplap', 'laplap']) == []
    assert candidate(s = "abcdefabcdefabcdefabcdefabcdef",words = ['abcdef', 'abcdef', 'abcdef', 'abcdef', 'abcdef']) == [0]
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",words = ['aabb', 'ccdd', 'eefg', 'ghhi', 'jklk', 'llmm', 'nnoo', 'pqqr', 'rstt', 'uuvv', 'wwxx', 'yyzz']) == []
    assert candidate(s = "oneonetwoonethreetwothreeonetwothreeone",words = ['one', 'two', 'three']) == []
    assert candidate(s = "abcdefgabcdefgabcdefg",words = ['abc', 'def', 'gab', 'cde', 'fgh']) == []
    assert candidate(s = "zazbzczdzazbzczdzaz",words = ['zaz', 'bz', 'cz', 'dz', 'az', 'bz', 'cz', 'dz']) == []
    assert candidate(s = "onetwothreefourfivesixseveneightnine",words = ['onetwo', 'threefour', 'fivesix', 'seveneight', 'ninetwo', 'threefour', 'fivesix']) == []
    assert candidate(s = "zzzzzzzzzzzzzzzzzz",words = ['zzz', 'zzz', 'zzz', 'zzz']) == [0, 3, 6, 1, 4, 2, 5]
    assert candidate(s = "abcdefghijabcdefghijabcdefghij",words = ['abc', 'def', 'ghi', 'jkl', 'abc', 'def', 'ghi', 'jkl', 'abc', 'def']) == []
    assert candidate(s = "abcdabcdabcdabcd",words = ['abcd', 'dcba', 'abdc', 'bacd']) == []
    assert candidate(s = "testtesttesttest",words = ['test', 'test', 'test']) == [0, 4]
    assert candidate(s = "alibabacloudisfastgrowing",words = ['ali', 'ba', 'ba', 'cloud', 'is', 'fast', 'grow', 'ing']) == []
    assert candidate(s = "mississippiissippi",words = ['mis', 'iss', 'ssi', 'ipp', 'ppi', 'ippi', 'ippi', 'ippi', 'ippi', 'ippi', 'ippi', 'ippi', 'ippi', 'ippi', 'ippi']) == []
    assert candidate(s = "thisisaverylongstringthatcontainsmanywordsandwordstogether",words = ['this', 'is', 'avery', 'long', 'string', 'that', 'contains', 'many', 'words', 'and', 'words', 'together']) == []
    assert candidate(s = "catdogcatdogcatdogcat",words = ['cat', 'dog', 'cat', 'dog', 'cat']) == [0, 6]
    assert candidate(s = "abcdefghabcdefghabcdefgh",words = ['abcdef', 'ghabcd', 'efghab', 'cdefgh', 'defghi', 'efghab', 'fghabc']) == []
    assert candidate(s = "repeatedrepeatedrepeated",words = ['repeated', 'repe', 'atedre', 'peated']) == []
    assert candidate(s = "xylophoneclarinetxylophoneclarinet",words = ['xylo', 'phone', 'clar', 'inet']) == []
    assert candidate(s = "aquickbrownfoxjumpsoverthelazydog",words = ['quick', 'brown', 'fox', 'jump', 'over', 'the', 'lazy', 'dog']) == []
    assert candidate(s = "repeatedrepeatedrepeatedword",words = ['repeated', 'repeated', 'repeated', 'word']) == []
    assert candidate(s = "aquickbrownfoxjumpsoverthelazydog",words = ['quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']) == []
    assert candidate(s = "onetwothreefour",words = ['one', 'two', 'three', 'four']) == []
    assert candidate(s = "loremipsumdolorsitamet",words = ['lorem', 'ipsum', 'dolor', 'sit', 'amet']) == []
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",words = ['aabb', 'ccdd', 'eefg', 'ghhi', 'ijjk', 'kllm', 'mnnm', 'nnoo', 'ppqq', 'rrss', 'ttuu', 'vvww', 'xxyy', 'zzaa']) == []
    assert candidate(s = "ababababababababababababababababab",words = ['aba', 'bab', 'aba', 'bab', 'aba', 'bab', 'aba', 'bab', 'aba', 'bab', 'aba', 'bab', 'aba', 'bab', 'aba', 'bab', 'aba', 'bab', 'aba', 'bab']) == []
    assert candidate(s = "onetwothreefourfivesixseveneightnine",words = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine']) == []
    assert candidate(s = "aaaabbbbccccddddeeeeffffgggghhhhiiii",words = ['aabb', 'bbcc', 'ccdd', 'ddeeff', 'ffgg', 'gghh', 'hhiiaa']) == []
    assert candidate(s = "aabbccddeeffgghhiijj",words = ['aabb', 'ccdd', 'eeff', 'gghh', 'iijj']) == [0]
    assert candidate(s = "mississippi",words = ['issi', 'ippi']) == []
    assert candidate(s = "aaaaaaaaaaaabbbbbbbbbbbcccccccccccddddddddddd",words = ['aaaaa', 'bbbbb', 'ccccc', 'ddddd', 'aaaaa', 'bbbbb', 'ccccc', 'ddddd', 'aaaaa', 'bbbbb']) == []
    assert candidate(s = "complexcomplexcomplexcomplex",words = ['com', 'ple', 'xco', 'mple', 'com', 'ple', 'xco', 'mple']) == []
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",words = ['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'zz']) == []
    assert candidate(s = "pythonprogramminglanguage",words = ['py', 'thon', 'pro', 'gram', 'ming', 'lan', 'guag', 'e']) == []
    assert candidate(s = "exampleexampleexampleexample",words = ['example', 'example', 'example', 'example']) == [0]
    assert candidate(s = "abcdefghabcdefgh",words = ['abcd', 'efgh', 'efgh', 'abcd']) == [0]
    assert candidate(s = "hellohellohellohellohello",words = ['hello', 'hello', 'hello', 'hello', 'hello']) == [0]
    assert candidate(s = "xxyyyzzzzzyyyxx",words = ['xx', 'yy', 'zz', 'yy', 'xx']) == []
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",words = ['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz']) == []
    assert candidate(s = "hellohellohellohellohellohellohello",words = ['hello', 'hello']) == [0, 5, 10, 15, 20, 25]
    assert candidate(s = "concatenationconcatenationconcatenation",words = ['concat', 'enationc', 'ationc', 'tenation', 'enationc', 'oncatena']) == []
    assert candidate(s = "overlapoverlappingoverlapping",words = ['over', 'lap', 'over', 'lapping']) == []
    assert candidate(s = "xxyyzzxxyyzzxxyyzzxxyyzz",words = ['xxyy', 'yyzz', 'xxyy', 'yyzz', 'xxyy', 'yyzz']) == []
    assert candidate(s = "abcdefgabcdefgabcdefg",words = ['abc', 'def', 'gab']) == [0, 7]
    assert candidate(s = "aabbccddeeff",words = ['abc', 'def', 'abb']) == []
    assert candidate(s = "mississippiissississippi",words = ['issi', 'ssis', 'siss', 'issi', 'ssis', 'siss', 'issi', 'ssis', 'siss']) == []
    assert candidate(s = "abcdefghijklmno",words = ['abc', 'def', 'ghi', 'jkl', 'mno']) == [0]
    assert candidate(s = "xyzxyzxyzxyzxyz",words = ['xyz', 'zyx', 'yzx', 'xzy', 'zxy']) == []
    assert candidate(s = "abcdefabcdefabcdefabcdefabcdefabcdef",words = ['abcdef', 'abcdef', 'abcdef', 'abcdef', 'abcdef', 'abcdef']) == [0]
    assert candidate(s = "thisisatargetstringwithtargetstring",words = ['this', 'is', 'a', 'target', 'string']) == []
    assert candidate(s = "thisisanexamplethisisanexamplethisisanexample",words = ['this', 'isan', 'example', 'isan', 'example']) == []
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",words = ['zzzz', 'zzzz', 'zzzz', 'zzzz', 'zzzz', 'zzzz', 'zzzz', 'zzzz', 'zzzz', 'zzzz']) == [0, 4, 1, 5, 2, 6, 3]
    assert candidate(s = "abcdabcdabcdabcdabcdabcd",words = ['abcd', 'dcba', 'abdc', 'bacd', 'cdab']) == []
    assert candidate(s = "abcdefghijabcdefghijabcdefghij",words = ['abc', 'def', 'ghi', 'jabc', 'def', 'ghij', 'abc', 'def', 'ghi', 'j']) == []
    assert candidate(s = "abcdefghiabcdefghiabcdefghi",words = ['abc', 'def', 'ghi', 'abc', 'def', 'ghi', 'abc', 'def', 'ghi']) == [0]
    assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghij",words = ['abc', 'def', 'ghi', 'jabc', 'def', 'ghi', 'jabc', 'def', 'ghi', 'j']) == []
    assert candidate(s = "aaaaaaaaaaaaaaaaaab",words = ['aaaa', 'aaaa', 'aaaa', 'aaaa', 'aaaa', 'aaaa', 'aaaa', 'aaaa', 'aaaa', 'a']) == []
    assert candidate(s = "onetwothreefourfivesix",words = ['one', 'two', 'three', 'four', 'five', 'six']) == []
    assert candidate(s = "ababababababababababababababab",words = ['aba', 'bab', 'aba', 'bab', 'aba', 'bab', 'aba', 'bab', 'aba', 'bab']) == [0]
    assert candidate(s = "abracadabra",words = ['bra', 'cad']) == [1]
    assert candidate(s = "amazinganduniquestring",words = ['amazing', 'and', 'unique', 'string']) == []
    assert candidate(s = "mississippiississi",words = ['issi', 'ssis', 'siss', 'issi']) == []
    assert candidate(s = "abcdefabcdefabcdef",words = ['abc', 'def', 'cba', 'fed']) == []
    assert candidate(s = "abcdefghij",words = ['abc', 'def', 'ghi', 'j']) == []
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",words = ['aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa']) == []
    assert candidate(s = "mnopqrstuvmnopqrstuv",words = ['mnop', 'qrst', 'uv', 'mnop', 'qrst', 'uv']) == []
    assert candidate(s = "lmnopqrlmnopqrlmnopqr",words = ['lmnop', 'qr', 'lmnop', 'qr', 'lmnop', 'qr']) == []
    assert candidate(s = "xyzzxyzzxyzzxyzzxyzzxyzzxyzz",words = ['xyz', 'zxy', 'zzx', 'xyz', 'zxy', 'zzx', 'xyz', 'zxy', 'zzx', 'xyz', 'zxy', 'zzx']) == []
    assert candidate(s = "abcdefghijabcdefghijabcdefghij",words = ['abcdefghij', 'abcdefghij', 'abcdefghij']) == [0]
    assert candidate(s = "anananananananananananananananananan",words = ['ana', 'nan', 'ana']) == [0, 6, 12, 18, 24, 4, 10, 16, 22, 2, 8, 14, 20, 26]
    assert candidate(s = "hellohellohellohello",words = ['hello', 'hello', 'hello']) == [0, 5]
    assert candidate(s = "abcdefabcdefabcdefabcdefabcdef",words = ['abc', 'def']) == [0, 3, 6, 9, 12, 15, 18, 21, 24]
    assert candidate(s = "qwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwerty",words = ['qwe', 'rty', 'qwe', 'rty', 'qwe', 'rty', 'qwe', 'rty', 'qwe', 'rty', 'qwe', 'rty', 'qwe', 'rty', 'qwe', 'rty', 'qwe', 'rty', 'qwe', 'rty']) == [0, 3, 6, 9, 12]
    assert candidate(s = "aaaabbbbccccaaaabbbbcccc",words = ['aaaa', 'bbbb', 'cccc', 'aaaa', 'bbbb', 'cccc']) == [0]
    assert candidate(s = "concatenatedsubstringthatappearsmultipleconcatenatedsubstring",words = ['concatenated', 'substring', 'that', 'appears', 'multiple']) == []
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc",words = ['abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc']) == []
    assert candidate(s = "mississippiissimissing",words = ['issi', 'ssis', 'ippi', 'ssip']) == []
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",words = ['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz']) == []
    assert candidate(s = "longstringwithmanywordsoflengthfive",words = ['fivel', 'ength', 'withm', 'nword', 'stringw', 'ongst', 'rings', 'words', 'thefa']) == []
    assert candidate(s = "xxyzxyzyxzyzyzxzy",words = ['xyz', 'zyx', 'zyz', 'zxy']) == []
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc",words = ['abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc']) == [0]
    assert candidate(s = "qwertyuiopqwertyuiopqwertyuiop",words = ['qwerty', 'uiop', 'qwerty', 'uiop', 'qwerty', 'uiop']) == []
    assert candidate(s = "mississippiississippi",words = ['miss', 'issi', 'ssip', 'ippi']) == []
    assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij",words = ['abc', 'def', 'ghi', 'jabc', 'def', 'ghi', 'jabc', 'def', 'ghi', 'jabc', 'def', 'ghi', 'jabc', 'def', 'ghi', 'j']) == []
    assert candidate(s = "aaaaaabbbbccccdddd",words = ['aaaa', 'bbbb', 'cccc', 'dddd']) == [2]
    assert candidate(s = "xyzxyzxyzxyz",words = ['xyz', 'xyz', 'xyz', 'xyz']) == [0]
    assert candidate(s = "mississippiissimissing",words = ['issi', 'ssis', 'ippi', 'ssim']) == []
