# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abcd",t = "abcde") == 1
    assert candidate(s = "hello",t = "world") == 5
    assert candidate(s = "abcdefghij",t = "fihgjedcba") == 8
    assert candidate(s = "abcde",t = "edcba") == 4
    assert candidate(s = "aaaaa",t = "aa") == 0
    assert candidate(s = "testcase",t = "ttccasse") == 3
    assert candidate(s = "programming",t = "gnimmargorp") == 9
    assert candidate(s = "abcd",t = "dbca") == 3
    assert candidate(s = "xyz",t = "abc") == 3
    assert candidate(s = "minimum",t = "imumin") == 2
    assert candidate(s = "abcd",t = "dcba") == 3
    assert candidate(s = "abcdefg",t = "xyz") == 3
    assert candidate(s = "programming",t = "gaming") == 0
    assert candidate(s = "abacaba",t = "bzaa") == 1
    assert candidate(s = "cde",t = "xyz") == 3
    assert candidate(s = "abcde",t = "ace") == 0
    assert candidate(s = "hello",t = "olelh") == 4
    assert candidate(s = "xyzxyzxyzxyzxyz",t = "zyzyzyzyzyzyzyzyzyz") == 9
    assert candidate(s = "testcase",t = "tttttttt") == 6
    assert candidate(s = "abcde",t = "abcdxyzef") == 5
    assert candidate(s = "hello world",t = "worldhello") == 5
    assert candidate(s = "abacabadabacaba",t = "zabacabadabacabaz") == 17
    assert candidate(s = "abababab",t = "bababa") == 0
    assert candidate(s = "aaaaaaaaaa",t = "aaaaaaaaaab") == 1
    assert candidate(s = "abcdexyz",t = "zyxwvutsrqponmlkjihgfedcba") == 25
    assert candidate(s = "aabbaabbaabb",t = "bbbb") == 0
    assert candidate(s = "abacabadabacaba",t = "aaaaabaaa") == 0
    assert candidate(s = "longstringwithmanypatterns",t = "stringwithpatternsstring") == 6
    assert candidate(s = "thisisaverylongstringfortesting",t = "stringfortestingthisisaverylong") == 15
    assert candidate(s = "abcdefghij",t = "bcdefghia") == 1
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",t = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 84
    assert candidate(s = "abcabcabcabc",t = "cccc") == 0
    assert candidate(s = "mississippi",t = "pi") == 0
    assert candidate(s = "hellotherehellotherehellotherehellothere",t = "herehellotherehellotherehellotherehellotherehello") == 14
    assert candidate(s = "abracadabra",t = "acraabdbrac") == 6
    assert candidate(s = "xyzxyzxyz",t = "zyxzyxzyx") == 5
    assert candidate(s = "abcdabcdabcd",t = "dcbaabdcba") == 7
    assert candidate(s = "sequence",t = "enqueseq") == 5
    assert candidate(s = "abracadabra",t = "rac") == 0
    assert candidate(s = "repeatedcharactersarehere",t = "tareeere") == 0
    assert candidate(s = "aabbccddeeffgg",t = "fedcbazyxwvutsrqponmlkjihgfedcba") == 31
    assert candidate(s = "abcdefghij",t = "abcdefghijabcdefghij") == 10
    assert candidate(s = "bananaananabayananabananabananabanana",t = "nananananananananananananananananan") == 11
    assert candidate(s = "abcde",t = "edcbaa") == 5
    assert candidate(s = "longstringwithseveralcharacters",t = "characterswithseveralstringlong") == 21
    assert candidate(s = "thisisaverylongstringwithmanysimilarcharacters",t = "similarcharacters") == 0
    assert candidate(s = "hellohellohello",t = "ollhll") == 0
    assert candidate(s = "longestsubstring",t = "strolng") == 2
    assert candidate(s = "solvingproblems",t = "problemsolving") == 6
    assert candidate(s = "banana",t = "bananabananabanana") == 12
    assert candidate(s = "ababababababababababababababababa",t = "bababababababababababababababababa") == 1
    assert candidate(s = "aabbccddeeffgghhii",t = "ihgfedcba") == 8
    assert candidate(s = "abcdefghij",t = "ihgfedcbaj") == 8
    assert candidate(s = "hellohellohello",t = "lllllooohehe") == 5
    assert candidate(s = "aaaaaa",t = "bbbbbb") == 6
    assert candidate(s = "aaaaaabbbbbbcccccc",t = "cccccccbaaaaa") == 7
    assert candidate(s = "quickbrownfoxjumpsoverthelazydog",t = "dogzyxvutwrofsjpmnklobq") == 20
    assert candidate(s = "aaaaaaaaaa",t = "aaaaaaaaa") == 0
    assert candidate(s = "programmingisfun",t = "misnpfrmigong") == 9
    assert candidate(s = "complexproblem",t = "problemcomplex") == 7
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzzyyxxwwvvuuttssrrqppoonnmmllkkjjiihhhgggffeeedddccbbaa") == 54
    assert candidate(s = "abracadabra",t = "raac") == 1
    assert candidate(s = "findingthesolution",t = "solutionfinding") == 7
    assert candidate(s = "abcdefghijabcdefghij",t = "hgfedcbajihgfedcbaj") == 16
    assert candidate(s = "abcdefghijabcdefghijabcdefghij",t = "zyxwvutsrqponmlkjihgfedcba") == 23
    assert candidate(s = "aaaaabbbbbccccc",t = "abcabcabcabc") == 8
    assert candidate(s = "abcdabcdabcd",t = "ddddccbbbaaa") == 9
    assert candidate(s = "racecar",t = "racecarracecar") == 7
    assert candidate(s = "mississippi",t = "ississipisipismiss") == 9
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzzzyyyyxxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccbaaabbaa") == 59
    assert candidate(s = "mississippi",t = "ppiisimiss") == 6
    assert candidate(s = "samestring",t = "samestring") == 0
    assert candidate(s = "abcdexyzabcdexyz",t = "zyxwvutzyxwvutzyxwvut") == 19
    assert candidate(s = "abcde",t = "bcdea") == 1
    assert candidate(s = "aabbccddeeff",t = "fedcba") == 5
    assert candidate(s = "uniquecharacters",t = "charactersunique") == 6
    assert candidate(s = "abcdefghijabcdefghij",t = "fihgjedcbafihgjedcbafihg") == 21
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 50
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zyxwvutsrqponmlkjihgfedcba") == 25
    assert candidate(s = "quickbrownfox",t = "brownfoxquick") == 5
    assert candidate(s = "dynamicprogramming",t = "ymnpgmcratidnodpmg") == 13
    assert candidate(s = "abababababab",t = "bababababa") == 0
    assert candidate(s = "aaaaaabbbbbccccc",t = "ccccbbbaaaaa") == 7
    assert candidate(s = "abacaxbadacabacaba",t = "bacabaa") == 0
    assert candidate(s = "abcdefghij",t = "abcdefghijk") == 1
    assert candidate(s = "longstringthatcontainscharactersrepeatedly",t = "characterscharacterscharacters") == 18
    assert candidate(s = "abcdabcdabcdabcdabcdabcd",t = "dddddddddd") == 4
    assert candidate(s = "thisisaverylongstring",t = "stringisaverylong") == 5
    assert candidate(s = "mississippi",t = "issississississississsissississississsississississs") == 44
    assert candidate(s = "qzxtqzxtqzxt",t = "xtzxtzxtzxtzxtzxtzxtzxtzxtzxtzxtzxtzxtzxtzxt") == 35
    assert candidate(s = "abacabadabacaba",t = "bzaaazza") == 6
    assert candidate(s = "repeatedcharacters",t = "eedaaeerereeeddperrrrttt") == 18
    assert candidate(s = "pythonprogramming",t = "ptyhnonrpgmaminnorgm") == 14
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",t = "zzzyyxxwwvvuutssrrqqppoonnllkkjjiihhhgggffeeeddccbaab") == 50
    assert candidate(s = "mississippi",t = "ppisissam") == 6
    assert candidate(s = "thisisatest",t = "ttttt") == 2
    assert candidate(s = "mississippi",t = "ssssii") == 0
    assert candidate(s = "abcabcabcabcabcabc",t = "cccbbbbaaabbbcccbbbbaaabbb") == 19
    assert candidate(s = "thisisalongstring",t = "thisstringislong") == 6
    assert candidate(s = "xyzxyzxyzxyz",t = "zzzzyyyyxxxxyyyyzzzz") == 15
    assert candidate(s = "thisisaverylongstring",t = "gnirtsylonlavraesiisthis") == 20
    assert candidate(s = "abcdefghij",t = "aabbccddeeffgghhiijj") == 18
    assert candidate(s = "optimization",t = "ttttiiiooonnnssss") == 15
    assert candidate(s = "abacabadabacaba",t = "dabacabad") == 1
    assert candidate(s = "abcdeabcdeabcde",t = "ecbedcab") == 4
    assert candidate(s = "abacabadabacaba",t = "abadab") == 0
    assert candidate(s = "abcdabcdabcd",t = "dddd") == 1
    assert candidate(s = "hello",t = "hhheeelllllooooo") == 14
    assert candidate(s = "thisisaverylongstring",t = "tsring") == 0
    assert candidate(s = "abacabadabacaba",t = "aaabbbccc") == 3
    assert candidate(s = "pythonprogramming",t = "notapysubsequence") == 15
    assert candidate(s = "abacabadabacaba",t = "aaaaa") == 0
    assert candidate(s = "mississippi",t = "ssissip") == 0
    assert candidate(s = "abcdefghijabcdefghij",t = "jihgfedcbajihgfedcba") == 18
    assert candidate(s = "abcdefabcdefabcdef",t = "fedcba") == 3
    assert candidate(s = "abcdefg",t = "gfedcbaacdefg") == 7
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcd",t = "dcbaabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 3
    assert candidate(s = "mississippi",t = "msssssssssssss") == 9
    assert candidate(s = "abababababababab",t = "babababababababa") == 1
    assert candidate(s = "abacabadabacaba",t = "abacabacaba") == 0
    assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghij",t = "jihgfedcbajihgfedcbajihgfedcbajihgfedcba") == 36
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",t = "zyxwvutsrqponmlkjihgfedcba") == 25
    assert candidate(s = "nestednestednested",t = "nns") == 0
    assert candidate(s = "abacabadabacaba",t = "zzzzzzzzzzzzzzz") == 15
    assert candidate(s = "aaaaabbbbbcccccdddddeeeee",t = "bbbbbeeecdddd") == 3
    assert candidate(s = "mississippi",t = "ppisss") == 2
    assert candidate(s = "aaaaaabbbbbbbccccccdddddeeeeefffff",t = "ffffeeeeeddccccbbbaaaa") == 18
    assert candidate(s = "longwordhere",t = "helloworld") == 8
    assert candidate(s = "aaaaaaa",t = "aaaaaaa") == 0
    assert candidate(s = "abcdefghij",t = "abcdefghijxyz") == 3
