# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "zzzz",k = 1) == 32
    assert candidate(s = "zzz",k = 10) == 6
    assert candidate(s = "programming",k = 1) == 68
    assert candidate(s = "abz",k = 5) == 2
    assert candidate(s = "a",k = 1) == 1
    assert candidate(s = "aaa",k = 3) == 3
    assert candidate(s = "challenge",k = 2) == 4
    assert candidate(s = "iiii",k = 1) == 36
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",k = 1) == 135
    assert candidate(s = "hello",k = 1) == 25
    assert candidate(s = "python",k = 2) == 8
    assert candidate(s = "abc",k = 3) == 6
    assert candidate(s = "zbax",k = 2) == 8
    assert candidate(s = "abcxyz",k = 3) == 9
    assert candidate(s = "leetcode",k = 2) == 6
    assert candidate(s = "a",k = 10) == 1
    assert candidate(s = "zzzz",k = 3) == 5
    assert candidate(s = "zzzzzzzzzz",k = 1) == 80
    assert candidate(s = "algorithms",k = 4) == 5
    assert candidate(s = "repeatthisoverandover",k = 7) == 8
    assert candidate(s = "zzzzzzzzzz",k = 6) == 8
    assert candidate(s = "interview",k = 5) == 8
    assert candidate(s = "artificialintelligence",k = 7) == 5
    assert candidate(s = "zzyxwvutsrqponmlkjihgfedcba",k = 4) == 8
    assert candidate(s = "singleletterx",k = 10) == 8
    assert candidate(s = "thisisaverylongstringwhichshouldbeconverted",k = 4) == 2
    assert candidate(s = "zzzzzzzzzz",k = 3) == 8
    assert candidate(s = "hippopotamus",k = 10) == 7
    assert candidate(s = "qwen",k = 5) == 5
    assert candidate(s = "datastructure",k = 4) == 9
    assert candidate(s = "quickbrownfoxjumpsoverthelazydog",k = 3) == 8
    assert candidate(s = "repeatedlettersqqqq",k = 6) == 7
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",k = 2) == 9
    assert candidate(s = "programming",k = 3) == 5
    assert candidate(s = "unbelievable",k = 9) == 2
    assert candidate(s = "mississippi",k = 7) == 4
    assert candidate(s = "zebra",k = 6) == 7
    assert candidate(s = "zzzzzzzzzz",k = 10) == 8
    assert candidate(s = "xyzxyz",k = 3) == 6
    assert candidate(s = "supercalifragilisticexpialidocious",k = 5) == 1
    assert candidate(s = "onetwothreefourfivesixseveneightnine",k = 5) == 8
    assert candidate(s = "generateadditionalinputs",k = 8) == 2
    assert candidate(s = "quickbrownfoxjumpsoverthelazydog",k = 4) == 8
    assert candidate(s = "multifarious",k = 7) == 2
    assert candidate(s = "consecutivesimilar",k = 8) == 1
    assert candidate(s = "neuralnetwork",k = 8) == 6
    assert candidate(s = "developerslovepython",k = 9) == 3
    assert candidate(s = "algorithm",k = 1) == 49
    assert candidate(s = "wearethebestprogrammers",k = 7) == 4
    assert candidate(s = "xylophone",k = 3) == 8
    assert candidate(s = "alibabacloud",k = 7) == 2
    assert candidate(s = "aaaaaaaaaa",k = 10) == 1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",k = 5) == 9
    assert candidate(s = "elephant",k = 8) == 9
    assert candidate(s = "supercalifragilisticexpialidocious",k = 4) == 1
    assert candidate(s = "abcdefghij",k = 5) == 1
    assert candidate(s = "repeatedletters",k = 4) == 2
    assert candidate(s = "datastructures",k = 5) == 1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",k = 3) == 9
    assert candidate(s = "facetious",k = 8) == 9
    assert candidate(s = "numericalsum",k = 7) == 5
    assert candidate(s = "expertise",k = 2) == 13
    assert candidate(s = "codingcontest",k = 6) == 4
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba",k = 4) == 9
    assert candidate(s = "alibabacloud",k = 2) == 11
    assert candidate(s = "manytimesk",k = 10) == 4
    assert candidate(s = "quickbrownfoxjumpsoverthelazydog",k = 6) == 8
    assert candidate(s = "giraffe",k = 9) == 7
    assert candidate(s = "qwen",k = 10) == 5
    assert candidate(s = "mississippi",k = 8) == 4
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz",k = 10) == 9
    assert candidate(s = "quickbrownfoxjumpsoverthelazydog",k = 10) == 8
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",k = 10) == 4
    assert candidate(s = "solution",k = 7) == 8
    assert candidate(s = "abacaxabacax",k = 5) == 1
    assert candidate(s = "algorithms",k = 5) == 5
    assert candidate(s = "zzzzzzzzzz",k = 5) == 8
    assert candidate(s = "transform",k = 8) == 7
    assert candidate(s = "congratulations",k = 5) == 9
    assert candidate(s = "xylophone",k = 4) == 8
    assert candidate(s = "quickbrownfoxjumpsoverthelazydog",k = 2) == 8
    assert candidate(s = "qwen",k = 4) == 5
    assert candidate(s = "leetcodeisfun",k = 9) == 3
    assert candidate(s = "programmingisfun",k = 3) == 2
    assert candidate(s = "machinelearning",k = 6) == 7
    assert candidate(s = "abcdefg",k = 10) == 1
    assert candidate(s = "thequickbrownfoxjumpsoverthelazydog",k = 6) == 5
    assert candidate(s = "thisisaverylongandcomplexstring",k = 6) == 1
    assert candidate(s = "xylophone",k = 5) == 8
    assert candidate(s = "thisisanexampletocheckthecomplexity",k = 4) == 1
    assert candidate(s = "datastructure",k = 5) == 9
    assert candidate(s = "abacaxi",k = 3) == 5
    assert candidate(s = "abcdabcdabcd",k = 4) == 3
