# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "xyzzxyzzxyzz") == 87
    assert candidate(s = "aaabbbccc") == 29
    assert candidate(s = "aabcb") == 5
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 0
    assert candidate(s = "abcdedcba") == 16
    assert candidate(s = "a") == 0
    assert candidate(s = "abcabcabc") == 16
    assert candidate(s = "zzzz") == 0
    assert candidate(s = "aabcbaa") == 17
    assert candidate(s = "pqrspqrspqrspqrs") == 63
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnm") == 0
    assert candidate(s = "xyzxyzxyz") == 16
    assert candidate(s = "abcdabcdabcd") == 30
    assert candidate(s = "abc") == 0
    assert candidate(s = "xyzzxyzz") == 25
    assert candidate(s = "abcd") == 0
    assert candidate(s = "aabbccddeeff") == 40
    assert candidate(s = "zzzzz") == 0
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 950
    assert candidate(s = "abcdefg") == 0
    assert candidate(s = "aaaabbbbccccddddeeeeffffgggghhhhiiii") == 1112
    assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghij") == 432
    assert candidate(s = "pqrstuvwxyzabcdefghijklmno") == 0
    assert candidate(s = "abccbaabccbaabccbaabccba") == 222
    assert candidate(s = "verycomplicatedstringwithrepeatedcharactersrepeatedrepeated") == 5556
    assert candidate(s = "mississippimississippimississippimississippi") == 4387
    assert candidate(s = "abracadabra") == 64
    assert candidate(s = "abacabadabacabadabacabadabacabad") == 2236
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacaba") == 11131
    assert candidate(s = "abcabcabcabc") == 33
    assert candidate(s = "xzyxzxyzxyz") == 34
    assert candidate(s = "abcdefabcdeabcdeabcde") == 183
    assert candidate(s = "aabacababa") == 66
    assert candidate(s = "zzzzzzzzzz") == 0
    assert candidate(s = "abcdefghijklmabcdefghijklm") == 90
    assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij") == 1170
    assert candidate(s = "abababababababababababababababab") == 240
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabc") == 456
    assert candidate(s = "mississippiissiippiisppiiiiiiii") == 1732
    assert candidate(s = "abacabadabacabadabacabadabacaba") == 2047
    assert candidate(s = "thisisaverylongandcomplicatedstringwithvariouscharacters") == 2645
    assert candidate(s = "mnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba") == 325
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 513
    assert candidate(s = "kayak") == 4
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc") == 261
    assert candidate(s = "xyzzzzxyzzzzxyzzzzxyzzzz") == 1254
    assert candidate(s = "ababababababab") == 42
    assert candidate(s = "abcdefghijklmnopqrstuvwxyza") == 1
    assert candidate(s = "abcdefabcdefabcdefabcdefabcdefabcdef") == 400
    assert candidate(s = "abcdabcdabcdabcd") == 63
    assert candidate(s = "level") == 4
    assert candidate(s = "ppppppppppppppppppppppppppppppppppqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq") == 13090
    assert candidate(s = "xyzzyxzyxzyzyx") == 87
    assert candidate(s = "pqrsrstsrqpqrs") == 102
    assert candidate(s = "madam") == 4
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 1053
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnmqwerty") == 21
    assert candidate(s = "xyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 2450
    assert candidate(s = "aaaabbbbccccddddeeeeffffgggg") == 630
    assert candidate(s = "abacabadabacaba") == 231
    assert candidate(s = "xyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxy") == 702
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad") == 44628
    assert candidate(s = "xyzzazxzy") == 45
    assert candidate(s = "abababababababababababababababababababababababab") == 552
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbcccccccccc") == 1275
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 1350
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(s = "aabbccddeeffgghhiijjaabbccddeeffgghhiijjaabbccddeeffgghhiijj") == 2118
    assert candidate(s = "bananaananabananananabananananananananananananana") == 7610
    assert candidate(s = "mnbvcxzlkjhgfdsapoiuytrewq") == 0
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(s = "banana") == 8
    assert candidate(s = "xyzzxyzzxyzzxyzzxyzzxyzzxyzzxyzzxyzzxyzzxyzzxyzzxyzzxyzzxyzzxyzz") == 11722
    assert candidate(s = "mnopqrsmnopqrsmnopqrsmnopqrsmnopqrsmnopqrsmnopqrsmnopqrs") == 1071
    assert candidate(s = "aabbccddeeefffggghhhiiijjjkkklllmmmnnnooopppqqqrrrssstttuuuvvvwwwxxxxyyyzzz") == 4312
    assert candidate(s = "aaaaabbbbccccddddeeeffffggghhh") == 782
    assert candidate(s = "nnnnoonnmnmlmllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll") == 33629
    assert candidate(s = "aaaabbbbccccdddd") == 162
    assert candidate(s = "abacabadabacabadabacabad") == 948
    assert candidate(s = "deified") == 9
    assert candidate(s = "zzzzzzzzzzzzzzzzz") == 0
    assert candidate(s = "repaper") == 9
    assert candidate(s = "xyzzzzzxyzzzzzxyzzzzzxyzzzzzxyzzzzzxyzzzzzxyzzzzzxyzzzzz") == 17541
    assert candidate(s = "aabbaaabbbaaabbaaaabbbaaabbaaaabbbaaabbaaaabbbaaabbaaaab") == 5129
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzzzz") == 11950
    assert candidate(s = "aabbccddeeffgghhiijjanmlkjihgfedcbazyxwvutsrqponmlkjihgfedcba") == 1979
    assert candidate(s = "abababababababababababab") == 132
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm") == 350
    assert candidate(s = "rotor") == 4
    assert candidate(s = "racecar") == 9
    assert candidate(s = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz") == 320
    assert candidate(s = "abcabcabcabcabcabcabcabc") == 161
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 350
    assert candidate(s = "reviled") == 4
    assert candidate(s = "mnopqrnopqmonmnopq") == 145
    assert candidate(s = "abacabadaba") == 85
    assert candidate(s = "mississippi") == 64
    assert candidate(s = "aaaaabbbbccccddddeeeffffgggghhhhiiiiijjjjkkkkllllmmmmmnnnnnooooo") == 4941
    assert candidate(s = "abcabcabcabcabc") == 56
    assert candidate(s = "xyzzzzzxyzzzzzxyzzzzz") == 936
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(s = "refer") == 4
