# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "xyzxyzxyz") == 18
    assert candidate(s = "abcabcabc") == 18
    assert candidate(s = "aabbcc") == 7
    assert candidate(s = "abacabadabacaba") == 32
    assert candidate(s = "zzzzz") == 15
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 26
    assert candidate(s = "abacaba") == 12
    assert candidate(s = "babab") == 9
    assert candidate(s = "azbazbzaz") == 14
    assert candidate(s = "abcde") == 5
    assert candidate(s = "zazazaz") == 16
    assert candidate(s = "aaaaa") == 15
    assert candidate(s = "aabbaabb") == 14
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba") == 26
    assert candidate(s = "a") == 1
    assert candidate(s = "abcdefg") == 7
    assert candidate(s = "aabbccddeeff") == 13
    assert candidate(s = "aaaaaaaaaabbbbbbbbbb") == 65
    assert candidate(s = "abacabadabacabadabacaba") == 60
    assert candidate(s = "abcdefgfedcbabcdefgfedcbabcdefgfedcbabcdefgfedcbabcdefgfedcb") == 180
    assert candidate(s = "xyxyxyxyxyxyxyxy") == 72
    assert candidate(s = "zxyzyxzyxzyxzyxzyxzyxzyx") == 31
    assert candidate(s = "aaaabbbbccccaaaabbbbcccc") == 48
    assert candidate(s = "mississippimississippimississippimississippi") == 110
    assert candidate(s = "aaaaaaaaaabaaaa") == 70
    assert candidate(s = "rotorrotor") == 17
    assert candidate(s = "abracadabra") == 18
    assert candidate(s = "abcabcabcabc") == 30
    assert candidate(s = "abcabcabcabcabcd") == 46
    assert candidate(s = "zzzzzzzzzzzzzzz") == 120
    assert candidate(s = "zzyyxxwwvvuuttssrrqqppoonnmmllkkiijjhhggffeeddccbbbaaa") == 55
    assert candidate(s = "aaaaaaaaaabaaaaaaaaab") == 111
    assert candidate(s = "abcabcabcabcabcabca") == 70
    assert candidate(s = "abcabcabcabca") == 35
    assert candidate(s = "abcdabcdabcd") == 24
    assert candidate(s = "abacabadabacabad") == 34
    assert candidate(s = "abababababababababababababababab") == 272
    assert candidate(s = "aaaaabbbbccccdddd") == 27
    assert candidate(s = "aaaaabbbbbccccdddd") == 28
    assert candidate(s = "aaaaabbbbb") == 20
    assert candidate(s = "aaaaabbbbccccddddeeeee") == 32
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabc") == 234
    assert candidate(s = "abcdefedcbafedcbafedcba") == 26
    assert candidate(s = "mississippimississippi") == 33
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabc") == 273
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 630
    assert candidate(s = "aabbaabbaabbaabb") == 44
    assert candidate(s = "bananaananabanana") == 23
    assert candidate(s = "abcabcabcabcabcabcab") == 77
    assert candidate(s = "abcabcabcabcabcabcabc") == 84
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 612
    assert candidate(s = "qwertyuiopqwertyuiop") == 30
    assert candidate(s = "aabbccddeeaabbccddeeaabbccddeeaabbccddeeaabbccdd") == 145
    assert candidate(s = "abcdefghjihgfedcba") == 19
    assert candidate(s = "acabacabacabacabacabacabacabacabacabacab") == 230
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc") == 165
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 360
    assert candidate(s = "abcabcabcab") == 26
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 408
    assert candidate(s = "qwertyuiopasdfghjklzxcvbnm") == 26
    assert candidate(s = "abcdefedcbafedcbafedcbafedcbafedcbafedcbafedcbafedcbafedcbafedcba") == 75
    assert candidate(s = "abcdeedcbaabcdeedcba") == 32
    assert candidate(s = "ababababababab") == 56
    assert candidate(s = "abcdeedcba") == 11
    assert candidate(s = "abababababababab") == 72
    assert candidate(s = "noon") == 5
    assert candidate(s = "abababababab") == 42
    assert candidate(s = "ababababababababab") == 90
    assert candidate(s = "abcabcabcabcabcabc") == 63
    assert candidate(s = "aabbccddeeffgghhii") == 19
    assert candidate(s = "abcdabcdabcdabcd") == 40
    assert candidate(s = "level") == 6
    assert candidate(s = "levellevellevel") == 33
    assert candidate(s = "abcdabcdabcdabcdabcd") == 60
    assert candidate(s = "abcdefghijk") == 11
    assert candidate(s = "aaaaaaaaaaa") == 66
    assert candidate(s = "qwertyuiopqwertyuiopqwertyuiopqwertyuiop") == 100
    assert candidate(s = "bananaananab") == 13
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz") == 210
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 666
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 315
    assert candidate(s = "banana") == 6
    assert candidate(s = "zzyzxzyzxzyzxzyz") == 24
    assert candidate(s = "xyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxy") == 272
    assert candidate(s = "zxyzyxzyxzyxzyxzyx") == 23
    assert candidate(s = "abracadabraabracadabra") == 47
    assert candidate(s = "abcdedcbaabcdedcba") == 29
    assert candidate(s = "abcdefghij") == 10
    assert candidate(s = "abcdedcbafedcbafedcbafedcbafedcba") == 38
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 53
    assert candidate(s = "aabbccddeeffgghhiijj") == 21
    assert candidate(s = "aabbccddeeffaabbccddeeff") == 38
    assert candidate(s = "aaaaaabbccddeeffgg") == 33
    assert candidate(s = "aaaaabbbbbaaaaa") == 40
    assert candidate(s = "racecarracecar") == 23
    assert candidate(s = "abacabadabacabadabacabad") == 63
    assert candidate(s = "deified") == 8
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbb") == 525
    assert candidate(s = "aaaaaabbbbbccccc") == 31
    assert candidate(s = "aaaaaabbbbccccdddd") == 33
    assert candidate(s = "abcbaabcbaabcba") == 33
    assert candidate(s = "ababababcabababa") == 44
    assert candidate(s = "abcdabcdbabc") == 19
    assert candidate(s = "abababababababababababab") == 156
    assert candidate(s = "ababababab") == 30
    assert candidate(s = "abacabadabacabadabacab") == 55
    assert candidate(s = "civic") == 6
    assert candidate(s = "rotor") == 6
    assert candidate(s = "racecar") == 8
    assert candidate(s = "abcabcabcabcabcabcabcabcabc") == 135
    assert candidate(s = "abcdefghijabcdefghij") == 30
    assert candidate(s = "zazbzcbzazbzcb") == 25
    assert candidate(s = "abcabcabcabcabcabcabcabc") == 108
    assert candidate(s = "pneumonoultramicroscopicsilicovolcanoconiosis") == 46
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabc") == 198
    assert candidate(s = "abcabcabcabcabcab") == 57
    assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 2211
    assert candidate(s = "abcdefabcdeabcdeabc") == 32
    assert candidate(s = "mississippi") == 11
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzz") == 71
    assert candidate(s = "hellohellohellohello") == 50
    assert candidate(s = "abcabcabcabcabc") == 45
    assert candidate(s = "xyzzzyxyzzzyxyzzzyxyzzzy") == 60
