# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(board = [['X', 'X', 'X', 'O'], ['X', 'O', 'O', 'X'], ['X', 'X', 'O', 'X'], ['X', 'O', 'X', 'X']]) == None
    assert candidate(board = [['O', 'X', 'X', 'O', 'X'], ['X', 'X', 'X', 'X', 'O'], ['X', 'X', 'X', 'O', 'X'], ['O', 'X', 'X', 'X', 'O'], ['X', 'O', 'O', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X'], ['X', 'X', 'O', 'X'], ['X', 'O', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'X'], ['X', 'O', 'X', 'O', 'X'], ['X', 'O', 'O', 'O', 'X'], ['X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['O', 'O', 'O'], ['O', 'X', 'O'], ['O', 'O', 'O']]) == None
    assert candidate(board = [['O', 'X', 'X', 'O', 'X'], ['X', 'X', 'X', 'X', 'X'], ['X', 'X', 'X', 'X', 'X'], ['X', 'X', 'X', 'O', 'O'], ['X', 'X', 'O', 'X', 'X']]) == None
    assert candidate(board = [['X', 'O', 'X', 'O'], ['O', 'X', 'O', 'X'], ['X', 'O', 'X', 'O'], ['O', 'X', 'O', 'X']]) == None
    assert candidate(board = [['X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X', 'X', 'O', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'O', 'X', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X', 'X', 'O', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'O', 'O', 'X'], ['X', 'O', 'X', 'X', 'X', 'O', 'X'], ['X', 'O', 'X', 'O', 'X', 'O', 'X'], ['X', 'O', 'X', 'X', 'X', 'O', 'X'], ['X', 'O', 'O', 'O', 'O', 'O', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X', 'X', 'O', 'O', 'X'], ['X', 'X', 'O', 'O', 'O', 'O', 'X', 'X'], ['X', 'O', 'X', 'X', 'X', 'X', 'X', 'O'], ['X', 'O', 'O', 'X', 'O', 'X', 'O', 'X'], ['X', 'X', 'O', 'X', 'X', 'X', 'O', 'X'], ['X', 'O', 'O', 'O', 'O', 'X', 'X', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['O', 'X', 'O', 'X', 'O'], ['O', 'O', 'O', 'O', 'O'], ['X', 'O', 'X', 'O', 'X'], ['O', 'O', 'O', 'O', 'O'], ['O', 'X', 'O', 'X', 'O']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'O', 'X'], ['X', 'X', 'X', 'X', 'X', 'X'], ['X', 'X', 'X', 'X', 'X', 'X'], ['X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'O', 'X']]) == None
    assert candidate(board = [['X', 'O', 'O', 'X'], ['X', 'O', 'O', 'X'], ['X', 'O', 'O', 'X'], ['X', 'X', 'X', 'X'], ['X', 'O', 'X', 'X']]) == None
    assert candidate(board = [['X', 'O', 'O', 'X', 'O', 'X', 'X'], ['X', 'X', 'O', 'X', 'X', 'X', 'X'], ['O', 'X', 'O', 'X', 'O', 'O', 'X'], ['X', 'O', 'X', 'O', 'X', 'X', 'X'], ['X', 'X', 'O', 'X', 'X', 'X', 'X'], ['X', 'O', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X'], ['X', 'O', 'X', 'O', 'X'], ['X', 'O', 'O', 'O', 'X'], ['X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'X']]) == None
    assert candidate(board = [['X', 'O', 'O', 'O', 'X', 'X'], ['X', 'X', 'X', 'X', 'O', 'X'], ['X', 'X', 'O', 'O', 'O', 'X'], ['O', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'O', 'X'], ['X', 'O', 'X', 'X', 'O', 'X'], ['X', 'O', 'X', 'X', 'O', 'X'], ['X', 'O', 'O', 'O', 'O', 'X'], ['X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'O', 'O', 'X'], ['X', 'O', 'O', 'X'], ['X', 'O', 'O', 'X'], ['X', 'O', 'O', 'X']]) == None
    assert candidate(board = [['O', 'O', 'X', 'O', 'O'], ['O', 'O', 'X', 'O', 'O'], ['X', 'X', 'X', 'X', 'X'], ['O', 'O', 'X', 'O', 'O'], ['O', 'O', 'X', 'O', 'O']]) == None
    assert candidate(board = [['O', 'O', 'O', 'O'], ['O', 'X', 'X', 'O'], ['O', 'X', 'X', 'O'], ['O', 'O', 'O', 'O']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'O', 'O', 'O', 'X'], ['X', 'O', 'X', 'X', 'X', 'X', 'O', 'X'], ['X', 'O', 'X', 'O', 'O', 'X', 'O', 'X'], ['X', 'O', 'X', 'X', 'X', 'X', 'O', 'X'], ['X', 'O', 'O', 'O', 'O', 'O', 'O', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'O', 'X'], ['X', 'O', 'X', 'O', 'X', 'X'], ['X', 'O', 'O', 'O', 'O', 'X'], ['X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'X'], ['X', 'X', 'X', 'X', 'X'], ['X', 'X', 'O', 'O', 'X'], ['X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X', 'X'], ['X', 'X', 'O', 'X', 'X'], ['X', 'O', 'X', 'O', 'O'], ['X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'O', 'X'], ['X', 'O', 'X', 'X', 'O', 'X'], ['X', 'O', 'X', 'O', 'X', 'X'], ['X', 'O', 'O', 'X', 'O', 'X'], ['X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X', 'X'], ['X', 'O', 'X', 'O', 'X'], ['X', 'X', 'X', 'O', 'X'], ['X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'O', 'O', 'X', 'X', 'X', 'X'], ['X', 'O', 'X', 'O', 'O', 'O', 'X'], ['X', 'O', 'X', 'O', 'X', 'O', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X'], ['O', 'X', 'X', 'O', 'X', 'O', 'O'], ['X', 'X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X', 'X', 'O', 'X', 'X', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'X', 'O', 'O', 'O', 'X', 'X', 'X', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'X', 'X', 'O', 'O', 'X', 'X', 'X', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X', 'X', 'O', 'X', 'X', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X'], ['X', 'O', 'O', 'X'], ['X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X'], ['X', 'O', 'O', 'X'], ['X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X', 'O', 'O', 'O', 'X'], ['X', 'O', 'X', 'O', 'X', 'O', 'X', 'X'], ['X', 'O', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'X', 'X', 'X', 'X', 'O', 'X'], ['X', 'O', 'X', 'X', 'O', 'X', 'X', 'X'], ['X', 'O', 'X', 'X', 'X', 'X', 'O', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['O', 'O', 'O', 'O', 'O'], ['O', 'X', 'X', 'X', 'O'], ['O', 'X', 'O', 'X', 'O'], ['O', 'X', 'X', 'X', 'O'], ['O', 'O', 'O', 'O', 'O']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X', 'X', 'O', 'X'], ['X', 'X', 'O', 'X', 'O', 'X', 'X'], ['X', 'O', 'X', 'O', 'O', 'X', 'X'], ['X', 'X', 'X', 'O', 'X', 'X', 'X'], ['X', 'O', 'O', 'X', 'X', 'O', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'O', 'X'], ['X', 'O', 'X', 'X', 'O', 'X'], ['X', 'O', 'X', 'O', 'X', 'X'], ['X', 'O', 'O', 'O', 'O', 'X'], ['X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'O', 'X'], ['X', 'X', 'X', 'X', 'X', 'X'], ['X', 'X', 'O', 'O', 'X', 'X'], ['X', 'O', 'X', 'O', 'X', 'X'], ['X', 'X', 'X', 'O', 'X', 'X'], ['X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'O', 'O', 'X'], ['X', 'O', 'X', 'X', 'X', 'O', 'X'], ['X', 'O', 'X', 'X', 'X', 'O', 'X'], ['X', 'O', 'X', 'O', 'X', 'O', 'X'], ['X', 'O', 'X', 'X', 'X', 'O', 'X'], ['X', 'X', 'O', 'O', 'O', 'O', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'O', 'X', 'O'], ['O', 'X', 'O', 'X', 'O', 'X'], ['X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'X', 'O', 'X', 'X'], ['X', 'X', 'O', 'X', 'X', 'O'], ['O', 'X', 'O', 'O', 'X', 'X']]) == None
    assert candidate(board = [['X', 'O', 'X', 'X', 'X'], ['X', 'O', 'X', 'O', 'X'], ['X', 'O', 'O', 'O', 'X'], ['X', 'X', 'X', 'X', 'X'], ['X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'X', 'X', 'O', 'O', 'X', 'X', 'X'], ['X', 'X', 'X', 'O', 'O', 'X', 'X', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X', 'O', 'X'], ['X', 'O', 'X', 'O', 'X', 'X'], ['X', 'X', 'O', 'X', 'O', 'X'], ['X', 'O', 'X', 'X', 'X', 'O'], ['X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'X'], ['X', 'X', 'X', 'O', 'X'], ['X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'O', 'X', 'X'], ['O', 'X', 'O', 'X'], ['X', 'O', 'O', 'X'], ['X', 'X', 'X', 'O'], ['X', 'O', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'X'], ['X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X', 'X'], ['X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'X'], ['X', 'X', 'X', 'O', 'X'], ['X', 'O', 'O', 'O', 'X'], ['X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X'], ['X', 'O', 'O', 'X'], ['X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X'], ['X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X', 'O', 'O', 'X'], ['X', 'X', 'O', 'X', 'O', 'X', 'X'], ['X', 'O', 'X', 'O', 'O', 'X', 'O'], ['X', 'X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'O', 'O', 'X', 'X'], ['X', 'X', 'X', 'X', 'X'], ['X', 'X', 'X', 'O', 'X'], ['X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X', 'X']]) == None
    assert candidate(board = [['X', 'O', 'X', 'O', 'X', 'O', 'X', 'O', 'X', 'O'], ['O', 'X', 'O', 'X', 'O', 'X', 'O', 'X', 'O', 'X'], ['X', 'O', 'X', 'O', 'X', 'O', 'X', 'O', 'X', 'O'], ['O', 'X', 'O', 'X', 'O', 'X', 'O', 'X', 'O', 'X'], ['X', 'O', 'X', 'O', 'X', 'O', 'X', 'O', 'X', 'O'], ['O', 'X', 'O', 'X', 'O', 'X', 'O', 'X', 'O', 'X'], ['X', 'O', 'X', 'O', 'X', 'O', 'X', 'O', 'X', 'O'], ['O', 'X', 'O', 'X', 'O', 'X', 'O', 'X', 'O', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'O', 'X'], ['X', 'O', 'X', 'X', 'O', 'X'], ['X', 'O', 'X', 'X', 'O', 'X'], ['X', 'O', 'X', 'X', 'O', 'X'], ['X', 'X', 'O', 'O', 'O', 'X']]) == None
    assert candidate(board = [['O', 'X', 'X', 'X', 'X', 'X', 'X', 'O'], ['X', 'X', 'X', 'O', 'O', 'X', 'X', 'X'], ['X', 'O', 'X', 'O', 'X', 'O', 'X', 'X'], ['X', 'X', 'O', 'X', 'O', 'X', 'O', 'X'], ['X', 'O', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'X', 'O', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'X', 'X', 'X', 'X', 'O', 'X'], ['O', 'X', 'X', 'X', 'X', 'X', 'X', 'O']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X', 'O', 'O', 'X', 'X'], ['X', 'O', 'X', 'X', 'X', 'X', 'O', 'X'], ['X', 'O', 'X', 'O', 'O', 'X', 'O', 'X'], ['X', 'O', 'X', 'X', 'X', 'X', 'O', 'X'], ['X', 'X', 'O', 'X', 'O', 'O', 'X', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'O', 'X', 'X'], ['X', 'O', 'O', 'X', 'X', 'X'], ['X', 'O', 'X', 'O', 'X', 'O'], ['X', 'X', 'O', 'X', 'O', 'X'], ['X', 'O', 'X', 'O', 'X', 'O'], ['X', 'O', 'O', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'O', 'X'], ['X', 'O', 'X', 'X', 'O', 'X'], ['X', 'O', 'X', 'O', 'O', 'X'], ['X', 'O', 'O', 'O', 'O', 'X'], ['X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'O', 'X', 'O', 'X', 'O'], ['O', 'X', 'O', 'X', 'O', 'X'], ['X', 'O', 'X', 'O', 'X', 'O'], ['O', 'X', 'O', 'X', 'O', 'X'], ['X', 'O', 'X', 'O', 'X', 'O']]) == None
    assert candidate(board = [['O', 'X', 'O', 'O', 'X', 'O', 'X'], ['O', 'X', 'X', 'O', 'O', 'X', 'X'], ['X', 'O', 'X', 'O', 'X', 'O', 'X'], ['X', 'X', 'X', 'O', 'O', 'X', 'O'], ['X', 'O', 'X', 'X', 'X', 'O', 'X'], ['O', 'X', 'X', 'O', 'O', 'X', 'O'], ['X', 'X', 'X', 'X', 'X', 'O', 'X']]) == None
    assert candidate(board = [['O', 'X', 'X', 'X', 'X', 'X', 'X', 'O'], ['X', 'O', 'O', 'X', 'O', 'X', 'O', 'X'], ['X', 'O', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'X', 'X', 'X', 'X', 'X', 'O'], ['X', 'X', 'O', 'X', 'O', 'X', 'X', 'X'], ['O', 'X', 'X', 'X', 'X', 'X', 'O', 'X'], ['X', 'O', 'X', 'X', 'X', 'O', 'X', 'O'], ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'X'], ['X', 'X', 'O', 'O', 'X'], ['X', 'X', 'X', 'O', 'X'], ['X', 'O', 'X', 'O', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'X', 'X', 'O', 'X'], ['X', 'X', 'X', 'X', 'O', 'O', 'X', 'X'], ['X', 'O', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'X', 'X', 'X', 'O', 'O', 'X', 'X'], ['X', 'O', 'O', 'O', 'X', 'X', 'O', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'X'], ['X', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X'], ['X', 'O', 'X', 'O', 'O', 'X', 'O', 'X', 'X'], ['X', 'O', 'X', 'X', 'X', 'X', 'O', 'X', 'X'], ['X', 'X', 'O', 'X', 'O', 'O', 'X', 'X', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'X', 'X', 'O', 'X'], ['X', 'O', 'X', 'X', 'O', 'X', 'X'], ['X', 'O', 'X', 'O', 'X', 'O', 'X'], ['X', 'X', 'O', 'X', 'X', 'O', 'X'], ['X', 'O', 'X', 'X', 'X', 'O', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'O', 'X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'X', 'O', 'X'], ['X', 'X', 'O', 'X', 'O', 'O', 'X'], ['X', 'O', 'X', 'O', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'X', 'O', 'X'], ['X', 'X', 'X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'X'], ['X', 'O', 'X', 'O', 'X'], ['X', 'O', 'O', 'O', 'X'], ['X', 'X', 'X', 'X', 'X'], ['X', 'X', 'X', 'X', 'X'], ['X', 'O', 'O', 'O', 'X'], ['X', 'X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'O'], ['X', 'O', 'O', 'O'], ['X', 'O', 'X', 'O'], ['X', 'O', 'O', 'X']]) == None
    assert candidate(board = [['X', 'X', 'X', 'O'], ['X', 'O', 'O', 'X'], ['X', 'O', 'X', 'X'], ['X', 'X', 'X', 'X']]) == None
    assert candidate(board = [['O', 'O', 'X', 'X'], ['X', 'X', 'O', 'O'], ['X', 'X', 'O', 'O'], ['O', 'O', 'X', 'X']]) == None
