# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abacbacbacb",k = 2) == 6
    assert candidate(s = "baccbaccbacc",k = 2) == 6
    assert candidate(s = "abcabcabcabcabc",k = 3) == 9
    assert candidate(s = "aabbaacc",k = 2) == 6
    assert candidate(s = "",k = 0) == 0
    assert candidate(s = "abc",k = 0) == 0
    assert candidate(s = "abcabcabcabcabcabc",k = 3) == 9
    assert candidate(s = "cccbbaaaa",k = 2) == 7
    assert candidate(s = "abacbcabc",k = 0) == 0
    assert candidate(s = "ccccccc",k = 2) == -1
    assert candidate(s = "aabbbccc",k = 2) == 6
    assert candidate(s = "aaaabbbbcccc",k = 4) == 12
    assert candidate(s = "aabaaaacaabc",k = 2) == 8
    assert candidate(s = "abcabcabc",k = 1) == 3
    assert candidate(s = "abcabcabc",k = 3) == 9
    assert candidate(s = "ccccccc",k = 3) == -1
    assert candidate(s = "a",k = 1) == -1
    assert candidate(s = "cccaaaabbb",k = 2) == 7
    assert candidate(s = "aabbcc",k = 1) == 4
    assert candidate(s = "aaabbbccc",k = 3) == 9
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc",k = 4) == 12
    assert candidate(s = "ccccccbbbaaa",k = 3) == 9
    assert candidate(s = "abacbacbacb",k = 3) == 9
    assert candidate(s = "aabbccaaabbcc",k = 2) == 6
    assert candidate(s = "abacbacbacbac",k = 2) == 6
    assert candidate(s = "baacababacbacbacbacbacb",k = 3) == 9
    assert candidate(s = "ababababababcabcabc",k = 3) == 9
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc",k = 5) == 15
    assert candidate(s = "bababababababa",k = 5) == -1
    assert candidate(s = "aaaabbbbccccaaaabbbbccccaaaabbbbcccc",k = 4) == 12
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabc",k = 4) == 12
    assert candidate(s = "bbbbbaaaaaccccaaaabbbbccccaaaa",k = 5) == 18
    assert candidate(s = "aabbbbccccaa",k = 2) == 8
    assert candidate(s = "abacabacabc",k = 2) == 6
    assert candidate(s = "aabacbacbacbac",k = 3) == 9
    assert candidate(s = "aabaaaabbbcccaabbcccaabbccc",k = 3) == 9
    assert candidate(s = "aabbbcccaaa",k = 3) == 9
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc",k = 6) == 18
    assert candidate(s = "ccccbbbaaaa",k = 3) == 10
    assert candidate(s = "bbbbbcccccc",k = 2) == -1
    assert candidate(s = "cccaaaabbbccc",k = 3) == 9
    assert candidate(s = "abcbaabcbaabcba",k = 2) == 6
    assert candidate(s = "aaaaaaaaaabbbbbbbbcccccccc",k = 4) == 16
    assert candidate(s = "abacbacbacbacbacbacbacbacb",k = 3) == 9
    assert candidate(s = "ccbbbaaa",k = 2) == 6
    assert candidate(s = "aabbccaaaabbcc",k = 3) == 10
    assert candidate(s = "abccbaabccba",k = 2) == 6
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbbcccccc",k = 5) == 16
    assert candidate(s = "baccbaabccba",k = 2) == 6
    assert candidate(s = "abcabcabcabcabcabcabc",k = 3) == 9
    assert candidate(s = "abcabcabcabcabc",k = 2) == 6
    assert candidate(s = "cccccccccccccccccc",k = 5) == -1
    assert candidate(s = "cccccccccccaabbbbbb",k = 3) == -1
    assert candidate(s = "abacabacabac",k = 3) == 11
    assert candidate(s = "abacabaacaba",k = 3) == -1
    assert candidate(s = "aabbbcccbbbcccaaa",k = 3) == 9
    assert candidate(s = "abcabcabcabcabcabcabcabcabc",k = 4) == 12
    assert candidate(s = "abccbaabcbaabc",k = 3) == 9
    assert candidate(s = "ccccccbbbbaaa",k = 2) == 7
    assert candidate(s = "aaaaabbbbbcccc",k = 1) == 6
    assert candidate(s = "aaaaaaabbbccc",k = 2) == 7
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc",k = 5) == 15
    assert candidate(s = "aaabbbcccbbbcccaaaccc",k = 4) == 14
    assert candidate(s = "cccbbbbaaa",k = 2) == 7
    assert candidate(s = "aabbccabcabcabcabcabcabc",k = 4) == 12
    assert candidate(s = "aabaaaacaabc",k = 5) == -1
    assert candidate(s = "aabccbaabccbaabccba",k = 3) == 9
    assert candidate(s = "bbbbbbbccccaaa",k = 2) == 7
    assert candidate(s = "aaabbbcccaaa",k = 2) == 8
    assert candidate(s = "bbbaaabbbcccaaa",k = 2) == 7
    assert candidate(s = "abcabcabcabcabcabcabcabc",k = 3) == 9
    assert candidate(s = "abacbacbacbacbacbac",k = 5) == 15
    assert candidate(s = "aabaaabccbbccaa",k = 3) == 10
    assert candidate(s = "bacbacbacbacbac",k = 4) == 12
    assert candidate(s = "ccccaaabbb",k = 2) == 7
    assert candidate(s = "acbbacaabcbab",k = 2) == 6
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc",k = 3) == 9
    assert candidate(s = "abababababababababcabcabcabc",k = 4) == 12
    assert candidate(s = "bcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcb",k = 3) == -1
    assert candidate(s = "abababababababababababababababababababababababab",k = 5) == -1
    assert candidate(s = "ccbaabacabcabcabcabcabcabcabcabcabcabc",k = 4) == 12
    assert candidate(s = "acbacbacbacbacbac",k = 2) == 6
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc",k = 10) == 30
    assert candidate(s = "cccccccccccccccccccccccccccccccccccccccccccccc",k = 15) == -1
    assert candidate(s = "cccbaaaaabbccc",k = 3) == 11
    assert candidate(s = "aababababababababababababa",k = 2) == -1
    assert candidate(s = "aabbcccaabbcccaabbccc",k = 5) == 16
    assert candidate(s = "ccababacabac",k = 2) == 6
    assert candidate(s = "aabbaabbaabbaabbcc",k = 4) == -1
    assert candidate(s = "ccbacababacba",k = 4) == 12
    assert candidate(s = "aabaaaabbbcccaabbcccaabbccc",k = 4) == 14
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabc",k = 5) == 15
    assert candidate(s = "cccccccccbaaaabbbccc",k = 3) == 9
    assert candidate(s = "bbaaccaabbbb",k = 2) == 6
    assert candidate(s = "abacbacbacbacbac",k = 4) == 12
    assert candidate(s = "caacbbacabcabc",k = 2) == 6
    assert candidate(s = "aabbccbaaabbccbaaabbcc",k = 2) == 6
    assert candidate(s = "cccccccccccbcccccccccc",k = 3) == -1
    assert candidate(s = "aabbcc",k = 0) == 0
    assert candidate(s = "cabcabcabcabcabcabcabcabcabcabcabc",k = 5) == 15
    assert candidate(s = "aabcaabcbaabcbaabcba",k = 4) == 16
    assert candidate(s = "ccccccbbbaaaaaaacccccccbbbaaaaaa",k = 4) == 16
    assert candidate(s = "abacabadabacaba",k = 3) == -1
    assert candidate(s = "bcccccccccccba",k = 3) == -1
    assert candidate(s = "aaabbbccc",k = 0) == 0
    assert candidate(s = "bcbcbcbcbcbc",k = 2) == -1
    assert candidate(s = "abcabcabcabcabcabc",k = 2) == 6
    assert candidate(s = "bacbacbacbacbacbacbacbacbacbacbacbac",k = 4) == 12
    assert candidate(s = "cccccccccccccccccccccccccc",k = 10) == -1
    assert candidate(s = "aabbbcccddd",k = 1) == 7
    assert candidate(s = "ccbaabccbaabccba",k = 3) == 9
    assert candidate(s = "ababababababababababababababababababababababababab",k = 6) == -1
    assert candidate(s = "ccccccaaaabbbb",k = 2) == 8
    assert candidate(s = "ccccbbbbaaaaccccbbaaaccccbbaa",k = 4) == 12
    assert candidate(s = "aabaaaacaabc",k = 3) == -1
    assert candidate(s = "bbbbbbbaaaaaaaccccccc",k = 3) == 13
    assert candidate(s = "cacacacacacaca",k = 2) == -1
    assert candidate(s = "bbacccbaaa",k = 2) == 6
    assert candidate(s = "bbbaaacccbbbaaacccbbbaaacccbbbaaaccc",k = 3) == 9
    assert candidate(s = "aabaaaacaabcbbbccc",k = 3) == 9
    assert candidate(s = "abcabcabcabcabcabcabc",k = 4) == 12
    assert candidate(s = "aabccccbaa",k = 1) == 4
    assert candidate(s = "aaaaabbbbbccccc",k = 2) == 9
    assert candidate(s = "abacabadabacabadabacabad",k = 4) == -1
    assert candidate(s = "ccccbbbaaa",k = 2) == 7
    assert candidate(s = "aaaaaaaaaaa",k = 1) == -1
    assert candidate(s = "abacabacabacabacabacabacabacabacabacabac",k = 5) == 19
    assert candidate(s = "aabbcc",k = 2) == 6
    assert candidate(s = "aabcaaacbbacabcabc",k = 4) == 12
