# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(n = 8,m = 8) == 1
    assert candidate(n = 1,m = 1) == 1
    assert candidate(n = 10,m = 14) == 5
    assert candidate(n = 7,m = 7) == 1
    assert candidate(n = 9,m = 10) == 6
    assert candidate(n = 7,m = 8) == 7
    assert candidate(n = 6,m = 7) == 5
    assert candidate(n = 6,m = 10) == 4
    assert candidate(n = 8,m = 9) == 7
    assert candidate(n = 3,m = 3) == 1
    assert candidate(n = 4,m = 10) == 4
    assert candidate(n = 11,m = 13) == 6
    assert candidate(n = 5,m = 8) == 5
    assert candidate(n = 12,m = 13) == 7
    assert candidate(n = 4,m = 6) == 3
    assert candidate(n = 10,m = 11) == 6
    assert candidate(n = 9,m = 12) == 4
    assert candidate(n = 9,m = 11) == 7
    assert candidate(n = 13,m = 13) == 1
    assert candidate(n = 3,m = 5) == 4
    assert candidate(n = 2,m = 3) == 3
    assert candidate(n = 10,m = 10) == 1
    assert candidate(n = 6,m = 6) == 1
    assert candidate(n = 7,m = 12) == 6
    assert candidate(n = 3,m = 11) == 6
    assert candidate(n = 11,m = 10) == 6
    assert candidate(n = 13,m = 5) == 6
    assert candidate(n = 12,m = 7) == 6
    assert candidate(n = 13,m = 7) == 6
    assert candidate(n = 5,m = 11) == 6
    assert candidate(n = 5,m = 12) == 6
    assert candidate(n = 3,m = 14) == 7
    assert candidate(n = 8,m = 15) == 8
    assert candidate(n = 7,m = 13) == 6
    assert candidate(n = 9,m = 9) == 1
    assert candidate(n = 3,m = 7) == 5
    assert candidate(n = 4,m = 15) == 7
    assert candidate(n = 6,m = 11) == 6
    assert candidate(n = 14,m = 14) == 1
    assert candidate(n = 2,m = 13) == 8
    assert candidate(n = 6,m = 13) == 6
    assert candidate(n = 6,m = 9) == 3
    assert candidate(n = 4,m = 9) == 6
    assert candidate(n = 8,m = 12) == 3
    assert candidate(n = 4,m = 11) == 6
    assert candidate(n = 13,m = 12) == 7
    assert candidate(n = 10,m = 5) == 2
    assert candidate(n = 4,m = 7) == 5
    assert candidate(n = 7,m = 10) == 6
    assert candidate(n = 12,m = 5) == 6
    assert candidate(n = 12,m = 14) == 5
    assert candidate(n = 9,m = 7) == 6
    assert candidate(n = 10,m = 12) == 5
    assert candidate(n = 8,m = 13) == 6
    assert candidate(n = 12,m = 11) == 7
    assert candidate(n = 10,m = 15) == 3
    assert candidate(n = 9,m = 14) == 7
    assert candidate(n = 8,m = 10) == 5
    assert candidate(n = 3,m = 10) == 6
    assert candidate(n = 11,m = 9) == 7
    assert candidate(n = 8,m = 11) == 6
    assert candidate(n = 13,m = 6) == 6
    assert candidate(n = 5,m = 9) == 6
    assert candidate(n = 4,m = 13) == 7
    assert candidate(n = 12,m = 15) == 5
    assert candidate(n = 12,m = 10) == 5
