# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(mainTank = 10,additionalTank = 0) == 100
    assert candidate(mainTank = 100,additionalTank = 100) == 1240
    assert candidate(mainTank = 5,additionalTank = 10) == 60
    assert candidate(mainTank = 3,additionalTank = 0) == 30
    assert candidate(mainTank = 7,additionalTank = 3) == 80
    assert candidate(mainTank = 0,additionalTank = 5) == 0
    assert candidate(mainTank = 1,additionalTank = 2) == 10
    assert candidate(mainTank = 0,additionalTank = 10) == 0
    assert candidate(mainTank = 10,additionalTank = 5) == 120
    assert candidate(mainTank = 0,additionalTank = 50) == 0
    assert candidate(mainTank = 20,additionalTank = 0) == 200
    assert candidate(mainTank = 20,additionalTank = 20) == 240
    assert candidate(mainTank = 5,additionalTank = 0) == 50
    assert candidate(mainTank = 45,additionalTank = 5) == 500
    assert candidate(mainTank = 80,additionalTank = 10) == 900
    assert candidate(mainTank = 55,additionalTank = 0) == 550
    assert candidate(mainTank = 15,additionalTank = 1) == 160
    assert candidate(mainTank = 1,additionalTank = 50) == 10
    assert candidate(mainTank = 3,additionalTank = 20) == 30
    assert candidate(mainTank = 50,additionalTank = 50) == 620
    assert candidate(mainTank = 25,additionalTank = 30) == 310
    assert candidate(mainTank = 25,additionalTank = 10) == 310
    assert candidate(mainTank = 5,additionalTank = 25) == 60
    assert candidate(mainTank = 80,additionalTank = 20) == 990
    assert candidate(mainTank = 30,additionalTank = 3) == 330
    assert candidate(mainTank = 50,additionalTank = 15) == 620
    assert candidate(mainTank = 49,additionalTank = 5) == 540
    assert candidate(mainTank = 45,additionalTank = 50) == 560
    assert candidate(mainTank = 3,additionalTank = 4) == 30
    assert candidate(mainTank = 30,additionalTank = 30) == 370
    assert candidate(mainTank = 7,additionalTank = 1) == 80
    assert candidate(mainTank = 99,additionalTank = 99) == 1230
    assert candidate(mainTank = 75,additionalTank = 15) == 900
    assert candidate(mainTank = 9,additionalTank = 3) == 110
    assert candidate(mainTank = 60,additionalTank = 30) == 740
    assert candidate(mainTank = 9,additionalTank = 2) == 110
    assert candidate(mainTank = 15,additionalTank = 2) == 170
    assert candidate(mainTank = 50,additionalTank = 10) == 600
    assert candidate(mainTank = 75,additionalTank = 20) == 930
    assert candidate(mainTank = 5,additionalTank = 50) == 60
    assert candidate(mainTank = 8,additionalTank = 1) == 90
    assert candidate(mainTank = 30,additionalTank = 0) == 300
    assert candidate(mainTank = 99,additionalTank = 1) == 1000
    assert candidate(mainTank = 30,additionalTank = 8) == 370
    assert candidate(mainTank = 40,additionalTank = 30) == 490
    assert candidate(mainTank = 10,additionalTank = 99) == 120
    assert candidate(mainTank = 80,additionalTank = 3) == 830
    assert candidate(mainTank = 3,additionalTank = 7) == 30
    assert candidate(mainTank = 9,additionalTank = 10) == 110
    assert candidate(mainTank = 15,additionalTank = 0) == 150
    assert candidate(mainTank = 75,additionalTank = 25) == 930
    assert candidate(mainTank = 49,additionalTank = 10) == 590
    assert candidate(mainTank = 25,additionalTank = 0) == 250
    assert candidate(mainTank = 75,additionalTank = 30) == 930
    assert candidate(mainTank = 24,additionalTank = 6) == 290
    assert candidate(mainTank = 45,additionalTank = 30) == 560
    assert candidate(mainTank = 99,additionalTank = 100) == 1230
    assert candidate(mainTank = 25,additionalTank = 5) == 300
    assert candidate(mainTank = 45,additionalTank = 10) == 550
    assert candidate(mainTank = 80,additionalTank = 8) == 880
    assert candidate(mainTank = 49,additionalTank = 2) == 510
    assert candidate(mainTank = 50,additionalTank = 25) == 620
    assert candidate(mainTank = 30,additionalTank = 15) == 370
    assert candidate(mainTank = 100,additionalTank = 1) == 1010
    assert candidate(mainTank = 25,additionalTank = 25) == 310
    assert candidate(mainTank = 25,additionalTank = 15) == 310
    assert candidate(mainTank = 60,additionalTank = 25) == 740
    assert candidate(mainTank = 60,additionalTank = 0) == 600
    assert candidate(mainTank = 8,additionalTank = 7) == 90
    assert candidate(mainTank = 5,additionalTank = 20) == 60
    assert candidate(mainTank = 2,additionalTank = 10) == 20
    assert candidate(mainTank = 5,additionalTank = 5) == 60
    assert candidate(mainTank = 30,additionalTank = 10) == 370
    assert candidate(mainTank = 8,additionalTank = 3) == 90
    assert candidate(mainTank = 60,additionalTank = 15) == 740
    assert candidate(mainTank = 10,additionalTank = 9) == 120
    assert candidate(mainTank = 100,additionalTank = 0) == 1000
    assert candidate(mainTank = 5,additionalTank = 4) == 60
    assert candidate(mainTank = 4,additionalTank = 5) == 40
