# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "qpqprstuvwxyzqpqprstuvwxyzqpqprstuvwxyz") == 48
    assert candidate(s = "abczabczabcz") == 10
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 351
    assert candidate(s = "azza") == 3
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "za") == 3
    assert candidate(s = "qpqprstuvwxyz") == 48
    assert candidate(s = "zaabcdefghijklmnopqrstuvwxyz") == 352
    assert candidate(s = "a") == 1
    assert candidate(s = "abcabcabc") == 6
    assert candidate(s = "zabcdefghijklmnopqrstuvwxyz") == 377
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "xyzxyzxyz") == 6
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 1027
    assert candidate(s = "abcd") == 10
    assert candidate(s = "abczab") == 9
    assert candidate(s = "cac") == 2
    assert candidate(s = "cab") == 4
    assert candidate(s = "zab") == 6
    assert candidate(s = "zabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 1053
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "abcabcdabcdeabcdefabcdefg") == 28
    assert candidate(s = "mnopqrstuvwxyza") == 120
    assert candidate(s = "pqrstuvwxyzabcdefghijklmno") == 351
    assert candidate(s = "aaaabbbbccccddddeeeeffffgggghhhhiiiijjjjkkkkllllmmmmnnnnooooqqqqrrrrssssttttuuuuvvvvwwwwxxxxyyyyzzzz") == 48
    assert candidate(s = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd") == 10
    assert candidate(s = "mnopqrstuvwxyzabcdefghijkl") == 351
    assert candidate(s = "nopqrstuvwxyzabcdefghijklmno") == 403
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "aaaaaaaaaabbbbbbbbcccccccc") == 5
    assert candidate(s = "qrstuvqrstuvqrstuvqrstuvqrstuvqrstuvqrstuvqrstuvqrstuv") == 21
    assert candidate(s = "vwxyzabcdefghijklmnopqrstu") == 351
    assert candidate(s = "abcdbca") == 10
    assert candidate(s = "zabzabzabzabzabzabzabzabzabzabzabzabzabzabzab") == 6
    assert candidate(s = "abacabadabacaba") == 5
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "abcabcabcabc") == 6
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 1703
    assert candidate(s = "cdefghijklmnopqrstuvwxyzab") == 351
    assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij") == 55
    assert candidate(s = "abababababababababababababababababababab") == 3
    assert candidate(s = "abcdefgabcdefgabcdefgabcdefg") == 28
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 3055
    assert candidate(s = "abcdzabcde") == 21
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzaabcdefghijklmnopqrstuvwxyzab") == 403
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 351
    assert candidate(s = "abcdefghijklmnopqrstuvwxyza") == 377
    assert candidate(s = "zzzzzzzzzz") == 1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 2379
    assert candidate(s = "qpqrstuvwxyzabcdefghijklmno") == 351
    assert candidate(s = "xyzabcdezyxabcdezyxabcdezyxabcdezyxabcdezyxabcdezyx") == 36
    assert candidate(s = "aaaabbbbccccddddeeeeffffgggghhhhiiiijjjjkkkkllllmmmmnnnnooooppppqqqqrrrrssssttttuuuuvvvvwwwwxxxxyyyyzzzz") == 51
    assert candidate(s = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz") == 6
    assert candidate(s = "qpqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcba") == 27
    assert candidate(s = "abcdabcdeabcdefabcdefgabcdefg") == 28
    assert candidate(s = "abcdzabcdezabcdefzabcdefgzabcdefgz") == 36
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba") == 26
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcbaabcdefghijklmnopqrstuvwxyz") == 351
    assert candidate(s = "mnopqrstuvwxyzabcdefghijklmnop") == 455
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcbaabcdefghijklmnopqrstuvwxyz") == 351
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 51
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcba") == 351
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcba") == 26
    assert candidate(s = "xyzabcdefghijklmnopqrstuvwxyz") == 429
    assert candidate(s = "xyzabc") == 21
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
