# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abcba") == 3
    assert candidate(s = "madam") == 3
    assert candidate(s = "abcdedcba") == 10
    assert candidate(s = "aaaaa") == 1
    assert candidate(s = "adc") == 0
    assert candidate(s = "abcabcabc") == 9
    assert candidate(s = "abracadabra") == 13
    assert candidate(s = "aaa") == 1
    assert candidate(s = "racecar") == 6
    assert candidate(s = "abba") == 1
    assert candidate(s = "noon") == 1
    assert candidate(s = "abccba") == 3
    assert candidate(s = "aaaa") == 1
    assert candidate(s = "aabbcc") == 0
    assert candidate(s = "mississippi") == 5
    assert candidate(s = "aabca") == 3
    assert candidate(s = "bbcbaba") == 4
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 0
    assert candidate(s = "xyzzyx") == 3
    assert candidate(s = "level") == 3
    assert candidate(s = "abcdefg") == 0
    assert candidate(s = "aabacbaabacba") == 8
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == 0
    assert candidate(s = "noonmoonnoonmoonnoonmoonnoonmoonnoonmoonnoonmoonnoon") == 9
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzyyxwwvvuuttssrrqqppoonnmmllkkjjiihhggeeffddccbbaa") == 352
    assert candidate(s = "zzzzzzzyyyyxxxwwvvuttsrrqqppoonnmmllkkjjiihhggffeeddccba") == 3
    assert candidate(s = "zzzazzaaz") == 4
    assert candidate(s = "abacabadabacaba") == 11
    assert candidate(s = "ababababababababababababababababababababab") == 4
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabc") == 9
    assert candidate(s = "ababcab") == 6
    assert candidate(s = "abacabadabacabadabacabadabacabad") == 16
    assert candidate(s = "racecarcarcarecarracecarcarcarecarracecarcarcarecarracecar") == 16
    assert candidate(s = "abacdfgdcaba") == 16
    assert candidate(s = "aabbbaaabbbaaa") == 4
    assert candidate(s = "aaabaaaabaaaaabaaaabaaaaaabaaaa") == 4
    assert candidate(s = "aaaabaaaabaaaab") == 4
    assert candidate(s = "abcbabcbabcbabcbabcbabcbabcba") == 9
    assert candidate(s = "bababababababababababababababababababababa") == 4
    assert candidate(s = "abcbacbacbacbacbacbacbacbacbacbacbacbacbacbacbacbacbac") == 9
    assert candidate(s = "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd") == 4
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 325
    assert candidate(s = "xyzyxyzyxyzyx") == 9
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 650
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcbaedcba") == 20
    assert candidate(s = "abbaabbbaabbaabbbaabbaabbbaabbaabbbaabbaabbba") == 4
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 9
    assert candidate(s = "abcdefghihgfedcbaabcdefghihgfedcba") == 80
    assert candidate(s = "aaaabbbbccccddddeeeeffffgggghhhhiiiijjjjkkkkllllmmmmnnnnooooppppqqqqrrrrssssttttuuuuvvvvwwwwxxxxyyyyzzzz") == 26
    assert candidate(s = "aaabaaaabaaaabaaaabaaaabaaaabaaaabaaaabaaaab") == 4
    assert candidate(s = "abcbacbacbacbacbacbacbacbacbacbacbacbacb") == 9
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzz") == 1
    assert candidate(s = "babababababababababababababababababababababababababababababa") == 4
    assert candidate(s = "aabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabba") == 4
    assert candidate(s = "aaaabbbbccccddddeeeeffffgggghhhhiiiijjjjkkkkllllmmmmnnnnooooppppqqqqrrrrssssttttuuuuvvvvwwwwxxxxyyyyzzzzzz") == 26
    assert candidate(s = "mamamadadadmmadammaddada") == 9
    assert candidate(s = "aabbccddeeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 1
    assert candidate(s = "ababababababababababababababababababababababababababab") == 4
    assert candidate(s = "aaaaaaaaaaaabbbbbbbbbbbbccccccccccdddddddddd") == 4
    assert candidate(s = "racecarcarcarecarracecarcarcarecarracecar") == 16
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 9
    assert candidate(s = "abacbacbacbacba") == 9
    assert candidate(s = "ababababababababababababababababababababababababababababababab") == 4
    assert candidate(s = "mississippississippiississippiississippiississippiississippi") == 9
    assert candidate(s = "abcabcabcabcabc") == 9
    assert candidate(s = "noonmoonnoonmoon") == 8
    assert candidate(s = "noonmoonnoonmoonnoonmoonnoonmoonnoonmoonnoonmoonnoonnoonmoon") == 9
    assert candidate(s = "aaaaabbbbbccccc") == 3
    assert candidate(s = "mississippississippiississippiississippiississippi") == 9
    assert candidate(s = "abacabadabacabadabacabadabacabadabacabadabacabad") == 16
    assert candidate(s = "zzzzzyyyxxwwvvuttsrrqqppoonnmmllkkjjiihhggffeeddccba") == 2
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba") == 0
    assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == 9
    assert candidate(s = "aabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabba") == 4
