# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "(())*") == True
    assert candidate(s = "((((((**))))))") == True
    assert candidate(s = "(()*") == True
    assert candidate(s = "****") == True
    assert candidate(s = "(()****)") == True
    assert candidate(s = "*()") == True
    assert candidate(s = "(()***)") == True
    assert candidate(s = "((*)*())") == True
    assert candidate(s = "())(*") == False
    assert candidate(s = "((*))") == True
    assert candidate(s = "(*)*") == True
    assert candidate(s = "(()))") == False
    assert candidate(s = "(()(()))") == True
    assert candidate(s = "(*))") == True
    assert candidate(s = "(**)") == True
    assert candidate(s = "(*)()") == True
    assert candidate(s = "()") == True
    assert candidate(s = "((()))") == True
    assert candidate(s = "(*)") == True
    assert candidate(s = "((*)") == True
    assert candidate(s = "()()") == True
    assert candidate(s = "(()*())") == True
    assert candidate(s = "(())))") == False
    assert candidate(s = "(***)") == True
    assert candidate(s = "(()*()*(*)*())") == True
    assert candidate(s = "(())*(())*") == True
    assert candidate(s = "((**))*((*))*(**)") == True
    assert candidate(s = "((((((()))))))***") == True
    assert candidate(s = "(((())))*(())") == True
    assert candidate(s = "(*(()*(())*))") == True
    assert candidate(s = "()***(())()") == True
    assert candidate(s = "((**(*)))") == True
    assert candidate(s = "(*)*(*)(*)*(*)(*)") == True
    assert candidate(s = "((((()))))))**(()((()))") == False
    assert candidate(s = "(()(()(()(*)))))") == True
    assert candidate(s = "(*((((**)))))") == True
    assert candidate(s = "((((**))))*(((**))))") == True
    assert candidate(s = "(*(*(*(*(*(*(*)))))****)") == True
    assert candidate(s = "(((((())))))") == True
    assert candidate(s = "(((((((*))))))") == True
    assert candidate(s = "((*)*(()))") == True
    assert candidate(s = "(**(())(*))") == True
    assert candidate(s = "(()**(**))") == True
    assert candidate(s = "((())((**)))") == True
    assert candidate(s = "((*)*)((**))") == True
    assert candidate(s = "(*(*(***))*))*") == True
    assert candidate(s = "(()*((*)))") == True
    assert candidate(s = "((*)*(*(*)))") == True
    assert candidate(s = "()**(((())))****") == True
    assert candidate(s = "(*)**(**)") == True
    assert candidate(s = "((*(**)))*(**)") == True
    assert candidate(s = "((*(**))*)*()") == True
    assert candidate(s = "((()))*(()**)**") == True
    assert candidate(s = "(())*(())*(())*((()))") == True
    assert candidate(s = "(*(*))**") == True
    assert candidate(s = "(**(**))") == True
    assert candidate(s = "((**))") == True
    assert candidate(s = "(()*())*()") == True
    assert candidate(s = "((*)()(**))") == True
    assert candidate(s = "(**((*)*))**") == True
    assert candidate(s = "(()***(())*)") == True
    assert candidate(s = "((*)(*(*)))") == True
    assert candidate(s = "(((())))*****") == True
    assert candidate(s = "((*)(*))(())((**))") == True
    assert candidate(s = "((*)(*)(*)(*))") == True
    assert candidate(s = "*(((******)))*") == True
    assert candidate(s = "((**)*))") == True
    assert candidate(s = "()(()(()(*)))") == True
    assert candidate(s = "(*)*(((**))*))") == True
    assert candidate(s = "(*(**))*((*)*)") == True
    assert candidate(s = "()(()())*") == True
    assert candidate(s = "(*(()*(()*)))") == True
    assert candidate(s = "(()*(()*(())))") == True
    assert candidate(s = "*(*(*(*)))**") == True
    assert candidate(s = "(())*()(())*()") == True
    assert candidate(s = "((((****))))") == True
    assert candidate(s = "((((())*)*))**") == True
    assert candidate(s = "((((((()))))))") == True
    assert candidate(s = "(((((**)))))") == True
    assert candidate(s = "(()*((())))") == True
    assert candidate(s = "(()(()))**") == True
    assert candidate(s = "(((()**)))(((()**)))") == True
    assert candidate(s = "(((()*****)****))") == True
    assert candidate(s = "(**)))(**(") == False
    assert candidate(s = "(())(())((**))") == True
    assert candidate(s = "(*(*(*(*(*)))))") == True
    assert candidate(s = "((((*))())*())") == True
    assert candidate(s = "(*(*(*)*))") == True
    assert candidate(s = "(((*)))((***))") == True
    assert candidate(s = "*(()*(())*(())**)") == True
    assert candidate(s = "(((***)))(((***)))") == True
    assert candidate(s = "*()**(**)()") == True
    assert candidate(s = "((*)(*))*") == True
    assert candidate(s = "(((*)**)*(***))") == True
    assert candidate(s = "((((*((*)))))") == True
    assert candidate(s = "**(()))*((***)**") == True
    assert candidate(s = "((((())))*)") == True
    assert candidate(s = "(*)*(*)") == True
    assert candidate(s = "((**)((()))*)**") == True
    assert candidate(s = "(()*()(*()*)*())") == True
    assert candidate(s = "(*(*))(*)") == True
    assert candidate(s = "(*)*(**(()**))") == True
    assert candidate(s = "((((**)))))") == True
    assert candidate(s = "(*())*()()*(())*") == True
    assert candidate(s = "((()))*(((**)))") == True
    assert candidate(s = "*(((*)*))") == True
    assert candidate(s = "(((****)))()") == True
    assert candidate(s = "((*)(*))(*)") == True
    assert candidate(s = "(**())((()))") == True
    assert candidate(s = "(((*))*)*(()))") == True
    assert candidate(s = "(((((******)))))") == True
    assert candidate(s = "(*(*(*)))") == True
    assert candidate(s = "(*(()*())*)") == True
    assert candidate(s = "(((((*)))))") == True
    assert candidate(s = "(***(**))") == True
    assert candidate(s = "(*(*(())))(((()))*)") == True
    assert candidate(s = "(()***)((()))") == True
    assert candidate(s = "((**())*(**))") == True
    assert candidate(s = "(())**(())") == True
    assert candidate(s = "((**)*)") == True
    assert candidate(s = "(()(**)()*)") == True
    assert candidate(s = "((*(())*)*)") == True
    assert candidate(s = "(*(*(*(*))))") == True
    assert candidate(s = "*(*(())*)*") == True
    assert candidate(s = "((()))(*(*)*())") == True
    assert candidate(s = "((*)(*)(*))((*)*)") == True
    assert candidate(s = "(*(*(*(*(*))))*") == True
    assert candidate(s = "(((())))**(**)***") == True
    assert candidate(s = "((**(())*(**)))") == True
    assert candidate(s = "(()(*(*)*))") == True
    assert candidate(s = "(()*(())**(())*(())*)") == True
    assert candidate(s = "(*((((())))))") == True
    assert candidate(s = "*()*(*)()") == True
    assert candidate(s = "(**((((**))))**") == True
    assert candidate(s = "(()*(()))") == True
    assert candidate(s = "(*(()*(()*(()*())))*)") == True
    assert candidate(s = "((***))((***))") == True
    assert candidate(s = "((*)*(*))") == True
    assert candidate(s = "((((*)))((**))((*))*)") == True
    assert candidate(s = "((((*)))()*)*") == True
    assert candidate(s = "**((**))**") == True
    assert candidate(s = "((((*)(*)(*))))****") == True
    assert candidate(s = "()**())((**))") == True
    assert candidate(s = "()**(**)()") == True
    assert candidate(s = "((**()))(*(()))") == True
    assert candidate(s = "((((()**))**))") == True
    assert candidate(s = "(*(*((())))**)") == True
    assert candidate(s = "(*(()))") == True
    assert candidate(s = "(()*(()**()))") == True
    assert candidate(s = "((((*))))(*)") == True
    assert candidate(s = "(**)(**)(**)") == True
    assert candidate(s = "(((*)))") == True
    assert candidate(s = "(()))(**(") == False
    assert candidate(s = "((*)((*)*))") == True
    assert candidate(s = "((*)(*)(*))") == True
    assert candidate(s = "(*()(*))**((*))**") == True
    assert candidate(s = "((*)(*))") == True
    assert candidate(s = "((***(****)))") == True
    assert candidate(s = "(((())))(*)(())") == True
    assert candidate(s = "((((**))))") == True
    assert candidate(s = "(**(*)*())(())**") == True
    assert candidate(s = "(***(())***)") == True
    assert candidate(s = "((())*(())*(())**)") == True
    assert candidate(s = "()(*(*(*())))") == True
    assert candidate(s = "(*(*)**(*)))") == True
    assert candidate(s = "((()))*()**") == True
    assert candidate(s = "(*)*(*(*)*(*))") == True
    assert candidate(s = "(())(((*)))") == True
    assert candidate(s = "(()*()(*))") == True
    assert candidate(s = "(()*(()*()**))") == True
    assert candidate(s = "((((*)**))***)") == True
    assert candidate(s = "((((()))))") == True
    assert candidate(s = "*(((****)(**))))") == True
    assert candidate(s = "(())((()))**") == True
    assert candidate(s = "**((((((()))))))**") == True
    assert candidate(s = "((**(**))**(**))") == True
    assert candidate(s = "(**(*)*)") == True
    assert candidate(s = "((((*))*)*))))") == True
    assert candidate(s = "(()***)()") == True
    assert candidate(s = "(())((()))***") == True
    assert candidate(s = "((()))(*)(((***)))*") == True
