# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "raceecar") == True
    assert candidate(s = "abcba") == True
    assert candidate(s = "deeee") == True
    assert candidate(s = "ab") == True
    assert candidate(s = "abc") == False
    assert candidate(s = "racecarx") == True
    assert candidate(s = "abca") == True
    assert candidate(s = "abcdedcba") == True
    assert candidate(s = "abcdefgihgfedcba") == True
    assert candidate(s = "abcdefdba") == False
    assert candidate(s = "aabaa") == True
    assert candidate(s = "racecar") == True
    assert candidate(s = "a") == True
    assert candidate(s = "abcdefg") == False
    assert candidate(s = "aba") == True
    assert candidate(s = "aabbbbaaabbb") == False
    assert candidate(s = "abcdefghijklnkjihgfedcba") == True
    assert candidate(s = "abcdefghikjlmnopqrstuvutsrqponmlkjihgfedcba") == False
    assert candidate(s = "aabbaa") == True
    assert candidate(s = "noonappa") == False
    assert candidate(s = "zxcvbnmlkjihgfedcbazyxwvutsrqponmlkjihgfedcba") == False
    assert candidate(s = "abcdexyzzyxedcba") == True
    assert candidate(s = "aaaabbbbccccddddcccccccddddbbbbbbaaaaa") == False
    assert candidate(s = "aabbcccbbbaa") == True
    assert candidate(s = "flgfgldad") == False
    assert candidate(s = "tattarrattat") == True
    assert candidate(s = "aabbccddeeeedcba") == False
    assert candidate(s = "aabbacdfgfddcabbaa") == True
    assert candidate(s = "zzzzzzzzzz") == True
    assert candidate(s = "aabbccddeeeffgggghhhiiiijjjjkkoollmmnnnnooppqqrrsstttuuuvvvvwwxxyyyzzzzyyyyxwvvvvuuutttsrrrqpnoonmlkkkiiihhhhggggfffeeedddccbbaa") == False
    assert candidate(s = "aabbccddeeeffgggihhii") == False
    assert candidate(s = "qwertyuiopoiuytrewq") == True
    assert candidate(s = "zxcvbnmasdfghjklqwertyuiopasdfghjklzxcvbnm") == False
    assert candidate(s = "aabbccddeeffgghhiaahhgffeeddccbbaa") == False
    assert candidate(s = "abcdefghihgfeddcba") == True
    assert candidate(s = "abcdabc") == False
    assert candidate(s = "aabbcddcbbbaa") == True
    assert candidate(s = "aabbbbbaaabbbb") == False
    assert candidate(s = "aabbaabbaa") == True
    assert candidate(s = "aabcaaba") == False
    assert candidate(s = "aabbccddeeffgghhijjihhgffeeddccbbaa") == True
    assert candidate(s = "aguokepatgbnvfqmgmlcupuufxoohdfpgjdmysgvhmvffcnqxjjxqncffvmhvgsymdjgpfdhooxfuupucmlmgqfvnbgtapekouga") == False
    assert candidate(s = "abcdcba") == True
    assert candidate(s = "abcdexyzxedcba") == True
    assert candidate(s = "aabbccddee") == False
    assert candidate(s = "abbaabbaabbaabba") == True
    assert candidate(s = "racecarwitharacecarinitt") == False
    assert candidate(s = "racecarxracecar") == True
    assert candidate(s = "aabbacdfgdcabbaa") == True
    assert candidate(s = "abbaaaabba") == True
    assert candidate(s = "aabbccddeedccbbaa") == True
    assert candidate(s = "aabbccddeeeffgggghhhhiiiijjjjkkkkllmmnnnnooppqqrrsstttuuuvvvvvwwxxyyyzzzzzzzyyyyxwvvvvuuutttsrrrqpnoonmlkkkiiihhhhggggfffeeedddccbbaa") == False
    assert candidate(s = "abcaabcba") == True
    assert candidate(s = "raceacar") == True
    assert candidate(s = "noon") == True
    assert candidate(s = "abcdeffedcba") == True
    assert candidate(s = "level") == True
    assert candidate(s = "aabbbbbbbaaabbbbbb") == False
    assert candidate(s = "aaaaabbaaaaa") == True
    assert candidate(s = "abcdefghhgfedcba") == True
    assert candidate(s = "aabbccddeeeffggghhiiii") == False
    assert candidate(s = "ababababababa") == True
    assert candidate(s = "zxcvbnmasdfghjklqwertyuiopplkjhgfdsazxcvbnm") == False
    assert candidate(s = "abcdefghijkjihgfedcba") == True
    assert candidate(s = "aabbccddeedcba") == False
    assert candidate(s = "aabbccddeeefffggg") == False
    assert candidate(s = "levelwithoneleveldropped") == False
    assert candidate(s = "noonwithanothernoon") == False
    assert candidate(s = "abzcdedcba") == True
    assert candidate(s = "acbbbca") == True
    assert candidate(s = "lcupuufxoohdfpgjdmysgvhmvffcnqxjjxqncffvmhvgsymdjgpfdhooxfuupuc") == True
    assert candidate(s = "abcbad") == True
    assert candidate(s = "abcdefghijkmlkjihgfedcba") == True
    assert candidate(s = "abcdexyzzyxdecba") == False
    assert candidate(s = "abccba") == True
    assert candidate(s = "abcdxzyxcba") == False
    assert candidate(s = "madamimadam") == True
    assert candidate(s = "aabbabba") == True
    assert candidate(s = "abcdefghihgfedcbai") == True
    assert candidate(s = "amanaplanacanalpanama") == True
    assert candidate(s = "aabbccddeedccbaa") == False
    assert candidate(s = "aebcbda") == False
    assert candidate(s = "deified") == True
    assert candidate(s = "repaper") == True
    assert candidate(s = "eedede") == True
    assert candidate(s = "abcdeffgedcba") == True
    assert candidate(s = "acbbcdcba") == False
    assert candidate(s = "aabbaaabbaa") == True
    assert candidate(s = "abcdefghijkllkjihgfedcba") == True
    assert candidate(s = "abacdfgdcaba") == True
    assert candidate(s = "abcdefghijklmnopqrrponmlkjihgfedcba") == True
    assert candidate(s = "abacdfgdfcba") == False
    assert candidate(s = "aabbccdddccbaa") == True
    assert candidate(s = "abcddcba") == True
    assert candidate(s = "aaaaabaaa") == True
    assert candidate(s = "rotor") == True
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyz") == False
    assert candidate(s = "abcdefghihgfedcba") == True
    assert candidate(s = "aguokepatgbnvfqmgmlcupuufxoohdfpgjdmysgvhmvffcnqxjjxqncffvmhvgsymdjgpfdhooxfuupucmlgqfvnbgtapekouga") == False
    assert candidate(s = "detartratedwithanotherdetartrated") == False
    assert candidate(s = "aabbccddeeffggahhigghhffeeddccbbaa") == False
    assert candidate(s = "zzazz") == True
    assert candidate(s = "rotorwithatinyrotor") == False
    assert candidate(s = "mississippi") == False
    assert candidate(s = "e race car e") == True
    assert candidate(s = "abcdefghihgfedcbaj") == True
    assert candidate(s = "ebcbbececabbacecbbcbe") == True
    assert candidate(s = "acbbba") == True
