# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abcba") == True
    assert candidate(s = "abcdef") == False
    assert candidate(s = "abcdedcba") == True
    assert candidate(s = "abcdba") == True
    assert candidate(s = "a") == True
    assert candidate(s = "abcdefghi") == False
    assert candidate(s = "abcabcabc") == False
    assert candidate(s = "ab") == True
    assert candidate(s = "aa") == True
    assert candidate(s = "abcde") == True
    assert candidate(s = "abcabc") == True
    assert candidate(s = "racecar") == True
    assert candidate(s = "abcdexdcba") == True
    assert candidate(s = "deeee") == True
    assert candidate(s = "abcxcba") == True
    assert candidate(s = "abcdefgh") == False
    assert candidate(s = "aabbcc") == True
    assert candidate(s = "aabbccdd") == False
    assert candidate(s = "abca") == True
    assert candidate(s = "abcdefg") == False
    assert candidate(s = "aabbccddeeeffgghhii") == False
    assert candidate(s = "abcdxyzyxwvutsrqponmlkjihgfedcba") == False
    assert candidate(s = "abacabadabacabadabacaba") == True
    assert candidate(s = "abac") == True
    assert candidate(s = "aabbaa") == True
    assert candidate(s = "abababababac") == False
    assert candidate(s = "zzzzyzzzz") == True
    assert candidate(s = "abcdefghijklmnopqrstuvwxzyxcba") == False
    assert candidate(s = "abcdexyzzyxedcba") == True
    assert candidate(s = "abcdexyzzyxdbca") == False
    assert candidate(s = "abcdefghijkllkjihgfe") == False
    assert candidate(s = "abcdefghjklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == False
    assert candidate(s = "abracadabra") == False
    assert candidate(s = "aabbccbaa") == True
    assert candidate(s = "abcdefxyzzyxabcdef") == False
    assert candidate(s = "") == True
    assert candidate(s = "racecarx") == False
    assert candidate(s = "abacaxbaxaba") == True
    assert candidate(s = "aaaabbbbcccc") == False
    assert candidate(s = "abcdabcdabcd") == False
    assert candidate(s = "racear") == True
    assert candidate(s = "abc") == True
    assert candidate(s = "abacabadabacabad") == False
    assert candidate(s = "abacabacaba") == True
    assert candidate(s = "aacaacaa") == True
    assert candidate(s = "aabbccddeee") == False
    assert candidate(s = "xyzzyx") == True
    assert candidate(s = "abacaba") == True
    assert candidate(s = "xyzzYx") == True
    assert candidate(s = "aabbaabbaa") == True
    assert candidate(s = "abaxyzyxab") == False
    assert candidate(s = "aabbccddeeeedccbbaa") == True
    assert candidate(s = "aabcaaba") == False
    assert candidate(s = "abcdxyz") == False
    assert candidate(s = "abacabadabacabadabacabadabacaba") == True
    assert candidate(s = "xyzzzzzyx") == True
    assert candidate(s = "abcdefzzzzzzfedcba") == True
    assert candidate(s = "abcdefghjihgfedcba") == True
    assert candidate(s = "abcdeffdcba") == True
    assert candidate(s = "abcdefghijkllkjihgfedcb") == False
    assert candidate(s = "abcda") == True
    assert candidate(s = "aabbccddeedccbbaa") == True
    assert candidate(s = "abcdeedcbaabcdeedcba") == True
    assert candidate(s = "abcdefghijkllkj") == False
    assert candidate(s = "abcdefghijkllk") == False
    assert candidate(s = "abcdeedcba") == True
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == True
    assert candidate(s = "noon") == True
    assert candidate(s = "abababababa") == True
    assert candidate(s = "abacabad") == False
    assert candidate(s = "aabbccddeeeeddcbaabbccdd") == False
    assert candidate(s = "abcaacb") == False
    assert candidate(s = "abababababababab") == False
    assert candidate(s = "abcdefghijjihgfeba") == False
    assert candidate(s = "abcd") == True
    assert candidate(s = "abcdefghijklmnop") == False
    assert candidate(s = "abcdeffedcba") == True
    assert candidate(s = "abcdefedcba") == True
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba") == True
    assert candidate(s = "level") == True
    assert candidate(s = "abacabadabacabac") == False
    assert candidate(s = "abcdefghiijihgfedcba") == True
    assert candidate(s = "racecarr") == False
    assert candidate(s = "abcdefghhgfedcba") == True
    assert candidate(s = "madam") == True
    assert candidate(s = "abcdefghijk") == False
    assert candidate(s = "aaaaaaaaaaa") == True
    assert candidate(s = "abcfedcba") == True
    assert candidate(s = "abcdexyz") == False
    assert candidate(s = "aabbccddccbaa") == True
    assert candidate(s = "abcdefghijkllkjihgfed") == False
    assert candidate(s = "abacabadabacaba") == True
    assert candidate(s = "abcdefgihgfedcba") == True
    assert candidate(s = "zzzzzzzzzzzzzzzzzzzz") == True
    assert candidate(s = "abcdefghijihgfedcba") == True
    assert candidate(s = "abaxab") == False
    assert candidate(s = "abcdefghijkll") == False
    assert candidate(s = "abcdabcd") == False
    assert candidate(s = "abba") == True
    assert candidate(s = "abcdexyzzyxzyxedcba") == True
    assert candidate(s = "abcdefghijkmlkjihgfedcba") == True
    assert candidate(s = "abcdexyzzyxdecba") == True
    assert candidate(s = "aabaaa") == True
    assert candidate(s = "aabbccddeeffgg") == False
    assert candidate(s = "detartrated") == True
    assert candidate(s = "abccba") == True
    assert candidate(s = "abbcbba") == True
    assert candidate(s = "abcdefghij") == False
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == False
    assert candidate(s = "aabbccddeeeeddccbaa") == False
    assert candidate(s = "aabbccddeedccbaa") == False
    assert candidate(s = "zyxwvutsrqponmlkjihgfedcba") == False
    assert candidate(s = "abcdefghgfedcba") == True
    assert candidate(s = "abcdefghijkllkjihg") == False
    assert candidate(s = "abccccba") == True
    assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == False
    assert candidate(s = "deified") == True
    assert candidate(s = "repaper") == True
    assert candidate(s = "abcdefghijkllkjihgf") == False
    assert candidate(s = "aabbaaabbaa") == True
    assert candidate(s = "abcdefghijkllkjihgfedcba") == True
    assert candidate(s = "abacdfgdcaba") == True
    assert candidate(s = "abcdefghijkllkjih") == False
    assert candidate(s = "ababababab") == False
    assert candidate(s = "abcdefabcdef") == False
    assert candidate(s = "abcddcba") == True
    assert candidate(s = "aaaaabaaa") == True
    assert candidate(s = "rotor") == True
    assert candidate(s = "abcdefghigfedcba") == True
    assert candidate(s = "abcdefghihgfedcba") == True
    assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == False
    assert candidate(s = "abcdefxzyxabcdef") == False
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnoopqrrsttuuuvvvvuuuuttsrrqponnmmoollkkjjiihhggeeffddccbbaa") == False
    assert candidate(s = "abcdefghijklmnopqponmlkjihgfedcba") == True
    assert candidate(s = "abcdefghijhgfedcba") == True
    assert candidate(s = "mississippi") == False
    assert candidate(s = "abaxxxxxxa") == True
    assert candidate(s = "abacaxaba") == True
    assert candidate(s = "abacax") == False
    assert candidate(s = "abcdexyzzyxdcba") == False
    assert candidate(s = "abacaxyzxyzxcaba") == False
