# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(word = "e") == 1
    assert candidate(word = "aeiou") == 35
    assert candidate(word = "abc") == 3
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(word = "aeiaaioaaaaeiiiiouuuooaauuaeiuiauuuuaeioaaaaeaiaioieoieiieoioioieouieiiaiaeiieoieouuiooaoaaiiaeiieeiooieiei") == 209934
    assert candidate(word = "bcbcbcbcbc") == 0
    assert candidate(word = "aeiaaioaaaaeiiiiouuuooaauuaeiu") == 4960
    assert candidate(word = "aeiaaioaaaaeiiiiouuuooaauuaeiuiaoiuuaeiuuaieiiaaaeeiuuoiuuuuuuu") == 43680
    assert candidate(word = "ltcd") == 0
    assert candidate(word = "aba") == 6
    assert candidate(word = "u") == 1
    assert candidate(word = "abcdefghijklmnopqrstuvwxyz") == 604
    assert candidate(word = "a") == 1
    assert candidate(word = "o") == 1
    assert candidate(word = "b") == 0
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(word = "i") == 1
    assert candidate(word = "") == 0
    assert candidate(word = "bbaaeekkeeaabbaaeekkeeaabbaaeekkeeaabb") == 6576
    assert candidate(word = "uvijqet") == 34
    assert candidate(word = "aieouaeiouaeiouaeiouaeiouaeiouaeiouaeiouaeiou") == 16215
    assert candidate(word = "uuygqijetbvrcw") == 150
    assert candidate(word = "mississippi") == 98
    assert candidate(word = "vowels") == 22
    assert candidate(word = "aeiouaeiouaeiou") == 680
    assert candidate(word = "abcdefghijabcdefghijabcdefghijabcdefghij") == 3412
    assert candidate(word = "cccccdcccc") == 0
    assert candidate(word = "aovnwqoeirqoweoirqoweoirquw") == 1949
    assert candidate(word = "congratulations") == 299
    assert candidate(word = "xyzaeiouxyzaeiouxyz") == 820
    assert candidate(word = "bcbcbcbcbcbcbcbcbcbc") == 0
    assert candidate(word = "vvvuuuooooiiiaaaaeeeee") == 1900
    assert candidate(word = "consonants") == 76
    assert candidate(word = "vowelvowelvowel") == 278
    assert candidate(word = "supercalifragilisticexpialidocious") == 3282
    assert candidate(word = "aquickbrownfoxjumpsoverthelazydog") == 2016
    assert candidate(word = "leetcode") == 58
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == 3860
    assert candidate(word = "sequence") == 62
    assert candidate(word = "aovvoaoaueuioeaueoaiouaoieaouioeaouioiea") == 11218
    assert candidate(word = "aeeee") == 35
    assert candidate(word = "aeioouaeiou") == 286
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(word = "bbbbbbbbbbbbbbbbbbbbbbba") == 24
    assert candidate(word = "hello") == 13
    assert candidate(word = "uoiea") == 35
    assert candidate(word = "bcdfghjklmnpqrstvwxyz") == 0
    assert candidate(word = "ffaaabbbccc") == 94
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(word = "aeiouaeiouaeiouaeiouaeiou") == 2925
    assert candidate(word = "qweoiauoieqweoiauoieqweoiauoie") == 4016
    assert candidate(word = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 4562
    assert candidate(word = "rhythms") == 0
    assert candidate(word = "bbbbbebbbb") == 30
    assert candidate(word = "aabbccddeeeffgg") == 221
    assert candidate(word = "beautiful") == 101
    assert candidate(word = "aeiouaeiouaeiouaeiouaeiouaeiou") == 4960
    assert candidate(word = "dddddeoeddd") == 103
    assert candidate(word = "aeiouaeiouaeiouaeiou") == 1540
    assert candidate(word = "vowel") == 16
    assert candidate(word = "xylophone") == 54
    assert candidate(word = "repetitiveeeee") == 350
    assert candidate(word = "repetition") == 118
    assert candidate(word = "characters") == 78
    assert candidate(word = "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu") == 13244
    assert candidate(word = "uvaeiouz") == 98
    assert candidate(word = "aovylqjwhepfuciphg") == 280
    assert candidate(word = "uoieaoueioauoiea") == 816
    assert candidate(word = "zzzzzzzzzzz") == 0
    assert candidate(word = "eeeeeaeeee") == 220
    assert candidate(word = "aaaaabaaaaa") == 250
    assert candidate(word = "abacaxabayabac") == 280
    assert candidate(word = "aeiouaeiou") == 220
    assert candidate(word = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == 0
    assert candidate(word = "programming") == 90
    assert candidate(word = "aeiaoeiaoeiaoeiaoeiaoeiaoeiaoeiaoeiaoei") == 10660
    assert candidate(word = "ouqofyrcjgz") == 63
    assert candidate(word = "aeiaeaieaa") == 220
    assert candidate(word = "vowelsarefun") == 158
    assert candidate(word = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == 4718
