# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(numBottles = 10,numExchange = 3) == 13
    assert candidate(numBottles = 2,numExchange = 3) == 2
    assert candidate(numBottles = 13,numExchange = 6) == 15
    assert candidate(numBottles = 100,numExchange = 1) == 114
    assert candidate(numBottles = 5,numExchange = 5) == 6
    assert candidate(numBottles = 1,numExchange = 1) == 2
    assert candidate(numBottles = 20,numExchange = 4) == 24
    assert candidate(numBottles = 50,numExchange = 10) == 54
    assert candidate(numBottles = 1,numExchange = 100) == 1
    assert candidate(numBottles = 1,numExchange = 10) == 1
    assert candidate(numBottles = 99,numExchange = 2) == 112
    assert candidate(numBottles = 70,numExchange = 6) == 78
    assert candidate(numBottles = 60,numExchange = 2) == 70
    assert candidate(numBottles = 45,numExchange = 20) == 47
    assert candidate(numBottles = 60,numExchange = 8) == 66
    assert candidate(numBottles = 90,numExchange = 9) == 97
    assert candidate(numBottles = 80,numExchange = 8) == 87
    assert candidate(numBottles = 90,numExchange = 18) == 94
    assert candidate(numBottles = 75,numExchange = 15) == 79
    assert candidate(numBottles = 40,numExchange = 50) == 40
    assert candidate(numBottles = 30,numExchange = 2) == 37
    assert candidate(numBottles = 90,numExchange = 5) == 100
    assert candidate(numBottles = 55,numExchange = 8) == 60
    assert candidate(numBottles = 15,numExchange = 15) == 16
    assert candidate(numBottles = 40,numExchange = 7) == 44
    assert candidate(numBottles = 55,numExchange = 6) == 61
    assert candidate(numBottles = 80,numExchange = 3) == 91
    assert candidate(numBottles = 60,numExchange = 15) == 63
    assert candidate(numBottles = 60,numExchange = 7) == 66
    assert candidate(numBottles = 30,numExchange = 5) == 34
    assert candidate(numBottles = 80,numExchange = 10) == 86
    assert candidate(numBottles = 80,numExchange = 20) == 83
    assert candidate(numBottles = 95,numExchange = 5) == 105
    assert candidate(numBottles = 40,numExchange = 12) == 43
    assert candidate(numBottles = 40,numExchange = 25) == 41
    assert candidate(numBottles = 50,numExchange = 5) == 57
    assert candidate(numBottles = 85,numExchange = 4) == 95
    assert candidate(numBottles = 45,numExchange = 12) == 48
    assert candidate(numBottles = 25,numExchange = 3) == 30
    assert candidate(numBottles = 80,numExchange = 5) == 89
    assert candidate(numBottles = 45,numExchange = 6) == 50
    assert candidate(numBottles = 30,numExchange = 7) == 33
    assert candidate(numBottles = 7,numExchange = 8) == 7
    assert candidate(numBottles = 70,numExchange = 8) == 76
    assert candidate(numBottles = 75,numExchange = 5) == 84
    assert candidate(numBottles = 75,numExchange = 7) == 82
    assert candidate(numBottles = 85,numExchange = 5) == 94
    assert candidate(numBottles = 45,numExchange = 10) == 49
    assert candidate(numBottles = 30,numExchange = 30) == 31
    assert candidate(numBottles = 90,numExchange = 4) == 101
    assert candidate(numBottles = 40,numExchange = 30) == 41
    assert candidate(numBottles = 75,numExchange = 10) == 81
    assert candidate(numBottles = 100,numExchange = 2) == 113
    assert candidate(numBottles = 35,numExchange = 18) == 36
    assert candidate(numBottles = 55,numExchange = 12) == 59
    assert candidate(numBottles = 100,numExchange = 50) == 102
    assert candidate(numBottles = 8,numExchange = 4) == 10
    assert candidate(numBottles = 80,numExchange = 15) == 84
    assert candidate(numBottles = 60,numExchange = 20) == 62
    assert candidate(numBottles = 99,numExchange = 3) == 111
    assert candidate(numBottles = 99,numExchange = 20) == 103
    assert candidate(numBottles = 100,numExchange = 20) == 104
    assert candidate(numBottles = 3,numExchange = 3) == 4
    assert candidate(numBottles = 50,numExchange = 1) == 60
    assert candidate(numBottles = 70,numExchange = 25) == 72
    assert candidate(numBottles = 6,numExchange = 6) == 7
    assert candidate(numBottles = 65,numExchange = 12) == 69
    assert candidate(numBottles = 55,numExchange = 20) == 57
    assert candidate(numBottles = 25,numExchange = 2) == 31
    assert candidate(numBottles = 95,numExchange = 7) == 104
    assert candidate(numBottles = 45,numExchange = 2) == 53
    assert candidate(numBottles = 90,numExchange = 25) == 93
    assert candidate(numBottles = 95,numExchange = 15) == 100
    assert candidate(numBottles = 45,numExchange = 4) == 52
    assert candidate(numBottles = 99,numExchange = 9) == 107
    assert candidate(numBottles = 25,numExchange = 7) == 28
    assert candidate(numBottles = 30,numExchange = 3) == 36
    assert candidate(numBottles = 5,numExchange = 2) == 7
    assert candidate(numBottles = 60,numExchange = 3) == 69
    assert candidate(numBottles = 45,numExchange = 3) == 53
    assert candidate(numBottles = 25,numExchange = 9) == 27
    assert candidate(numBottles = 90,numExchange = 6) == 99
    assert candidate(numBottles = 90,numExchange = 10) == 97
    assert candidate(numBottles = 70,numExchange = 7) == 77
    assert candidate(numBottles = 90,numExchange = 15) == 95
    assert candidate(numBottles = 50,numExchange = 2) == 59
