# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(s = "abcde",p = "ab*e") == True
    assert candidate(s = "abcde",p = "*") == True
    assert candidate(s = "mississippi",p = "m??*ss*?i*pi") == False
    assert candidate(s = "aa",p = "a") == False
    assert candidate(s = "abcde",p = "?bcde") == True
    assert candidate(s = "abcde",p = "a*b*e") == True
    assert candidate(s = "cb",p = "?a") == False
    assert candidate(s = "abcabczzzde",p = "*abc***de*") == True
    assert candidate(s = "abcde",p = "abc?de") == False
    assert candidate(s = "",p = "") == True
    assert candidate(s = "abcde",p = "b*c*d*e*") == False
    assert candidate(s = "abcde",p = "a?c*e") == True
    assert candidate(s = "abefcdgiescdfimde",p = "*a*b*ef*cd*ei*de*") == False
    assert candidate(s = "abcde",p = "*****e") == True
    assert candidate(s = "aa",p = "*") == True
    assert candidate(s = "abcde",p = "a*de") == True
    assert candidate(s = "adceb",p = "*a*b") == True
    assert candidate(s = "abcde",p = "*****") == True
    assert candidate(s = "abcde",p = "a*****") == True
    assert candidate(s = "acdcb",p = "a*c?b") == False
    assert candidate(s = "a",p = "?") == True
    assert candidate(s = "mississippi",p = "m*iss*iss*pp*i*pi") == False
    assert candidate(s = "abcde",p = "a?c?e") == True
    assert candidate(s = "abcde",p = "a*e?") == False
    assert candidate(s = "abcde",p = "a*b?e") == False
    assert candidate(s = "abcde",p = "*b*c*d*e*") == True
    assert candidate(s = "abcde",p = "a*e") == True
    assert candidate(s = "abcde",p = "*a*bc*e*") == True
    assert candidate(s = "abcde",p = "*b*c*d*e") == True
    assert candidate(s = "abcde",p = "a*b*c*d*e*f") == False
    assert candidate(s = "abefcdgiescdfimde",p = "ab*ef*cd*ei*de") == False
    assert candidate(s = "abcde",p = "abc*def") == False
    assert candidate(s = "abcde",p = "*bcde") == True
    assert candidate(s = "abcde",p = "abcd*") == True
    assert candidate(s = "hoop",p = "hoop*") == True
    assert candidate(s = "mississippi",p = "m??*ss*?si*pp*") == False
    assert candidate(s = "aaaa",p = "***a") == True
    assert candidate(s = "abcde",p = "abc??") == True
    assert candidate(s = "abcde",p = "a*b*c*d*e*") == True
    assert candidate(s = "bba",p = "?*a**") == True
    assert candidate(s = "abcde",p = "a*b*c*d*e?") == False
    assert candidate(s = "",p = "*") == True
    assert candidate(s = "abcde",p = "abcd?") == True
    assert candidate(s = "abcde",p = "*a*b*c*d*e*f") == False
    assert candidate(s = "a",p = "*") == True
    assert candidate(s = "",p = "?") == False
    assert candidate(s = "abcde",p = "abc*e") == True
    assert candidate(s = "abcde",p = "*a*b*c*d*e*") == True
    assert candidate(s = "abefcdgiescdfimde",p = "ab*ef*cd*de") == True
    assert candidate(s = "abefcdgiescdfimde",p = "ab*cd?i*de") == True
    assert candidate(s = "abcde",p = "a*b*c*d*e") == True
    assert candidate(s = "abcde",p = "abcde") == True
    assert candidate(s = "aaaaa",p = "a*a*a*a*a") == True
    assert candidate(s = "abcdef",p = "a*b*c*d*e*f") == True
    assert candidate(s = "abcd",p = "a*d") == True
    assert candidate(s = "xyxzyxytxzyxy",p = "x*y*z*x*y*z*x*y*z") == False
    assert candidate(s = "xyxxyxyxyx",p = "x*yx*yx*yx*yx") == True
    assert candidate(s = "abcxyz",p = "*xyz") == True
    assert candidate(s = "abcabcabc",p = "a*bc*a*bc*a*bc*") == True
    assert candidate(s = "abcdefghij",p = "a*c*e*g*i*j") == True
    assert candidate(s = "abcdefghij",p = "a*bc*de*fgh*i*j") == True
    assert candidate(s = "ababababab",p = "a*b*a*b*a*b*") == True
    assert candidate(s = "xyz",p = "*x*y*z*") == True
    assert candidate(s = "zxyxzy",p = "z*xy*z*") == True
    assert candidate(s = "hellohellohello",p = "he*lo*he*lo*") == True
    assert candidate(s = "xyz",p = "*z") == True
    assert candidate(s = "xyxzyzyx",p = "x*y*x*y*x") == True
    assert candidate(s = "ababababa",p = "a*b*a*b*a") == True
    assert candidate(s = "abcdefghij",p = "a*?*c*?*e*?*g*?*i*?*j") == False
    assert candidate(s = "abefcdgiescdfimdeeeiad",p = "ab*cd?i*de") == False
    assert candidate(s = "ababababab",p = "a*b*a*b*a*b*a*b*a*b") == True
    assert candidate(s = "aabbccdd",p = "aab?cc?d*") == True
    assert candidate(s = "abc",p = "*?*?*") == True
    assert candidate(s = "abcdefghij",p = "?????????") == False
    assert candidate(s = "abcabcabc",p = "abc*abc*abc*") == True
    assert candidate(s = "abcdefghij",p = "*b*d*f*h*") == True
    assert candidate(s = "xyzxyzxyz",p = "xyz*xyz*xyz") == True
    assert candidate(s = "aaaaaa",p = "?*?*?*?*?*") == True
    assert candidate(s = "abcd",p = "?b*d") == True
    assert candidate(s = "xxyyzz",p = "x*y*z") == True
    assert candidate(s = "abcabcabcabcabcabc",p = "abcabc*abcabc*") == True
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j?") == False
    assert candidate(s = "abcdabcd",p = "ab*cd*ab*cd*") == True
    assert candidate(s = "mississippi",p = "m??*ss*?") == True
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j?*k*?*l*?") == False
    assert candidate(s = "abababab",p = "a?b?*b?") == False
    assert candidate(s = "mississippi",p = "m*is*p*i*") == True
    assert candidate(s = "abcdefghij",p = "a*d*f?j") == False
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j?*k*?*l*") == False
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",p = "a*b*c*d*e*f*g*h*i*j*k*l*m*n*o*p*q*r*s*t*u*v*w*x*y*z*z*") == True
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j*?*?*") == False
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j*") == True
    assert candidate(s = "abcdabcdabcd",p = "*a*b*c*d*a*b*c*d*a*b*c*d*") == True
    assert candidate(s = "abcabcabc",p = "abc*abc*") == True
    assert candidate(s = "patternmatching",p = "pa*?t*?n*?m*?a*?t*?c*?h*?i*?n*?g") == False
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j*?*") == False
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j*k*?") == False
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j*k?*") == False
    assert candidate(s = "abcabcabc",p = "*abc*abc*abc*") == True
    assert candidate(s = "abcdabcdabcd",p = "a*d*d*bc*bc*bc") == False
    assert candidate(s = "abcabcabc",p = "a*bc*bc*") == True
    assert candidate(s = "abcdefghij",p = "*a*b*c*d*e*f*g*h*i*j*?*") == False
    assert candidate(s = "abcdefghij",p = "*?*?*?*?*?*?*?*?") == True
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j?*k*?*") == False
    assert candidate(s = "abcdefg",p = "a*d?e?*g") == False
    assert candidate(s = "abcdefg",p = "abc*def*ghi") == False
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j?*k*?") == False
    assert candidate(s = "abcdefg",p = "a?c*f?g") == False
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j????") == False
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j*a*") == False
    assert candidate(s = "mississippi",p = "m??*ss*?i*") == True
    assert candidate(s = "abcabcabc",p = "a*b*c*a*b*c*a*b*c") == True
    assert candidate(s = "aaaaabbbbbcccc",p = "a*b*c*") == True
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j?*k*?*l") == False
    assert candidate(s = "aabbccddeeff",p = "a*b*c*d*e*f*") == True
    assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",p = "a*b*c*d*e*f*g*h*i*j*k*l*m*n*o*p*q*r*s*t*u*v*w*x*y*z*z*z*") == False
    assert candidate(s = "abcde",p = "a*bcd*e") == True
    assert candidate(s = "abcdefghij",p = "*a*b*c*d*e*f*g*h*i*j*k") == False
    assert candidate(s = "abcde",p = "a*?c*e") == True
    assert candidate(s = "mississippi",p = "m??*ss*ip*") == True
    assert candidate(s = "xyzxyzxyz",p = "*xyzxyzxyz") == True
    assert candidate(s = "hello",p = "h?ll*") == True
    assert candidate(s = "abcdexyz",p = "*d*xyz") == True
    assert candidate(s = "aaaaabbbbb",p = "a*b*") == True
    assert candidate(s = "hello",p = "he*o") == True
    assert candidate(s = "abcdabcd",p = "a*b*c*d*") == True
    assert candidate(s = "abcdefg",p = "a?c*e?g") == True
    assert candidate(s = "abxyzz",p = "ab*zz") == True
    assert candidate(s = "xyzabc",p = "*abc") == True
    assert candidate(s = "abcabcabc",p = "a*?*?*b*c*") == True
    assert candidate(s = "xyzzxyzzxyzz",p = "*z*z*z") == True
    assert candidate(s = "abcxyz",p = "abc*xyz") == True
    assert candidate(s = "abcdefghij",p = "*a????b????c????d????e????f????g????h????i????j*") == False
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j*k*") == False
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j?*k") == False
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j?*k?") == False
    assert candidate(s = "zazbzczdz",p = "z*a*z*b*z*c*z*d*z") == True
    assert candidate(s = "abcdefghij",p = "*a*b*c*d*e*f*g*h*i*j*") == True
    assert candidate(s = "abcdefghij",p = "*a*b*c*d*e*f*g*h*i*j") == True
    assert candidate(s = "mississippi",p = "mi*is*ip*pi") == True
    assert candidate(s = "aaaaaa",p = "a?a?a?a?a?a") == False
    assert candidate(s = "abcdefghij",p = "*a*b*c*d*e*f*g*h*i*j*k*?") == False
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j*k") == False
    assert candidate(s = "xyzzaz",p = "*x?z*a*") == True
    assert candidate(s = "abcde",p = "*abc?e") == True
    assert candidate(s = "abcdabcd",p = "a*a*a*a*") == False
    assert candidate(s = "abc",p = "a*c") == True
    assert candidate(s = "xyz",p = "?yz*") == True
    assert candidate(s = "hello_world",p = "he*o?wo*rld") == True
    assert candidate(s = "abcdefg",p = "a*c*e*g") == True
    assert candidate(s = "abcdefghij",p = "a*d*g*j") == True
    assert candidate(s = "abcdexyz",p = "a*?d*x*yz") == True
    assert candidate(s = "aabbccddeeffgg",p = "*b*c*d*e*f*g*") == True
    assert candidate(s = "abcdefghij",p = "a*b*e*i*") == True
    assert candidate(s = "xyxxyxyxyx",p = "x*y*x*y*x*y*x") == True
    assert candidate(s = "abcd",p = "*d") == True
    assert candidate(s = "abcdexyz",p = "abcd*xyz") == True
    assert candidate(s = "mississippi",p = "m*iss*ss*ip*") == True
    assert candidate(s = "mississippi",p = "m??*iss*ippi") == True
    assert candidate(s = "abcdefghij",p = "*b*d*f*h*j") == True
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j") == True
    assert candidate(s = "abc",p = "***") == True
    assert candidate(s = "aabbccdd",p = "a*bb*cc*dd") == True
    assert candidate(s = "abcdefghij",p = "*") == True
    assert candidate(s = "abcde",p = "*abcde") == True
    assert candidate(s = "aaabbbccc",p = "a*bbb*c*") == True
    assert candidate(s = "abcde",p = "abcde*") == True
    assert candidate(s = "xyzabc",p = "x*y?*") == True
    assert candidate(s = "aabbaabb",p = "a*bb*a*bb") == True
    assert candidate(s = "abcdedef",p = "ab*?de*?") == True
    assert candidate(s = "pattern_matching",p = "p*a*t*t*e*r_*m*a*t*c*h*i*n*g") == False
    assert candidate(s = "worldwide",p = "wo*d*i*e") == True
    assert candidate(s = "aabbcc",p = "a*bb*c*") == True
    assert candidate(s = "abcdefg",p = "*cde*fg") == True
    assert candidate(s = "aabbcc",p = "a*b*c*") == True
    assert candidate(s = "xyyxxyyxxyy",p = "x*y*x*y*x*y*") == True
    assert candidate(s = "abcabcabc",p = "abc*abc*abc") == True
    assert candidate(s = "aabbababab",p = "a*b*a*") == True
    assert candidate(s = "abcdexyz",p = "a*b?c*?d*x?y*z*") == False
    assert candidate(s = "abcdefgh",p = "a*gh") == True
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j*?*k*") == False
    assert candidate(s = "zzzzzzzzzz",p = "z*z*z*z*z*z*z*z*z*z") == True
    assert candidate(s = "abcabcabcabc",p = "a*b*c*a*b*c*a*b*c") == True
    assert candidate(s = "abcdefghij",p = "a*d*f*h*j") == True
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j*?") == False
    assert candidate(s = "abcdefghij",p = "a*b*c*d*e*f*g*h*i*j*?*?") == False
    assert candidate(s = "abcdefghij",p = "????a*b*c*d*e*f*g*h*i*j") == False
    assert candidate(s = "ababab",p = "a*b*a*b*") == True
    assert candidate(s = "abcabcabc",p = "abc*a*bc*a*bc*") == True
    assert candidate(s = "abcdefghij",p = "*a*b*c*d*e*f*g*h*i*j*j*") == False
    assert candidate(s = "abcabcabcabc",p = "abc*abc*") == True
    assert candidate(s = "abcdefghij",p = "*ef*gh*ij") == True
    assert candidate(s = "aabbccddeeff",p = "a*bb*c*dd*ee*f*") == True
    assert candidate(s = "abcdefghij",p = "a*d*f*h*j*") == True
    assert candidate(s = "abcdef",p = "*?*?*?*") == True
    assert candidate(s = "abcabcabc",p = "abcabcabc") == True
    assert candidate(s = "abcd",p = "*?c*d*") == True
    assert candidate(s = "abcdefghij",p = "a*d?g*j") == False
    assert candidate(s = "abcabcabc",p = "*b*a*b*c*a*b*c*") == True
    assert candidate(s = "mississippi",p = "m??*ss*?si*pp*i*") == False
    assert candidate(s = "aabb",p = "*b") == True
    assert candidate(s = "abcabcabcabc",p = "*abcabc*") == True
    assert candidate(s = "examplepattern",p = "e*ample?attern") == True
    assert candidate(s = "nested_matching",p = "n*es*t*e*d_*m*a*t*c*h*i*n*g") == True
    assert candidate(s = "abcabcabc",p = "*a*b*c*a*b*c*a*b*c*") == True
    assert candidate(s = "teststring",p = "t*st*ng") == True
    assert candidate(s = "aabbcc",p = "a*a*a*c*c*") == False
    assert candidate(s = "abcdef",p = "*abc?ef") == True
    assert candidate(s = "aaaabaaaab",p = "a*a*ba*a*b") == True
