# Import the utils module for prompts
from utils import *

def check(candidate):
    assert candidate(pattern = "ab",s = "dogdog") == True
    assert candidate(pattern = "aaaa",s = "catcatcatcat") == True
    assert candidate(pattern = "aabb",s = "xyzabcxzyabc") == False
    assert candidate(pattern = "abcd",s = "oneonetwothree") == True
    assert candidate(pattern = "ab",s = "aa") == False
    assert candidate(pattern = "abc",s = "bagg") == True
    assert candidate(pattern = "abba",s = "dogcatcatdog") == True
    assert candidate(pattern = "ab",s = "catdog") == True
    assert candidate(pattern = "abab",s = "redblueredblue") == True
    assert candidate(pattern = "abc",s = "bentleybentleybentley") == True
    assert candidate(pattern = "ab",s = "ba") == True
    assert candidate(pattern = "abba",s = "dogdogdogdog") == False
    assert candidate(pattern = "abc",s = "bent") == True
    assert candidate(pattern = "aaaa",s = "catcatcat") == False
    assert candidate(pattern = "abc",s = "dogcat") == True
    assert candidate(pattern = "abc",s = "dog") == True
    assert candidate(pattern = "a",s = "dog") == True
    assert candidate(pattern = "abcd",s = "dogcatmousefish") == True
    assert candidate(pattern = "ab",s = "ab") == True
    assert candidate(pattern = "abc",s = "dogcatsdog") == True
    assert candidate(pattern = "aa",s = "dogdog") == True
    assert candidate(pattern = "abcabc",s = "xyzxyzxyzxyzxyzxyz") == True
    assert candidate(pattern = "aaaa",s = "aaaa") == True
    assert candidate(pattern = "abab",s = "dogcatcatfish") == False
    assert candidate(pattern = "aaaa",s = "asdasdasdasd") == True
    assert candidate(pattern = "abc",s = "dogcats") == True
    assert candidate(pattern = "abc",s = "bcb") == False
    assert candidate(pattern = "ab",s = "dogcat") == True
    assert candidate(pattern = "abba",s = "dogcatcatfish") == False
    assert candidate(pattern = "ab",s = "catcat") == True
    assert candidate(pattern = "ab",s = "dog") == True
    assert candidate(pattern = "aabbccdd",s = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyz") == False
    assert candidate(pattern = "abcabcabc",s = "xyzxyzxyzxyzxyzxyzxyzxyzxyz") == True
    assert candidate(pattern = "aabbcc",s = "abcabcabc") == False
    assert candidate(pattern = "abac",s = "xyzxyzuvwxyz") == True
    assert candidate(pattern = "aabbcc",s = "mnopqrstuvwxmnopqrstuvwx") == False
    assert candidate(pattern = "aaaabc",s = "catcatcatdog") == False
    assert candidate(pattern = "aba",s = "catdogcat") == True
    assert candidate(pattern = "abb",s = "catdogdog") == True
    assert candidate(pattern = "aabbcc",s = "zzzxxxyyyxxxzzzyyy") == False
    assert candidate(pattern = "abac",s = "xyzzyzyxzyxzyx") == True
    assert candidate(pattern = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",s = "xyzxyzxyzxyzabcdabcdabcdabcdabcdefghabcdefghabcdefghabcdefghabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == False
    assert candidate(pattern = "aabbcc",s = "oneonetwoonetwothree") == False
    assert candidate(pattern = "aabbcc",s = "catdogcowcatdogcow") == False
    assert candidate(pattern = "abc",s = "hellohellosai") == True
    assert candidate(pattern = "aabb",s = "ababcababc") == False
    assert candidate(pattern = "abababa",s = "redblueredblueredblueredblue") == False
    assert candidate(pattern = "abcb",s = "redbluegreenblue") == True
    assert candidate(pattern = "abcdabcd",s = "dogcatmousefishdogcatmousefish") == True
    assert candidate(pattern = "aab",s = "dogdogcat") == True
    assert candidate(pattern = "abcabcabcabc",s = "onetwothreeonetwothreeonetwothreeonetwothree") == True
    assert candidate(pattern = "abcabcabcabcabcabcabcabcabcabc",s = "abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh") == True
    assert candidate(pattern = "abca",s = "dogcatdogmouse") == False
    assert candidate(pattern = "abcdef",s = "abcdef") == True
    assert candidate(pattern = "abcd",s = "dogcatfishbird") == True
    assert candidate(pattern = "ababa",s = "dogcatdogcatdog") == True
    assert candidate(pattern = "abab",s = "catdogcatdog") == True
    assert candidate(pattern = "aaaa",s = "dogdogdog") == False
    assert candidate(pattern = "aabbccddeeff",s = "abcdefabcdefabcdef") == False
    assert candidate(pattern = "abcabcabcabc",s = "abcdabcdabcdabcd") == True
    assert candidate(pattern = "aabbaa",s = "catcatdogdogcatcat") == True
    assert candidate(pattern = "xyzyx",s = "abcdefedcbafedcbaf") == False
    assert candidate(pattern = "abcb",s = "dogcatbirdcat") == True
    assert candidate(pattern = "abcabcabcabcabcabcabcabc",s = "abcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdef") == False
    assert candidate(pattern = "abcdabcd",s = "abcdabcdabcdabcd") == True
    assert candidate(pattern = "abab",s = "redredblueblue") == False
    assert candidate(pattern = "abacaba",s = "xyzuvwxyzuwvxzyzx") == False
    assert candidate(pattern = "abcabcabcabc",s = "xyzxyzxyzxyzxyzxyzxyzxyz") == True
    assert candidate(pattern = "abcabcabcabc",s = "dogcatmousedogcatmousedogcatmouse") == False
    assert candidate(pattern = "aabbaabb",s = "xyzxyzababxyzxyzabab") == True
    assert candidate(pattern = "abcabcabc",s = "xyzxyzxyzz") == False
    assert candidate(pattern = "abccba",s = "dogcatcatdog") == False
    assert candidate(pattern = "aabbba",s = "catdogdogdogcat") == False
    assert candidate(pattern = "abcabcabcabc",s = "abcdefghabcdefghabcdefghabcdefgh") == True
    assert candidate(pattern = "aaaa",s = "aabbccdd") == False
    assert candidate(pattern = "aabbcc",s = "abcdabcdabcd") == False
    assert candidate(pattern = "abababababababab",s = "redblueredblueredblueredblueredblueredblueredblue") == False
    assert candidate(pattern = "aabbaabb",s = "redblueredblueredblue") == False
    assert candidate(pattern = "abababcabc",s = "redblueredbluecatdogcatdog") == False
    assert candidate(pattern = "aabbcc",s = "xyzxyzxyzxyzxyzxyz") == False
    assert candidate(pattern = "abcdabcd",s = "onetwothreefouronetwothreefour") == True
    assert candidate(pattern = "abcabc",s = "xyzxyzzxyz") == False
    assert candidate(pattern = "aabbcc",s = "xyzxyzxyzxyzzzz") == False
    assert candidate(pattern = "abcb",s = "dogcatcatfish") == False
    assert candidate(pattern = "abcabcabc",s = "redblueredbluegreenredblueredbluegreen") == False
    assert candidate(pattern = "ababab",s = "redbluegreenredbluegreen") == False
    assert candidate(pattern = "abcabcabc",s = "xyzxyzxyzxyz") == False
    assert candidate(pattern = "aabbccddeeff",s = "xyxymxyzmxyxm") == False
    assert candidate(pattern = "abcabcabc",s = "onetwothreeonetwothreeonetwothree") == True
    assert candidate(pattern = "aabbccddeeff",s = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij") == False
    assert candidate(pattern = "abcd",s = "oneonetwothreefour") == True
    assert candidate(pattern = "abababab",s = "redblueredblueredblueredblue") == True
    assert candidate(pattern = "ab",s = "xyxyxyxyxy") == True
    assert candidate(pattern = "abababab",s = "catdogcatdogcatdogcatdog") == True
    assert candidate(pattern = "abab",s = "onefouronetwo") == False
    assert candidate(pattern = "abcabc",s = "abcabcabcabcabcabc") == True
    assert candidate(pattern = "abacabac",s = "onetwothreeonetwothreeonetwothreeonetwothree") == True
    assert candidate(pattern = "abab",s = "xyxyzyzy") == False
    assert candidate(pattern = "aabbaa",s = "oneonetwoonetwooneone") == False
    assert candidate(pattern = "abcdef",s = "abcdefabcdefabcdef") == True
    assert candidate(pattern = "abac",s = "applebananapplecat") == True
    assert candidate(pattern = "aabb",s = "xyzxyzabab") == True
    assert candidate(pattern = "aab",s = "hellohellohai") == True
    assert candidate(pattern = "abc",s = "aabb") == True
    assert candidate(pattern = "abcabc",s = "abcdefgabcdefg") == True
    assert candidate(pattern = "aabbccddeeffgghh",s = "xyzxyzxyzxyzabcdabcdabcdabcd") == False
    assert candidate(pattern = "abcabcabcabc",s = "aaaabbbbccccdddd") == False
    assert candidate(pattern = "abcabc",s = "xyzxyzxyzxyz") == True
    assert candidate(pattern = "abba",s = "aabb") == False
    assert candidate(pattern = "aabbcc",s = "mnopqrmnopqrmnopqr") == False
    assert candidate(pattern = "abab",s = "redbluebluered") == False
    assert candidate(pattern = "aabb",s = "xyzxyzxyzxyz") == False
    assert candidate(pattern = "ababab",s = "dogcatdogcatdogcat") == True
    assert candidate(pattern = "ababac",s = "redblueredbluegreen") == False
    assert candidate(pattern = "abab",s = "xyzxyxzyzx") == False
    assert candidate(pattern = "ababab",s = "helloworldhelloworldhelloworld") == True
    assert candidate(pattern = "abab",s = "aabb") == False
    assert candidate(pattern = "abcabcabc",s = "xyzxyzxyzxyzxyzxyz") == True
    assert candidate(pattern = "abccba",s = "dogcatbirdbirdcatdog") == True
    assert candidate(pattern = "abababa",s = "xyzxyzxyzxyzxyzxyzxyz") == False
    assert candidate(pattern = "abcabc",s = "dogcatdogcatdogcat") == False
    assert candidate(pattern = "abc",s = "dogcatmouse") == True
    assert candidate(pattern = "abababab",s = "redblueredbluegreenredblueredblue") == False
    assert candidate(pattern = "abcdabcd",s = "dogcatfishbirddogcatfishbird") == True
    assert candidate(pattern = "aabbccddeeffgghhiijjkkll",s = "xyzxyzxyzxyzabcdabcdabcdabcdabcdefghabcdefghabcdefghabcdefgh") == False
    assert candidate(pattern = "abcdefghij",s = "abcdefghijabcdefghijabcdefghijabcdefghij") == True
    assert candidate(pattern = "abacaba",s = "xyzwxyzxyzwxyz") == False
    assert candidate(pattern = "ababab",s = "redblueredblue") == False
    assert candidate(pattern = "aabbccddeeff",s = "onetwothreefourfivesixonetwothreefourfivesix") == False
    assert candidate(pattern = "abababababab",s = "redblueredblueredblueredblueredblue") == False
    assert candidate(pattern = "abab",s = "xyzxyzyxzyxzyx") == False
    assert candidate(pattern = "abacaba",s = "dogcatdogcatdogcatdog") == False
    assert candidate(pattern = "abcd",s = "wxyz") == True
    assert candidate(pattern = "mnopqr",s = "lorepsumdolors") == True
    assert candidate(pattern = "abcbca",s = "redblueredgreenblueredgreen") == False
    assert candidate(pattern = "aabbccddeeffgg",s = "oneonetwoonetwothreethreefourfourfivefivesixsixsevenseven") == False
    assert candidate(pattern = "abcabc",s = "abcdefabcdef") == True
    assert candidate(pattern = "abac",s = "redbluered") == True
    assert candidate(pattern = "abac",s = "dogcatdogcat") == False
    assert candidate(pattern = "abcde",s = "aabbccdde") == True
    assert candidate(pattern = "abcde",s = "applebananacherrydateme") == True
    assert candidate(pattern = "abcde",s = "quickbrownfoxjumps") == True
    assert candidate(pattern = "aabbccdd",s = "xyzxyzxyzxyzyzxzyz") == False
    assert candidate(pattern = "ababab",s = "redblueredblueredblue") == True
    assert candidate(pattern = "ababab",s = "onetwoonetwoonetwo") == True
    assert candidate(pattern = "abcabcabcabc",s = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyz") == False
    assert candidate(pattern = "abac",s = "dogcatdogmouse") == True
    assert candidate(pattern = "abcabcabc",s = "abcabcabcabcabcabcabc") == False
    assert candidate(pattern = "abcdef",s = "abcdefabcdefabcdefabcdefabcdefabcdef") == True
    assert candidate(pattern = "abcde",s = "fghij") == True
