import json
import os

from a2a.types import AgentCapabilities, AgentCard, AgentSkill


def get_agent_url() -> str:
    """Get the agent URL from environment or use localhost fallback."""
    cloudrun_host = os.getenv("CLOUDRUN_HOST")
    if cloudrun_host:
        https_enabled = os.getenv("HTTPS_ENABLED", "true").lower() == "true"
        protocol = "https" if https_enabled else "http"
        return f"{protocol}://{cloudrun_host}/"
    return "http://localhost:9999/"


# Skills below are visible to the white agents
register_skill = AgentSkill(
    id="register",
    name="Register",
    description="Register the white agent with the green agent",
    tags=["green agent", "register"],
    examples=[json.dumps({"skill": "register", "name": "<your agent name>"})],
)

distribute_problem_skill = AgentSkill(
    id="distribute_problem",
    name="Distribute Problem",
    description="Distribute a new coding problem to the white agent",
    tags=["green agent", "distribute problem"],
    examples=[
        json.dumps(
            {
                "skill": "distribute_problem",
                "id": "<your assigned ID>",
                "name": "<your agent name>",
            }
        )
    ],
)

process_answer_skill = AgentSkill(
    id="process_answer",
    name="Process Answer",
    description="Process the answer from the white agent",
    tags=["green agent", "process answer"],
    examples=[
        json.dumps(
            {
                "skill": "process_answer",
                "id": "<your assigned ID>",
                "name": "<your agent name>",
                "solution": "<your generated code>",
            }
        )
    ],
)

# Public agent card
agent_card = AgentCard(
    name="Coding Evaluation Agent",
    description="The eval agent that evaluates code generated by white agents",
    url=get_agent_url(),
    version="1.0.0",
    default_input_modes=["text"],
    default_output_modes=["text"],
    capabilities=AgentCapabilities(streaming=False),
    skills=[
        register_skill,
        distribute_problem_skill,
        process_answer_skill,
    ],
    supports_authenticated_extended_card=True,
)

# Skills below are hidden from the white agents
report_results_skill = AgentSkill(
    id="report_results",
    name="Report Results",
    description="Returns the current benchmarking results. Hidden to white agents.",
    tags=["green agent", "report results", "extended"],
)

# Extended (hidden) agent card
extended_agent_card = agent_card.model_copy(
    update={
        "name": "Coding Evaluation Agent - Extended",
        "skills": [
            register_skill,
            distribute_problem_skill,
            process_answer_skill,
            report_results_skill,
        ],
    }
)
